### ISSUE TITLE
Firefox 支持

### ISSUE THREAD

**Issue by Rictusempra** [crimx/ext-saladict#10]
可同样使用 WebExtension 完成，参见 https://developer.mozilla.org/en-US/Add-ons/WebExtensions

**Comment by crimx** [comment]
这个工作量并不少，坑比较多，一些针对 Chrome 的设计也要修改。维护两套系统有点吃不消，只能看有没有 ff 发烧友愿意接盘了。

**Comment by midpoint** [comment]
挺好用的，等待 firefox 版

**Comment by god891006** [comment]
非常希望有firefox版

**Comment by YinlinHu** [comment]
Firefox too.

**Comment by kaigedong** [comment]
Star 等Firefox

**Comment by crimx** [comment]
[新版](https://github.com/crimx/ext-saladict/wiki/Saladict6)已支持，如有问题欢迎开新 issue 反馈。
