### ISSUE TITLE
反馈窗口无法显示的bug

### ISSUE THREAD

**Issue by kingofotaku** [crimx/ext-saladict#100]
- 平台：Chrome Canary 68.0.3418.2 on Windows 10

- 类型：一个bug

- 重现：
![ytedx7yp3 1ouk3fa6 m0nh1](https://user-images.githubusercontent.com/12953574/39615262-d32ad4c4-4fa7-11e8-85a3-dd5b12b3b400.png)

- 期待：修复bug

- 实际：(https://cn.engadget.com)   下所有文章的文本区及评论区划词都会出现截图里的情况

- 额外信息：另外提个建议，能否考虑增加搜狗翻译？

**Comment by crimx** [comment]
谢谢反馈！这应该是 Canary 的问题，具体问题未知。Canary 其实不适合日常使用，如果以后稳定版有问题再考虑修复。
