### ISSUE TITLE
独立窗口查词面板是否可以钉住，在最前端显示

### ISSUE THREAD

**Issue by sknin** [crimx/ext-saladict#1000]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: []

**Comment by crimx** [comment]
见[常见问题与答复](https://saladict.crimx.com/q&a.html#%E9%97%AE%EF%BC%9A%E7%8B%AC%E7%AB%8B%E7%AA%97%E5%8F%A3%E6%9F%A5%E8%AF%8D%E9%9D%A2%E6%9D%BF%E8%83%BD%E5%90%A6%E9%92%89%E4%BD%8F%E7%BD%AE%E9%A1%B6%EF%BC%9F)。
