### ISSUE TITLE
彩云小译网页翻译 无法关闭

### ISSUE THREAD

**Issue by FrontendStack** [crimx/ext-saladict#1002]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Chrome 版本 85.0.4183.102（正式版本） （64 位）]
- 沙拉查词版本: [v7.17.0] 

## 描述问题

1. 沙拉查词设置--右键菜单 关闭“彩云小译网页翻译”
2.过一段时间（昨天上午关闭下午又出现了，昨天下午关闭，今天早上又出现了）右键菜单又出现“彩云小译网页翻译”。

**Comment by ahaha-vip** [comment]
同样的问题。以前点击右上角会出现翻译弹窗，现在不知为何出不来，反而会出现彩云小译，火力全开。

系统：win10
浏览器：chrome 85.0.4183.83

**Comment by crimx** [comment]
你是在新浏览器上安装的么？在设置「右上弹框」中设置。

**Comment by ahaha-vip** [comment]
> 同样的问题。以前点击右上角插件图标会出现翻译弹窗，现在不知为何出不来，反而会出现彩云小译，火力全开。
> 
> 系统：win10
> 浏览器：chrome 85.0.4183.83
> 沙拉：7.17.0

@crimx 谢谢，我的问题已解决，在设置「右上弹框」中设置即可，新版的「右上弹框」默认是彩云小译，以前貌似是查词面板。另外彩云小译没找到明显的关闭入口，但是还挺好用的。

**Comment by crimx** [comment]
> 另外彩云小译没找到明显的关闭入口，但是还挺好用的

彩云小译不用就是关闭的。

**Comment by FrontendStack** [comment]
我试着关闭了，但是不知道什么情况又自己打开了。死循环。

**Comment by crimx** [comment]
> 我试着关闭了

你试了什么方式关闭。

> 但是不知道什么情况又自己打开了

自己打开是什么意思？

建议重新编辑一楼，填写模板描述问题。

**Comment by FrontendStack** [comment]
已编辑

**Comment by crimx** [comment]
> 1. 沙拉查词设置--右键菜单 关闭“彩云小译网页翻译”
> 2. 过一段时间（昨天上午关闭下午又出现了，昨天下午关闭，今天早上又出现了）右键菜单又出现“彩云小译网页翻译”。

这个有点奇怪。出现前有无重置过设置？其它设置修改后会不会重新恢复？

我这边关闭了，目前还没有这个现象。过段时间再看看。

**Comment by crimx** [comment]
经过 23 小时测试，目前右键菜单中没有自动出现「彩云小译网页翻译」。

**Comment by FrontendStack** [comment]
> 经过 23 小时测试，目前右键菜单中没有自动出现「彩云小译网页翻译」。

好的，我再试试

**Comment by crimx** [comment]
测试6天，依然没有复现问题。你看看是什么原因。

**Comment by Pearlulu** [comment]
> 经过 23 小时测试，目前右键菜单中没有自动出现「彩云小译网页翻译」。
每次更新后，彩云小译就会跑右键菜单里，自从有彩云小译就一直有这BUG。我只想留一个沙拉查词在右键菜单里，留两个每次都要多点一下，头疼了几个月。

**Comment by crimx** [comment]
好的我有空再看看
