### ISSUE TITLE
必应和有道翻译这两个是不是出啥bug了，今天用90%都翻译不出来。不知道什么问题

### ISSUE THREAD

**Issue by Clerlove** [crimx/ext-saladict#1004]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Chrome85] 
- 沙拉查词版本: [] 

## 截图

![image](https://user-images.githubusercontent.com/71173084/92992750-c9ffd780-f51f-11ea-8396-a2d3efe0ed55.png)
![image](https://user-images.githubusercontent.com/71173084/92992752-cf5d2200-f51f-11ea-8f1d-6d5cb3c460c7.png)

**Comment by crimx** [comment]
这边测试没有问题。请点击相应词典的标题看能否打开官网。
