### ISSUE TITLE
Add "Open Dict Definition in New Tab" Button

### ISSUE THREAD

**Issue by tddschn** [crimx/ext-saladict#1006]
**Is your feature request related to a problem? Please describe.**

I had Wikipedia enabled as a dictionary and it works great.
But sometimes the Wikipedia article is quite long and have images embedded in them, and I want to be able to view the Wikipedia page in a new tab, i.e., open the Wikipedia URL in the new tab. 

**Describe the solution you'd like**

It would be great if there's a button in the pop-up dict that allow me to do just that! :) 

**Describe alternatives you've considered**

- Allow user to resize the pop-up dict panel to view long Wikipedia pages or word definitions more easily
- Auto resize the pop-up dict panel to fit the dict contents.

**Additional context**

**Comment by crimx** [comment]
> open the Wikipedia URL in the new tab.

Just click the dictionary title.

> Allow user to resize the pop-up dict panel to view long Wikipedia pages or word definitions more easily

Saladict Settings(Options) -> Dictionaries -> Edit Wikipedia -> Default Panel Height

> Auto resize the pop-up dict panel to fit the dict contents.

By pop-up dict you mean the browser action panel(when clicking the saladict icon next to the address bar)? That is not adjustable at the moment. An option for this will be added in the next release.

**Comment by tddschn** [comment]
Thank you for the quick reply!

By "pop-up" I mean the panel that pops up when user moves focus on the Saladict icon next to the selected text.

It's great that the feature I need is already implemented. I'll close the issue. :)
