### ISSUE TITLE
Add full English support for COBUILD and Bing Dict interfaces

### ISSUE THREAD

**Issue by tddschn** [crimx/ext-saladict#1007]
**Is your feature request related to a problem? Please describe.**

In an en-US environment, COBUILD and Bing Dict's interfaces have some elements that are in Mandarin like "不可数名词".
It would be more friendly to English speakers if the interfaces of English dictionaries are shown in full English if the browser's language is set to English

**Describe the solution you'd like**

Display the dicts in English if the browser's language is set to English.

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/45612704/93018191-88932900-f600-11ea-853e-2c13f3cad1a0.png)

**Comment by crimx** [comment]
Saladict Settings(Options) -> Dictionaries -> Edit COBUILD -> Turn off "Prefer bilingual dictionary"

**Comment by crimx** [comment]
> Display the dicts in English if the browser's language is set to English.

Thanks for the feedback!

**Comment by tddschn** [comment]
Thanks for the quick reply! COBUILD is working perfectly for me now. :P
