### ISSUE TITLE
建议pdf可以修改背景色

### ISSUE THREAD

**Issue by colinkk** [crimx/ext-saladict#1009]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [360极速12.0.1502.0] 
- 沙拉查词版本: [v7.17.0] 

## 请描述目前使用沙拉查词遇到什么不便

网页背景色可以更改，但是pdf文件的不变。

## 理想情况下，沙拉查词应该怎么做

pdf文件的背景色也和网页的一样。

**Comment by crimx** [comment]
请阅读[常见问题及答复](https://saladict.crimx.com/q&a.html)。
