### ISSUE TITLE
搜狗翻译修改账号后无法翻译

### ISSUE THREAD

**Issue by hqyyqh** [crimx/ext-saladict#1011]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome85] 
- 沙拉查词版本: [v7.17.0] 

## 描述问题

搜狗翻译在修改词典账号后无法翻译，没有结果。
![image](https://user-images.githubusercontent.com/38676455/93408283-c6c16e80-f8c6-11ea-9c18-dfab818592ff.png)

## 复现步骤

1. 以项目主页 https://github.com/crimx/ext-saladict 为例，原始的搜狗翻译中我设置了 `pid` 和 `key`，可以正常使用。

> 原始未修改设置截图
>
> ![image](https://user-images.githubusercontent.com/38676455/93408430-143ddb80-f8c7-11ea-9f7f-a0a41de78262.png)
> 
> 翻译正常
>
> ![image](https://user-images.githubusercontent.com/38676455/93408454-2d468c80-f8c7-11ea-9b65-33ab4e9551d7.png)

2. 删除自定义的词典账号，点击`保存`。如果此时未刷新 https://github.com/crimx/ext-saladict 则搜狗翻译可以正常使用，按下Ctrl强制刷新页面后翻译无结果。

> 删除自定义账号截图
>
> ![image](https://user-images.githubusercontent.com/38676455/93408662-b231a600-f8c7-11ea-8698-1ed170e2acdf.png)
>
> 翻译无结果
>
> ![image](https://user-images.githubusercontent.com/38676455/93408654-ad6cf200-f8c7-11ea-877b-1b7c15f4ad34.png)

3. 重新填回 `pid` 和 `key`，按下Ctrl强制刷新 https://github.com/crimx/ext-saladict 翻译无结果

> 填回自定义账号截图
>
> ![image](https://user-images.githubusercontent.com/38676455/93408796-050b5d80-f8c8-11ea-986e-f172c01f184a.png)
>
> 翻译无结果
>
> ![image](https://user-images.githubusercontent.com/38676455/93408800-063c8a80-f8c8-11ea-9355-d4d3fac79975.png)

## 期待的正常行为

搜狗翻译在修改配置后能够正常使用。

**Comment by crimx** [comment]
打开 http://fanyi.sogou.com/ 看看是不是被误判成机器人，输入验证码后看可以不。

看来我要更新一下。

**Comment by hqyyqh** [comment]
输入验证码之后正常了，赞d=====(￣▽￣*)b
