### ISSUE TITLE
动画过渡功能无法关闭？

### ISSUE THREAD

**Issue by ArnoYe** [crimx/ext-saladict#1013]
## 设备信息
- Mac 10.12.3
- 版本 85.0.4183.102（正式版本）
- v7.17.0

## 描述问题
关闭"开启动画过渡"不起作用。

## 截图

![image](https://user-images.githubusercontent.com/9108645/93467413-4a5b7980-f920-11ea-8277-662673c69a39.png)

![image](https://user-images.githubusercontent.com/9108645/93467385-429bd500-f920-11ea-90f9-e24fcc1c1760.png)

**Comment by ArnoYe** [comment]
![image](https://user-images.githubusercontent.com/9108645/93467274-1bdd9e80-f920-11ea-848c-903cfe8b570e.png)
![image](https://user-images.githubusercontent.com/9108645/93467303-25ff9d00-f920-11ea-8e65-c8aed8d1a0f3.png)

**Comment by crimx** [comment]
你好，从静态截图上看不出动画过渡？

**Comment by ArnoYe** [comment]
我认为关闭“开启动画过渡”，双击单词时不会出现
沙拉图标，应该是直接显示翻译结果，但是我关闭了，还是会出现这个图标？

**Comment by crimx** [comment]
动画过渡关闭的是动画过渡效果（动起来的顺滑度）。图标在「查词习惯」-「普通模式」中设置。
