### ISSUE TITLE
在 JAVA API 文档：https://docs.oracle.com/javase/7/docs/api/上不支持翻译

### ISSUE THREAD

**Issue by liuhao326** [crimx/ext-saladict#1014]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Chrome85] 
- 沙拉查词版本: [v7.17.0] 

## 请描述目前使用沙拉查词遇到什么不便

发现沙拉单词不支持在<https://docs.oracle.com/javase/7/docs/api/>上进行划词翻译，具体是指在该网站上选中文本后不弹出翻译图标，此时沙拉单词插件图标显示为灰色表示不支持在该网站上进行划词翻译。

## 理想情况下，沙拉查词应该怎么做

理想情况下，沙拉单词将会在选中文本之后弹出图标，点击图标可翻译选中文本。

**Comment by crimx** [comment]
请阅读[常见问题及答复](https://saladict.crimx.com/q&a.html)。
