### ISSUE TITLE
Feature request: translation based on speech recognition.

### ISSUE THREAD

**Issue by hongyi-zhao** [crimx/ext-saladict#1016]
Hi,

Can saladict support the Translation based on speech recognition?

Regards,
HY

**Comment by crimx** [comment]
Hi please fill in the feature request issue template.

**Comment by hongyi-zhao** [comment]
If you have understand the problem, there is really no need to do more job.

**Comment by crimx** [comment]
Hi,

> If you have understood the problem, there is really no need to do more job.

I know what you need, but I also need more information about the reason you need it in order to examine the benifit of it. Saladict is mainly a personal side project, I don't have much time to investigate every requirement personally.

> Personally, I don't like to repeat what the book says, but make the achieve-the-purpose of communication or problem-solving at highest priority.

Issue template is made purposely for the sake of clearity and time saving without falling into a back-and-forth routine conversation.

**Comment by hongyi-zhao** [comment]
To be simple, I want to let saladict capture the speech input from the sound input, say, from microphone, and then do the transaltion.

**Comment by crimx** [comment]
Can you leverage input methods that support speech recognition? Combined with Saladict's [global shortcuts](https://saladict.crimx.com/en/native.html) I think it's possible to achieve the desired result.

**Comment by hongyi-zhao** [comment]
I'm on Linux and really not learned any input method that support speech recognition.

**Comment by crimx** [comment]
> I'm on Linux and really not learned any input method that support speech recognition.

Here are a few [tools](https://en.wikipedia.org/wiki/Speech_recognition_software_for_Linux) to get you started. [AUR](https://aur.archlinux.org/packages/?O=0&K=speech+recognition) if on Arch.

I need more convincing use case that shows such feature is worth implementing.

**Comment by hongyi-zhao** [comment]
BTW, maybe the machine learning based solutions are also wonderful candidates.
