### ISSUE TITLE
开放API给命令行

### ISSUE THREAD

**Issue by kevinhwang91** [crimx/ext-saladict#1017]
## 设备信息
- 操作系统: [ArchLinux] 
- 浏览器版本: [Version 85.0.4183.102 (Official Build) Arch Linux (64-bit)] 
- 沙拉查词版本: [v7.17.0] 

## 请描述目前使用沙拉查词遇到什么不便

经常终端里面使用命令行(Linux用户的无奈)，有时候翻译会在命令行里面，这就用不到沙拉了。

为什么想要沙拉提供api让命令调用呢？我经常用谷歌翻译，在国内的延时大家都懂的。
1. 依赖浏览器的缓存DNS，加速；
2. 依赖浏览器的TCP复用，因为建立连接是非常耗时的；
3. 用其他的翻译命令行，都是无法复用TCP的，那种体验是非常难受的；

虽然这听起来听滑稽的，从终端切到浏览器再按三下ctrl就能激活沙拉窗口，但是让终端用户体验差了一截。

## 理想情况下，沙拉查词应该怎么做

在已有沙拉词典的基础上，开一个端口和开发api，让命令行接收结果。

**Comment by kevinhwang91** [comment]
举一个例子，用https://github.com/soimort/translate-shell 调用谷歌翻译https://translate.google.com/，每次大概都是1-3s间。而用web或者沙拉，只会在第一次延时较高，短时间内每次翻译在300ms左右。

**Comment by crimx** [comment]
因为终端支持需要在本地额外配置（[Chrome](https://developer.chrome.com/extensions/nativeMessaging), [Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging)），我目前还没时间了解怎么实现，如果你能对接请告知。

目前可以参考[浏览器外划词](https://saladict.crimx.com/native.html)的方法，配置全局快捷键，通过脚本触发。

**Comment by kevinhwang91** [comment]
原来应该是开发一个端口就可以， 我未接触过浏览器相关的编程。
可以参考 https://github.com/voldikss/coc-browser ，同样是利用浏览器的插件开端口，命令行应用vim调用。纯ts的技术栈了。

**Comment by crimx** [comment]
这个 coc-browser 是开了个本地服务器，扩展通过 https 请求传送数据。沙拉应该会通过浏览器原声接口实现，资源占用会低一些。

**Comment by kevinhwang91** [comment]
抱歉，我想了想还是觉得这样耦合大了，最好的方式应该是用proxy解决延时的问题。打扰你，实在抱歉。
