### ISSUE TITLE
weblio辞書，查询某些汉字词时无结果

### ISSUE THREAD

**Issue by smartsl** [crimx/ext-saladict#1018]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [ALL] 
- 沙拉查词版本: [v7.17.0] 

## 描述问题

weblio辞書，查询某些汉字词时无结果，例如查询【主催】等等，点击到网站打开可以看到是一类不同的页面格式，故旧解析脚本无法识别。

## 复现步骤

词典设置中选择weblio，然后查询这个词：【主催】，发现weblio的结果中为空白。

## 期待的正常行为

应该显示其释义，正如在weblio的网站中查询这个词一样

## 截图

略

## 额外信息

这个问题与使用哪个浏览器无关，而是与weblio网站的一类新格式相关。碰到的频率还是比较高的，暂时只有这个词示例，如果需要，我会搜集补充更多的词

**Comment by crimx** [comment]
确实部分页面采用了新版的界面。感谢反馈。
