### ISSUE TITLE
独立窗口在浏览器外无法使用划词查询

### ISSUE THREAD

**Issue by garpy-stu** [crimx/ext-saladict#1019]
在浏览器外使用划词查询时，会打开独立窗口界面，但是不会读取划选的单词并进行查询。

**Comment by crimx** [comment]
有两个打开窗口的快捷键，看看你设置的快捷键是否为查询剪贴板的。

**Comment by garpy-stu** [comment]
您说的是

快捷查词”配置快捷查词
可选择预先加载的来源，“剪贴板”、“页面划词”从当前页面上获取单词或者“无”不预载；
这部分吧。
我三个选项都试过了，没能解决问题，独立窗口在浏览器外依然无法使用划词查询。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CRIMX"<notifications@github.com&gt;; 
发送时间: 2020年9月24日(星期四) 上午8:56
收件人: "crimx/ext-saladict"<ext-saladict@noreply.github.com&gt;; 
抄送: "Garfield_P"<garfield_p@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [crimx/ext-saladict] 独立窗口在浏览器外无法使用划词查询 (#1019)





 
有两个打开窗口的快捷键，看看你设置的快捷键是否为查询剪贴板的。

**Comment by crimx** [comment]
不是，在浏览器快捷键设置中，沙拉查词提供了两个快捷键。一个是「打开独立词典窗口」，另一个是「在独立窗口中搜索剪贴板内容」。

**Comment by crimx** [comment]
如不知道位置见[说明](https://saladict.crimx.com/manual.html#shortcuts)。

**Comment by DaveBoy** [comment]
@crimx 如你所说，我改成了「打开独立词典窗口」，但是并只打开并不预加载外部的划词内容了，请问一下可能是什么原因呢。
快捷查词--》预先加载  我设置的页面划词。为什么无法获取到我其他软件里面的页面划词呢。当我设置成粘贴板预先加载就正常了，只有页面划词项没有预先加载任何内容

**Comment by crimx** [comment]
> 为什么无法获取到我其他软件里面的页面划词呢

因为沙拉查词是运行在浏览器中的。其它软件的文字目前是通过剪贴板传送到沙拉查词中。原理可以见 https://saladict.crimx.com/native.html 。

**Comment by DaveBoy** [comment]
> > 为什么无法获取到我其他软件里面的页面划词呢
> 
> 因为沙拉查词是运行在浏览器中的。其它软件的文字目前是通过剪贴板传送到沙拉查词中。原理可以见 https://saladict.crimx.com/native.html 。

所以目前在浏览器外部无法通过划词进行翻译是吗？即使我打开了“写入剪贴板”权限。

**Comment by crimx** [comment]
可以的，可以用快捷键或配合其它插件，见上面的链接。
