### ISSUE TITLE
[建议]希望能将生词导出为 anki 卡牌

### ISSUE THREAD

**Issue by pessoalzy** [crimx/ext-saladict#102]
希望能将生词或查词记录导出为 anki 卡牌，类似[这个](https://zhuanlan.zhihu.com/p/22472893?refer=-anki)（https://zhuanlan.zhihu.com/p/22472893?refer=-anki） 和 [这个](https://zhuanlan.zhihu.com/p/26522832)(https://zhuanlan.zhihu.com/p/26522832)。
现在只能简单导出为 txt 文件，希望能增加结合指定词典翻译导出为 anki 卡片的功能。来完成进一步的记忆。
目前我似乎找不到什么好的办法来把 txt 文件里的单词批量生成 anki 卡片， kindle 生词本里的单词但是有办法。

**Comment by crimx** [comment]
Anki 导入文本很简单的，`文件` -> `导入` -> `按 Tab 或者分号分割的文本`。建议模板用 <kbd>`</kbd> 分割不容易冲突。且 Anki 会自动识别重复的。

专门整合 Anki 需要精力分析，我近期是没有时间实现了。你分享的我也了解过，整个流程还不是很流畅。我还是保持现有的通用方案。

**Comment by pessoalzy** [comment]
多谢！是我冒昧了。感谢你抽出时间回复！
