### ISSUE TITLE
当前 Saladict 的新版 PDF 阅读器文字渲染要比 Chrome 自带的模糊

### ISSUE THREAD

**Issue by Triple-Z** [crimx/ext-saladict#1021]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome 85] 
- 沙拉查词版本: [v7.17.0] 

## 描述问题

使用 Saladict 的 PDF 阅读器打开 PDF 文档，和使用 Chrome 打开该 PDF 文档。Chrome 的阅读器字体渲染要比 Saladict 使用的 PDF 阅读器要清晰。Saladict 的阅读器字体有些模糊。

## 复现步骤

1. 用 Saladict 插件打开一个 PDF 文档（双栏，论文格式）
2. 用 Chrome 打开同 PDF 文档
3. 比较两者字体清晰程度
4. 问题出现

## 期待的正常行为

Saladict 的 PDF 字体渲染形式应该与 Chrome 自带的阅读器一致。

**Comment by crimx** [comment]
沙拉查词保持使用最新 PDF.js 阅读器，相关问题可以前往[该项目](https://github.com/mozilla/pdf.js/issues)反馈。相关问题见[常见问题及答复](https://saladict.crimx.com/q&a.html#%E9%97%AE%EF%BC%9A%E5%8F%AF%E4%B8%8D%E5%8F%AF%E4%BB%A5%E5%A2%9E%E5%8A%A0-pdf-%E9%98%85%E8%AF%BB%E5%99%A8%E5%8A%9F%E8%83%BD%EF%BC%8C%E5%A6%82%E5%81%9A%E7%AC%94%E8%AE%B0%E3%80%81%E5%88%92%E7%BA%BF%E6%A0%87%E8%AE%B0%E3%80%81%E5%A4%9C%E9%97%B4%E6%A8%A1%E5%BC%8F%E7%AD%89%E3%80%82)。
