### ISSUE TITLE
Invoke the saladict recursively.

### ISSUE THREAD

**Issue by hongyi-zhao** [crimx/ext-saladict#1022]
Hi,

Say, when I select some words on the already appeared saladict, the saladict **will not** invoke itself again, i.e., invoking the saladict recursively, for doing the translation. 

When I select the word **Spare**, the  saladict won't be invoked again for this word. See the following screenshot for more info

![image](https://user-images.githubusercontent.com/11155854/94130059-bb55e080-fe8e-11ea-9564-11fa82fb7793.png)

Can this feature be added into saladict?

Regards,
HY

**Comment by crimx** [comment]
Saladict options - Search Modes - Inside Dict Panel

**Comment by hongyi-zhao** [comment]
Very good, got it. Thanks a lot.
