### ISSUE TITLE
Document enhancement: "Read Clipboard" is needed by "Works Outside of Browser".

### ISSUE THREAD

**Issue by hongyi-zhao** [crimx/ext-saladict#1023]
Hi,

I noticed the document for "Works Outside of Browser" [here](https://saladict.crimx.com/en/native.html), and it seems that the "Read Clipboard" option need to be enabled for this capability. But the instructions given there don't include this step.

Regards,
HY

**Comment by crimx** [comment]
The Clipboard permissions were made optional in recent versions. Thanks for the input!
