### ISSUE TITLE
最近使用沙拉查词发现识别错误，它会把find这类，前面有fi多识别一次，识别结果是fifind或firm——fifirm

### ISSUE THREAD

**Issue by Destiny057** [crimx/ext-saladict#1026]
设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome85.0.4183.121（正式版本） （64 位）] 
- 沙拉查词版本: [v7.17.0] 

描述问题
<最近使用沙拉查词发现识别错误，它会把find这类，前面有fi多识别一次，识别结果是fifind或firm——fifirm>

复现步骤
<

1. 打开quicker上的沙拉查词
2. 使用划词翻译
3. 鼠标划动到find和firm这类单词时
4. 沙拉查词的独立查词窗口里面的英文原文识别结果是fifind或firm——fifirm
>

期待的正常行为
<能把这些单词识别错误原因找到并修正>

 截图
<!-- 可选，需要情况下，可借助截图描述问题 --
![image](https://user-images.githubusercontent.com/72026115/94439871-8968b500-01d3-11eb-9008-53bae1709602.png)
，
![image](https://user-images.githubusercontent.com/72026115/94439945-a43b2980-01d3-11eb-80db-6e1316457034.png)
>

**Comment by crimx** [comment]
是用了 OCR 还是在 PDF 上划词了？前者因不同图像识别算法的局限性会产生误差，后者不同 PDF 工具生成的 PDF 会出现不同程度的语义丢失，见[常见问题及答复](https://saladict.crimx.com/q&a.html#%E9%97%AE%3A-pdf-%E5%88%92%E8%AF%8D%E5%AD%97%E7%AC%A6%E6%98%BE%E7%A4%BA%E4%B8%8D%E5%AF%B9%EF%BC%88%E5%A6%82-f-%E4%B8%8E-%C6%92%EF%BC%89%2F-pdf-%E5%88%92%E8%AF%8D%E6%8D%A2%E8%A1%8C%E7%9A%84%E5%8D%95%E8%AF%8D%E7%B2%98%E8%BF%9E%E5%9C%A8%E4%B8%80%E8%B5%B7%E3%80%82)。

**Comment by hqyyqh** [comment]
动作会替换LaTeX生成的PDF中的 `ﬃ`, `ﬁ` 等连字，以保证单词的准确性，目前使用中没有遇到异常的情况。

建议更换一个文档或者PDF阅读器测试一下。
