### ISSUE TITLE
希望加入谷歌医学翻译引擎

### ISSUE THREAD

**Issue by bio-er** [crimx/ext-saladict#1028]
## 设备信息
- 操作系统: [win10] 
- 浏览器版本: [] 
- 沙拉查词版本: [7.17] 

## 请描述目前使用沙拉查词遇到什么不便
加入谷歌医学翻译引擎，适合科研文献翻译，更加准确。

**Comment by crimx** [comment]
你好，据我所知，谷歌没有医学翻译引擎，这貌似是一个叫「知云文献翻译」软件自建的服务器。
