### ISSUE TITLE
同步到anki中显示模板希望正面单词，背面直接就是该单词的翻译

### ISSUE THREAD

**Issue by SEEYOU20** [crimx/ext-saladict#1029]
同步到anki中显示模板希望正面单词，然后单词底下是该单词上下文
背面直接就是该单词的翻译，底下是该单词上下文及翻译，

**Comment by crimx** [comment]
Anki 的模板可以自行调整。沙拉查词只会在初次连接生成一个默认的模板。

**Comment by yyang755** [comment]
该怎么调整呀。只能手动复制吗
