### ISSUE TITLE
[建议]希望增加分辨单词和长句并相应调整词典顺序的功能

### ISSUE THREAD

**Issue by pessoalzy** [crimx/ext-saladict#103]
请问能不能增添识别划词划的是单词还是句子的功能呢？
我在使用沙拉查词的过程中，一般是用于查单个的词，或是句子的翻译。从实际体验和评价及口碑中，大概都足以得出谷歌翻译翻句子更好，而必应词典查词更好的结论。
但是目前沙拉查词的弹框中，不同词典的顺序是固定的。如果能够在划选中单词的时候，必应词典排在第一位，谷歌翻译排在其后。在划选中句子的时候，谷歌翻译排在第一位，必应变到其后。这样的话大概能进一步提升一点大家的使用体验。
另外，如果能在查词历史记录界面一键剔除句子或词组，保留单词，方便导出单词进行进一步整理，就更好了。
多谢！

**Comment by crimx** [comment]
嗨，谢谢建议！

1. 词典顺序变化。我会考虑加入一个智能排序功能，按查词的长度调整。
2. 这个功能相对私人化，文本处理已经有很多优秀的工具，各大编辑器都能很好处理这个问题，我就不重复劳动了。

**Comment by crimx** [comment]
对了，忘了提一下，因为 6 使用了新的框架，剔除句子变得很简单，所以 6 中会加入这个功能的 :tada: 。
