### ISSUE TITLE
Saladict7.17.0版本为何无法设置全局快捷键

### ISSUE THREAD

**Issue by KK-3458** [crimx/ext-saladict#1030]
## Device info
 - OS:  Window10
 - Browser Version： 版本 85.0.4183.121（正式版本） （64 位）
 - Saladict Version 7.17.0

## Describe the bug

想要实现浏览器外划词，突然发现没办法设置全局的快捷键（所有功能都没有全局快捷键实现方式）
想问问是最新版改成这个样子了吗？还是我漏掉哪一个步骤呢？

## Expected behavior

希望能实现浏览器外划词！！拜托拜托~~

## Screenshots

![image](https://user-images.githubusercontent.com/66560506/94984350-aa3b5c80-057d-11eb-8f7e-5daa3e1a49d5.png)

![image](https://user-images.githubusercontent.com/66560506/94984342-9abc1380-057d-11eb-87bd-5e9fd106ba53.png)

**Comment by crimx** [comment]
> Browser Version： 版本 85.0.4183.121（正式版本） （64 位）

这是 Chrome 浏览器么？是不是最近更新了？尝试重启系统试试。

**Comment by KK-3458** [comment]
![image](https://user-images.githubusercontent.com/66560506/94984404-32216680-057e-11eb-9832-c79f50b91621.png)
是最新版的Chrome浏览器来着的
重启了，但是还是那样？？

**Comment by KK-3458** [comment]
你说的重启电脑是吧？😂

**Comment by KK-3458** [comment]
浏览器重启，电脑重启也是无法解决，还是跟原来一样，设置不了全局快捷键😥
![image](https://user-images.githubusercontent.com/66560506/94984531-8b3dca00-057f-11eb-9a19-93b5e840e30e.png)

**Comment by crimx** [comment]
我的也是同个版本，是可以正常设置的。你要先设置了快捷键才能选择全局。是不是因为这个先后次序的问题？

**Comment by KK-3458** [comment]
哦！真的是这个先后次序问题😅多谢解答😝
