### ISSUE TITLE
剑桥词典增加搜索建议

### ISSUE THREAD

**Issue by zzan1** [crimx/ext-saladict#1031]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [EDGE ] 
- 沙拉查词版本: [7.17.0] 

## 请描述目前使用沙拉查词遇到什么不便

对于有些单词有变形，比如过去式，复数这些，剑桥词典的搜索结果为空。

能否增加支持，对于剑桥词典搜索引擎的建议，匹配最近的结果，返回相应的搜索结果。
![image](https://user-images.githubusercontent.com/47623989/94986416-255a3e00-0591-11eb-9cb4-7bfa24de76bf.png)

**Comment by crimx** [comment]
> 对于有些单词有变形，比如过去式，复数这些，剑桥词典的搜索结果为空

dictionary 的复数是 dictionaries 不是 dictionarys。但我会考虑把剑桥词典这个页面添加进去。目前你可以通过必应词典或有道词典等查看纠正结果。

**Comment by zzan1** [comment]
好的 感谢至极
