### ISSUE TITLE
建议增加查词面板自动展开功能

### ISSUE THREAD

**Issue by Quantum-Zhao** [crimx/ext-saladict#1033]
## 设备信息
- 操作系统: [MacOS] 
- 浏览器版本: [Chrome 85.0.4183.121（正式版本）] 
- 沙拉查词版本: [v7.17.0] 

## 请描述目前使用沙拉查词遇到什么不便

每次查词只有简单释义，如果想看例句等更详细的内容就要手动点箭头展开。

## 理想情况下，沙拉查词应该怎么做

希望设置里能增加面板自动展开的功能。

**Comment by crimx** [comment]
每个词典均可设置默认高度，在设置词典管理，词典列表中点击相应词典的编辑按钮。

**Comment by Quantum-Zhao** [comment]
解决了，抱歉没注意到词典设置。
