### ISSUE TITLE
生词本的翻译来源词典增加

### ISSUE THREAD

**Issue by iamakitty** [crimx/ext-saladict#1034]
## 设备信息
- 操作系统: [window10] 
- 浏览器版本: [chrome 85.0.4183.121] 
- 沙拉查词版本: [v7.17.0] 

## 请描述目前使用沙拉查词遇到什么不便

1）添加生词后默认采纳的翻译词典只有谷歌、百度、有道和彩云等6个词典，无法选择柯林斯高阶、必应等更加准确的词典来源
2）每次查词都需要重新选择自己偏好的词典翻译
3）单词仅有中文翻译，无词性标志（如adj., v., adv.等）

## 理想情况下，沙拉查词应该怎么做

1）将查词时可选择的词典纳入翻译结果的选项
2）允许设置默认翻译结果的词典来源
3）单词翻译前添加词性标志

## 额外信息

没有了，刚发现这个好用的app，感谢开发者~~

**Comment by crimx** [comment]
见[常见问题及答复](https://saladict.crimx.com/q&a.html#%E9%97%AE%EF%BC%9A%E6%B7%BB%E5%8A%A0%E7%94%9F%E8%AF%8D%E5%8F%AF%E4%B8%8D%E5%8F%AF%E4%BB%A5%E5%8A%A0%E5%85%A5%E5%8D%95%E8%AF%8D%E7%BF%BB%E8%AF%91%EF%BC%88%E8%80%8C%E4%B8%8D%E6%98%AF%E7%BF%BB%E8%AF%91%E6%95%B4%E5%8F%A5%E4%B8%8A%E4%B8%8B%E6%96%87%EF%BC%89%E3%80%82)。
