### ISSUE TITLE
Open dict definition page in new tab without switching to that tab with ctrl-click

### ISSUE THREAD

**Issue by tddschn** [crimx/ext-saladict#1035]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/45612704/95058849-adc01680-072a-11eb-9178-bf24244e4633.png)

When I cmd+clicked (or ctrl-click) on COBUILD, I was taken to a new tab. 

I wish I could open the new tab behind the current one without switching to it. 

**Describe the solution you'd like**

Saladict opens a new tab behind the current one without switching to it when I cmd-click / ctrl-click on the dict name like "COBUILD", just as how Google Chrome works with hyperlinks in a web page when you cmd-click / ctrl-click on them.

**Describe alternatives you've considered**

Maybe make it a optional feature that can be turned off in the settings?

**Additional context**

**Comment by crimx** [comment]
Will be added in the upcoming version.
