### ISSUE TITLE
在pdf中滑译选中的颜色对比度太低，看不清楚

### ISSUE THREAD

**Issue by surefish** [crimx/ext-saladict#1036]
希望能在pdf模式能调整划译选中的颜色，最好能自定义！感谢🙏

**Comment by crimx** [comment]
![image](https://user-images.githubusercontent.com/6882794/95341991-7c417980-08e9-11eb-9195-7cd1a1254b7d.png)

很清楚吧。请阅读[常见问题及答复](https://saladict.crimx.com/q&a.html#%E9%97%AE%EF%BC%9A%E5%8F%AF%E4%B8%8D%E5%8F%AF%E4%BB%A5%E5%A2%9E%E5%8A%A0-pdf-%E9%98%85%E8%AF%BB%E5%99%A8%E5%8A%9F%E8%83%BD%EF%BC%8C%E5%A6%82%E5%81%9A%E7%AC%94%E8%AE%B0%E3%80%81%E5%88%92%E7%BA%BF%E6%A0%87%E8%AE%B0%E3%80%81%E5%A4%9C%E9%97%B4%E6%A8%A1%E5%BC%8F%E7%AD%89%E3%80%82)。

**Comment by surefish** [comment]
https://github.com/mozilla/pdf.js/issues/12471
