### ISSUE TITLE
可以考虑添加到ONENOTE中吗

### ISSUE THREAD

**Issue by annexiao** [crimx/ext-saladict#1038]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 请描述目前使用沙拉查词遇到什么不便

我平常使用Onenote很多，觉得如果onenote中如果能使用沙拉的功能就好了

## 理想情况下，沙拉查词应该怎么做

像浏览器一样 可以右键点击然后查词

**Comment by crimx** [comment]
可以看看[浏览器外划词](https://saladict.crimx.com/native.html)。

**Comment by annexiao** [comment]
赞👍
