### ISSUE TITLE
右上角弹窗无法钉住置顶，钉住指定按钮一直灰色无法点击。

### ISSUE THREAD

**Issue by zhuyinqi** [crimx/ext-saladict#1039]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: []

**Comment by crimx** [comment]
那个是扩展的弹窗，不能钉住的，所以禁用了按钮，下个版本我直接去掉按钮以免引起误解。

**Comment by crimx** [comment]
你可以使用独立窗口的查词面板。https://saladict.crimx.com/manual.html#triple-ctrl

**Comment by zhuyinqi** [comment]
明白了，谢谢！~



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CRIMX"<notifications@github.com&gt;; 
发送时间: 2020年10月11日(星期天) 上午10:22
收件人: "crimx/ext-saladict"<ext-saladict@noreply.github.com&gt;; 
抄送: "Inch"<865810197@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [crimx/ext-saladict] 右上角弹窗无法钉住置顶，钉住指定按钮一直灰色无法点击。 (#1039)





 
那个是扩展的弹窗，不能钉住的，所以禁用了按钮，下个版本我直接去掉按钮以免引起误解。
