### ISSUE TITLE
highcharts图形区域单击会报错

### ISSUE THREAD

**Issue by kuake** [crimx/ext-saladict#104]
- 平台：包括操作系统和 Chrome 版本
chrome Version 65.0.3325.162 (Official Build) (64-bit)／ubuntu 16.04 LTS

- 类型：错误？
单击highcharts绘图区域必现bug：
`Uncaught TypeError: t.className.startsWith is not a function
    at HTMLDocument.<anonymous> (selection.js:formatted:644)`

- 重现：提供详细地操作来重现状况。
单击highcharts绘图区域必现

http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/members/chart-addseries/
可以在这里单击绘图区域

- 期待：理想情况下扩展应该怎么做？
`t.className.startsWith("saladict-")`这里应该判断下t.className是否string，在highcharts绘图区域t.className是一个SVGAnimatedString对象

- 实际：客观描述扩展实际上做了什么。

- 额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
这个其实是监听划词的 bug，不影响使用。SVG 元素的 `className` 不是 `string` ，6 使用全新的引擎，所以没有这个问题了。多谢反馈。
