### ISSUE TITLE
MOJI辞書中部分单词无法发音

### ISSUE THREAD

**Issue by smartsl** [crimx/ext-saladict#1042]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chromium内核Edge 86.0.622.38，Chrome 86.0.4240.75] 
- 沙拉查词版本: [v7.17.0] 

## 描述问题

查询部分单词时，如【教える】，发音是空白，在其网站上查看则发音正常。还有部分其他单词也有类似的问题，也有一些单词没有这个问题

## 复现步骤

在saladict里查询单词【教える】，找到MOJI辞書那一栏，点击单词后的🔈，会发现发音是空白的

## 期待的正常行为

应该与在MOJI的网站上一样能正常发音

## 截图

略

## 额外信息

虽然本贴是在反馈bug，不过还有2个小小的建议一并提出：
1）MOJI官网的CSS美观的多，要是能一致就好了
2）MOJI官网上，单词后的示例句子也能发音，要是能加上就好了。在例句中记单词效率会更高

**Comment by crimx** [comment]
MOJI 接口升级了，感谢反馈。
