### ISSUE TITLE
为啥沙拉查词查出的  单个单词的意思  却没有输出的字段？这个可以自定义吗

### ISSUE THREAD

**Issue by enron2014** [crimx/ext-saladict#1044]
输出的字段只有 整个句子的意思
却没有单个单词的意思

**Comment by crimx** [comment]
见[常见问题及答复](https://saladict.crimx.com/q&a.html#%E9%97%AE%EF%BC%9A%E6%B7%BB%E5%8A%A0%E7%94%9F%E8%AF%8D%E5%8F%AF%E4%B8%8D%E5%8F%AF%E4%BB%A5%E5%8A%A0%E5%85%A5%E5%8D%95%E8%AF%8D%E7%BF%BB%E8%AF%91%EF%BC%88%E8%80%8C%E4%B8%8D%E6%98%AF%E7%BF%BB%E8%AF%91%E6%95%B4%E5%8F%A5%E4%B8%8A%E4%B8%8B%E6%96%87%EF%BC%89%E3%80%82)。
