### ISSUE TITLE
浏览器外取词  好像是取不到上下文？

### ISSUE THREAD

**Issue by enron2014** [crimx/ext-saladict#1045]
![image](https://user-images.githubusercontent.com/38575961/95719030-da7fab00-0ca1-11eb-926f-3de24f0b69b3.png)

**Comment by crimx** [comment]
是的。见[使用说明](https://saladict.crimx.com/native.html)，沙拉查词只是通过剪贴板获取浏览器外的数据。上下文需要其它插件的支持才行，但各种程序环境复杂，这个应该很难实现。
