### ISSUE TITLE
输入发音

### ISSUE THREAD

**Issue by zz1616611** [crimx/ext-saladict#1046]
## 设备信息
- 操作系统: Window10 Enterprise N
- 浏览器版本:chromiun84
- 沙拉查词版本: v7.17.0

## 理想情况下，沙拉查词应该怎么做
朗读功能能够跟随光标朗读出打出来的内容，边听边打。TTS 朗读输入单词或句子。 输入空格 5秒后TTS朗读单词，输入空格15秒后朗读句子。这样可以纠正发音和加深记忆。 主要用于朗读chrome浏览器输入的内容。不知道是否可以调用我win10安装的TTS引擎？我使用的TTS是 Neospeech

**Comment by crimx** [comment]
你好，沙拉查词已经有许多机器翻译，切换到「翻译模式」即可同时浏览多个机器翻译结果，支持原文译文朗读。

对于朗读输入内容这个功能我认为已经超出了一个词典的范畴。如果我想朗读自己输入的内容我觉得应该会到单独的应用中使用，而不是边查词边朗读。
