### ISSUE TITLE
请问能否增加词根词缀词典

### ISSUE THREAD

**Issue by wtbsw** [crimx/ext-saladict#1048]
## 设备信息
- 操作系统: [MacOS] 
- 浏览器版本: [Chrome86] 
- 沙拉查词版本: [v7.0.1] 

## 请描述目前使用沙拉查词遇到什么不便
缺少增加词根词缀词典，无法查询单词的词根词缀

## 理想情况下，沙拉查词应该怎么做
增加词根词缀词典，方便知道词语的来源，更有利于理解单词

**Comment by crimx** [comment]
Etymonline 与 谷歌词典 都有词源。

**Comment by nanmao** [comment]
同样希望增加词根词缀词典.

## 能否在线加载词根词缀词典
例如"优词词源"、"英语词根词缀_YGYL"、"童哥词根".
## 或者能加载自定义mdx词典
<img width="535" alt="1" src="https://user-images.githubusercontent.com/26304888/96601475-a1d87500-1324-11eb-94ad-31e6dfe9a119.png">

## 或者增加有道词典"词源"模块
<img width="619" alt="2" src="https://user-images.githubusercontent.com/26304888/96601579-bddc1680-1324-11eb-99dc-7bd27d6b8fa4.png">

**Comment by TomIsFat** [comment]
> 
> 
> 同样希望增加词根词缀词典.
> ## 能否在线加载词根词缀词典
> 
> 例如"优词词源"、"英语词根词缀_YGYL"、"童哥词根".
> ## 或者能加载自定义mdx词典
> 
> <img alt="1" width="535" src="https://user-images.githubusercontent.com/26304888/96601475-a1d87500-1324-11eb-94ad-31e6dfe9a119.png">
> ## 或者增加有道词典"词源"模块
> 
> <img alt="2" width="619" src="https://user-images.githubusercontent.com/26304888/96601579-bddc1680-1324-11eb-99dc-7bd27d6b8fa4.png">

支持啊，沙拉里的网易有道没有同根和词源太难受了
