### ISSUE TITLE
关于生词本的翻译字段

### ISSUE THREAD

**Issue by itgoyo** [crimx/ext-saladict#105]
- 平台：

window10 

- 类型：建议

![image](https://user-images.githubusercontent.com/23348551/39902017-40fcf9f4-54fe-11e8-89a2-f92c1f17adf4.png)

我在把生词添加到生词本的时候，发现生词是添加进去了，但是悬浮窗口没有翻译字段，看到上下文的都有显示，所以我先问问，这个翻译字段空白是我操作不当才会这样，还是说设计本来就是这样子的呢

如果本来翻译字段就是空白的话，我个人的想法是觉得把翻译字段也添加进去的好点，这样子看起来，也方便。

望解答。

**Comment by crimx** [comment]
你好，这是故意的，因为要得到正确的翻译很难，而泛滥的翻译比空白更糟糕（个人意见），所以空着。在 6 的时候会优化这个流程，添加生词的时候会并列显示词典和这个面板，以便输入。

**Comment by itgoyo** [comment]
@crimx 好的，确实翻译有时候不尽人意、省去自己填写也可以加深印象，多方面原因吧，插件真好用，听说还可以配合Anki，晚些时候再爬帖看看。谢谢您回答。
