### ISSUE TITLE
【BUG反馈 】翻译框焦点问题

### ISSUE THREAD

**Issue by CheeseOn** [crimx/ext-saladict#1054]
在文本框内翻译单词时（我用的是双击）一旦点击翻译框右上角的叉叉（框内的内容也有着问题）文本框就会失去焦点。最讨厌的是，由于文本框失去焦点，这个时候一按Backspace键浏览器就会返回上一页。在用谷歌Docs翻译的时候这个问题很让人头疼，别人甚至问我怎么老是下线。希望改成关掉之后焦点自动返回原来的位置，谢谢！

**Comment by crimx** [comment]
> 一旦点击翻译框右上角的叉叉（框内的内容也有着问题）文本框就会失去焦点

页面内查词面板目前没有办法解决这个问题了。你可以在 Google Docs 页面上使用[独立窗口的快捷查词面板](https://saladict.crimx.com/manual.html#triple-ctrl)，同时在沙拉查词设置「快捷查词」中开启响应页面内划词。

> 一按Backspace键浏览器就会返回上一页

Chrome 和 Firefox 很早就取消了 Backspace 返回上一页，不知道你使用的是什么浏览器？
