### ISSUE TITLE
求safari版本的，愿意付费

### ISSUE THREAD

**Issue by stfenjobs** [crimx/ext-saladict#1055]
## 设备信息
- 操作系统: [mac] 
- 浏览器版本: [safari] 
- 沙拉查词版本: [最新] 

## 请描述目前使用沙拉查词遇到什么不便

希望可以在safari上用

## 理想情况下，沙拉查词应该怎么做

支持safari

## 替代方案

暂无

## 额外信息

可以付费

**Comment by ghost** [comment]
已有safari版本  https://saladict.crimx.com/safari
