### ISSUE TITLE
Add support for the online etymology dictionary https://www.etymonline.com/.

### ISSUE THREAD

**Issue by hongyi-zhao** [crimx/ext-saladict#1056]
Could you please add the support for the [online etymology dictionary](https://www.etymonline.com/)?

**Comment by crimx** [comment]
Saladict options 👉 Dictionaries 👉 Add

**Comment by hongyi-zhao** [comment]
> Saladict options point_right Dictionaries point_right Add

I checked this option, but still can't find the solution for my problem. To be specific, The list consists of a series of dictionaries which doesn't include the [online etymology dictionary](https://www.etymonline.com/).

**Comment by crimx** [comment]
![image](https://user-images.githubusercontent.com/6882794/96400871-7d857700-1204-11eb-9083-5e943d9158ac.png)

**Comment by hongyi-zhao** [comment]
OMG, got it. Thanks a lot, I didn't even notice its existence due to the dictionaries list is rather long.

**Comment by crimx** [comment]
In major browsers there is a shortcut key <kbd>Ctrl</kbd>+<kbd>F</kbd> that allows you to find text in the current page.
