### ISSUE TITLE
自动读取剪贴板功能以及权限可否可以设为可选

### ISSUE THREAD

**Issue by 10frank** [crimx/ext-saladict#1057]
谢谢

**Comment by crimx** [comment]
沙拉查词设置👉权限管理

**Comment by crimx** [comment]
另外，沙拉查词设置👉快捷查词 以及 右上弹框 设置预加载内容

**Comment by crimx** [comment]
> 能不能像有些收费App那样按照功能打包为不同版本，例如基础功版本、全功能版；免费版、收费版。这样功能与权限也就可选。

沙拉查词所有功能都是免费的，除去一些可选的第三方翻译服务。
