### ISSUE TITLE
点击扩展栏的沙拉查词图标会翻译整个网页

### ISSUE THREAD

**Issue by QBH-insist** [crimx/ext-saladict#1059]
## 设备信息
- 操作系统: [macos 10.14.6 ] 
- 浏览器版本: [Chrome 86.0.4240.80] 
- 沙拉查词版本: [v7.17.0] 

## 描述问题

在 Chrome 打开网页，点击右上角的扩展栏的沙拉查词插件，会直接把整个网页都给翻译了，出现下图的 tips
![image](https://user-images.githubusercontent.com/39401478/96360959-38097100-1154-11eb-93ac-112edd514f40.png)

## 复现步骤

打开任何网页点击扩展拦的沙拉查词图标即可重现

## 期待的正常行为

期望：点击扩展图标会弹出沙拉查词的弹框，可手动输入查询

**Comment by crimx** [comment]
https://saladict.crimx.com/notice.html#%E9%A2%84%E8%AE%BE

**Comment by QBH-insist** [comment]
thx
