### ISSUE TITLE
与简悦或Just Read等阅读模式插件配合

### ISSUE THREAD

**Issue by ljhui** [crimx/ext-saladict#106]
如标题，网页经过简悦或Just [Read等阅读模式插件转化后的页面上无法取词划词，希望能配合使用。
[简悦](https://chrome.google.com/webstore/detail/ijllcpnolfcooahcekpamkbidhejabll)
[Just Read](https://chrome.google.com/webstore/detail/dgmanlpmmkibanfdgjocnabmcaclkmod)

**Comment by crimx** [comment]
已支持，等待约一周后的更新

**Comment by crimx** [comment]
Just Read 已支持，简悦进度可参考 https://github.com/Kenshin/simpread/issues/317
