### ISSUE TITLE
edge版单点图标不出翻译栏，而是页面翻译

### ISSUE THREAD

**Issue by Lcmolin** [crimx/ext-saladict#1061]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [版本 86.0.622.43 (官方内部版本) (64 位)] 
- 沙拉查词版本: [v7.17.0] 

## 描述问题

edge版单点图标不出翻译栏，而是页面翻译

## 复现步骤

1. 打开egde浏览器
2. 点击点击沙拉划词图标
4. 不出现翻译栏，而是页面翻译

## 期待的正常行为

出现翻译栏

## 截图

![image](https://user-images.githubusercontent.com/49859097/96447190-269f9200-1244-11eb-808c-d99874587b01.png)

**Comment by crimx** [comment]
Duplicate of #1059
