### ISSUE TITLE
上一个查词记录和下一个查词记录能支持浏览器的前进后退功能

### ISSUE THREAD

**Issue by nanmao** [crimx/ext-saladict#1063]
## 设备信息
- 操作系统: [win10] 
- 浏览器版本: [Chrome 86.0.4240.75 (Official Build) (64-bit)] 
- 沙拉查词版本: [v7.17.0] 

## 请描述目前使用沙拉查词遇到什么不便

查词面板内部划词, 直接搜索后我要回到上一个查词记录, 这时候需要鼠标移到面板左上角点击, 操作不方便. 
## 理想情况下，沙拉查词应该怎么做

如果上一个查词记录和下一个查词记录能支持浏览器的前进后退功能, 就可以直接用鼠标的两个侧键方便切换上一个和下一个查词记录.

## 替代方案

~~上一个查词记录和下一个查词记录支持"前进/后退"的快捷键, 我可以用quicker映射快捷键动作到鼠标两个侧键实现查词记录的快速切换.~~
沙拉划词独立窗口的quicker面板和Chrome是共用的,所以用quicker映射快捷键动作方案不行.
希望上一个查词记录和下一个查词记录能支持浏览器的前进后退功能.

**Comment by crimx** [comment]
嗯嗯，感谢反馈。
