### ISSUE TITLE
希望右上角查词面板添加自动回车功能,这样就不需要每次查词都需要手动按一下回车键

### ISSUE THREAD

**Issue by AirBashX** [crimx/ext-saladict#1064]
## 设备信息
- 操作系统: [] Window10
- 浏览器版本: [] Chrome86
- 沙拉查词版本: [] 7.17.0

## 请描述目前使用沙拉查词遇到什么不便

右上角弹窗不能自动查词

## 理想情况下，沙拉查词应该怎么做

当我设置**剪切板**+**自动查词**,时:点击右上角图标会自动查询剪切板的翻译;但是当我需要在此输入内容进行查询时却不能实时查询,需要按回车键才能查询;能不能不按回车键进行查询;

## 替代方案

希望效果能跟隔壁插件**划词翻译**的效果一样

**Comment by crimx** [comment]
你好，谢谢反馈。不考虑实现这样的功能。与简单的查词接口不一样，在沙拉查词中如此频繁地大量查词可能会大幅度拖慢浏览器运行速度以及导致你IP被服务器拉黑。
