### ISSUE TITLE
 建议增加鼠标悬停在小喇叭icon上，单词自动发音的功能

### ISSUE THREAD

**Issue by Marina207** [crimx/ext-saladict#1065]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Chrome86x64] 
- 沙拉查词版本: [v7.17.0] 

## 请描述目前使用沙拉查词遇到什么不便
划词后想听每个单词的单词发音，都要点击单词旁边的小喇叭icon，如果需要多听几遍就要鼠标多点击几遍很麻烦。

## 理想情况下，沙拉查词应该怎么做

我希望能实现悬浮收听单词发音的功能。
既：
1.鼠标悬停在小喇叭icon上，0.2s~0.3s后（具体多长时间，用户可自定义）自动发出一次单词读音。
2.若用户想再听一次读音，可将鼠标挪开，再次放置在小喇叭icon上，重复步骤1.
## 替代方案

无

## 额外信息

有道dict Chrome 插件即可实现悬停听取单词发音的功能，我建议增加这个功能的原因是，悬停发音和点击发音相比真的是太舒服了！少click一次是一次！Thanks♪(･ω･)ﾉ

**Comment by crimx** [comment]
😂原先因为是悬停发音容易误触导致太多用户反馈才改成点击的。点击其实也不是难用，更多是习惯问题。觉得没必要在增加如此多设置了，而且目前的实现增加悬停会使底层很不优雅，所以不考虑实现了。谢谢反馈。

**Comment by Marina207** [comment]
PS：「悬停发音」和目前已有的「自动发音」功能不一样哦
因为「自动发音」是你划词查询后就立即自动发音了。
而『悬停发音』是当用户的鼠标挪动在『小喇叭icon』上时才自动发音。

**Comment by Marina207** [comment]
> 😂原先因为是悬停发音容易误触导致太多用户反馈才改成点击的。点击其实也不是难用，更多是习惯问题。觉得没必要再增加如此多设置了，而且目前的实现增加悬停会使底层很不优雅，所以不考虑实现了。谢谢反馈。

原来是这样啊，看来产品功能还有点儿众口难调，不知道能不能单独为「悬停发音」留一个用户自定义开关，默认「关闭」这样。

**Comment by crimx** [comment]
我觉得没必要在习惯问题上做这么复杂了。但如果有其它人愿意接手的话欢迎。
