### ISSUE TITLE
为什么我设置了有道翻译的词典账号，但是依然没有使用api

### ISSUE THREAD

**Issue by yllgl** [crimx/ext-saladict#1067]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome86] 
- 沙拉查词版本: [v7.17.0] 

## 描述问题

我在有道申请了api，想获得更加精确的翻译结果，我把appkey和密钥填入saladict的设置中的词典账号中，点击了保存，然后尝试重新用saladict翻译原来的句子，但是结果依旧没变，和有道在线翻译网页上的结果不一致，我用python测试过有道api返回结果，是和有道在线翻译网页一致的，但是saladict的翻译结果不一致。

## 复现步骤
在saladict的设置页面中的词典账号填写好自己的有道翻译的appkey与key，点击保存，然后尝试翻译一段文章，与有道在线翻译网页上的翻译结果对比。

## 期待的正常行为

翻译结果应该需要一致。

**Comment by crimx** [comment]
> 然后尝试翻译一段文章

你好，请提供具体可复现的步骤，供测试对比。

**Comment by yllgl** [comment]
> > 然后尝试翻译一段文章
> 
> 你好，请提供具体可复现的步骤，供测试对比。
填好有道翻译的appkey与key，保存后翻译下面一段话：
It has evolved since then—its 750 pupils now include some girls.
翻译结果：从那时起，学校的750名学生中有一些是女孩。
[有道在线翻译](http://fanyi.youdao.com/)的翻译结果：
从那时起，它就不断发展，现在的750名学生中包括一些女孩。
结果与有道在线翻译结果不一致。

**Comment by crimx** [comment]
感谢提供进一步信息

> 我用python测试过有道api返回结果，是和有道在线翻译网页一致的

你测试的参数是什么？

**Comment by yllgl** [comment]
[test.txt](https://github.com/crimx/ext-saladict/files/5432743/test.txt)
请重命名为.py后缀

**Comment by crimx** [comment]
我这边的测试是一致的

![image](https://user-images.githubusercontent.com/6882794/97080189-36481d80-162c-11eb-9804-b6e7c9833d83.png)

**Comment by crimx** [comment]
如果依然出现这样的情况你可以尝试打开 fanyi.youdao.com 点击地址栏前面的按钮，点开 Cookies 全删掉。看能不能解决这个问题。

**Comment by yllgl** [comment]
@crimx 
![QQ截图20201024193144](https://user-images.githubusercontent.com/23625282/97080688-c9368700-162f-11eb-88d1-67bc8225cf21.png)

为什么我的显示的图标是有道词典，你的显示的是有道翻译？

**Comment by crimx** [comment]
那个是有道词典，与有道翻译不是一个词典。

**Comment by crimx** [comment]
打开[设置](https://saladict.crimx.com/manual.html#open-setting)，选择词典管理

**Comment by crimx** [comment]
或者切换[情景模式](https://saladict.crimx.com/manual.html#profile)

**Comment by yllgl** [comment]
好的，解决了！谢谢！

**Comment by sjhsbhqf** [comment]
我怀疑你是不是没有实名认证
