### ISSUE TITLE
腾讯微云分享pdf后进入的落地页 沙拉查词会导致下载按钮不能点击

### ISSUE THREAD

**Issue by Relsoul** [crimx/ext-saladict#1068]
## 设备信息
- 操作系统: [macos/win10] 
- 浏览器版本: [chrome85] 
- 沙拉查词版本: [v7.17.0] 

## 复现步骤

打开页面 https://share.weiyun.com/s7SQQAvj
点击下载
![image](https://user-images.githubusercontent.com/11955123/96993296-af2c7400-155d-11eb-8e7e-b1d3f2495e83.png)

## 期待的正常行为

禁用沙拉查词后可正常下载

**Comment by crimx** [comment]
感谢反馈。PDF 黑名单添加 URL pattern `*://sh-download.weiyun.com/*`
