### ISSUE TITLE
自动将输入焦点集中到查词的输入框

### ISSUE THREAD

**Issue by Tback1** [crimx/ext-saladict#107]
- 平台：Windows 7 SP1 和 Chrome  66 版本

- 类型：建议

在**ctrl 快速查词** 和**快捷键弹出**右上角 查词窗体后，建议自动将输入焦点集中到查词的输入框

![snipaste20180521_154324](https://user-images.githubusercontent.com/8872546/40295944-c29d451a-5d0d-11e8-9d66-3fdf422cc2db.png)

**Comment by crimx** [comment]
谢谢反馈，理应获取焦点的，可能在一些地方有些小 bug，新版将使用不一样的机制，到时不行可以再反馈。
