### ISSUE TITLE
OCR suport on Linux.

### ISSUE THREAD

**Issue by hongyi-zhao** [crimx/ext-saladict#1070]
Hi,

Are there any good solutions for OCR support of saladict on Linux?

Regards,
HY

**Comment by crimx** [comment]
I don't know since I don't use OCR. You may check out [here](https://saladict.crimx.com/en/native.html#windows) for inspiration.

**Comment by hongyi-zhao** [comment]
Seems its target platform is windows.

**Comment by crimx** [comment]
Yes, hence "for inspiration". Similar approach may be applied to other platforms.
