### ISSUE TITLE
点击Chrome工具栏图标后弹出的“输入然后翻译”窗口应该可以移动

### ISSUE THREAD

**Issue by edwinyzh** [crimx/ext-saladict#1072]
点击Chrome工具栏图标后弹出的“输入然后翻译”窗口应该可以移动，因为该窗口常常遮盖住了页面上需要看到的单词。

谢谢。

**Comment by crimx** [comment]
那个窗口是浏览器的 browser action 窗口，是不能移动的。如果需要系统级的窗口可以使用[独立窗口查词面板](https://saladict.crimx.com/manual.html#triple-ctrl)。

**Comment by edwinyzh** [comment]
> 那个窗口是浏览器的 browser action 窗口，是不能移动的。如果需要系统级的窗口可以使用[独立窗口查词面板](https://saladict.crimx.com/manual.html#triple-ctrl)。

太好了，都不知道有这个独立窗口可以使用！
感谢开发了这个extension，太方便了！

**Comment by edwinyzh** [comment]
你好，很抱歉在这个已经关闭的issue下面留言，不过提个建议：按Esc关闭这个独立窗口查词面板。这样可以极大提高效率。谢谢。

**Comment by crimx** [comment]
ctrl/command w 关闭就行。跟普通窗口一样操作。
