### ISSUE TITLE
部分词典还是失效...

### ISSUE THREAD

**Issue by Ethan-Crisp** [crimx/ext-saladict#1073]
![image](https://user-images.githubusercontent.com/44205688/97521709-107a9a00-19d9-11eb-8562-d92c8a7bb9b1.png)
怎么办呢，现在只有谷歌翻译和有道词典能用，难道是和其他词典的登陆有关吗

**Comment by crimx** [comment]
![image](https://user-images.githubusercontent.com/6882794/97521881-70714080-19d9-11eb-89f6-01f0799a8670.png)


我这边是没有问题的。点词典标题打开官网看看，检查一下你的网络，DNS 什么的。
