### ISSUE TITLE
Mac 下墙内下载，确定扩展id是对的。但无法安装成功

### ISSUE THREAD

**Issue by FuChen1649** [crimx/ext-saladict#1074]
## 设备信息
- 操作系统:MacOS Catalina 10.15.7
- 浏览器版本: Chrome86
- 沙拉查词版本: v7.16.1

## 描述问题

下载后扩展页面上拖拽后添加插件失败

## 截图

<img width="1327" alt="截屏2020-10-30 上午11 15 35" src="https://user-images.githubusercontent.com/39113750/97655968-3ec3ac80-1aa1-11eb-8335-79ba044509a1.png">
<img width="1337" alt="截屏2020-10-30 上午11 16 08" src="https://user-images.githubusercontent.com/39113750/97656004-526f1300-1aa1-11eb-854e-8a37b774da2b.png">

**Comment by crimx** [comment]
> Mac 下墙内下载，确定扩展id是对的。

是在什么地方下载的呢？安装前应该无法确认 id 吧？可以在[下载页面](https://saladict.crimx.com/download.html)选网盘下载试试。

**Comment by FuChen1649** [comment]
https://www.crx4chrome.com/extensions/cdonnmffkdaoajfknoeeecmchibpmkmg/  
在这下的

**Comment by FuChen1649** [comment]
已解决
