### ISSUE TITLE
网页翻译添加翻译网站选择（如谷歌翻译，百度翻译）

### ISSUE THREAD

**Issue by cloverzrg** [crimx/ext-saladict#1077]
## 设备信息
- 操作系统: [macos 10.16] 
- 浏览器版本: [chrome86] 
- 沙拉查词版本: [7.17] 

## 请描述目前使用沙拉查词遇到什么不便

在使用网页翻译时，总感觉翻译意思不准，比如把`client's date of birth` 翻译为`病人出生日期`，只有有道翻译才会这么翻译，然后再设置页面找不到更换的地方

## 理想情况下，沙拉查词应该怎么做

提供翻译网站选项，而不是只能使用有道翻译进行网页翻译

**Comment by crimx** [comment]
在沙拉查词设置[右键菜单管理](https://saladict.crimx.com/manual.html#page-trans)里添加就行。沙拉查词内置 彩云小译网页翻译，有道网页翻译，谷歌网页翻译。

**Comment by crimx** [comment]
> 在使用网页翻译时，总感觉翻译意思不准

网页翻译更适合作为快速理解，而不是对准确度有要求的场景，请使用词典面板功能查词，通过多个信息源对比获得更高准确度。

**Comment by cloverzrg** [comment]
右键有点麻烦，我是直接点击图标来进行网页翻译的

**Comment by crimx** [comment]
要不你试试设置[浏览器快捷键](https://saladict.crimx.com/manual.html#shortcuts)？

**Comment by cloverzrg** [comment]
不怎么用快捷键，谢谢帮助
