### ISSUE TITLE
自动发音错误 & 希望添加谷歌发音呢

### ISSUE THREAD

**Issue by Lukikay** [crimx/ext-saladict#108]
> 用了一阵子沙拉，非常喜欢哦！

##### 平台：

OS: Windows 10 April Update 2018, version 1803

Chrome:  66.0.3359.181, x64

##### 类型：

错误

##### 重现：

开启自动发音功能，选Bing的英音，结果念出来的是美英。可以用*water*试一下。

##### 期待：

修复一下呗

##### 类型：

建议

##### 期待：

窗口翻译能不能加入牛津、剑桥词典和发音呀，加一个谷歌的发音也行呢

现在只能用Bing的发音，感觉Bing不是很舒服，而且加载非常慢

**Comment by crimx** [comment]
谷歌翻译没有提供发音 api ，其它词典计划见 https://github.com/crimx/ext-saladict/projects/2

**Comment by Lukikay** [comment]
哦哦，谢谢哈

BTW, 请问这个项目是你的业余兴趣嘛，作为一个机械学生，好想进这个圈子啊，正儿八经立等可取的造福大家。。。

**Comment by Lukikay** [comment]
还有哦，Chrome上的PDF.js支持双页视图嘛，用双页会方便好多啊

**Comment by crimx** [comment]
Saladict 用的就是 PDF.js 官方提供的 UI，特意去安裝了官方扩展，也没发现有双页视图？

**Comment by Lukikay** [comment]
所以Chrome上的PDF.js是没有双页的嘛，好像FIrefox上的是有的吧

**Comment by crimx** [comment]
新版[已发布](https://github.com/crimx/ext-saladict/wiki/Saladict6)，关闭遗留问题页，如有问题欢迎开新 issue 反馈。
