### ISSUE TITLE
windows 10 egde 浏览器 打开新的页面点击插件要重新刷新才可用

### ISSUE THREAD

**Issue by HelloWorldZQ** [crimx/ext-saladict#1080]
windows 10 egde 浏览器 打开新的页面点击插件要重新刷新才可用

## 设备信息
- 操作系统: win10
- 浏览器版本:Microsoft Edge。
版本 86.0.622.56 (官方内部版本) (64 位)
![image](https://user-images.githubusercontent.com/10047555/97934688-58bb0300-1db1-11eb-9936-13f7834950b8.png)

- 沙拉查词版本: v7.17.0

windows 10 egde 浏览器 打开新的页面点击插件要重新刷新才可用

![image](https://user-images.githubusercontent.com/10047555/97934744-82742a00-1db1-11eb-95ff-27c631bd299c.png)

## 描述问题
windows 10 egde 浏览器 打开新的页面点击插件要重新刷新才可用

## 复现步骤
1.wind10  edge 安装 插件
2.  打开新的页面
3. 提示内嵌页面查询不可使用,但是独立窗口仍然可以使用,
4. 点击插件提示刷新页面后插件可用

## 期待的正常行为
1.期待和chrome 一样打开新页面就可以使用

## 截图

![image](https://user-images.githubusercontent.com/10047555/97934857-d848d200-1db1-11eb-8881-ac12c14c515f.png)

![image](https://user-images.githubusercontent.com/10047555/97934861-dbdc5900-1db1-11eb-84f4-c1e833bf87af.png)

**Comment by crimx** [comment]
你是不是限制了扩展访问数据。右键这个图标，菜单里有 "This can read and change site data"，选择“On all sites”。

**Comment by HelloWorldZQ** [comment]
@crimx
多谢,确实是的
