### ISSUE TITLE
希望能加入单词本分类功能

### ISSUE THREAD

**Issue by weishx** [crimx/ext-saladict#1081]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [edge] 
- 沙拉查词版本: [] 

## 请描述目前使用沙拉查词遇到什么不便

要是单词本能分类就更好了

## 理想情况下，沙拉查词应该怎么做

在加入单词本时能放入不同的单词本中，这样可以方便的将想导出anki的词进行分类导出

**Comment by crimx** [comment]
你可以在笔记中使用 `#xxx` 或者任意的符号作为标签。然后利用单词本页面上方的搜索进行筛选。

**Comment by weishx** [comment]
> 你可以在笔记中使用 `#xxx` 或者任意的符号作为标签。然后利用单词本页面上方的搜索进行筛选。

谢谢指导。
作者真是厉害了秒回
