### ISSUE TITLE
谷歌翻译不自动发音和发音按钮消失Google translation does not automatically pronounce and the pronunciation button disappears

### ISSUE THREAD

**Issue by eryisan** [crimx/ext-saladict#1085]
## 设备信息
- 操作系统: [**Win 10**] 
- 浏览器版本: [Chrome 86.0.4240.183] 
- 沙拉查词版本: [ 7.18.0 ] 

## 描述问题

Google translation does not automatically pronounce and the pronunciation button disappears
------------------1.谷歌翻译自动发音和发音按钮功能异常
出现问题版本：
Chrome浏览器---Chrome 86.0.4240.183
火狐开发者浏览器Firefox browser developer ---- 83.0b8

没问题版本（正常）：
火狐浏览器Firefox Browser ---82.0.2

沙拉查词谷歌翻译都无法自动发音,且发音按钮消失.是次数限制还是BUG?
打算换其他词典,自动发音选项设置里词典没有有道词典.
另外腾讯翻译君,彩云小译发音很低沉很模糊,远不如谷歌有道的声音清晰,很奇怪音质.

------------------1.自动发音的覆盖问题
1.发音设置---设置英文自动发音---剑桥词典---机器自动发音----谷歌翻译----查词剑桥词典发音功能则正常
2.一旦把机器自动发音----换成腾讯翻译君,查词剑桥词典发音功能则消失,音质变得很差,感觉腾讯翻译君的发音覆盖了剑桥词典
但是设置选项里并没改变.英文自动发音仍然是剑桥词典.一旦换回谷歌翻译发音(当然也没声音),剑桥词典发音正常清晰洪亮.
3.Chrome浏览器---Chrome 86.0.4240.183      火狐开发者浏览器Firefox browser developer ---- 83.0b8
4.上面两本版本都测试过,同样的问题.

## 复现步骤

1.打开freecodecamp.org
2.划词翻译某个句子
3.弹出沙拉查词窗口
4.谷歌发音按钮和自动发音消失

## 期待的正常行为

谷歌自动发音
出现发音按钮
有道自动发音

## 截图

Chrome浏览器---Chrome 86.0.4240.183
火狐开发者浏览器Firefox browser developer ---- 83.0b8
有问题;
![image](https://user-images.githubusercontent.com/61043745/98066252-752e6c80-1e91-11eb-8d44-745e4a820d65.png)
a class="saladict-Speaker这块显示不出来

火狐浏览器Firefox Browser ---82.0.2
功能正常：
![图片](https://user-images.githubusercontent.com/61043745/98075138-c6952680-1ea6-11eb-9800-b00d7f5300a9.png)

发音覆盖问题
![image](https://user-images.githubusercontent.com/61043745/98186917-c8b0c100-1f4a-11eb-9c73-df1ec55c1142.png)

## 额外信息

感谢作者,因机器翻译用的比较多.
已赞助项目,谢谢这么好的工具!

**Comment by thomasygh** [comment]
是的，也遇到同样的问题了。期待作者解决。
也已赞助项目，非常感谢如此优秀的工具。

**Comment by crimx** [comment]
应该是谷歌更新了。我要周末才能修复，如果感兴趣的可以去 [OpenTranslate](https://github.com/OpenTranslate/OpenTranslate/tree/master/packages/service-google) 提交 PR。

**Comment by eryisan** [comment]
!谢谢作者答复!   辛苦了!
还没提交过PR哈哈哈，看看能不能试一下

**Comment by eryisan** [comment]
正常工作了,感谢感谢.这个issue完成了.

已打赏作者喝咖啡补充精力加油哈哈哈.

**Comment by crimx** [comment]
这个还需要点时间才能完全解决。现在 google 在灰度测试新的翻译 API。  
https://github.com/Boudewijn26/gTTS-token/blob/master/docs/november-2020-translate-changes.md

**Comment by thomasygh** [comment]
不好意思，发音按钮又消失了。反反复复。
 请求大神再次解救，拜托了。
@crimx

**Comment by zhl111** [comment]
谷歌翻译发音按钮消失，谷歌翻译发音比较靠谱

请求大神解救，拜托了。

**Comment by CorleoneW** [comment]
+1

**Comment by crimx** [comment]
已修复，等待 v2.20.0 上架。
