### ISSUE TITLE
右键菜单删掉后再次出现

### ISSUE THREAD

**Issue by lirikirikiri** [crimx/ext-saladict#1086]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Edge86] 
- 沙拉查词版本: [v7.18.0] 

## 描述问题

每次我把右键菜单“彩云小译网页翻译”删掉，但过一段时间又会自己出现。

## 期待的正常行为

我不需要右键菜单，希望删掉后就不再出现。

## 截图

![image](https://user-images.githubusercontent.com/10389204/98185579-ddd82080-1f47-11eb-812f-c07bc3f1d9f4.png)

**Comment by crimx** [comment]
最近有比较多人反馈这个问题，但我这边一直没办法复现，周末再看看是什么情况。

**Comment by crimx** [comment]
感觉有可能跟 #1078 有关，但你用的是 Edge 应该没有科学上网的问题。你是在 Edge 商店里安装的吗？还是通过 Edge 安装 Chrome 商店的？

**Comment by lirikirikiri** [comment]
是通过 Edge 安装 Chrome 商店的，不过我这个应该不算被重置，划词菜单都还在。

> 感觉有可能跟 #1078 有关，但你用的是 Edge 应该没有科学上网的问题。你是在 Edge 商店里安装的吗？还是通过 Edge 安装 Chrome 商店的？

是通过 Edge 安装 Chrome 商店的，不过我这个应该不算被重置，划词菜单都还在。

**Comment by crimx** [comment]
那你可以尝试直接安装 Edge 商店中的，Chrome 商店的可能走的是 Google 服务器同步数据。

先导出现有的沙拉查词设置，然后卸载沙拉查词，从 Edge 商店安装，最后导入设置。
