### ISSUE TITLE
建议可以打开多个pdf阅读器，方便阅读多个pdf文档

### ISSUE THREAD

**Issue by ORZbiubiubiu** [crimx/ext-saladict#1089]
## 设备信息
- 操作系统: [window10] 
- 浏览器版本: [Chrome86] 
- 沙拉查词版本: [v7.18.0] 

## 请描述目前使用沙拉查词遇到什么不便

无法使用pdf阅读器打开多个pdf文档。

## 理想情况下，沙拉查词应该怎么做

让用户可以打开多个pdf阅读器，同时阅读多个pdf文档。

**Comment by hqyyqh** [comment]
可以按照这个帖子 #1005 中**实现**的方式，在多个独立窗口打开pdf。
安装Quicker的话可以一步到位。
