### ISSUE TITLE
词典帐号界面只能填写百度翻译api

### ISSUE THREAD

**Issue by zpzwz** [crimx/ext-saladict#1090]
## 设备信息
- 操作系统: Win10
- 浏览器版本: 新版Edge  版本 86.0.622.51 (官方内部版本) (64 位)
                      此浏览器基于 Chromium 开源项目及其他开源软件。
- 沙拉查词版本: v7.18.0
## 描述问题
词典帐号界面只能填写百度api，其他的都不显示。
## 复现步骤
1. 进入沙拉查词设置界面
2. 点击词典账号
3. 问题出现
## 期待的正常行为
呈现多个账号api配置输入框。
## 截图
![图示](https://user-images.githubusercontent.com/49054632/98336239-80c09580-2041-11eb-99db-002dd3de76d0.png)

## 额外信息
无

**Comment by crimx** [comment]
我这边没有办法复现。你是不是导入过其他人的沙拉查词设置备份？重置试试。

**Comment by zpzwz** [comment]
> 我这边没有办法复现。你是不是导入过其他人的沙拉查词设置备份？重置试试。
重置后解决了，谢谢~
