### ISSUE TITLE
firefox中突然不能用了

### ISSUE THREAD

**Issue by neracn** [crimx/ext-saladict#1091]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Firefox 82.0.2] 
- 沙拉查词版本: [v7.18.0] 

## 描述问题

最近在firefox中，沙拉查词突然不能翻译了。
我试了一下，划词是正常的，但是手动打开沙拉查词，手输单词翻译就不行了，没反应。

## 复现步骤

划词在任何网站都可以，功能正常。
点开沙拉查词的图标，手动输入单词翻译就没反应：
1. 打开任一网站，如 https://laws-lois.justice.gc.ca/eng/acts/c-1.68/
2. 点击沙拉查词图标
3. 输入单词 time
4. 没反应

## 期待的正常行为

正常情况下，会出现翻译结果

## 截图

![图片](https://user-images.githubusercontent.com/32286995/98493448-71299280-2275-11eb-8d62-b6c61c956e65.png)
![图片](https://user-images.githubusercontent.com/32286995/98493486-8999ad00-2275-11eb-923c-f74cc4c2476d.png)

## 额外信息

已经持续了一周多时间

**Comment by crimx** [comment]
我这边测试没问题的。看看是不是跟其它冲突了。

**Comment by leonevilred** [comment]
> 
> 
> 我这边测试没问题的。看看是不是跟其它冲突了。

在firefox82.0.3发生一样的问题，并且设置右上弹框-自动弹词提示如下错误：
设置保存失败
QuotaExceededError: storage.sync API call exceeded its quota limitations.

**Comment by dncry** [comment]
同样的问题出现在,82.0.3(64位).
添加或者删除词典的时候提示:"
设置保存失败
QuotaExceededError: storage.sync API call exceeded its quota limitations."

词典 点按3下Ctrl出现的独立查词窗口是没问题的, 划词后出现的窗口也没问题,以上两个窗口都可以修改单词并查看翻译.
但是通过firefox顶部的工具栏图标点出的查词窗口是有错误的,无法查询单词,也无法翻译

**Comment by crimx** [comment]
> QuotaExceededError: storage.sync API call exceeded its quota limitations.

火狐的扩展存储频率限制有点大，动不动就超了，应该是出现大量修改设置后。等一段时间应该就好了。

**Comment by Kenvas** [comment]
同样的问题，我已经持续几个 firefox 的版本了，今天用管理员身份运行之后就好了，再用回普通用户也是好的
