### ISSUE TITLE
希望查词界面能固定在某个位置

### ISSUE THREAD

**Issue by YesHub** [crimx/ext-saladict#1094]
希望能记住查词界面关闭后的位置，不会每次显示在鼠标旁，有时候连续划词会把原文挡住,希望增加这个功能选项。谢谢!

**Comment by crimx** [comment]
你可以按查词面板上的工具栏中的图钉钉住。或者使用[侧边栏模式](https://saladict.crimx.com/manual.html#triple-ctrl)。
