### ISSUE TITLE
独立查词窗口关闭后，浏览器窗口会向上发生位移, 每次打开后再关闭都发生一次

### ISSUE THREAD

**Issue by imanokZ** [crimx/ext-saladict#1095]
#620  设备信息
- 操作系统: [Win10，mac OSX 10.14.6] 
- 浏览器版本: [Chrome86] 
- 沙拉查词版本: [v7.18.0] 

## 描述问题
独立查词窗口关闭后，浏览器窗口会向上发生位移, 每次打开后再关闭都发生一次

## 复现步骤
打开 独立查词 ， 关闭独立查词窗口，浏览器窗口自动上移发生

## 期待的正常行为
修复此问题

**Comment by crimx** [comment]
这是因为 chrome 的 bug，不同情况下窗口标题栏可能会不一样。打开沙拉查词设置【 快捷查词】 【打开独立窗口设置】 【校准标题栏高度】。

**Comment by imanokZ** [comment]
不错，点”自动校准“后修复

感谢！

**Comment by AngelontheRoad** [comment]
我按照这样做了，但关闭的时候还会往上移动
