### ISSUE TITLE
查词框中文输入首字母出现重复

### ISSUE THREAD

**Issue by yankangwin** [crimx/ext-saladict#1096]
## 设备信息
- 操作系统: [Win7 Ultimate SP1] 
- 浏览器版本: [Chrome Version 86.0.4240.183 (Official Build) (64-bit)] 
- 沙拉查词版本: [v7.18.0] 

## 描述问题

剪贴板查词后，再直接输入中文查词会多出一个英文字母。

## 复现步骤

步骤一：使用“读取剪贴板功能”，从外部复制任意文字，在Chrome浏览器点击沙拉查词图标，此时单词处于“全选”标蓝状态。【正常】
步骤二：如果突然不想查这个词了，直接键盘输入另外一个词，如新输入的单词为英文，则可替换原词语，正常显示。【正常】
步骤三：如新输入的词汇为中文，则会在词首，多出该词的小写拼音首字母，比如输入“测试”，则实际显示“c测试”如图。【Bug】
![image](https://user-images.githubusercontent.com/38773914/98641843-5fc0b300-2367-11eb-80f1-c624992fc433.png)

## 期待的正常行为

在查词栏内容全选的情况下，输入中文词汇可以【准确】的显示、查询。

## 截图

已在上文附图。

## 额外信息

我用的是QQ拼音输入法（并且我只安装了这个输入法），会是输入法引起的吗？
如答案是肯定的，那么受这个bug影响的肯定不止我一个人。在不更换输入法的情况下，有办法解决吗？
感谢各位大佬的劳动。

**Comment by gitman486** [comment]
ditto

**Comment by gitman486** [comment]
像这样->
在覆盖状态下(按enter查词后在接着输入查)/使用剪切板,输入会double字母(有一小部分字母不会
![image](https://user-images.githubusercontent.com/64391947/99032321-3f396880-25b4-11eb-8462-43e79ab881d8.png)
这里我只按了一次s
![image](https://user-images.githubusercontent.com/64391947/99032468-89224e80-25b4-11eb-9d43-b5199594a1c8.png)

**Comment by crimx** [comment]
感谢反馈，我明天看看。

**Comment by wzw1016** [comment]
同样发现，首字母会显示两个

**Comment by refcell** [comment]
win10微软拼音也有相同的问题

**Comment by AlanCutFlim** [comment]
MacOS 搜狗输入法也有这个问题

感谢作者的付出！另外请问这个 issue 的进展怎么样了，还挺影响用户体验的

**Comment by crimx** [comment]
新版已修复。
