### ISSUE TITLE
为什么我的划词翻译只有谷歌翻译可用？

### ISSUE THREAD

**Issue by teraStars** [crimx/ext-saladict#1097]
## 设备信息
- 操作系统: [win10 1909] 
- 浏览器版本: [chrome 86] 
- 沙拉查词版本: [7.18.0] 

## 描述问题

在网页中选择一段英文，然后点击弹出的图标，显示出来的翻译面板，只有谷歌翻译的内容。还有个有道词典，但其中的内容也是空的。

## 截图

<img width="341" alt="Snipaste_2020-11-11_12-46-32" src="https://user-images.githubusercontent.com/7426499/98770224-b1774500-241c-11eb-9762-8262766e7a7b.png">

## 额外信息

刚安装好这个扩展，没有做任何设置。

**Comment by crimx** [comment]
词典预设了划词字数识别，你可以自行对每个词典设置。也可以切换到【[翻译模式](http://localhost:4000/manual.html#profile)】查看更多机器翻译。
