### ISSUE TITLE
pdf翻译时，每行末尾都识别为换行符

### ISSUE THREAD

**Issue by bio-er** [crimx/ext-saladict#1098]
## 设备信息
- 操作系统: [win10] 
- 浏览器版本: [谷歌内核版edge浏览器86] 
- 沙拉查词版本: [7.18.0] 

## 描述问题
【和网页版的谷歌翻译一样的问题】独立窗口查词时，pdf的每一行都会单独翻译，就是每行末尾都识别为换行符。而且在输入栏里没法编辑删掉那个换行符。
用了x translator这个划词翻译软件没有出现这种情况。

**Comment by crimx** [comment]
原因：[常见问题与答复](https://saladict.crimx.com/q&a.html#%E9%97%AE%3A-pdf-%E5%88%92%E8%AF%8D%E5%AD%97%E7%AC%A6%E6%98%BE%E7%A4%BA%E4%B8%8D%E5%AF%B9%EF%BC%88%E5%A6%82-f-%E4%B8%8E-%C6%92%EF%BC%89%2F-pdf-%E5%88%92%E8%AF%8D%E6%8D%A2%E8%A1%8C%E7%9A%84%E5%8D%95%E8%AF%8D%E7%B2%98%E8%BF%9E%E5%9C%A8%E4%B8%80%E8%B5%B7%E3%80%82)。
解决方式：沙拉查词设置【词典设置】中打开相应机器翻译词典的设置，【保留换行】选【不保留】。如果需要频繁切换可创建新的【情景模式】。
