### ISSUE TITLE
Add an option to use bing.com instead of cn.bing.com

### ISSUE THREAD

**Issue by tddschn** [crimx/ext-saladict#1099]
**Is your feature request related to a problem? Please describe.**

cn.bing.com censors user inputs, while bing.com does not.
Since bing.com is blocked in mainland China, maybe it would be a good idea to add an option for users to choose which one to use (same with translate.google.cn)

**Describe the solution you'd like**

Add an option to configure which service (domain to request) Bing dict uses. (And maybe for Google Translate too.)

**Describe alternatives you've considered**

**Additional context**

**Comment by crimx** [comment]
Are you talking about the context menus? It is fully customizable in Saladict settings.

**Comment by tddschn** [comment]
Nope, the dict panel :)

**Comment by crimx** [comment]
Then can you provide a url to the bing dict page that you mentioned? AFAIK bing dict only has Chinese-English version.

google translate can be configure in saladict settings "Dictionaries".

**Comment by tddschn** [comment]
Oh I didn't realize it only has the Chinese-English version! 😅
Thanks for the info, I'll close the issue now. :)
