### ISSUE TITLE
功能请求：提供复制按钮，复制翻译后的内容到剪切板

### ISSUE THREAD

**Issue by LinXueyuanStdio** [crimx/ext-saladict#110]
划词翻译，提供复制按钮，复制翻译后的内容到剪切板。

另外，作者有兴趣的话，还可以考虑以下划词场景：
- 复制按钮，复制当前选中的文本。
- 搜索按钮，自定义搜索引擎，搜索当前选中的文本

**Comment by crimx** [comment]
谢谢建议！不太清除您的描述。

> 划词翻译，提供复制按钮，复制翻译后的内容到剪切板。

直接复制不行么？

> 复制按钮，复制当前选中的文本。

复制文本已经不是划词翻译的范畴。而且，这个复制按钮应该是怎样的？

> 搜索按钮，自定义搜索引擎，搜索当前选中的文本

Saladict 提供了右键菜单，里面可以选择常见搜索引擎。如果有缺少的可以提供。

**Comment by LinXueyuanStdio** [comment]
我设计的话，就把复制翻译文本的按钮放在翻译引擎名称的后面

类似这样：

<logo> 谷歌翻译 <复制>                 ∨
<logo> 必应词典 <复制>                 ∨
<logo> 国语辞典 <复制>                 ∨
<logo> 有道翻译 <复制>                 ∨

**Comment by crimx** [comment]
谢谢推荐，我安装试用了一下，大概明白您的需求。

再看回您的建议，有两种地方希望添加复制按钮

1. 划词附近，这确实对于纯鼠标操作的用户很有用，但我对 Saladit 这方面的用户比例存疑。另外也有用户不喜欢弹出小图标，所以兼顾所有人不容易，在新增入口方面我相对谨慎些。最后，这个场景可以结合其它更专注这方面的扩展。

2. 复制翻译内容
   能直接复制内容确实很方便。但是问题在于难以确定用户感兴趣的地方，因为这是一个非常私人化的选择。对于句子翻译类的结果，这是可以接受的；但是对于词典的结果，全文复制就显得有些鸡肋。所以如果要添加的话，可以考虑只对部分引擎添加。这时我更倾向于将按钮置于结果右下方，并处于隐藏状态，鼠标移上来再显示。

不知解答了您的问题没有。

**Comment by LinXueyuanStdio** [comment]
感谢回复。很用心了。非常ok。
其实我真正的需求就只是长句子的翻译复制吧。其他的只是顺带。。。
