### ISSUE TITLE
维基百科中的数学方程图片不显示

### ISSUE THREAD

**Issue by OnceThenEver** [crimx/ext-saladict#1100]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Google Chrome 81.0.4044.138（正式版本）（64 位）] 
- 沙拉查词版本: [v7.18.0] 

## 描述问题

如题，不显示数学方程图片，但其它位置的图片显示正常

## 复现步骤

1.打开独立面板
2.查询“拉普拉斯方程”
3.查看独立面板中维基百科的内容
4.展开关于该条目的定义

## 期待的正常行为

正常显示图片

## 截图

![屏幕截图(232)](https://user-images.githubusercontent.com/66708845/99136516-3bfbb680-2660-11eb-8b32-dd8c6a33afde.png)
图1⬆：独立面板中的情况，缺失图片的位置已被选中

![屏幕截图(230)](https://user-images.githubusercontent.com/66708845/99136200-a3b10200-265e-11eb-98ba-48b412abf629.png)
图2⬆：浏览器中的情况

![屏幕截图(231)](https://user-images.githubusercontent.com/66708845/99136201-a4e22f00-265e-11eb-9633-80d7484da4db.png)
图3⬆：在浏览器新标签中单独显示该图的情况

## 额外信息

以下是我的 自定义查词面板 代码

.dictPanel-Root {
  --color-brand: #f15a24 !important;
  --color-background: #000 !important;
  --color-font: #bbb !important;
  --color-divider: #fff !important;
}
.menuBar {
  background-color: #000;
}

**Comment by crimx** [comment]
![image](https://user-images.githubusercontent.com/6882794/99139331-aa497480-2672-11eb-83c9-4031e272847a.png)

这边测试没问题，检查一下你的网络。

**Comment by OnceThenEver** [comment]
和VPN有关系吗？毕竟不用梯子的话国内用不了WIKI

**Comment by crimx** [comment]
应该有关系，图片是来自 wikimedia.org 的，有的代理可能默认配置了直连。

**Comment by OnceThenEver** [comment]
但奇怪的是只有数学方程图片不显示（可能还有其他的图片类型），别的都正常，比如拉普拉斯的画像

**Comment by OnceThenEver** [comment]
破案了，我自定义的查词面板里 background 是#000，方程字母也是#000，所以重了，你测试的时候背景是白的 @crimx

**Comment by OnceThenEver** [comment]
![屏幕截图(236)](https://user-images.githubusercontent.com/66708845/100302145-ad2e5880-2fd4-11eb-9195-bc601420f0af.png)

不过，这是在清除了自定义面板代码的情况下插件自带的黑暗模式，还是看不清，希望这里可以改一下
