### ISSUE TITLE
用Firefox打开本地pdf不能启用沙拉划词

### ISSUE THREAD

**Issue by Ye-YB** [crimx/ext-saladict#1101]
## 设备信息
- 操作系统: [win0] 
- 浏览器版本: [Firefox82.0.3] 
- 沙拉查词版本: [v7.13.3] 

## 描述问题

打开网页中的pdf可以启用沙拉划词
打开本地PDF无法启用沙拉划词

## 复现步骤

1.打开本地pdf
2.问题出现：沙拉划词无法触发
3.并且打开本地PDF后，使用右键点击沙拉查词插件选择“在pdf阅读器中打开”，无法正确的打开pdf

## 期待的正常行为

打开本地pdf自动启动沙拉划词的功能

## 截图

从网页中打开pdf，可以看到沙拉查词的插件是亮的
![图片](https://user-images.githubusercontent.com/60165915/99181241-25408700-2768-11eb-9b78-79ed7f3ef699.png)
从本地打开pdf，可以看到沙拉查词的插件是暗的
![图片](https://user-images.githubusercontent.com/60165915/99181256-4012fb80-2768-11eb-9aaa-0199cd85a2a1.png)
右键点击沙拉查词，在PDF阅读器中打开
![图片](https://user-images.githubusercontent.com/60165915/99181341-c9c2c900-2768-11eb-9991-9340c0bb077d.png)

**Comment by crimx** [comment]
火狐目前不支持拦截本地链接，你可以打开沙拉查词里的 PDF 阅读器后在阅读器上方的按钮打开本地 PDF。或者结合[浏览器外划词](https://saladict.crimx.com/native.html)使用本地 PDF 阅读器。
