### ISSUE TITLE
中文首字母输入重复

### ISSUE THREAD

**Issue by 413802375** [crimx/ext-saladict#1103]
## 设备信息
- 操作系统: [] 
win10
- 浏览器版本: [] 
Google Chrome  版本 86.0.4240.111（正式版本）
- 沙拉查词版本: [] 
[v7.18.0]

## 描述问题

在系统输入法默认为中文时，首次点击查词面板并输入 第一个字母会被重复输入，删除后再次输入就不会出现这种情况

## 复现步骤

1、打开查词面板
2、点击输入框，切换到系统中文输入法
3、输入任意字符
4、输入框内重复出现首次输入的内容

## 期待的正常行为

中文输入时首个字符不会重复输入

## 截图

![image](https://user-images.githubusercontent.com/48540266/99233917-d1e53c00-282e-11eb-92d4-7731f820c86e.png)
因面板在输入时会出现1词汇联想，截图无法捕捉输入法面板框

## 额外信息

暂无

**Comment by crimx** [comment]
Duplicate of #1096

**Comment by crimx** [comment]
感谢反馈
