### ISSUE TITLE
Edge版什么时候可以与原生的PDF阅读配合呐，就想要横滚模式……

### ISSUE THREAD

**Issue by wolfan** [crimx/ext-saladict#1106]
没有横滚的PDF不是好PDF阅读器……

**Comment by crimx** [comment]
Edge 应该也可以用[浏览器外划词](https://saladict.crimx.com/native.html)。

**Comment by wolfan** [comment]
> Edge 应该也可以用[浏览器外划词](https://saladict.crimx.com/native.html)。

主要是想用沙拉的PDF 横滚模式。

**Comment by crimx** [comment]
按上面的教程做就不再限制阅读器了，你可以用自己喜欢的阅读器。

目前沙拉查词的 PDF 阅读器基于 [PDF.js](https://github.com/mozilla/pdf.js/) ，相关的功能需求可以前往该项目。
