### ISSUE TITLE
划译PDF文档时鼠标选中内容不稳定，光标经常会跳跃

### ISSUE THREAD

**Issue by huimeitianya** [crimx/ext-saladict#1110]
和QQ浏览器的划译功能相比，鼠标选中内容时不稳定，会跳跃，经常会选中比想要选中的文字更多的内容，甚至一整段大段文字会被选中。。。。刚刚开始探索萨拉查词插件，表示上手难度要很大，学习成本很高，要花好长时间去设置。另外，备选的词典眼花缭乱，死了好多，只有有道翻译可以很敏捷地反应。希望能做得更加轻量化。交互逻辑有待于进一步优化

**Comment by crimx** [comment]
[PDF 相关问题及答复](https://saladict.crimx.com/q&a.html#%E9%97%AE%3A-pdf-%E5%88%92%E8%AF%8D%E5%AD%97%E7%AC%A6%E6%98%BE%E7%A4%BA%E4%B8%8D%E5%AF%B9%EF%BC%88%E5%A6%82-f-%E4%B8%8E-%C6%92%EF%BC%89%2F-pdf-%E5%88%92%E8%AF%8D%E6%8D%A2%E8%A1%8C%E7%9A%84%E5%8D%95%E8%AF%8D%E7%B2%98%E8%BF%9E%E5%9C%A8%E4%B8%80%E8%B5%B7%E3%80%82)。
