### ISSUE TITLE
在扩展程序栏打开的面板中可以添加一个固定按钮

### ISSUE THREAD

**Issue by AlanCutFlim** [crimx/ext-saladict#1111]
## 设备信息
- 操作系统: [Mac OS Catelina 10.15.4] 
- 浏览器版本: [Chrome86] 
- 沙拉查词版本: [v7.18.0] 

## 请描述目前使用沙拉查词遇到什么不便

希望在扩展程序栏打开的面板中有固定按钮

## 理想情况下，沙拉查词应该怎么做

在图示的地方会有一个固定按钮
![image](https://user-images.githubusercontent.com/50612752/99981443-5cf0a400-2de4-11eb-9da6-2a4a33e501b4.png)

## 替代方案

鼠标右键，两次按 `command` 打开的面板都有固定按钮

## 额外信息

无

**Comment by crimx** [comment]
这个窗口是无法固定的

**Comment by AlanCutFlim** [comment]
请问还有什么方法可以打开一个可以钉住的面板？现在好像只有通过点击用鼠标划取一段文字后出现的沙拉查词图标，打开的面板才可以钉住并拖动。

**Comment by crimx** [comment]
[这里](https://saladict.crimx.com/q&a.html#%E9%97%AE%EF%BC%9A%E7%8B%AC%E7%AB%8B%E7%AA%97%E5%8F%A3%E6%9F%A5%E8%AF%8D%E9%9D%A2%E6%9D%BF%E8%83%BD%E5%90%A6%E9%92%89%E4%BD%8F%E7%BD%AE%E9%A1%B6%EF%BC%9F)

**Comment by AlanCutFlim** [comment]
感谢，我去看看有没有固钉插件
