### ISSUE TITLE
彩云小译，限免次数已不足，我成为彩云的vip后就能正常使用了吗？

### ISSUE THREAD

**Issue by teraStars** [crimx/ext-saladict#1113]
我在使用彩云小译的网页翻译功能时，提示，限免次数已不足，我成为彩云的vip后就能正常使用这个功能了吗？

**Comment by crimx** [comment]
是的，这是彩云小译的功能，沙拉查词仅提供了接入，彩云小译所有登陆功能都支持。

**Comment by teraStars** [comment]
> 是的，这是彩云小译的功能，沙拉查词仅提供了接入，彩云小译所有登陆功能都支持。

谢谢
