### ISSUE TITLE
CNKI翻译助手是不是挂掉了？

### ISSUE THREAD

**Issue by bio-er** [crimx/ext-saladict#1114]
## 设备信息
- 操作系统: [win10] 
- 浏览器版本: [chrome 版edge87正式版 ] 
- 沙拉查词版本: [7.18] 

## 描述问题
CNKI翻译助手的接口是不是挂了？翻译词汇词组短句时，CNKI翻译助手都没有任何内容。
CNKI翻译助手官网最近变化了，是不是导致接口挂掉了？

**Comment by Cute-Pig** [comment]
同挂了，cnki翻译助手改版了

**Comment by crimx** [comment]
感谢反馈，我周末看看

**Comment by niecailong** [comment]
请赶快修复一下，CNKI对我们看论文帮助很大，谢谢。

**Comment by niecailong** [comment]
> 感谢反馈，我周末看看

请快点修复吧，看文献真的很需要。

**Comment by crimx** [comment]
这个已经在 #1201 修复。
