### ISSUE TITLE
多个词典无响应

### ISSUE THREAD

**Issue by ENIAC-Y** [crimx/ext-saladict#1117]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Edg87] 
- 沙拉查词版本: [7.18.0] 

## 描述问题

使用沙拉查词只有柯林斯高阶词典有结果，必应词典、有道词典、百度翻译均无响应

## 复现步骤

1. 打开网站http://www.kekenet.com/cet6/202010/619589_3.shtml
2. 点击Section C的Passage One中的microcosm、society都是此结果

## 期待的正常行为

所有词典都有翻译结果

## 截图

![沙拉查词问题](https://user-images.githubusercontent.com/66289057/100492383-61abb400-3166-11eb-9fa6-309a330ccedd.jpg)

**Comment by crimx** [comment]
![image](https://user-images.githubusercontent.com/6882794/100492440-f1e9f900-3166-11eb-90ae-5d7168562bb6.png)

测试没有问题，点一下词典标题检查你的网络。
