### ISSUE TITLE
剑桥词典响应速度显著低于其他词典

### ISSUE THREAD

**Issue by OnceThenEver** [crimx/ext-saladict#1118]
## 设备信息
- 操作系统: [win10] 
- 浏览器版本: [Chrome 81.0.4044.138（正式版本）（64 位）] 
- 沙拉查词版本: [v7.18.0] 

## 描述问题

绝大部分时候，其他词典（包括柯林斯、朗文、韦氏、Lexico、有道、WiKi等）可在5秒甚至3秒内显示结果

而剑桥平均需要10秒

## 复现步骤

在弹出窗口或独立面板中查询任意一词后，将剑桥的加载速度和其他词典对比

## 截图

![截图1](https://user-images.githubusercontent.com/66708845/100494346-d1786980-317b-11eb-8fe9-747a6b81b4cc.png)
图1：加载中

![截图2](https://user-images.githubusercontent.com/66708845/100494421-6d09da00-317c-11eb-9adc-0bfed540f381.png)
图2：然后干脆放弃加载

![截图3](https://user-images.githubusercontent.com/66708845/100494427-7d21b980-317c-11eb-9ed7-7bcad95bb8db.png)
图3：查询多次才勉强显示，说明剑桥里是有这个词的

**Comment by crimx** [comment]
你点一下剑桥词典标题打开官网看看速度？如果使用科学上网什么的试试代理剑桥词典的网址。

**Comment by OnceThenEver** [comment]
官网速度也一个样

我用的代理可以设置为 仅代理被墙流量 或 代理所有流量，刚才切换到 代理所有流量 后确实明显快了不少

不过，同样是外国网站，为什么就剑桥这么慢呢？

**Comment by crimx** [comment]
> 刚才切换到 代理所有流量 后确实明显快了不少

说明是你的网络问题。

> 同样是外国网站，为什么就剑桥这么慢呢？

数据包长途跋涉，中间任何一个环节出问题都会影响速度。

> 我用的代理可以设置为 仅代理被墙流量 或 代理所有流量

主流代理都应该支持针对特定网址设置的，你可以自行搜索一下。

**Comment by drcege** [comment]
我发现谷歌翻译有类似的问题，在浏览器中打开网页时，网页出现较快，但是沙拉查词里有时就很慢。

经过调试发现，谷歌翻译的主页面会很快加载出来，但有些加载项因为没被加入到代理里，所以就会请求超时（比如 *.google-analytics.com 等）。把这些相关请求都加入到代理中，或者开启全局代理，沙拉的谷歌翻译就会变快了。

猜测沙拉查词可能是同步请求模式，必须等待所有请求都成功了才返回结果？可能剑桥词典也是这个原因？ @crimx

**Comment by crimx** [comment]
`*.google-analytics.com` 在沙拉查词中不会加载，所以不会影响到网速。

> 猜测沙拉查词可能是同步请求模式，必须等待所有请求都成功了才返回结果

请求是异步的，所有需要的资源加载完才能得到结果，所以必然要等。但沙拉查词只会请求必要的资源，比打开网站需要的要少一些，当然这些资源也可能来自其它域名。
