### ISSUE TITLE
[Bug report] 拼音的第一个字符被当做英文字符输入

### ISSUE THREAD

**Issue by liuhao326** [crimx/ext-saladict#1119]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome87] 
- 沙拉查词版本: [v7.18.0] 

## 描述问题

在独立窗口或查词窗口中使用拼音输入中文时，拼音的第一个字符会被当做英文字符输入，结果导致中文输入不正常。

## 复现步骤

<details>
			<summary>查词面板</summary>

1. 在设置页面的`右上弹框`选项下设置`点击地址栏旁图标`动作为`显示查词面板`并选择`预先加载`选项为`剪切板`
2. 确保当前输入法为中文拼音且剪切板内容不为空
2. 点击地址栏旁扩展图标（此时查词面板打开，焦点位于输入框且输入框中填入了剪切板上的内容）
3. 尝试在查词面板中输入中文（以`输入`为例）
4. 问题出现：这时候会发现`shuru`的首字符（s）将会像输入英文一样出现在输入框中（而不是作为拼音的一部分）

</details>

<details>
			<summary>快捷键打开的独立查词窗口</summary>

1. 设置好`在独立窗口中搜索剪贴板内容`的快捷键（比如`Ctrl + L`）
    
   ![image](https://user-images.githubusercontent.com/51501079/100495599-f377e900-3187-11eb-8cba-daafe6f81297.png)

2. 确保当前输入法为中文拼音且剪切板内容不为空
2. 按下设置好的快捷键（此时查词独立窗口打开，焦点位于输入框且输入框中填入了剪切板上的内容）
3. 尝试在查词独立窗口中输入中文（以`输入`为例）
4. 问题出现：这时候会发现`shuru`的首字符（s）将会像输入英文一样出现在输入框中（而不是作为拼音的一部分）

</details>

## 期待的正常行为

键入`shuru`后整个字符串都应该作为拼音。

## 截图

<details>
			<summary>Gif</summary>

  ![input](https://user-images.githubusercontent.com/51501079/100495403-726c2200-3186-11eb-91b2-e1f05e86b0c7.gif)

  ![input2](https://user-images.githubusercontent.com/51501079/100495644-6c774080-3188-11eb-937b-4732ac1d7e3f.gif)

</details>

## 额外信息

剪切板为空时没有这个问题

**Comment by crimx** [comment]
Duplicate of #1103
