### ISSUE TITLE
找不到上个版本的海词词源了

### ISSUE THREAD

**Issue by YrracOwl** [crimx/ext-saladict#112]
# 类型
- 建议：能不能把上个版本的海词词源给加回来……那个用饼状图来展示很直观的

**Comment by nameldk** [comment]
嗯，更新后海词词源没有了。

**Comment by YrracOwl** [comment]
好吧，感谢。


来自 魅蓝 note

-------- 原始邮件 --------
发件人："dengke.li" <notifications@github.com>
时间：周四 5月31日 09:59
收件人：crimx/ext-saladict <ext-saladict@noreply.github.com>
抄送：YrracOwl <deadly_silence@163.com>,Author <author@noreply.github.com>
主题：Re: [crimx/ext-saladict] 找不到上个版本的海词词源了 (#112)

**Comment by crimx** [comment]
嗨，考虑到海词[版权](http://about.dict.cn/copyrightstatement?cur=1)比较严厉，以及为了显示这个饼状图其实要引入一大串东西，所以还是撤下了。

**Comment by YrracOwl** [comment]
原来如此，十分感谢你做的这个取词插件


来自 魅蓝 note

-------- 原始邮件 --------
发件人：CRIMX <notifications@github.com>
时间：周四 5月31日 11:26
收件人：crimx/ext-saladict <ext-saladict@noreply.github.com>
抄送：YrracOwl <deadly_silence@163.com>,Author <author@noreply.github.com>
主题：Re: [crimx/ext-saladict] 找不到上个版本的海词词源了 (#112)

**Comment by funway** [comment]
期待下一个版本能重新收录海词词典，那个饼图实在太好用了。🙏
