### ISSUE TITLE
在PDF中无法正常查词

### ISSUE THREAD

**Issue by Aerotic** [crimx/ext-saladict#1124]
## 设备信息
- 操作系统: [Ubuntu 20.04.1 LTS] 
- 浏览器版本: [Chrome 84.0.4147.105 (Official Build) (64-bit)] 
- 沙拉查词版本: [v7.18.0] 

## 描述问题

所有页面无法正常查词  , 同时，拓展栏中，沙拉查词的logo变灰，右键点开后能看到
`can't read or change stie's data`
可以确定的是，我在chrome 中给了沙拉查词权限

## 复现步骤

打开任何页面都是这样

## 期待的正常行为

选中单词后单词附近出现logo点击即可查词

**Comment by crimx** [comment]
> 打开任何页面都是这样

给一个例子？

浏览器自带的 PDF 浏览器或者其它原生应用需要配合[浏览器外划词](https://saladict.crimx.com/native.html)使用。沙拉查词自带一个 PDF 阅读器，见[使用说明](https://saladict.crimx.com/notice.html)。
