### ISSUE TITLE
推荐小牛翻译

### ISSUE THREAD

**Issue by Aerotic** [crimx/ext-saladict#1125]
## 词典名称以及链接

小牛翻译
https://niutrans.com/
## 单词举例

这是一个类似于谷歌翻译的网站，个人实践表明其翻译准确度，尤其是在计算机领域，比谷歌翻译更准

## 额外信息

这是一个类似于谷歌翻译的网站，个人实践表明其翻译准确度，尤其是在计算机领域，比谷歌翻译更准

**Comment by moon290** [comment]
不知道是否可以接入DeepL呢？也是在计算机领域效果更好

**Comment by crimx** [comment]
Duplicate of #705 #624
