### ISSUE TITLE
打开独立窗口后划词失效

### ISSUE THREAD

**Issue by Higurashi-kagome** [crimx/ext-saladict#1126]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome87]
- 沙拉查词版本: [v7.18.0]

## 描述问题

使用浏览器快捷键打开独立窗口后划词失效。

## 复现步骤

1. 将翻译方式设置为在选中内容旁显示图标
2. 设置打开独立窗口的快捷键
3. 快捷键呼出独立查词窗口
4. 在浏览器中划词
5. 问题出现：划词不显示图标

## 期待的正常行为

或许应该将划词内容发送到独立窗口或另开窗口进行翻译。

## 截图

<details>
<summary>Details</summary>

![gif](https://user-images.githubusercontent.com/51501079/100687820-fa873d00-33bb-11eb-897d-e51e7639c6ef.gif)

</details>

**Comment by crimx** [comment]
设置-快捷查词-打开独立窗口设置-网页划词。默认是按住 ctrl 触发，这个很多人不知道，下版改成直接触发吧。

**Comment by lixiao1290** [comment]
设置保存失败
QuotaExceededError: storage.sync API call exceeded its quota limitations.
