### ISSUE TITLE
CNKI翻译助手无响应

### ISSUE THREAD

**Issue by hwk0809** [crimx/ext-saladict#1129]
## 设备信息
- 操作系统: [win10] 
- 浏览器版本: [Chrome 版本 87.0.4280.66（正式版本） （32 位）] 
- 沙拉查词版本: [v7.18.0] 

## 描述问题

翻译PDF的时候，CHKI翻译助手内容不显示，但是到网页中翻译会正常显示，在沙拉中点CHKI翻译助手弹出的网页也无法正常打开，谷歌和有道的翻译均显示正常

## 复现步骤

1. 在chorm中PDF阅读器打开或者自己的PDF用Quicker对PDF划词翻译
2. CHKI翻译助手不显示内容
3. 点开其中的CHKI翻译助手页面无法打开，但是输入网址https://dict.cnki.net/index#可正常打开搜索

## 期待的正常行为

能正常显示CHKI翻译结果

## 截图

![image](https://github.com/hwk0809/Image/blob/main/1.png)
![image](https://github.com/hwk0809/Image/blob/main/2.png)
![image](https://github.com/hwk0809/Image/blob/main/3.png)
![image](https://github.com/hwk0809/Image/blob/main/4.png)

**Comment by crimx** [comment]
Duplicate of #1114

**Comment by niecailong** [comment]
请尽快修复吧，看专业文献帮助很大。
