### ISSUE TITLE
不流畅

### ISSUE THREAD

**Issue by general-lee** [crimx/ext-saladict#113]
新版本使用没有上个版本流畅，不开过渡动画有卡顿现象，就像安卓手机不跟手一样。上个版本感觉很完美，不知道是不是加了有道词典的原因。

**Comment by general-lee** [comment]
哦，还有 点开图标后，字体开始模糊，然后两秒后变清晰。。

**Comment by crimx** [comment]
请按根据模板描述问题。模糊是因为 Chrome 的 GPU 加速在某些设备上的问题。可尝试更新最新版。

**Comment by crimx** [comment]
新版已发布，有问题欢迎另开 issue 。再次感谢提供反馈。
