### ISSUE TITLE
Chrome打开本地pdf不能默认用沙拉查词打开

### ISSUE THREAD

**Issue by jiang54** [crimx/ext-saladict#1130]
## 设备信息
- 操作系统: [] windows
- 浏览器版本: [] Chrome 87
- 沙拉查词版本: [] v.7.180

## 描述问题

Chrome打开本地pdf不能默认用沙拉查词打开

## 期待的正常行为

能用沙拉打开本地pdf

## 截图

![image](https://user-images.githubusercontent.com/24377958/100803065-9da08b00-347e-11eb-8e67-8c0b228a6a70.png)

**Comment by crimx** [comment]
请阅读[初次使用注意事项](https://saladict.crimx.com/notice.html)。
