### ISSUE TITLE
edge商店无法安装，下载完毕后显示错误

### ISSUE THREAD

**Issue by Gsw511** [crimx/ext-saladict#1138]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: []

**Comment by crimx** [comment]
显示什么错误？？一般是网络问题，下载中断了。

**Comment by Gsw511** [comment]
您看一下这个情况











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "crimx/ext-saladict"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月5日(星期六) 晚上9:20
收件人:&nbsp;"crimx/ext-saladict"<ext-saladict@noreply.github.com&gt;;
抄送:&nbsp;"粉饰"<1659350617@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [crimx/ext-saladict] edge商店无法安装，下载完毕后显示错误 (#1138)





 
显示什么错误？？一般是网络问题，下载中断了。

**Comment by Gsw511** [comment]
> 显示什么错误？？一般是网络问题，下载中断了。
