### ISSUE TITLE
希望增加失焦后自动关闭窗口功能

### ISSUE THREAD

**Issue by justwezzz** [crimx/ext-saladict#114]
![test](https://user-images.githubusercontent.com/1901634/40759739-f53d0734-64c5-11e8-99a0-22823d72ce72.gif)
现在在未配置钉住窗口的设置下，失焦没有关闭窗口，希望增加一个配置。

**Comment by crimx** [comment]
你好，应该关闭的。请根据模板描述问题。

**Comment by crimx** [comment]
新版已发布，有问题欢迎另开 issue 。再次感谢提供反馈。
