### ISSUE TITLE
请问将该扩展移植到VSCode上应该采取什么样的技术方案？

### ISSUE THREAD

**Issue by ffffansz** [crimx/ext-saladict#1140]
经常需要在VSCode中阅读一些README之类的文档，想移植成一个VSCode插件。

不知道作者对这块有没有什么了解，是否能指出一些技术方向？

感谢作者的工作，非常棒的项目！

**Comment by ffffansz** [comment]
一个work around是通过浏览器打开README来阅读...暂时放弃在VSCode上使用的念头。

**Comment by crimx** [comment]
可通过[浏览器外划词](https://saladict.crimx.com/native.html)。

**Comment by ffffansz** [comment]
> 可通过[浏览器外划词](https://saladict.crimx.com/native.html)。

好的谢谢，我去尝试一下~
