### ISSUE TITLE
在Notion页面中，复制查词结果失败

### ISSUE THREAD

**Issue by hqyyqh** [crimx/ext-saladict#1141]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [edge 87] 
- 沙拉查词版本: [7.18.0] 

## 描述问题

在 [Notion](https://www.notion.so/) 页面查询单词后，复制查词结果失败。
其它网页可以正常复制（已开启写入剪贴板权限）。

## 复现步骤

1. 打开页面 [https://www.notion.so/precipitation-d0f064ceceb0484e99744c53371977e8](https://www.notion.so/precipitation-d0f064ceceb0484e99744c53371977e8)，查词 `precipitation`

![image](https://user-images.githubusercontent.com/38676455/101460525-aa3c4c00-3974-11eb-96e0-b60cf8b1e716.png)

2. 选中必应词典翻译结果，复制，在编辑器内粘贴结果为 `precipitation`

![image](https://user-images.githubusercontent.com/38676455/101460901-2898ee00-3975-11eb-8097-924be92f4497.png)

3. 其他页面复制粘贴正常（例如当前反馈页面）。

![image](https://user-images.githubusercontent.com/38676455/101461282-9d6c2800-3975-11eb-8a30-ccb7354d14ed.png)

## 期待的正常行为

可以正常复制 Notion 页面中，沙拉查词的查询结果

**Comment by crimx** [comment]
铅笔哥，这个貌似是因为 Notion 的页面拦截了复制的操作，然后自行写数据到剪贴板中。这个目前无解。如果取消到它的这个行为可能会导致其它问题。只能通过浏览器外的方式复制了。

**Comment by hqyyqh** [comment]
> 铅笔哥，这个貌似是因为 Notion 的页面拦截了复制的操作，然后自行写数据到剪贴板中。这个目前无解。如果取消到它的这个行为可能会导致其它问题。只能通过浏览器外的方式复制了。

了解了，感谢。浏览器外复制确实稳妥✔
