### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by FullStack1994** [crimx/ext-saladict#1144]
## 设备信息
- 操作系统: [win10] 
- 浏览器版本: [chrome87] 
- 沙拉查词版本: [v7.18.0] 

## 描述问题

控制台报错

## 复现步骤

暂时无法复现，无意中触发

## 截图

![image](https://user-images.githubusercontent.com/58390198/101749906-413a0d00-3b09-11eb-95ba-bdb30ccd01dd.png)

**Comment by crimx** [comment]
嗯嗯，可能选到什么特殊元素了吧，应该不影响。感谢反馈。
