### ISSUE TITLE
中文输入法首字母冲突

### ISSUE THREAD

**Issue by Loa5** [crimx/ext-saladict#1149]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome86] 
- 沙拉查词版本: [v7.18.0] 

## 描述问题

Chrome右上角点出查词窗口（或划词翻译），每次查询后重新输入单词时：
1. 搜狗输入法
拼音第一个字母总是被直接输入到输入框，而不是作为拼音的一部分。
2. Win10中文输入法
拼音的第一个字母总是被直接输入到输入框（且第一个字母会被重复两次），而不是作为拼音的一部分。

## 复现步骤

1. 打开www.github.com（实际上是所有页面）
2. 点击Chrome右上角插件或划词翻译，出现弹窗
3. 每次查询翻译前，使用输入法第一次输入内容时
4. 问题出现

## 截图

![image](https://user-images.githubusercontent.com/29650742/101982759-fe1a9e00-3cb0-11eb-9db8-0890caca2db1.png)
![image](https://user-images.githubusercontent.com/29650742/101982764-0e327d80-3cb1-11eb-9b42-7d6fbc891909.png)

## 额外信息

1. 在第一次输入内容前，如果使用剪切、粘贴、回退这类修改输入框内容的操作，问题就不会出现。
2. 不确定是否是软件问题，事实上这个问题很早就出现了，之前Chrome还在70+版本，沙拉查词也是去年的版本。

**Comment by dongwa** [comment]
我也遇到了，部分输入法会遇到这个问题，有点烦心，后来换了个输入法好一点了

**Comment by Loa5** [comment]
确实，不同输入法表现的BUG也不一样，可能确实有输入法能正常输入。
不过我还是打算等作者更新解决吧，今天注意到之前已经有人和作者反馈过这个BUG了。
PS. 我不知道怎么关闭该问题，等作者操作

**Comment by crimx** [comment]
这个问题迟些会修复，年底比较忙🙏

**Comment by Loa5** [comment]
这对我个人是小BUG，瑕不掩瑜。而且我之前也这么操作好久了，再操作一段时间也问题不大。
作者大大辛苦了🙏

**Comment by gaorchen** [comment]
可以肯定的是此前的旧版本没有这个问题

**Comment by roy2651** [comment]
我想问的是一般是什么问题导致了这类的情况，我也遇到了，但是找不到问题的原因

**Comment by crimx** [comment]
是我程序的 bug 😛

**Comment by roy2651** [comment]
> 是我程序的 bug 😛。DOM 被意外销毁了。

有commit嘛，我想看看如何解决的，我这边使用到了一个三方库也有类似的问题，我想查一查
我现在就遇到每次在新的一行光标第一次focus的是就遇到打ceshi 出现c字母上屏幕，输入法就变成eshi，也只有在chrome里面遇到，Safari跟edge都没有遇到

**Comment by crimx** [comment]
基本确定问题，但还没时间修复…… 

应该是某个 React 组件更新时被错误销毁了，导致 DOM 也被销毁。

**Comment by drcege** [comment]
还没更新吗，这个问题困扰很久了。。用起来真让人头疼

**Comment by zsedcbm** [comment]
选项配置-》右上弹框-》预先加载内容  改为 无 就不会出现这个问题了。
@drcege

**Comment by JER-ry** [comment]
> 
> 
> 选项配置-》右上弹框-》预先加载内容 改为 无 就不会出现这个问题了。
> @drcege

确实有效, 暂时先这样吧.

**Comment by sysu18301047** [comment]
> > 选项配置-》右上弹框-》预先加载内容 改为 无 就不会出现这个问题了。
> > @drcege
> 
> 确实有效, 暂时先这样吧.

我的反而无效，不过我用的是独立窗口
右上弹框 选择了独立窗口
快捷查词 关闭了预加载
快捷查词/独立窗口 关闭了响应划词
然后问题依然有（环境：win10，edge 89.0.774.63，salatdict 7.18.1，ms自带中文输入法）
话说，crimx你这个问题有个特性跟我在原神里看见的一样：
你看到有两个h，但是你删去（backspace）的时候两个都被删掉。
大佬，真的，这个bug太影响效率了，今天实在是忍不住才过来反馈...
不过还是很感谢有这个生产力工具！祝你身体健康，万事如意，思如泉涌。

**Comment by zsedcbm** [comment]
@sysu18301047  快捷查词里面的预先加载改成无试一下

**Comment by tryqtyl** [comment]
我也遇到了这个问题，看来不是个例呀，我还折腾了好几遍输入法哈哈哈哈。希望作者大佬有时间关注一下这个问题，顺祝时祺，万事胜意。

**Comment by crimx** [comment]
已修复，等待新版发布。
