### ISSUE TITLE
Saladict 内部连续查词功能

### ISSUE THREAD

**Issue by alexya** [crimx/ext-saladict#115]
## 平台：包括操作系统和 Chrome 版本
OSX 10.11.3 (15D21)
Windows 10.0 (build 10240)

Chrome Version Version 
66.0.3359.181 (Official Build) (64-bit)
69.0.3445.2 (Official Build) canary (64-bit)

## 类型：错误？建议？
1. 我记得上个版本，每次查词的时候，Bing dict 展开，都有一个pie图，能够显示该单词的几个翻译的使用率是多少？哪种是最常用的释译。
2. 在Saladict的展开的英文解释中，如果又发现了一个不认识的单词，双击后，好像会自动继续查词。点击Saladict的左上角返回，还能够再返回到上一次的查词。现在这个功能好像没有了......

**Comment by crimx** [comment]
参见 #112 #92

**Comment by alexya** [comment]
看了一下，这两功能，在新版都没有了啊...... 
好难过T_T

**Comment by crimx** [comment]
词典里的链接都是可以自动查词的，应该可以满足大部分需要。

**Comment by sonyxu** [comment]
私以为 连续查词可以作为一个设置选项 不知道可否 作者大大请酌情考虑

**Comment by crimx** [comment]
大更新 bug 已补完，有空再考虑将连续查词补回来

**Comment by crimx** [comment]
新版已添加。
