### ISSUE TITLE
在钉住面板之后，在添加生词本时，会导致编辑完单词后，面板消失，需要重新打开。

### ISSUE THREAD

**Issue by guokuan** [crimx/ext-saladict#116]
使用相关的问题请确保先看了 Wiki 《划词翻译食用方式》 <https://github.com/crimx/crx-saladict/wiki> 。

不能划词的网站请提供具体链接。刚安装扩展后已经打开的页面需要刷新一遍以加载词典。

如果是查词结果不正确或无结果，请先点击结果左上的词典图标跳转到词典网页，查看是否为自身网络问题。

因安全问题，chrome 商店页面、自带的 PDF 页面以及其它扩展的页面是不能划词的。可用点击图标或三按 ctrl 快速查词，本扩展自带 PDF 阅读器。

请根据模板描述问题，以便作者理解和解决。

## 平台：包括操作系统和 Chrome 版本
windows 最新版本

## 类型：错误？建议？

希望在编辑生词时，钉住的面板不会在编辑完之后消失。

## 期待：理想情况下扩展应该怎么做？
希望钉住的面板不随单词编辑而消失，或者应该具有一个开启和关闭的设定。

**Comment by crimx** [comment]
嗯，谢谢反馈，这个需要优化。

**Comment by guokuan** [comment]
还是非常感谢您做出的插件，很棒。

**Comment by crimx** [comment]
新版已发布，有问题欢迎另开 issue 。再次感谢提供反馈。
