### ISSUE TITLE
划词后谷歌翻译没有结果，其他翻译有结果

### ISSUE THREAD

**Issue by HY1492** [crimx/ext-saladict#1160]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome87] 
- 沙拉查词版本: [v7.18.0] 

## 描述问题

划词后谷歌翻译没有结果，其他翻译有结果

## 复现步骤

1. 打开谷歌浏览器
2. 进入某网页（鼠标划词翻译已开启）
3. 选中一段英文
4. 弹出查词面板，谷歌翻译那一栏没有显示结果，而其他翻译有结果
5. 点击谷歌翻译进入官网，却可以正常翻译

## 期待的正常行为

划词后谷歌翻译可以显示结果

## 截图

![沙拉](https://user-images.githubusercontent.com/73172021/102680149-c780de00-41f0-11eb-908b-0eed3907f089.PNG)
![谷歌结果](https://user-images.githubusercontent.com/73172021/102680154-cd76bf00-41f0-11eb-95e2-a01ecb41f054.PNG)

## 额外信息

比较少的时候谷歌翻译会有结果 ，但多数时候没有，而点进官网可以正常翻译，想知道是查词程序和谷歌浏览器的接口问题，还是浏览器的问题

**Comment by lgjj1999** [comment]
加一

**Comment by Theyearling** [comment]
+1 最近才出现这个问题的

**Comment by crimx** [comment]
谷歌翻译最近的灰度测试新版的页面，有一定几率会遇到。逆向需要点时间。

**Comment by slzms** [comment]
> ## 设备信息
> * 操作系统: [Win10]
> * 浏览器版本: [Chrome87]
> * 沙拉查词版本: [v7.18.0]
> 
> ## 描述问题
> 划词后谷歌翻译没有结果，其他翻译有结果
> 
> ## 复现步骤
> 1. 打开谷歌浏览器
> 2. 进入某网页（鼠标划词翻译已开启）
> 3. 选中一段英文
> 4. 弹出查词面板，谷歌翻译那一栏没有显示结果，而其他翻译有结果
> 5. 点击谷歌翻译进入官网，却可以正常翻译
> 
> ## 期待的正常行为
> 划词后谷歌翻译可以显示结果
> 
> ## 截图
> ![沙拉](https://user-images.githubusercontent.com/73172021/102680149-c780de00-41f0-11eb-908b-0eed3907f089.PNG)
> ![谷歌结果](https://user-images.githubusercontent.com/73172021/102680154-cd76bf00-41f0-11eb-95e2-a01ecb41f054.PNG)
> 
> ## 额外信息
> 比较少的时候谷歌翻译会有结果 ，但多数时候没有，而点进官网可以正常翻译，想知道是查词程序和谷歌浏览器的接口问题，还是浏览器的ji

**Comment by slzms** [comment]
加一，我的还包括腾讯翻译君和搜狗反应

**Comment by slzms** [comment]
加一，我的还包括腾讯翻译君和搜狗翻译

**Comment by edwinLi-xuewei** [comment]
我现在谷歌、有道、必应翻译都没有结果了，平时就用这三个，现在都不能用了

**Comment by Douerww** [comment]
+1，我的谷歌翻译也挂了（chrome浏览器）

**Comment by anklcaptain** [comment]
我的翻译倒是都正常，但是谷歌翻译的发音按钮消失很久了，请问有类似情况的吗

**Comment by qwer133245** [comment]
+1 chrome出现同样问题 版本 87.0.4280.88（正式版本） （64 位）

**Comment by jinmingzhuo** [comment]
+1, 好多天了，edge浏览器（chromium内核）

**Comment by crimx** [comment]
Duplicate of #1085
