### ISSUE TITLE
腾讯翻译君 翻译日文时没有结果

### ISSUE THREAD

**Issue by lllbin1** [crimx/ext-saladict#1167]
原网页可以翻译，希望修复

其他语言正常

**Comment by crimx** [comment]
这个有可能是语言识别的问题，你点一下词典标题旁的菜单按钮看看当前识别的语言是什么。

如果只有汉子的话默认是识别为中文，在词典设置中可以针对腾讯翻译君调整汉子识别语言。

**Comment by crimx** [comment]
经测试确认是 bug
