### ISSUE TITLE
pdf翻译断行

### ISSUE THREAD

**Issue by liuyun198833** [crimx/ext-saladict#1168]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 请描述目前使用沙拉查词遇到什么不便

翻译pdf时文件时应该把每行回车去掉后翻译。

**Comment by crimx** [comment]
![image](https://user-images.githubusercontent.com/6882794/103078770-81bb7f80-460d-11eb-9a53-c7180c269bcb.png)

在对应的机器翻译词典中设置

**Comment by flespark** [comment]
这个保留换行的设置在哪呀，最新的chrome版本（7.18.1）中找不到😳

**Comment by crimx** [comment]
在需要配置的机器翻译中

**Comment by flespark** [comment]
找到了，可以在词典设置->已选词典->不同机器翻译平台的单独配置中。但是这里的不保留换行只对浏览器内的网页和沙拉内置的pdf阅读器起作用，可以添加配置项对剪贴板内容也生效吗

**Comment by crimx** [comment]
剪贴板目前做不到判断是否来自 PDF。

**Comment by crimx** [comment]
你可以新建一个浏览器外PDF专用的情景模式，然后开启全保留换行。

**Comment by flespark** [comment]
不做判断，我就想翻以前删去剪贴板中换行，浏览器外pdf翻译只能通过剪贴板吧。还有我发现一个问题，设置了保留换行内置pdf阅读会把换行前的空格也删掉，例如这个的frowned upon合成一个单词了
![](https://gitee.com/flespark/open-pixel-blocks/raw/master/screenshoot/saladict_bug1.jpg)

**Comment by crimx** [comment]
你可以把PDF文字复制粘贴到评论框这里看看有无空格？

**Comment by flespark** [comment]
But such combinations of modifications to several objects in one go is generally frownedupon. 
哦，本来就只是一个换行，那就功能就需要根据结尾是否为连字符来区分了

**Comment by crimx** [comment]
评论框是一个纯文本编辑器，所以如果复制过来也是连着的话说明原来也是连着的。具体原因见[这里](https://saladict.crimx.com/q&a.html#%E9%97%AE%3A-pdf-%E5%88%92%E8%AF%8D%E5%AD%97%E7%AC%A6%E6%98%BE%E7%A4%BA%E4%B8%8D%E5%AF%B9%EF%BC%88%E5%A6%82-f-%E4%B8%8E-%C6%92%EF%BC%89%2F-pdf-%E5%88%92%E8%AF%8D%E6%8D%A2%E8%A1%8C%E7%9A%84%E5%8D%95%E8%AF%8D%E7%B2%98%E8%BF%9E%E5%9C%A8%E4%B8%80%E8%B5%B7%E3%80%82)。

**Comment by flespark** [comment]
所以内置的pdf阅读器并不好使啦，用外置pdf阅读器（sumatruapdf）复制出来就保留了换行。我希望通过剪贴板翻译外置pdf复制内容时候，能先把连字符换行符按情况处理一下
