### ISSUE TITLE
添加单词，是否可以支持自动填入翻译

### ISSUE THREAD

**Issue by ciknight** [crimx/ext-saladict#117]
如下图所示，是否可以支持自动填入翻译

![image](https://user-images.githubusercontent.com/6505138/40768889-222f4568-64e9-11e8-864c-20b533441a67.png)

**Comment by crimx** [comment]
动动手丰衣足食，送到嘴边的往往不懂得珍惜。请尊重每个单词的灵魂，烙下实在的印记。（误 :smile:）

原因是无法准确判断单词在当前上下文的翻译。与其随便搪塞个翻译，不如空着。因为最后还是要导出来背的，那么手动整理这步省不了。否则要么是在记忆错误的内容，要么是添加了无用的噪音，违背了[最小信息原则](https://www.supermemo.com/en/articles/20rules#minimum%20information%20principle)。

所以除非实现了什么炸裂的 AI 算法，并列显示两个面板是我认为目前最有效的实现。

**Comment by ciknight** [comment]
@crimx 谢谢

**Comment by DismalSnail** [comment]
good idea

**Comment by qq3127610** [comment]
原来如此,支持

**Comment by l0o0** [comment]
我想问下，能添加单词的相关的音标么？复习时候，发现有些不会念了

**Comment by crimx** [comment]
读单词应该尽量摆脱对音标的依赖，把发音钩子埋在单词本身。语感较弱的话可以多点喇叭听发音，特别是例句。“朗文词典”和“双语例句”都有非常棒的真人语库。

如果复习时忘了读音，说明一开始就没有记住。这时应该重新查一遍，重复上面的记忆流程，重复几次应该都会记住了。

**Comment by KikouAria** [comment]
0分. 不知道脑子在想什么
查单词就一定要背了????
你就知道每个单词都是需要背(而不是极为稀有的)的???
我笔记个单词还要复制黏贴? 真不知道在想什么

**Comment by crimx** [comment]
你不记可以在设置关闭弹出。
