### ISSUE TITLE
保存到生词本能否不要再弹出保存界面

### ISSUE THREAD

**Issue by ljhui** [crimx/ext-saladict#118]
最近的版本更新后生词本功能不太喜欢，每次点击保存到生词本自动弹出一个保存界面，还要再次点击保存才能成功，希望能像以前一样，点击就自动保存，在选项设置中也没有找到定制的选项

**Comment by crimx** [comment]
新版已发布，有问题欢迎另开 issue 。再次感谢提供反馈。
