### ISSUE TITLE
之后是否会增加Safari版本开发计划

### ISSUE THREAD

**Issue by leorenjianhan** [crimx/ext-saladict#1180]
## 设备信息
- 操作系统: [MacOS Big Sur 11.1] 
- 浏览器版本: [Safari 14.0.2] 
- 沙拉查词版本: [v7.18.0] 

## 请描述目前使用沙拉查词遇到什么不便

不支持Safari浏览器

## 理想情况下，沙拉查词应该怎么做

看到Q&A中说不支持Safari的原因是端口不同，但听说现在Safari14已经支持Web Extension API，应该可以直接把其他版本的转换过去？所以想问一下之后是否有支持Safari浏览器的开发计划，谢谢！

## 替代方案

N/A

## 额外信息

N/A

**Comment by crimx** [comment]
是吗？那我得好好看看。多谢反馈。

**Comment by ShingLi** [comment]
希望兼容下Safari

**Comment by wzyrichard** [comment]
+1 希望支持safari

**Comment by crimx** [comment]
Safari 会在沙拉查词近两个版本内支持。

**Comment by ghost** [comment]
https://saladict.crimx.com/safari  已支持
