### ISSUE TITLE
希望能增加一个关闭快捷查词的快捷键

### ISSUE THREAD

**Issue by D0think** [crimx/ext-saladict#1181]
## 设备信息
- 操作系统: [Windows] 
- 浏览器版本: [Chromium 86.0.4240.198] 
- 沙拉查词版本: [v7.18.0] 

## 请描述目前使用沙拉查词遇到什么不便

打开快捷查词后需要鼠标点击关闭才能关闭面板，有时候不想用鼠标

## 理想情况下，沙拉查词应该怎么做

三击crtl打开查词，在搜索框输入查词后，三击crtl或者别的什么再关闭查词

**Comment by crimx** [comment]
按 Esc 关闭。如果是独立窗口按 Ctrl/Command w。

**Comment by D0think** [comment]
ctrl w可以的

**Comment by D0think** [comment]
> 按 Esc 关闭。如果是独立窗口按 Ctrl/Command w。

ctrl w可以的
