### ISSUE TITLE
快捷键设置后异常

### ISSUE THREAD

**Issue by BOQ3** [crimx/ext-saladict#1189]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome 87] 
- 沙拉查词版本: [v7.18.0] 

## 描述问题

无论是全局还是在浏览器内, 只要设置了打开独立查词窗口的快捷键, 便会与浏览器自身快捷键 `ctrl+shift+t` 冲突, 导致恢复标签页快捷键不能使用.

## 复现步骤

设置快捷键 --> 设置打开独立查词窗口快捷键为 `ctrl+shift+q` --> 按下 `ctrl+shift+t` --> 出现独立查词窗口?

## 期待的正常行为

按下 `ctrl+shift+t` 照常恢复已关闭标签页.

## 截图

![image](https://user-images.githubusercontent.com/37544729/103970874-32945380-51a4-11eb-82a2-1579334e2885.png)
![image](https://user-images.githubusercontent.com/37544729/103970905-4475f680-51a4-11eb-9076-1ade6d01ba89.png)

**Comment by crimx** [comment]
Ctrl-Shift-Q 是 chrome 本身的快捷键，建议不要这么设置。请使用未占用的快捷键组合。

**Comment by BOQ3** [comment]
你好! 不管设置什么按键, 都会与 `ctrl+shift+t` 冲突, 如: `alt+q` 或 `alt+shift+q` 或 'alt+shfit+m'.
PS: 沙拉查词真好用! 给作者大大的赞!

**Comment by crimx** [comment]
> 不管设置什么按键, 都会与 ctrl+shift+t 冲突

冲突发生了之后有没有重启系统？貌似 Chrome 它是没有办法直接恢复系统快捷键冲突的，需要重启系统。

> 沙拉查词真好用! 给作者大大的赞!

谢谢谢谢！😁

**Comment by BOQ3** [comment]
问题已解决, 非常感谢!

**Comment by BOQ3** [comment]
我想我找到了原因.

我的操作是:
按下快捷键打开独立查词窗口.
关闭独立查词窗口.
按下 `ctrl+shift+t`.
独立查词窗口弹出.

这里的 `ctrl+shift+t` 只是把之前关闭的独立查词窗口给恢复了, 就像恢复一个标签页一样.
  



chahhfut@163.com
 
发件人： CRIMX
发送时间： 2021-01-08 11:49
收件人： crimx/ext-saladict
抄送： BO; Author
主题： Re: [crimx/ext-saladict] 快捷键设置后异常 (#1189)
不管设置什么按键, 都会与 ctrl+shift+t 冲突
冲突发生了之后有没有重启系统？貌似 Chrome 它是没有办法直接恢复系统快捷键冲突的，需要重启系统。
沙拉查词真好用! 给作者大大的赞!
谢谢谢谢！
