### ISSUE TITLE
查词面板抖动的问题

### ISSUE THREAD

**Issue by zfanli** [crimx/ext-saladict#119]
使用相关的问题请确保先看了 Wiki 《划词翻译食用方式》 <https://github.com/crimx/crx-saladict/wiki> 。

不能划词的网站请提供具体链接。刚安装扩展后已经打开的页面需要刷新一遍以加载词典。

如果是查词结果不正确或无结果，请先点击结果左上的词典图标跳转到词典网页，查看是否为自身网络问题。

因安全问题，chrome 商店页面、自带的 PDF 页面以及其它扩展的页面是不能划词的。可用点击图标或三按 ctrl 快速查词，本扩展自带 PDF 阅读器。

请根据模板描述问题，以便作者理解和解决。

## 平台：包括操作系统和 Chrome 版本

OS：macOS 10.13.4
Chrome：版本 66.0.3359.181（正式版本） （64 位）

## 类型：错误？建议？

可能是 BUG ？

## 重现：提供详细的可重现问题的操作。

查词面板每一次显示完成后有抖动的现象，今天更新插件之后出现的。

GIF 帧数限制只能见到一次抖动，实际上大概每回抖个7-8次的样子。

![重现](https://user-images.githubusercontent.com/20221538/40783392-d2dd5d7a-6514-11e8-9c73-519e444704b8.gif)

## 期待：理想情况下扩展应该怎么做？

不抖动。

## 实际：客观描述扩展实际上做了什么。

查词完成后面板整体抖动，看多了眼花...( ꒦ຶД꒦ຶ )

## 额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

console 没有错误输出。

很棒的插件，感觉比 mac 自带的查词 app 还好用 ✧Ꮚˊ͈꒳​ˋ͈Ꮚ✧

**Comment by crimx** [comment]
嗨，这是 Chrome 66 渲染的 bug ，可以升级到 67

**Comment by zfanli** [comment]
@crimx 

Hi，我升级了 Chrome，现在版本：版本 67.0.3396.62（正式版本） （64 位）

但是问题好像还在 ( ꒪⌓꒪)

**Comment by zfanli** [comment]
感谢 🙏

**Comment by crimx** [comment]
新版已发布，有问题欢迎另开 issue 。再次感谢提供反馈。
