### ISSUE TITLE
访问 https://javaee.github.io/javaee-spec/javadocs/ 网站,  沙拉查词是灰色的

### ISSUE THREAD

**Issue by GivenCui** [crimx/ext-saladict#1190]
## 设备信息
- 操作系统: [Mac 10.15.5] 
- 浏览器版本: [Chrome 87.0.4280.88] 
- 沙拉查词版本: [v7.18.0] 

## 描述问题

访问 https://javaee.github.io/javaee-spec/javadocs/ 网站,  沙拉查词是灰色的

## 复现步骤

点击网站 [https://javaee.github.io/javaee-spec/javadocs/ ](url)

## 期待的正常行为

可以正常查词使用

## 截图

![image](https://user-images.githubusercontent.com/17002107/103975701-c6b7e800-51af-11eb-934e-e89d1be968c0.png)

**Comment by crimx** [comment]
请阅读[常见问题及答复](https://saladict.crimx.com/q&a.html)。
