### ISSUE TITLE
开启划词翻译后的全选效果

### ISSUE THREAD

**Issue by Higurashi-kagome** [crimx/ext-saladict#1191]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome87] 
- 沙拉查词版本: [v7.18.0] 

## 描述问题

在浏览器使用 Ctrl+A 快捷键全选网页内容（比如输入框中的内容）时不会弹出复制按钮（此时开启了划词翻译）。

## 复现步骤

0. 前提：开启了划词翻译
1. 打开 GitHub 中任意一个 Issue
2. 在评论框中输入一串字
3. 使用 Ctrl+A 全选输入内容
4. 问题出现：没有弹出翻译按钮

## 期待的正常行为

或许该支持在这种情况下弹出翻译按钮。

## 额外信息

一个使用场景：在编写完英文评论之后往往需要全选内容并翻译以检查表意是否准确，支持全选弹出将使翻译评论变得更加方便。

**Comment by crimx** [comment]
你可以：
1. 设置快捷查词面板，打开后自动加载页面选词内容，并开启打开后自动查词。
2. 快捷查词面板划词模式设为直接查词，面板在开启状态便会选中即查词。

**Comment by Higurashi-kagome** [comment]
好的，谢谢。
