### ISSUE TITLE
官网-注意事项-部分.md后缀的href失效

### ISSUE THREAD

**Issue by ouyangjunfei** [crimx/ext-saladict#1193]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome 87.0.4280.141] 
- 沙拉查词版本: [7.18.0] 

## 描述问题

官网的[注意事项](https://saladict.crimx.com/notice.html)部分`*.md`后缀的href失效

已经发现的有：
- `https://saladict.crimx.com/manual.md`
- `https://saladict.crimx.com/q&a.md`
- `https://saladict.crimx.com/native.md`

## 复现步骤

1. 打开[网页](https://saladict.crimx.com/notice.html)
2. 点击某些链接
3. 404无法跳转

## 期待的正常行为

href指向正常的页面资源

**Comment by crimx** [comment]
非常感谢反馈！目前把 .md 后缀改为 .html 可以访问。

**Comment by crimx** [comment]
已修复
