### ISSUE TITLE
我就是来吐槽的

### ISSUE THREAD

**Issue by Sasa996** [crimx/ext-saladict#1196]
最近发现了『梦想划词翻译』，与之相比暗然失色，一直拿『最好用的XXX』做宣传，感觉被打脸了。我今天就来吐槽一下，首先太复杂，我第一次使用，感觉进入一个大型系统，各种设置，看的我眼花缭乱，如果号称最复杂的翻译扩展，我估计会赞同。然后是界面丑，字又小，还密密麻麻，一点间距美感都没有，设计的默认折叠，我第一次使用都不知道这是折叠，试问开发者，懂设计吗？一点排版美感都没有，配色也是我很不喜欢的颜色，用着就是委屈了我的眼睛。然后很多翻译源不能用，用着用着就让我去买收费服务，对于我们这种小白，完全不懂怎么买，也没钱买啊。还有默认那个云彩小译，简直是个累赘，用着用着就收费，还占用一个常点击的默认位置。我就想简简单单用个翻译功能，你给我送一堆不需要，不给钱还不让用的功能。扩展大小居然11.7M，我用火狐版的梦想划词翻译才120K，居然很多词典都不用收费也能用，排版也看着舒服很多，还可以自由拖动调整，设置也简单明了，简直不能不爱。建议开发者别拿最好用做宣传，简直被打脸啪啪的，比复杂你最复杂，比简单易用，你完败给梦想划词翻译，直接被秒杀了！

**Comment by crimx** [comment]
谢谢你的反馈。沙拉查词确实还有许多需要改进的地方。

> 一直拿『最好用的XXX』做宣传...  

沙拉查词从来没有以『最好用的XXX』宣传，见官网 https://saladict.crimx.com/ 。

> 我就想简简单单用个翻译功能

沙拉查词对自己对定位是一款“聚合词典专业划词翻译”，主要针对的是对外语单词有深入理解需求的高阶用户。简单的查词功能市面已有许多优秀的词典应用，就不再重复开发实现了。

在有限的时间和精力下，沙拉查词目前首先实现了可用性，并暴露出了可观的自定义接口让用户可以按自己的喜好调整。未来在时间允许的情况下会继续优化易用性。

**Comment by xuchuang199636** [comment]
用过很多款划词翻译，沙拉查词让我把之前的划词翻译都删除了(～￣▽￣)～沙拉查词真的太好用了！！！

**Comment by hqyyqh** [comment]
如果你是冲着`『最好用的 XXX』` 这个宣传语来吐槽的话，我真的直替作者叫屈。

**关于『最好用的 XXX』`的说法**

- 作者从来没有用过`『最好用的 XXX』` 的说法，你所看到的应该是出自于用户写的介绍吧。（ps. 作者自己都懒得宣传，全靠用户口口相传

**关于沙拉查词设置过于复杂**

- 这个没得说，沙拉查词功能很多，设置复杂确实是个问题。如果能够直接暴露最核心的功能设置给用户的话会好很多。
>但是话说，用户类型那么多，每种类型用户的认为的核心功能可能会有所不同。例如你就想要一个简简单单的翻译功能，但是我想的是简简单单的PDF翻译功能

- 按照我自己的理解，沙拉查词已经尽可能做到开箱即用，也希望将来沙拉查词的设置能够对新手友好一点🤣
- 沙拉查词的设置可以导入导出，也可以跟随浏览器账号同步，真的有比较重的查词需求的话，耐心自定义到自己满意的程度，然后就一劳永逸啦。因为配置不会丢失
- 沙拉查词初期设置也是挺简洁的，不过你看看这一千多个[issues](https://github.com/crimx/ext-saladict/issues)，还有这几千个[commits](https://github.com/crimx/ext-saladict/commits)😂，基本都是用户的需求和建议，要满足大部分的用户的需求并不容易。（作者太宠用户了(っ °Д °;)っ

**关于试问开发者，懂设计吗？**

- 审美就见仁见智了，千人千面，我觉得目前界面挺好的\(￣︶￣*\))。

**关于很多翻译源不能用**

- 值得一说的是，沙拉查词初期基本没有这个问题。按照我的理解，是用户数量比较庞大，内置的翻译账号免费额度不够用导致的。
- 总得来说，除非作者自掏腰包，否则用户数量到一定程度必然会面临这个问题。因此作者也只能妥协，让用户配置自己的词典账号。
- 例如腾讯翻译君个人账号文本翻译的每月免费额度为 5 百万字符 。其实如果个人用的话是绰绰绰绰绰绰绰绰有余的。`https://cloud.tencent.com/document/product/551/35017`

**关于彩云翻译**

- 彩云翻译算是第三方翻译服务了，翻译的方式还是挺有创意的，双语对照。
- 不过作者或许可以考虑一下更改彩云翻译默认的触发方式，比如说只默认出现在右键菜单，点击扩展栏沙拉查词图标的时候可以直接弹出输入框。
- 或许从一个新用户的角度来说，点击沙拉查词图标的时候更希望出现的是查词框😘

**关于建议开发者别拿最好用做宣传，简直被打脸啪啪的，比复杂你最复杂，比简单易用，你完败给梦想划词翻译，直接被秒杀了！**

- 最后，没必要捧一踩一，好的东西都是相互借鉴，在实践过程中不断改进的。

- 必须吐槽的是，一方面`建议开发者别拿最好用做宣传`，另一方面自己的描述语言中又出现`完败`、`秒杀`。。。
- 所以有话好好说，问题也容易得到解答，这不是很好嘛。

**Comment by crimx** [comment]
@hqyyqh 感谢小铅笔天使的理解支持和反馈！❤️ 会慢慢改进哒！

**Comment by xiajunwen1007** [comment]
试用了一下，感觉【梦想划词助手】和目前的沙拉查词比还是差的很远的
### 梦想划词助手的不足：
- 界面方面：一些词典没有样式，看起来没有重点（例如：自由词典）。没有暗黑模式。
- 使用方面：目前没有方法在浏览器外使用。没有生词本。没有情景模式。当然这些可能是由于目标用户不一样，但是没有生词本这一个功能就可以说不适合大部分学习英语的人了（个人观点）。
- 翻译方面：不能自动检测中英文来切换模式。有一些翻译引擎失效（腾讯翻译），这个应该是这一类软件共同的缺点，不知道为什么要吐槽这个。
- 词典方面：也有一些词典会时不时失效…所有词典内都没有js，所以没有展开和收缩按钮，有时候词典太长了会不方便。如果本来网页版设计了js，有时会影响翻阅内容。
- 网页翻译：目前没有看到有这个功能，之所以提一下是因为楼主吐槽了一下沙拉查词的彩云小译网页翻译这个功能。大家还是相互理解一下吧，作者花这么多时间写的扩展，能支持就支持。在设置里可以对“点击地址旁按钮”进行更改

之所以要写这个是因为自己喜欢的东西被喷了之后的本能反应，希望楼主以后好好说话吧。最后加一句，沙拉查词牛逼，哈哈哈。貌似写完的时候issue已经关了。

**Comment by crimx** [comment]
因为我们其它的词典开发者也收到这个了，感觉好像是个广告😂 就先关掉不浪费大家的时间啦。

@xiajunwen1007 谢谢你的对比介绍！❤️
