### ISSUE TITLE
[bug]firefox85中无法编辑并保存扩展设置

### ISSUE THREAD

**Issue by Oshibuki** [crimx/ext-saladict#1198]
错误信息：
QuotaExceededError: storage.sync API call exceeded its quota limitations.

**Comment by listenerri** [comment]
估计是配置的云同步接口调用配额超了

**Comment by crimx** [comment]
火狐的频率限制太严厉了，等一会或者尝试删掉一些情景模式试试。

**Comment by crimx** [comment]
Duplicate of #1188
