### ISSUE TITLE
词典有时内容显示比较慢

### ISSUE THREAD

**Issue by linsui** [crimx/ext-saladict#120]
使用相关的问题请确保先看了 Wiki 《划词翻译食用方式》 <https://github.com/crimx/crx-saladict/wiki> 。

不能划词的网站请提供具体链接。刚安装扩展后已经打开的页面需要刷新一遍以加载词典。

如果是查词结果不正确或无结果，请先点击结果左上的词典图标跳转到词典网页，查看是否为自身网络问题。

因安全问题，chrome 商店页面、自带的 PDF 页面以及其它扩展的页面是不能划词的。可用点击图标或三按 ctrl 快速查词，本扩展自带 PDF 阅读器。

请根据模板描述问题，以便作者理解和解决。

## 平台：包括操作系统和 Chrome 版本
win10 18.04，chrome版本 66.0.3359.181

## 类型：错误？建议？
有时词典内容显示较慢，收起再展开即可立即显示。点击字典通过网页打开速度很快，往往一个页面长时间浏览时出现此问题，切换标签后问题消失

**Comment by crimx** [comment]
我看看什么原因。这个也可能是网络不稳定造成的，再次打开快可能是因为前一次内容被缓存了。

**Comment by crimx** [comment]
还有这个”长时间”是指多长，在使用什么查词模式。

**Comment by crimx** [comment]
新版已发布，有问题欢迎另开 issue 。再次感谢提供反馈。
