### ISSUE TITLE
CNKI翻译助手失效

### ISSUE THREAD

**Issue by carteryx** [crimx/ext-saladict#1200]
## 设备信息
- 操作系统: [Win10]
- 浏览器版本: Chrome
- 沙拉查词版本: v7.18.0

## 描述问题
CNKI翻译助手失效，CNKI翻译助手改版了，所以原接口貌似失效了。希望修复一下

**Comment by niecailong** [comment]
请尽快修复吧，CNKI瘫痪好久了。好多专业词靠这个查呢。

**Comment by crimx** [comment]
Duplicate of #1154
