### ISSUE TITLE
词典中添加的谷歌翻译多个网站均无法运行,其他词典正常运行

### ISSUE THREAD

**Issue by Ahasser** [crimx/ext-saladict#1207]
## 设备信息
- 操作系统: win10
- 浏览器版本:chrome 87.0.4280.66（正式版本） （32 位）
- 沙拉查词版本: v7.18.1

## 描述问题

词典中添加的谷歌翻译多个网站均无法运行,其他词典正常运行

## 复现步骤

打开此反馈bug的页面，选中bug一词进行翻译，谷歌翻译无结果，其他词典正常出现翻译结果

## 期待的正常行为

谷歌翻译将对应中文翻译并显示

## 截图

![QQ图片20210120170256](https://user-images.githubusercontent.com/38968180/105151810-5f038480-5b41-11eb-8e9c-4f14d37771b4.png)

**Comment by crimx** [comment]
Duplicate of #1160
