### ISSUE TITLE
谷歌沙拉查词插件输入中文首个字母会自动输入查词窗口

### ISSUE THREAD

**Issue by readyhuihui** [crimx/ext-saladict#1208]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome  87.0.4280.66] 
- 沙拉查词版本: [v7.18.1] 

## 描述问题

谷歌浏览器点开沙拉查词插件输入中文时，首个中文字母会自动呈现在查词的文本框中。

## 复现步骤

1. 打开谷歌
2. 打开沙拉查词
3. 先输入英文，如“hello” 回车搜索。
3. 再清空搜索框，输入中文，如：阿里
4. 沙拉查词的查词框，会呈现：a里

## 期待的正常行为

期待：中文汉字可以等输入完毕后内容再呈现到沙拉查词的文本框中。如：想输入“阿里”，则文本框展示“阿里”

## 截图

我打算输入“真棒”，实际文本框的内容是：z很棒

**Comment by readyhuihui** [comment]
谷歌浏览器升级到“V88.0.4324.96”版本依旧有这个问题。

**Comment by crimx** [comment]
Duplicate of #1149
