### ISSUE TITLE
在页面选词之后，被选定词无法被快捷键进行复制

### ISSUE THREAD

**Issue by xlgao-zju** [crimx/ext-saladict#121]
使用相关的问题请确保先看了 Wiki 《划词翻译食用方式》 <https://github.com/crimx/crx-saladict/wiki> 。

不能划词的网站请提供具体链接。刚安装扩展后已经打开的页面需要刷新一遍以加载词典。

如果是查词结果不正确或无结果，请先点击结果左上的词典图标跳转到词典网页，查看是否为自身网络问题。

因安全问题，chrome 商店页面、自带的 PDF 页面以及其它扩展的页面是不能划词的。可用点击图标或三按 ctrl 快速查词，本扩展自带 PDF 阅读器。

请根据模板描述问题，以便作者理解和解决。

在页面选词之后，被选定词无法被快捷键进行复制（command+c）

## 平台：包括操作系统和 Chrome 版本
macos 10.13.4

## 类型：错误？建议？

建议不用影响复制功能。

**Comment by crimx** [comment]
嗨，根据你提供的信息无法重现问题。确定是 Saladict 的问题吗？

1. 请提供浏览器及版本
1. 划词模式是什么？如果是直接弹出查词面板自然要关闭后才能复制。
1. 在设置关闭划词后还会影响复制么？
1. 禁用扩展后呢？

**Comment by xlgao-zju** [comment]
浏览器 chrome 67.0.3396.62
查词模式 直接搜索

![image](https://user-images.githubusercontent.com/1636894/40831516-c7943464-65bb-11e8-9257-5f2d88e2d776.png)

例如这个，在鼠标划选之后这两个地方都是灰色的，没法进行复制操作。
但是如果关掉查询面板，被划中的词还是灰色的，也是没法复制的。

**Comment by crimx** [comment]
嗯，知道问题了，多谢反馈。暂时可以用其它划词模式。

**Comment by xlgao-zju** [comment]
好的，这个还是挺影响体验的。请问version 6大概多久上线，期待。

**Comment by crimx** [comment]
修复会在一周内提交，等待收集更多问题。

**Comment by xlgao-zju** [comment]
Cool

**Comment by crimx** [comment]
新版已发布，有问题欢迎另开 issue 。再次感谢提供反馈。

**Comment by Sooongz** [comment]
v6 依然存在复制问题

**Comment by crimx** [comment]
请详细阐述。如果使用了直接搜索，那么原页面焦点失去是必然的。现在查词面板搜索框已修复焦点问题，所以选择内容可以直接复制（从搜索框中）。

**Comment by Sooongz** [comment]
关闭直接搜索‘复制’可以正常使用 谢谢
