### ISSUE TITLE
今日更新后

### ISSUE THREAD

**Issue by luoanita** [crimx/ext-saladict#1210]
## 设备信息
- 操作系统: [win 10] 
- 浏览器版本: [edge 87.0.664.75 ] 
- 沙拉查词版本: [v7.18.0] 

## 描述问题

谷歌翻译和腾讯翻译君不能正常显示翻译结果，如图所示

## 复现步骤

1.通过沙拉翻译打开本地pdf文件
2.选中段落进行翻译
3.谷歌翻译和腾讯翻译不能正常显示翻译结果，有道翻译、百度翻译、彩云小译正常显示翻译结果

## 期待的正常行为

应该全部显示正常翻译结果

## 额外信息

<img width="320" alt="20210121155530968" src="https://user-images.githubusercontent.com/77774197/105321476-7787a380-5c02-11eb-8a0e-0743b84c8934.png">
<img width="329" alt="20210121155557999" src="https://user-images.githubusercontent.com/77774197/105321483-79516700-5c02-11eb-8ee8-9e578aaa786f.png">

**Comment by cpdyj** [comment]
最近我也遇到此类问题，正当我打开inspector准备检查问题时，这个现象又消失了

**Comment by crimx** [comment]
Duplicate of #1160

**Comment by crimx** [comment]
谷歌在灰度测试新的 API ，有一定几率会碰到。需要点时间才能支持。

腾讯的还是申请个翻译账号吧，公用的估计撑不了多久。
