### ISSUE TITLE
PDF 识别换行

### ISSUE THREAD

**Issue by zzan1** [crimx/ext-saladict#1217]
## 设备信息
- 操作系统: [Microsoft Windows 10 专业版 19042] 
- 浏览器版本: [Edge 88.0.705.50，uTools plugin] 
- 沙拉查词版本: [V7.18.0] 

## 请描述目前使用沙拉查词遇到什么不便

![image](https://user-images.githubusercontent.com/47623989/105788835-36094680-5fbc-11eb-9523-36a4b18d69da.png)

复制文本已经识别换行了，但是翻译出的中文没有识别出换行，仍然是两行的翻译。

**Comment by crimx** [comment]
在沙拉查词设置中，打开该词典的设置，找到保持换行的选项（只有机器翻译的词典支持这个选项）。

**Comment by zzan1** [comment]
> 在沙拉查词设置中，打开该词典的设置，找到保持换行的选项（只有机器翻译的词典支持这个选项）。

解决了~，谢谢！！！
