### ISSUE TITLE
部分词典失效

### ISSUE THREAD

**Issue by BlueSpaceX** [crimx/ext-saladict#1218]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome77] 
- 沙拉查词版本: [v7.18.1] 

## 描述问题

部分词典失效，如图所示，只有谷歌翻译能正常显示，望修复

## 复现步骤

1.打开沙拉查词设置，点击词典设置
2.点击右下角预览查词面板
3.出现问题

## 期待的正常行为

应该有种不同词典的翻译，实际上只有谷歌能正常使用

## 截图

![image](https://user-images.githubusercontent.com/78003901/105790207-d3657a00-5fbe-11eb-8352-2057294403ba.png)

**Comment by crimx** [comment]
是不是修改了其它几个词典的匹配规则，比如语言，字数。点击编辑去看看。

**Comment by BlueSpaceX** [comment]
quote

> 是不是修改了其它几个词典的匹配规则，比如语言，字数。点击编辑去看看。

谢谢，最小值划字字数被错误的设置成了6，改成1就可以了
