### ISSUE TITLE
按住alt后不能ctrl+鼠标选词

### ISSUE THREAD

**Issue by tkkcc** [crimx/ext-saladict#122]
- 平台：archlinux chrome67.0.3396.62 按住ctrl触发翻译

- 类型：建议

- 重现

  1. 按住alt的同时使用ctrl+鼠标选词不会触发翻译，这在5上是可以的

  2. 在谷歌/百度搜索网页的输入框中使用ctrl+鼠标选词不会触发翻译，这在5上是可以的

  3. ctrl+鼠标滚轮缩放网页时会触发翻译，这在5上也是这样

- 期待

  1. 按住alt可以选择翻译链接上的文字，我觉的挺有必要。。

  2. 在谷歌/百度搜索网页的输入框中使用，我也觉的很有必要。。

  3. ctrl+鼠标滚轮缩放网页时不应触发翻译

**Comment by crimx** [comment]
嗨，谢谢反馈。

1. 我晚些看看如何处理。验证我的猜测，你试试先按 alt 再按 ctrl 是不是可以的。
2. 这是新版的功能，识别输入区域，可在设置关掉。
3. 这个不应该触发的，晚些再给你答复。

**Comment by crimx** [comment]
嗯，对于 2 我想按下 ctrl 应该强制搜索才对。

**Comment by tkkcc** [comment]
1. 先按alt再按ctrl也不能触发

2. 我改了设置OK了

**Comment by crimx** [comment]
嗨，1 我会做进一步兼容处理，3 我测试是没有问题的。Saladict 也没有监听滚轮事件，会不会是跟硬件或者其它设置相关？之前也有一位用户按键浏览器检测不对。

试试缩放时触发了什么 https://output.jsbin.com/tobune/1

**Comment by tkkcc** [comment]
3确实是我的问题，关掉imwheel就OK了

**Comment by crimx** [comment]
cool

**Comment by tkkcc** [comment]
1我现在试试先按alt再按ctrl可以触发的，之前试错了。

**Comment by crimx** [comment]
新版应该可以了，有问题欢迎另开 issue 。再次感谢提供反馈。
