### ISSUE TITLE
谷歌翻译、有道翻译、搜狗翻译、CNKI翻译助手无法正常运作

### ISSUE THREAD

**Issue by UprightH** [crimx/ext-saladict#1223]
## 设备信息
- 操作系统:  [Win10]
- 浏览器版本: [Edge88.0.705.56 ] 
- 沙拉查词版本: [v7.18.0]

## 描述问题
谷歌翻译、有道翻译、CNKI翻译助手一直无结果，那怕是查简单的单词(网站可以打开而再次查词依然无结果)
搜狗翻译只显示原文不显示译文

## 复现步骤
1. 选中任一单词（如Firefox、university）
2. 点击沙拉查词图标
4. 问题出现

## 期待的正常行为
查词面板中每个词典都能正常显示

## 截图
![image](https://user-images.githubusercontent.com/77877846/106570197-8a8a6400-6570-11eb-9fed-b080b001b564.png)
![image](https://user-images.githubusercontent.com/77877846/106570212-8f4f1800-6570-11eb-9c86-b1d4e88c7981.png)
![image](https://user-images.githubusercontent.com/77877846/106570224-937b3580-6570-11eb-9890-b6e127e4e26e.png)
![image](https://user-images.githubusercontent.com/77877846/106570244-97a75300-6570-11eb-9a20-5db5bcdc1c9e.png)
![image](https://user-images.githubusercontent.com/77877846/106570755-4350a300-6571-11eb-937d-b3324a1edea3.png)

**Comment by crimx** [comment]
CNKI 词典的问题请更新 v7.18.1，其它机器翻译可能共享频率用完了，可以注册个账号自用。
