### ISSUE TITLE
长句发音

### ISSUE THREAD

**Issue by lancerXXXX** [crimx/ext-saladict#1224]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [版本 88.0.705.56 (官方内部版本) (64 位)] 
- 沙拉查词版本: [v7.18.1] 

## 请描述目前使用沙拉查词遇到什么不便

![image](https://user-images.githubusercontent.com/42160297/106873461-73ce4380-670f-11eb-9761-c61603b6a8a6.png)

## 理想情况下，沙拉查词应该怎么做

我记得原来这里红圈附近, 有朗读长句 的按钮, 现在好像没了

**Comment by lancerXXXX** [comment]
我知道了 == 有个翻译模式

**Comment by crimx** [comment]
跟 #1160 属于同个问题。
