### ISSUE TITLE
打开pdf时，是否可以添加高亮划线的功能

### ISSUE THREAD

**Issue by colaaaaaa** [crimx/ext-saladict#1227]
首先非常感谢沙拉给我的学习生活带来这么多的便利！！
有个小需求像说一说
一般来说看论文既需要翻译也需要标记重点段落，但是现在不好兼得...，可否能添加一个标记pdf的功能呢，划线或者高亮然后能够保存更改这种~

**Comment by crimx** [comment]
[常见问题与答复](https://saladict.crimx.com/q&a.html#%E9%97%AE%EF%BC%9A%E6%B7%BB%E5%8A%A0%E7%94%9F%E8%AF%8D%E5%8F%AF%E4%B8%8D%E5%8F%AF%E4%BB%A5%E5%8A%A0%E5%85%A5%E5%8D%95%E8%AF%8D%E7%BF%BB%E8%AF%91%EF%BC%88%E8%80%8C%E4%B8%8D%E6%98%AF%E7%BF%BB%E8%AF%91%E6%95%B4%E5%8F%A5%E4%B8%8A%E4%B8%8B%E6%96%87%EF%BC%89%E3%80%82)
