### ISSUE TITLE
在Chrome上复制东西经常出现没办法粘贴

### ISSUE THREAD

**Issue by MrYu4** [crimx/ext-saladict#1231]
## 设备信息
- 操作系统: [Mac] 
- 浏览器版本: [Chrome88] 
- 沙拉查词版本: [7.18.1] 

## 描述问题

在Chrome上复制东西经常出现没办法粘贴

## 复现步骤

cmd+c没法复制

## 期待的正常行为

在Chrome上复制东西经常出现没办法粘贴

**Comment by crimx** [comment]
你好，为什么会觉得是沙拉查词的问题？停用沙拉查词后可以复制么？是否开启了划词直接显示查词面板？
