### ISSUE TITLE
改进编辑框光标移动行为

### ISSUE THREAD

**Issue by QuarticCat** [crimx/ext-saladict#1232]
## 设备信息

- 操作系统: [Arch Linux] 
- 浏览器版本: [Chrome 88.0.4324.150] 
- 沙拉查词版本: [v7.18.1] 

## 请描述目前使用沙拉查词遇到什么不便

编辑查词输入框的行为违反一般预期。具体操作如下：

1. 在编辑框输入任意字符串后回车
2. 移动光标至字符串中间的任意位置
3. 进行任意编辑操作，如键入一个字母
4. 光标立刻被移动至字符串结尾处

比如我一开始键入 `abcd` 并回车，然后移动光标到 `bc` 中间，希望输入 `xy` 后改成 `abxycd` ，但结果会获得 `abxcdy` 。

## 理想情况下，沙拉查词应该怎么做

让光标停留在原处

## 替代方案

无

## 额外信息

无

**Comment by crimx** [comment]
感谢反馈，与 #1149 是同个 bug 造成

**Comment by QuarticCat** [comment]
看起来已经修复了，因此关闭这个 issue
