### ISSUE TITLE
新版（6.0.0）Bugs满载啊

### ISSUE THREAD

**Issue by Erbzur** [crimx/ext-saladict#124]
- 平台：win10，chrome 66

- 类型：错误

- 划词操作、面板设置、快捷查词设置、右上弹框设置

- 重现：在我本地上常规操作，对任意网站可重现

- 期待：上一版（5.31.7）体验无可挑剔

- 实际：查词面板失焦后没有自动关闭，且手动关闭后无法”再一次“翻译当前位置的划词；右上弹框设置不预先加载仍然会加载剪切板的内容；面板显示时会抖动；快捷查词（连按三次ctrl）预先加载页面划词时面板输入框为粘贴状态而非已输入状态；进入设置后第一次出现的面板预览没有对“salad”翻译，且输入框也为粘贴状态；快捷查词面板由原来的正右方变为右下方出现；面板出现位置设置没了？（按住ctrl后划词，查词面板会挡住网页中部的其它内容）

**Comment by crimx** [comment]
感谢反馈，会在一周内修复。

**Comment by Erbzur** [comment]
1."粘贴"状态指的就是预先加载的输入框的内容为全选状态，记得前一版没有这种现象；

2.屏幕是1920x1080，上个问题和该问题的共同截图如下：
![image](https://user-images.githubusercontent.com/39868528/40960002-f5af60d6-68d0-11e8-9cf7-956b274b8b00.png)

3.划词时我希望它能在固定位置出现，选项中没有相关设置，也许我搞混了吧，因为我快捷查词用的多，它以前就是固定在正右方出现的，不会挡到网页中部内容，划词翻译应该本来就没有固定设置的。。。

**Comment by crimx** [comment]
嗨

1. 全选状态在 Saladict 中一直是有的，这可以实现预加载的同时也能方便的编辑。
2. 这个是原先设计的理想状态，但我会考虑换个方式。
3. Saladict 一直没有固定位置出现的选项。快捷查词可以设置出现位置，但一旦出现必然会遮挡该位置的内容。侧边栏类的功能可以考虑未来实现。

**Comment by Erbzur** [comment]
表述问题，“固定位置”我指的是在期望的位置（通过设置）出现面板，快捷查词就已经是固定右方出现了。

其实完全展开的面板在该扩展的设置页面是右方居中的，在其它网页翻译时却都在右下角。
据本人观察，它未展开时的确是出现在正右方的，但翻译时，总体面板是向下展开的，从而就体现为右下方出现了。面板出现位置和展开方式跟上一版不一样，这应该是问题所在：
![image](https://user-images.githubusercontent.com/39868528/40969007-7857281c-68e9-11e8-930a-2c6aa4097cf8.png)

另外，我所表述的第三点是想让划词与快捷查词一样，可以设置在固定方位出现。比起划词时面板在划词位置的右方显示，翻译后又得手动让其失焦或关闭才能不被遮挡网页内容，固定的出现位置能提升网页的阅读体验。

**Comment by crimx** [comment]
嗨，这属于特殊情况，也是图钉功能的作用。

**Comment by crimx** [comment]
还有展开，跟上一版不一样的地方在于这版的高度是动态的，所以要保持居中的话需要引入额外的定位的方式，这个有些 overhead 了，所以计算采用了 30% 左右的估计。

**Comment by crimx** [comment]
我考虑将这个计算换为按最大高度的中心来估计，这样如果词典总体高度比最大高度小的用户会稍微靠上。

**Comment by crimx** [comment]
新版已发布，有问题欢迎另开 issue 。再次感谢提供反馈。
