### ISSUE TITLE
希望能支持Safari

### ISSUE THREAD

**Issue by sunmeda** [crimx/ext-saladict#1243]
现在每天使用臃肿的chrome就是为了沙拉查词，
身边safari和沙拉查词重叠的用户不少
苹果也推出了十分便捷的将Chrome、Firefox扩展转换成Safari适用版本的工具
[https://developer.apple.com/documentation/safariservices/safari_web_extensions](https://developer.apple.com/documentation/safariservices/safari_web_extensions
)
希望能支持safari

**Comment by RtYkk** [comment]
https://github.com/crimx/ext-saladict/issues?q=is%3Aissue+safari

**Comment by crimx** [comment]
感谢反馈，Safari 的扩展实现局限性比较多，已经在调研啦。先关了这个 issue，讨论请前往 #1180 。

**Comment by crimx** [comment]
Safari 支持已提上日程，详情见 #1180。
