### ISSUE TITLE
某些字会导致汉典显示不正常的图片

### ISSUE THREAD

**Issue by laptifi** [crimx/ext-saladict#1244]
![屏幕截图 2021-02-24 142622](https://user-images.githubusercontent.com/29730054/108957564-a6cf7b80-76ac-11eb-9e38-95d7a86fa404.jpg)

然后就是希望作者能添加百度汉语的词典：https://dict.baidu.com/

**Comment by crimx** [comment]
感谢反馈。

> 然后就是希望作者能添加百度汉语的词典：https://dict.baidu.com/

这个相比沙拉查词现有的有什么优势呢？
