### ISSUE TITLE
建议添加deeply翻译

### ISSUE THREAD

**Issue by fengshiyu58** [crimx/ext-saladict#1247]
## 词典名称以及链接
https://www.deepl.com/

## 沙拉查词的已有的词典为什么不能满足？

翻译更加智能，贴近中文表达

## 单词举例

- 
![image](https://user-images.githubusercontent.com/43529170/109138493-65ff6180-7795-11eb-9955-8f887760d9cb.png)

![image](https://user-images.githubusercontent.com/43529170/109138588-7fa0a900-7795-11eb-838a-9570673a68a9.png)

**Comment by crimx** [comment]
Duplicate of #705
