### ISSUE TITLE
查询结果支持导出图片未找到

### ISSUE THREAD

**Issue by zhxt0** [crimx/ext-saladict#125]
- 平台：Ubuntu 16.04 和 Chrome 66

- 类型： 查询结果支持导出图片 的分享按钮没找到

- 期待：查词结果导出图片

- 实际：没有找到 [wiki](https://github.com/crimx/ext-saladict/wiki#save-img) 中所说的分享按钮

**Comment by crimx** [comment]
我更新一下文档，这个在之前的版本有一个实现性的实现，有点鸡肋，所以新版去掉了。等待合适的时机在加回去。
