### ISSUE TITLE
PantherBar 沙拉查词扩展修改后缀问题

### ISSUE THREAD

**Issue by 100725** [crimx/ext-saladict#1250]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Firefox84] 
- 沙拉查词版本: [v7.13.4] 

#请教一个关于PantherBar的问题# 。

#PantherBar 沙拉查词扩展下载，需要下载文件后缀.zip 改为 .pbar，双击安装。
而我改完后缀，还是只能当做zip，解压，是我操作错误吗。
也无法直接用PantherBar打开zip
尝试解压，双击key.ps1只有一个文本文档，# 复现步骤

#希望有人看看这是怎么回事# 期待的正常行为

#
![图片](https://user-images.githubusercontent.com/61739298/109521328-2794da00-7ae8-11eb-9685-2a7a9d591830.png)
# 截图

**Comment by crimx** [comment]
你看看左上方的文件名，没有改对。可以搜索一下如何修改文件后缀。
![image](https://user-images.githubusercontent.com/6882794/109580920-6487bd80-7b36-11eb-887a-b9ef56b6aab6.png)

**Comment by 100725** [comment]
> 
> 
> 你看看左上方的文件名，没有改对。可以搜索一下如何修改文件后缀。
> ![image](https://user-images.githubusercontent.com/6882794/109580920-6487bd80-7b36-11eb-887a-b9ef56b6aab6.png)

学会了，非常感谢您的答复

**Comment by 100725** [comment]
@crimx 学会了，非常感谢您的答复
