### ISSUE TITLE
添加 牛津高阶 与 美国传统词典

### ISSUE THREAD

**Issue by architecturers** [crimx/ext-saladict#1253]
## 词典名称以及链接
牛津高阶
https://www.oxfordlearnersdictionaries.com/

美国传统词典
https://ahdictionary.com/

## 沙拉查词的已有的词典为什么不能满足？

学习词典
牛津高阶 是最权威的学习词典 目前没有这个词典

全本词典
美国传统词典 是最权威的美语全本词典 目前没有

希望能为沙拉查词尽一份绵薄之力，沙拉查词是我目前为止用过的最好的查词工具，感谢所有工作人员的辛勤付出！

**Comment by JER-ry** [comment]
Lexico就是牛津的emmm

**Comment by crimx** [comment]
美国传统词典 我看看……感谢反馈！

**Comment by dabing16888** [comment]
> Lexico
你好
Lexico 收录的是Oxford Dictionary of English 

我说的牛津是advanced learner‘s dictionary 
是最权威的学习词典

**Comment by goodean** [comment]
所谓所有工作人员，好像就是@crimx 大佬一个![image](https://user-images.githubusercontent.com/40910711/115279558-77ebf800-a179-11eb-85d5-97fe31652770.png)

@crimx 大佬，请加一些古汉语词典，这方面缺得厉害，而在这方面那个汉典真不是很好用，太杂乱了。你查一个字试试就知道了。比如说【将】这个字，你对比一下这个结果[将-词典网](https://www.cidianwang.com/guhanyu/jiang952.htm) 与汉典查出来的这个结果[将-汉典网](https://www.zdic.net/hans/%E5%B0%86)，汉典是不断地重复解释，看得人头大。

**Comment by crimx** [comment]
感谢 @yipanhuasheng 大佬实现了美国传统词典！将在下一版上线。

@goodean 我也想要一些古汉语词典，不知道有没有比较好的推荐！词典网好像有点简陋？
