### ISSUE TITLE
希望提供单词本同步功能

### ISSUE THREAD

**Issue by vleyong** [crimx/ext-saladict#1256]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 理想情况下，沙拉查词应该怎么做

我打开设置面板，发现没有自定义 单词存储路径 这个选项，希望加上去，另外是否可以同步到有道单词本，或者OneDrive,或则跟随新登chrome账号

**Comment by crimx** [comment]
单词存在浏览器的数据库中，受浏览器插件限制抱歉还不能做到存在本地文件。Chrome 账号因为容量有限，所以也不能用来存单词本。目前支持 WebDAV 同步，你可以通过 WebDAV 软件如坚果云再同步到本地任意文件。

有道单词本与 OneDrive 目前没有计划支持。

**Comment by ershat-dl** [comment]
> 

我看 支持同步到欧路词典，这个可以进一步支持 双向的同步功能吗？
在新的设备上使用沙拉时 从欧路词典里同步到本地
