### ISSUE TITLE
首页拼写错误

### ISSUE THREAD

**Issue by BenjiaH** [crimx/ext-saladict#1257]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Edge 89] 
- 沙拉查词版本: [v7.18.1] 

## 描述问题

[https://saladict.crimx.com/ocr.html](https://saladict.crimx.com/ocr.html)
拼写错误。
ORC ->OCR

## 复现步骤

访问[https://saladict.crimx.com/ocr.html](https://saladict.crimx.com/ocr.html)

## 期待的正常行为

ORC ->OCR

## 截图

![image](https://user-images.githubusercontent.com/46958476/110227605-10fde100-7f35-11eb-969b-18cd0d12910e.png)

**Comment by crimx** [comment]
感谢提醒
