### ISSUE TITLE
建议：增加统计每个所查单词累计查词次数，方便生成个性化的词频表

### ISSUE THREAD

**Issue by lweo** [crimx/ext-saladict#126]
首先十分感谢作者写了这么强大的查词拓展，同时佩服作者的技术能力！

据我所知，市面上还没有词典有统计查词次数的功能，不知道作者能否在拓展中实现？每个单词对每个用户的重要性是不一样的，经常查的单词往往是对自己很重要的。统计所查单词，按查询次数排序，导出变是一个针对个人的词频表了，极大地方便复习。

还一个建议：类似于网易对原文分级翻译，能不能基于所查生词，对于原文所有生词高亮，作者可以试用国外的lingq[www.lingq.com](url)

**Comment by crimx** [comment]
嗨，感谢建议！

1. 统计查词次数。这个功能简单的增加不难，但要完善需要考虑不少情况。比如单词的时态、上下文是否算入计算、排序后如何展示重复的词语，如何导出等等。数据处理比较复杂和私人化，所以 Saladict 提供了通用的导出，以便配合其它专业的工具使用。可以试试[相关的工具](https://www.zhihu.com/question/26564557)，或者写个脚本处理。
1. 所有单词高亮是个 nice-to-have 的特性，但与 Saladict 划词翻译的定位有些水土不服。首先，这个功能简单的情况浏览器搜索可以实现，如果涉及到时态将会很复杂；其次技术角度，在原网页上这么操作一定程度上增加了搞乱网页样式的风险，这里面是个大泥潭，要踏进去爬出来代价不低；最后，有这方面需求的用户量还待衡量。另外我试用了 lingq ，觉得它已经做得非常不错了，并且可以从 Saladict 导过去，所以就不重复劳动了。

希望上面解答了你的问题。

Regards.

**Comment by lweo** [comment]
@crimx 1.不用考虑得太理想，每查一个词（不同时态的单词分开记录），该词在本地数据库+1就行，上下文在6.0版本是自动录入的吗？我这是空。。导出只是为了方便复习，txt格式就行…

2.lingq是收费的。。免费用户限制太多基本没可用性；有道分级翻译不也是要网页重排吗？
[“跨文本全文生词高亮功能”国内有个“蒙哥英语原版阅读器”，主打特色功能就是这个，用户数还不少，我感觉这需求还是挺大的](https://itunes.apple.com/cn/app/%E8%92%99%E5%93%A5%E8%8B%B1%E8%AF%AD%E5%8E%9F%E7%89%88%E9%98%85%E8%AF%BB%E5%99%A8-meerkat-reader/id483247714?mt=8)

**Comment by crimx** [comment]
嗨，对于 1 我上面已经强调了数据处理的私人化。这么实现只能说是暂时满足了你的个人需求。Saladict 的方向不在数据处理，目前的精力是在打磨划词翻译的体验上。将数据处理交给更专业的工具。

对于 2 有道翻译等并不是 Saladict 一样对网页频繁操作的工具，那么使用时偶尔出现影响排版的错误是可以接受的。另外也是上面提到的方向问题。能实现的好用功能很多，但我相信好的产品更需要做减法。

Regards.

**Comment by crimx** [comment]
新版已发布，有问题欢迎另开 issue 。再次感谢提供反馈。

**Comment by lweo** [comment]
@crimx 作者参考下这个扩展https://chrome.google.com/webstore/detail/words-discoverer-expand-y/noncaeikjgpbdeoocblijjgegnobogib?hl=zh-CN 几乎就是我想的那样，不过不带查词功能。。扩展能看到源代码吗？如果不需要什么精力作者就整合进去吧。。

**Comment by crimx** [comment]
嗨，这个项目的介绍已经表达了我上面提到的意思了。 Saladict 目前专注于划词翻译，且应该与这个不错的扩展兼容。
