### ISSUE TITLE
划词自动翻译建议设置一个时差！！或者灵敏度调节啥的。有时候词还没画完就开始翻译了（甚至还没松鼠标）！！希望是松掉鼠标后延迟0.x秒开始自动翻译

### ISSUE THREAD

**Issue by BYwwww** [crimx/ext-saladict#1267]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: []

**Comment by crimx** [comment]
默认情况下应该是只有鼠标松手后才会开始划词。可以看看有没有以下的情况

- 开启了触摸模式。
- 开启了悬浮查词。
- 鼠标按键氧化导致出现连击。（可以尝试对一个文件夹按住鼠标，看会不会打开了）

**Comment by BYwwww** [comment]
确实是触摸模式的问题，非常感谢！
