### ISSUE TITLE
三击复制得到的翻译结果中包含多余的换行

### ISSUE THREAD

**Issue by Higurashi-kagome** [crimx/ext-saladict#1268]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome89.0.4389.82] 
- 沙拉查词版本: [v7.18.1] 

## 描述问题

三击选中翻译结果后使用 Ctrl + C 复制到的内容中包含多余的换行。

## 复现步骤

1. 选中网页内文本
2. 点击弹出的翻译按钮进行翻译
3. 在翻译结果上连续点击三次以选中翻译内容
4. 使用 Ctrl + C 复制选中内容
5. 在编辑器中粘贴复制内容，问题出现：复制到的内容中包含多余的换行

## 期待的正常行为

应该仅仅是复制到选中内容，而不包含换行。

## 截图

<details>
<summary>Details</summary>

![demo](https://user-images.githubusercontent.com/51501079/111263531-f9270b00-8660-11eb-8f62-ba1478d0270a.gif)

</details>

**Comment by Higurashi-kagome** [comment]
不过在其他网页上三击复制到的一些内容中也会有多余的空格。

**Comment by crimx** [comment]
看了动图，请问你是如何直接全选译文句子的？

**Comment by Higurashi-kagome** [comment]
在译文上（短时间内）连续点击鼠标左键三次。

**Comment by crimx** [comment]
感谢反馈。应该是样式的问题，晚点我看看。

**Comment by yipanhuasheng** [comment]
严格来说这个不算是bug，页面上双击选中的文本会自带一个硬回车（\n），这个应该是浏览器的默认行为，双击即选中段落。

**Comment by crimx** [comment]
好的，如果是浏览器的行为那么我们不做特殊处理了。
