### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by CNHLM** [crimx/ext-saladict#127]
- 平台：win10  64位，QQ浏览器最新版

- 类型：错误

- 划词模式和其它模式

- 重现：我的翻译选了必应和谷歌，谷歌翻译一直加载，换谷歌浏览器，谷歌翻译可以正常使用，在这次更新前，QQ浏览器可以正常使用

**Comment by crimx** [comment]
嗨，我测试了 QQ 浏览器 10.1 是可用的。

原本 Saladict 是用了 Google 翻译一个未公开的 API ，这个 API 最近应该下线了，所以现在 Saladict 是直接从 translate.google.com -> translate.google.cn -> 再到原来的 translate.googleapis.com 三步地尝试。请确认你能访问这些网站或者检查 VPN 的设置。

**Comment by crimx** [comment]
新版已发布，有问题欢迎另开 issue 。再次感谢提供反馈。
