### ISSUE TITLE
建议默认打开独立窗口“记住位置与大小“选项

### ISSUE THREAD

**Issue by Higurashi-kagome** [crimx/ext-saladict#1278]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome89] 
- 沙拉查词版本: [v7.18.1] 

## 请描述目前使用沙拉查词遇到什么不便

在打开独立窗口后调整独立窗口大小，然后关闭窗口重新打开，发现没有扩展记住窗口大小。查找设置选项后发现提供了“记住位置与大小”选项，但默认关闭。

## 理想情况下，沙拉查词应该怎么做

或许该默认打开该选项。

## 额外信息

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/51501079/113086039-759a1c00-9213-11eb-894a-7645c83b1bf2.png)

</details>

**Comment by crimx** [comment]
因为这个设置在一些魔改的浏览器上会有问题，所以默认没有打开。
