### ISSUE TITLE
可以增加读取本地mdict词典的功能吗？

### ISSUE THREAD

**Issue by hanmala123** [crimx/ext-saladict#1284]
## 设备信息
- 操作系统: [Windows10] 
- 浏览器版本: [Edge89] 
- 沙拉查词版本: [v7.0.0] 

## 请描述目前使用沙拉查词遇到什么不便

线上英汉翻译网站对于单个单词的查询都不太好用，显示的释义都不全

## 理想情况下，沙拉查词应该怎么做

希望能像欧路词典一样读取本地的mdict格式的词典

**Comment by crimx** [comment]
Duplicate of #636
