### ISSUE TITLE
Collins Cobuild no longer working

### ISSUE THREAD

**Issue by YinxingHN** [crimx/ext-saladict#1286]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome 86] 
- 沙拉查词版本: [v7.18.1] 

## 描述问题

 COBUILD Stopped show results

## 复现步骤

https://www.theguardian.com/world/2021/apr/05/mecca-to-accept-only-immunised-pilgrims-from-ramadan

double click words to show results -> other dictionaries work but COBUILD doesn't

## 期待的正常行为

Display lookup results. 

## 截图

![Snipaste_2021-04-12_10-12-14](https://user-images.githubusercontent.com/7692652/114362460-a7967100-9b77-11eb-8a64-c0347332b0d2.png)
Urban and Wikipedia work fine but are folded.

**Comment by crimx** [comment]
Click the COBUILD title or open this page https://www.collinsdictionary.com/dictionary/english/love

Then try again in Saladict.

**Comment by YinxingHN** [comment]
That worked, thanks!
