### ISSUE TITLE
句子翻译选项

### ISSUE THREAD

**Issue by TemppyLee** [crimx/ext-saladict#129]
加上海词会更加方便，或者必应或谷歌多一个可勾选选项，就是超过一定单词数不翻译。平常习惯用必应或海词看一个单词的翻译，用谷歌看整段翻译，现在海词没有了，选择谷歌和必应同时存在，那么在选择一段话的时候界面就是一段话两种翻译，看起来就有点乱了。（个人鄙见）

**Comment by crimx** [comment]
新版已添加。

**Comment by TemppyLee** [comment]
你好，非常感谢你采用了我的意见，辛苦了。但是这个最大单词量不能看见具体的值，其实我还是希望Google翻译不设置最大量值的，因为我经常用Google整段翻译。最完美的是可以把设置可翻译最大单词量改为可勾选的设置。感觉现在的版本可能会不方便大多数人，希望再改进一下或恢复原来的版本。
真的很不好意思打扰你了，总之真的谢谢你对我意见的重视。

发送自 Windows 10 版邮件应用

发件人: CRIMX
发送时间: 2018年6月7日 21:35
收件人: crimx/ext-saladict
抄送: Temppy; Author
主题: Re: [crimx/ext-saladict] 句子翻译选项 (#129)

新版已添加。

**Comment by TemppyLee** [comment]
问题是我不能自己填写值，而且我也不知道值是多少，因为没有显示


发送自 Windows 10 版邮件应用

发件人: CRIMX
发送时间: 2018年6月8日 8:24
收件人: crimx/ext-saladict
抄送: Temppy; Author
主题: Re: [crimx/ext-saladict] 句子翻译选项 (#129)

这... 你设个 999999 不相当于不限了

**Comment by crimx** [comment]
在设置中可以对每个词典设置最大最小字数，如不知道怎么打开设置可参考 Wiki <https://github.com/crimx/ext-saladict/wiki>

**Comment by TemppyLee** [comment]
发送自 Windows 10 版邮件应用
