### ISSUE TITLE
希望增加词典默认折叠功能

### ISSUE THREAD

**Issue by luminislight** [crimx/ext-saladict#1292]
## 设备信息
- 操作系统: Window10 
- 浏览器版本: Chrome89 
- 沙拉查词版本: 7.18.1 

## 请描述目前使用沙拉查词遇到什么不便

添加了多个词典的情况下，同时展开弹窗会过于冗长，查看不便。且一般参考首选的一两个词典的结果足以，其他的作为参考或用于特定的补充查询。
比如大部分情况只需谷歌翻译，当遇到特殊的俚语时才手动展开urban dict的查询结果。

## 理想情况下，沙拉查词应该怎么做

能单独设置每个词典默认是否展开

## 替代方案

有个记忆折叠，但是只在同一个页面生效

**Comment by crimx** [comment]
沙拉查词已有这样的设置。在词典设置中可针对每个词典设置。
