### ISSUE TITLE
无法兼容其他 Cirlce 阅读模式扩展

### ISSUE THREAD

**Issue by hewenguang** [crimx/ext-saladict#1293]
## 设备信息
- 操作系统: [mac]
- 浏览器版本: [Chrome77] 
- 沙拉查词版本: [v7.18.1] 

## 描述问题

你好，我开发了一个阅读模式插件：https://chrome.google.com/webstore/detail/circle-reading-mode/dhpfcgilccfkodnhbllpiaabofjbjcbg?hl=zh-CN&authuser=0

用户反馈启用我的插件后无法使用沙拉查词，我自己排查没有找到问题。我的扩展会在 body 元素上面创建一个 div ，然后把用户需要的正文重新整理成更方便阅读的样子。所以猜测是沙拉查词是只检测 body 内部元素，而不是 document.documentElement 元素下的文本

希望可以得到回复，如何修复这个问题，感谢

## 期待的正常行为

复制文字可以正常启用沙拉查词

**Comment by crimx** [comment]
好的！我去排查一下！插件做得真棒btw👍

**Comment by hewenguang** [comment]
感谢♥️

**Comment by crimx** [comment]
沙拉是监测到了，只是沙拉查词的页面内面板是放在 body 中，随着 body 隐藏了故看不到。

**Comment by hewenguang** [comment]
> 沙拉是监测到了，只是沙拉查词的页面内面板是放在 body 中，随着 body 隐藏了故看不到。

我的插件是为了在原页面生成一个新的页面，并且为了防止样式复写，禁用掉了所有的页面原有样式。也就是说，即使沙拉展示也是没有样式的。难搞😂

我在想想有没有办法处理这个

**Comment by crimx** [comment]
我晚些调研一下能不能把查词面板放其它地方。

**Comment by hewenguang** [comment]
👌

**Comment by BlackHole1** [comment]
是不是可以在沙拉查词里提供一个postMessage API，其他插件调用这个API，沙拉查词会根据传参，把面板放插件里指定的DOM元素上

**Comment by crimx** [comment]
@BlackHole1 666666
