### ISSUE TITLE
请问在最顶层放置搜索结果这个功能是有的吗，还是还没有实现？

### ISSUE THREAD

**Issue by KK-3458** [crimx/ext-saladict#1294]
## 设备信息
- 操作系统: [mac 11.2.3] 
- 浏览器版本: [Chrome 89.0.4389.114] 
- 沙拉查词版本: [v7.18.1] 

## 请描述目前使用沙拉查词遇到什么不便

喜欢全屏使用safari浏览器，配合Afred浏览器外划词，请问是可以设置查词窗口在最上层显示的吗？还是说没有实现是这个功能，请问有计划实现查词窗口在最上层显示这个计划吗？😅

## 理想情况下，沙拉查词应该怎么做

希望查词窗口可以在最上层显示，如果不难实现的话。

**Comment by crimx** [comment]
见[常见问题及答复](https://saladict.crimx.com/q&a.html#%E9%97%AE%EF%BC%9A%E7%8B%AC%E7%AB%8B%E7%AA%97%E5%8F%A3%E6%9F%A5%E8%AF%8D%E9%9D%A2%E6%9D%BF%E8%83%BD%E5%90%A6%E9%92%89%E4%BD%8F%E7%BD%AE%E9%A1%B6%EF%BC%9F)。
