### ISSUE TITLE
添加牛津词典

### ISSUE THREAD

**Issue by songyy14** [crimx/ext-saladict#13]
请问能否在查词面板中集成牛津词典，而不是提供定向到目标网页的右键菜单。牛津词典释义详细而且非常权威，希望能把它添加进来！

**Comment by crimx** [comment]
每添加一个词典我就要多维护一个，Macmillan 也是相当不错的。

**Comment by Lukikay** [comment]
突然发现，牛津词典的API是要收费的啊，免费版每个月只有3000次请求，那么多用户，一下子就没了吧。。。
不过牛津词典确实范围更广一点，好多稍微学术一点的词麦克米伦就没有了。

**Comment by crimx** [comment]
[新版](https://github.com/crimx/ext-saladict/wiki/Saladict6)已添加，如有问题欢迎开新 issue 反馈。
