### ISSUE TITLE
外置的查词，怎么样才能有上下文可以导入anki

### ISSUE THREAD

**Issue by christxh** [crimx/ext-saladict#1300]
我的在pdfexpert 里面使用复制查词，但是只有词没有上下文，怎么处理。

## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: []

**Comment by crimx** [comment]
Duplicate of #1285

**Comment by christxh** [comment]
Well, thank you!



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月21日(周三) 上午9:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [crimx/ext-saladict] 外置的查词，怎么样才能有上下文可以导入anki (#1300)




 
Duplicate of #1285
