### ISSUE TITLE
建议加入同义词词典

### ISSUE THREAD

**Issue by Lin-Ether** [crimx/ext-saladict#1306]
## 设备信息
- 操作系统: Windows10
- 浏览器版本: Edge
- 沙拉查词版本: v7.18.1

## 请描述目前使用沙拉查词遇到什么不便

没有同义词词典，有时候需要同义词

## 理想情况下，沙拉查词应该怎么做

添加同义词词典

## 替代方案

试着爬取[https://www.thesaurus.com/](https://www.thesaurus.com/)，里面有同义词/反义词查询

## 额外信息

无

**Comment by crimx** [comment]
Duplicate of #736
