### ISSUE TITLE
使用Applescript模拟连续按三次command无效

### ISSUE THREAD

**Issue by zhaiyi-000** [crimx/ext-saladict#1307]
我不习惯连续按三次command，想着在Mac顶部状态栏增加一个按钮可以直接执行AppleScript，AppleScript脚本的作业是模拟点击三次command，然后点击“钉住查词面板”

其他功能都没问题，就连续三次点击command不响应。
我试过用AppleScript点击空格，空格在Chrome里面是翻页，没有问题
点击command+y，是查看历史，也没有问题
独独三次command不行，求大佬帮忙看看什么问题

<img width="835" alt="截屏2021-04-29 上午11 43 57" src="https://user-images.githubusercontent.com/61309244/116500010-31686d00-a8e0-11eb-9e40-973ea758e3c6.png">

**Comment by crimx** [comment]
沙拉查词支持设置[全局快捷键](https://saladict.crimx.com/manual.html#shortcuts)，设置完之后模拟快捷键就行。

**Comment by zhaiyi-000** [comment]
我希望单词面板固定在右边中间😂，而且不是全局窗口 ，这个快捷单词面板在设置快捷键里面没有

**Comment by crimx** [comment]
> 我希望单词面板固定在右边中间😂，而且不是全局窗口 ，这个快捷单词面板在设置快捷键里面没有

再描述一下你的意思？没读明白。可以截图拖进来。

**Comment by zhaiyi-000** [comment]
![image](https://user-images.githubusercontent.com/61309244/116531241-883a6a80-a911-11eb-87bb-677d7908e7b7.png)

我上面的意思是弹出面板在网页的右边，且不是独立窗口。这个不能设置快捷键...

现在我直接用独立窗口了。所以，那没事了（/斜眼笑
