### ISSUE TITLE
谷歌搜索的链接必须是com么，我只有cn能上去。。。

### ISSUE THREAD

**Issue by fan2957262222** [crimx/ext-saladict#131]
- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）

Win10 1803         Chrome：67.0.3396.62      沙拉也是最新版6.1.2

- 类型：错误？建议？

我划词的时候第一次谷歌翻译查不出来，必须再划一次才能出来，点左上角发现链接是https://translate.google.com  这个网站我只有科学上网才能上去。随时都能上去的是https://translate.google.cn，只有cn才能上去。。。不知是我网的问题还是都这样，算是报个错吧，谢谢了。

**Comment by crimx** [comment]
你好，因为解析 token 的算法是基于 google.com 的，所以保证效果 Saladict 是从 translate.google.com -> translate.google.cn -> 再到原来的 translate.googleapis.com 三步地尝试。

**Comment by crimx** [comment]
或许我可以增加个设置。

**Comment by fan2957262222** [comment]
嗯嗯，明白了，谢谢

**Comment by crimx** [comment]
新版已添加。
