### ISSUE TITLE
怎么鼠标点击划词外区域翻译弹框不消失了

### ISSUE THREAD

**Issue by zcy2nn** [crimx/ext-saladict#132]
使用相关的问题请确保先看了 Wiki 《划词翻译食用方式》 <https://github.com/crimx/crx-saladict/wiki> 。

不能划词的网站请提供具体链接。刚安装扩展后已经打开的页面需要刷新一遍以加载词典。

如果是查词结果不正确或无结果，请先点击结果左上的词典图标跳转到词典网页，查看是否为自身网络问题。

因安全问题，chrome 商店页面、内置的 PDF 页面以及其它扩展的页面是不能划词的。可用点击图标或三按 ctrl 快速查词，本扩展自带 PDF 阅读器。

请根据模板描述问题，以便作者理解、定位和解决问题。

== 提交前将本行及已上内容删除，并填充以下模板 ==

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）

- 类型：错误？建议？

- 划词模式？以及其它觉得相关的设置。

- 重现：提供详细的可重现问题的操作。

- 期待：理想情况下扩展应该怎么做？

- 实际：客观描述扩展实际上做了什么。

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by fengyn** [comment]
6.1.2版还有这个问题 win10 64bit chrome67稳定版

**Comment by crimx** [comment]
请提供产生问题的网站，以及查词模式。

**Comment by fengyn** [comment]
所有网站，按住ctrl查词模式。

**Comment by fengyn** [comment]
导出设定[https://1drv.ms/u/s!AhsTrNNBQV3Hvz8aTky46iRmRzb6](url)

**Comment by crimx** [comment]
好的多谢反馈

**Comment by crimx** [comment]
这个 bug 是由于延迟隐藏面板引起的，只有在单独 ctrl 模式时出现，新版已发布。
