### ISSUE TITLE
查询界面变成透明

### ISSUE THREAD

**Issue by chongfengling** [crimx/ext-saladict#1324]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome 90.0.4430.93（正式版本） （64 位）] 
- 沙拉查词版本: [v7.18.1] 

## 描述问题

查询界面变成透明，严重影响使用。

## 复现步骤

1. 点击需要查询词，双击打开查询结果面板。
2. 问题出现。背景为透明。

## 期待的正常行为

背景为非透明（白色）

## 截图

[Snipaste_2021-05-10_21-51-50](https://user-images.githubusercontent.com/39767612/117670471-7f337e00-b1da-11eb-8771-705cc3901077.jpg)

**Comment by crimx** [comment]
只有在一个网站上出现还是所有网站出现？

如果只有一个网站出现，可以提供网址么。

如果所有出现，请检查沙拉查词设置 `查词面板` -> `自定义查词面板样式`，看看是否填了自定义样式。
