### ISSUE TITLE
为什么所有的PDF文件都不能用沙拉查词了？

### ISSUE THREAD

**Issue by Mandarin-Cat** [crimx/ext-saladict#1329]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Microsoft Edge 90.0.818.62 (官方内部版本) (64 位)] 
- 沙拉查词版本: [v7.18.1] 

## 描述问题

只是PDF文件用不了沙拉查词，图标显示灰色，我选“在PDF浏览器中打开”，就打不开文件。
但是其他网页都正常使用。
重启过，也删除沙拉查词重新安装过。
还是不行。

## 复现步骤

1. 打开PDF文件
2. 选中单词
3. 没有弹出沙拉查词的图标
4. 看到图标是灰色
5. 选中单词后右键-更多操作-沙拉查词
6. 没有任何反应
7. 在工具栏图标那里右键，选择“在PDF阅读器中打开”
8. 打不开，一片空白
9. 以为是单个PDF文件的问题，但并不是，因为这个PDF文件可复制可搜索可编辑。
10. 打开用以前沙拉查词读过的PDF，还是不行。

## 期待的正常行为

正常情况下我选中单词就自动弹出图标了

**Comment by crimx** [comment]
这个 PDF 文件是本地文件还是在线？

- 本地文件需要[开启访问权限](https://saladict.crimx.com/notice.html#%E9%A2%84%E8%AE%BE)。
- 在线文件可以提供链接以供测试。

**Comment by Mandarin-Cat** [comment]
已经解决了，但我不知道怎么解决的。是本地文件，我开启权限了。我恢复了一下电脑系统，重新安了一边沙拉查词，然后重新按照教程配置了一遍。再重启也没有好。但是今天用的时候不知怎的就好了……
