### ISSUE TITLE
更新新版后，输入单词会一直被替换

### ISSUE THREAD

**Issue by dream-jx** [crimx/ext-saladict#133]
插件更新到新版本后，输入英文单词一直会显示被覆盖，比如我输入 a，然后再输入 b，那么 a 就会被 b 覆盖，无论怎么切换输入法和去除大小写都会出现，完全输入不了单词，目前 window 和 mac 都会这样

**Comment by dream-jx** [comment]
一直用了很久，更新版本后就出现这问题，现在完全输入不了单词查询，只能在其他地方输入好后再复制进去

**Comment by crimx** [comment]
你好，无法重现你的问题。请按照模板提供信息。可以导出设置复制过来。

**Comment by crimx** [comment]
新版已发布，如有问题欢迎开新 issue 并按模板反馈。
