### ISSUE TITLE
Enable GitHub sponsor

### ISSUE THREAD

**Issue by yo1995** [crimx/ext-saladict#1332]
是否可以考虑开通GitHub sponsor呢？
一直在用这个插件，觉得很好用，希望支持一下

**Comment by crimx** [comment]
谢谢建议！我看看怎么弄这个哈哈哈

**Comment by yo1995** [comment]
哈哈，刚才我看了一下：https://github.com/sponsors 目前好像国内还不支持。我先关掉了，如果到时候支持我再来打钱 💸
