### ISSUE TITLE
沙拉查词-有道词典翻译的时候能不能精简些

### ISSUE THREAD

**Issue by actforjason** [crimx/ext-saladict#1335]
沙拉查词-有道词典翻译的时候能不能精简些，有时候不希望翻译整个网页，只划词翻译一段，但是在用有道翻译的时候，会把英文的一大段重复显示（页面上已有），“机器翻译”这几个字也很冗余，是否可以类似谷歌翻译精简下？

![image](https://user-images.githubusercontent.com/57058325/119632633-92ce1e00-be43-11eb-8a19-6f67058c9080.png)

**Comment by crimx** [comment]
可以对在词典设置中限制有道词典出现的最大划词字数。

**Comment by actforjason** [comment]
你可理解错了，我意思是还继续使用有道翻译，这种情况下能否精简。设置“最大划词字数”后翻译段落时就没有有道翻译了。

**Comment by actforjason** [comment]
多行英语显示成类似谷歌翻译的单行

**Comment by crimx** [comment]
好的，这个我看看怎么接过去。但机器翻译其实有道没有什么优势。

**Comment by actforjason** [comment]
其实我觉得，除了有道，其他几个翻译也没必要显示原文，因为很鸡肋——显示的话也不全（全了也很占空间）。

**Comment by crimx** [comment]
你可以在词典设置里默认隐藏原文。
