### ISSUE TITLE
[Question] 彩云翻译 token 设置后全文翻译不会生效

### ISSUE THREAD

**Issue by imbadark** [crimx/ext-saladict#1336]
## 设备信息
- 操作系统: [macOS 11.1x] 
- 浏览器版本: [Chrome 9x ] 
- 沙拉查词版本: [v7.19.0] 

## 描述问题

彩云页面翻译很快就额度没了, 申请了单独的 彩云小译 token, 并填入保存, 但是发现并没有效果, 彩云还是会提示余额不足

尝试更换一样的用户 / 邮箱, 退出重登, 换账户, 似乎都没有用, 如果 token 并不能全文翻译使用, 只是词典内查询, 那似乎就意义小了许多了 (另外想问下还有可以全文翻译免费使用的词典 api 么)

如果的确不能用于直接翻译, 也希望可以备注一下.  (也没有看到文档或已有 issue 有特别说明这)

## 期待的正常行为

期待能使用 token 有 100w 字符额度

## 截图

![image](https://user-images.githubusercontent.com/38650392/119633701-96ae7000-be44-11eb-8d13-1bdccc525dcf.png)

## 额外信息

另外问一下, 如果想把词典固定在浏览器的标签页, 就是一个单独的页面一样, 现在可以支持 / 实现么

类似传统的 google/腾讯/彩云翻译的网页版, 只不过现在这个网页编程了 saladict, 然后样式是显示正常的. 因为现在独立窗口进程的版本, 它也不能放全屏, 而且单个也占位置, 就是希望能允许设置为一个页面, 然后用户可以在里面查询

**Comment by crimx** [comment]
确实两者不通用，这个我在文档上补充一下，感谢反馈。


> 另外问一下, 如果想词典固定再浏览器的标签页, 现在可以支持 / 实现么, 就是把窗口固定类似传统网页查询的方式. 目前直接最大化会样式不适配

没明白你的问题？这个固定是怎么样的一个效果？

**Comment by imbadark** [comment]
感谢回复, 更新了一下描述,  就是类似页面版的 saladict

**Comment by crimx** [comment]
哦哦，你可以访问 `chrome-extension://cdonnmffkdaoajfknoeeecmchibpmkmg/popup.html` 试试，目前还没有做宽屏优化，之后在宽屏会有不同的效果。

**Comment by imbadark** [comment]
THX, 期待宽屏后的优化 (主要就是能有个居中就行, 或者更好点双边显示)
