### ISSUE TITLE
断网后每个页面都要重新刷新才能划词翻译

### ISSUE THREAD

**Issue by actforjason** [crimx/ext-saladict#1338]
如题

**Comment by crimx** [comment]
能按模板把问题复现的过程描述一遍嘛？

**Comment by actforjason** [comment]
360极速浏览器
就是断网后划词翻译不会出现图标，必需刷新才能显示图标。
也不难理解吧。。

**Comment by crimx** [comment]
Chrome 下按这个步骤没有出现问题。这可能是 360 魔改的问题？

**Comment by actforjason** [comment]
我试了试，好像自己断网再连接没有这个问题，就是下午关了电脑吃了个饭再划词就得刷新页面了，我再观察观察
