### ISSUE TITLE
为什么有道词典有柯林斯却没有牛津词典呢？

### ISSUE THREAD

**Issue by actforjason** [crimx/ext-saladict#1339]
为什么有道词典有柯林斯却没有牛津词典呢？

**Comment by crimx** [comment]
Lexic 就是牛津的。牛津词典没有单独的网站。

**Comment by dream-hack** [comment]
> Lexico 就是牛津的。牛津词典没有单独的网站。

[这个应该是OALD](https://www.oxfordlearnersdictionaries.com/)

另外借这里提一个朗文的排版错误,查询variety时，在词语搭配处词性adjectives和后面例子a wide/great/large variety没有换行分开而是连在一起，如图：
![20210531_145218](https://user-images.githubusercontent.com/18359166/120303991-f0f67780-c301-11eb-8dc6-f98efc6761ce.jpg)


另外还是朗文，名词的复数形式和来源词典能保留不要隐藏吗，感觉这些信息还是比较有用的。
![20210531_145058](https://user-images.githubusercontent.com/18359166/120304512-6eba8300-c302-11eb-8285-d66cb869671a.jpg)

最后感谢作者开发出这么好用的工具，谢谢！

**Comment by crimx** [comment]
OALD 已添加。
