### ISSUE TITLE
为什么不出个桌面版呢

### ISSUE THREAD

**Issue by actforjason** [crimx/ext-saladict#1341]
浏览器插件使用的频率并不高，更多是看英文文档，做个桌面版不更有用吗？桌面版本身也支持各种浏览器，discussion里边方法大多得调用独立窗口，没有浮动窗口便捷。
试了几款GitHub上的[桌面版](https://github.com/zenghongtu/saladict-desktop)（基于Electron）但是作者已经很久没维护了，有点bug。

**Comment by crimx** [comment]
见 [Q&A](https://saladict.crimx.com/q&a.html#%E9%97%AE%EF%BC%9A%E8%83%BD%E5%90%A6%E5%9C%A8-windows%2Fmac%2Flinux%2Fios%2Fandroid-%E5%B9%B3%E5%8F%B0%E4%B8%8A%E5%AE%9E%E7%8E%B0%E5%8E%9F%E7%94%9F%E7%89%88%E6%9C%AC%E7%9A%84-saladict%E3%80%82)。
