### ISSUE TITLE
[Bug] 按键+划词下长句经常不触发翻译效果, 原因未知

### ISSUE THREAD

**Issue by imbadark** [crimx/ext-saladict#1342]
## 设备信息
- 操作系统: [macos 10.1x] 
- 浏览器版本: [chrome 90] 
- 沙拉查词版本: [v7.19.0] 

## 描述问题

发现按住键划词会稳定出现, 超过一定长度或者带有其他字符无法翻译的情况

## 复现步骤

简单说就是当按住 `alt / shift / option` + 鼠标划词来触发查词时, 句子比较短就都可以触发, 但是句子比较长, 就经常无法触发了.
而且我发现长句子如果很快的勾选, 触发概率也比较大, 如果慢慢拖就很大概率不触发....

重复:
简单说就是当按住 `alt / shift / option` + 鼠标划词来触发查词时, 句子比较短就都可以触发, 但是句子比较长, 就经常无法触发了.
而且我发现长句子如果很快的勾选, 触发概率也比较大, 如果慢慢拖就很大概率不触发....
简单说就是当按住 `alt / shift / option` + 鼠标划词来触发查词时, 句子比较短就都可以触发, 但是句子比较长, 就经常无法触发了.
而且我发现长句子如果很快的勾选, 触发概率也比较大, 如果慢慢拖就很大概率不触发....

例如上面的几行重复测试的文字, 按住选中超过4行就一直不能触发翻译. 但是局部翻译是正常的, 感觉像触到了什么机制跳过了翻译一样, 很费解. 

---

F12 没看到额外报错, 之后需要可以简单录屏一下演示... 就是也想问下, 目前的按键 + 划句子翻译, 有限制最大字数, 或者划词时间么?  就 github 的 issue 评论都可以经常的复现这个问题.  不确定是否和浏览器还是啥有关. 也是来问问作者遇到过类似情况么

## 期待的正常行为

任意情况下按键 + 选中句子都能触发翻译

**Comment by crimx** [comment]
按你的步骤我这边没有复现这个问题。按键模式下只要鼠标放开那一刻有按住相应的按钮就行。

**Comment by imbadark** [comment]
![sala](https://user-images.githubusercontent.com/38650392/119828791-1b74b900-bf2d-11eb-8c50-1dcbc7f12975.gif)

补充了个压缩的截图, 应该能看到大概的意思, `alt` 键是一直按着的, 并且只要单词短就一定能触发, 长拉就很容易不触发.

**Comment by crimx** [comment]
记得很久前有人遇到类似的情况。他是配置了鼠标手势还是热键什么的导致鼠标滑动被中断了。

**Comment by crimx** [comment]
你可以试试先不按按键，选词完成后保持按住鼠标，然后同时按住按键，再放开鼠标，看有结果么。

**Comment by imbadark** [comment]
> 记得很久前有人遇到类似的情况。他是配置了鼠标手势还是热键什么的导致鼠标滑动被中断了。

- 为了排除鼠标手势, 我特意换了 mac 自带的触控板, 也是一样的情况 (而且鼠标没开手势 / 热键)
- 不按按键刚试过, 也是近乎一样的效果(需要可以再录屏), 不触发的时候还是一直不触发...
- 在 win 上的 edge 试了下倒是很正常... 我在想要不要 mac 换个 edeg试试:)

**Comment by imbadark** [comment]
**更新3:** (找到问题了)
在原有环境下, 备份配置后重装 saladict, 为了排除配置影响, 先不导入配置, 发现一切正常, 恢复划词可用, 导入配置后, 马上出现问题了... 让我看看找下变动的地方.  (经过一个个可能排查)

找到了问题源头:)  点开了这个触摸模式, 作者你可以点开试试就能复现了, 具体机制和原因我没深究

![image](https://user-images.githubusercontent.com/38650392/119841410-592b0f00-bf38-11eb-9303-e8c62d8ee1a5.png)

**Comment by crimx** [comment]
啊！这个是的。不知道怎么没想起跟你说这个😂。触摸模式下的行为跟鼠标不太一样，所以是通过延时的方式判断。

**Comment by imbadark** [comment]
啊没事, 这个触摸模式似乎提示有点少, 如果会对正常查词有比较明显影响, 可以特别说明一下~
至于具体是否还能再优化, 就看作者你自己考虑了, 多谢及时解答.
