### ISSUE TITLE
yarn pdf报错

### ISSUE THREAD

**Issue by actforjason** [crimx/ext-saladict#1343]
> yarn pdf

> F:\OOPs\SalaDict\ext-saladict>yarn pdf
> yarn run v1.22.5
> $ node scripts/pdf.js
> Cloning into 'pdf'...
> POST git-upload-pack (375 bytes)
> POST git-upload-pack (189 bytes)
> remote: Enumerating objects: 522, done.
> remote: Counting objects: 100% (522/522), done.
> remote: Compressing objects: 100% (203/203), done.
> remote: Total 522 (delta 210), reused 522 (delta 210), pack-reused 0
> Receiving objects: 100% (522/522), 5.50 MiB | 813.00 KiB/s, done.
> Resolving deltas: 100% (210/210), done.
> 
> Checking files.
> F:\OOPs\SalaDict\ext-saladict\scripts\pdf\es5\build\pdf.js not exist
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
>

**Comment by crimx** [comment]
拉最新的代码再跑一下。pdf.js 已经完全取消 es5 导出了，之前有部分 360 浏览器的用户希望用这个。
