### ISSUE TITLE
Urban词典查询结果会被每日热词污染

### ISSUE THREAD

**Issue by pickalexrener** [crimx/ext-saladict#1344]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Chrome90.0.4430.212] 
- 沙拉查词版本: [v7.19.0] 

## 请描述目前使用沙拉查词遇到什么不便

Urban词典查询的第二个结果总是会返回每日热词

## 理想情况下，沙拉查词应该怎么做

屏蔽每日热词

## 额外信息

词典内部的显示
![33352](https://user-images.githubusercontent.com/51726771/119929968-1fe2b580-bfb1-11eb-886b-1bba254d47d8.png)

实际为urban官网上的每日热词
![53252](https://user-images.githubusercontent.com/51726771/119930058-4d2f6380-bfb1-11eb-9bc7-320a91e97c3e.png)

**Comment by crimx** [comment]
感谢反馈！

**Comment by crimx** [comment]
已修复，等待 v2.20.0 上架。
