### ISSUE TITLE
希望加上自动更新

### ISSUE THREAD

**Issue by ws123y** [crimx/ext-saladict#1348]
## 设备信息
- 操作系统: win10 
- 浏览器版本: edge最新（2021年5月31日）
- 沙拉查词版本: 7.18.1 

当有更新时会跳出一个通知，但插件本身不会自动更新## 请描述目前使用沙拉查词遇到什么不便

当有新版本时自动更新并显示通知最好（可以设置“自动更新并通知”或“自动更新但不通知”）## 理想情况下，沙拉查词应该怎么做

无## 替代方案

无## 额外信息

**Comment by crimx** [comment]
Edge 如果在商店中安装是会自动更新的，有时恰好碰上的审核延迟了更新。不需要沙拉查词自己检查更新可以在沙拉查词「私隐设置」中关闭检查更新。
