### ISSUE TITLE
更新最新版后查词面板出现在页面左上角位置

### ISSUE THREAD

**Issue by zfanli** [crimx/ext-saladict#135]
- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）

macOS 10.13.4
Chrome 67.0.3396.79

- 类型：错误？建议？

错误

- 划词模式？以及其它觉得相关的设置。

查词面板位置问题。

- 重现：提供详细的可重现问题的操作。

每次查词时。

- 期待：理想情况下扩展应该怎么做？

与之前版本一样，查词面板出现在图标位置的右方。

- 实际：客观描述扩展实际上做了什么。

更新最新版插件后出现的问题。

查词面板出现在页面左上角。

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

Console 下没有输出。

**Comment by crimx** [comment]
非常感谢反馈，已发布修复。
