### ISSUE TITLE
谷歌浏览器显示：无法翻译次网页（所有网页都是）

### ISSUE THREAD

**Issue by LWli3** [crimx/ext-saladict#1350]
谷歌浏览器显示：无法翻译次网页（所有网页都是如此显示）

## 设备信息
- 操作系统: Win10
- 浏览器版本: Chrome91.0.4472.77
- 沙拉查词版本: v7.19.0

#谷歌浏览器显示：无法翻译此网页（所有网页都是）# 

## 复现步骤

如何重复触发这个不正确的行为：

1. 移除了旧版本拓展程序，重新在官网的网盘地址，下载最新的7.19.0
2. 同时安装了其他拓展：如谷歌访问助手、谷歌翻译（已移除）、Ruffle、Infinity、超级复制这几个拓展
3. 点击英文网页
4. 问题出现：无法翻译此网页（所有网页都无法访问），以前都可以使用

## 期待的正常行为

全部都翻译为中文

## 截图

![image](https://user-images.githubusercontent.com/85096245/120150113-39883500-c21d-11eb-9bc0-8cad60d55222.png)

**Comment by crimx** [comment]
你好，你的截图是浏览器自带的网页翻译功能，不是沙拉查词扩展的界面。
