### ISSUE TITLE
开启chrome沙拉查词插件后，js脚本window.print不触发的问题

### ISSUE THREAD

**Issue by wufeng87** [crimx/ext-saladict#1352]
开启chrome沙拉查词插件后，js脚本window.print()执行后不会弹出chrome打印弹框；
禁用chrome沙拉查词插件后，window.print()打印正常。谢谢

**Comment by crimx** [comment]
我这边测试没有问题。而且沙拉查词不应该影响到 window.print()。不清楚什么问题？

**Comment by wufeng87** [comment]
是比较奇怪，现象是禁用掉这2个插件才能正常运行我们web程序的打印功能：
![Uploading wecom-temp-6f58680eed0300ec7b21b4ef5c6f6ba6.png…]()
