### ISSUE TITLE
safari下无法使用，提示权限“background”申请失败

### ISSUE THREAD

**Issue by Mykko** [crimx/ext-saladict#1359]
## 设备信息
- 操作系统: [macOS 11.2.3] 
- 浏览器版本: [safari 14.0.3] 
- 沙拉查词版本: [v7.19.0] 

## 描述问题

安装后无法使用

在设置页面保存时提示申请 background 权限失败

## 截图

<img width="257" alt="image" src="https://user-images.githubusercontent.com/25126520/120787990-86904200-c562-11eb-8c57-5cb8a5aa807b.png">

**Comment by crimx** [comment]
感谢反馈

**Comment by czloveyou** [comment]
10.15.7 也提示申请失败
画词不展示搜索面板

**Comment by crimx** [comment]
已修复。
