### ISSUE TITLE
划词翻译：弹出面板高度【不能自动展开】

### ISSUE THREAD

**Issue by Yumega** [crimx/ext-saladict#1363]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Chrome91] 
- 沙拉查词版本: [v7.19.0] 

## 请描述目前使用沙拉查词遇到什么不便

划词翻译：无法自动展开整个面板设置的最大尺寸，需要在底部点击后才显示面板的最大高度

## 理想情况下，沙拉查词应该怎么做

直接显示弹出面板的所设置的最大尺寸（高度）

**Comment by crimx** [comment]
设置词典默认高度 99999 即可。

**Comment by Yumega** [comment]
在哪里设置默认高度？找不到位置

**Comment by Yumega** [comment]
> 设置词典默认高度 99999 即可。

在哪里设置默认高度？找不到位置

**Comment by crimx** [comment]
在[沙拉查词设置](https://saladict.crimx.com/manual.html#open-setting)的「词典设置」中，点击相应词典的小铅笔即可编辑。
