### ISSUE TITLE
pdf阅读器双击选词错误

### ISSUE THREAD

**Issue by zhanggenex** [crimx/ext-saladict#1364]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome 91.0.4472.77] 
- 沙拉查词版本: [7.19.0] 

## 描述问题

pdf阅读器，双击选词出现错误
1. 双击行首或者行尾的单词，会额外选中前一个或者后一个单词
2. 双击某个单词，会额外选中前后字体不一样的单词

## 复现步骤

1. 打开一篇pdf，双击选中行首或者行尾单词
2. 打开一篇pdf，双击选中某个和前后字体不一样的单词

## 期待的正常行为

正常情况下应该只是选中双击的单词

## 截图

1. 双击行首或者行尾的单词，会额外选中前一个或者后一个单词
![image](https://user-images.githubusercontent.com/26472848/121157471-2d831f80-c87c-11eb-94fa-87c93023a67e.png)
2. 双击某个单词，会额外选中前后字体不一样的单词
![image](https://user-images.githubusercontent.com/26472848/121157598-4986c100-c87c-11eb-82c2-6598603817dc.png)

## 额外信息

你们的项目应该是用了其他的pdf阅读器，但是如果可以的话，请提供一下它的反馈问题的地址，我愿意去此处提交反馈，pdf阅读器修复之后再更新你们的项目。这个错误确实太影响用户体验了，请务必关注一下！感谢！

**Comment by crimx** [comment]
见[常见问题与答复](https://saladict.crimx.com/q&a.html#%E9%97%AE%3A-pdf-%E5%88%92%E8%AF%8D%E5%AD%97%E7%AC%A6%E6%98%BE%E7%A4%BA%E4%B8%8D%E5%AF%B9%EF%BC%88%E5%A6%82-f-%E4%B8%8E-%C6%92%EF%BC%89%2F-pdf-%E5%88%92%E8%AF%8D%E6%8D%A2%E8%A1%8C%E7%9A%84%E5%8D%95%E8%AF%8D%E7%B2%98%E8%BF%9E%E5%9C%A8%E4%B8%80%E8%B5%B7%E3%80%82)。沙拉查词用的是 [PDF.js](https://github.com/mozilla/pdf.js) 自带的阅读器。

**Comment by zhanggenex** [comment]
[外部pdf阅读器翻译教程](https://github.com/crimx/ext-saladict/discussions/493)不错，已入坑
