### ISSUE TITLE
查词面板选中输入框所有文本后，敲第一个字符会出两个

### ISSUE THREAD

**Issue by Cleansweep7** [crimx/ext-saladict#1365]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome80.0.3987.163] 
- 沙拉查词版本: [v7.18.1] 

## 描述问题

查词面板选中输入框所有文本后，敲第一个字符会立即出两个那个字符

## 复现步骤

1. 打开https://www.bilibili.com/video/BV18b4y1Z7ch
2. 选中标题文本，点击沙拉标志，弹出查词面板
3. 点击输入框中间，所有文本会被选中
4. 切换成中文输入法，按下a
5. 输入框立马出现两个a，没有中文输入法的a

## 期待的正常行为

1. 打开https://www.bilibili.com/video/BV18b4y1Z7ch
2. 选中标题文本，点击沙拉标志，弹出查词面板
3. 点击输入框中间，所有文本会被选中
4. 切换成中文输入法，按下a
5. 输入框立马出现中文输入法的a

## 截图

![image](https://user-images.githubusercontent.com/59435862/121531947-78926380-ca31-11eb-987f-599ce78fc699.png)

![image](https://user-images.githubusercontent.com/59435862/121532031-8ea02400-ca31-11eb-8906-73c61edcf3c6.png)

![image](https://user-images.githubusercontent.com/59435862/121532177-b099a680-ca31-11eb-9ec5-57009eba63c5.png)

## 额外信息

总之解决一下文本全选后，它会自动多打一个字符的问题吧

**Comment by crimx** [comment]
更新一下[版本](https://saladict.crimx.com)。
