### ISSUE TITLE
沙拉查词在quicker中使用截图功能无法正常使用，已经给了剪切板的权限

### ISSUE THREAD

**Issue by FirmamentWu** [crimx/ext-saladict#1367]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 截图

![image](https://user-images.githubusercontent.com/63577034/121778225-a78f0d80-cbc8-11eb-8830-ccf293b145db.png)

## 额外信息

> 
### 

> __

**Comment by crimx** [comment]
Duplicate of #1358
