### ISSUE TITLE
谷歌翻译引擎的精度大不如前

### ISSUE THREAD

**Issue by ZLYong** [crimx/ext-saladict#1369]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome91] 
- 沙拉查词版本: [v7.19.0] 

## 描述问题

谷歌引擎翻译一个网页段落时，在英文翻译中文模式下，得到的结果和谷歌翻译网页版大不一样。翻译效果没有以前的版本好，对比百度翻译和彩云小译的结果，谷歌的效果是最差的，但是这绝对不是谷歌翻译的真实水平。

## 复现步骤

https://pubs.acs.org/doi/10.1021/acs.macromol.1c00667
对开头“Abstract”部分划词翻译，就能看到问题，谷歌翻译的结果非常不通畅。

## 期待的正常行为

能做到和谷歌翻译网页版一样就行

**Comment by zrongcheng** [comment]
同，谷歌翻译的简直不能看，期待修复 @crimx ，谢谢

**Comment by rainzm** [comment]
感觉可以在词典账号里面增加 谷歌翻译，这样用户可以自己配置账号以获得稳定的体验和准确的结果。

**Comment by crimx** [comment]
v7.19.1 已修复，请等待审核上架。

**Comment by zrongcheng** [comment]
又出现了，翻译不如有道，和谷歌官方的也不一样
