### ISSUE TITLE
希望提供crx文件下载

### ISSUE THREAD

**Issue by IOL0ol1** [crimx/ext-saladict#137]
- 平台：
**360极速浏览器 | 9.0.1.162
内核版本号 | 55.0.2883.87**
修订版本 | d41396325a5480bbf82d44a8cc0c2875b6a6213e
操作系统 | Windows
JavaScript | V8 5.5.372.32
Flash | 27.0.0.187
用户代理 | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36 QIHU 360EE
命令行 | "D:\360Chrome\Chrome\Application\360chrome.exe" --flag-switches-begin --disable-direct-write --enable-tab-audio-muting --flag-switches-end
可执行文件路径 | D:\360Chrome\Chrome\Application\360chrome.exe
个人资料路径 | d:\360chrome\chrome\User Data\Default
Compiler | MSVC 2015

- 类型：
**建议在Release中添加.crx文件下载**

- 期待：
上架360极速浏览器应用商店
http://open.chrome.360.cn/extension_dev/upload.html

**Comment by crimx** [comment]
发布后等待打包完成才上传

**Comment by crimx** [comment]
已上传

**Comment by crimx** [comment]
国内平台太多了，实在没精力一一上传。360 还在用 55 内核有些过时了，最好安装新版 Chrome 享受最新特性。

**Comment by crimx** [comment]
嗯，理解。

**Comment by IOL0ol1** [comment]
> > 发布后等待打包完成才上传
> 
> 希望在Released页面放crx文件，那些下载链接基本都用不了。没有梯子很无奈...

[Releases页面有提供国内crx文件下载方式，你可以仔细看看](https://github.com/crimx/ext-saladict/releases)

**Comment by sky5454** [comment]
> > > 发布后等待打包完成才上传
> > 
> > 
> > 希望在Released页面放crx文件，那些下载链接基本都用不了。没有梯子很无奈...
> 
> [Releases页面有提供国内crx文件下载方式，你可以仔细看看](https://github.com/crimx/ext-saladict/releases)

基本都下载不了，有一个可以，但是版本更新不及时
