### ISSUE TITLE
兼容 xhtml 网页

### ISSUE THREAD

**Issue by qisc123** [crimx/ext-saladict#1374]
## 设备信息
- 操作系统: manjaro-linux
- 浏览器版本: firefox 89
- 沙拉查词版本: v7.19.0

## 描述问题

在sicp的网页版中使用划词，lexico词典有概率会render error

## 复现步骤

https://sarabander.github.io/sicp/html/1_002e3.xhtml#g_t1_002e3_002e1
页面中划词
比如incremented Rather

## 期待的正常行为

正常显示

## 截图

![2021-06-22_19-04](https://user-images.githubusercontent.com/40145802/122914951-cb531000-d38d-11eb-9f0f-b07bbd81a2ee.png)

**Comment by crimx** [comment]
感谢反馈。问题为对 xhtml 网页提供兼容。
