### ISSUE TITLE
插件在 Edge 扩展中全部设置均无法选择全局

### ISSUE THREAD

**Issue by 502y** [crimx/ext-saladict#1375]
## 设备信息
- 操作系统: [Win 10] 
- 浏览器版本: [Edge 91.0.864.54] 
- 沙拉查词版本: [v7.19.0] 

## 描述问题
插件在 Edge 扩展中全部设置均无法选择全局

## 复现步骤
1.右键沙拉查词图标
2.点击管理扩展
3.点击键盘快捷方式
4.滚动到沙拉查词相关选项区域
5.发现所有沙拉查词相关选项均被锁定为“在 Microsoft Ed...”

## 期待的正常行为
激活扩展选项可改为“全局”

## 截图
![MRSPJ8`PX(_PTW((N8~G~YK](https://user-images.githubusercontent.com/53784463/122940139-c9e21180-d3a6-11eb-8a9d-6f8c43e7143c.png)

**Comment by crimx** [comment]
激活扩展是浏览器内部给每个扩展的快捷键，不需要管。为其它的设置快捷键，然后就可以看到全局配置亮了。

**Comment by 502y** [comment]
> 激活扩展是浏览器内部给每个扩展的快捷键，不需要管。为其它的设置快捷键，然后就可以看到全局配置亮了。

多谢多谢
