### ISSUE TITLE
无法打开应用Safari

### ISSUE THREAD

**Issue by NYXFLOWER** [crimx/ext-saladict#1376]
## 设备信息
- 操作系统: [macOS Big Sur v11.4] 
- 浏览器版本: [Safari 14.1.1] 
- 沙拉查词版本: [v7.19.0] 

## 描述问题

无法打开从[网盘](https://72k.us/dir788/24782725-37758132-dc15d5)下载的沙拉词典应用。

## 复现步骤

1. 从 https://72k.us/dir788/24782725-37758132-dc15d5 下载 “沙拉查词-聚合词典划词翻译_v7.19.0-safari.zip” 应用
2. 解压并双击应用图标
3. 弹出窗口“it can't be opened because Apple cannot check it for malicious software” （参见截图）

## 期待的正常行为

打开应用...

## 截图

<img width="257" alt="Screenshot 2021-06-22 at 17 29 10" src="https://user-images.githubusercontent.com/38955723/123002640-2120bb80-d380-11eb-88cb-10ed73866bed.png">

**Comment by crimx** [comment]
这是因为没有签名，需要右键打开。
