### ISSUE TITLE
在以下网页无法使用

### ISSUE THREAD

**Issue by linsui** [crimx/ext-saladict#138]
- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）
win10,chrome66.0.3359.181
- 类型：错误？建议？
错误
- 重现：提供详细的可重现问题的操作。
https://www.hindawi.com/journals/cin/2018/7068349/
在此网站上划词窗口会透明，界面会不正常
此网站谷歌翻译也无法使用

**Comment by crimx** [comment]
感谢反馈，已提升兼容性。会在两周以内发布。
