### ISSUE TITLE
增加单词黑白名单，过滤专业单词（翻译不如不翻译）

### ISSUE THREAD

**Issue by chenzhiguo** [crimx/ext-saladict#1381]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 理想情况下，沙拉查词应该怎么做

有很多专业文档，里面很多命名性质的单词，其本身没有必要翻译成具体的中文，这类单词希望可以支持用户手动加入白名单，翻译结果中过滤这些单词，保持原来英文。这样体验会更好些。

**Comment by crimx** [comment]
沙拉查词的翻译服务都是用的第三方，抱歉没有办法可以做到这样的控制。
