### ISSUE TITLE
[请求实现新功能] 实现在按钮之外的附近区域移动整个窗口的功能

### ISSUE THREAD

**Issue by luis-arch** [crimx/ext-saladict#1384]
## 设备信息
- 操作系统: [Window10] Window10
- 浏览器版本: [Chrome  90.0.4430.212] 
- 沙拉查词版本: [v7.19.0] 

## 请描述目前使用沙拉查词遇到什么不便

在阅读某些英文网页时会出现英文很小，需要放大网页，因此很容易出现如下情况：
![image](https://user-images.githubusercontent.com/61920061/124342759-dcefaf80-dbf8-11eb-9df0-64c8feaab421.png)

这个时候我想通过移动浏览框来实现看清翻译，但发现下图红框区域似乎无法移动，只有蓝框区域才可移动整个窗口

![Snipaste_2021-07-03_12-27-31](https://user-images.githubusercontent.com/61920061/124342919-360c1300-dbfa-11eb-9dcd-e51b2eeecf4f.jpg)

另外在上图红框区域我发现还是有不少不是选中该按钮的空白地方，不知道能否将这些地方设置为可移动窗口的鼠标点位

## 理想情况下，沙拉查词应该怎么做

![image](https://user-images.githubusercontent.com/61920061/124342998-e24df980-dbfa-11eb-970b-0cb9b6d78753.png)

能够实现在上图红色填充区域移动整个窗口

**Comment by crimx** [comment]
网页放大的情况可以试试[独立窗口](https://saladict.crimx.com/manual.html#triple-ctrl)。

**Comment by luis-arch** [comment]
> 网页放大的情况可以试试[独立窗口](https://saladict.crimx.com/manual.html#triple-ctrl)。

这个我也有尝试过，但由于浏览器本身没有始终将页面保持在最前的设置，所以个人认为可能对改善我这个体验没啥太大用处？

请问这个实现具有难度吗？其实大多数情况也不会遇到类似的事，只是偶尔英文网页格式问题出现而已。太难实现的话，其实这个优先级可以放得很靠后，我也关闭这个issue。

**Comment by luis-arch** [comment]
目前看了下feature request 似乎#1368这个假如实现，应该也能解决我的问题，我就先关闭问题，静等作者的更新了。（希望可以因此提高#1368的优先级）
