### ISSUE TITLE
it would be better if the extension support translation in original pdf reader in chromium edge

### ISSUE THREAD

**Issue by Mew1998** [crimx/ext-saladict#1385]
I found that this extension can not work when I use the original pdf reader in chromium edge. It would be better if the extension support translation in original pdf reader in chromium edge.
![Screenshot 2021-07-03 172130](https://user-images.githubusercontent.com/74886522/124349707-3a005b00-dc23-11eb-91f0-35e54069138d.png)

**Comment by gricn** [comment]
You can use [Native Version](https://saladict.crimx.com/en/native.html) to implement it.
