### ISSUE TITLE
Youdao dictionary cannot translate Japanese into English in the way Google translation does.

### ISSUE THREAD

**Issue by hongyi-zhao** [crimx/ext-saladict#1386]
I was puzzled that Youdao dictionary cannot translate Japanese into English in the way Google translation does. See below for more detailed info: 

![image](https://user-images.githubusercontent.com/11155854/124465523-1c202b00-ddc8-11eb-90ea-0de59e168976.png)

Any hints will be highly appreciated.

Regards,
HY

**Comment by crimx** [comment]
Use "Youdao Translate" instead of Youdao Dictionary for machine translating by simply switching to "Translation mode" profile.

Or you make turn on the dictionary in Saladict settings.

**Comment by hongyi-zhao** [comment]
I've switched to "Translation mode", but there are still some engines that can't do the job:

![image](https://user-images.githubusercontent.com/11155854/124493311-0d497080-dde8-11eb-9446-0cf1cceb3709.png)

![image](https://user-images.githubusercontent.com/11155854/124493389-2a7e3f00-dde8-11eb-9f61-21e124b917a5.png)
