### ISSUE TITLE
段落<p></p>中的<code></code>会被翻译

### ISSUE THREAD

**Issue by cubic759** [crimx/ext-saladict#1389]
## 设备信息
- 操作系统: [Windows10] 
- 浏览器版本: [Edge91] 
- 沙拉查词版本: [v7.19.0] 

## 请描述目前使用沙拉查词遇到什么不便

段落\<p>\</p>中的一些代码，如Thread.Sleep(0)，即使它已经用\<code>\</code>括住仍然会把.当作句号进行翻译，影响理解。

## 理想情况下，沙拉查词应该怎么做

直接略过不译段落\<p>\</p>中\<code>\</code>中的内容。

**Comment by crimx** [comment]
目前沙拉查词是直接获取划词扔给了第三方翻译服务翻译，还做不到中间跳过一些词语。可以看一看其它的词典应用有没有类似的解决方案？
