### ISSUE TITLE
无法默认打开 PDF | 右键图标只出来最基本的菜单

### ISSUE THREAD

**Issue by pessoalzy** [crimx/ext-saladict#139]
- 平台：Windows 10 | Chrome (67.0.3396.79)

- 类型：错误

![snipaste_2018-06-10_19-56-48](https://user-images.githubusercontent.com/26316942/41201355-f1a5de68-6ce8-11e8-8074-c0bc10fc6c66.png)

1. 如上图。一开始是不管怎么开关都是这样，然后我准备排查是不是哪个扩展程序造成的，一顿开关重启浏览器之后，就只有刚启用时是这样了，重启一次浏览器之后就正常了。

2. 不能默认打开 pdf（已经允许了 沙拉查词 访问文件网址），选项里选中了默认用它打开 pdf，实际打开时也只会是直接 chrome 打开。目前还不知道是不是和哪个插件冲突。
只要任意切换一下 SwitchOmega 的情景模式（哪怕是点一下正在使用的），Chrome 打开的 pdf 文件就会自动刷新一下，变成由 沙拉查词 打开的模式。关掉 SwitchOmega 仍不能解决不默认打开的问题。

**Comment by crimx** [comment]
是不是禁用过？关闭重启 Chrome 试试

**Comment by crimx** [comment]
嗯，这个不排除其它扩展冲突。但应该不是 SwitchOmega ，因为我测试过没问题的。还有更新情况可以使用 comment 而不是修改主题，方便有同样问题的人参考。

**Comment by crimx** [comment]
如果发生了 PDF 重定向有冲突，Chome 右上角会有黄色感叹号提醒，比如 IDM 如果设置 PDF 下载就会跟 Saladict 冲突。

**Comment by crimx** [comment]
新版已提升兼容性，如有问题欢迎开新 issue
