### ISSUE TITLE
请求添加《牛津高阶英语词典》（Oxford Advanced Learner's Dictionary，OALD，非 Lexico）

### ISSUE THREAD

**Issue by MacbethOL** [crimx/ext-saladict#1392]
## 词典名称以及链接
Oxford Advanced Learner's Dictionary (OALD) 牛津高阶英语词典
https://www.oxfordlearnersdictionaries.com/

## 沙拉查词的已有的词典为什么不能满足？

我其实看到有其他用户提出添加 OALD 的需求，但可能是因为没有按照版规来提，所以没有得到开发团队的重视。下面我说一下，为什么这个词典非常有必要添加。

https://en.wikipedia.org/wiki/Comparison_of_English_dictionaries
以上这篇维基百科文章中，横向比较了世界上最权威的英语词典（不涉及时下流行的英语网络词典）。文章最末所列的六款学习型词典中，OALD 是历史最悠久（初版 1948 年），更新频度最高（最新第 10 版），同时又是最与时俱进的（最新版 2020 年）。

OALD 在世界英语学习领域的影响力举足轻重，而 Lexico 所收录的词典为 Oxford Dictionary of English (ODE)，是一款母语型词典，绝非 OALD。通过 Lexico 搜不到 OALD 上的词条，这与 Collins 的网站是不同的（collinsdictionary.com 可以同时搜到学习型和母语型词典中的词条）。想要在网上查 OALD，仅能通过前文给出的网站。

OALD 具体强在哪？权威在哪？下面我通过今天查过的一个单词来举例：

## 单词举例

grit 的基本义项用中文来解释就是“砂；砂砾；砂粒；硬颗粒”的意思，并不复杂。

查过母语型的 Oxford Dictionary of English (Lexico) 和 Collins English Dictionary (collinsdictionary.com)，以及所有六款学习型词典，发现对其解释大同小异，其中 Collins 的母语型和学习型词典的解释要更为出彩一些，OALD 的释义处于平均水准。

但一部词典的核心竞争力除了释义，还有例句。OALD 的例句，是使它在两款权威母语型词典和六款权威学习型词典的激烈竞争中，脱颖而出的关键所在，具体请看词典截图：

## 截图

**学习型：Oxford Advanced Learner's Dictionary (OALD)**
![image](https://user-images.githubusercontent.com/87238628/125170304-0e601080-e1e1-11eb-824b-a6a03770b118.png)

**母语型：Oxford Dictionary of English (Lexico)**
![image](https://user-images.githubusercontent.com/87238628/125170373-52ebac00-e1e1-11eb-8b3f-0b22a983db02.png)

**母语型：Collins English Dictionary (collinsdictionary.com)**
![image](https://user-images.githubusercontent.com/87238628/125170403-79a9e280-e1e1-11eb-92a3-bb8297da4be6.png)

**学习型：Collins COBUILD Advanced Dictionary (collinsdictionary.com)**
![image](https://user-images.githubusercontent.com/87238628/125170433-a100af80-e1e1-11eb-8d53-058001159c48.png)

**学习型：Longman Dictionary of Contemporary English**
![image](https://user-images.githubusercontent.com/87238628/125170518-f63cc100-e1e1-11eb-8798-1cdd6992fbd4.png)

**学习型：Cambridge Advanced Learner's Dictionary**
![image](https://user-images.githubusercontent.com/87238628/125170766-25076700-e1e3-11eb-97d7-f1716038da02.png)

**学习型：Macmillan English Dictionary for Advanced Learners**
![image](https://user-images.githubusercontent.com/87238628/125170820-74e62e00-e1e3-11eb-9cb6-25f988a31481.png)

**学习型：Merriam-Webster's Advanced Learner's English Dictionary**
![image](https://user-images.githubusercontent.com/87238628/125170838-87f8fe00-e1e3-11eb-89e3-1eea34d29f95.png)

## 额外信息

通过以上八张截图可以看出，grit 的基本义项非常简单，但仅有 OALD 强调了该词的用法，并“奢侈”的通过三条例句，对该词用法做出了完美的展示——两条例句展示 bit/piece of grit 的用法搭配，一条例句展示 grit 的惯用语境。而大多数词典要么不提供例句，要么仅提供一条例句。如此细致的词典编撰，对英语学习者的帮助是巨大的。

这里要特别指出，虽然有的词典提供了例句库，但例句库中的例句是基于搜索引擎由程序提供的，这和由经验丰富的词典编撰者人工挑选出的，充分阐明单词意义及用法的例句，存在质的差别。因此，如果能够收录这款词典，必将极大提升“沙拉查词”的词典聚合完善度。

感谢贵团队开发出了如此优秀的工具，希望以上提出的建议，能够采纳！

**Comment by MacbethOL** [comment]
7 月 10 日，刚发出这个需求，就被 GitHub 自动封禁账号了。虽然立即向 GitHub 发送了恢复申请，但一直没有回复。直到今天看到一封 GitHub 的调查问卷，才发邮件再次询问，结果顺利解封。

希望看到此贴的各位能支持一下这个需求，更希望勤劳、高贵的开发团队，看到我为了发这贴经历了如此的折腾，能够重视这个需求，谢谢大家！

**Comment by crimx** [comment]
已添加。
