### ISSUE TITLE
韩语naver词典不能正常显示

### ISSUE THREAD

**Issue by gwuse** [crimx/ext-saladict#1398]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Edge 91.0.864.70（最新）] 
- 沙拉查词版本: [v7.19.0] 

## 描述问题

开启naver词典使用时划词不会翻译，有无梯子都不行，点进去转到naver网页可以正常查看，
## 复现步骤

1.设置中打开naver选项
2.寻找韩语单词划词
3.未出现翻译

## 期待的正常行为

出现翻译

## 截图

![image](https://user-images.githubusercontent.com/54311337/126052497-fac244ad-965f-46f5-9855-847f3f7d385b.png)

**Comment by crimx** [comment]
感谢反馈！

**Comment by crimx** [comment]
已修复。
