### ISSUE TITLE
Ctrl+C操作复制浏览器文本会自动关闭沙拉查词插件

### ISSUE THREAD

**Issue by wlei9534** [crimx/ext-saladict#1402]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome91] 
- 沙拉查词版本: [V7.19] 

每次在浏览器中想要通过Ctrl+C或者双击Ctrl后，沙拉查词插件会自动关闭，再按一次又会打开，而且Ctrl+C无法正常复制文本
## 描述问题

打开网页，选取一段文字，会正常显示沙拉查词图标和界面，此时可以正常使用，想要通过Ctrl+C或者双击Ctrl时，一方面无法正常复制选中的文本，另一方面沙拉查词的插件会自动关闭，再次按Ctrl+C或者双击Ctrl时，插件又会重新开启，此时仍然不能复制文本。而选中文本之后右键复制，可以正常复制内容，且沙拉查词插件也不会受到影响。

## 期待的正常行为

1.可以正常复制浏览器文本
2.按快捷键复制浏览器文本时不会自动关闭沙拉查词插件

**Comment by crimx** [comment]
有没有设置了什么快捷键？

**Comment by Oliver-F1** [comment]
> 
> 
> 有没有设置了什么快捷键？

请大佬修复下谷歌翻译，完全不准，好像不是原来的接口了？

**Comment by wlei9534** [comment]
> 有没有设置了什么快捷键？

感谢大佬回复！我重新安装了一下插件就好了，可能我对插件有些地方的设置不对。
