### ISSUE TITLE
谷歌翻译完全不准确

### ISSUE THREAD

**Issue by Oliver-F1** [crimx/ext-saladict#1403]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 描述问题

昨天晚上使用还好好的，今天突然翻译不准了，完全不是谷歌翻译

## 期待的正常行为

![图片](https://user-images.githubusercontent.com/59132857/126579896-07f1d38f-45b7-43b4-ad22-a93706d98d2b.png)

## 截图

![图片](https://user-images.githubusercontent.com/59132857/126579783-52bad9d1-ddb7-4915-a40b-3e145dee0e34.png)

**Comment by meiguoofa** [comment]
和你有同样的问题，谷歌翻译完全不行，在乱翻译，和谷歌翻译官网的翻译完全不一样

**Comment by crimx** [comment]
v7.19.1 已修复，请等待审核上架。

**Comment by zrongcheng** [comment]
又出现了，翻译不如有道，和谷歌官方的也不一样 @crimx

**Comment by miracle-cat** [comment]
> 又出现了，翻译不如有道，和谷歌官方的也不一样 @crimx

我也是，现在谷歌翻译又是一股浓浓的机翻味了。
他们翻译句子的时候不像是在翻译句子，而像是翻译一堆连起来的词组
