### ISSUE TITLE
关于遮挡输入框的问题

### ISSUE THREAD

**Issue by wk989898** [crimx/ext-saladict#1406]
有时候输入时，面板会遮挡住输入框。能不能考虑在监听到用户输入时，让面板消失？

**Comment by crimx** [comment]
在查词面板外点击沙拉查词会自动消失的。请按模板描述你的问题以及复现步骤。

**Comment by wk989898** [comment]
我会遇到在输入框（例如谷歌搜索）中查询单词的情况，当我想搜索其他东西时，光标已经在输入框内，但是查词面板会遮挡输入框，这让我不得不点击其他地方使查词面板消失，然后在点击输入框输入内容。
![cut](https://user-images.githubusercontent.com/55834428/127152373-24ccff91-20e4-4f77-9c19-3775fed5a240.png)

**Comment by crimx** [comment]
唤起了查词框必然是保持最前的，按一下 Esc 查词面板就会消失。

**Comment by wk989898** [comment]
按下ESC后能否让图标也跟着消失呢🤔

**Comment by crimx** [comment]
这个可以补上，感谢反馈。

**Comment by crimx** [comment]
我看了一下，按下 ESC 沙拉图标是会消失的。

**Comment by wk989898** [comment]
如果鼠标在图标上，图标会保持存在，移开后就会消失，和ESC没有关系。和我的设置有关系吗:thinking:
<img width="637" alt="截屏2021-10-08 09 05 04" src="https://user-images.githubusercontent.com/55834428/136482418-0d567e57-254a-44b3-a1ed-92a9ff081985.png">

**Comment by crimx** [comment]
> 如果鼠标在图标上，图标会保持存在，移开后就会消失，和ESC没有关系。

这个原来的设计就是这样的。使用鼠标的话什么情况下会长时间停留在一个位置？

**Comment by wk989898** [comment]
在搜索框查询单词时，图标也有概率遮挡搜索。按下esc只会让面板消失，如果移动鼠标让图标消失，那也不差点击一下的功夫让面板也消失。能否在按下esc的同时，让图标(即使鼠标位于图标上)也跟着消失？

**Comment by crimx** [comment]
按下 esc 沙拉图标也会消失的。如果鼠标位于图标上说明已经在用鼠标，则不存在鼠标无法移动的问题。对于不用鼠标的情况也可以启用其它划词模式。
