### ISSUE TITLE
能不能设置快捷键？

### ISSUE THREAD

**Issue by drcege** [crimx/ext-saladict#141]
- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）
    Windows 10 / Chrome  66.0.3359.181

- 类型：建议
    能不能给每个操作设置快捷键？我经常使用网页翻译功能，但是必须得用鼠标右键页面空白，或者右键右上角图标，比较繁琐。

比较方便的方式是：
1. 可以给每个操作设置快捷键
2. **`右上弹框`** 可以设置为网页翻译，点击图标即可网页翻译（很多其他扩展都是这样的）。目前只能设置预加载 **`剪贴板`** 和 **`页面划词`**

**Comment by crimx** [comment]
你好，快捷键原本是等 Firefox 支持完善了再加，既然有人提到了可以提前在 Chrome 上实现。最近有点忙，有空再加上去。

**Comment by drcege** [comment]
😄 其实我比较喜欢第二个方案，这样只用鼠标也很方便，而且实现起来也比较简单。

**Comment by crimx** [comment]
嗨，经过调查，第二个方案是无法实现的，因为设置了弹框后不能再监听点击并抑制弹框。

**Comment by drcege** [comment]
好的 ^_^

我没开发过chrome扩展，只是感觉一般情况下，如果能监听到点击，然后可以手动触发弹框逻……我就随便说说😝

**Comment by crimx** [comment]
新版已添加
