### ISSUE TITLE
教程中推荐的youtube字幕固定 油猴脚本失效

### ISSUE THREAD

**Issue by CedricShang** [crimx/ext-saladict#1413]
## 设备信息
- 操作系统: [Windows10] 
- 浏览器版本: [Chrome92] 
- 沙拉查词版本: [v7.19.1] 

## 请描述目前使用沙拉查词遇到什么不便

之前工作正常，近期失效，鼠标操作后字幕没有变化

## 理想情况下，沙拉查词应该怎么做

如题

## 替代方案

目前使用quicker的ocr识别+沙拉查词全局快捷键解决。但是没有自动断句的上下文，还是很麻烦。

## 额外信息

暂无

**Comment by pickalexrener** [comment]
我自己测试的没有问题，依然能固定和上下文嗅探
