### ISSUE TITLE
词典设置保存失败

### ISSUE THREAD

**Issue by ximeibin** [crimx/ext-saladict#1418]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Firefox90.0.2 (64 位)] 
- 沙拉查词版本: [v7.19.1] 

## 描述问题

词典设置无法修改,浏览器提示

>设置保存失败
>QuotaExceededError: storage.sync API call exceeded its quota limitations.

## 复现步骤

每次设置词典都可以复现

## 期待的正常行为

正常设置词典

## 截图

[![fE4qW6.md.png](https://z3.ax1x.com/2021/08/04/fE4qW6.md.png)](https://imgtu.com/i/fE4qW6)

**Comment by crimx** [comment]
Duplicate of #1288
