### ISSUE TITLE
个别网站选词后沙拉图标不显示

### ISSUE THREAD

**Issue by xstarrr** [crimx/ext-saladict#142]
- 平台：

> Windows 10  
> Chrome 67.0.3396.87（正式版本） （64 位）

- 类型：错误

> 网站 [Inno Setup](http://www.jrsoftware.org/ishelp/)
> 选中单词后沙拉图标不显示

- 查词模式：

> 显示图标

**Comment by crimx** [comment]
你好，这网站用了一个很老的过时技术编写的，无法兼容。
