### ISSUE TITLE
希望独立查词窗口的字体大小也可以调整

### ISSUE THREAD

**Issue by anklcaptain** [crimx/ext-saladict#1421]
## 设备信息
- 操作系统: win10 
- 浏览器版本: Microsoft edge dev 版本 94.0.972.0  
- 沙拉查词版本: 7.19.1 

## 请描述目前使用沙拉查词遇到什么不便
在调整了查词面板的字体大小后，设置大小如图
![QQ截图20210806100914](https://user-images.githubusercontent.com/70800107/128445839-199a4c3d-5fa5-4014-a04e-a8dfb3d94c4e.png)
浏览器内查词面板确实生效，但独立查词窗口没有变化
![QQ截图20210806100956](https://user-images.githubusercontent.com/70800107/128445918-44063868-796b-4f99-b1bb-45b766615dbc.png)
![Snipaste_2021-08-06_10-10-23](https://user-images.githubusercontent.com/70800107/128445929-62837bbf-1071-432c-a7e5-5b019d402ce1.png)

## 理想情况下，沙拉查词应该怎么做
希望独立查词面板的字体大小也能随设置变化，或者在独立查词面板的设置里加入字体大小的调整设置

**Comment by crimx** [comment]
感谢反馈。这应该是 bug ，我看一下。
