### ISSUE TITLE
关闭发音波形控制按钮不起作用

### ISSUE THREAD

**Issue by uldaman** [crimx/ext-saladict#1423]
## 设备信息
- 操作系统: [win10] 
- 浏览器版本: [Microsoft Edge 92.0.902.67] 
- 沙拉查词版本: [v7.19.1] 

## 描述问题

在设置界面的查词面板选项中, 关闭波形控制按钮. 打开沙拉查窗口后, 依然出现控制按钮.

## 复现步骤

1. 打开"设置界面"
2. 点击"查词面板"
3. 关闭"波形控制按钮"
4. 打开查词窗口
5. 发现依然有波形控制按钮

## 期待的正常行为

打开沙拉查窗口后, 应该没有波形控制按钮.

**Comment by crimx** [comment]
独立窗口确实存在这个 bug，感谢反馈。
