### ISSUE TITLE
希望能添加DeepL翻译

### ISSUE THREAD

**Issue by ZhhHugoChang** [crimx/ext-saladict#1425]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 请描述目前使用沙拉查词遇到什么不便

希望能添加DeepL翻译

## 理想情况下，沙拉查词应该怎么做

希望能添加DeepL翻译

## 替代方案

希望能添加DeepL翻译

## 额外信息

希望能添加DeepL翻译

**Comment by gricn** [comment]
#705 问题重复。该需求已被作者添加到[Todolist](https://github.com/crimx/ext-saladict/projects/3#column-5755822)中
