### ISSUE TITLE
Safari 无法使用划词；设置无法保存，提示权限background申请失败

### ISSUE THREAD

**Issue by XaverWang** [crimx/ext-saladict#1434]
## 设备信息
- 操作系统: [Mac OS 11.2.1] 
- 浏览器版本: [Safari 14.0.3] 
- 沙拉查词版本: [7.19.1] 

## 描述问题

划词之后没有出现图标。
设置无法保存，提示”权限background申请失败“。
![1628662492937](https://user-images.githubusercontent.com/88763379/128978799-d12a6016-4a0e-47df-b569-72169c3bc9d5.jpg)

多从重装沙拉划词也无法解决。

## 截图

<img width="543" alt="image" src="https://user-images.githubusercontent.com/88763379/128978455-25b1cdca-798c-436e-bc41-5ba5859d5135.png">

**Comment by crimx** [comment]
感谢反馈！这个权限可能只有 chrome 能用，我会把它去掉。但这个应该不影响默认的设置使用。看看 https://saladict.crimx.com/safari 有无漏了步骤。比如点击地址栏旁的沙拉图标选总是允许所有网页。

**Comment by zjz317** [comment]
+1

**Comment by crimx** [comment]
[v2.20.0](https://saladict.crimx.com/safari) 已修复。
