### ISSUE TITLE
一段话（长句）的单词无法翻译

### ISSUE THREAD

**Issue by goto8080** [crimx/ext-saladict#1439]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome 91.0.4472.77] 
- 沙拉查词版本: [v7.19.1] 

## 描述问题

比如 一段话（It looks like this is your first）无法信息，显示无返回接口

## 截图

![image](https://user-images.githubusercontent.com/8896533/129302732-a328fca1-d431-4e8b-8c63-f6ce9d2c368b.png)
![image](https://user-images.githubusercontent.com/8896533/129302814-cf6b609d-aa9e-49cb-a218-930049cb92bf.png)

## 额外信息

比如一段这样的话  It looks like this is your first 无法翻译，以前可以现在不知道为什么不行了。 单独翻译比如 looks 就可以

**Comment by crimx** [comment]
你好，我这边测试是可以的。你可以点击词典标题看看能不能打开词典页面。

![image](https://user-images.githubusercontent.com/6882794/129302911-be708f3d-a7f8-42b3-b134-985bd256ec30.png)

**Comment by luoruiqing** [comment]
同样的问题
