### ISSUE TITLE
一些请求,关于浏览器外查词

### ISSUE THREAD

**Issue by superblackcat** [crimx/ext-saladict#1441]
## 设备信息
- 操作系统: [Window10专业版] 
- 浏览器版本: [edge 最新] 
- 沙拉查词版本: [v7.19.1] 

## 我遇到的问题是想在typora中进行搜索

  1. typota默认的是谷歌搜索,可以通过修改文件的方式进行修改为百度搜索.
  2. 因此在我使用typora做单词备忘录的时候,想通过一样的原理进行搜索,但是我网上并没有找到沙拉查词的搜索引擎(不知道怎么称呼,就暂且这么叫了).
  3. 百度的搜索引擎格式在typora中是"https://www.baidu.com/#ie={inputEncoding}&wd=%s"
  4. 我在edge浏览器的"地址栏搜索引擎"(在设置搜索即可找到)并没有发现,所以冒昧向您求助.

## 理想情况下，沙拉查词应该怎么做

- 期待可以提供一个类似的搜索引擎.在此条件下,也可以实现在浏览器地址栏查词.
- 如果可以实现直接在typora中,点击搜索后,直接出现独立窗口可以实现,将会更好,因为是法科生,所以并不知道如何操作,如果方便,还请您考虑这一建议.
- 但是我的设想是基于沙拉查词本质上也是一种搜索引擎的这一猜测,如果实现原理并非如此,恕我冒昧.

## 替代方案

暂无

## 额外信息

如能回复不胜感激.

**Comment by crimx** [comment]
你好，因为没有词典的版权，沙拉查词只会做成浏览器的辅助插件，不会提供单独的站点。浏览器外的使用可以参考[浏览器外划词](https://saladict.crimx.com/native.html#quicker)。
