### ISSUE TITLE
有办法调用google dictionary的查词结果吗？

### ISSUE THREAD

**Issue by lweo** [crimx/ext-saladict#145]
我觉得在所有在线查词web服务里，google dictionary是词库最大，解释最准确的。作者可以考虑集成到插件中～
（扩展里带的几个词典都是用的在线服务，词库并不全，urban dictionary词库是全但不专业）

https://www.google.com/search?q=Dictionary
这个wget好像加密了？

**Comment by crimx** [comment]
嗨，感谢建议！Google Dictionary 是不错，但不好扒。而且现在 Saladict 已经涵盖了大部分主流词典，词根如 etymonline；俚语如 urban dictionary；老牌词典如牛津、剑桥、韦氏、朗文、柯林斯、麦克米伦，可以说解释已经相当全面了。

**Comment by lweo** [comment]
@crimx 你自己是英语重度使用用户吗？我试了这些词典，词库明显和其对应的离线词典不一样

**Comment by crimx** [comment]
与离线版不一样不是很正常么，这些词典本身这么多年都有好多版本。能详细说明一下 Saladict 没有覆盖到的地方么。

**Comment by lweo** [comment]
我没记录，确实很多词没有查到，主要是用麦克米伦，柯林斯，vvocabulary。查不到的就google搜索了。。

**Comment by crimx** [comment]
嗨，这样还不是很 convincing. 没有数据支撑不太好做判断。

**Comment by lweo** [comment]
不带鼠标悬停功能，为配合Vocabulary discoverer, 又用回FairyDict这个查词扩展了。。

**Comment by crimx** [comment]
嗯，这个 FairyDict 也做得十分不错。
