### ISSUE TITLE
希望能够增加欧路词典同步功能, 欧路已有开放api 和接口文档

### ISSUE THREAD

**Issue by goooggle** [crimx/ext-saladict#1457]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 请描述目前使用沙拉查词遇到什么不便

获取欧路词典授权信息
https://my.eudic.net/OpenAPI/Authorization  
![image](https://user-images.githubusercontent.com/75106451/131355233-75a4dc7d-27cd-47c2-98b0-9973b77bfdb8.png)

添加新的单词到单词本 接口文档
https://my.eudic.net/OpenAPI/doc_api_study#-studylistapi-addwords
![image](https://user-images.githubusercontent.com/75106451/131355569-954a0800-bc76-4ed4-affb-d46a2583ed16.png)

需要的参数也很简单 
id 为单词本id , 0为默认单词本
language  为语言
words 为数组 可一次添加多个单词

**Comment by crimx** [comment]
Duplicate of #869
