### ISSUE TITLE
划词被edge dev功能覆盖

### ISSUE THREAD

**Issue by ghost** [crimx/ext-saladict#1459]
## 设备信息
- 操作系统: [Windows 11 专业工作站版 22000.168] 
- 浏览器版本: [Microsoft Edge 版本 94.0.992.4 (官方内部版本) dev (64 位)] 
- 沙拉查词版本: [7.19.1] 

## 描述问题

右键划词的时候被edge dev的划词覆盖住

## 截图

![image](https://user-images.githubusercontent.com/34802963/131464670-0b58988f-1582-4878-9e2e-08ab3be22b95.png)
![image](https://user-images.githubusercontent.com/34802963/131464721-e5922ec6-1449-4c33-ab0e-5dfc978ab947.png)
![录制_2021_08_31_15_55_37_824_2](https://user-images.githubusercontent.com/34802963/131466318-5fec8517-9a2c-413f-a4b5-9df16e85834e.gif)

**Comment by crimx** [comment]
可以在设置「查词面板」调整沙拉图标位置。
