### ISSUE TITLE
右键菜单添加：彩云小译，谷歌横幅翻译

### ISSUE THREAD

**Issue by stroop566** [crimx/ext-saladict#146]
希望右键菜单添加：[彩云小译](http://www.caiyunapp.com/)，[谷歌网页横幅翻译](https://www.cnblogs.com/toutou/p/4812466.html)（可以当前窗口打开），以及百度和搜狗的整页翻译可以考虑添加下：）

**Comment by crimx** [comment]
嗨，感谢建议！整合是属于逆向破解源码，十分费时费精力，日后维护还需要同步，所以如果已经有能用的且持续更新的接口，更建议结合 Saladict 一起使用。如彩云小译已有持续更新的 Chrome 扩展，谷歌翻译提供了网页翻译网址，就不再作整合了。

百度和搜狗网页翻译会以网页跳转的形式收入。

Regards.
