### ISSUE TITLE
[feature request] 给PDF阅读界面添加 Vimium C 快捷键支持

### ISSUE THREAD

**Issue by gdh1995** [crimx/ext-saladict#1462]
## 设备信息
- 操作系统: [任意] 
- 浏览器版本: [Chrome、Firefox、新版Edge] 
- 沙拉查词版本: [任意] 

## 请描述目前使用沙拉查词遇到什么不便

现在沙拉查词对PDF内查词的办法是用PDF.js在自己的网页里显示PDF内容，但这种扩展程序页面上不能运行其它扩展程序的内容脚本（content scripts）。我想给 PDF 界面单独添加“引入 Vimium C 内容脚本”的功能，请问开发者是否接受？

## 理想情况下，沙拉查词应该怎么做

通过往 Vimium C 发消息获得“引入内容脚本”的相关参数，然后添加`<script>`来运行 Vimium C 的脚本。

Vimium C 内容脚本已经针对“在第三方扩展页面上运行”而设计过了，一般都能正常跑。

## 替代方案

无。必须修改沙拉查词的代码才能引入其它扩展的脚本。

## 额外信息

我给 EdgeTranslate 做了类似的“往 PDF 页面引入 Vimium C”的功能（ https://github.com/EdgeTranslate/EdgeTranslate/pull/225 ），主要修改就是：1）多一个 JS 文件往 Vimium C 发消息；2）修改 `manifest.json` 来允许执行 Vimium C 脚本（Firefox下不需要）。添加的 JS 文件挺短的，可以参考 https://github.com/EdgeTranslate/EdgeTranslate/blob/master/static/pdf/vimium-c-injector.js

**Comment by crimx** [comment]
哇， 我也想要这样的功能，只是不知道有这样的方法！非常感谢！

**Comment by gdh1995** [comment]
那我试着写个pr？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月2日(周四) 下午5:48
收件人: ***@***.***&gt;;
抄送: "Dahan ***@***.******@***.***&gt;;
主题: Re: [crimx/ext-saladict] [feature request] 给PDF阅读界面添加 Vimium C 快捷键支持 (#1462)




 
哇， 我也想要这样的功能，只是不知道有这样的方法！非常感谢！
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SkyTu** [comment]
使用acorbat读paper的时候用不了沙拉查词，不知道是为什么。

**Comment by gdh1995** [comment]
@SkyTu 你是说acorbat那个软件？但沙拉查词不是用在浏览器里边的吗，你说的这个问题好像和沙拉查词关系不大？

另外和一楼的问题就更没关系了。这个问题已经解决但我忘了关了，我先关掉了。有问题的话你可以继续回复或者另外开新问题。

**Comment by SkyTu** [comment]
> @SkyTu 你是说acorbat那个软件？但沙拉查词不是用在浏览器里边的吗，你说的这个问题好像和沙拉查词关系不大？
> 
> 另外和一楼的问题就更没关系了。这个问题已经解决但我忘了关了，我先关掉了。有问题的话你可以继续回复或者另外开新问题。

就是acorbat可以在chrome里面用插件打开，就是好奇能不能使用所以就问一下

**Comment by gdh1995** [comment]
大概看了一下， https://chrome.google.com/webstore/detail/adobe-acrobat/efaidnbmnnnibpcajpcglclefindmkaj 这个扩展程序也自己做了套PDF阅读页面，而沙拉查词没法在它的扩展页面上工作，因为浏览器不允许。

像 Vimium C 想在沙拉查词上工作，就需要沙拉查词主动允许，Vimium C 配合，才能做到。Acrobat 这种扩展就别指望会主动允许别人了……

**Comment by SkyTu** [comment]
好的，谢谢你！软件做的非常棒！

**Comment by crimx** [comment]
目前只能通过[浏览器外划词](https://saladict.crimx.com/native.html)的方式在上面划词翻译。
