### ISSUE TITLE
The `ext-saladict` will defeat `zotero-connectors` for importing pdf file.

### ISSUE THREAD

**Issue by hongyi-zhao** [crimx/ext-saladict#1466]
On Ubuntu 20.04.2 LTS, I installed Firefox plugin [zotero-connectors](https://github.com/zotero/zotero-connectors) and ext-saladict. When I open [this file](https://courses.physics.ucsd.edu/2019/Fall/physics239/LECTURES/C02.pdf) in Firefox, and then click `zotero-connectors` to save the PDF into it, the following error will occur:

```
[JavaScript Error: "Method saveSnapshot failed
@moz-extension://e11bfd75-5870-4591-ac13-cbf785f7c9d4/connector.js:250:49
"]
```
Any hints for fixing this problem when using the above two plug-ins together?

Regards,
HY

**Comment by crimx** [comment]
> and then click zotero-connectors to save the PDF into it

What is the url in the address bar when clicking zotero-connectors?

**Comment by hongyi-zhao** [comment]
`moz-extension://b892d156-6061-4a1e-9300-36b4e92a4fb5/assets/pdf/web/viewer.html?file=https%3A%2F%2Fcourses.physics.ucsd.edu%2F2019%2FFall%2Fphysics239%2FLECTURES%2FC02.pdf`

**Comment by crimx** [comment]
This is a page in Saladict extension which zotero-connectors does not have access to. You'll have to turn off the Saladict "PDF sniffing" option and use browser default PDF viewer instead.

**Comment by hongyi-zhao** [comment]
![image](https://user-images.githubusercontent.com/11155854/132097186-96307d63-5e21-4336-ba4f-939ed01f668e.png)

- Still failed to save it into Zotero.
- PDF screen word-capturing translation will be disabled.

**Comment by crimx** [comment]
> Still failed to save it into Zotero.

Then it has nothing to do with Saladict.

> PDF screen word-capturing translation will be disabled.

This is expected.

**Comment by hongyi-zhao** [comment]
> > Still failed to save it into Zotero.
> 
> Then it has nothing to do with Saladict.

Sorry for my negligence, the PDF file really has been imported into Zotero successfully. 

> This is expected.

How to have the PDF screen word-capturing translation and Zotero PDF importing convenience simultaneously?
