### ISSUE TITLE
韦氏词典不正确

### ISSUE THREAD

**Issue by larrydragon123** [crimx/ext-saladict#1468]
## 词典名称以及链接
https://www.merriam-webster.com

## 沙拉查词的已有的词典为什么不能满足？

开发者你好，沙拉查词非常好用，但是上面提供的韦氏词典不是官方的韦氏词典，官方韦氏词典的链接是：https://www.merriam-webster.com
查词的时候有很多不准确的地方，可能导致使用者受到影响。

## 单词举例

如我在做GRE题目的时候Gradual这个单词，只有在韦氏词典中有imperceptible这个意思。但是用沙拉词典里面的韦氏查不到，导致做题错误。

## 截图

![image](https://user-images.githubusercontent.com/82367138/132097925-c0c7df1b-a3e2-4986-91e1-67316892cb2d.png)

![image](https://user-images.githubusercontent.com/82367138/132097983-5f90aabf-0e5e-40d2-8ece-dbd08beb64c2.png)

## 额外信息

必要性：GRE考试的所有题目的单词全部来自韦氏词典merriam-webster，如果韦氏字典不是官方的，可能导致做题错误和误解单词意思。请开发者给予重视，希望沙拉查词越来越好。

**Comment by crimx** [comment]
你好，韦氏学习词典与韦氏词典都是官方的词典。一般学习型词典释义用词会更简单一些。

因为沙拉查词英文词典已经非常多，韦氏词典还没有时间添加，但其它词典目前应该都是满足需求的。

> 如我在做GRE题目的时候Gradual这个单词，只有在韦氏词典中有imperceptible这个意思。但是用沙拉词典里面的查不到，导致做题错误。

不清楚题目是如何会因为这个导致错误？

**Comment by larrydragon123** [comment]
![image](https://user-images.githubusercontent.com/82367138/132121470-30d82927-6f40-49e1-8759-e1dcd736ed89.png)
![8531ceef5a73729fbbe44f14221bda5](https://user-images.githubusercontent.com/82367138/132121585-e2bf5e7e-f515-4cf7-b5e8-3068acebb32b.png)
你好，请看考试真题中的Gradual，只有在韦氏词典里面可以查到imperceptible这个程度词，别的只有happening or changing slowly over a long period of time or distance这种意思。虽然说可以去强行理解成不易察觉的，但是在gre考试中考生不允许做过度推断。如果单词本意没有这种意思，其他选项则会变成最优解。如果查词典是为了简单理解，别的词典都可以胜任，但是做这种题目需要高精确的解释。希望开发者再三斟酌，谢谢啦。

**Comment by alickxie** [comment]
赞同，GRE是按照韦氏词典出的，在其他的字典上查词有时不可避免地会会错意。添加最权威的词典之一对于沙拉查词也是一项升级。

**Comment by crimx** [comment]
好的，如果韦氏在这方面有特殊的不可替代性可以考虑加上去。

**Comment by AU-Linsanity** [comment]
> ![image](https://user-images.githubusercontent.com/82367138/132121470-30d82927-6f40-49e1-8759-e1dcd736ed89.png)
> ![8531ceef5a73729fbbe44f14221bda5](https://user-images.githubusercontent.com/82367138/132121585-e2bf5e7e-f515-4cf7-b5e8-3068acebb32b.png)
> 你好，请看考试真题中的Gradual，只有在韦氏词典里面可以查到imperceptible这个程度词，别的只有happening or changing slowly over a long period of time or distance这种意思。虽然说可以去强行理解成不易察觉的，但是在gre考试中考生不允许做过度推断。如果单词本意没有这种意思，其他选项则会变成最优解。如果查词典是为了简单理解，别的词典都可以胜任，但是做这种题目需要高精确的解释。希望开发者再三斟酌，谢谢啦。

gradual并不是等同于imperceptible，而是imperceptible描述的是这个渐变的过程。也就是imperceptible是对gradual这种渐变的修饰。我认为即使是没有imperceptible这个修饰这个题也是可以做出来的。因为changing slowly over a long period of time本身就难以察觉. 当然impercetible这种直接定义了更好。只是说这个题不是说只有用韦氏才能做得出来。
P.S. 加入好词典我是是支持的

**Comment by Longday0923** [comment]
顶一下，感觉韦氏相对来说是最准确、最学术的英英释义，建议添加，辛苦作者！

**Comment by AU-Linsanity** [comment]
> 顶一下，感觉韦氏相对来说是最准确、最学术的英英释义，建议添加，辛苦作者！

其实 韦氏 柯林斯 朗文 牛津高阶4 这四本都很不错，国内的英汉，陆古孙的大英汉也是相当出色的。
另外USE THE RIGHT WORD这本也很不错
![image](https://user-images.githubusercontent.com/62975691/132547120-1edbaaf7-577d-485c-9adc-d1fd096c2954.png)

**Comment by Longday0923** [comment]
确实，主要理由还是GRE考试中大量选项直接就是韦氏的解释照抄，详细描述见3、4楼。所以如果不麻烦的话，还希望作者早日添加到豪华套餐中啦。
