### ISSUE TITLE
是否能支持驼峰查词？

### ISSUE THREAD

**Issue by dream-jx** [crimx/ext-saladict#147]
程序员有时候用这个，但是很多单词类似驼峰的形式如, addProduct，那么该插件是否支持自动分解为2个单词来进行查词呢

**Comment by crimx** [comment]
你好，感谢建议！我认为这个支持是费力不讨好的。程序中的命名单词基本不会全是难词，完全可以单独滑词理解。如 #117 所述，我更倾向将精力放在**方便**同时能促使用户**进步**的功能上，而不是让用户更依赖这个扩展。

**Comment by crimx** [comment]
Closing. Thanks again for the input.
