### ISSUE TITLE
无法保存设置

### ISSUE THREAD

**Issue by ghost** [crimx/ext-saladict#1478]
## 设备信息
- 操作系统: [win10 1809ltsc] 
- 浏览器版本: [firefox91.1.0esr] 
- 沙拉查词版本: [v7.19.1] 

## 复现步骤

1. 打开插件设置
2. 点击 PDF 设置
3. 打开 嗅探 PDF 链接.
4. 问题出现

## 期待的正常行为
当然是，可以更改并保存这个设置项。

## 截图

[![hvbNXd.png](https://z3.ax1x.com/2021/09/11/hvbNXd.png)](https://imgtu.com/i/hvbNXd)

**Comment by crimx** [comment]
Duplicate of #1288
