### ISSUE TITLE
部分网页无法划词翻译

### ISSUE THREAD

**Issue by wuxingjie** [crimx/ext-saladict#148]
--划词网址:  https://leafletjs.com/reference-1.3.0.html#browser

- 平台：window7 chrome版本 67.0.3396.87（正式版本） （64 位）

- 类型：无法划词,可能是和其他库变量名冲突

- 划词模式？按住ctrl划词翻译,双击划词翻译

- 重现：按住ctrl划词,双击划词

![image](https://user-images.githubusercontent.com/11767887/41575511-581524f6-73b5-11e8-8968-9a0b792c893d.png)

**Comment by crimx** [comment]
你好，感谢反馈。这是因为这个网页定义了一个 browser 全局变量，导致 [webextension-polyfill](https://github.com/mozilla/webextension-polyfill) 误判没有加载。这个暂时没有好的方式处理，但毕竟这样的网页也不多。

**Comment by crimx** [comment]
已修复，下个版本两周内发布。

**Comment by crimx** [comment]
已发布
