### ISSUE TITLE
一些针对同 Vimium、Vimium C 兼容性的建议

### ISSUE THREAD

**Issue by gdh1995** [crimx/ext-saladict#1481]
## 设备信息
- 操作系统: [Windows 10] 
- 浏览器版本: [Edge 93] 
- 沙拉查词版本: [7.19.1] 

## 请描述目前使用沙拉查词遇到什么不便

目前在使用 [Vimium C](https://github.com/gdh1995/vimium-c) 键盘快捷键插件点击沙拉查词时，已找到两处小问题：
1. Wikipedia 词典的查询结果中，可折叠的小节标题（`.section-heading.collapsible-heading`）无法被默认识别为可点击元素 (https://github.com/gdh1995/vimium-c/issues/433)
2. 词典浮层隐藏后重新显示时，始终追加到当前`<html>`的末尾，这会遮挡 Vimium、Vimium C 的同 `z-index` 级别的 UI 元素

## 理想情况下，沙拉查词应该怎么做

1. 给 `<div class="section-heading">` 添加 `[role=button]`，比如在这儿：

https://github.com/crimx/ext-saladict/blob/1399e77b11a0a404709f473f5d6db65ac190112d/src/components/dictionaries/wikipedia/engine.ts#L105-L106

2. 沙拉查词面板显示在 Vimium、Vimium C 的界面元素 下方
  - 但是目前没有好办法来判断一个空 `<div>` 是不是 Vimium C 界面的根元素。我没想好能怎么做 

## 替代方案

对于问题2，是否可以让沙拉查词的根元素 `<div id=saladict-dictpanel-root>` 始终插入到 `<body>` 后边，而不是`<html>`末尾？

我也可以让 Vimium C 自动移动根元素，但这个也有代价：Vomnibar 会创建一个隐藏的iframe，如果移动根元素，iframe 会被销毁重建，下次触发命令显示 Vomnibar 的时候延迟会增加；另外 FindMode 也会创建 iframe，移动后 FindMode 会因为 iframe 销毁了而自动退出。所以“自动移动根元素”只在没在当前页面用过 Vomnibar 时代价较小。

**Comment by crimx** [comment]
感谢建议，我修改一下提高兼容性。

> 对于问题2，是否可以让沙拉查词的根元素 `<div id=saladict-dictpanel-root>` 始终插入到 `<body>` 后边，而不是 `<html>` 末尾？

这个不行，插入这里是有原因的。对于极简模式阅读类的扩展，它们往往也是这么插，然后把整个 body 隐藏掉；另外也为了兼容用了 frameset 的文档页面。所以为了兼容沙拉查词的面板也需要插在它们后面。

**Comment by gdh1995** [comment]
哦，我是说和body同级的后边, 就是兄弟元素的next



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月13日(周一) 中午12:39
收件人: ***@***.***&gt;;
抄送: "Dahan ***@***.******@***.***&gt;;
主题: Re: [crimx/ext-saladict] 一些针对同 Vimium、Vimium C 兼容性的建议 (#1481)




 
感谢建议，我修改一下提高兼容性。
  
对于问题2，是否可以让沙拉查词的根元素 <div id=saladict-dictpanel-root&gt; 始终插入到 <body&gt; 后边，而不是 <html&gt; 末尾？
  
这个不行，插入这里是有原因的。对于极简模式阅读类的扩展，它们往往也是这么插，然后把整个 body 隐藏掉；另外也为了兼容用了 frameset 的文档页面。所以为了兼容沙拉查词的面板也需要插在它们后面。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by crimx** [comment]
啊，明白了。但这个方案也是治标不治本的。沙拉查词面板这么做的原因也是要保证盖在其它阅读类扩展上方，插入 html 末尾是最保险的做法，不然还是也得做单个适配。

**Comment by gdh1995** [comment]
我有个新想法：在隐藏查词面板的时候，用 WeakRef 记下来当前的 nextSibling，下次插入的时候，如果它还是 html 的直接子节点、且在 body 之后，就插入到它前边。

**Comment by crimx** [comment]
> 我有个新想法：在隐藏查词面板的时候，用 WeakRef 记下来当前的 nextSibling，下次插入的时候，如果它还是 html 的直接子节点、且在 body 之后，就插入到它前边。

如果在打开查词面板的时候用户打开了极简模式类扩展，那么它的 nextSibling 就是这些扩展的元素了，所以还是无法保证在最后。

另外我测试了一下，即便 Vomnibar 的 div 在沙拉查词后面，还是会被挡住。

**Comment by gdh1995** [comment]
你测试的是 Vimium 吧？我的 Vimium C 统一了用 `z-index: 2147483647`，我试了一下只要是先显示查词面板、后触发 Vomnibar 就不会被挡住。

> 如果在打开查词面板的时候用户打开了极简模式类扩展

不过这时候查词面板大概就已经被挡住了…… 确实这时候用户还能取消+重新唤出查词面板来避开遮挡。我去改 Vimium C 吧。

**Comment by crimx** [comment]
> 你测试的是 Vimium 吧

我测试的是 Vimium C，但是忘了关闭 Vimium 。确实是可以了。

> 不过这时候查词面板大概就已经被挡住了

这是合理的，因为用户唤出了新界面，旧的已经没有意义。下次在这个界面上选词时就需要显示在它上面了。
