### ISSUE TITLE
缴费仍不可用

### ISSUE THREAD

**Issue by Bella-I** [crimx/ext-saladict#1485]
在网页划词翻译总是用着用着就不能用了，网页翻译更是达到一定的次数就不能再用，需要充值12元成为会员方可继续，结果充值成功后也不能使用，建议沙拉方尽快核实一下问题，如果确定无法使用或无法解决，请把钱款退还给我！！！！

**Comment by crimx** [comment]
你好，请按模板反馈问题以便排查。我看这里有两个问题：

> 在网页划词翻译总是用着用着就不能用了

请问是如何不能用？是词典没有结果还是划词没有显示面板？是所有页面还是某个页面出现这个问题？方便的话最好可以提供出现问题的页面以便复现问题。

> 结果充值成功后也不能使用

沙拉查词里面用的是彩云小译的官方接口，与小译本身是一样的，沙拉查词没有动过里面的代码。如果出现网页翻译不能使用请看看网页翻译右下方是否有已经登录了的头像。同时在 https://fanyi.caiyunapp.com/#/mine/vip 看看有没有记录。如果没有邮件我帐号我帮你去问一下。

**Comment by Bella-I** [comment]
![1632378789(1)](https://user-images.githubusercontent.com/81574908/134463578-66d271b9-fa26-461e-b321-98d023b004f9.jpg)
就像这样，所有页面都如此，刚打开可以用，用几次之后就不能用了

**Comment by crimx** [comment]
这两个词典机器翻译最近不稳定，你可以在设置-「词典管理」中添加彩云小译和有道翻译试试。

**Comment by eryisan** [comment]
你说的是彩云小译，那就去彩云小译官网或者下载Chrome插件-彩云小译反馈问题，沙拉查词 不等于 彩云小译。就像北京  不等于 上海。你充值给的是彩云小译，而不是沙拉查词。

**Comment by crimx** [comment]
v7.20.0 已经修复了谷歌翻译和有道词典的问题，请等待应用商店过审。
