### ISSUE TITLE
独立查词窗口出现后，网页划词就不能用了

### ISSUE THREAD

**Issue by tachikomachann** [crimx/ext-saladict#1493]
在Win10 Edge浏览器下，独立窗口出现后，在网页上划词，不会出现沙拉图标。
把独立窗口关闭后，功能恢复正常。
![image](https://user-images.githubusercontent.com/51024737/134130099-b63a5b7c-f0b3-4490-90a1-f85496190c9f.png)
![image](https://user-images.githubusercontent.com/51024737/134130107-5eb27079-43df-40c8-92ea-9c1e38ca8786.png)
Edge浏览器版本： 93.0.961.52 (官方内部版本) (64 位)
沙拉查词版本：v7.19.1

**Comment by crimx** [comment]
沙拉查词设置-「快捷查词」-「打开独立窗口设置」-「响应划词」-关闭。

**Comment by tachikomachann** [comment]
> 沙拉查词设置-「快捷查词」-「打开独立窗口设置」-「响应划词」-关闭。

多谢，问题解决了。
