### ISSUE TITLE
文本截图写入剪贴板失败

### ISSUE THREAD

**Issue by origamiwhite** [crimx/ext-saladict#1494]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome93] 
- 沙拉查词版本: [v7.19.1] 

## 描述问题

使用quicker利沙拉查词文本截图写入剪贴板失败。

## 复现步骤

1. 打开quicker
2. 右键沙拉查词
3. 左键文本截图
4. 随意选取任意文本
5. 出现如图提示
![image](https://user-images.githubusercontent.com/47637215/134176018-ca12591e-20ed-4cea-a95e-da779131a173.png)

## 期待的正常行为

正常识别文本并翻译。

## 截图

![image](https://user-images.githubusercontent.com/47637215/134176092-e21cf031-a868-4ae1-8757-509b951bcd52.png)

**Comment by eryisan** [comment]
沙拉查词--Quicker沙拉查词--Quicker，这是三个软件。
至于你的问题：使用quicker沙拉查词文本截图写入剪贴板失败。
更应该去Quicker沙拉查词处反馈：https://getquicker.net/sharedaction?code=b0d1a134-8284-4a44-d1be-08d746da5869

麻烦仔细审题

**Comment by crimx** [comment]
感谢回复。
