### ISSUE TITLE
导出本页单词预览异常

### ISSUE THREAD

**Issue by hotWater-me** [crimx/ext-saladict#1496]
## 设备信息
- 操作系统: [Mac OS] 
- 浏览器版本: [Chrome/94.0.4606.54] 
- 沙拉查词版本: [v7.19.1] 

## 描述问题

![image](https://user-images.githubusercontent.com/56283392/134300469-73d2f4f5-b8a4-4afd-a777-164724ce777b.png)

## 额外信息

path: src/components/WordPage/_style.scss;
textarea {
   resize: none;
   background: transparent;
 };
textarea设置的背景色为透明，font也没有设置颜色。

**Comment by crimx** [comment]
感谢反馈，这是升级 antd 之后的 bug，会在下个版本修复。
