### ISSUE TITLE
某些网页第一次进入无法划词，刷新后可以划词

### ISSUE THREAD

**Issue by Kazfyx** [crimx/ext-saladict#150]
- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）

Ubuntu16.04  Chrome 67.0.3396.99

- 类型：错误？建议？

某些网站新打开的网页不生效，必须刷新一次才能划词。

- 划词模式？以及其它觉得相关的设置。

所有划词模式

- 重现：提供详细的可重现问题的操作。

进入网址 http://gazebosim.org/tutorials  再点击任意链接，比如 Categorized 下面的 Installation，此时无法划词，再刷新网页一次，又可以划词了。

- 期待：理想情况下扩展应该怎么做？

在任何时候可以划词

- 实际：客观描述扩展实际上做了什么。

某些网页第一次进入无法划词，刷新后可以划词

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
已发布
