### ISSUE TITLE
希望增加小牛翻译引擎

### ISSUE THREAD

**Issue by Recke-9528** [crimx/ext-saladict#1509]
我觉得小牛翻译的英译中质量较好，且小牛翻译目前支持自建术语库和翻译记忆，所以能否增加小牛翻译引擎，并通过登陆个人账号实现使用自己的术语库和翻译记忆的功能呢，对于平时看文献的我来说太想要这个功能了，谢谢作者！

## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: []

**Comment by crimx** [comment]
Duplicate of #624
