### ISSUE TITLE
右上角的扩展图标按钮加个快捷键吧，随机查词的速度就可以大大提高了

### ISSUE THREAD

**Issue by mo-han** [crimx/ext-saladict#151]
- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）
FireFox 61.0

- 类型：错误？建议？
建议

**Comment by crimx** [comment]
你好，Saladict 支持快捷键的，“激活该扩展程序” 即为地址栏旁的图标，设置请阅读 wiki <https://github.com/crimx/ext-saladict/wiki>

**Comment by drcege** [comment]
我今天用了快捷键设置了鼠标划词翻译开关，但是用起来有些不友好。

按了快捷键之后不知道自己现在是处于激活还是暂停的状态，必须得划词试一下才行…… 

右上角的图标能不能变换一下状态，比如暂停的时候变成灰色，或者是加个小标记，只要能跟正常激活模式区分开就好~

**Comment by crimx** [comment]
谢谢，这是很好的建议，会加上去。
