### ISSUE TITLE
似乎还没有修复naver韩语词典的bug，大大需要帮忙吗？另外想添加西语词典可以吗？

### ISSUE THREAD

**Issue by wekey7** [crimx/ext-saladict#1518]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome94.0.4606.81]
- 沙拉查词版本: [v7.19.1] 

## 描述问题
似乎现在还没有修复naver韩语词典bug，作者大大需要帮忙吗？我随时可以帮忙测试反馈bug。
另外想问一下可以抓一下西语词典吗？[http://www.esdict.cn/]

## 截图

![QQ图片20211013213011](https://user-images.githubusercontent.com/34415026/137142842-68e6152a-3b06-43c4-9938-fd28f8a143ea.png)
![2](https://user-images.githubusercontent.com/34415026/137142855-f8cb52f8-265f-4d13-9ea3-c9f9cb61fb28.png)

**Comment by wekey7** [comment]
https://github.com/crimx/ext-saladict/issues/1151

**Comment by wekey7** [comment]
https://github.com/crimx/ext-saladict/issues/308
如果有需要可以像之前那样帮助大大！！

**Comment by crimx** [comment]
感谢！ #1483 已经修复啦，我还需要处理一下剩下的 issues 再发版。

**Comment by wekey7** [comment]
> 感谢！ #1483 已经修复啦，我还需要处理一下剩下的 issues 再发版。

原来如此 那太好了！
另外想问问大大还有精力扩展下西语词典吗！我可以帮忙的！
http://www.esdict.cn/ 中西词典
https://www.spanishdict.com/ 英西词典

**Comment by crimx** [comment]
感谢！这个后面我看看。

**Comment by wekey7** [comment]
> 感谢！这个后面我看看。

可以随时召唤我！ 哈哈哈哈
