### ISSUE TITLE
无法在edge浏览器打开的pdf中划词翻译

### ISSUE THREAD

**Issue by zchuz** [crimx/ext-saladict#1519]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 复现步骤
Edge浏览器，打开pdf时无法加载沙拉查词拓展，导致无法在网页pdf中划词翻译。

## 期待的正常行为

edge浏览器打开pdf文件，加载沙拉查词拓展，可以在pdf中划词

**Comment by crimx** [comment]
- [PDF 划词](https://saladict.crimx.com/manual.html#pdf)
- [浏览器外划词](https://saladict.crimx.com/native.html)
