### ISSUE TITLE
ipadOS 15 增加Safari 浏览器拓展

### ISSUE THREAD

**Issue by yegetables** [crimx/ext-saladict#1526]
ipadOS15.02 已经推送稳定版, appstore 已经增加 safari拓展商店, 希望可以看到 沙拉查词 拓展的 上架

**Comment by crimx** [comment]
谢谢你的告知！很抱歉我基本不会考虑上架啦。目前导出了开发版可以桌面 [Safari](https://saladict.crimx.com/safari) 上使用。有其他人愿意将沙拉查词弄上架也非常欢迎。

**Comment by yegetables** [comment]
哦,那真是 太遗憾了
