### ISSUE TITLE
牛津高阶词典无法完整显示动词短语的查询结果

### ISSUE THREAD

**Issue by funnybones2015** [crimx/ext-saladict#1528]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Microsoft Edge 94] 
- 沙拉查词版本: [7.20.0] 

## 描述问题

牛津高阶词典查询动词短语比如check out，查询结果只有该短语，不显示解释和例句

## 复现步骤

打开独立查词窗口，查询 check out

## 期待的正常行为

正常情况下应该呈现该短语的查询结果，比如官网的查询结果如下：

![image](https://user-images.githubusercontent.com/15063728/138198391-c11f22de-439b-44d4-8d15-9e0c25263c0f.png)

## 截图

而在沙拉词典中查询，不显示完整的结果
![image](https://user-images.githubusercontent.com/15063728/138198068-f43a7d29-5aff-472b-8a3e-885bad4021bd.png)

**Comment by crimx** [comment]
@yipanhuasheng 看一下？
