### ISSUE TITLE
“新增 新增韦氏词典、美国传统词典、牛津学习词典与欧路生词同步”，请问如何与欧路生词同步？有教程吗？

### ISSUE THREAD

**Issue by WrathGluttony** [crimx/ext-saladict#1530]
## 设备信息
- 操作系统: Window10 21H1
- 浏览器版本: 版本 94.0.4606.81（正式版本） （64 位）
- 沙拉查词版本: v7.20.0

v7.20.0新增与欧路生词同步，请问这个功能(下面引号里的功能)有教程吗？能具体说说吗？
“新增
新增韦氏词典、美国传统词典、牛津学习词典与欧路生词同步（感谢 @yipanhuasheng 贡献）。
Added Merriam Webster’s Dict, American Heritage Dict, Oxford Learner’s Dict and Eudic Notebook sync service (Thanks to @yipanhuasheng).”
## 请描述目前使用沙拉查词遇到什么不便

新增的功能没有教程，能在教程里添加吗？

## 理想情况下，沙拉查词应该怎么做

新增的功能最好有个教程

**Comment by yipanhuasheng** [comment]
![image](https://user-images.githubusercontent.com/18358639/138265761-37994709-b929-4270-9585-e12a3b9c02df.png)
![image](https://user-images.githubusercontent.com/18358639/138266027-a496f82f-927b-44e9-b844-0060ba3b0909.png)
如图，需要先在欧路的网站创建默认生词本（初次手动导入会自动创建并且不可删除），然后将个人的授权信息填入。点击“开启”，然后“确定”就可以了。之后的单词会自动同步到欧路的默认单词本，然后你再自行更改单词分组。

**Comment by WrathGluttony** [comment]
①“韦氏词典、美国传统词典、牛津学习词典与欧路生词同步”意思是：韦氏词典里的“生词”、美国传统词典里的“生词”、牛津学习词典里的“生词”与欧路生词同步？
②是前面3个词典的“生词”与欧路的“生词”同步？是“生词”之间的同步？
③原来其它词典的“生词”是可以与欧路“生词”同步的，这次又新增这3个词典的"生词"同步(韦氏词典、美国传统词典、牛津学习词典)？

**Comment by yipanhuasheng** [comment]
是的，生词同步和词典没有强关联。韦氏词典、美国传统词典、牛津学习词典就是单纯新增的词典，查词用。欧路生词同步就是新增了一个同步单词的平台。

**Comment by crimx** [comment]
“韦氏词典、美国传统词典、牛津学习词典与欧路生词同步” 是说加了四个功能😂

**Comment by WrathGluttony** [comment]
@yipanhuasheng @crimx 
①我终于明白什么意思了，是新增了4个功能：前3个是新增3个词典，第4个功能是沙拉查词又新增了1个把沙拉查词里所有词典的生词同步到欧路词典的功能。
②我一开始理解错了，我以为是新增了1个功能，就是前3个词典的生词同步到欧路生词里
③谢谢二位大神
