### ISSUE TITLE
关于韩语naver词典的bug反馈与建议！ 【带图】

### ISSUE THREAD

**Issue by wekey7** [crimx/ext-saladict#1532]
操作系统: [Win10]
浏览器版本: [Chrome94.0.4606.81]
沙拉查词版本: [v7.19.1]

## 描述问题
BUG出现是在【中韩】词典的情况下 某些词会出现<strong>这个命令 
![bug1](https://user-images.githubusercontent.com/34415026/138457425-68f4bf25-6846-4f66-951c-4df27ee93a38.png)
![bug2](https://user-images.githubusercontent.com/34415026/138457429-cbeb0ec0-ebcf-45a0-9555-a98e1cdcfdce.png)

作为对比同样词条【日韩】词典是没有的
![无1](https://user-images.githubusercontent.com/34415026/138456296-5036e0ad-641c-4a4a-b950-583bfe12b20e.png)
![无2](https://user-images.githubusercontent.com/34415026/138456302-9f15d24e-7c73-4d71-b081-231a1434affb.png)

——————————
另外想提个建议 大大可以作为功能参考 没有也没有关系 因为这样已经很方便了！

建议 希望提供【中韩】【日韩】词典的韩语词汉字表记
韩语有70%左右的词汇是汉字词 
有些词和汉字意思一样文字一样 比如这一堆的수도 有没有汉字表记都没有关系
![提议2](https://user-images.githubusercontent.com/34415026/138456604-1c4b1e9b-f2f4-4eb9-9ffb-03be1bc9e283.png)

但也有些词语汉字意思不一样 “比如거래汉字写作【去来】 意思是交易”
如果有汉字标识会更好记住这个单词
![提议1](https://user-images.githubusercontent.com/34415026/138457479-db2527a5-2857-4d6e-8901-a7dda1252fab.png)

期待出现的情况 汉字标识在韩文旁
![建议2](https://user-images.githubusercontent.com/34415026/138457475-ac56c2df-92dc-4525-9d56-a2477bac43e6.png)

如果有帮助请大大随时呼唤我~

**Comment by wekey7** [comment]
@crimx 大大在吗~

**Comment by crimx** [comment]
感谢反馈！ @yipanhuasheng 有空修复这个么？

**Comment by yipanhuasheng** [comment]
好的，周末一块搞下
