### ISSUE TITLE
pdf阅读器无法打开本地pdf

### ISSUE THREAD

**Issue by Bardielz** [crimx/ext-saladict#1540]
## 设备信息
- 操作系统: [ubuntu 20.04] 
- 浏览器版本: [95.0.4638.54] 
- 沙拉查词版本: [v7.20.0] 

## 描述问题

使用沙拉查词打开本地pdf时无法打开推测是文件名解析错误

## 截图

![image](https://user-images.githubusercontent.com/33973388/139210880-c1f69929-146b-4e8e-a224-190b9a88ac33.png)

**Comment by crimx** [comment]
是否勾选了[允许插件访问本地文件](https://saladict.crimx.com/manual.html#pdf)？

**Comment by Bardielz** [comment]
确实是这个问题。。。。。

**Comment by chptx** [comment]
用Edge+沙拉打开本地pdf成功后，重启浏览器，从历史记录里面打开刚刚的pdf失败。
