### ISSUE TITLE
请求添加百度词典中的牛津词典

### ISSUE THREAD

**Issue by woodwm** [crimx/ext-saladict#1542]
## 词典名称以及链接

牛津词典, Oxford English-Chinese Dictionary

https://fanyi.baidu.com/#en/zh/

## 沙拉查词的已有的词典为什么不能满足？

包含有更多中英双语例句及发音

## 截图

下图为查询单词 desert, https://fanyi.baidu.com/#en/zh/desert

![image](https://user-images.githubusercontent.com/13971199/139455390-09d0707e-8b53-441a-a90c-09b17695d9d5.png)

## 额外信息

默认牛津词典没有附带单词的翻译，部分单词有“同义词辨析”，我不太确定这部分是不是也来自《牛津词典》

**Comment by crimx** [comment]
你好，谢谢建议！百度翻译的牛津词典应该独有版权，故不考虑实现。

**Comment by woodwm** [comment]
如果完整地展示百度翻译页面上的所有词典内容能不能规避版权问题，类似浏览器，不做过多的编辑。这样跟展示其他词典是一样的逻辑。
