### ISSUE TITLE
请天假DeepL翻译引擎

### ISSUE THREAD

**Issue by MangoBank** [crimx/ext-saladict#1543]
## 设备信息
- 操作系统: <MacOS 12>
- 浏览器版本: <Chrome 93>
- 沙拉查词版本: <v7.2.0>

## 请描述目前使用沙拉查词遇到什么不便

希望能够添加DeepL翻译引擎。

## 理想情况下，沙拉查词应该怎么做

可以添加DeepL翻译引擎的选项。翻译API可由用户自己申请免费版填写。

**Comment by crimx** [comment]
Duplicate of #705
