### ISSUE TITLE
MacOS 12.0.1无法读取剪切板内容,权限都开了,谷歌浏览器最新版本.

### ISSUE THREAD

**Issue by jiayouzl** [crimx/ext-saladict#1550]
MacOS 12.0.1无法读取剪切板内容,权限都开了,谷歌浏览器最新版本.

插件,浏览器都是最新版本,浏览器的权限也打开的.

**Comment by crimx** [comment]
"无法读取剪切板内容" 具体是指什么情况？出现什么报错还是什么功能不正常？

**Comment by jiayouzl** [comment]
> “无法读取剪切板内容”具体是指什么情况？出现什么报错还是什么功能不正常？

没有任何报错提示,就是我在别的程序上复制一段文本,在Windows上是可以在这个插件里读取到剪切板内容并自动翻译的,在MACOS里不行,在插件设置里都设置权限也提示也都允许的.

**Comment by crimx** [comment]
"在Windows上是可以在这个插件里读取到剪切板内容并自动翻译的" 这个流程具体是如何的？是[配合了 quicker 实现浏览器外自动翻译](https://saladict.crimx.com/native.html)，还是在[沙拉查词设置](https://saladict.crimx.com/manual.html#open-setting)「快捷查词」或「右上弹框」中配置了「预先加载：剪贴板」以及开启了「自动查词」。

**Comment by jiayouzl** [comment]
> "在Windows上是可以在这个插件里读取到剪切板内容并自动翻译的" 这个流程具体是如何的？是[配合了 quicker 实现浏览器外自动翻译](https://saladict.crimx.com/native.html)，还是在[沙拉查词设置](https://saladict.crimx.com/manual.html#open-setting)「快捷查词」或「右上弹框」中配置了「预先加载：剪贴板」以及开启了「自动查词」。

我在Windows平台用你们这个插件好几年了,设置方面都对的,其他功能也都正常,唯独点击浏览器你们的插件图标读取剪切板内容没效果(权限同意了),不知道怎么解析了都,我感觉我说的挺清楚了,我找找其他平替的软件吧.

假设环境,我在系统记事本复制一段文本,这个文本内容是"china"然后我打开浏览器点击你们插件图标,它会自动读取到剪切板内容,并翻译成china=中国,就是这个功能失效,设置都正常,权限也允许.说的真的非常详细了.

**Comment by crimx** [comment]
> 我在系统记事本复制一段文本,这个文本内容是"china"然后我打开浏览器点击你们插件图标,它会自动读取到剪切板内容,并翻译成china=中国,就是这个功能失效

这个功能属于[沙拉查词设置](https://saladict.crimx.com/manual.html#open-setting)「右上弹框」中配置「预先加载：剪贴板」以及开启「自动查词」。

- 可以检查以上两个设置是否开启。
- 检查[沙拉查词设置](https://saladict.crimx.com/manual.html#open-setting)「权限管理」中「读取剪贴板」权限是否开启。如已开启，可以点击关闭再点击开启重新激活浏览器的授权。
