### ISSUE TITLE
希望能设置背景色和字体颜色（而不是仅限于默认和黑暗模式两种）

### ISSUE THREAD

**Issue by future-zhang** [crimx/ext-saladict#1551]
## 颜色配置的局限性
目前只有默认（白底黑字）和黑暗模式（黑底白字）两种颜色配置可供选择，对于使用其他颜色配置（比如绿色、灰色等护眼模式）的用户仍然不够友好。

对此，希望能增加背景色和字体颜色的设置，方便用户自定义和自身相匹配的颜色方案。

**Comment by crimx** [comment]
[沙拉查词设置](https://saladict.crimx.com/manual.html#open-setting)「查词面板」中支持自定义面板 CSS 样式，也欢迎[分享主题](https://github.com/crimx/ext-saladict/discussions/categories/theme-%E4%B8%BB%E9%A2%98)。

**Comment by future-zhang** [comment]
原来查词面板里面可以设置，之前没发现，不好意思。
我刚刚也分享了一个报纸色主题，个人感觉对眼睛比较友好😃
https://github.com/crimx/ext-saladict/discussions/1554
