### ISSUE TITLE
无法保存设置，QuotaExceededError: storage.sync API call exceeded its quota limitations.

### ISSUE THREAD

**Issue by zhufengning** [crimx/ext-saladict#1555]
## 设备信息
- 操作系统: Linux（我猜Windows也会）
- 浏览器版本: Firefox 94.0.1
- 沙拉查词版本: 7.20.0

## 描述问题
设置保存失败
`QuotaExceededError: storage.sync API call exceeded its quota limitations.`

## 复现步骤
修改任意设置后保存

**Comment by ifkn271** [comment]
- 操作系统: Windows10 
 - 浏览器版本: Firefox 94.0.1
 - 沙拉查词版本: 7.20.0

复现

**Comment by crimx** [comment]
Duplicate of #1288
