### ISSUE TITLE
希望增加双语对照翻译

### ISSUE THREAD

**Issue by YesHub** [crimx/ext-saladict#1564]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 请描述目前使用沙拉查词遇到什么不便

没有双语对照翻译功能。

## 理想情况下，沙拉查词应该怎么做

希望增加双语对照翻译，就像彩云小译那样。

## 替代方案

以行为单位，对照。

**Comment by Eyion** [comment]
这个功能实现了吗？怎么设置？需要付费吗？

**Comment by crimx** [comment]
这个功能直接使用彩云小译即可，他们的浏览器扩展做得挺好了，没必要重复造轮子。

**Comment by Eyion** [comment]
彩云小译这个功能需要付费。某网友实现此功能的代码，总共几行，可惜没有封装成插件；还有一种方法是核心代码保存成书签形式，但好像只能遍历p元素，不能覆盖所有文本。以上两种方法应该都没有运营成本的产生。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "crimx/ext-saladict"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月31日(星期天) 上午8:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [crimx/ext-saladict] 希望增加双语对照翻译 (Issue #1564)





 
这个功能直接使用彩云小译即可，他们的浏览器扩展做得挺好了，没必要重复造轮子。
