### ISSUE TITLE
edge最新版本划词会遮挡图标

### ISSUE THREAD

**Issue by nadirvishun** [crimx/ext-saladict#1566]
## 设备信息
- 操作系统: [win0] 
- 浏览器版本: [Edge 96.0.1054.34 (官方内部版本) (64 位)] 
- 沙拉查词版本: [7.20.0] 

## 描述问题
刚更新edge版本后，划词选择，edge会出现自带的标志遮挡了沙拉的标识，导致无法点击翻译。

## 复现步骤
随便点开网页，划词翻译

## 期待的正常行为
展示不被覆盖的图标

## 截图
![image](https://user-images.githubusercontent.com/5761981/143198309-dcb13aba-68ab-4094-afb0-55f420b9adc0.png)

## 额外信息
无

**Comment by nadirvishun** [comment]
大体搜了下，貌似edge有个`迷你菜单`的新功能导致的遮挡，可以在设置中关闭。但如果想同时用这个功能和沙拉词典就会产生冲突。

**Comment by crimx** [comment]
可在[设置](https://saladict.crimx.com/manual.html)「查词面板」设置沙拉图标出现的位置，或者配置其它划词模式。

**Comment by nadirvishun** [comment]
好的，谢谢，已解决。
