### ISSUE TITLE
edge96版微型菜单与沙拉查词冲突

### ISSUE THREAD

**Issue by PaulHerrero** [crimx/ext-saladict#1570]
## 设备信息
- 操作系统: [win11] 
- 浏览器版本: [edge96] 
- 沙拉查词版本: [7.2] 

## 描述问题

与edge96版的微型菜单冲突，选中文本后会沙拉图标会被微型菜单遮挡

## 复现步骤

1. 开启edge设置里的微型菜单
2. 打开网站 https://www.zhihu.com/question/462844792/answer/2237842571
3. 选中标题的前两个字
4. 问题出现

## 期待的正常行为

edge的微型菜单不会遮挡沙拉图标

**Comment by crimx** [comment]
Duplicate of #1566
