### ISSUE TITLE
microsoft edge打开本地pdf时无法划词

### ISSUE THREAD

**Issue by DachuanZhao** [crimx/ext-saladict#1574]
## 设备信息
- 操作系统: [win11] 
- 浏览器版本: [microsoft edge 96.0.1054.34]
- 沙拉查词版本: [v7.20.0]

## 描述问题
edge打开本地pdf时，无法划词

## 复现步骤
1. 打开本地pdf
2. 无法划词

## 期待的正常行为
可以划词

**Comment by crimx** [comment]
见[安装说明](https://saladict.crimx.com/notice.html)。

**Comment by DachuanZhao** [comment]
> 见[安装说明](https://saladict.crimx.com/notice.html)。

已解决，需要在拓展设置页面打开：“允许访问文件 URL”
