### ISSUE TITLE
请问目前能否翻译本地的HTML游戏?

### ISSUE THREAD

**Issue by Misakacat1** [crimx/ext-saladict#1580]
## 设备信息
- 操作系统: Windows10
- 浏览器版本: Chrome96.0.4664.45
- 沙拉查词版本: v7.20.0

## 请描述目前使用沙拉查词遇到什么不便
在普通网页浏览时运行正常，但是在打开本地HTML游戏时候无法正常翻译，无论是划词还是鼠标悬浮都不会出现翻译框

## 理想情况下，沙拉查词应该怎么做
我觉得可能是已经有办法解决该功能了但是我找不到....能麻烦告知一下吗

## 替代方案
无
## 额外信息
无

**Comment by crimx** [comment]
见[初次使用说明](https://saladict.crimx.com/notice.html)。打开允许访问文件地址。

**Comment by Misakacat1** [comment]
> 见[初次使用说明](https://saladict.crimx.com/notice.html)。打开允许访问文件地址。
谢谢！！成功了
