### ISSUE TITLE
翻译标识与菜单位置冲突问题

### ISSUE THREAD

**Issue by ProjektMing** [crimx/ext-saladict#1581]
## 设备信息
- 操作系统: [Window10]
- 浏览器版本: [Edge96]
- 沙拉查词版本: [v7.20.0]

## 请描述目前使用沙拉查词遇到什么不便

edge扩展栏刚好阻挡了划词图标

## 理想情况下，沙拉查词应该怎么做

将图标移到光标左边（也许）

**Comment by crimx** [comment]
Duplicate of #1566
