### ISSUE TITLE
safari 没地方下载啊

### ISSUE THREAD

**Issue by TLovers** [crimx/ext-saladict#1591]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: []

**Comment by crimx** [comment]
https://saladict.crimx.com/safari

**Comment by shinglove** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by TLovers** [comment]
> https://saladict.crimx.com/safari

em~~感谢回复！
之前我一直在这个页面转圈圈，我找到safari网盘下载的地址，并进行下载，下来的.crx 格式貌似好像Safari打不开
然后我一直卡在第一步 下载并安装app  这个app 是指？

**Comment by crimx** [comment]
不好意思，城通把一些文件隐藏了，先通过[这里](https://saladict.crimx.com/download.html#%E4%B8%8B%E8%BD%BD)的「网盘」下载 「Saladict_for_Safari_v7.20.0.zip」
