### ISSUE TITLE
内置的韦氏词典查不到omicron这个词，但韦氏词典官网上能查到

### ISSUE THREAD

**Issue by funnybones2015** [crimx/ext-saladict#1595]
## 设备信息
- 操作系统: [win 11] 
- 浏览器版本: [Edge 96] 
- 沙拉查词版本: [7.20.0] 

## 描述问题

内置的韦氏词典查不到omicron这个词，但韦氏词典官网上能查到

**Comment by funnybones2015** [comment]
没有回应吗？希望作者关注下这个问题，排查一下看看是哪里出问题了。

**Comment by crimx** [comment]
@yipanhuasheng 点击词典标题打开原页面是有的，应该是解析有问题？

**Comment by yipanhuasheng** [comment]
好的，我研究下

**Comment by funnybones2015** [comment]
这个bug是已经修复了吗？我看目前没有什么变化呢
