### ISSUE TITLE
Google Translate 翻译结果与网页版 Google Translate 不一致

### ISSUE THREAD

**Issue by liyuhang1997** [crimx/ext-saladict#1598]
## 设备信息
- 操作系统: [Windows 11] 
- 浏览器版本: [Chrome 96] 
- 沙拉查词版本: [7.20.0] 

## 描述问题

原文：Bing China has been required by the relevant government agency to suspend the search auto suggestion feature in mainland China for 30 days under PRC laws. Bing is a global search platform and remains committed to respect the rule of law and users’ right to access information and to help users find information to the greatest extent feasible under applicable laws.

沙拉查词提供的译文：有关政府机构的冰川已被要求暂停中国大陆的搜索汽车建议特色30天在中国法律下。Bing是全球搜索平台，仍然致力于尊重法治和用户访问信息的权利，并帮助用户在适用法律下可行的最大程度的信息。

Google Translate 网页端提供的译文：根据中国法律，Bing China 已被相关政府机构要求在中国大陆暂停搜索自动建议功能 30 天。 Bing 是一个全球搜索平台，并始终致力于尊重法治和用户获取信息的权利，并在适用法律允许的最大范围内帮助用户查找信息。

## 复现步骤

打开 [https://cn.bing.com/cnlegal](https://cn.bing.com/cnlegal)，翻译对应原文。
打开 [Google Translate](https://translate.google.com/)，翻译对应原文

## 期待的正常行为

如题

**Comment by crimx** [comment]
Duplicate of #1559
