### ISSUE TITLE
EDGE无法导入CHROME导出的配置

### ISSUE THREAD

**Issue by sixrui** [crimx/ext-saladict#1599]
## 设备信息
- 操作系统: [Win7] 
- 浏览器版本: [Chrome 96.0.4664.110，EDGE：版本 96.0.1054.62] 
- 沙拉查词版本: [V7.20] 

## 描述问题

Chrome导出配置
EDGE导入提示备份解析失败，格式不正确

## 期待的正常行为

EDGE可以导入CHROME导出的配置

**Comment by crimx** [comment]
有填写词典账号或者生词同步帐号等敏感信息么？没有可以把导出文件拖进评论框上传过来看一下。

**Comment by sixrui** [comment]
[config-1640046468344.zip](https://github.com/crimx/ext-saladict/files/7748711/config-1640046468344.zip)

**Comment by sixrui** [comment]
> 有填写词典账号或者生词同步帐号等敏感信息么？没有可以把导出文件拖进评论框上传过来看一下。

在上面

**Comment by crimx** [comment]
我在 Edge 中可以导入成功的。注意是里面的 .saladict 文件，不是 .zip 压缩包。

**Comment by sixrui** [comment]
不知道怎么回事突然又好了，上传ZIP是因为评github不支持备份文件的格式做附件，谢谢你
