### ISSUE TITLE
沙拉查词中的谷歌翻译和网页中的谷歌翻译的英译汉结果不一样

### ISSUE THREAD

**Issue by Concise360** [crimx/ext-saladict#1607]
-->

## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [360极速浏览器13.5] 
- 沙拉查词版本: [v7.20.0] 

## 描述问题
沙拉查词中的谷歌翻译和网页中的谷歌翻译的英译汉结果不一样，沙拉查词中的谷歌翻译文不对头，而网页中的谷歌翻译较准确

## 复现步骤
选择一段英文，打开沙拉查词独立翻译窗口，下滑指'谷歌翻译"

## 期待的正常行为
希望管理员可以将沙拉查词中的谷歌翻译结果和网页的谷歌翻译一样准确

## 截图
![tmpB588](https://user-images.githubusercontent.com/97098803/148054179-162bbf4d-41ca-46cc-8e87-4146668d4c90.png)

![tmpE5E0](https://user-images.githubusercontent.com/97098803/148054209-9c4bc9f8-6e0e-4642-bfde-0e3c3a230051.png)

**Comment by crimx** [comment]
Duplicate of #1559
