### ISSUE TITLE
[建议]钉住查词默认启用

### ISSUE THREAD

**Issue by wangbinyq** [crimx/ext-saladict#161]
钉住查词默认启用.
可以有两种方式, 一种所有页面一直钉住, 另一种只在第一次查词后钉住查词.

**Comment by crimx** [comment]
嗨，能描述一下使用场景么。没有理解这样的用法。

**Comment by wangbinyq** [comment]
比方说浏览的网站上面生词比较多的
不希望每次刷新都点一下钉住

**Comment by crimx** [comment]
频繁刷新？这样的场景我认为不是很多，点击钉住已经是很方便的操作。为此额外添加一个选项，会增加设置的复杂度（目前已经接近繁杂了）。

**Comment by wangbinyq** [comment]
ok

**Comment by crimx** [comment]
谢谢理解。

**Comment by Xtephen1231** [comment]
设置一个默认启用的选项真的很重要。。。

**Comment by crimx** [comment]
@Xtephen1231 现在可以用独立窗口代替了。
