### ISSUE TITLE
Safari 版插件无法访问 anki connect

### ISSUE THREAD

**Issue by JoneWang** [crimx/ext-saladict#1611]
## 设备信息
- 操作系统: [macOS 12.1] 
- 浏览器版本: [Safari Version 15.2 (17612.3.6.1.6)] 
- 沙拉查词版本: [v7.20.0] 

## 描述问题

无法连接 Anki Connect

## 复现步骤

沙拉查词设置页面 -> 单词管理 -> Anki Connect
点击 ___检查 Anki Connect___ 提示 ___无法连接 Anki Connect，请确认 Anki 已在运行。___

## 期待的正常行为

正常连接

## 额外信息

在 Safari 的开发工具，查看请求信息，在点击 ___检查 Anki Connect___ 后，请求中可以看到 http://127.0.0.1:8765 的请求结果是 403。（猜测可能是由于插件无权限访问 http://127.0.0.1:8765 导致）
如果手动打开 http://127.0.0.1:8765 则能正常显示 Anki Connect。
Chrome 版本插件可以正常连接。

**Comment by crimx** [comment]
感觉你的猜测是对的，Safari 有允许插件访问所有网站么？

**Comment by JoneWang** [comment]
> 感觉你的猜测是对的，Safari 有允许插件访问所有网站么？

有的，在所有网页中可以正常查词。

**Comment by crimx** [comment]
那可能是 Safari 不允许了。

**Comment by JoneWang** [comment]
> 那可能是 Safari 不允许了。

经查证，是 Anki Connect 对请求的 Headers 中的 Origin 进行了判断，仅允许了 Chrome 和 Firefox 浏览器的插件进行访问。
已经向 Anki Connect 提交 PR 修复此问题（[Allow safari-web-extension to access Aniki Connect.  #297](https://github.com/FooSoft/anki-connect/pull/297)），等待 Anki Connect 合并发布即可结束此 issue 。

**Comment by JoneWang** [comment]
Anki Connect 已合并。
