### ISSUE TITLE
在查词面板中三击ctrl，会导致光标跳转到输入框，如何禁用它？

### ISSUE THREAD

**Issue by g495326** [crimx/ext-saladict#162]
- 平台：win7_64，chrome63

- 类型：快捷键

- 重现：在查词面板中三击ctrl即可

- 期待：提供在查词面板中禁用三击ctrl快捷键的选项

- 实际：仅是统一设置，实际没有提供附加选项。

- （可选）额外信息：
![2018-07-14_120758](https://user-images.githubusercontent.com/41222130/42720705-f9c4559e-875e-11e8-8c29-f8330568805c.png) 
焦点处于该查词面板中，三击后变成如下
![2018-07-14_120824](https://user-images.githubusercontent.com/41222130/42720706-fe698394-875e-11e8-9c56-e727fa6743af.png)

**Comment by crimx** [comment]
你好，请问为什么不希望查词被选中呢？

如果不希望三按 ctrl 弹出查词，关闭“快捷查词”选项即可。

**Comment by g495326** [comment]
关闭的原因：和一个autohotkey脚本冲突，当前还无法解决。

「快捷查词」选项我已注意到，但经过测试发现该「选项」的作用仅在查词面板没有出现的情况，通过三击ctrl来弹出界面，「快捷查词」选项已关闭，如下图，但在查词面板已出现的情况（且处于活动状态）「三击ctrl」仍然会被跳转到输入框。
![2018-07-14_122845](https://user-images.githubusercontent.com/41222130/42720883-7d9d5480-8762-11e8-8290-8b6d98f1e931.png)

**Comment by crimx** [comment]
好的，感谢反馈，会在下个版本修正这个问题。

**Comment by crimx** [comment]
修复版本已发布。
