### ISSUE TITLE
Bug: 无效或损坏的PDF文件

### ISSUE THREAD

**Issue by xuestrange** [crimx/ext-saladict#1624]
## 设备信息
- 操作系统: Manjaro 21.2.1 Qonos
- 浏览器版本: Chrome 97.0.4692.99
- 沙拉查词版本: v7.20.0

## 描述问题
首先我在插件的Options里设置了允许访问文件URL， 然后在沙拉查词的内部设置里设置了嗅探PDF，同时设置了点击图标为打开PDF,然而当我在www.scholar.google.com上搜搜文献，然后打开文献右侧的PDF链接时，沙拉查词应该是自动接管了PDF的打开，然而显示无效或损坏的PDF文件。

另外，对于scihub搜索到的PDF,点击沙拉查词图标，也会显示无效或损坏的PDF文件，如果这不是一个bug，那就当成feature requests吧。感谢开发者的付出，希望软件越做越好。

## 复现步骤
对于第一个问题
1. 打开 <https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=clickstream+data+purchase+intention&oq=>
2. 右侧的PDF链接随便点击一个， 例如点击第一个
 ![操作演示](https://raw.githubusercontent.com/xuestrange/picGoUploader/main/img/Peek%202022-01-22%2023-12.gif)
3. 可以看出，沙拉词典确实接管了PDF,但是失败了

对于第二个问题
1. 对于scihub找到的一篇文献<https://sci-hub.yncjkj.com/10.1080/02642060903026254>
2. 点击沙拉词典图标，显示文件损坏， 在PDF上右击也没有效果
![操作演示](https://raw.githubusercontent.com/xuestrange/picGoUploader/main/img/Peek%202022-01-22%2023-18.gif)

## 期待的正常行为

正常情况下， 沙拉查词应该会自动接管PDF,打开PDF, bug在于接管了，但是却不能成功打开文件

## 额外信息
我感觉，之前好像正常工作过，但是现在是不行的，说明这个功能还不稳定，在我的另外一台电脑（manjaro）上也有这个问题。

**Comment by xuestrange** [comment]
更新：

第一个问题，在谷歌学术网站上， 时好时坏，多点几次貌似可以打开，可能与网络有关

**Comment by crimx** [comment]
有的网站防止盗链会对声明为 PDF 类型的链接却返回 html 页面，所以会导致错误拦截。沙拉查词的 PDF 设置支持黑名单，需要把相关域名加入黑名单。

你先关了沙拉查词的 PDF 拦截，然后直接下载 PDF，在浏览器下载页面看看这个 PDF 的地址是多少？

**Comment by xuestrange** [comment]
> 有的网站防止盗链会对声明为 PDF 类型的链接却返回 html 页面，所以会导致错误拦截。沙拉查词的 PDF 设置支持黑名单，需要把相关域名加入黑名单。
> 
> 你先关了沙拉查词的 PDF 拦截，然后直接下载 PDF，在浏览器下载页面看看这个 PDF 的地址是多少？

懂了，那第二个问题，能否支持为scihub网站嗅探pdf， 即专门为scihub优化下。我看了下，scihub网页的源代码里包含了PDF文件的真实地址，但是我不是程序员，也不懂前端这些语言，请问能否作为一个feature request

**Comment by xuestrange** [comment]
> > 有的网站防止盗链会对声明为 PDF 类型的链接却返回 html 页面，所以会导致错误拦截。沙拉查词的 PDF 设置支持黑名单，需要把相关域名加入黑名单。
> > 你先关了沙拉查词的 PDF 拦截，然后直接下载 PDF，在浏览器下载页面看看这个 PDF 的地址是多少？
> 
> 懂了，那第二个问题，能否支持为scihub网站嗅探pdf， 即专门为scihub优化下。我看了下，scihub网页的源代码里包含了PDF文件的真实地址，但是我不是程序员，也不懂前端这些语言，请问能否作为一个feature request

我临时学习，写了个js脚本，在scihub上显示真实的PDF链接地址，点击即可用沙拉查词打开
``` javascript
// ==UserScript==
// @name         showScihubPdfLink
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        *://sci-hub*
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @grant        none
// ==/UserScript==

(function() {
    //'use strict';

    // Your code here...
    var ids = document.getElementsByTagName("embed");
    var pdfsrc= ids.pdf.src;
    var header = document.getElementById("header");
    // header.removeAttribute("onclick")
    header.setAttribute("onclick", "location.href='"+pdfsrc+"'");
    document.getElementById("motto").innerHTML = "点击使用沙拉词典打开";
    motto.style.color="red";
    motto.style.fontSize="20px";
})();
```
