### ISSUE TITLE
希望加入图片搜索作为词典

### ISSUE THREAD

**Issue by yymyyy** [crimx/ext-saladict#163]
使用了沙拉查词，非常惊喜。
首先，自己做的一些本地html，不能查词。作者说是chrome限制，自行克服了。

- 平台：windows10 Chrome67
- 类型：建议
- 期待：加入图片搜索
- 实际：在英语学习中，遇到新单词搜索一下图片，会很直观地加深印象。比如单词abandon，用google搜索图片，可以看到很多图片，一只狗狗看着主人远去、一只哭泣的狐狸、一个荒岛等。经过实践，对理解单词、记住单词是有益的。可否加入这样的词典供选择？（可以直接使用google等搜索引擎的图片搜索，如果技术上可行的话）

**Comment by crimx** [comment]
你好，本地网页是可以查词的，见第一次安装时弹出的说明 <https://github.com/crimx/ext-saladict/wiki/Instructions> 。

图片这个之前也有人提过（#22），然而准确性是个难题。搜索引擎的结果太泛，如果有其它专门做单词图片的平台欢迎推荐。在无法保证准确性的情况下，自行搜索是更好的解决方式。

**Comment by yymyyy** [comment]
收到，谢谢回复
