### ISSUE TITLE
无法打开edge栏

### ISSUE THREAD

**Issue by og1oc** [crimx/ext-saladict#1636]
## 设备信息
- 操作系统: [win10] 
- 浏览器版本: [edge98] 
- 沙拉查词版本: [7.20.0] 

## 描述问题

无法打开edge栏

## 复现步骤

设置--edge栏 选项无法选中,并提示该设置由扩展管理

**Comment by C1oudust** [comment]
是的，确实和edge的某些功能冲突了
![image](https://user-images.githubusercontent.com/29059054/154916723-496cde0e-abb3-4a08-830b-e471eab9b42a.png)
![image](https://user-images.githubusercontent.com/29059054/154916728-467ac71a-f448-42c0-a334-ac9e4ecbb0ce.png)

**Comment by crimx** [comment]
这个好像是 Edge 的 bug，虽然警告了但还是能正常启用。看看是不是开启了沙拉查词的「后台保持运行」导致的？

<img width="483" alt="image" src="https://user-images.githubusercontent.com/6882794/154953010-3bd58863-b715-4264-98e1-57a5dd09c489.png">

**Comment by crimx** [comment]
Duplicate of #1614
