### ISSUE TITLE
，

### ISSUE THREAD

**Issue by vouss123** [crimx/ext-saladict#1637]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: []

**Comment by suibianzai** [comment]
既然知道打扰了 你就应该把具体信息都详尽地附上 尽可能免去开发者的麻烦 人家是免费提供的 没有义务帮你全部查出来
说实话很多bug都没修复 我真担心你们这种伸手要饭的人会消磨开发者的热情
