### ISSUE TITLE
6.5.1版本,Google翻译不能用??翻译不了??

### ISSUE THREAD

**Issue by lzpong** [crimx/ext-saladict#164]
6.5.1版本,,,google翻译翻译不了
![tim 20180716093101](https://user-images.githubusercontent.com/10493371/42740508-2063ec0a-88db-11e8-9978-1c004199b740.jpg)

**Comment by crimx** [comment]
你好，谷歌翻译 .com 和 .cn 都正常解析的，如果在墙内的话你有没有开启了“优先使用 cn”

**Comment by lzpong** [comment]
请看图片, https://translate.google.cn 网页使用翻译是正常的, 但是在这个页面上  插件就不能google翻译,  其他任意网页google也不能翻译

"优先使用cn" ? 没注意有这个选项呢...

**Comment by crimx** [comment]
在谷歌词典的选项中

**Comment by lzpong** [comment]
没海词,好不习惯, 其他功能 貌似没使用到, 换回用5版本最后一个啦 O(∩_∩)O

**Comment by crimx** [comment]
好的，感谢反馈！有其它问题欢迎开新 issue。
