### ISSUE TITLE
插件与edge栏配置文件冲突导致无法同时启用插件和Edge栏

### ISSUE THREAD

**Issue by KilianShen** [crimx/ext-saladict#1641]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Edge  98.0.1108.43] 
- 沙拉查词版本: [7.20.0] 

## 描述问题

插件与edge栏配置文件冲突导致无法同时启用插件和Edge栏

## 复现步骤

启用沙拉翻译插件，在浏览器设置-->Edge栏中显示不可开启该功能

## 期待的正常行为

可同时启用沙拉翻译插件和Edge栏

## 截图

![image](https://user-images.githubusercontent.com/86402559/153135323-e0dd401b-c640-40c8-a55f-4f4d0dc2236e.png)

## 额外信息

无

**Comment by itheabyss** [comment]
我也是这样，不知要怎么解决

**Comment by crimx** [comment]
Duplicate of #1614
