### ISSUE TITLE
独立查词窗口自动翻译粘贴版或划词取词内容，没有开关，影响日常操作

### ISSUE THREAD

**Issue by yufanme** [crimx/ext-saladict#1644]
## 设备信息
- 操作系统: [mac os 13.3 + win10] 
- 浏览器版本: [mac-edge-Version 97.0.1072.69 ] 
- 沙拉查词版本: [v7.20.0] 

## 描述问题

按三次mac电脑上的commond键，出现独立查词窗口，
![image](https://user-images.githubusercontent.com/37041186/154055664-39df970a-3f6e-4ae2-a6ea-95f15b18fc9b.png)
我将此窗口放在副屏上，随时准备查单词。
问题在于，我发现他默认翻译粘贴版上的词汇和划词的词汇，而且无法设置“在独立查词窗口关闭自动翻译粘：贴版词汇和划词词汇”的功能。
所以，我经常划词想删除词汇时，发现删除的是独立查词窗口的词汇。
经常划线后，想打字，发现打得字出现在独立查词窗口，就很不方便。
如果关闭独立查词窗口，mac上打开窗口很麻烦，因为独立窗口最开始是最大化出现在单独屏幕，我必须先缩小，再拖到副屏。

## 期待的正常行为

为独立查词窗口开发单独的粘贴版或划词取词开关。
比如目前我只需要连续三次commond键出现独立查词窗口的功能（已实现）。

## 截图

![image](https://user-images.githubusercontent.com/37041186/154058636-cf2dd95a-a7f9-4c1d-9894-570c728500c0.png)

![image](https://user-images.githubusercontent.com/37041186/154058607-33e7ea1a-9c0e-4172-937e-4b98b7346b31.png)

**Comment by crimx** [comment]
在「快捷查词」里设置。

**Comment by yufanme** [comment]
> 在「快捷查词」里设置。

thx, it works for me.
