### ISSUE TITLE
建议为“红心”增加快捷键+红心不能取消收藏。

### ISSUE THREAD

**Issue by yufanme** [crimx/ext-saladict#1645]
## 设备信息
- 操作系统: [mac os 13.3] 
- 浏览器版本: [Version 98.0.1108.51 (Official build) (x86_64) ] 
- 沙拉查词版本: [v7.20.0] 

## 请描述目前使用沙拉查词遇到什么不便

1.平时查词和收藏单词较多，所以独立查词面板一直在副屏，按三个commond直接输入单词就能查词，很方便，但是收藏单词需要移动鼠标到红心，再点击红心，很麻烦。
2.红心收藏单词后，再点击红心仍然是红色，说明不能取消收藏，希望改进，

## 理想情况下，沙拉查词应该怎么做

建议：
1.设立收藏当前查词单词的快捷键，就不用移动鼠标了。
2.第一次点击收藏，第二次点击取消收藏。

**Comment by crimx** [comment]
[打开浏览器快捷键设置](https://saladict.crimx.com/manual.html#shortcuts)配置沙拉查词的生词本快捷键。

**Comment by yufanme** [comment]
> [打开浏览器快捷键设置](https://saladict.crimx.com/manual.html#shortcuts)配置沙拉查词的生词本快捷键。
牛蛙 原来早就有了，缺一个使用文档，不然找不到呢
