### ISSUE TITLE
建议增加在查词面板中，按下ctrl+鼠标划词自动翻译

### ISSUE THREAD

**Issue by g495326** [crimx/ext-saladict#165]
- 平台：win7 chrome63

- 类型：建议

- 期待：在面板中，ctrl+鼠标划词来自动查词

- 实际：当前仅有，在面板中ctrl+双击自动查词

- （可选）额外信息：
![2018-07-16_103159](https://user-images.githubusercontent.com/41222130/42741334-ce648c8a-88e3-11e8-9d61-8fb2e2b32546.png)

**Comment by crimx** [comment]
感谢建议，这个会考虑加进去

**Comment by crimx** [comment]
修复版本已发布。原有选项已移到下方的“面板查词”中。
