### ISSUE TITLE
有道翻译显示不全

### ISSUE THREAD

**Issue by T-Mofeng** [crimx/ext-saladict#1655]
## 设备信息
- 操作系统: [win11] 
- 浏览器版本: [Chrome98.0.4758.102] 
- 沙拉查词版本: [7.20.0] 

## 描述问题

pdf阅读器中，有道翻译我觉得不错，但是最近出现翻译不完全的现象，框选一段只能翻译开头几个词，其他翻译都好的，但我更喜欢有道

## 复现步骤

pdf阅读器打开任何文件，框选翻译都会出现

## 期待的正常行为

有完整的有道翻译呀。

**Comment by zhaisilong** [comment]
我在 ubuntu 上也遇到了同样的情况

**Comment by crimx** [comment]
Duplicate of #1648
