### ISSUE TITLE
沙拉查词无法识别上下文

### ISSUE THREAD

**Issue by Xinyue-Wong** [crimx/ext-saladict#1659]
## 设备信息
- 操作系统: [Win10]
- 浏览器版本: [Chrome98.0.4758.102（正式版本） （64 位）] 
- 沙拉查词版本: [v7.20.0] 

## 描述问题

当划词翻译、查询单词并加入单词收藏时，沙拉查词无法识别上下文，因此句子/语境也无法同步到Anki中。这种情况不论是在浏览器内，还是在浏览器外（如阅读pdf）时都会出现。一直无法解决。我换了很多pdf阅读器，都一直有这个问题。
**ps**: Anki已后台开启，chrome已后台开启，使用的是quicker。

## 复现步骤

1. 使用chrome浏览器打开任意pdf
2. 选中某个单词（划词）
3. quicker触发划词翻译动作，打开沙拉查词
4. 点击沙拉查词右上角的红心，收藏单词，salad word editor窗口出现
5. 问题出现，“上下文”一栏是空白的。Anki中也无法显示该单词的上下文

## 期待的正常行为

按照沙拉查词的说明，在划词翻译、将单词加入收藏时，应该自动识别上下文才对？

## 截图

![捕获](https://user-images.githubusercontent.com/81224394/155938738-d21041b1-1d27-493e-99b8-47536bcb75ee.JPG)

## 额外信息

暂无

**Comment by crimx** [comment]
通过 Quicker 方式是属于「浏览器外」的方式获取划词，即便这个文字是在浏览器中，它现在走了是另一个方式（剪贴板）获取划词，所以拿不到上下文了。目前还没有方式在浏览器外获取上下文。
