### ISSUE TITLE
划词后点击右键会弹出查词界面，而我仅想复制选择的内容。feature ? can it disabled : will it fixed 

### ISSUE THREAD

**Issue by g495326** [crimx/ext-saladict#166]
- 平台：win7，chrome63&67

- 类型：Feature Or Bug？

- 划词模式？以及其它觉得相关的设置。
![2018-07-17_055701](https://user-images.githubusercontent.com/41222130/42785831-6d502870-8986-11e8-8eb3-70a8e74aad8c.png)

- 重现：提供详细的可重现问题的操作。
![bug](https://user-images.githubusercontent.com/41222130/42785857-83686e60-8986-11e8-89c0-644641ec4737.gif)

- 期待：理想情况下扩展应该怎么做？
由于不知道是bug或者是feature，但我更倾向于bug，因为查词界面会被浏览器的右键界面挡住，不管怎么样，希望能提供关闭的选项。

- 实际：设置中没看到有提及。

**Comment by crimx** [comment]
感谢反馈，这个直接划词确实会比较 annoying，右键划词是一个解决方式，下个版本会优化这个问题。目前可先关闭直接划词，或者设置快捷键开启关闭划词。

**Comment by g495326** [comment]
右键划词，会不会和鼠标手势冲突？
我实际想要的效果是，左键选择文本（进行图标提示，指向图标可以查看释义），而在点击右键时不自动弹窗查词即可。

**Comment by crimx** [comment]
嗯，是的，这个交互有点复杂，我看看如何处理

**Comment by g495326** [comment]
经过测试，发现是「双击搜索」的逻辑判断问题，当前的逻辑好像是无论鼠标的哪个键（左左，左右，右右，右左）按下，只要两键间隔时间小于450ms，即会触发弹窗查词
![issua1](https://user-images.githubusercontent.com/41222130/42799719-77985c36-89cb-11e8-8102-1cbe4614813a.png)

个人建议：仅在左键双击（即上面提到的左左）时，才触发查词，即可以避免该问题。

**Comment by crimx** [comment]
好的感谢建议

**Comment by crimx** [comment]
修复版本已发布。

**Comment by maiyuyu** [comment]
在检测到 非翻译界面 的点击时，翻译界面关闭。

**Comment by maiyuyu** [comment]
关闭以前的功能会导致 选词(单个词或多个词)翻译 更难使用。
只能通过右键菜单或者插件图标实现。

**Comment by crimx** [comment]
@maiyuyu 

- 什么情况下会出现通过查词面板外点击右键来关闭？
- 后面的没看明白，能再说明一下什么意思么。
  - 什么查词模式下什么操作会使得更加难用？
  - 双击单词也存在复制的意图？跟什么模式冲突了？

**Comment by crimx** [comment]
> 不然就可能会影响到不可预知的、类似楼主的操作

这时面板已经存在，不会出现什么意外的结果。

> 复制一段话自动翻译，就无法实现了

在什么查词模式下不能进行这个操作？

> 当你想复制一个单词的时候，最快的方式就是双击、右键复制。

所以？默认模式下对这个没有影响吧？开启双击查词模式是用户自行选择的。

> 我没觉得楼主的反馈是bug

我也没有呢，所以这贴才修复了。

> 这个产品逻辑没错(可以提供关闭划词翻译的功能)

一直有这个功能，还可以设置快捷键。

> 当然如果是双击的判定出了问题，应该算是bug。

是的，所以这贴才发布了修复。

所以综上 @maiyuyu 还是不太明白你描述的问题？你期望在什么查词模式下进行什么样的改变？
