### ISSUE TITLE
建议添加DeepL Translator

### ISSUE THREAD

**Issue by iblh** [crimx/ext-saladict#1667]
## 设备信息
- 操作系统: [Window 10]  
- 浏览器版本: [Chrome 98]  
- 沙拉查词版本: [v7.20.0]  

## 请描述目前使用沙拉查词遇到什么不便

建议添加DeepL Translator作为词典
https://www.deepl.com/pro-api?cta=header-pro-api

## 理想情况下，沙拉查词应该怎么做

可使用DeepL Translator作为词典

## 额外信息

主页: https://www.deepl.com/translator
API文档: https://www.deepl.com/pro-api?cta=header-pro-api

**Comment by crimx** [comment]
Duplicate of #705

**Comment by ysj-ch** [comment]
同意，其他字典翻译的实在是差强人意
