### ISSUE TITLE
手动安装crx，导致不能自动更新，在不丢失查词记录和单词本的情况下能否转到chrome store版本？

### ISSUE THREAD

**Issue by g495326** [crimx/ext-saladict#167]
1、插件的是以前不能访问chrome store的时候安装的，但每次更新都要手动操作。

2、如果删除后，重新使用chrome store上的版本，不知「单词本」和「查词记录」会保存吗？

3、如果不能保存，是否有别的方式在不丢失「单词本」和「查词记录」的情况下，转到chrome store版本，以实现自动更新扩展？

**Comment by crimx** [comment]
如果能连上 Chrome Store 无论如何方式安装都会自动更新的。

如果不能，有可能扩展被第三方打包过，这情况下重新安装会丢失所有信息。

如果是本平台发布的版本：

- v5 到 v6 版升级会丢失单词，不会丢失设置。
- v6 之后的都不会。

无论如何，最好的方式是将单词本和设置导出来。

**Comment by g495326** [comment]
crx扩展是在你github发布页上下载的，我可以访问chrome store。
版本是6.5.1，即便我手动进入该网址“https://chrome.google.com/webstore/detail/%E6%B2%99%E6%8B%89%E6%9F%A5%E8%AF%8D-%E5%A4%9A%E8%AF%8D%E5%85%B8%E4%B8%93%E4%B8%9A%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91/cdonnmffkdaoajfknoeeecmchibpmkmg”，仅提示「已添加至chrome」，如图：
![2018-07-19_170345](https://user-images.githubusercontent.com/41222130/42932888-0f3094c2-8b76-11e8-8e2e-b5721ce42eb5.png)

我在单词本页面，仅看到有导出的按钮，而没有导入的按钮（如下图），即便我从chrome store重新安装，可能仍然无法导入。
![2018-07-19_171200](https://user-images.githubusercontent.com/41222130/42933268-faf85534-8b76-11e8-8c6b-28a67a170c68.png)


对了，还有一个问题，即扩展的更新机制，如果chrome store上的扩展更新后，是chrome进行推送，还是扩展定时向chrome store查询？

**Comment by crimx** [comment]
那就可以了，Chrome 会在适当时机自动下载，一般在关闭打开浏览器后更新。
