### ISSUE TITLE
添加生词本仅导出英语的功能

### ISSUE THREAD

**Issue by jie-neng** [crimx/ext-saladict#1673]
## 设备信息
- 操作系统: [windows11] 
- 浏览器版本: [edge99] 
- 沙拉查词版本: [v7.20.0] 

#生词本导出功能，会把英语和中文翻译全部导出# 请描述目前使用沙拉查词遇到什么不便

#生词本导出时，添加一个按钮，会只把英语单词全部导出，其他全部不要。单词之间换行# 理想情况下，沙拉查词应该怎么做

**Comment by crimx** [comment]
导出模板只保留 `%text%` 就是导出单词，再加个换行就是一行一个单词。

**Comment by jie-neng** [comment]
> 导出模板只保留 `%text%` 就是导出单词，再加个换行就是一行一个单词。

噢噢噢，开始没懂那里啥意思。大多数时候，默认发音在设置里打开了，划词的时候，却没有发音是什么原因啊？
