### ISSUE TITLE
搜索一段文字，只有三个词典选项，但是搜索几个单词，就可以跳出所有的词典

### ISSUE THREAD

**Issue by Ageral-Bao** [crimx/ext-saladict#1674]
![image](https://user-images.githubusercontent.com/101039108/156915150-db9de1b7-6e96-4f5a-9b3e-636c54f387a2.png)
但是选择单词数量少的时候，就没有问题。
![image](https://user-images.githubusercontent.com/101039108/156915164-09f39ccd-e73e-4a7e-8d1a-91a6525d91ff.png)

## 设备信息
- 操作系统: [] Window 11
- 浏览器版本: []  Chrome. 98.0.4758.102
- 沙拉查词版本: [] v7.20.0

## 复现步骤

搜索一段文字，只有三个词典选项，但是搜索几个单词，就可以跳出所有的词典

**Comment by crimx** [comment]
这是沙拉查词的默认配置，词典网站只能查单词，查句子没有结果的。你也可以自行去[设置](https://saladict.crimx.com/manual.html)「词典设置」中调整显示条件。
