### ISSUE TITLE
无法正常使用有道翻译的长句翻译

### ISSUE THREAD

**Issue by Abibabodudu** [crimx/ext-saladict#1677]
## 设备信息
- 操作系统: Win11
- 浏览器版本: Chrome97.0.4692.71 
- 沙拉查词版本: v7.20.0

## 描述问题

有道词典长句翻译无法正常弹出

## 复现步骤

直接选中文字翻译

## 期待的正常行为

如同截图的谷歌翻译一样有长句翻译

## 截图

![image](https://user-images.githubusercontent.com/90749771/157058605-efb2b7d1-6aca-47d6-b0b6-df62b6b1e001.png)

**Comment by crimx** [comment]
Duplicate of #1648
