### ISSUE TITLE
三按ctrl快速查词的逻辑判断问题，以及希望支持快速查词自定义快捷键功能

### ISSUE THREAD

**Issue by g495326** [crimx/ext-saladict#168]
- 平台：win7 chrome63

- 类型：快捷键逻辑

- 划词模式：不相关

- 重现：对于「ctrl+c，ctrl，ctrl」如图
![bug 3](https://user-images.githubusercontent.com/41222130/42933556-a44d0684-8b77-11e8-9166-b6937c5bfdef.gif)

- 期待：对于组合键能有效的忽略（比如「ctrl+c，ctrl，ctrl」应该只算2次ctrl击键，而非三次）。

- 希望：个人认为三击ctrl有点太麻烦了，更倾向于「ctrl+固定键」模式，而且有效避开多次击键的判断复杂度，当然这种方式可能和别的快捷键冲突，所以希望支持快速查词自定义快捷键功能。

- 实际：通过测试，三按ctrl，仅检测ctrl的击键次数击键的间隔，而没有忽略其中的组合键，即ctrl+c，ctrl，ctrl也是可以弹出查词面板。而这种情况应该不弹出查词面板才对。

**Comment by crimx** [comment]
该 bug 将在下小版本修复

FYI ，如果不知道如何自定义快捷键可参考 https://github.com/crimx/ext-saladict/wiki#shortcuts
