### ISSUE TITLE
有道翻译无论选中多少只翻译半句

### ISSUE THREAD

**Issue by Felix9190** [crimx/ext-saladict#1682]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome97.0.4692.71] 
- 沙拉查词版本: [v7.20.0] 

## 描述问题

沙拉查词的有道翻译的结果出现异常，只翻译半句话。

## 复现步骤

1.打开quicker
2.点击文本/截图翻译的复制翻译方式
3.复制一段话
4.沙拉查词的有道翻译的翻译结果无论复制多少只翻译半句话。

## 期待的正常行为

有道翻译的翻译结果回归正常

## 截图

![image](https://user-images.githubusercontent.com/33978674/157409544-4fffc23f-7920-442d-a153-c76fec3ae7a4.png)

**Comment by crimx** [comment]
Duplicate of #1648
