### ISSUE TITLE
希望增加一个文本预处理功能

### ISSUE THREAD

**Issue by akhzz905** [crimx/ext-saladict#1685]
## 设备信息
- 操作系统: [Windows 11] 
- 浏览器版本: [Firefox 98.0.1] 
- 沙拉查词版本: [7.20.0] 

## 请描述目前使用沙拉查词遇到什么不便

有些网页选择的单词不是用空格分隔的，他是用换行符分隔的。具体是灯塔阅读（www.deltareading.com），他们网页不允许选择，我是用插件选择的。
![图片](https://user-images.githubusercontent.com/52377847/158405419-025c8a2e-5f3e-48be-868f-29a2d8e90561.png)

## 理想情况下，沙拉查词应该怎么做

希望能加一个预处理选项，把换行替换成空格。

**Comment by crimx** [comment]
你好，感谢反馈。这个网站费这么大心思来降低文本的真实语义，我觉得没必要额外兼容了😂

**Comment by z0ow** [comment]
啥网站啊，给我整的感兴趣了，链接po出来看看

**Comment by akhzz905** [comment]
> 啥网站啊，给我整的感兴趣了，链接po出来看看

www.deltareading.com，可能是他们网站做了单词翻译功能导致的
