### ISSUE TITLE
建议添加不对input[text]进行查词

### ISSUE THREAD

**Issue by zhuxiaoxi** [crimx/ext-saladict#169]
- 平台：Manjaro Linux/Google Chrome 67.0.3396.99
- 类型：错误
- 划词模式：无论是双击选词还是滑动选词，在处理input的时候应该禁用
- 重现：搜索引擎的输入框，想选中已经输入的次删除时总弹出翻译菜单。
- 期待：我认为扩展应该在选中单词内容后判断，单词是不是用户在表单的输入框中，如果是输入框中的单词不需要弹出搜索。
- 实际：当我选中搜索框中的英文时，翻译功能正常生效，翻译了选中的词。此时沙拉翻译的窗口弹出，内部的输入框获取了焦点，导致本应该对网页上输入框的操作无法正常实行。

**Comment by crimx** [comment]
你好，设置中有“关闭可编辑区域划词”，勾选即可

**Comment by zhuxiaoxi** [comment]
麻烦了，没太理解这个选项的意思

**Comment by crimx** [comment]
这个名字当时确实取拗口了哈哈。主要为了凸显一些不是简单输入框的地方也支持，这个貌似对用户来说也没什么区别。
