### ISSUE TITLE
与「Edge 栏」功能冲突

### ISSUE THREAD

**Issue by BobYue-01** [crimx/ext-saladict#1693]
## 设备信息
- 操作系统: [Windows 11]
- 浏览器版本: [Edge 版本 99.0.1150.39 (正式版本) (64 位)]
- 沙拉查词版本: [v7.20.0]

## 描述问题

与「Edge 栏」功能冲突：

> 此设置由一个或多个已安装的扩展管理。

经排查，是由「沙拉查词」引起。

## 复现步骤

1. 打开 Edge 设置
2. 打开「Edge 栏」选项卡
3. 提示「此设置由一个或多个已安装的扩展管理」
4. 禁用「沙拉查词」后，「Edge 栏」恢复正常使用

## 期待的正常行为

「沙拉查词」与「Edge 栏」兼容并存。

**Comment by xc2f** [comment]
![Snipaste_2022-03-23_10-11-27](https://user-images.githubusercontent.com/11835233/159610315-e1b2823b-ef87-4d60-9d2a-552a4d5be55c.png)

**Comment by crimx** [comment]
Duplicate of #1614
