### ISSUE TITLE
在 codepen 中唤起瞬间出现层叠错误

### ISSUE THREAD

**Issue by syt-honey** [crimx/ext-saladict#1696]
## 设备信息
- 操作系统: [macOS Big Sur 11.5.2]
- 浏览器版本: [Chrome 98]
- 沙拉查词版本: [v7.20.0]

## 描述问题
打开 `codepen` 网站，然后选中 `JS` tab，选中某个单词唤起沙拉查词的瞬间，窗口中会有背景中的黑色滚动条。

## 复现步骤
1. 打开网站 [Day 27 Drag The CSS Jelly Pickle #JavaScript30](https://codepen.io/syt-honey/pen/WNdRNEK)
2. 选中 `JS` tab 中的任意单词
3. 观察当前弹窗弹出瞬间
4. 背景中的滚动条出现在了弹窗中，当前弹窗加载完后恢复正常

## 期待的正常行为
不论在哪个网站、不论在什么场景下，弹窗都应该在最上面

## 截图
https://user-images.githubusercontent.com/36325249/159856898-d63c2b21-1507-4b92-9d1b-2771f1cccc77.mov

**Comment by crimx** [comment]
这个应该是 Chrome 硬件加速的 bug，解决方案只能是让 CSS 动画过度不触发硬件加速了。

P.S. 这不是我的 pen 么哈哈哈哈哈

**Comment by syt-honey** [comment]
> 这个应该是 Chrome 硬件加速的 bug，解决方案只能是让 CSS 动画过度不触发硬件加速了。

奥奥，我知道了，这就是一个过渡动画是吧。我还以为是两种状态 -_-

> P.S. 这不是我的 pen 么哈哈哈哈哈

哈哈哈哈，这个要去问 Leo 了 😆，他最近天天都在偷偷学习 🙃️
