### ISSUE TITLE
有道翻译只翻译了部分内容 无法全部获取翻译

### ISSUE THREAD

**Issue by bluegothic** [crimx/ext-saladict#1703]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [edge 99.0.1150.52] 
- 沙拉查词版本: [7.20.0] 

## 描述问题

使用有道翻译在划取长文本时，翻译结果只显示部分内容，无法全部获取文本翻译

## 复现步骤

划词=>翻译

## 期待的正常行为

应显示划取长文本全部的翻译结果

## 截图

![bug](https://github.com/bluegothic/picture/blob/188e6bc07bcc2a87d39961f132c9c67aee7ace6b/bug.PNG)

**Comment by higrass-ai** [comment]
您好，请问解决了吗，我也有一样的问题，重新安装也无法解决

**Comment by freemedom** [comment]
确实，我也发现了 @higrass-ai

**Comment by freemedom** [comment]
原因大概是有道最近限制了这个api，http://fanyi.youdao.com/translate_o?smartresult=dict&smartresult=rule

**Comment by freemedom** [comment]
https://github.com/crimx/ext-saladict/issues/1648
@bluegothic

**Comment by crimx** [comment]
Duplicate of #1651
