### ISSUE TITLE
关于PDF阅读器

### ISSUE THREAD

**Issue by IceCreamInAvalon** [crimx/ext-saladict#1706]
## 设备信息
- 操作系统: [window10] 
- 浏览器版本: [Chrome77] 
- 沙拉查词版本: [v7.20.0] 

## 请描述目前使用沙拉查词遇到什么不便

PDF阅读器使用起来很方便，但是打开阅读器的同时基础的PDF功能如 下划线 荧光笔 删除线 留言板却没了 希望可以添上 

## 理想情况下，沙拉查词应该怎么做

希望可以补上PDF浏览中下划线 荧光笔 删除线 留言板等基础文本编辑功能

**Comment by crimx** [comment]
[常见问题及答复](https://saladict.crimx.com/q&a.html#%E9%97%AE%EF%BC%9A%E5%8F%AF%E4%B8%8D%E5%8F%AF%E4%BB%A5%E5%A2%9E%E5%8A%A0-pdf-%E9%98%85%E8%AF%BB%E5%99%A8%E5%8A%9F%E8%83%BD%EF%BC%8C%E5%A6%82%E5%81%9A%E7%AC%94%E8%AE%B0%E3%80%81%E5%88%92%E7%BA%BF%E6%A0%87%E8%AE%B0%E3%80%81%E5%A4%9C%E9%97%B4%E6%A8%A1%E5%BC%8F%E7%AD%89%E3%80%82)
