### ISSUE TITLE
浏览器浏览pdf时，不能使用zotero将pdf保存起来

### ISSUE THREAD

**Issue by l0o0** [crimx/ext-saladict#171]
Ubuntu 18.04 chrome 

阅读划词都正常，就是不能使用zotero来保存pdf了，如果禁用了沙拉，就可以正常保存了。不知道是不是因为pdf插件的问题，是不是可以选择使用浏览器内置的pdf阅读器打开pdf？

**Comment by crimx** [comment]
你好，因浏览器安全机制，扩展不能跨扩展访问，所以本扩展是通过拦截 PDF 请求并调用内置的 PDF.js 浏览 PDF。如果你希望其它扩展来关联 PDF，可在本扩展设置中关闭 PDF 浏览。

这个在初次使用注意事项中有说明：https://github.com/crimx/ext-saladict/wiki/Instructions

另外本扩展 PDF 浏览界面也可以按保存按钮下载到本地。
