### ISSUE TITLE
PantherBar作者已更改为Snip.Do，沙拉查词失效

### ISSUE THREAD

**Issue by hardsoft888** [crimx/ext-saladict#1714]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Edge100.0.1185.29 (64 位)]、[360急速浏览器13.0.2256.0][以及其他浏览器]
- 沙拉查词版本: [7.20.0]

## 请描述目前使用沙拉查词遇到什么不便

原来，沙拉有提供PantherBar插件，所以在PantherBar中可以呼出沙拉，实现在浏览器外查词。现在，PantherBar更新成了Snip.Do，在其扩展库中，没有沙拉查词的扩展。是否重新可以提供WIN10下该APP的扩展支持？万分感谢！！！

![无标题](https://user-images.githubusercontent.com/103290976/162545534-555a7235-d266-434c-9409-2d2d7c43d958.png)

![1](https://user-images.githubusercontent.com/103290976/162545608-0fd5cb11-14fe-4d05-8c97-b22b87912151.png)

## 理想情况下，沙拉查词应该怎么做

重新提供WIN10下对Snip.Do的扩展支持。

**Comment by crimx** [comment]
https://github.com/crimx/ext-saladict/discussions/605#discussioncomment-2501476
