### ISSUE TITLE
请问如何设置右键菜单中的一项自动执行

### ISSUE THREAD

**Issue by WangShuoran** [crimx/ext-saladict#1718]
比如我想用的是彩云小译的网页翻译，因为平常看外文比较多，所以如果有一个功能可以帮我自动打开这个功能就好了，因为平常用触控板，不太方便，谢谢啦！

**Comment by crimx** [comment]
你可以直接转彩云小译的扩展，或者在沙拉查词[设置](https://saladict.crimx.com/manual.html#open-setting)「右上弹框」下配置点击按钮的行为。

**Comment by crimx** [comment]
以及配置[快捷键](https://saladict.crimx.com/manual.html#shortcuts)

**Comment by WangShuoran** [comment]
这个右上弹框功能很好用，我喜欢它
