### ISSUE TITLE
无法使用腾讯翻译君

### ISSUE THREAD

**Issue by jiang-gy** [crimx/ext-saladict#1724]
## 设备信息
- 操作系统: [W10] 
- 浏览器版本: [Chrome77] 
- 沙拉查词版本: [v7.20.0] 

## 描述问题

无法使用腾讯翻译君；

## 截图

![image](https://user-images.githubusercontent.com/63504229/164367489-39efa0ca-c9a8-4f10-8141-d4d27c237293.png)

**Comment by Yolo-qh** [comment]
1、[腾讯云控制台](https://curl.qcloud.com/imsowZzT)，先实名再去产品里面找机器翻译，然后免费试用领取免费账户。
2、[腾讯云控制台](https://curl.qcloud.com/imsowZzT)，右上方头像菜单，点击访问管理，左侧访问密钥，点击API密钥管理，如没有密钥则新建一个，然后把 SecretId 和 SecretKey 的值复制进来。

**Comment by jiang-gy** [comment]
谢谢[Yolo-qh](https://github.com/Yolo-qh)的回答，问题解决
