### ISSUE TITLE
功能建议：提供「查词后自动加入生词本」开关

### ISSUE THREAD

**Issue by xuchkang171** [crimx/ext-saladict#1729]
## 设备信息
- 操作系统: [macOS Monterey 12.0.1] 
- 浏览器版本: [Firefox 99.0.1] 
- 沙拉查词版本: [v7.20.0] 

## 请描述目前使用沙拉查词遇到什么不便

查词后，需要点击红心才添加到生词本。

## 理想情况下，沙拉查词应该怎么做

提供一个「查词后自动加入生词本」开关。参考欧路词典 mac app 中，设置->通用->词典->「查词后自动加入生词本」功能。

**Comment by crimx** [comment]
开启查词记录即可。

**Comment by xuchkang171** [comment]
> 开启查词记录即可。

开启查词记录后，查词并不会自动添加到沙拉的生词本。

我的目的也并不是通过「查词后自动加入生词本」功能在沙拉得到一个查词记录或生词本记录，而是配合「欧路单词同步」「扇贝单词同步」功能，最终达到浏览器查词后（不用点击那个红心）即触发自动加入欧陆（查词记录）及扇贝（生词本）的效果。

换言之，我希望沙拉查词是且仅是我在浏览器端的查词入口，而不希望在沙拉这里再「重复」管理一个查词记录、生词本。

**Comment by crimx** [comment]
你好，明白了。查词自动加入生词本的功能与沙拉查词的设计相违背，故没有计划加入这个功能。
