### ISSUE TITLE
6.7版本中的谷歌翻译对于中文划词无法显示英文

### ISSUE THREAD

**Issue by g495326** [crimx/ext-saladict#173]
- 平台：win7 chrome 63

- 类型：查词bug

- 重现：
6.6版本，如下
![1](https://user-images.githubusercontent.com/41222130/43273484-1b9aafc2-912f-11e8-9018-62adf65340a6.png)
6.7版本，如下
![2](https://user-images.githubusercontent.com/41222130/43273496-22fd0aee-912f-11e8-8770-031a28f32033.png)

- 期待：恢复到6.6的样子

PS：为了重现该bug，我手动降级为6.6，虽然单词本我已经导出，尴尬的是，我无法导入，有没有解决方案？

**Comment by crimx** [comment]
非常抱歉带来不变。这个 bug 已在 #172 紧急修复，并已经发布了，稍等即可自动更新。

生词本目前没有加入导入功能，原因是本扩展的生词本目的是作为单词获取的临时载体。所以既然导出来了，就导入到相应的工具（如 [Anki](https://github.com/crimx/ext-saladict/wiki/ANKI)）中背起来吧！

**Comment by crimx** [comment]
已发布。
