### ISSUE TITLE
求单词管理中的翻译引擎添加有道词典

### ISSUE THREAD

**Issue by hhoao** [crimx/ext-saladict#1738]
## 设备信息
- 操作系统: [] 
- linux
- 浏览器版本: [] 
- chrome版本 102.0.5005.49（正式版本）beta （64 位）
- 沙拉查词版本: [] 
- 7.20.0

## 请描述目前使用沙拉查词遇到什么不便

单词管理中所有的上下文翻译引擎翻译单词时只能翻译出一个释义，这对学习单词来说并不友好

## 理想情况下，沙拉查词应该怎么做

希望添加添加有道词典，或者希望提供翻译引擎所翻译单词的所有释义

## 额外信息

![image](https://user-images.githubusercontent.com/64757882/168705019-83ee7e31-58f0-4fc0-a27b-1d1e1f41e8b8.png)

![image](https://user-images.githubusercontent.com/64757882/168705105-55fd0966-8da2-4a49-ae15-381794472218.png)

**Comment by crimx** [comment]
这是刻意的设计，沙拉查词目前在探索更准确的翻译机制，但不会提供多个与上下文不相关的释义。https://saladict.crimx.com/anki.html
