### ISSUE TITLE
劍橋詞典無法發音

### ISSUE THREAD

**Issue by CurtisJamesgh** [crimx/ext-saladict#175]
- 平台：Windows 8.1 with Chrome 68

- 类型：字典無法發音。

- 期待：修復發音功能，感謝。

- 实际： 谷歌翻譯發音正常，劍橋詞典卻無法。

**Comment by crimx** [comment]
你好，請問在劍橋詞典的網頁上能發音嗎。

點擊字典介面上劍橋詞典的標題即可訪問網頁。

如網頁上可以，請提供單字例子以及不能發音的地方。

**Comment by CurtisJamesgh** [comment]
網頁（dictionary.cambridge.org）上能夠發音、但是查詢視窗卻無法發音，無論什麼字都一樣。

之前的版本可以，就最近這兩次改版後就不行了。

**Comment by crimx** [comment]
感謝提醒。是劍橋詞典更新了網頁，我一會更新解析程式。

**Comment by CurtisJamesgh** [comment]
萬分感謝：）

**Comment by crimx** [comment]
已修復。請等待更新。
