### ISSUE TITLE
独立窗口激活时调用快捷键重新搜索剪贴板

### ISSUE THREAD

**Issue by vvyoko** [crimx/ext-saladict#1750]
我是在浏览器外通过快捷键调用的独立窗口
用的是 预选加载剪贴板模式

第一次调用没问题
关闭独立窗口再次调用也没问题
有问题的是调用之后窗口忘关(或者需要频繁查询故意没关)
然后再次通过快捷键调用时并不会自动搜索剪贴板了....

导致现在每次查询之后都要特意去关闭那个窗口
我偶尔记得好像以前不会这样
是改了还是我记错了?

最好是能在再次调用时重新搜索剪贴板

如果不行可否为独立窗口添加失去焦点后自动关闭窗口的功能?
就像浏览器中非独立窗口的快捷键查询那样
失去焦点后就消失了
再次调用又会重新搜索剪贴板
也不会有忘了关窗口的烦恼

**Comment by crimx** [comment]
你看看配置了快捷键的功能是哪个？有一个是打开或高亮查词面板，有一个是对剪贴板进行查词，后者应该是你要的。

**Comment by vvyoko** [comment]
> 有问题的是调用之后窗口忘关(或者需要频繁查询故意没关)

我就说为什么以前可以...
感谢.
