### ISSUE TITLE
某个网站不能划词

### ISSUE THREAD

**Issue by e71828** [crimx/ext-saladict#1755]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [101.0.4951.67] 
- 沙拉查词版本: [7.20] 

## 描述问题

只有某个网站不能划词，其它可以。

## 复现步骤

1. 打开 [wangye](http://www.isle.illinois.edu/speech_web_lg/coursematerials/ece401/fa2020/)
2. 点击单词。

## 期待的正常行为

弹出翻译

**Comment by crimx** [comment]
尝试没有问题的，是不是因为网页没有加载完成？可以再打开试试。
