### ISSUE TITLE
【bug】独立小窗口无法使用

### ISSUE THREAD

**Issue by Rexexe** [crimx/ext-saladict#1757]
## 设备信息
- 操作系统: [win11 21H2 22000.675]
- 浏览器版本: [Chrome 102.0.5005.63]
- 沙拉查词版本: [v7.20.0] 

## 描述问题
使用快捷键调用小窗口翻译，无反应

## 复现步骤
只有独立小窗口报错，浏览器右上角以及悬浮窗没问题

## 截图
![image](https://user-images.githubusercontent.com/27289798/172304789-3168e2b8-8db3-422d-b403-0bf93266495f.png)

**Comment by Rexexe** [comment]
重装插件该问题消失

**Comment by crimx** [comment]
可能是独立窗口宽高设置过小导致的。
