### ISSUE TITLE
对代码块+搜索框+文本框进行过滤

### ISSUE THREAD

**Issue by FineRegn** [crimx/ext-saladict#1758]
## 设备信息
- 操作系统: [windows10] 
- 浏览器版本: [Chrome102] 
- 沙拉查词版本: [7.20.0] 

## 请描述目前使用沙拉查词遇到什么不便

在代码块+搜索框+文本框标签中 会进行匹配
在选择直接弹出面板的情况下会非常阻碍阅读

## 理想情况下，沙拉查词应该怎么做

不在代码块+搜索框+文本框中进行匹配
或者添加不对中英文混合的文本进行匹配的选项

## 替代方案

对代码块html标签如&lt;code&gt;/进行过滤

## 额外信息
![image](https://user-images.githubusercontent.com/76417073/172335662-1032a6d5-2ab5-4fe0-92c5-8002b9262d1c.png)

**Comment by crimx** [comment]
> 不在搜索框+文本框中进行匹配

见设置-查词习惯-不在输入框划词

> 或者添加不对中英文混合的文本进行匹配的选项

见设置-查词习惯-划词语言

**Comment by FineRegn** [comment]
>> 不在搜索框+机器人进行匹配
>  
> 见设置-查词习惯-不在输入框画词
  
已解决 感谢指导 但是好像没有对代码块过滤的支持？
比如&lt;code&gt; &lt;pre&gt;标签

**Comment by crimx** [comment]
代码块目前不支持。
