### ISSUE TITLE
6.8.3版本的朗文词典列表图标与发音图标重叠，以及可否实现按键发音

### ISSUE THREAD

**Issue by g495326** [crimx/ext-saladict#176]
- 平台：win7 chrome 63

- 类型：错误

- 重现：提供详细的可重现问题的操作。
![1](https://user-images.githubusercontent.com/41222130/43363778-f03602c0-933e-11e8-979b-b46cef2b3a10.png)

- 期待：理想情况下扩展应该怎么做？
修复此问题，
1、关于悬浮发音，是挺方便的，不用点击鼠标左键了。但是有时鼠标会意外的悬停的发音图标上，造成发音。容易引起尴尬。
2、当然我不是让悬浮发音直接改成点击发音，毕竟其他人可能需要。
3、最好能提供设置选项，默认悬浮发音，以便向后兼容。

**Comment by crimx** [comment]
谢谢反馈！

因为内部页面需要使用不一样的加载方式，所以有的样式可能跟正常页面不一致。这个重叠会在下个版本修复。

悬浮发音是有延时的，鼠标意外停留在喇叭上的概率相对较小，就不再增加设置复杂度了。
