### ISSUE TITLE
Android 上的 Anki 卡牌显示异常

### ISSUE THREAD

**Issue by RiwiHow** [crimx/ext-saladict#1763]
## 设备信息
- 操作系统: [Windows 11] 
- 浏览器版本: [Firefox 101.0.1] 
- 沙拉查词版本: [v7.20.0] 

## 描述问题

在浏览器上保存到生词本后，Windows 上的 Anki 可以正常查看，使用 AnkiWeb 账户同步到 Android 上，卡牌显示有问题

## 期待的正常行为

Android 上也应该是好的

## 截图

![Screenshot_20220611-075402__01_Mosaic_7_54_34](https://user-images.githubusercontent.com/53964574/173163869-de197ab8-2df4-4295-a04c-7efd500df4d0.jpg)
<img width="960" alt="Snipaste_2022-06-11_07-55-07" src="https://user-images.githubusercontent.com/53964574/173163873-e2562a4e-6ba3-4282-872c-7941ff2cab02.png">

**Comment by crimx** [comment]
我这边测试正常的。是不是修改过卡牌类型或者网络原因等原因导致卡牌同步的数据出现损坏？在你的截图中看到数据 .bin 文件加载失败了。

**Comment by RiwiHow** [comment]
> 我这边测试正常的。是不是修改过卡牌类型或者网络原因等原因导致卡牌同步的数据出现损坏？在你的截图中看到数据 .bin 文件加载失败了。

我没有改过卡牌。我试了一下手动导出后再导入到手机，还是这个样子，应该也不是网络原因。
不过我用 Chrome 上的沙拉查词，再导入到手机上，没有提示 .bin 文件加载失败，但是还是不能输入答案。
![Screenshot_20220612-074411_Mosaic_7_44_27](https://user-images.githubusercontent.com/53964574/173208486-8aa6e431-ae82-4df1-a6a5-764b1fb4e7f3.jpg)

**Comment by crimx** [comment]
你分别在手机和PC上查看（编辑）这张卡牌，看看 `ContextCloze` 是否为空的（如果有可以复制一下贴到这里）？以及卡片类型是否为 `Saladict Cloze` ？

**Comment by RiwiHow** [comment]
Windows：``They’re not flashy, but they offer {{c1::simplicity}} with style``
Android：  ``They’re not flashy, but they offer {{c1::simplicity}} with style``
看起来好像是一样的

卡片类型：
![Screenshot_20220612-090910_Mosaic_9_9_35](https://user-images.githubusercontent.com/53964574/173210132-19846d7a-9253-4b95-baef-a87e07a492c9.jpg)
<img width="774" alt="Snipaste_2022-06-12_09-12-40" src="https://user-images.githubusercontent.com/53964574/173210134-63709732-51c5-4c67-8822-cb4d6ef5aea0.png">

**Comment by crimx** [comment]
感谢提供，找到问题了。Android 上再次打开这个编辑笔记页面，然后点底下的 `卡片：Saladict Cloze`，新打开的卡片类型编辑页面上方中找到 `{{{{type:cloze:ContextCloze}}`，删除前面两个 `{{`，然后点击下方的「背面」，同样删除，保存即可。

**Comment by RiwiHow** [comment]
好了，谢谢。话说刚才我同步了一个新的卡片，这个多余的 ``{{`` 自己没了，是你刚才 commit 就更新了？

还有，Firefox 的 bin 的问题，是不是 ``favicon`` 有问题呀？
Firefox 同步的：
![Screenshot_20220612-095038__01](https://user-images.githubusercontent.com/53964574/173211050-f371cfb5-bfa4-405d-8691-d81473e4dbe4.jpg)

Chrome 同步的：
![Screenshot_20220612-095042__01](https://user-images.githubusercontent.com/53964574/173211057-eaf310e8-ea4e-4b33-a591-e15cbe146298.jpg)

**Comment by crimx** [comment]
不是，我的 commit 要在下一次发版才会生效。你这边是因为这个是卡片类型，只需改一次所有 `Saladict Cloze` 的卡片都会应用上的。

火狐的 API 直接导出 icon 的数据了，而 Anki [没有做支持](https://anki.tenderapp.com/discussions/ankidesktop/20987-how-can-anki-show-image-file-in-base64-format#comment_41489479)。

要支持先回到刚才卡片类型编辑的界面，把 `<img src="{{Favicon}}" />` 换成 `<span class="favicon" style="background-image:url({{Favicon}})"></span>` ，背面同样替换，然后点击下方的 「样式」标签，末尾添加

```css
.favicon {
  display: inline-block;
  width: 1em;
  height: 1em;
  background: center/cover no-repeat;
}
```

**Comment by RiwiHow** [comment]
哦，好的，谢谢！
