### ISSUE TITLE
关于三次ctrl弹出独立窗口翻译的问题。

### ISSUE THREAD

**Issue by coeoo** [crimx/ext-saladict#1773]
## 设备信息
- 操作系统: [windows11] 
- 浏览器版本: [chorme 100] 
- 沙拉查词版本: [v7.20.0] 

## 请描述目前使用沙拉查词遇到什么不便

因为我使用了listray这个快速查找文件的软件，它的默认启动是两次连续快速按两次ctrl  而这个就和三次ctrl弹出独立翻译窗口的功能冲突了。连按三次总是识别到我的listary软件，我想去改一下快捷键发现无法更改。

## 理想情况下，沙拉查词应该怎么做

理想情况下，应该支持修改快捷键才对。或者将三次ctrl的改为其他更合理的按键。比如两次~~  或者两次alt 或者其他。

**Comment by crimx** [comment]
「[扩展设置](https://saladict.crimx.com/manual.html#open-setting)」-「快捷查词」-「启用Ctrl快捷键」

其它快捷设置： https://saladict.crimx.com/manual.html#shortcuts
