### ISSUE TITLE
是否考虑加入同步功能？

### ISSUE THREAD

**Issue by Sraw** [crimx/ext-saladict#178]
是否考虑加入同步功能？这样就可以在多机上同步生词本/查词历史/设置等。

如果考虑的话，我可以负责服务端的编写与维护。

**Comment by crimx** [comment]
你好，非常感谢你的提议！目前 Saladict 的设置是同步的。

至于生词本和历史记录我认为还是不同步好。目前 Saladict 并没有打算打造为背单词扩展（难度太大），故生词本的功能主要是作为获取单词素材的临时载体。所以我认为同步的实质意义不大，更多是对数据占领的心理安慰。

在 Saladict 的设计中，有几个地方都尝试性地在这样的心理盲点上让用户不舒服。当然还不是很满意，期待能找到一个平衡点。

最后再次感谢你的提议。有什么想法欢迎继续交流。

**Comment by Sraw** [comment]
设置的同步是由什么驱动的？Google自身的同步服务吗？

另外不知道这是不是最近引进的功能，我的linux系统和windows系统貌似没有同步设置，我是手动重新设置的。

**Comment by crimx** [comment]
是的， Google 账号登录 Chrome 后会同步。
，这个功能应该很久前就有了。Saladict 一直都支持。

**Comment by Sraw** [comment]
好的，谢谢，可能是安装后需要等一等。
