### ISSUE TITLE
与简悦一起使用时WordEditorPanel的z-index不够

### ISSUE THREAD

**Issue by unlsycn** [crimx/ext-saladict#1783]
## 设备信息
- 操作系统: [Windows 11 21H2] 
- 浏览器版本: [Microsoft Edge 103.0.1264.37] 
- 沙拉查词版本: [v7.20.0] 

## 描述问题

在[简悦 - SimpRead](https://github.com/Kenshin/simpread)的「阅读模式」页面，Saladict的wordEditorPanel-Background的z-index是$global-zindex-dictedito=2147483645，而简悦的z-index是2147483646，于是「保存到生词本」无法正常显示。

## 复现步骤

如截图，在[页面内](https://rainforests.mongabay.com/deforestation_alpha.html)打开「阅读模式」，选中单词，点击「保存到生词本」，问题出现。

## 截图

![2022-06-29_114205](https://user-images.githubusercontent.com/31343548/176348078-a09a6b96-dc3f-402d-a9d5-925288969ce4.png)

## 期待的正常行为

将wordEditorPanel-Background的z-index改为2147483646，显示正常。
![2022-06-29_114343](https://user-images.githubusercontent.com/31343548/176348089-a42297d3-5d62-4f4b-8b00-1cd858fef0dc.png)

## 额外信息

saladict的$global-zindex-dictpanel-dragbg是2147483646，但是从来没有用过这个变量，所以将$global-zindex-dicteditor也改成2147483646应该不会对现有功能造成影响吧

**Comment by crimx** [comment]
好的，感谢反馈🙏🏻

**Comment by unlsycn** [comment]
#1784 Merged
