### ISSUE TITLE
期望上架 utools 插件

### ISSUE THREAD

**Issue by JasonGrass** [crimx/ext-saladict#1786]
## 设备信息
- 操作系统:   无
- 浏览器版本:   无
- 沙拉查词版本:   无

## 请描述目前使用沙拉查词遇到什么不便

[uTools](https://u.tools/ ) 是一个越来越被关注的效率工具，期望作者可以开发其插件。

## 理想情况下，沙拉查词应该怎么做
上架 uTools 插件，可以直接使用 uTools 进行查词。

## 替代方案

其它的 utools 查词插件，发现都没有 沙拉查词 好用。

## 额外信息

老早之前好像是有这个插件的，下架了吗？呜呜呜。

![image](https://user-images.githubusercontent.com/10756994/177450704-676110aa-42b8-43b3-84b8-7ee4bba0fa5e.png)

**Comment by crimx** [comment]
@anrgct 大佬维护的，好像因为什么原因下架了 https://github.com/crimx/ext-saladict/discussions/827

**Comment by crimx** [comment]
可以直接在仓库装 https://github.com/anrgct/utools-saladict
