### ISSUE TITLE
干扰广告拦截扩展的css拦截规则

### ISSUE THREAD

**Issue by Heporis** [crimx/ext-saladict#1787]
## 设备信息
- 操作系统: win10
- 浏览器版本: edge103
- 沙拉查词版本: 7.20.0

## 描述问题

划词会干扰广告拦截扩展的css拦截规则

## 复现步骤

1.安装广告拦截扩展，比如ublock origin，启用CHN: AdGuard Chinese (中文)这个规则(默认已启用)
2.打开[远景论坛](https://bbs.pcbeta.com/)，选中一段文本，原本已经被屏蔽的占位符就会出现，取消选中则消失
3.关闭沙拉，则第二步中的情况不会出现

## 期待的正常行为

希望能不影响广告过滤插件的css过滤规则

## 截图

![GIF 2022-7-6 11-21-25](https://user-images.githubusercontent.com/51895154/177461746-fabf45a9-88fc-4990-bdb1-d55f7a034e17.gif)

## 额外信息

具体的css拦截规则是这一条：
bbs.pcbeta.com#?##toptb ~ #wp > div[class]:matches-css(height : /170px/)

**Comment by crimx** [comment]
不太可能由沙拉查词导致的。我这边 ublock 是没有隐藏，你看看有没有其它插件在控制这个样式？

![image](https://user-images.githubusercontent.com/6882794/177468183-954632fa-5cc9-4c10-bf1a-b725e00e83cd.png)

**Comment by crimx** [comment]
开启沙拉查词选中的效果

![image](https://user-images.githubusercontent.com/6882794/177468408-4b0d5712-9d23-4c1d-a52d-b15b876c3d8d.png)

**Comment by Heporis** [comment]
> 不太可能由沙拉查词导致的。我这边 ublock 是没有隐藏，你看看有没有其它插件在控制这个样式？

我开无痕模式，只加载了这两个插件，最新的规则肯定是屏蔽了这个空白广告位的，我前几天刚反馈给adguard的，你更新一下规则试试。我刚才又给他们反馈了一下，看看能不能换一种不和沙拉冲突的css拦截方式。看看你们哪边好解决吧🤣我估计他们那边换一种拦截规则简单一点，先看他们那边的答复吧。[这个](https://github.com/AdguardTeam/AdguardFilters/issues/123472)
![image](https://user-images.githubusercontent.com/51895154/177479740-d169f146-3f0a-4d5f-a88a-fdfe90285a3a.png)

**Comment by crimx** [comment]
更新之后确实复现了。原理是这样的，ublock 规则依赖了这个广告位元素的两个属性，而这个页面监听了 `<html>` 如果插入了新元素，就会把这个广告位的一个属性删掉了，所以导致 ublock 规则匹配不上。为了兼容性沙拉查词的元素都是在 `<html>` 下插入的，所以触发了这个现象，这个目前改变不了。ublock 规则改为依赖 `#aIHJSMBf` 屏蔽应该就行。

**Comment by Heporis** [comment]
> 更新之后确实复现了。原理是这样的，ublock 规则依赖了这个广告位元素的两个属性，而这个页面监听了 `<html>` 如果插入了新元素，就会把这个广告位的一个属性删掉了，所以导致 ublock 规则匹配不上。为了兼容性沙拉查词的元素都是在 `<html>` 下插入的，所以触发了这个现象，这个目前改变不了。ublock 规则改为依赖 `#aIHJSMBf` 屏蔽应该就行。

你能去adguard那边用英语解释一下这个原理吗？上面有issue的链接。我不太会解释，那边的人说搞不懂出什么问题😂
