### ISSUE TITLE
打开本地pdf后无法使用词典的“pdf模式”

### ISSUE THREAD

**Issue by drinmo** [crimx/ext-saladict#179]
- 平台：Win10 和 Chrome

- 类型：错误

- 启用划词翻译√  、默认用本扩展浏览 PDF √

- 重现：几乎每一次

- 期待：打开已经下载好的本地pdf，可以直接进入词典的“pdf模式”或者右键小图标“打开为pdf”实现功能

- 实际：新标签页被创建，页面抬头可见词典“pdf模式”的工具栏，**但无pdf文件显示**，背景为黑色。

**Comment by crimx** [comment]
你好！先感谢打赏与反馈！能说明是如何打开本地 PDF 的吗？

浏览器机制问题，是不能直接右击 PDF 文件打开的。

要直接打开本地 PDF 文件，请参考说明 <https://github.com/crimx/ext-saladict/wiki#pdf> 。

否则需要先进入扩展的 PDF 页面（见 wiki），在顶部有按钮打开本地 PDF （默认的 PDF 有箭头指引）。

如果还不行的话欢迎上传 PDF 原件供测试。

**Comment by drinmo** [comment]
重启机器后，根据参考说明对 允许访问文件网址 取消并重新勾选，问题已得到解决。
另，本地pdf为做左键双击打开。

**Comment by crimx** [comment]
好的！

**Comment by drcege** [comment]
@drinmo  你是怎么双击打开本地 PDF 的？ 我更新了最新版Chrome (69.0.3497.100)，为什么在本地右键打开方式用Chrome打不开PDF了

**Comment by crimx** [comment]
https://github.com/crimx/ext-saladict/wiki#pdf

**Comment by drcege** [comment]
嗯，我知道，都设置了，原来是可以的。。。
不知道怎么回事，不过刚刚重启了一下电脑就好了😅

**Comment by crimx** [comment]
好的，Chrome 更新后常常有些小问题，需要重启。

**Comment by Aster-snow** [comment]
我想请问一下怎么才能用浏览器打开本地PDF之后还能用saladict呀，我不论怎么打开PDF，那个收藏符号后面的saladict的标志都是灰的，并且也无法使用。（已设置为默认双左键击可打开，设置了允许访问文件网址）

**Comment by crimx** [comment]
灰的说明沙拉查词没有权限访问这个页面，请再次检查「允许访问文件网址」是否勾选。可尝试「关闭-重新勾选-重启」操作。

检查打开的 PDF 页面是否为沙拉查词内置 PDF 阅读器（链接带沙拉查词 id）。目前因为建议使用浏览器外划词搭配为本地 PDF 阅读器使用，拦截 PDF 链接功能是默认关闭的，请检查是否开启（见[初次安装的说明](https://saladict.crimx.com/notice.html)）。

最后如果依然无法解决，请另开 issue 描述你的情况。最重要提供浏览器版本和操作系统版本。最好能提供截图。

**Comment by tanxuan21** [comment]
允許訪問文件網址仍然不行,不是灰的,選擇單詞後沒有彈出沙拉查詞面板
