### ISSUE TITLE
双语例句这词典在词板里面无法显示

### ISSUE THREAD

**Issue by bfqbpq567** [crimx/ext-saladict#1806]
## 设备信息
- 操作系统: [] Win10
- 浏览器版本: [] Chrome98.0
- 沙拉查词版本: [] v7.20.0

## 描述问题

双语例句无法在词板里无法显示出来，这好像是欧陆的词典，也希望增加欧陆词典，欧陆词典挺好的。同时希望有自动展开词典的功能，有的词典内容太长了。

## 复现步骤

![image_23](https://user-images.githubusercontent.com/66172873/182988334-181c71eb-47a0-47d4-a81b-ccbc2da93718.png)

## 期待的正常行为

双语例句查到词，能出现在面板中

## 截图

![image](https://user-images.githubusercontent.com/66172873/182987244-8ee3c7bb-a8ff-4bde-a284-aec2ea1e093a.png)

**Comment by crimx** [comment]
点击下箭头即可展开，每个词典高度都可以在[设置](https://saladict.crimx.com/manual.html#open-setting)-「词典设置」中调节，不需要收纳设置默认高度为 99999 即可。
