### ISSUE TITLE
Typo? Should it be `enable`?

### ISSUE THREAD

**Issue by zhouhao** [crimx/ext-saladict#181]
多谢提供一个这么好的ext！

这边应该是`Enable`吗？

https://github.com/crimx/ext-saladict/blob/e89cd0310adc1d508c59074766e83f87f1812a73/src/_locales/popup/messages.json#L5
![image](https://user-images.githubusercontent.com/2281521/44111615-ed3c6606-9fd0-11e8-8c8c-1fdfca21b978.png)

**Comment by crimx** [comment]
Nice catch! :smile_cat:

**Comment by albertazhao** [comment]
朗文词典，单词释义与例句之间 通常有同义词或者搭配，这个显示是有bug的。建议修改。
![image](https://user-images.githubusercontent.com/6287061/44159988-93122a00-a0eb-11e8-9bf6-bf926b6fab36.png)

**Comment by albertazhao** [comment]
是不是

**Comment by crimx** [comment]
好的谢谢反馈。以后可以新起一个 issue .
