### ISSUE TITLE
可选右键菜单触发“划词翻译”

### ISSUE THREAD

**Issue by bowencool** [crimx/ext-saladict#1817]
## 请描述目前使用沙拉查词遇到什么不便

我经常在阅读时双击划词，大部分情况都不是为了翻译，但现有配置每次都会出现一个小图标。

## 理想情况下，沙拉查词应该怎么做

可选右键菜单触发“划词翻译”

## 替代方案

右键菜单新增“添加到生词本”

**Comment by bowencool** [comment]
或者是新增右键菜单触发“划词翻译”

**Comment by bowencool** [comment]
我经常在阅读时双击划词，大部分情况都不是为了翻译，但现有配置每次都会出现一个小图标。谢谢！

**Comment by crimx** [comment]
打开「[沙拉查词设置](https://saladict.crimx.com/manual.html#open-setting)」

- 「右键菜单」，只保留「沙拉查词」即可右键直接看到选项。
- 「查词习惯」，更换查词模式。

**Comment by bowencool** [comment]
> 打开「[沙拉查词设置](https://saladict.crimx.com/manual.html#open-setting)」
> 
> * 「右键菜单」，只保留「沙拉查词」即可右键直接看到选项。
> * 「查词习惯」，更换查词模式。

谢谢，但是这个右键查词好像并没有反应：
MacOS 12.5 Chrome 104

**Comment by bowencool** [comment]
> > 打开「[沙拉查词设置](https://saladict.crimx.com/manual.html#open-setting)」
> > 
> > * 「右键菜单」，只保留「沙拉查词」即可右键直接看到选项。
> > * 「查词习惯」，更换查词模式。
> 
> 谢谢，但是这个右键查词好像并没有反应： MacOS 12.5 Chrome 104

是我没打开开关。。
