### ISSUE TITLE
弹出的查词界面 不要捕捉输入框 或者提供可选配置

### ISSUE THREAD

**Issue by maiyuyu** [crimx/ext-saladict#182]
#### 弹出的查词界面 请不要捕捉输入框 或者提供可选配置
这样在Chrome编辑区无法同时编辑与查询；
**也会导致vimium插件无法在网页上使用，在查词界面需要先脱离输入框锁定才能使用。**

在产品体验逻辑上，
既然用户已经选择个查询某单词，插件还默认捕捉输入框让用户输入干嘛呢？
如果有输入查询需求，我一般是点击右上角的插件图标。

**Comment by maiyuyu** [comment]
图示如下：
![image](https://user-images.githubusercontent.com/10529546/44296665-a2fd5a00-a2f5-11e8-8e74-66f1d03ec676.png)

**Comment by crimx** [comment]
又被发现一个偷懒的地方了哈哈（捂脸）。不行现在用户的眼神实在太犀利了 :stuck_out_tongue_closed_eyes:  。接下来会抽时间处理的。
