### ISSUE TITLE
Saladict for Safari 没有工作

### ISSUE THREAD

**Issue by ZHANGChongzhi** [crimx/ext-saladict#1823]
14寸M1 MBP
按照步骤成功在safari中添加了拓展，但是并不工作。选中不会有查词图标，直接用拓展处的图标查词也不行，只要输入东西就会显示一个黑框
![截屏2022-08-23 上午12 18 10](https://user-images.githubusercontent.com/32870489/186095680-775927d1-11a0-4639-9bbb-c76b29637523.png)

**Comment by Henrrychan** [comment]
我也是。你解决了吗

**Comment by crimx** [comment]
#1862 跟这个类似么？

**Comment by Kan9e** [comment]
应该是 #1629 的问题，更换编码重启后可正常使用

**Comment by ZHANGChongzhi** [comment]
已解决，谢谢！



> 应该是 #1629 的问题，更换编码重启后可正常使用
