### ISSUE TITLE
升级Chrome后控制台报错，无法配置

### ISSUE THREAD

**Issue by wmzy** [crimx/ext-saladict#183]
- 平台：fedora 28 / 版本 68.0.3440.84（正式版本） （64 位）

- 类型：错误

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。
每个页面都报这个错：
![image](https://user-images.githubusercontent.com/5526525/44441810-173f4280-a601-11e8-9e15-5a121bce759a.png)

**Comment by crimx** [comment]
嗨，这问题不在扩展层面。很可能是系统跟浏览器间的问题。初步猜测是升级过程中一些文件被损坏了。可以尝试重启系统后卸载本扩展再安装。

**Comment by crimx** [comment]
这似乎是 Chrome 扩展存储 API 的一个 bug <https://bugs.chromium.org/p/chromium/issues/detail?id=490915> 。原因未知，貌似在很小的机率下会出现，官方也搁置了修复。

综上：

1. 有可能是一些文件被系统占用了，这情况下重启系统应该可以解决。
2. 扩展文件被污染了，这情况建议卸载本扩展再安装。
3. 如果还出现问题的话只能建议彻底清理干净再重装 Chrome 。

**Comment by wmzy** [comment]
多谢，重启了下系统解决了，可能太久没有重启了吧
