### ISSUE TITLE
希望增加查词结果自动完整显示选项，目前需要每次手动点向下箭头，如下图所示。

### ISSUE THREAD

**Issue by AndyQiao0828** [crimx/ext-saladict#1830]
## 设备信息
- 操作系统: win10
- 浏览器版本: Chome104.0.5112.82
- 沙拉查词版本: v7.20.0

![image](https://user-images.githubusercontent.com/62641360/189024376-cb51db75-a206-4eef-afef-33a4482702c5.png)
希望实现自动完整显示匹配结果内容，目前需要每次点击向下箭头。
## 请描述目前使用沙拉查词遇到什么不便

希望实现自动完整显示多个词典中搜索词相关语句的完整内容，目前需要每次点击图中的向下箭头。

## 理想情况下，沙拉查词应该怎么做

每个词典自动完整显示匹配词的例句。

**Comment by crimx** [comment]
打开沙拉查词[设置](https://saladict.crimx.com/manual.html#open-setting)，词典设置，对应的词典设置默认高度大一点即可。
