### ISSUE TITLE
在chrome中浏览本地文件时，选中目标翻译的词后，没有出现沙拉查词的弹窗图标

### ISSUE THREAD

**Issue by eval-exec** [crimx/ext-saladict#1834]
## 设备信息
- 操作系统: [Arch Linux] 
- 浏览器版本: [Google Chrome 104.0.5112.101] 
- 沙拉查词版本: [v7.20.0] 

## 描述问题

我使用 chrome 打开本地的文件（在浏览器url栏输入本地文件的路径，比如 file:///tmp/sample.txt），选中里面的词之后，沙拉查词插件没出现沙拉查词的弹窗图标

## 期待的正常行为

正常情况下，应该会出现沙拉查词的图标

## 截图

这是打开`file:///tmp/sample.txt` 本地文件，选中待查询的词，没有出现沙拉啥词图标：
![image](https://user-images.githubusercontent.com/46400566/189376506-4309c8c0-0882-467c-b292-2f01acd7ccb5.png)

这是打开一个普通http网页后，选中待查询的词，就会出现沙拉查词的图标
![image](https://user-images.githubusercontent.com/46400566/189376289-2e90e3a5-3547-4b75-826b-ec375067caaa.png)

**Comment by crimx** [comment]
https://saladict.crimx.com/notice.html#%E9%A2%84%E8%AE%BE
