### ISSUE TITLE
能否增加对Edge浏览器的支持？

### ISSUE THREAD

**Issue by dhssingle** [crimx/ext-saladict#184]
微软也有提供移植工具
https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/porting-chrome-extensions

**Comment by crimx** [comment]
你好，因为 Edge 对 WebExtension 规范的实现也不是很全，需要做些兼容，如果有人愿意维护也是欢迎的。

**Comment by Key033** [comment]
Edge的pdf浏览器更加健全，支持标注。

**Comment by crimx** [comment]
鉴于 Edge 将基于 Chrome 开发，这个帖子关闭了。
