### ISSUE TITLE
快捷键无法设置为全局生效

### ISSUE THREAD

**Issue by swaitter** [crimx/ext-saladict#1848]
## 设备信息
- 操作系统: [MacOS 13] 
- 浏览器版本: [Version 105.0.5195.125] 
- 沙拉查词版本: [v7.20.] 

## 描述问题

chrome 插件快捷键设置中（chrome://extensions/shortcuts），之前的可以设置快捷键的生效范围，浏览器内或者全局，设置了全局，就可以在任何软件下生效，直接唤醒查词面板。目前已经没有办法可以设置全局了。

## 期待的正常行为

后面下拉框可以选择全局

## 截图

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/46062527/191636594-3ed08477-fa47-43e9-a868-c3ee6134799d.png">

**Comment by crimx** [comment]
是不是跟其它软件冲突了？这个是浏览器控制的，你可以试试重启浏览器或电脑。

**Comment by swaitter** [comment]
![image](https://user-images.githubusercontent.com/46062527/192225828-01351c08-ce80-4df0-8464-ed12ac1d43e7.png)
更换了一台win11电脑，是同样的情况。
对比其他插件发现，部分插件的快捷键是支持全局的。
想确认下，这个权限是完全由chrome控制的么？
自己查找了chrome的插件开发文档，暂时未找到相关的介绍。

**Comment by crimx** [comment]
快捷键配置完全由 chrome 控制的，第二个「在Chrome中」需要设置了第一个快捷键才会变成可选，可能前面你设的跟其它冲突了。你可以用 alt + L 测试一下。
