### ISSUE TITLE
固定面板大小不随页面缩放

### ISSUE THREAD

**Issue by linsui** [crimx/ext-saladict#185]
- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）
win10chrome

- 类型：错误？建议？
建议：能否使查词面板不随网页缩放？当网页放大后查词面板也放大会占据太多空间而且操作很不方便

- 期待：理想情况下扩展应该怎么做？
希望可以在扩展选项里设置面板大小，不随页面缩放变化。

- 实际：客观描述扩展实际上做了什么。
缩放页面时面板同时缩放

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
你好，能描述一下你的使用场景吗？为什么对网页进行缩放？为什么不希望查词面板跟随缩放？

**Comment by crimx** [comment]
如果你的浏览器是一直缩放的，可以设置查词面板的宽高和字体大小。

**Comment by linsui** [comment]
但是对于不同网页由于字体不同会经常调整，能否将面板大小固定？或是设置面板从右上角弹出而不嵌入网页？

**Comment by linsui** [comment]
对不同网页缩放设置不同，有时会经常切换，所以如果能固定大小就太好了:joy:

**Comment by crimx** [comment]
这种情况建议你使用右上图标的弹框，配合 chrome[ 扩展快捷键](https://github.com/crimx/ext-saladict/wiki#shortcuts)使用。

**Comment by linsui** [comment]
如果这样设置似乎无法使用双击查词:joy:，能否添加右上弹框双击查词的功能？

**Comment by linsui** [comment]
感谢您的解答 :joy:
