### ISSUE TITLE
右上弹框查词按钮第一次点击调整输入框大小，第二次开始查词

### ISSUE THREAD

**Issue by linsui** [crimx/ext-saladict#186]
- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）
win10chrome

- 类型：错误？建议？
错误：右上弹框查词按钮第一次点击调整输入框大小，第二次才开始查词

- 划词模式？以及其它觉得相关的设置。
右上弹框

- 重现：提供详细的可重现问题的操作。
点击扩展按钮输入单词，点击搜索按钮

- 期待：理想情况下扩展应该怎么做？
第一次点击时开始查词

- 实际：客观描述扩展实际上做了什么。
第一次点击时输入框缩小，第二次点击开始查词

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by linsui** [comment]
是这样，我输入单词后，点击输入框右侧的搜索按钮，第一次不会开始搜索

**Comment by crimx** [comment]
我测试是没问题的，我再看看其它潜在问题。与此同时你可以直接按回车搜索。

**Comment by linsui** [comment]
是的，直接按回车没有问题，谢谢 👍 。另外有个建议，能否把输入框改为多行？单行输入框在编辑较长句子是很困难 😄

**Comment by crimx** [comment]
这个之前在 Chrome 商店解答过，这个功能不太符合目前的设计。你可以把翻译网站的 tab 拖出来单独窗口，就可以用系统快捷键切换窗口了。这其实比同个页面里点击更为快捷，因为两边的焦点都可以保持。

**Comment by linsui** [comment]
明白了，谢谢解答 😄

**Comment by crimx** [comment]
v6.13.0 将在绿色工具栏下方引入可展开多行搜索框，可设置自动展开。“翻译模式”已自动开启。
