### ISSUE TITLE
沙拉查词的运营者们辛苦了，很高兴能使用这个软件，但是最近从win转换到mac，下载安装后，沙拉查词在Safari上仍然不能使用，不论是鼠标取词或是手动输入查词都无响应，尝试过重新下载安装，也核对了相关设置都处于开启状态，想问运营大大们有无解决办法，谢谢🙏

### ISSUE THREAD

**Issue by npj06** [crimx/ext-saladict#1862]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: []

**Comment by crimx** [comment]
你看看是不是这个编码问题 #1577

**Comment by npj06** [comment]
> 你看看是不是这个编码问题 #1577

十分感谢您的回复，已经重新更改了，仍然还是不可以
<img width="715" alt="截屏2022-10-08 16 08 56" src="https://user-images.githubusercontent.com/114918453/194697432-13cb0d26-6490-4
<img width="715" alt="截屏2022-10-08 16 08 56" src="https://user-images.githubusercontent.com/114918453/194697455-e203e6d2-a456-47bc-9052-05497ff443fe.png">
57b-889c-3c9acff481f1.png">

**Comment by crimx** [comment]
“不论是鼠标取词或是手动输入查词都无响应” 所以你是可以看到查词面板的是么？如果只是查词没有结果可能是扩展网络权限没有给到（[这里](https://saladict.crimx.com/safari.html)的第六步）。

**Comment by npj06** [comment]
查词面板一片空白，其他操作也都核对了，给您附了图和视频，超级感谢您的耐心解答！希望下次回复能让我重新快乐文献！
<img width="1470" alt="允许未签名的拓展" src="https://user-images.githubusercontent.com/114918453/194711832-4158a1ec-35ac-4fb0-b887-154c31a600b1.png">
<img width="880" alt="允许网站" src="https://user-images.githubusercontent.com/114918453/194711841-54c1b8bf-4a3c-41d4-b2f3-cad0b9a203ee.png">
<img width="1470" alt="查词设置" src="https://user-images.githubus
<img width="1470" alt="查词面板展开" src="https://user-images.githubusercontent.com/114918453/194711853-67d66386-4391-45c0-adef-1efaff8cb627.png">
e
<img width="1470" alt="查词面板" src="https://user-images.githubusercontent.com/114918453/194711852-6b836355-0281-4a5b-8e11-56986c1a67d0.png">
rcontent.com/114918453/194711845-8f13582b-b2f2-498f-a164-65ac3e8c58e0.png">

**Comment by npj06** [comment]
视频有点大了，传不上去，大概就是这样子，鼠标划词也没有任何反应

**Comment by npj06** [comment]
https://user-images.githubusercontent.com/114918453/194718330-70793f46-8696-40b0-9e84-c320159ae46c.mov

https://user-images.githubusercontent.com/114918453/194718338-23585b7f-ee3e-495f-a4c5-981b787e7010.mov

重新录制了大小合适的视频，表达会更清楚一些，谢谢！

**Comment by crimx** [comment]
这看起来像是崩溃了，但不清楚是什么原因。我这边测了一下是可以用的。

<img width="988" alt="image" src="https://user-images.githubusercontent.com/6882794/194736438-08ecb75c-b276-4932-9714-ad9e00ae833f.png">

窗口崩溃之后还剩一点点区域，你能右键点击一下那块，选最后一下「审查元素」（Inspect Element），弹出来的窗口中点击第二个标签「终端」（console），看看有无红色的报错信息。

**Comment by crimx** [comment]
<img width="794" alt="image" src="https://user-images.githubusercontent.com/6882794/194736558-fbd17f95-6318-41fd-ad22-6aa04ac5b276.png">

**Comment by npj06** [comment]
找到了，给您贴上图，应该确实是有问题的。
<img width="1470" alt="截屏2022-10-09 16 31 03" src="https://user-images.githubusercontent.com/114918453/194746609-1469facc-5bf3-426b-b03e-0296e
<img width="1470" alt="截屏2022-10-09 16 31 39" src="https://user-images.githubusercontent.com/114918453/194746618-c35740a9-9a9f-4d35-a067-62427ce4b621.png">
88bdf71.png">
<img width="1470" alt="截屏2022-10-09 16 31 48" src="https://user-images.githubusercontent.com/114918453/194746624-f2c30751-1967-4f62-9803-b97900b28a51.png">

**Comment by npj06** [comment]
<img width="1470" alt="截屏2022-10-09 16 31 03" src="https://user-images.githubusercontent.com/114918453/194746704-c4588b09-6482-48b7-ada6-5b906d354e7c.png">

**Comment by npj06** [comment]
<img width="1470" alt="截屏2022-10-09 17 27 41" src="https://user-images.githubusercontent.com/114918453/194749075-798d89e7-3baf-4f44-aa10-3d1b5076cda5.png">

**Comment by crimx** [comment]
你的系统和 Safari 版本是多少？可以双击其中一个错误信息（或者点击信息右边的 7.102ac3f8.js:237:87）看看具体的位置么？它的行列信息貌似不对，我这边找不到具体位置。

**Comment by npj06** [comment]
系统是mac OS12.6，Safari版本是16.0
<img width="1470" alt="截屏2022-10-10 21 35 15" src="https://user
<img width="1470" alt="截屏2022-10-10 21 35 32" src="https://user-images.githubusercontent.com/114918453/194879113-0be5424d-54f9-4c31-aaa9-425780b06
<img width="1470" alt="截屏2022-10-10 21 35 44" src="https://user-images.githubusercontent.com/114918453/194879163-b6e07e97-7608-45e0-bf37-84ca02b98494.png">
5b2.png">
<img width="1470" alt="截屏2022-10-10 21 36 03" src="https://user-images.githubusercontent.com/114918453/194879189-dfdcf299-79dd-44d7-a28b-53754a1fa313.png">

-images.githubusercontent.com/114918453/194879058-179e10a9-0c3e-40a7-b5e2-ca518d0a89ad.png">

**Comment by npj06** [comment]
<img width="1470" alt="截屏2022-10-10 21 35 15" src="https://user-images.githubusercontent.com/114918453/194879529-591a9b4e-8bf4-4bdb-9278-ec1dacccfffe.png">
<img width="1470" alt="截屏2022-10-10 21 35 32" src="https://user-images.githubusercontent.com/114918453/194879565-e947a08e-4339-4b2b-af46-f3f24b530185.png">

**Comment by npj06** [comment]
其余的项目都不能再点开的状态，不知道是不是您需要的材料，非常感谢您的回复，麻烦您了！

**Comment by npj06** [comment]
重新安装之后，再尝试成功了，谢谢您！

**Comment by crimx** [comment]
看起来是浏览器的消息通信出问题了，但不清楚是由什么原因导致的，我加一些防御性代码试试。

**Comment by npj06** [comment]
谢谢，现在大部分场景都可运营正常，只有偶尔会不出现了，感谢您的维护和开发！

**Comment by cyaaan823** [comment]
我这边也是，不过重新安装了还是不行

**Comment by cyaaan823** [comment]
我这边也是同样的问题，不过重新安装了还是不行

**Comment by npj06** [comment]
以上步骤都检查过了吗？每次重新打开浏览器都要重新允许未签名拓展，以及重新打开安装包，点击Safari偏好选择拓展，再重新开启Safari页面，试试看？

**Comment by cyaaan823** [comment]
检查过了，鼠标取词和手动输入查词都不行，控制台会出现像你一样的报错，但重新装了几遍都不行，github中的safari文件夹应该不需要下载只需要zip文件对吗

**Comment by Kan9e** [comment]
> 

我跟你一样，Safari上面不工作，有时候输入单词会变成一个矩形灰框，有时候就是一直在词典检索。。。

**Comment by npj06** [comment]
好呢，现在基本上就在网页上划词使用了




3℃
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "crimx/ext-saladict"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月7日(星期一) 下午2:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [crimx/ext-saladict] 沙拉查词的运营者们辛苦了，很高兴能使用这个软件，但是最近从win转换到mac，下载安装后，沙拉查词在Safari上仍然不能使用，不论是鼠标取词或是手动输入查词都无响应，尝试过重新下载安装，也核对了相关设置都处于开启状态，想问运营大大们有无解=E 5��办法，谢谢🙏 (Issue #1862)





   
我跟你一样，Safari上面不工作，有时候输入单词会变成一个矩形灰框，有时候就是一直在词典检索。。。

**Comment by Kan9e** [comment]
已经解决这个问题啦，问题出在safari默认编码上，在偏好设置-高级中把默认编码从GB 18030改为UTF-8再重启就可以了

**Comment by crimx** [comment]
Duplicate of #1629

**Comment by cheung-dp** [comment]
不能发音,不能显示图片.
fixed youtube caption 油猴插件在Safari中失效
Safari中没有扩展程序快捷键

三个从chrome转战Safari的老大难

**Comment by righterk** [comment]
> 已经解决这个问题啦，问题出在safari默认编码上，在偏好设置-高级中把默认编码从GB 18030改为UTF-8再重启就可以了

感谢！更改设置后终于可以使用了
