### ISSUE TITLE
Firefox 内置PDF阅读器无法自动加载

### ISSUE THREAD

**Issue by chenxilong** [crimx/ext-saladict#187]
- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）

win10 专业版，Firefox 61.0.2 32-bit

- 类型：错误？建议？

打开PDF文件时，内置PDF插件无法自动加载：
先打开内置PDF插件，通过内置插件直接打开PDF是可用的，但直接打开PDF链接或本地PDF文件，Firefox依然将PDF加载到默认的PDF阅读器中。

**Comment by crimx** [comment]
你好，经测试 PDF 网页链接是没有问题的，请查看是否跟其它扩展冲突（Chrome 冲突了会在右上方显示，Firefox 不清楚）。另外本地文件链接貌似对 Firefox 无效，目前没有找到原因，只能从本扩展内部打开。

**Comment by chenxilong** [comment]
谢谢。我升级最新沙拉版本，并删除所有其他扩展后， PDF 网页链接已经可以正常打卡。
希望未来本地文件也能如chrome一样正常打开，chrome有“允许访问文件”这个选项，估计Firefox也有类似的权限选项，但默认没有开启。

**Comment by crimx** [comment]
有可能，Firefox 现在的支持还不是很完善，如快捷键也无法设置，等待其升级吧。

**Comment by byrChen** [comment]
请问现在还是这样吗？我也用的火狐，本地直接打开pdf不能划词，然后半天也不知道作者说的那个sala的pdf页面怎么打开。。。最后在pdf.js里的demo链接打开pdf才能划词，建议在使用说明里添加 右键插件--在pdf阅读器中打开 的说明。
火狐本身内置了pdf.js，为什么从本地的就不行啊？是没给插件访问本地文件的权限吗？

**Comment by crimx** [comment]
PDF 的使用说明在下面……列举了入口以及 Firefox 说明。 https://github.com/crimx/ext-saladict/wiki#pdf

**Comment by byrChen** [comment]
嗯嗯知道了，主要是在 “Firefox 目前不支持本地路径拦截，可以在 Saladict 的 PDF 页面中按右上方的按钮打开本地文件。” 之前没看到Saladict的PDF页面入口...
那个“不支持本地路径拦截”是指直接打开就不能取词是吗？但本地打开也是用的火狐自带的pdf.js阅读器啊，我看了权限里面也没有 access local 之类的选项。

**Comment by crimx** [comment]
拦截本地路径然后 redirect 到 Saladict 自带的 PDF 阅读器。

**Comment by crimx** [comment]
> 但本地打开也是用的火狐自带的pdf.js阅读器啊，我看了权限里面也没有 access local 之类的选项。

既然是自带的自然有特殊待遇。

**Comment by byrChen** [comment]
谢谢作者了，很nice的插件

**Comment by copdips** [comment]
谢了， 原来是从自带的pdf阅读器里打开
