### ISSUE TITLE
谷歌翻译已经停止在中国大陆的服务

### ISSUE THREAD

**Issue by FredQSWang** [crimx/ext-saladict#1876]
## 设备信息
- 操作系统: [Window11] 
- 浏览器版本: [Edge106.0.1370.42] 
- 沙拉查词版本: [v7.20.0] 

## 请描述目前使用沙拉查词遇到什么不便

谷歌翻译已经停止在中国大陆的服务

## 理想情况下，沙拉查词应该怎么做

在中国大陆地区 删除 谷歌翻译 服务

## 额外信息

https://translate.google.cn/

**Comment by FredQSWang** [comment]
Also like [#1860](https://github.com/crimx/ext-saladict/pull/1860)

**Comment by leywey0129** [comment]
建议不要删除，因为有些使用VPN的照样可以使用些服务

**Comment by FredQSWang** [comment]
我知道了
感谢 @leywey0129 的建议
