### ISSUE TITLE
浏览器外划词不弹窗

### ISSUE THREAD

**Issue by bgm108** [crimx/ext-saladict#1879]
## 设备信息
- 操作系统: []  
- 浏览器版本: [] 
- 沙拉查词版本: [] 

Win10 
Microsoft Edge 版本 106.0.1370.47 (正式版本) (64 位)
v7.20.0
## 描述问题

浏览器外划词翻译不弹出面板

## 复现步骤

1. 打开word/PDF
2. 点击划词翻译，出现右下角翻译增量/划词窗口，但是不显示翻译面板
3.点击文本截图/触边翻译，出现截图窗口，截图完成后，没有后续响应

## 期待的正常行为

出现翻译弹窗

## 截图

![image](https://user-images.githubusercontent.com/115964028/196079391-66a57fd5-4665-4db0-86f7-6635e243934b.png)
![image](https://user-images.githubusercontent.com/115964028/196079625-5303634c-5a46-4895-a349-d3111f1a5a9b.png)

**Comment by crimx** [comment]
Edge 上配置全局快捷键了么？直接按快捷键是否能触发？

**Comment by bgm108** [comment]
Edge 全局快捷键不能触发，无任何反应

**Comment by crimx** [comment]
说明全局快捷键没设置成功，可能跟其它软件快捷键冲突了？可以设一个不常用的如 alt+ctrl+shift+L 这种。

**Comment by bgm108** [comment]
设置全局快捷键后，在独立窗口中搜索剪贴板内容有效 ，打开打开独立词典窗口有效，使用鼠标划词翻译开关无效，悬浮取词无效（不是快捷键冲突）





1152975561
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "crimx/ext-saladict"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月17日(星期一) 晚上8:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [crimx/ext-saladict] 浏览器外划词不弹窗 (Issue #1879)





 
说明全局快捷键没设置成功，可能跟其它软件快捷键冲突了？可以设一个不常用的如 alt+ctrl+shift+L 这种。

**Comment by crimx** [comment]
配合其它工具浏览器外使用应该按工具的文档说明设置相关功能的全局快捷键，一般是在独立窗口中搜索剪贴板内容。悬浮取词是在浏览器内使用的。

**Comment by bgm108** [comment]
在Quicker中重新安装动作，已恢复，感谢帮助




1152975561
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "crimx/ext-saladict"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月17日(星期一) 晚上9:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [crimx/ext-saladict] 浏览器外划词不弹窗 (Issue #1879)





 
配合其它工具浏览器外使用应该按工具的文档说明设置相关功能的全局快捷键，一般是在独立窗口中搜索剪贴板内容。悬浮取词是在浏览器内使用的。
