### ISSUE TITLE
生词本和anki联合

### ISSUE THREAD

**Issue by ytxcash** [crimx/ext-saladict#1882]
## 设备信息
- 操作系统: [Manjaro] 
- 浏览器版本: [Chrome Version 106.0.5249.119 (Official Build) (64-bit)] 
- 沙拉查词版本: [v7.2.0] 

## 请描述目前使用沙拉查词遇到什么不便

生词本和anki使用不方便，没有例句、没有音标、也没有释义

## 理想情况下，沙拉查词应该怎么做

查询时用了牛津英英和必应英汉，添加单词时把这两个词典的主要释义各自添加一列（最后附上完整释义的链接）

## 替代方案

暂无；大佬能提供下思路吗？？ 我想试着修改，如何改生词本、和anki模板这两方面

## 额外信息

暂无

**Comment by crimx** [comment]
沙拉查词的[设计](https://saladict.crimx.com/anki.html)遵循单一输入输出的原则，故不推荐填入与当前上下文不相关的释义。

如果你需要实现的话可以在这个添加生词本前的位置添加其它信息

https://github.com/crimx/ext-saladict/blob/663c16025929dd607f88305f80557c5f10975f60/src/content/redux/epics/index.ts#L96-L102

**Comment by ytxcash** [comment]
收到 我试试哈
