### ISSUE TITLE
Mac系统chrome浏览器很多时候划词取词无法显示Bing等词典的结果

### ISSUE THREAD

**Issue by montage0921** [crimx/ext-saladict#1888]
## 设备信息
- 操作系统: [macOS Monterey] 
- 浏览器版本: [Chrome Version 106.0.5249.119] 
- 沙拉查词版本: [v.7.20.0] 

## 描述问题
在浏览器划词取词时Bing词典经常不显示任何内容。此现象在划取非常规单词（诸如人名，地点，电影名等）时经常出现。划取普通词汇（例如”write","preview")等时则不会出现。

## 复现步骤

1. 打开某一网页（如科比（Kobe Bryant）的英文维基百科）......
2. 划取单词 "Kobe Bryant"
3.单词面板出现
4. 问题出现：Bing词典，urban dictionary词典这几栏不显示任何内容。有道词典则正常现实

## 期待的正常行为

正常情况下Bing词典在划取非常规单词时非常好用,可以显示网络搜索结果。

## 截图

<img width="785" alt="Screen Shot 2022-10-25 at 6 52 47 PM" src="https://user-images.githubusercontent.com/76137011/197896939-0bbbd597-7725-4643-855b-41205a2f9260.png">

**Comment by crimx** [comment]
https://cn.bing.com/dict/search?q=Kobe%20Bryant 你可以点击词典标题打开源网页，没有那就是没有了。不同的词典有不同的侧向，所以沙拉查词才会做成聚合的方式。
