### ISSUE TITLE
单词本自动恢复

### ISSUE THREAD

**Issue by laerhu** [crimx/ext-saladict#189]
平台：win10，Chrome 68.0.3440.106
功能：单词本自动恢复
类型：建议
重现：删除并重装插件
期待：找回卸载之前的单词本内容
实际：误删插件并重装后无法恢复之前的单词本内容
补充：希望能像Tampermokey一样提供保存数据到云盘的选项，谢谢！

**Comment by crimx** [comment]
你好，因浏览器同步容量有限，故没有花费时间实现单词本同步。以后会加入 Anki 有道 和 扇贝 同步。

**Comment by laerhu** [comment]
谢谢你的及时回复！还有2个问题想要请教
1. 丢失的单词本怎样找回？本地缓存文件（瞎猜的）……
2. 同步到有道之后还能保存saladict的特色字段吗？能否将文件导出到Google Drive，在插件选项页面给出登录谷歌账号并手动管理备份的功能，就像Tampermonkey一样。

**Comment by crimx** [comment]
1. 卸载的话应该是无法恢复了。非常抱歉。
2. 是的！ Google Drive 等支持会逐步添加。单枪匹马进度有点慢请体谅。

**Comment by crimx** [comment]
实现完 WebDAV 同步已经失去了实现 Google Drive 的兴趣。如果有其他人愿意实现欢迎 reopen 这个 issue 。
