### ISSUE TITLE
有没有办法从其它的扩展调用沙拉查词的翻译功能？

### ISSUE THREAD

**Issue by yuyang0** [crimx/ext-saladict#1892]
比如我用surfingkeys，所以一般都是键盘操作不用鼠标，但是沙拉查词似乎都需要鼠标点一下，所以想问下有没有办法通过js直接触发沙拉的查词功能？如果能得话就可以直接通过快捷键操作了。

**Comment by crimx** [comment]
可以设置[浏览器快捷键](https://saladict.crimx.com/manual.html#shortcuts)

**Comment by yuyang0** [comment]
需求其实和 #1155 是一样的，最好的方法还是沙拉把api暴漏出来，像[这里](https://developer.chrome.com/docs/extensions/mv3/messaging/#external)， 我看了下，好像有个todo，但是两年了没动静，至于另外一个方法就是模拟双击，但是我这半吊子js水平还没弄明白怎么弄。

**Comment by crimx** [comment]
主要是发现浏览器暴露 API 的方式可能用户有点难接，不同操作系统还不一样。最简单的方式是 Anki Connect 这种起个本地服务器，但我也没想好怎么设计比较方便接入。

**Comment by yuyang0** [comment]
沙拉查词是chrome上最好的翻译扩展，如果能把api暴漏出来应该可以玩出更多新花样，所以还是希望把这作为高优先级功能实现下，我目前用模拟双击的方法看起来也能work。

**Comment by crimx** [comment]
好的，我再想想
