### ISSUE TITLE
在quicker中使用，选了截图翻译的动作，面板里还是空白的

### ISSUE THREAD

**Issue by iceMagi** [crimx/ext-saladict#1896]
## 设备信息
- 操作系统: [win11] 
- 浏览器版本: [Chrome 107] 
- 沙拉查词版本: [7.20] 

## 描述问题

我装了quicker+沙拉查词的动作，昨天还能正常使用，今天截图翻译之后，跳出沙拉查词的空白窗口，但是里面没有我截图的句子的翻译。

## 复现步骤

quicker面板→文本截图翻译→空白窗口

## 期待的正常行为

在弹出的窗口里辨认出我截图的内容，并且进行翻译

## 截图

![image](https://user-images.githubusercontent.com/64744343/200728427-a2d04a45-757c-45d0-9587-97a3fc851f0a.png)

**Comment by crimx** [comment]
查词框输入文字能翻译吗？如果可以的话应该是 Quicker 插件那边没有把文字传进来。

**Comment by iceMagi** [comment]
> 查词框输入文字能翻译吗？如果可以的话应该是 Quicker 插件那边没有把文字传进来。

可以的，排查之后应该是插件的问题，谢谢解答
