### ISSUE TITLE
沙拉查词插件与edge浏览器最新版本“edge栏”功能冲突

### ISSUE THREAD

**Issue by niuble6** [crimx/ext-saladict#1899]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Microsoft Edge 107.0.1418.42 (正式版本) (64 位)] 
- 沙拉查词版本: [7.20] 

## 请描述目前使用沙拉查词遇到什么不便

沙拉查词插件与edge浏览器最新版本“edge栏”功能冲突。

## 理想情况下，沙拉查词应该怎么做

建议优化以兼容此功能，以便两者均能正常使用。

## 额外信息
![image](https://user-images.githubusercontent.com/99662730/201358228-d3f59fec-813b-4b84-94b4-3f9de170bdb0.png)
可以通过在edge浏览器最新版本地址栏中访问 edge://settings/edgeBar 来查看此功能页面，访问
https://go.microsoft.com/fwlink/?linkid=2166395 查看更多介绍。

**Comment by crimx** [comment]
Duplicate of #1870

**Comment by niuble6** [comment]
你好，你错误理解了我的反馈。
本人提到的功能名称为“edge栏”，可以在edge浏览器的设置左侧第10个选项查找到，不是选中文字后的弹出图标。
你可以通过在edge浏览器最新版本中中访问edge://settings/edgeBar来查看此功能页面，访问https://go.microsoft.com/fwlink/?linkid=2166395查看更多介绍。

edge浏览器“设置页面>>edge栏”显示：Microsoft Edge 栏已关闭，因为当前配置文件使用的一个或多个扩展存在冲突。
下方列出冲突的扩展是“沙拉查词”。

**Comment by niuble6** [comment]
> Duplicate of #1870

你好，你错误理解了我的反馈。
本人提到的功能名称为“edge栏”，可以在edge浏览器的设置左侧第10个选项查找到，不是选中文字后的弹出图标。
你可以通过在edge浏览器最新版本中中访问edge://settings/edgeBar来查看此功能页面，访问https://go.microsoft.com/fwlink/?linkid=2166395          查看更多介绍。

edge浏览器“设置页面>>edge栏”显示：Microsoft Edge 栏已关闭，因为当前配置文件使用的一个或多个扩展存在冲突。
下方列出冲突的扩展是“沙拉查词”。

**Comment by crimx** [comment]
#1708 这个？

**Comment by niuble6** [comment]
也不是这个。这是我的截图：

![image](https://user-images.githubusercontent.com/99662730/201356761-2c70f8af-a898-4d17-921e-d8f8c71a291b.png)

你可以通过在edge浏览器最新版本地址栏中访问 edge://settings/edgeBar 来查看此功能页面，访问
https://go.microsoft.com/fwlink/?linkid=2166395 查看更多介绍。

此功能可能尚未向所有用户提供，我在另一台电脑上没看到此功能。

**Comment by niuble6** [comment]
你可以通过在edge浏览器最新版本地址栏中访问 edge://settings/edgeBar 来查看此功能页面，访问
https://go.microsoft.com/fwlink/?linkid=2166395     查看更多介绍。

此功能可能尚未向所有用户提供，我在另一台电脑上没看到此功能。

**Comment by niuble6** [comment]
你认为此问题与启动增强的冲突，是同一问题吗？我浏览器“启动增强”与沙拉查词不冲突，但是“edge栏”与沙拉查词冲突。
此问题似乎不是“a duplicate of [#1614](https://github.com/crimx/ext-saladict/issues/1614) [on Mar 23]”。

https://github.com/crimx/ext-saladict/issues/1693

**Comment by crimx** [comment]
它没有说明如何冲突，看不出来是什么配置会导致冲突？

**Comment by crimx** [comment]
> 你可以通过在edge浏览器最新版本地址栏中访问 edge://settings/edgeBar 来查看此功能页面，访问
https://go.microsoft.com/fwlink/?linkid=2166395 查看更多介绍。


我这边的 Edge 也没有这个功能

**Comment by crimx** [comment]
<img width="461" alt="image" src="https://user-images.githubusercontent.com/6882794/201568129-270b0c9c-b49e-4be9-8c43-5d823afb2cc7.png">

但有一个类似的叫 sidebar 的功能默认开启了，不知道是不是同一个。

**Comment by niuble6** [comment]
![捕获](https://user-images.githubusercontent.com/99662730/201590842-f1da6b3f-1420-4ae1-8c08-3e130823c69a.JPG)
不是同一个功能，edge栏会在之后更新中出现。
这个edge栏实际上就是能在电脑上浏览手机版本网页，edge栏与沙拉查词的“独立查词窗口”有一些共性，它可以在edge浏览器主窗口关闭后继续常驻在桌面右侧，也可以悬浮在别的应用之上（如同一个手机浏览器），这个图是把沙拉查词禁用之后截的。

具体冲突原因，我也不太清楚，得问微软。我把沙拉查词的独立查词窗口功能选项关了还是显示冲突。
