### ISSUE TITLE
自动填充翻译反馈

### ISSUE THREAD

**Issue by crimx** [crimx/ext-saladict#190]
## 背景

在 #117 中解释过，本扩展推荐的使用方式是辩证地对比多个词典，并手动输入翻译以保证记忆的准确性和有效性。

然而考虑到太多用户反馈希望自动填充，本着存在即合理的原则，本扩展对此做了一些探索与尝试。

## 实现

首先任何直接提供第一个查词结果的词典都是不负责任的。这样的功能只是作撑门面之用，于用户理解单词是没有丝毫帮助的。

更好些的如[深蓝英文字幕助手](https://github.com/studyzy/LearnEnglishBySubtitle)，利用 NLP （自然语言处理）引擎猜测出词性，再从词典中取对应词性的第一条结果。然而目前尚未有成熟的面向浏览器的 NLP 引擎。

最后采用了一个折衷的方式，对上下文进行翻译，相当于间接利用了翻译引擎对词义进行猜测，再通过多个翻译引擎结果进行对比，最大限度保留了单词在上下文中的意思。

对于关闭了红心单词编辑框的用户，翻译会自动添加保存。

## 反馈

本功能在 v6.11.0 添加，欢迎反馈使用效果。如有更好的建议也欢迎交流！ :dancing_women:

**Comment by DerekTso** [comment]
@crimx 
能否提供一个设置，让用户自己决定是否开启 [自动填充翻译] 呢？
1. 现在提供了三个上下文的自动翻译，有时候感觉有点乱
2. 红心单词编辑的时候是有换行显示的，但是在生词本中就没有换行，也就更乱了。

希望：
1. 提供一个是否开启 [自动填充翻译] 的选项
2. 提供一个开启哪个翻译功能的选项，比如我只想开启 google 翻译
3. 生词本中的文本也换行显示，如果支持 markdown 就最好了

谢谢~

**Comment by crimx** [comment]
选择翻译引擎请查看设置。生词本的换行我看看，这里生词本主要是为了管理单词，使用建议导出到专门的应用中。

**Comment by DerekTso** [comment]
1. 翻译引擎问题解决了。
2. 划词翻译的时候，选中的某个单词的一部分时，它会出现三次
比如，我选中 swaddle 而不是选中 **swaddled**，它就会重复出现三次，像这样 swaddleswaddleswaddle**d**
![image](https://user-images.githubusercontent.com/10363328/55929562-d8bdcd00-5c4f-11e9-8f75-f95f2398852c.png)

**Comment by crimx** [comment]
这应该是该网页为了实现某种布局效果而隐藏的，无解。跟本 issue 无关的问题请新开 issue 反馈。
