### ISSUE TITLE
AnkiDroid中，学习单词卡时不能显示输入框，提示： 未知字段 cq-1:ContextCloze

### ISSUE THREAD

**Issue by jaychoww** [crimx/ext-saladict#1904]
## 设备信息
- 操作系统: [win 11][android 11] 
- anki[2.1.54 QT5] with plugins [AnkiConnect | Minimize to tray] （pc)
- ankiDroid from google play [2.15.6] (android)
- 浏览器版本: [Chrome107.0.5304.107] 
- 沙拉查词版本: [v7.20.0] 

## 描述问题
在win 11上的chrome开启anki 同步功能，手机安装anki，在PC上生成的单词卡能正常同步到手机；在PC的anki上学习单词卡功能正常，能输入单词并提示正确或者错误，但是在安卓手机上的学习功能不能正确显示输入框，无法输入

## 期待的正常行为

期待手机上的单词卡能正常显示输入框

## 截图

PC上的正确界面：
![image](https://user-images.githubusercontent.com/4192339/201805835-f30a5df2-3bce-4a66-a6f0-371334713824.png)
Android上不能显示输入框：
![image](https://user-images.githubusercontent.com/4192339/201805711-6e016b19-9c5e-49fe-a174-9dbe162be3fd.png)

**Comment by crimx** [comment]
![Screenshot_2022-11-15-10-18-28-250-edit_com.ichi2.anki.jpg](https://user-images.githubusercontent.com/6882794/201810396-8d2b924a-b69a-450d-9063-1f066b7d93c2.jpg)

我这边用沙拉查词生成的卡片模板是没问题的，可能是卡片模板被修改过了？

**Comment by jaychoww** [comment]
> ![Screenshot_2022-11-15-10-18-28-250-edit_com.ichi2.anki.jpg](https://user-images.githubusercontent.com/6882794/201810396-8d2b924a-b69a-450d-9063-1f066b7d93c2.jpg)
> 
> 我这边用沙拉查词生成的卡片模板是没问题的，可能是卡片模板被修改过了？

你用的也是ankiDroid么

**Comment by crimx** [comment]
截图是 Ankidroid

**Comment by crimx** [comment]
你可以通过左上角菜单的卡片浏览器看一下卡片的 `ContextCloze` 字段，看看里面挖空地方的源文本是什么，一般长 `{{c1::xxx}}` 这样。

**Comment by jaychoww** [comment]
挖空的内容就是{{c1::throttling}}， throttling就是我要记的单词
![33abea9f89f54284fa7fc7e2b1a1949](https://user-images.githubusercontent.com/4192339/201863228-26110cbe-41fe-42c1-8f8d-3e3bf69f290b.jpg)

**Comment by crimx** [comment]
那说明卡片内容没有问题，你看看卡片配置。主界面右上角菜单，笔记类型，长按 Saladict Word，编辑卡片，看看是不是这样的？
![Screenshot_2022-11-15-16-18-59-914-edit_com.ichi2.anki.jpg](https://user-images.githubusercontent.com/6882794/201866716-9b867763-eaf4-46d4-b48b-2d813fa4d23d.jpg)

**Comment by jaychoww** [comment]
![image](https://user-images.githubusercontent.com/4192339/201880726-4afeb865-dec1-430e-bc40-0195fbb047c2.png)
这里做了转义？

**Comment by jaychoww** [comment]
我把这{{{{改成{{就可以了

**Comment by zyichang** [comment]
> 我把这{{{{改成{{就可以了

你是我的神！


> 那说明卡片内容没有问题，你看看卡片配置。主界面右上角菜单，笔记类型，长按 Saladict Word，编辑卡片，看看是不是这样的？ 

神！
