### ISSUE TITLE
产品很好用，但是能不能不要每次更新都打开一个浏览器标签哇，有点烦躁哇

### ISSUE THREAD

**Issue by JackPanda8** [crimx/ext-saladict#191]
产品很好用，但是能不能不要每次更新都打开一个浏览器标签哇，有点烦躁哇

**Comment by crimx** [comment]
1. 操作系统？
1. 浏览器及版本？
1. 是否通过浏览器背后自动升级扩展？
1. 打开的页面是什么？

**Comment by crimx** [comment]
新版本使用不同的方式。应该不会再有这样的问题。如有欢迎继续反馈。
