### ISSUE TITLE
自动发音功能，选剑桥词典的英音，不会自动发音

### ISSUE THREAD

**Issue by Lukikay** [crimx/ext-saladict#192]
- 平台：Windows 10 1803, Chrome 68.0.3440.106

- 类型：小bug

- 自动发音

- 重现：自动发音功能，选剑桥词典的英音，不会自动发音，选别的词典工作正常。因为剑桥的词库更大，所以希望能用剑桥的自动发音

-另外，这个插件太好用了！！

**Comment by crimx** [comment]
谢谢反馈。会在下个版本更新。
