### ISSUE TITLE
triple Ctrl呼出词典时不自动选中了？

### ISSUE THREAD

**Issue by Sraw** [crimx/ext-saladict#193]
- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）
Linux X64 Chrome 68

- 类型错误？建议？
probable bug.

- 重现：提供详细的可重现问题的操作。
Triple Ctrl呼出词典，开启自动查剪贴板选项。

- 期待：理想情况下扩展应该怎么做？
查词内容自动选中，方便直接修改。
这是之前版本的行为。

- 实际：客观描述扩展实际上做了什么。
查词内容未自动选中，修改困哪，需要手动全选。

这是重新设计了这个功能还是bug？如果是重新设计的话，能添加一个选项来控制这个行为吗？

**Comment by crimx** [comment]
你好，这个是最新版加速后的 bug ，太快了输入框还没反应过来哈哈 😄。已经修复了，但还没有发布新版本。

**Comment by Sraw** [comment]
Thanks.

**Comment by Sraw** [comment]
你好，经过确认，在相同的环境下，6.13.3版本的词典依旧无法选中。

我稍微测试了一下，某些网页上呼出词典非常缓慢，需要大约1~2秒的时间，此时单词是会被选中的。譬如gmail页面（有时gmail页面会无法呼出词典，包括任何形式的呼出，暂时无法稳定复现）。
在大部分网站上，呼出词典相当迅速，但是单词不会被自动选中。

**Comment by Sraw** [comment]
抱歉，环境稍微发生了一点变化，chrome升级至了69.0版本

**Comment by crimx** [comment]
感谢反馈。请问右上弹框会自动选中么？

Google 的一些产品都是非常庞大复杂，需要在客户端进行大量计算，所以有可能是资源暂时被占用了。我试了一下 Gmail 没有发现延时。

**Comment by crimx** [comment]
嗯，那应该是面板没有及时显示造成的。目前我是直接加了 200 毫秒延时再选中。我看看能不能找到更精确的钩子。

无法呼出这个原因很复杂，特别是 G 系产品经常直接屏蔽浏览器的接口自行造轮子。我又试了几封邮件还是没有遇到问题。方便的话你也可以转发过来我试试看。

另外提一下，只有 triple ctrl 和 右上弹框 出现的面板会自动选中。划词出现的会保留原来的焦点。

**Comment by crimx** [comment]
已换用更精确的方式判断选中。

**Comment by Sraw** [comment]
你好，貌似issue不能再reopen了，不过在最新的6.15.3版本中，triple ctrl依旧无法自动选中...右上弹框界面一直很正常。
Really hope it can be solved.

我不禁有点怀疑是不是自己记忆出现了错误，记得某个改版之前，是一直可以自动选中的来着。

**Comment by crimx** [comment]
目前的设定是在面板没有词典结果或者是右上弹框的时候自动选中。应该是自动查词干扰了判断，我再给 triple ctrl 情况加个标记。
