### ISSUE TITLE
etymonline无法显示

### ISSUE THREAD

**Issue by caerlie** [crimx/ext-saladict#194]
- 平台：Win7 MacOS Chrome

- 类型：etymonline不显示

- 划词模式？默认设置

- 重现：初始化设置 添加etymonline词典

- 期待：etymonline显示正常

- 实际：显示为空 ，但是通过点击etymonline链接可以正常链接到相关搜索结果

**Comment by crimx** [comment]
感谢反馈，稍后检测原因

**Comment by crimx** [comment]
找到问题了， Etymonline 更新了，Saladict 会在下个版本跟上。

**Comment by caerlie** [comment]
给力给力！

PS：这个插件是目前用到过的最给力的英文APP！科技是提高生产力的唯一工具被体现的淋漓尽致！感恩！

**Comment by crimx** [comment]
谢谢美言哈哈

**Comment by crimx** [comment]
已发布
