### ISSUE TITLE
可以将沙拉查词的独立窗口的WM_CLASS类名修改与firefox本身不同的类名吗？

### ISSUE THREAD

**Issue by awarewen** [crimx/ext-saladict#1947]
**Is your feature request related to a problem? Please describe.**

https://user-images.githubusercontent.com/53365857/212639221-96a03d8d-f539-4a29-bd9f-b482fa17be5f.mp4

由于firefox自身的WM_CLASS名称和独立查词的窗口类名相同，wm的窗口合成器（picom）没办法将firefox本身和独立查词的窗口区分出来。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by crimx** [comment]
这个扩展不能控制的，你能通过窗口标题判断吗？`WM_NAME`？

**Comment by awarewen** [comment]
好，这个并不太影响。谢谢回复。
