### ISSUE TITLE
能自己实现整个网页的双语显示吗？而不是集成彩云小译

### ISSUE THREAD

**Issue by who10086** [crimx/ext-saladict#1948]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: []

**Comment by crimx** [comment]
可以的，你要实现么？

**Comment by who10086** [comment]
> 可以的，你要实现么？

当然是希望你们实现的，毕竟是有这个需求才说的

**Comment by crimx** [comment]
这个适配工作量非常大，我一个人是不太敢挖这个坑。你可以装小译的插件使用他们最新的版本，做得还可以，特别是对小说网站的适配。

**Comment by who10086** [comment]
> 这个适配工作量非常大，我一个人是不太敢挖这个坑。你可以装小译的插件使用他们最新的版本，做得还可以，特别是对小说网站的适配。

是的，他家的翻译设配做的不错，基本不会改变页面的布局，专业名词也能识别，问题就是价格贵了点，在其他翻译全免费的情况，多了一个双语对照的功能就158/年有点无法接受，6-8元/月我还会考虑下。

**Comment by Chenm4** [comment]
> 

请问你现在有什么替代方案吗
