### ISSUE TITLE
天天给我弹更新消息，烦不烦啊？

### ISSUE THREAD

**Issue by Num426** [crimx/ext-saladict#195]
有更新了不起是吗，我根本就不在乎你又更新了什么东西，请不要一周弹好几次系统级别的通知告诉我你更新了，每次弹都是用一个版本更新的内容。你更新了就更新了，请安静一点，好吗？这点破事就别调用系统通知了OK？

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）

Windows 10 1803，chrome 版本 68.0.3440.106（正式版本） （64 位）

**Comment by Num426** [comment]
刚刚态度不太好，跟作者说声抱歉。但是我真的不希望在我使用其他程序的时候你调用系统通知告诉我你有更新了，更新都是自动更新的，通知一次就好了，别一直通知。

**Comment by crimx** [comment]
你好，最近有时间更新比较勤而已。一般是一个月更新不到一次。
