### ISSUE TITLE
能否在划词翻译前先判断是否是中文

### ISSUE THREAD

**Issue by 390620652** [crimx/ext-saladict#1958]
## 设备信息
- 操作系统: [windows11] 
- 浏览器版本: [edge最新版] 
- 沙拉查词版本: [v7.20.0] 

## 请描述目前使用沙拉查词遇到什么不便

每次划选内容都触发小图标，影响阅读。我们平时用的比较多是其他语言翻译成中文，很少把中文翻译成其他语言，很多划词的操作并不是要查词。

## 理想情况下，沙拉查词应该怎么做

划词后先判断内容是否是中文（或可配置的语言），如果是则不用显示划词翻译的小图标

## 替代方案

只对配置的语言比如英语启用划词翻译

**Comment by 390620652** [comment]
而且为什么关闭了划词翻译后，右键的沙拉查词也失效了。我只是单纯不想老是显示那个小图标

**Comment by 390620652** [comment]
而且为什么关闭了划词翻译后，右键的沙拉查词也失效了。我只是单纯不想老是显示那个小图标。如果右键跟划词是关联的，那右键翻译还有什么意义？

**Comment by crimx** [comment]
你可以在设置的「查词习惯」「普通划词」关闭「显示图标」。

**Comment by 390620652** [comment]
thank you
