### ISSUE TITLE
查词后在最上层出现多余的？下拉框

### ISSUE THREAD

**Issue by caerlie** [crimx/ext-saladict#196]
== 提交前将本行及已上内容删除，并填充以下模板 ==

- 平台：Win7 Chrome

- 类型：我不太确定是否是新的feature还是回退bug
              如果是新的fearture的话，请见谅。

- 划词模式？默认设置。

- 重现：如下图
搜索结果里面出现了①这个下拉框图标，但是我的词典第一个是vocabulary，这个图标出现在vocabulary的结果之上。点开这个图标的话，出现②

![bug1](https://user-images.githubusercontent.com/8187463/44971220-b6642280-af8f-11e8-9aa7-fd314c20f1ba.PNG)

- 期待：应该没有这个下拉框，直接就是首个词典结果，也就是vocabulary的结果。

**Comment by crimx** [comment]
你好，这是昨天发布的 feature ，许多用户请求多行编辑。

**Comment by caerlie** [comment]
感谢回复 了解了。

good feature！
