### ISSUE TITLE
沙拉查词无法运行

### ISSUE THREAD

**Issue by DuckDeng** [crimx/ext-saladict#1960]
## 设备信息
- 操作系统: [Win0] 
- 浏览器版本: [版本 109.0.5414.120] 
- 沙拉查词版本: [7.20.0] 

## 描述问题

在chrome应用商店安装后无法使用，设置页面打开，查词窗口打不开。

## 期待的正常行为

正常弹出设置页面和查词窗口

## 截图

![image](https://user-images.githubusercontent.com/64295725/218379312-e4c76de3-4884-4ba8-a6c0-ca9c2b69c732.png)
![image](https://user-images.githubusercontent.com/64295725/218379392-0e263c43-0733-4055-b543-73a1d53823e8.png)

## 额外信息

浏览器F12控制台输出了一下错误
![image](https://user-images.githubusercontent.com/64295725/218379704-857c6cd3-e0d5-4a78-bc40-90a3e942a3e8.png)

**Comment by crimx** [comment]
提示 Chrome 的某些数据文件出问题。可能用了清理软件什么的导致文件损坏或被占用，也可能是安装浏览器失败。可以试试重启电脑，或者重新安装浏览器试试。

**Comment by DuckDeng** [comment]
重新安装chrome后问题依旧
![image](https://user-images.githubusercontent.com/64295725/219362159-38c24847-3fea-4189-b04e-eeb7f40d73cb.png)

**Comment by crimx** [comment]
Chrome 的数据持久化在 levelDB 上，这个报错是 levelDB 无法创建文件。一般就是上面提到的情况。我没查到具体这些文件在什么目录下，要是重装浏览器不成功很可能这个目录下的文件还是存在问题。

**Comment by DuckDeng** [comment]
卸载重装后恢复正常了，感谢帮助
