### ISSUE TITLE
生词本有本地文件可以复制到另一台电脑吗？

### ISSUE THREAD

**Issue by lj123454321** [crimx/ext-saladict#1965]
## 设备信息
- 操作系统: [Windows 11] 
- 浏览器版本: [Chrome 109.0.5414.121] 
- 沙拉查词版本: [7.20.0] 

## 请描述目前使用沙拉查词遇到什么不便

生词本有本地文件可以复制到另一台电脑吗？
我还没来得及配置webdav，旧电脑就坏了，只有硬盘还可以插硬盘盒里打开。
但是我不清楚生词本本地文件的路径。

## 理想情况下，沙拉查词应该怎么做

弄清楚生词本本地文件的路径。

**Comment by crimx** [comment]
生词是存在 Chrome IndexedDB 上。

- 打开 Chrome Profile 目录。
  - Windows 上应该是 `%LocalAppData%\Google\Chrome\User Data\`
  - Linux `~/.config/google-chrome/`
  -  macOS `~/Library/Application\ Support/Google/Chrome/`
- 如果你是默认用户应该在 `default` 目录下，否则就是你的账户名。
- 打开 `IndexedDB` 目录，找到 `chrome-extension_cdonnmffkdaoajfknoeeecmchibpmkmg_0.indexeddb.leveldb` 目录（其中 `cdonnmffkdaoajfknoeeecmchibpmkmg` 是沙拉查词的 id），里面就是沙拉查词生词本的数据。

**Comment by lj123454321** [comment]
> 生词是存在 Chrome IndexedDB 上。
> 
> * 打开 Chrome Profile 目录。
>   
>   * Windows 上应该是 `%LocalAppData%\Google\Chrome\User Data\`
>   * Linux `~/.config/google-chrome/`
>   * macOS `~/Library/Application\ Support/Google/Chrome/`
> * 如果你是默认用户应该在 `default` 目录下，否则就是你的账户名。
> * 打开 `IndexedDB` 目录，找到 `chrome-extension_cdonnmffkdaoajfknoeeecmchibpmkmg_0.indexeddb.leveldb` 目录（其中 `cdonnmffkdaoajfknoeeecmchibpmkmg` 是沙拉查词的 id），里面就是沙拉查词生词本的数据。

谢谢，解决了，复制到另一台电脑上能正常读取生词本。
