### ISSUE TITLE
划词后结果未自动添加到搜索框

### ISSUE THREAD

**Issue by caerlie** [crimx/ext-saladict#197]
== 提交前将本行及已上内容删除，并填充以下模板 ==

平台：Win7 Chrome

类型：我不太确定是否是新的feature还是回退bug
如果是新的fearture的话，请见谅。

划词模式？默认设置。

重现：重复选词后，搜索框里面的内容不能同步的变化，
          如下图，①的内容，没有随选定的词的变化而同步变化，一直保持第一次的搜索状态。
          好像以前的版本，还会把光标自动focus到搜索框上。
          PS：这个自动同步划词到搜索栏的的feature对我来说很有用，例如，
          搜索到multimedia后，我想知道其中的部门词根或者其变体，只需要通过键盘，稍加编辑即，然后Enter即可搜索，现在，我需要首先复制在编辑，或者一个一个字母敲进去才可以。（当然如果这里是特意的feature更改的话，也是能适应的哈）

![but2](https://user-images.githubusercontent.com/8187463/44971591-21fabf80-af91-11e8-8235-47e16b16aeff.PNG)

- 期待：自动同步划到的词到搜索栏，并focus到搜索栏

**Comment by crimx** [comment]
已修复
