### ISSUE TITLE
句子过长无法翻译，只会显示前半部分

### ISSUE THREAD

**Issue by youqugit** [crimx/ext-saladict#1975]
## 设备信息
- 操作系统: [Win11]
- 浏览器版本: [edge] 
- 沙拉查词版本: [v7.20.0] 

## 额外信息

![image](https://user-images.githubusercontent.com/55398814/221515521-12a9257f-edab-4c78-899e-64d530be6555.png)

**Comment by crimx** [comment]
Duplicate of #1893
