### ISSUE TITLE
 thank u

### ISSUE THREAD

**Issue by waihoyu** [crimx/ext-saladict#198]
This tool is very usefull for me , thank u for your contribution.!
By the way , adding words to favorites ，its can repeat to add !! You can optimize it.

- 平台：win7 &&chrome 68.0.3440.106

- 类型：错误？建议？

- 划词模式: none

- 重现：none

- 期待：If this is a bug, please modify it

- 实际：none

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
Hi thanks for your kind word. And this is not a bug. One word may have different contexts which produce different meanings. 

You can switch off showing the word editor. And it will work as expected.
