### ISSUE TITLE
在ubuntu 20.04 firefox上划词无法使用

### ISSUE THREAD

**Issue by prexhu** [crimx/ext-saladict#1992]
## 设备信息
- 操作系统: [Ubuntu20.04] 
- 浏览器版本: [Firefox 110.0.1+build2-0ubuntu0.20.04.1] 
- 沙拉查词版本: [v7.11.0] 

## 描述问题
划词之后，翻译框内很长时间不显示
但是翻译框上方的搜索栏可以查找单词

## 复现步骤

1. 选中文本
2. 鼠标放置在划词logo上，翻译框展开
3. 一直无翻译显示

## 期待的正常行为

有翻译选项出现

## 截图

![image](https://user-images.githubusercontent.com/96912272/224909013-daa4b5b1-052f-4061-ad1f-3c24803edafc.png)

**Comment by crimx** [comment]
看看是不是这个问题 #1985

**Comment by prexhu** [comment]
> 看看是不是这个问题 #1985

谢谢，已解决

**Comment by crimx** [comment]
Duplicate of #1985
