### ISSUE TITLE
建议增加chatGPT的API接口，提升翻译质量

### ISSUE THREAD

**Issue by laozui** [crimx/ext-saladict#1994]
已经有基于chatGPT的翻译扩展出现（包括分析、汇总和代码分析）。但界面和使用友好性上，远不如沙拉查词。希望沙拉查词能提供基于chatGPT的翻译选项，那就太棒了。

https://github.com/yetone/openai-translator

**Comment by bbcvc** [comment]
#1972

**Comment by crimx** [comment]
Duplicate of #1972
