### ISSUE TITLE
希望能够添加chatgpt翻译窗口

### ISSUE THREAD

**Issue by felinae99** [crimx/ext-saladict#1997]
## 设备信息
- 操作系统: [Windows11] 
- 浏览器版本: [Edge111.0.1661.41] 
- 沙拉查词版本: [7.20.0] 

## 请描述目前使用沙拉查词遇到什么不便

无chatgpt翻译接口

## 理想情况下，沙拉查词应该怎么做

目前chatgpt4的翻译功能已经非常强大，能不能在沙拉查词中加入chatgpt翻译接口，API可以由个人自己填写

## 替代方案

无

## 额外信息

插件“OpenAI Translator”已经实现了相关功能，希望沙拉查词可以加入该功能

**Comment by zmm147** [comment]
同求>>>

**Comment by kevinzhao2233** [comment]
同求

**Comment by tomatolike-self** [comment]
chatgpt的翻译太好了，另外这个需求已经提过了，也已经被添加到功能请求中了。

**Comment by zgpnuaa** [comment]
同求+1

**Comment by crimx** [comment]
Duplicate of #1972
