### ISSUE TITLE
Firefox浏览器调用api翻译接口,无法翻译

### ISSUE THREAD

**Issue by GU023** [crimx/ext-saladict#1999]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Firefox111] 
- 沙拉查词版本: [7.11.0] 

## 描述问题

调用了腾讯,百度,有道的翻译api接口,火狐浏览器的全部翻译不了,但是edge浏览器使用这些接口能正常翻译

## 复现步骤

firefox浏览器
![图片](https://user-images.githubusercontent.com/106470916/225827239-70805afa-7c55-44a6-a90d-c8b286083554.png)
edge浏览器
![图片](https://user-images.githubusercontent.com/106470916/225827439-a24af740-94ca-43d0-b31d-5d8403e21b07.png)
两个浏览器调用相同api
![图片](https://user-images.githubusercontent.com/106470916/225827597-291e8a57-4923-4a9a-b794-d5f30747ed64.png)

## 期待的正常行为

火狐浏览器正常翻译

**Comment by wayne3602** [comment]
同样遇到了这个问题

**Comment by wayner6** [comment]
我没有使用api，一样无法调用，同样的，在edge和chrome都可以正常使用

**Comment by chenyue404** [comment]
一样，可能火狐更新了什么东西吧。控制台报错`Content Security Policy: 页面设置阻止读取位于 eval 的一项资源("script-src")。`

**Comment by cangzhouyuhe** [comment]
+1，我是在chrome中，其他翻译插件可以使用彩云小译的网页翻译，但沙拉查词不能。
沙拉查词7.20在Chrome111.0.5563.111，已经填写了彩云小译的token，还是无法网页翻译，如果选择登录彩云小译，则网页翻译时显示需要充值。但是，使用“沉浸式翻译”这个插件，填写彩云小译的token后可以正常翻译网页。
注：token是一样的；已保存设置、重启浏览器。

**Comment by crimx** [comment]
Duplicate of #1985

**Comment by GTX10086Ti** [comment]
+1

**Comment by GU023** [comment]
> +1

主要是Firefox的插件市场沙拉查词版本低了，可以去找最新版本的沙拉查词
