### ISSUE TITLE
知网pdf加载失败；插件设置不知如何保存

### ISSUE THREAD

**Issue by hqyyqh** [crimx/ext-saladict#200]
- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）
`macos, win10` ， `Chrome`

- 类型：错误
1. **知网 pdf 查看出现问题**
禁用插件前，点击`下载 pdf`出现文件已损坏
![default](https://user-images.githubusercontent.com/38676455/45102492-730cde00-b160-11e8-8f59-e18115de98fd.gif)
禁用后可以正常点击下载
![default](https://user-images.githubusercontent.com/38676455/45102541-8fa91600-b160-11e8-928e-58fde0255bca.gif)

换成别的网站，比如 sciencedirect，可以正常加载pdf
![scidir](https://user-images.githubusercontent.com/38676455/45102628-b9623d00-b160-11e8-9f93-2a44dbd49f7e.gif)

不知道为什么知网的无法正常加载。

2. **如何保存设置** 
出现了上面的问题，我想禁用插件的浏览 pdf功能，但是发现更改了之后刷新网页或者重新打开又恢复了。不知道怎么保存设置
![pdf](https://user-images.githubusercontent.com/38676455/45102870-2d044a00-b161-11e8-9398-cf477919fd6e.gif)

**Comment by crimx** [comment]
扩展可以添加 PDF 黑名单，建议把知网添加进去。

另外改变设置应该会自动保存，页面上方出现绿条通知。你的录屏没有出现，应该是 Chrome 存储机制出了问题。这个原因未知，只能建议卸载重装。另外，系统版本 `macos, win10` 是什么意思？

**Comment by crimx** [comment]
另外我猜测还有可能是没有登录 Chrome 的原因？不清楚 Chrome 扩展同步存储在不登录的情况下是否可用。

**Comment by hqyyqh** [comment]
两个操作系统都试过，加载pdf同样的问题。
Chrome 已经登录了，网络也稳定

**Comment by crimx** [comment]
是的，知网会返回不正确的文件头所以 PDF 拦截会出问题。所以建议加入黑名单。

两个系统下都不能保存设置？

**Comment by hqyyqh** [comment]
设置保存的确是浏览器的问题，换了另一台电脑尝试没问题了。

插件设置黑名单后可以正常下载了。非常感谢

**Comment by crimx** [comment]
感谢反馈。能把屏蔽的网址发过来吗，我以后把它加入默认设定。

**Comment by hqyyqh** [comment]
*://*.cnki.net/*

**Comment by hqyyqh** [comment]
` *://*.cnki.net/*`

**Comment by crimx** [comment]
谢谢
