### ISSUE TITLE
CNKI翻译助手查词无结果

### ISSUE THREAD

**Issue by Amy-Liu-FW** [crimx/ext-saladict#2000]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Microsoft Edge 版本 110.0.1587.63 ] 
- 沙拉查词版本: [v7.20] 

## 描述问题

CNKI翻译助手查词无反应。
符合这个描述：网站可以打开而再次查词依然无结果的话，有可能是服务器更新了，请作反馈。
查词后从查词面板中点开的连接时是：https://dict.cnki.net/old/dict_result.aspx?scw=Added
网站现在可以正常查词的连接是：https://dict.cnki.net/index#

**Comment by crimx** [comment]
Duplicate of #1878
