### ISSUE TITLE
Fedora 37 下火狐浏览器无法使用

### ISSUE THREAD

**Issue by acyanbird** [crimx/ext-saladict#2001]
## 设备信息
- 操作系统: [Fedora 37] 
- 浏览器版本: [Firefox 110.0] 
- 沙拉查词版本: [7.11.0] 

## 描述问题

未调用任何 API 端口，输入查词&划词时所有词典都处在加载状态中，少数情况下可正常显示。已经阅读了 issue https://github.com/crimx/ext-saladict/issues/1999 以及 https://github.com/crimx/ext-saladict/issues/1985 ，尝试重置之后也无法修复。划词功能也同样失灵，选中词语之后没有 saladict 图标出现。切换情景模式时候同样报错 
QuotaExceededError: storage.sync API call exceeded its quota limitations.
应该和那两个issue的问题一样？

## 复现步骤

1. 安装saladict
2. 点击查词，输入一个单词或者选择一个单词

## 期待的正常行为

希望词典连接，能够正常加载。

## 截图

![Screenshot from 2023-03-22 15-29-46](https://user-images.githubusercontent.com/29391395/226831954-80e34f71-6d77-4e12-9690-1adcb2e3433c.png)

**Comment by WangJincheng4869** [comment]
我win11也有同样的问题，只能用有道词典
![图片](https://user-images.githubusercontent.com/41162158/227119005-d8a5fcc2-946c-49ac-8758-2199491b9d18.png)
![图片](https://user-images.githubusercontent.com/41162158/227119076-50fdef4e-4e9e-418c-bb88-531032c907f0.png)
![图片](https://user-images.githubusercontent.com/41162158/227119159-04beb5a4-f31e-49e0-a59c-17b86e350f91.png)

**Comment by Ayx03** [comment]
同样的问题，Windows 11 22H2，左边是 Edge 111 + Saladict 7.20.0 右边是 Firefox 111.0.1 + Saladict 7.11.0 (latest)
![图片](https://user-images.githubusercontent.com/75155322/227292498-cc560fe1-27bc-4f6a-b11e-21238e26dc65.png)

**Comment by konzonz** [comment]
操作系统: [windows 10 22H2]
    浏览器版本: [Firefox 原版（非中国版） 102.9 esr(64 位) ]
    沙拉查词版本: [v7.11.0]

我处理的方法步骤：
1，按这里的方法：https://github.com/crimx/ext-saladict/issues/956
2，然后重置设置

**Comment by acyanbird** [comment]
> ```
> 操作系统: [windows 10 22H2]
> 浏览器版本: [Firefox 原版（非中国版） 102.9 esr(64 位) ]
> 沙拉查词版本: [v7.11.0]
> ```
> 
> 我处理的方法步骤： 1，按这里的方法：#956 2，然后重置设置

通过输入 await browser.storage.sync.clear() 解决，感谢！

**Comment by Ayx03** [comment]
> ```
> 操作系统: [windows 10 22H2]
> 浏览器版本: [Firefox 原版（非中国版） 102.9 esr(64 位) ]
> 沙拉查词版本: [v7.11.0]
> ```
> 
> 我处理的方法步骤： 1，按这里的方法：#956 2，然后重置设置

这样会无法保存词典设置，修改后刷新还是默认的
