### ISSUE TITLE
firefox 划词翻译没有结果

### ISSUE THREAD

**Issue by vioulo** [crimx/ext-saladict#2008]
## 设备信息
- 操作系统: [Win11] 
- 浏览器版本: [firefox 111.0.1] 
- 沙拉查词版本: [7.11.0] 

## 描述问题

划词搜索没有结果，右上角的搜索框也没有结果。
我试了 Edge 是好的

## 复现步骤

多个页面都是同样结果

## 期待的正常行为

当然是能有翻译结果了

## 截图

![Snipaste_2023-03-31_09-09-39](https://user-images.githubusercontent.com/27475937/229000336-b5aaca30-70a6-407c-b716-3408cc39f811.png)

**Comment by Lovening** [comment]
作者好久没在火狐应用商店更新了，这个插件最新版本是7.20  火狐商店的是7.11  要不换个浏览器要不换个翻译插件吧

**Comment by crimx** [comment]
那大概明白为什么最近这么多用户反馈火狐问题了，它下架了最新几个版本，好像是因为沙拉查词带了 PDF.js 里面有对代码做了修改……

**Comment by crimx** [comment]
Duplicate of #1985

**Comment by operav** [comment]
> 那大概明白为什么最近这么多用户反馈火狐问题了，它下架了最新几个版本，好像是因为沙拉查词带了 PDF.js 里面有对代码做了修改……

我用火狐91时沙拉没问题，升级到110.0.1，页面划词翻译就用不了。
希望大佬能尽快解决吧...pdf到无所谓，就是看网页时遇到生词，划一下挺省事的。

**Comment by Eliot00** [comment]
现在划词完全用不了了
