### ISSUE TITLE
查词面板偶尔不会自动展开,尤其是首次查词

### ISSUE THREAD

**Issue by AiSY-Yang** [crimx/ext-saladict#201]
- 平台：Windows10 1803, Chrome 69.0.3497.81

- 类型：错误

- 查词面板

- 重现：
有时候会出现查词面板无法展开的情况,尤其是第一次查某个词的时候
![image](https://user-images.githubusercontent.com/20870087/45130807-c876d880-b1bc-11e8-9bf5-b1b3d75c5b77.png)
但是多试几次是可以查到结果的

尝试了关闭动画和开启动画均会出现无法展开的情况
可以通过点击两次右边的展开符号让面板展开
但是"freeCodeCamp"这个词怎么样都展不开面板

- 期待：理想情况下扩展应该怎么做？
当然是自动展开了
如果是因为网速问题的话可以有个loading动画,等查找到了在展开

**Comment by crimx** [comment]
嗯，再看来你的描述。应该是有道词典网页的问题。

**Comment by crimx** [comment]
有道词典网页连接确实有时不太稳定，下个版本我看看更换其它的 API 。

**Comment by AiSY-Yang** [comment]
![image](https://user-images.githubusercontent.com/20870087/45131430-84390780-b1bf-11e8-8662-6d03b5fd23a7.png)
当我第二次点击的时候就可以显示出结果了 是同一个单词 选中方式都是双击选中

**Comment by crimx** [comment]
是的。第一次连接失败了。打开网页也会有这样的情况。有道词典的网页年久失修。

**Comment by crimx** [comment]
我看看能不能抓取客户端用的页面，应该稳定些。

**Comment by AiSY-Yang** [comment]
![image](https://user-images.githubusercontent.com/20870087/45131903-8ef49c00-b1c1-11e8-9086-ad78cd866e85.png)
搜狗翻译也会出现无法展开的情况

**Comment by crimx** [comment]
搜狗一直是很稳定的，毕竟网页也是他们的主要入口。这个有可能是你的网络问题。

**Comment by caerlie** [comment]
我在用Vocabulary的时候，有的时候也会出现这样的问题
应该也是您提到的网络的原因吧，这应该是一个网络不可避免的问题。
大多数时候，这个并未给我造成什么困扰，因为，再去点击一下为空的结果最右边的展开Icon的话，
应该是会再次去取一次结果，如果是网络原因的话，绝大情况这样就能取到。

那么，针对这样的问题，如果需要改的话，
与其是针对网络异常去改的话（应该是改不好的。比较视对方服务器的符合，已经用户本身的网络所致）
是否，可以在明确知道是网络异常导致的搜索为空的话，能否retry 一次呢，稍微拉开个30sm啥的应该会大有不同把。。。前提但是能区分 【搜索结果本身为空】和【网络异常导致空 - 404？啥的】

**Comment by crimx** [comment]
这个可以考虑加进去，我看看如何处理。与此同时如果网络经常不稳定的话可以考虑更换 DNS 服务器，如 1.1.1.1
