### ISSUE TITLE
Firefox不能本地PDF划词

### ISSUE THREAD

**Issue by zxy06677** [crimx/ext-saladict#202]
用Firefox打开本地PDF后右键图标打开为PDF，出来的是空页面。
地址栏显示moz-extension://a4b5bd69-4ef3-4fce-bf54-d770ffae694a/static/pdf/web/viewer.html?file=file:///D:/xxx.pdf
我换了Chrome后按照说明的修改设置，用同样的方法能够打开划词。

Firefox版本62.0，操作系统WIN10  版本号17134.228

**Comment by crimx** [comment]
Firefox 对扩展支持还没有 Chrome 完善。目前可以在 Saladict 的 PDF 页面中点右上方的按钮打开。

**Comment by zxy06677** [comment]
好的，谢谢解答！
