### ISSUE TITLE
Edge浏览器上不能用了

### ISSUE THREAD

**Issue by 10GH** [crimx/ext-saladict#2022]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Edge 112.0.1722.58 (正式版本) (64 位)] 
- 沙拉查词版本: [v7.20.0] 

## 描述问题

问题：1.在浏览器里右键菜单中找不到选项；请看截图[1]
           2.在划词后没有出现弹窗按钮；请看截图[2]
           3.在扩展按钮上点击，弹不出菜单窗口；请看截图[3]

## 复现步骤

复现步骤：在任何步骤

## 期待的正常行为

期待的正常行为：可以正常查词，翻译

## 截图

![1](https://user-images.githubusercontent.com/64300290/234461760-8e41d6e3-034a-4369-96c9-bf87b4c6eea4.png)
![2](https://user-images.githubusercontent.com/64300290/234461769-12af2b9d-0c3e-4938-afbc-bafa4ad45b20.png)
![3](https://user-images.githubusercontent.com/64300290/234461770-74329df8-1e6b-4f56-84c8-49aed395c67d.png)

**Comment by 10GH** [comment]
自己顶一下，不要沉啊

**Comment by 10GH** [comment]
再顶一下，不要沉

**Comment by crimx** [comment]
右键沙拉图标，看看网页权限有设置为给所有网站么？

**Comment by 10GH** [comment]
已经可以使用了，不知道怎么可以的，可能是更新了
