### ISSUE TITLE
关于火狐无法正常使用划词翻译

### ISSUE THREAD

**Issue by operav** [crimx/ext-saladict#2024]
火狐版本：112.0.2 (64 位)
见https://github.com/crimx/ext-saladict/issues/1985中Akatsukiw的回复
经过测试，确实如此，只要把可以填写token或者key的词典删掉，只保留例如必应词典，然后重启沙拉扩展，必应词典就能正常工作了。
麻烦作者大佬看一下，这个问题到底出在哪？现在沙拉中的百度词典、彩云词典在火狐已经至少半个月没法使用了。

如果是因为火狐官方扩展网站下架了最新版的原因，请问可否在Github或者网盘单独提供火狐版的沙拉最新版下载？
我看了下Releases，现在只提供了谷歌版的单独下载，没有火狐版。

**Comment by LTHPKBTE** [comment]
重新打包后的文件见 [#1985](https://github.com/crimx/ext-saladict/issues/1985#issuecomment-1575517457) 。
没有签名，只有第三方 firefox 改版（waterfox等）或者 ESR、Nightly、开发者版本能安装。

**Comment by operav** [comment]
> 重新打包后的文件见 [#1985](https://github.com/crimx/ext-saladict/issues/1985#issuecomment-1575517457) 。 没有签名，只有第三方 firefox 改版（waterfox等）或者 ESR、Nightly、开发者版本能安装。

非常感谢！现在换成ESR版又可以继续使用了！
唉，也不知道这个问题作者何时能解决。
ESR版也好，开发者也罢，终归不是正途来得方便。

**Comment by crimx** [comment]
Duplicate of #1985
