### ISSUE TITLE
沙拉查词在划词翻译时没有翻译结果

### ISSUE THREAD

**Issue by PILIHU2022** [crimx/ext-saladict#2025]
Firefox112.0版本
沙拉查词7.11.0版本
在Firefox中使用沙拉查词插件，添加了百度词典，并且正确设置了appid和key，使用划词翻译是却是这样的
 
![09%ISTHUA(LRTQ1KC$IS150](https://user-images.githubusercontent.com/100511118/235292070-7bbe1e13-9e27-4e71-bafc-863f10b23c6f.png)

并且在设置了百度翻译的appid和key（已确认是正确配置了）时，Bing翻译也无法使用，都是没有翻译结果的，请问这是什么情况？

**Comment by PILIHU2022** [comment]
现在Bing翻译的问题已经解决了，已经可以划词翻译了，只剩下百度翻译的问题，谢谢！

**Comment by PILIHU2022** [comment]
在Microsoft Edge Dev 版本 114.0.1807.1 (正式版本) dev (64 位)中使用沙拉查词（7.20）可以使用百度翻译，并且Bing翻译也可以使用，可能是7.11.0版本出现了问题，请开发者尽快修复，谢谢！

**Comment by RESTART1230** [comment]
#1985
