### ISSUE TITLE
沙拉词典在Firefox查词出现异常

### ISSUE THREAD

**Issue by PILIHU2022** [crimx/ext-saladict#2026]
> 设备/系统信息
 操作系统：Windows10
 浏览器版本：Firefox 112.0
 沙拉查词版本：7.11
> 描述问题
在正确地配置了百度翻译地appid和key并添加了百度翻译源，在任何界面划词翻译任意词均一直在加载（包括bing翻译），不使用百度翻译时bing翻译也无法翻译。
> 复现步骤
1.移出沙拉查词扩展
2.重新下载并安装该扩展
3.添加词典并设置appid与key
4.打开任意界面使用沙拉查词
> 截图

![09%ISTHUA(LRTQ1KC$IS150](https://user-images.githubusercontent.com/100511118/235292070-7bbe1e13-9e27-4e71-bafc-863f10b23c6f.png)

> 额外信息
已尝试过在Microsoft Edge的沙拉查词中可以正常使用的配置导入到Firefox的沙拉查词中，但是没有效果。在Arch Linux中的Firefox也是同样。

**Comment by LTHPKBTE** [comment]
firefox上的插件问题在7.11.1修复，但是不知道为什么火狐插件商店回滚了新版本更新。请尝试自行更高的版本

**Comment by PILIHU2022** [comment]
> firefox上的插件问题在7.11.1修复，但是不知道为什么火狐插件商店回滚了新版本更新。请尝试自行更高的版本

尝试过自行打包7.20版本到Firefox插件商店，但是因某种原因无法上传

**Comment by LTHPKBTE** [comment]
#1985

**Comment by crimx** [comment]
Duplicate of #1985
