### ISSUE TITLE
右上面板显示不完整

### ISSUE THREAD

**Issue by linsui** [crimx/ext-saladict#203]
- Saladict 版本
6.13.4

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）
win10 1804 Firefox 62.0

- 类型：错误？建议？
右上面板显示不完整

<img width="288" alt="default" src="https://user-images.githubusercontent.com/36977733/45335361-91843680-b5b1-11e8-9449-4ee329639486.PNG">

**Comment by crimx** [comment]
你好，你的屏幕尺寸是？

**Comment by crimx** [comment]
可在 Saladict 设置中调整面板宽度。

`chrome-extension://gokbidhfnnodknepblnmlgbedcgkhphf/options.html`

**Comment by crimx** [comment]
你好，经测试我确定是屏幕大小问题的。Firefox 与 Chrome 的处理方式不一样。当浏览器宽度变小后 Firefox 的弹出框会出现标题，正常情况下是没有的。

所以解决方式还是设置查词面板的大小。

**Comment by crimx** [comment]
得知真正的问题了。这是由于图标被收入 “more tools” 图标（ `>>` ）造成的。屏幕大小会间接导致图标被收进去。拖出来到最左边即可。

**Comment by linsui** [comment]
谢谢，确实是这个问题，不隐藏就恢复正常了
