### ISSUE TITLE
cnki词典网页改版

### ISSUE THREAD

**Issue by systemoutprintlnhelloworld** [crimx/ext-saladict#2031]
## 设备信息
- 操作系统: [win11 preview] 
- 浏览器版本: [edge112.0.1722.68 (正式版本) (64 位)] 
- 沙拉查词版本: [v7.20] 

## 描述问题

cnki原访问网站已废弃`https://dict.cnki.net/index#`
![image](https://user-images.githubusercontent.com/62531937/236167573-6907108a-d41e-4d02-ab73-50213a2f1e22.png)
目前yi已换到新网址`https://dict.cnki.net/index#`
![image](https://user-images.githubusercontent.com/62531937/236167627-86177c0d-57a9-4b65-993e-013dddce6db3.png)

## 期待的正常行为

期望可以修复该失效访问链接

**Comment by crimx** [comment]
Duplicate of #1878
