### ISSUE TITLE
搜索翻译的官网已经停止使用了，建议关闭词典中的搜索翻译添加api的功能

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [crimx/ext-saladict#2032]
<img width="631" alt="image" src="https://user-images.githubusercontent.com/59086082/236592276-032611e4-c66b-4a0c-bb82-864448a18b0a.png">

**Comment by crimx** [comment]
这个已经有小伙伴实现了 https://github.com/crimx/ext-saladict/pull/2010 ，我把剩下的问题处理完会发个版。
