### ISSUE TITLE
词典里面加了必应词典但是划词翻译的时候有时候出现有时候不出现

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [crimx/ext-saladict#2035]
![image](https://user-images.githubusercontent.com/59086082/236975831-52206394-7d53-4038-8b19-297bbd080894.png)
![image](https://user-images.githubusercontent.com/59086082/236975862-a9197596-28d0-416d-8535-b1cadd2819f3.png)
<img width="715" alt="image" src="https://user-images.githubusercontent.com/59086082/236975892-9911e261-6cd0-4f04-a224-4a8b33815540.png">

**Comment by crimx** [comment]
每个词典都可以设置在一定字数范围内才展示。

**Comment by duoluodexiaoxiaoyuan** [comment]
> 每个词典都可以设置在一定字数范围内才展示。

原来是这样
