### ISSUE TITLE
Add support for kindle online reader

### ISSUE THREAD

**Issue by gcgeng** [crimx/ext-saladict#2036]
**Is your feature request related to a problem? Please describe.**

Yes. I have issues reading Kindle e-books with the web reader(https://read.amazon.com). I wish to be able to mark some words and use saladict to look them up, which can then be stored in Anki using the awesome connect plugin. I do know that there are some built-in dictionaries for such e-readers, yet I still wish to use Anki to memorize the words I learned from reading and collect them into a unified place where I can review them conveniently.

**Describe the solution you'd like**

I'd like Saladict to be enabled on this website: https://read.amazon.com Currently, when selecting a word, it pops up the default dictionary look-up window, and the saladict bubble cannot be found. An image of the current scenario is attached.
<img width="392" alt="image" src="https://github.com/crimx/ext-saladict/assets/8966584/2a710ac8-2c1e-4eed-a605-acd70564e946">

**Describe alternatives you've considered**

I may consider using the default dictionary and using some notes to mark the new vocabulary, but that's cumbersome and cannot be reviewed easily using Anki.

**Additional context**

- I think the core problem is that due to copyright issues, the text is not plain HTML text, making it hard for extensions like Saladict to work. 

- To reproduce or debug, I'd suggest going to the amazon kindle webstore and finding some free books like [this one](https://www.amazon.com/Shakespeares-Sonnets-William-Shakespeare-ebook/dp/B004TPEMLK/), and reading it in the [web reader](https://read.amazon.com/).

- Any suggestions on how to solve this issue, like possible technical roadmaps, are welcomed!

**Comment by crimx** [comment]
Sorry no luck. Looks like the page on kindle reader is an image and the selection is merely a simulation with a colored rectangle.

<img width="1056" alt="image" src="https://github.com/crimx/ext-saladict/assets/6882794/dcafdf58-ee9a-49b8-88ae-4d10e692b098">

**Comment by gcgeng** [comment]
> Sorry no luck. Looks like the page on kindle reader is an image and the selection is merely a simulation with a colored rectangle.
> <img alt="image" width="1056" src="https://user-images.githubusercontent.com/6882794/238196149-dcafdf58-ee9a-49b8-88ae-4d10e692b098.png">

Thank you for your prompt reply! I also find this task challenging, and I have come across a helpful YouTube video: https://www.youtube.com/watch?v=VvzcIWh8PRU. It provides a workaround to export Kindle vocabularies to Anki. Consequently, I have decided to pursue this solution and close this issue.
