### ISSUE TITLE
中英文都存在的情况，未翻译

### ISSUE THREAD

**Issue by erjinzhi2333** [crimx/ext-saladict#204]
- Saladict 版本

6.14.0

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）

WIN10、Chrome 67.0.3396.62 (正式版本) （64 位）

- 类型：错误？建议？
错误

- 划词模式？以及其它觉得相关的设置。

- 重现：提供详细的可重现问题的操作。
中英文混合情况，未翻译
`The Cambricon research project is helmed by two brothers, Chen Yunji (陈云霁) and Chen Tianshi (陈天石), two of the youngest full professors at the CAS Institute of Computing Technology.`

- 期待：理想情况下扩展应该怎么做？
不能确定要求 中译英 还是 英译中，可以考虑两个都输出

- 实际：客观描述扩展实际上做了什么。
未翻译

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
你好，默认设置下无法重现你的“未翻译”情况。请提供你的启用词典，以及划词和词典的语言设置。

**Comment by crimx** [comment]
已发布
