### ISSUE TITLE
希望可以设置不点击" ﹀ "就展开所有内容

### ISSUE THREAD

**Issue by xiaohuji** [crimx/ext-saladict#2047]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Microsoft Edge 版本 114.0.1823.41] 
- 沙拉查词版本: [v7.20.0] 

## 请描述目前使用沙拉查词遇到什么不便
查词之后如果单词内容多可以点击" ﹀ "展开内容，但是我想不点 希望可以直接自动展开

## 理想情况下，沙拉查词应该怎么做

设置里加一个按钮，可以不点击" ﹀ "就展开所有内容

**Comment by crimx** [comment]
[沙拉查词设置](https://saladict.crimx.com/manual.html#open-setting)「词典设置」编辑相应的词典，「词典默认高度」设置一个比较大的值即可。

**Comment by xiaohuji** [comment]
我在设置中的“查词面板”选项中只看到了“设置面板宽度”，没有看到可以设置高度的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "crimx/ext-saladict"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月10日(星期六) 下午4:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [crimx/ext-saladict] 希望可以设置不点击" ﹀ "就展开所有内容 (Issue #2047)





 
沙拉查词设置「词典设置」编辑相应的词典，「词典默认高度」设置一个比较大的值即可。

**Comment by xiaohuji** [comment]
会了谢谢！
