### ISSUE TITLE
建议词典面板overscroll时不要引发页面的scrolling

### ISSUE THREAD

**Issue by hax** [crimx/ext-saladict#205]
给 `div.panel-StyleRoot.saladict-DictPanel` 加上 `overscroll-behavior: contain` 即可。
本来想直接提个pr，粗看了一下，不知道加在哪个源文件里好。所以就提个issue啦。

**Comment by hax** [comment]
我自己用devtools加了，是起作用的。（latest Chrome）

**Comment by hax** [comment]
嗯，我当时只在内部页面测了。。。

iframe目前好像不行。我去spec repo开了一个issue：https://github.com/WICG/overscroll-behavior/issues/31

或许在普通页面也可以考虑不用 iframe，可以用 web component 。

**Comment by crimx** [comment]
已经针对 iframe 进行了许多深度整合，改起来会比较大工程。

**Comment by crimx** [comment]
已发布。等待浏览器支持。
