### ISSUE TITLE
关闭访问剪贴板权限

### ISSUE THREAD

**Issue by ghost** [crimx/ext-saladict#2059]
## 设备信息
- 操作系统: Windows 10
- 浏览器版本: Firefox 117 测试版
- 沙拉查词版本: 7.11.0

## 请描述目前使用沙拉查词遇到什么不便

扩展会访问剪贴板

## 替代方案

是否可以关闭访问剪贴板的功能

**Comment by crimx** [comment]
[打开设置](https://saladict.crimx.com/manual.html#open-setting)，左侧导航最后一项「权限管理」。
