### ISSUE TITLE
为什么 google translate 在 fetchWithoutToken 时不使用 dt 参数

### ISSUE THREAD

**Issue by iamgqb** [crimx/ext-saladict#206]
看了下代码发现在 [fetchWithToken](https://github.com/crimx/ext-saladict/blob/dev/src/components/dictionaries/google/engine.ts#L71) 时是带有 dt 参数的
是什么原因选择在 [fetchWithoutToken](https://github.com/crimx/ext-saladict/blob/dev/src/components/dictionaries/google/engine.ts#L81) 时不使用 dt 参数呢？

目前 Google Translate 都只返回了一个结果

![image](https://user-images.githubusercontent.com/2213424/45898360-5df4a800-be0c-11e8-9661-590e52295d73.png)

偏偏我好像每次都是没有get token?惨... 没有细究...
![image](https://user-images.githubusercontent.com/2213424/45899504-9c3f9680-be0f-11e8-82fb-83e8293d4783.png)

个人测试好像不带 token 时的 dt 参数也是生效的：

![image](https://user-images.githubusercontent.com/2213424/45899161-aad97e00-be0e-11e8-9fc2-a50e3c1068cd.png)

另外就是，dt 参数似乎可以削减一些，感觉 `dt=bd` 似乎好像也许就够用了？

参见：https://stackoverflow.com/questions/26714426/what-is-the-meaning-of-google-translate-query-params

**Comment by crimx** [comment]
你好，因为在设计的时候都是只考虑取第一个结果（翻译），所以其它参数并没有特别注意（抱着能行不影响的原则）。希望获取丰富的结果可看其它词典，就不重复劳动解析了。

**Comment by iamgqb** [comment]
emmmm...

如果把 Google Translate 定义为整段文字翻译的确是够了的，其他词典对于单词的释义反而是更加完整的... 

OK~ 
（才不会说本来想提个pr，结果看了下代码发现要改需要重写整个View 和 重新定义engine的结构，懒癌大犯...

**Comment by crimx** [comment]
哈哈，优秀的人常常技痒 :smile:
