### ISSUE TITLE
在Firefox国际版中查词一直在加载

### ISSUE THREAD

**Issue by x2295914794** [crimx/ext-saladict#2062]
在Firefox国际版中查词一直在加载，以后都没有出现这样的情况
<img width="338" alt="微信截图_20230717154926" src="https://github.com/crimx/ext-saladict/assets/107030618/b01a4a52-6e3c-4372-859c-f44c5f8389fc">

**Comment by crimx** [comment]
火狐更换了审核，商店版下架了好几个版本。要支持改动较大，可能要等到下一个大版本更新。目前可以手动安装 Release 下方的 [`firefox.zip`](https://github.com/crimx/ext-saladict/releases/tag/v7.20.0#:~:text=yipanhuasheng%20and%20rumosky-,Assets,-6)（火狐正式版需要额外[配置](https://stackoverflow.com/questions/31952727/how-can-i-disable-signature-checking-for-firefox-add-ons/31952728#31952728)）

**Comment by crimx** [comment]
Duplicate of #1985
