### ISSUE TITLE
刚自动更新的6.15.1，用不来了啊

### ISSUE THREAD

**Issue by Lukikay** [crimx/ext-saladict#208]
- Saladict 版本
6.15.1

- 平台：
Win 10, Chrome 69.0.3497.100

- 类型：
错误

- 重现：
右上弹框白屏，什么都没有了；
设置界面本来在右边的弹框预览也整个没了；
网页上划词，小图标还能显示，但是打不开弹窗的词典，但是自动发音倒还是念了出来

- 额外信息：

![image](https://user-images.githubusercontent.com/39486024/45930392-84732a00-bf57-11e8-9c7c-755a7381ef0b.png)

**Comment by crimx** [comment]
是的，修复刚发布。

**Comment by crimx** [comment]
问题在特定配置上出现，所以测试时没测出来。
