### ISSUE TITLE
查找日語漢字時不出現weblio結果

### ISSUE THREAD

**Issue by entrechienetloup** [crimx/ext-saladict#2081]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [116.0.5845.110] 
- 沙拉查词版本: [7.20.0] 

## 描述问题

查找日語單詞時，只有含有假名時才會出現weblio詞典的結果。查單純的漢字詞（即便是日本漢字）都沒有weblio結果。

## 复现步骤

1. 打开Dictionaries
2. 添加weblio詞典（也添加moji辭書）
3. 搜索「労」「広告」「拡張」「宣伝」、再對比「限り」「辿る」「みやぎ」
4. 可以發現含有假名時才會出現weblio結果

## 期待的正常行为

漢字詞也出現weblio結果

## 额外信息

如果是因為無法區分日本和中文漢字，為什麼moji辭書卻可以不管是漢字還是假名都出結果？weblio也是日英辭書，和中文唔關。

**Comment by crimx** [comment]
在词典的设置中可以勾选汉字
