### ISSUE TITLE
UI BUG

### ISSUE THREAD

**Issue by tsQing** [crimx/ext-saladict#209]
- Saladict 版本：6.15.3
- 平台：Chrome(69.0.3497.100)
- 类型：UI错误
- 划词模式？以及其它觉得相关的设置。
UI出现被遮挡
- 重现：提供详细的可重现问题的操作。
在设置里面讲宽度从450px→350px后，在点击谷歌菜单处的saladict按钮时内容会有部分被遮挡
![image](https://user-images.githubusercontent.com/18617540/46005897-dbf4cf80-c0e8-11e8-8a1f-450a4e77c9b3.png)

- 期待：理想情况下扩展应该怎么做？
在搜索框这个上面的白边能不能去掉，即用同样的颜色（搜索栏的颜色，墨绿色？#5CAF9E），这只是个人使用时对ui的一点点小强迫症而已，对使用并无影响。谢谢了
![image](https://user-images.githubusercontent.com/18617540/46006395-05622b00-c0ea-11e8-9441-5881070e478a.png)

**Comment by crimx** [comment]
感谢反馈，宽度的 bug 会被处理。

白边很遗憾是浏览器强加的无法去除。这个已经有不少人提过，如果有更好的排版方式欢迎建议。

**Comment by tsQing** [comment]
关于宽度设置还存在一点bug，就是在完全退出浏览器后重启，对于划词弹窗显示时，原来设置的宽度不将失效，我这里设置的宽度依然是350px，重启浏览器后，划词弹窗宽度变为默认宽度450px，菜单栏的宽度依然保持在修改后的宽度350px。
