### ISSUE TITLE
浏览器扩展模版

### ISSUE THREAD

**Issue by tra4less** [crimx/ext-saladict#2097]
有一说一，这个项目代码质量挺好的，是否考虑维护一个ext starter

**Comment by crimx** [comment]
谢谢！这个项目的技术栈已经有点年份了，之前弄了一些工具在 [awesome-webextension](https://github.com/awesome-webextension) 上。

现在更推荐看看 antfu 的 [vitesse-webext](https://github.com/antfu/vitesse-webext)。

另一方面，Chrome Extension Manifest V3 作妖过头不被开发者接受，现在规范无限延期重改。我对浏览器扩展的发展整体还是悲观，所以接下来会减少核心业务对浏览器扩展的依赖，倾向使用 [tauri](https://github.com/tauri-apps/tauri) 开发桌面应用搭配使用。

**Comment by tra4less** [comment]
感谢回复，有基于react的Starter的推荐吗。

**Comment by crimx** [comment]
react 不需要什么特别的脚手架吧，基本支持 ts 的都能用。

**Comment by tra4less** [comment]
我表达有误，我是说开发扩展的，类似[vitesse-webext](https://github.com/antfu/vitesse-webext)的。

**Comment by crimx** [comment]
它用 vite 的，直接在 vite config 加上 react plugin 就能用。

**Comment by tra4less** [comment]
好的，谢谢
