### ISSUE TITLE
【嘤嘤嘤...我有130亿个建议】【首先我是用划词直接搜索的......】

### ISSUE THREAD

**Issue by 990721830** [crimx/ext-saladict#211]
1丶【建议可以直接搜索模式下设置划词延迟秒数】

2丶【那个划词面板能不能记忆位置或者固定在哪里,经常挡住我想看的位置】
【快捷查词-出现位置-右下角】点了没用不知道这个是干嘛的

3丶【添加输入框应该禁止划词直接触发】
【可以采用划词后按一下快捷键触发-这个触发也可以匹配全模式吧】

4丶【能不能在右上角弹窗输入框记忆住文字或者启用即时翻译,不需要要手动点击这个按钮
![snipaste20181006_091741](https://user-images.githubusercontent.com/25548230/46565933-dac56d00-c948-11e8-8271-5f6b7d1a3037.jpg)】
因为经常不小心点击页面空白处就没了...

5丶【哦...对了那个右上角左键弹窗的时候能不能点击弹出新页面】
类似smms图床这样
https://chrome.google.com/webstore/detail/smms图床/jfnojkljiahflcnlodkicgfbofclmdoi
![2018 10 06 09 35 39](https://user-images.githubusercontent.com/25548230/46566131-60e2b300-c94b-11e8-89bc-86ba5b49cac9.gif)

**Comment by crimx** [comment]
感谢建议，非常欢迎！

> 1丶【建议可以直接搜索模式下设置划词延迟秒数】

请展开描述一下这个场景。

> 2丶【那个划词面板能不能记忆位置或者固定在哪里,经常挡住我想看的位置】

划词面板 可以拖动，也可以钉住。[「参见」](https://github.com/crimx/ext-saladict/wiki#%E6%9F%A5%E8%AF%8D%E9%9D%A2%E6%9D%BF%E5%8F%AF%E9%92%89%E4%BD%8F%E5%8F%AF%E6%8B%96%E5%8A%A8%E5%8F%AF%E8%BE%93%E5%85%A5)

> 【快捷查词-出现位置-右下角】点了没用不知道这个是干嘛的

三按 ctrl 触发快捷查词，鼠标移动该设置见右边说明。

> 3丶【添加输入框应该禁止划词直接触发】

不太清楚你的描述，是希望输入框不触发划词吗，这个见设置“**不在输入框划词**”。

> 【可以采用划词后按一下快捷键触发-这个触发也可以匹配全模式吧】

划词方式中设置“**按住 ctrl**” 即是按键触发。另外扩展也支持设置 chrome 快捷键。

> 4丶【能不能在右上角弹窗输入框记忆住文字就算关闭的时候或者启用即时翻译,不需要要手动点击按钮,】

“就算关闭的时候”是什么意思？另外搜索输入完按回车键<kbd>↵</kbd>就行了。如果是希望点开自动翻译，见设置“**右上弹框**”，也可设置自动加载的内容。

> 5丶【哦...对了那个右上角左键弹窗的时候能不能点击弹出新页面】

这是个很好的建议！我会考虑把快捷查词（三按 ctrl）换成弹出新页面。

**Comment by 990721830** [comment]
2丶【那个划词面板能不能记忆位置或者固定在哪里,经常挡住我想看的位置】

划词面板 可以拖动，也可以钉住。「参见」

我是想要所有页面都记忆住当前位置....刷新页面后又要重新固定

4丶【能不能在右上角弹窗输入框记忆住文字就算关闭的时候或者启用即时翻译,不需要要手动点击按钮,】

“就算关闭的时候”是什么意思？另外搜索输入完按回车键↵就行了。如果是希望点开自动翻译，见设置“右上弹框”，也可设置自动加载的内容。

就是目前点开右上角弹窗的时候要是没有点击那个搜索按钮的情况下...
点击页面空白处有可能会导致输入文字不见了...
但是问题5要是实现了话...这个问题应该不存在了...


![2018 10 06 10 25 13](https://user-images.githubusercontent.com/25548230/46566949-00f40880-c95b-11e8-86b1-5a34b09ed358.gif)

**Comment by 990721830** [comment]
1丶那个还有UI配色的建议
希望可以弄成我百度这样深灰底+灰白字这样会比较护眼
或者可以让用户自定义选择RGB颜色

2丶我不知道你这能不能弄出这个聚合翻译搜索串就是那个%s的
如果可以的话我就可以配合WGestures手势
跳脱chrome限制直接在win10选中文字然后手势就可以直接调用了
![snipaste20181006_114030](https://user-images.githubusercontent.com/25548230/46567017-cbe8b580-c95c-11e8-9946-a54c04395ab0.jpg)

**Comment by crimx** [comment]
> 我是想要所有页面都记忆住当前位置....刷新页面后又要重新固定

每个页面各不一样，这么实现应该是弊大于利。

> 但是问题5要是实现了话...这个问题应该不存在了...

是的。保留输入会与其本身的设计冲突。

UI 自定义配色目前没有计划实现。

> 我不知道你这能不能弄出这个聚合翻译搜索串就是那个%s的
> 如果可以的话我就可以配合WGestures手势
> 跳脱chrome限制直接在win10选中文字然后手势就可以直接调用了

不明白。如何跳出 Chrome 限制？

还有你的浏览器是什么，貌似右上弹框溢出了。

**Comment by 990721830** [comment]
1丶每个页面各不一样，这么实现应该是弊大于利。

默认固定了...难道不能再解开吗
我只是想让他在浏览器右下角附近

或者还是默认不固定..
添加一个按钮不同网站匹配不同位置的方式...


2丶360极速内测69内核...我刚才没有截取完整而已
![snipaste20181006_115332](https://user-images.githubusercontent.com/25548230/46567160-8332fb80-c960-11e8-836b-f5274481e56b.jpg)

3丶就是用WGestures手势...
打个比方我在win10用网易云随便看到一个单词不会...
只要选中后按右键手势直接一秒打开自定义搜索页面...
![2018 10 06 12 09 50](https://user-images.githubusercontent.com/25548230/46567206-94c8d300-c961-11e8-8868-2ff76ed51aa6.gif)

**Comment by crimx** [comment]
> 默认固定了...难道不能再解开吗
> 我只是想让他在浏览器右下角附近
> 
> 或者还是默认不固定..
> 添加一个按钮不同网站匹配不同位置的方式...

你好，这不是能与不能的问题，而是这么实现会增加配置的复杂度。这个功能带来的效果我认为不足以抵消其带来的麻烦，所以是弊大于利。

> 360极速内测69内核

估计是被 360 魔改了，我有时间测试一下其右上弹框的最大高度。

> 只要选中后按右键手势直接一秒打开自定义搜索页面...

Saladict 不是这么实现的，所以这个方法应该不行。如果你需要获得原网站的链接，这里有一份[清单](https://github.com/crimx/ext-saladict/blob/dev/src/app-config/context-menus.ts)供参考。

**Comment by 990721830** [comment]
>>对了还可以添加 腾讯ai lab..腾讯君翻译 
https://ai.qq.com/product/nlptrans.shtml#text

>>还有一个问题是我默认浏览器全局缩放放大了..
所以导致右上角弹窗会出现滚动条而且显示不完整了...
先和你说一下...我也不知道之后那个新弹窗会不会也有
![snipaste20181006_125201](https://user-images.githubusercontent.com/25548230/46567582-c0e75280-c967-11e8-8a87-ea3dafa87050.jpg)

**Comment by crimx** [comment]
哦，原来是放大了。那这个应该不是 360 的问题了，默认情况下是没有溢出的吧。

放大的话我看要不要再加个设置右上弹框的高度。考虑到目前设置已经有点臃肿，先搁置着有时间再想想。

英语词典目前不考虑再加了。谷歌翻译搭配搜狗翻译已经满足绝大部分需要。

**Comment by 990721830** [comment]
![snipaste20181006_133252](https://user-images.githubusercontent.com/25548230/46567807-88964300-c96c-11e8-85e2-e41ca95c910f.jpg)
这是原比例的...

**Comment by 990721830** [comment]
还有最上面第三个回复的问题修改了...我修改添加了也许你可能没看到

>1丶【建议可以直接搜索模式下设置划词延迟秒数】

请展开描述一下这个场景。

>>就是在划词选中文字后我不一定是需要翻译的
我只是复制这个词语粘贴或者拖拽而已
所以是让他选中文字几秒后才触发翻译
你现在应该是0秒吧太快了
或者可以设置复制后让鼠标停留在选中文字后几秒触发...
不然触发的太频繁了...
![2018 10 06 15 23 35](https://user-images.githubusercontent.com/25548230/46568698-001f9e80-c97c-11e8-8ec3-76e6171bdb5f.gif)

**Comment by crimx** [comment]
确实没看到哈哈。直接搜索的设计就是马上搜的，不建议在平时使用，设置了延时也很容易误触。一般是搭配钉住时使用，或者设置不同查词情景模式。另外也可以使用悬浮取词，不喜欢按住 alt 键也可以搭配快捷键启用关闭。

**Comment by crimx** [comment]
是的，请阅读[使用说明](https://github.com/crimx/ext-saladict/wiki#shortcuts)。

**Comment by crimx** [comment]
查了一下这个 WGestures 发现作者也做了一款划词应用。双键的方式可以参考一下，之前的设计没有针对纯鼠标的用户。

**Comment by 990721830** [comment]
>我之前用翻译侠你也可以看一下...
https://github.com/magic-FE/translate-man
![2018 10 06 17 32 24](https://user-images.githubusercontent.com/25548230/46569928-1be07000-c98f-11e8-9714-b8ed1d6b61bd.gif)

>>他做的UI超级简约...
但是搜索引擎只有谷歌...
而且他做的划词直接显示做了优化....
翻译页面是正好在这个单词或者光标水平线下面的...
第一层显示对单词所有解释...
然后点击显示所有注解...
目前是显示太大了....




https://chrome.google.com/webstore/detail/translate-man/fapgabkkfcaejckbfmfcdgnfefbmlion

**Comment by crimx** [comment]
Saladict 也可以对词典设置不自动展开。

Saladit 的重心是准确性（也是我查词的主要需求），这是各个功能设计时优先考虑的。

你也可以结合两个扩展使用，需要详细了解的时候再唤出 Saladict 。

**Comment by drcege** [comment]
其实我有个建议，能不能做成 Chrome App 的形式。。就是单独出来作为日常查词的应用，感觉 PC 端现有的词典类工具都没你这个好用 O(∩_∩)O

**Comment by crimx** [comment]
@drcege 你好，谢谢哈哈。但 Chrome APP 已在淘汰边缘了，所以不会考虑花时间实现。快捷查词单独窗口实现之后可以一定程度上作为本地查词。

**Comment by crimx** [comment]
供参考

> As of November 21st, 2016, all newly published packaged or hosted apps are restricted to Chrome OS, and are not available to users on Windows, Mac or Linux.
All packaged and hosted apps will be removed from Chrome Web Store search & browse functions in mid-December 2017. Existing apps will continue to work and receive updates. - [More Info](http://blog.chromium.org/2016/08/from-chrome-apps-to-web.html)

**Comment by KnIfER** [comment]
WGesture是全局鼠标钩子么，用起来卡不卡？（最好开启的时候玩一盘游戏试试……）
