### ISSUE TITLE
反馈一些firefox使用的问题

### ISSUE THREAD

**Issue by zzm-note** [crimx/ext-saladict#212]
环境：win10 64位；firefox 62
1. 划词习惯->不在输入框划词  此处没有勾选，但是输入框还是不能划词翻译（没有显示图标）
2. 词典设置->谷歌翻译 勾选了“优先使用google.cn“，关闭代理后，谷歌翻译还是加载不了。点击左上角图标能正常跳转到translate.google.cn进行翻译
3. 建议：希望网页全文翻译调用谷歌的时候，能够增加使用google.cn的选项。[S3.Translator](https://addons.mozilla.org/zh-CN/firefox/addon/s3google-translator/?src=ss)在网页全文翻译的时候可以调用google.cn，可以参考一下

**Comment by crimx** [comment]
感谢反馈。

1. Firefox 确实没反应，我看看是什么原因。
2. 经调试发现是 Google 更新了密钥的算法，得找时间研究研究。
3. 我会再加个 cn 的选项。
