### ISSUE TITLE
关于面板查词

### ISSUE THREAD

**Issue by dyean** [crimx/ext-saladict#213]
- Saladict 版本
6.16.1

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）
windows10 1803 || chrome 69.0

- 类型：错误？建议？
建议

- 划词模式？以及其它觉得相关的设置。
 1. **面板查词**时可以在旁边弹出一个新的查词框，使用**英文词典**时可以快速查询生词。

**Comment by crimx** [comment]
面板内部可另外设置查词模式。

**Comment by dyean** [comment]
> 面板内部可另外设置查词模式。

比如在面板查词设置双击查词，会在当前的面板查询，之后再点击返回 `<` 不会自动显示上一个单词的翻译。

希望的效果是，面板查词时弹出一个新的面板；或者是，点击返回后显示上一个单词的翻译。
这样在使用英文词典的时候，会比较方便。

**Comment by crimx** [comment]
会改为返回后自动搜索

**Comment by dyean** [comment]
Thx.
