### ISSUE TITLE
对于scihub解密的文档划词翻译会弹出两个翻译窗口

### ISSUE THREAD

**Issue by TerenceZ** [crimx/ext-saladict#214]
- 6.16.1

- Windows Chrome 69.0.3497.81（正式版本）（64 位）

- 类型：BUG？

- 划词模式

- 重现地址：https://sci-hub.tw/https://dl.acm.org/citation.cfm?id=1507157

- 期待：划词后只显示一份翻译Popup

- 实际：划词翻译后会弹出两个Popup

**Comment by crimx** [comment]
这种情况比较少见，我看看能不能做兼容。

**Comment by crimx** [comment]
于此同时，你可以 <kbd>ctrl+shift+i</kbd> 直接在新 Tab 打开 iframe 的地址。
