### ISSUE TITLE
pdf中加入单词本的上下文bug

### ISSUE THREAD

**Issue by jokerkeny** [crimx/ext-saladict#215]
pdf中，加入单词本，上下文只包括单词所在行，而非整句（在一般网页中功能正常，能够把单词所在整句加入）
额外期待：可以自定义加入前n句，后m句作为上下文。

**Comment by crimx** [comment]
你好，这是因为 PDF 是没有语义的，它仅在乎样式的准确还原。所以一行有可能实际上就是一个段落。这个即使加上自定义范围也是不治本的。
