### ISSUE TITLE
打印字体不清晰

### ISSUE THREAD

**Issue by Konfido** [crimx/ext-saladict#216]
- Saladict 版本：6.16.1

- 平台：ubuntu 16.04, Chrome Version 69.0.3497.100 (Official Build) (64-bit)

- 类型：改进

- 重现：在阅读paper时英文字体就不算太清晰，而打印出来paper的字都没法看，是糊的，质量很差。跪求解决～

**Comment by crimx** [comment]
你好，这应该跟本扩展无关。你可以下载 PDF 用本地程序查看以及打印。看是不是同样问题。

**Comment by Konfido** [comment]
一开始我以为是打印机的问题，但是发现并不是。用浏览器自带pdf阅读器打印就正常了。Saladict打印出来后字体是那种虚虚的感觉，不知道为什么...

用saladict打印： [https://i.loli.net/2018/10/10/5bbd731432ae2.jpg](url)
用自带pdf阅读器打印： [https://i.loli.net/2018/10/10/5bbd73146cbfb.jpg](url)

**Comment by Konfido** [comment]
一开始我以为是打印进的问题，后来用浏览器自带pdf阅读器打印发现是正常的。Saladict打印出来的字体是虚的，不知道为什么...

用Saladict打印：https://i.loli.net/2018/10/10/5bbd731432ae2.jpg
用自带pdf阅读器打印： https://i.loli.net/2018/10/10/5bbd73146cbfb.jpg

**Comment by crimx** [comment]
如果是这样的话那应该是 [PDF.js](https://mozilla.github.io/pdf.js/) 的问题。你可以按他们的要求提交 issue ，可以的话最好提供文件供他们测试。

**Comment by SRainGit** [comment]
你好，我碰到的是使用Saladict在chrome浏览器可视化pdf文件时的模糊问题。
Saladict的pdf阅读器查找功能很好用，但是使用过程中忽然变模糊，阅读十分不方便。
如果按照您说的可能是PDF.js的问题的话，我觉得如果你们能够沟通一下应该更方便。
同样，跪求解决啊！

> 如果是这样的话那应该是 [PDF.js](https://github.com/mozilla/pdf.js) 的问题。你可以按他们的要求提交 issue ，可以的话最好提供文件供他们测试。

**Comment by crimx** [comment]
你好，对不起我实在没有兴趣花时间去处理这些特例问题。你可以试试关闭浏览器的硬件加速看看能不能解决迷糊。

至于打印可以关闭沙拉查词的 PDF 拦截，默认用自带的浏览，需要时从右键菜单打开。

**Comment by SRainGit** [comment]
> 你好，对不起我实在没有兴趣花时间去处理这些特例问题。你可以试试关闭浏览器的硬件加速看看能不能解决迷糊。
> 
> 至于打印可以关闭沙拉查词的 PDF 拦截，默认用自带的浏览，需要时从右键菜单打开。

哦不好意思。
浏览器硬件加速的开关跟这个没有关系。
最近发现在pdf可视化界面全屏显示后再退出就会恢复正常清晰度。但与此同时侧边栏与顶栏会被放大很多，沙拉查词的设置界面也会被放大。效果与在笔记本小屏幕上的win10系统界面被放大的效果相同。我使用的台式机24寸显示器。其他扩展插件的设置界面没有影响。
因此我估计是跟dpi之类的有关系。

该问题应该对大多数用户没有影响。毕竟是开源项目，仅做建议，谢谢。
