### ISSUE TITLE
建议划词翻译的右上角弹窗能够自定义位置，比如为左上角等位置

### ISSUE THREAD

**Issue by gherkin75** [crimx/ext-saladict#2161]
## 设备信息
- 操作系统: [windows11] 
- 浏览器版本: [edge 121.0.2277.128] 
- 沙拉查词版本: [v7.20.0] 

## 请描述目前使用沙拉查词遇到什么不便

划词查询的右上角弹窗按钮和edge的右上角快捷菜单重合了，不方便使用

## 理想情况下，沙拉查词应该怎么做

期望右上角弹窗的位置能够自定义调整

## 替代方案

暂时无替代方案

**Comment by crimx** [comment]
右上方的面板是浏览器提供的，动不了。
