### ISSUE TITLE
[特性建议] 增加点击图标查词的方式

### ISSUE THREAD

**Issue by quanbrew** [crimx/ext-saladict#217]
图标取词现在的行为是把鼠标移动到图标上开始查词，如果能增加点击悬浮按钮查词的方式就好了，类似 Chrome 的 Google 翻译扩展

<img width="197" alt="2018-10-11 11 17 35" src="https://user-images.githubusercontent.com/34709816/46778679-64a97780-cd47-11e8-80b1-3f17a7196019.png">

这不是非常重要的特性，只是个人更喜欢这样。我现在设成 command 触发取词也挺好的。

如果要有这个 feature 的话，希望图标也专门弄成有边界的按钮状。

非常棒的扩展，是我见过最好的翻译和查词扩展了，之前唯一的遗憾是不支持 Google 翻译，结果发现已经支持了，谢谢作者！

**Comment by crimx** [comment]
你好，谢谢建议！点击确实也是常见的操作方式，只是跟现有的悬浮方式在使用流程上大同小异，就不再做细分了。
