### ISSUE TITLE
刚刚自动更新了词典，怎么不能自动查词了。是我的问题吗？还是大家都出现了这个问题。

### ISSUE THREAD

**Issue by smlhd1993** [crimx/ext-saladict#218]
使用相关的问题请确保先看了 Wiki 《划词翻译食用方式》 <https://github.com/crimx/crx-saladict/wiki#wiki-content> 。

不能划词的网站请提供具体链接。刚安装扩展后已经打开的页面需要刷新一遍以加载词典。

如果是查词结果不正确或无结果，请先点击结果左上的词典图标跳转到词典网页，查看是否为自身网络问题。

因安全问题，chrome 商店页面、内置的 PDF 页面以及其它扩展的页面是不能划词的。可用点击图标或三按 ctrl 快速查词，本扩展自带 PDF 阅读器。

请根据模板描述问题，以便作者理解、定位和解决问题。

== 提交前将本行及已上内容删除，并填充以下模板 ==

- Saladict 版本

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）

- 类型：错误？建议？

- 划词模式？以及其它觉得相关的设置。

- 重现：提供详细的可重现问题的操作。

- 期待：理想情况下扩展应该怎么做？

- 实际：客观描述扩展实际上做了什么。

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
你好，请按模板描述问题。

**Comment by NEPDream** [comment]
我知道问题是什么，新版有一个bug，就是不能关闭动画过度效果，开启动画过度效果即可，关闭了就无法查词了，应该是作者更新时候把动画与展开查词的面板连接在一起导致的

**Comment by crimx** [comment]
@NEPDream 能按模板提供信息么，我测试没有发现问题。

**Comment by 990721830** [comment]
> @NEPDream 找到问题了，一会修复。

>>那个独立面板好像不能划词后按3ctrl触发了
还是说独立窗口无法触发的...
但是复制剪切板可以的...
能不能设置
1ctrl直接划词
2ctrl直接复制剪切板
3ctrl直接打开空白

**Comment by 990721830** [comment]
> @NEPDream 找到问题了，一会修复。

>>那个独立面板好像不能划词后按3ctrl触发了
还是说独立窗口无法触发的...
但是复制剪切板可以的...
能不能设置
1ctrl直接划词
2ctrl直接复制剪切板
3ctrl直接打开空白

**Comment by crimx** [comment]
@990721830 设置里关闭响应主页面划词。

**Comment by 990721830** [comment]
> @990721830 设置里关闭响应主页面划词。

>>
我点了独立窗口的话...
这打开关闭响应都无效...
还是说69内核的问题...
![2018 10 12 09 02 11](https://user-images.githubusercontent.com/25548230/46842025-c3312d00-cdfd-11e8-96bc-eafc1f72a2d8.gif)

**Comment by crimx** [comment]
@990721830 嗯，原来是从活跃 tab 中获取划词，现在焦点被查词面板 hijack 了，我看看怎么修改。

**Comment by fc4soda** [comment]
> 
> 
> 我知道问题是什么，新版有一个bug，就是不能关闭动画过度效果，开启动画过度效果即可，关闭了就无法查词了，应该是作者更新时候把动画与展开查词的面板连接在一起导致的

我也发现了，我第一次用，只是单纯的不喜欢页面上有动画效果。

**Comment by Maxico** [comment]
请问我用的默认安装，可为什么听不到发音呢？汉字取词的话，只能听到头一个字的发音！不知道是不是个例！谢谢

**Comment by crimx** [comment]
@Maxico 跟本 issue 无关的问题请另开 issue 反馈，并按模板填写信息。

另外附上以下信息

听不到发音是指鼠标放到喇叭上没有发声还是指没有自动发音，是某个词典的不行还是所有都不行。自动发音设置默认是关闭的。

汉字发音是指哪个词典。

**Comment by Maxico** [comment]
> @Maxico跟本问题无关的问题请另发问题反馈，并按模板填写信息。
> 
> 另外附上以下信息
> 
> 听不到发音是指鼠标放到喇叭上没有发声还是指没有自动发音，是某个词典的不行还是所有都不行。自动发音设置默认是关闭的。
> 
> 汉字发音是指哪个词典。

不好意思，刚接触这些东西，不懂规矩！见笑了。我已经从新发了，有空可以看一下
