### ISSUE TITLE
添加谷歌图片单词功能需求

### ISSUE THREAD

**Issue by xudaolong** [crimx/ext-saladict#22]
谢谢作者的不断研发...

其实我感觉学单词最好有个图片搭配的话 对识别和记忆有很大的帮助

能否实现
1.划词为单个单词的时候去搜索谷歌图片,并返回相似的或者最前面几张图片?
2.若没空的话我可以帮忙试着写一下?

**Comment by crimx** [comment]
这个想法可以，就是光是搜索图片意义不大，需要高一些的命中率。如拿维基百科的结果如何？

**Comment by longlife** [comment]
意义不大，还费时间和资源

**Comment by crimx** [comment]
[新版](https://github.com/crimx/ext-saladict/wiki/Saladict6)已发布，关闭遗留页面，如有问题欢迎开新 issue 反馈。
