### ISSUE TITLE
默认安装好像听不到发音！不知道是不是个例！

### ISSUE THREAD

**Issue by Maxico** [crimx/ext-saladict#220]
Saladict版本：6.17.1

平台：win10，Chrome浏览器

类型：我用的默认模式，划词后点击“小喇叭”听不到发音。汉字取词的话，只能听到头一个字的发音！
设置自动朗读也没效果，不过放“小喇叭”上，有喇叭播放效果。不知道是不是个例！

划词模式？以及其它觉得相关的设置。

重现：就直接安装，没有动其他设置。我也删了插件重新安装，还是这个问题！

期待：能发音就行，其实这个插件真的很不错了。你们维护起来肯定也很费神，如果是个例的话就算了吧。光是翻译就很足够用了。

实际：真没操作别的什么。

**Comment by crimx** [comment]
这是在哪个词典上的呢？

**Comment by crimx** [comment]
点击该词典的标题可以跳转到官网上，你可以在官网试试能不能发音。

**Comment by Maxico** [comment]
> 只有 google 的几个词典需要。我需要知道是哪个词典才能测试。

我刚才断了代理好像还不行，就有道一个能发音，还是英美发音的头一个能发音。其他词典都不能发音。进官网点击都没有声音

**Comment by crimx** [comment]
可以确认是网络问题。这个本扩展也没什么可以做的了。
