### ISSUE TITLE
鼠标悬浮取词能否添加shift取词按键

### ISSUE THREAD

**Issue by daimen1980** [crimx/ext-saladict#221]
目前只有ctrl 和 alt 以及直接取词
直接取词有时候会比较烦，不需要取词的时候经常会弹出解释界面
ctrl会跟ctrl+c的时候有冲突，有时候需要复制点内容的时候，会发现复制不上。
alt的话，在取词完毕，释放alt键的时候会弹出firefox 的菜单显示。

**Comment by firewiki** [comment]
感同身受，支持+1

**Comment by crimx** [comment]
可以考虑，非重要问题，我看有没有时间做。

**Comment by firewiki** [comment]
感谢crimx为“按住按键”模式添加shift键，不过该issue里说的是“鼠标悬浮取词”模式，可否考虑在“鼠标悬浮取词”模式下添加shift支持呢？多谢crimx的贡献。
