### ISSUE TITLE
建议：用户可设置关闭 “三按 ctrl 快速查词” ，“快捷查词”未勾选

### ISSUE THREAD

**Issue by Hosify** [crimx/ext-saladict#222]
- Saladict 版本
6.17.1

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）
windows 10
chrome 69.0.3497.100

- 类型：错误？建议？
  
  建议

- 划词模式？以及其它觉得相关的设置。

- 重现：提供详细的可重现问题的操作。

1. 已设置“快捷查词”未勾选启动（即关闭该功能）
2. “按住 ctrl+鼠标左键”打开几个网页链接，会弹出“查词界面”
3. 希望能关闭此功能

- 期待：理想情况下扩展应该怎么做？

  不应该弹出“查词界面”，或由用户设置是否启用“三按 ctrl 快速查词”

- 实际：客观描述扩展实际上做了什么。

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
收到，感谢反馈。
