### ISSUE TITLE
Firefox扩展组件ID差异求证

### ISSUE THREAD

**Issue by fengge-dev** [crimx/ext-saladict#2226]
## 设备信息
- 操作系统: [] win10
- 浏览器版本: [] Firefox v130.0.1
- 沙拉查词版本: [] v7.20.0

## 描述问题
2024.09.23从Firefox商店下载了沙拉查词扩展，发现该该扩展ID跟官网描述不同，希望求证此扩展是否是正版。

## 复现步骤
Firefox商店地址：https://addons.mozilla.org/zh-CN/firefox/addon/%E9%9D%9E%E5%AE%98%E6%96%B9-%E6%B2%99%E6%8B%89%E6%9F%A5%E8%AF%8D-%E8%81%9A%E5%90%88%E8%AF%8D%E5%85%B8%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

扩展组件ID差异对比：
![Snipaste_2024-09-23_12-04-05](https://github.com/user-attachments/assets/83337e35-f309-4f8e-931c-3dfd0729bc91)

## 期待的正常行为
无，仅求证

**Comment by Hynpothalamus** [comment]
https://github.com/Ayx03/UNOFFICIAL_saladict
这是这个项目的仓库，不是原作者发布。只是解决了火狐正式版没法安装的问题，现在正式版就算改about:config也没法安装了未签名的扩展了。
