### ISSUE TITLE
pdf 显示建议

### ISSUE THREAD

**Issue by OpenWaygate** [crimx/ext-saladict#223]
- Saladict 版本
6.17.1

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）
Windows 10 Enterprise Insider Preview, Version 1809
chrome Version 71.0.3573.0 (Official Build) dev (64-bit)

- 类型：错误？建议？
建议

- 划词模式？以及其它觉得相关的设置。
pdf 显示问题, 现在内置的pdf viewer 会把pdf 居中放置, 所以左右留下的空间较小, 当我查词的时候 词框会挡住一部分pdf, 但把词框调太小看着又不太方便, 所以能否添加一选项使 pdf 居左显示, 词框居右, 提升阅读体验. 谢谢!

- 重现：提供详细的可重现问题的操作。

- 期待：理想情况下扩展应该怎么做？

- 实际：客观描述扩展实际上做了什么。

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
你好，PDF 是另外一个插件不好调整。你这个情况可以使用独立窗口查词面板。见设置“快捷查词”。

**Comment by OpenWaygate** [comment]
懂了, 原来独立窗口是这样用的!
我现在是把浏览器放到桌面的左边, 再打开独立窗口并把它拖到浏览器外.
非常感想!

**Comment by crimx** [comment]
不客气！
