### ISSUE TITLE
PDF模式下选中单词会出现偏移

### ISSUE THREAD

**Issue by zcy2dd** [crimx/ext-saladict#225]
- Saladict 版本：6.18.1

- 平台：Chromium 67.0.3396.99

- 问题 ：在PDF阅读英语文章划词的时候，单词普遍会出现左移的情况，也就是我在视觉效果上选中那个单词，但是其实会选中的地方会向前偏移一点

- 重现：可重现

**Comment by crimx** [comment]
> 没有，因为我双击一个单词，在浏览器自带的那个PDF浏览工具下，他是正好选中那个单词，但是在翻译模式下，他会向左或者向右偏移一些

是的，因为 PDF 工具只保证视觉的还原。实在需要的话你可以提交 issue 给 [PDF.js](https://github.com/mozilla/pdf.js)，最好能提供文件供他们测试。

**Comment by zcy2dd** [comment]
好吧，谢了
