### ISSUE TITLE
【建议】独立窗口下能不能添加OCR图片识别

### ISSUE THREAD

**Issue by 990721830** [crimx/ext-saladict#228]
1丶嘤嘤嘤本可人儿又来了惹...
【响应主页面划词】
目前独立窗口下只有划词才可以秒触发...
比如浏览器程序外剪切板复制文字能不能实现秒触发呢?
现在是需要先点关闭再3ctrl才或者手动删除+ctrl+v+再点搜索按钮才可以...
<a href="https://drive.google.com/file/d/16wgSgHB_942lAuzjdkTh22hhRwCKIJ9M/preview" target="_blank">【这是问题的视频惹】</a>

2丶如果1能实现的话
能不能增加OCR图片识别功能
比如我本地截了一个图...
它不是会自动记忆到剪切板吗?
然后拓展自动从剪切板黏贴图片到搜狗OCR或者腾讯OCR接口...
然后再把识别的文字传输到独立窗口那个输入框...
接着自动翻译...

3丶接口你看一下
https://ai.qq.com/console/capability/detail/22
http://ai.sogou.com/project/ocr

4丶我目前用的熊猫ocr...
但是你的聚合翻译实在太好了...
https://github.com/miaomiaosoft/PandaOCR
你可以看看...
能不能融合一下什么的....

**Comment by crimx** [comment]
你好哈哈哈

1. 理论上可以实现，具体我得再看看。
2. OCR 目前没有计划支持。

**Comment by crimx** [comment]
不能监听浏览器以外的剪贴板事件，所以无法实现了。

**Comment by crimx** [comment]
@Noah1995 看看 #493
