### ISSUE TITLE
当鼠标移开时自动关闭查词界面

### ISSUE THREAD

**Issue by sculxb** [crimx/ext-saladict#229]
建议：如题，感觉看文章的时候鼠标移开，如果查词界面还是在的话会遮挡页面，如果去叉掉，又比较麻烦

**Comment by crimx** [comment]
你好谢谢建议，词典面板以外任意地方点一下或按 <kbd>Esc</kbd> 即可关闭，不考虑加入这个功能。

**Comment by solohsi** [comment]
个人感觉这个功能非常重要，1，esc其实是比较远的一个键，2，如果屏幕上很多超链很容易误点，3，参考以前的灵格斯，其实人在查词的时候，是会专心看着这个面板的，看完了才会动鼠标，其实我一直觉得，灵格斯的ctrl加右键点击，面板大小自动调整尽量小，移动鼠标面板消失，是最合理的屏幕取词模式

**Comment by crimx** [comment]
1. 我习惯了 Vim 所以 <kbd>Esc</kbd> 对我个人来说不是很远。
1. 「屏幕上很多超链很容易误点」这个情况还没遇到过。
1. 「是会专心看着这个面板的，看完了才会动鼠标」两者没有因果关系。沙拉查词是面向重度阅读的，过于容易关闭反而容易造成误触。

综上，目前的交互方式已经足够，新的操作更多是个人习惯的问题，适用率尚不明确，故不作实现，但欢迎其他人贡献代码。

**Comment by Forforfor-3** [comment]
是的 这个功能属于个人习惯 建议加入自定义配置项

**Comment by KnIfER** [comment]
建议考虑我的增强脚本 #1225
