### ISSUE TITLE
希望在打开网址不是.pdf结尾的网页也能启用pdf翻译

### ISSUE THREAD

**Issue by lauwingkin** [crimx/ext-saladict#23]
使用相关的问题请确保先看了 Wiki 《划词翻译食用方式》 <https://github.com/crimx/crx-saladict/wiki> 。

不能划词的网站请提供具体链接。刚安装扩展后已经打开的页面需要刷新一遍以加载词典。

如果是查词结果不正确或无结果，请先点击结果左上的词典图标跳转到词典网页，查看是否为自身网络问题。

因安全问题，chrome 商店页面、自带的 PDF 页面以及其它扩展的页面是不能划词的。可用点击图标或三按 ctrl 快速查词，本扩展自带 PDF 阅读器。

一个好的反馈格式
===============

- 平台：包括操作系统和 Chrome 版本
macos 10.13.2    63.0.3239.108

- 类型：错误？建议？
打开不是".pdf"为结尾的pdf网页，没办法启动pdf翻译，

- 重现：提供详细地操作来重现状况。
我打开例如http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=6685914 这类的pdf网页，无法使用pdf翻译

- 期待：理想情况下扩展应该怎么做？
chrome的“划词翻译” 插件可以达到这个功能（https://github.com/Selection-Translator/crx-selection-translate）可以参考看看

- 实际：客观描述扩展实际上做了什么。

- 额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

谢谢

**Comment by crimx** [comment]
这个其实是我在功能与性能上取的一个平衡。对所有网页都判断必然会对页面的速度有影响，而日常里面绝大部分情况都不是 PDF 链接，所以我觉得没必要都判断。

这类的链接你可以右键打开为 PDF，或者打开之后右键地址栏旁的沙拉查词图标。

**Comment by crimx** [comment]
https://github.com/crimx/crx-saladict/wiki#pdf

**Comment by lauwingkin** [comment]
感谢回复，你说到的这个操作我其实试过 在那个网址为例 是不行的（已附图），不知道是否可以建一个开关，让使用者自行选择这个“功能与性能上取的一个平衡” ？谢谢
![image](https://user-images.githubusercontent.com/26156322/34321506-73586494-e84b-11e7-93d1-37fe02568f9f.png)

**Comment by crimx** [comment]
[新版](https://github.com/crimx/ext-saladict/wiki/Saladict6)已修复，如有问题欢迎开新 issue 反馈。
