### ISSUE TITLE
【有个小bug】本来有换行符的文本翻译的时候无法自动换行

### ISSUE THREAD

**Issue by 990721830** [crimx/ext-saladict#230]
![snipaste20181024_113751](https://user-images.githubusercontent.com/25548230/47404833-692b5280-d781-11e8-8232-0ef6e4ed574b.jpg)
打开翻译网站输入是可以换行的...

**Comment by crimx** [comment]
谢谢反馈

**Comment by 990721830** [comment]
昨天ocr的反馈看到了吗?
我记得我应该发表了吧...
是你删掉了还是我发错软件区了.....

**Comment by crimx** [comment]
#228 已经关闭了，在 [closed](https://github.com/crimx/ext-saladict/issues?q=is%3Aissue+is%3Aclosed) 可看到。
