### ISSUE TITLE
github 页面翻译存在显示界面bug

### ISSUE THREAD

**Issue by Wisehit** [crimx/ext-saladict#234]
<details><summary>反馈说明</summary>

使用相关的问题请阅读 《使用方式》 <https://github.com/crimx/crx-saladict/wiki#wiki-content> 。

常见问题：

问: 词典第一次没结果，再点一下展开箭头又可以。
答: 这是由于网络不稳定导致的。可考虑在设置更换其它词典，或者更换 DNS 服务器。
    如果某个词典反复出现这种情况也可以作反馈，我会检查一下。

问: PDF 划词字符显示不对（如 f 与 ƒ）/ PDF 划词换行的单词粘连在一起。
答: PDF 文件是不保存语义的，它只负责让文档的样式保持一致。
    请先自行复制一遍原文粘贴到纯文本编辑器上看看是不是 PDF 的问题。

问: 某个词典一直无结果，那怕是查简单的单词。
答: 先排除自身网络问题。可先点击词典标题跳转到网页。
    如果打不开可用代理试试。再不行可作反馈。
    如果可以打开的话有可能是网站更新了，请作反馈。

问: 只有某个网站不能划词，其它可以。
答: 按下面模板反馈并提供具体链接和可复现的操作。
    注意刚安装扩展可能需要刷新一遍已打开的页面以加载词典。
    因安全问题，扩展商店页面、内置的 PDF 页面以及其它扩展的页面是不能划词的。
    可用点击图标或三按 ctrl 快速查词，本扩展自带 PDF 阅读器。

请根据模板描述问题，以便作者理解、定位和解决问题。

== 提交前删除下一行以及到以上*所有*内容，并填充下面模板 ==
</details>

- Saladict 版本

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）

- 类型：错误？建议？

- 划词模式？以及其它觉得相关的设置。

- 重现：提供详细的可重现问题的操作。

- 期待：理想情况下扩展应该怎么做？

- 实际：客观描述扩展实际上做了什么。

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
你好，无法定位问题。
