### ISSUE TITLE
点多次红心会重复添加单词

### ISSUE THREAD

**Issue by longdeqidao** [crimx/ext-saladict#245]
- Saladict 版本
6.20.1

- 平台：
MacOS Mojave 10.14.1
Chome 70.0.3538.77&Firefox 63.0.1

- 类型：错误

- 重现：点红心多次，会重复添加单词到生词本，而不是第二次消除红心删除单词。

- 期待：点红心第一次添加，第二次取消，以此类推。

**Comment by crimx** [comment]
这是因为你开启了红心时显示编辑框。Saladict 允许多次添加是因为单词可以存在不同上下文。

如果希望取消这种行为，可以关闭红心时显示编辑框。

**Comment by longdeqidao** [comment]
红心单词时弹出编辑面板，这一项是没有勾选的。
我就是在弹出的查询面板上多次点红心，然后单词本会有多个一样的单词，上下文也是一样的。然后如果很快地点击红心，会直接跳到生词本。

P.S. 小问题，如果觉得没问题可以Close，钉住查词的feature太棒了，目前用过最好的查询extention~

**Comment by crimx** [comment]
关闭了确实还会重复添加，我看看是什么地方出问题。

双击是打开生词本。

**Comment by crimx** [comment]
定位到问题了。原因在于取消红心后依然获取翻译，导致得到翻译后又添加了一遍。稍后会提供修复。
