### ISSUE TITLE
如何使用快捷键启用禁用划词

### ISSUE THREAD

**Issue by Witee** [crimx/ext-saladict#246]
MacOS 10.14.1
Chrome Version 70.0.3538.77 (Official Build) (64-bit)

如题，现在貌似只能使用点击插件图标，再点击最下方的“启动划词”开关。

**Comment by crimx** [comment]
请看 wiki

**Comment by crimx** [comment]
https://github.com/crimx/ext-saladict/wiki

**Comment by Witee** [comment]
感谢回复。

我现在设置快捷键只是能操作鼠标点击扩展图标，我是想有个快捷键可以操作划词开关。

**Comment by crimx** [comment]
弹出框的“启动划词”即是对应快捷键的“鼠标划词翻译开关”。

**Comment by Witee** [comment]
```
Activate the extension

Open Google Translate
 
Open current PDF in Saladict

Open or highlight standalone dict panel
 
Open Youdao Translate
 
Toggle inline translator
 
Toggle instant capture

```

以上是 `chrome://extensions/shortcuts` 可以设置的所有快捷键，是不是我的版本问题？
`Chrome Version 70.0.3538.77 (Official Build) (64-bit)`

**Comment by Witee** [comment]
我操作系统是英文的，是不是没有提供英文的设置？

**Comment by crimx** [comment]
`Toggle inline translator`

**Comment by Witee** [comment]
感谢，我的英文太差了。
这是我用过的最好的翻译插件。

**Comment by crimx** [comment]
谢谢！在本扩展设置中可以更换语言的。

**Comment by Witee** [comment]
找到了，谢谢。
