### ISSUE TITLE
[建议]单词翻译和句子翻译的操作方式整合

### ISSUE THREAD

**Issue by LongerPro** [crimx/ext-saladict#248]
- Saladict 版本：6.20.2

- 平台：Win10，Chrome 70.0.3538.102

- 类型：建议

- 查词模式

- 重现：在“查词模式”中，勾选“直接搜索”和“鼠标悬浮取词”，并设置悬浮取词按键为 Shift 。其他选项不勾选。

- 期待：在不勾选直接搜索、不设置悬浮取词按键的情况下，根据选择的内容是单词还是句子，进行对应的翻译。

- 实际：
  - 设置悬浮取词按键
    - 单词：按下悬浮取词按键，并把鼠标悬浮到对应单词上，显示翻译结果。
    - 句子：选中整个句子，显示翻译结果。
  - 不设置悬浮取词按键
    - 单词：正常显示。
    - 句子：无法选中句子。总是在鼠标离开单词后取消选中内容，又变为悬浮选中下一个单词。

- 额外信息：是否可以根据鼠标按键的状态，进行区分，避免“不设置悬浮取词按键”时，“句子”中描述的现状。
  - 悬浮在单词上时，鼠标按键都没有按下，这时候就只可能是翻译单词，因为鼠标按键没按下的情况下无法选中句子。
  - 选中句子开始时，需要按下鼠标左键；结束后，需要释放鼠标左键，这时候就是翻译所选内容。可能是句子，也可能在这个操作过程中只选中了一个单词。

简单说，就是什么都没按，就翻译悬浮在的单词上；按下鼠标选中了，就翻译选中的内容。

**Comment by Oldmoooon** [comment]
另外，建议增加优化，对单词和句子使用不同的词典，比如选中句子使用谷歌翻译，选中单词使用柯林斯词典

**Comment by crimx** [comment]
你好，感谢建议！可以对每个词典设置划词长度的。

而主问题提的两个方式，我认为操作过于复杂了，让其它用户理解这样的方式也有些麻烦。所以目前没有精力去实现这样的功能了。

**Comment by 990721830** [comment]
亲我顺便说一下搜索搜狗接口无法显示了...
点击打开页面是好的...
还有那个输入框能不能让它随文字长短自动适应高度?

**Comment by crimx** [comment]
@990721830 

搜狗 api 更新了，我得抽时间研究一下。

你说的是绿色的搜索框么，绿色条下方有一个长长的按钮看见没，点一下就展开了多行编辑框。

另外请不要插楼无关的问题，可以新建一个 issue。

**Comment by 990721830** [comment]
其实是指白色的那个...
还有一个问题是白色输入框能否增加长按enter或者shift+enter直接搜索
目前按一下enter是换行..

**Comment by crimx** [comment]
自动改变高度其实也是可以的，但目前没有计划实现。你可以设置为展开一次，这样搜索完了就合上了。然后需要不停写大段文字的时候切换到翻译情景模式保持展开。

**Comment by 990721830** [comment]
我就是为了一直显示才开的...
先讲究吧...
还有就是未来有空的话能不能UI弄个黑夜皮肤(深灰+浅白字)...
或者让用户自定义css代码修改....

**Comment by Yonkon111** [comment]
搜狗翻译和有道翻译在翻译句子的时候没反应了，不能翻译了，其他的可以
