### ISSUE TITLE
建议：添加同义词查词&疑问：单词本如何查看和导出

### ISSUE THREAD

**Issue by tzcnancy** [crimx/ext-saladict#250]
- Saladict 版本:6.21.1
- 平台：包括win10和 Chrome 70.0.3538.102

- 类型：建议
- 期待：添加同义词查词网站https://www.thesaurus.com/

- 类型：疑问
- 问题：单词本在哪里查看以及导出？

**Comment by crimx** [comment]
1. 你好，目前没有计划为同义词单独提供词典。几大英英词典都有 thesaurus 。
2. <https://github.com/crimx/ext-saladict/wiki#search-history>

**Comment by tzcnancy** [comment]
感谢回复，谢谢您制作的超级用心的词典。我再研究一下用法~
