### ISSUE TITLE
[Bug] 多窗口下已打开pdf时的tab跳转错误

### ISSUE THREAD

**Issue by sixleaveakkm** [crimx/ext-saladict#251]
- Saladict 版本
6.21.1

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）
Ubuntu 18.04 Chrome Version 70.0.3538.67 (Official Build) (64-bit)

- 类型：错误？建议？
Bug

- 重现：提供详细的可重现问题的操作。
chrome多窗口下，
第一个打开了a,b,c三个tab
第二个打开了e,d,f三个tab

**其中假定`c`为原本chrome自带的pdf预览**
** `d`为saladict打开的对应`c` pdf页面**

在第一个窗口`c` tab中按下“Open current PDF in Saladict”对应快捷键时会跳转到b

将第二个窗口中tab顺序调整为d,e,f后回到窗口1中的`c` tab按下“Open current PDF in Saladict”对应快捷键时会跳转到a

- 期待：理想情况下扩展应该怎么做？
跳转到另一窗口，显示对应pdf的tab

- 实际：客观描述扩展实际上做了什么。
只找到了对应tab的编号，并在当前窗口中打开对应该编号的tab

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
感谢反馈
