### ISSUE TITLE
[Feature Request] 沪江日语词典支持

### ISSUE THREAD

**Issue by pepapu** [crimx/ext-saladict#252]
看到#156 可以使用weblio的词典了，希望也能添加一些中日词典。

https://www.hjdict.com/
沪江日语词典是目前最好的日中词典，
平时难度高一点的词汇一般都直接查日日词典和google，都不会去查日中词典，
但沪江的在线日语词典却可以做到和日日词典互补程度的好用，完全超越了以往对日中词典的印象。
（甚至连活用都能查，虽然目前沙拉内置的weblio也能查活用，“活用”指的是日语词形变化相关的语法名词）
沪江app上的api有加密，只能手动爬。
同时这个词典其实是2本词典，有时候没有中文释义的词沪江会直接日日词典的解释（这是这本词典的另一个厉害的地方）。蓝色背景和底下详细释义要爬的话应该同时获取，模板稍微有点混乱，还得多找几个词测试。
详细释义有些是《现代日汉双解词典》里的解释（和外教社合作）

同时建议weblio的日中词典https://cjjc.weblio.jp/也可以放入。

**Comment by crimx** [comment]
谢谢推荐，这个可以添加。

能提供一些典型的单词以及需要获取的部分么。我就照着爬了。

**Comment by crimx** [comment]
那要不我整个一起抓好了，我看了这些例子都是上部蓝色部分以及下部的“详细释义”两块。

中日价值不大那只实现日中吧。

**Comment by crimx** [comment]
或者默认日中，我再提供个中日的按钮。

**Comment by pepapu** [comment]
我觉得没必要，实现起来简单的话也无妨。提供按钮是个不错的方法。

还有一种情况是查不到的词有些会出现建议选项 
比如 https://www.hjdict.com/jp/jc/磨りガラ 
会跳转成 https://www.hjdict.com/notfound/jp/jc/磨りガラ

可以把建议选项 放在查询结果里，点击跳转到词典网页或者应用内查词

**Comment by crimx** [comment]
嗯，这个会加上去
