### ISSUE TITLE
能否支持一下设置中文不查询？只有选中英文或者设置的语言才查询？

### ISSUE THREAD

**Issue by ttxhxz** [crimx/ext-saladict#255]
想查英文翻译的时候不用多点一下图标查询，可以直接搜索，但是设置成直接搜索之后，我想复制中文的时候也自动跳出一堆查询，就很苦恼，能否多加个如果识别到是全中文的话，就不自动搜索和跳出小图标？

**Comment by crimx** [comment]
请自行看设置“语言支持”。

**Comment by ttxhxz** [comment]
原来语言支持是这个意思，好吧
