### ISSUE TITLE
鼠标经过网页上的汉字，文字会变为选中状态

### ISSUE THREAD

**Issue by maggiedot** [crimx/ext-saladict#257]
- Saladict 版本：6.22.0

- 平台：WIn10，Firefox

- 类型：看上去是文字被选中的效果，但实际鼠标没有任何点击操作。这样也不能在网页选择复制文字了。中英文页面都是这样，把选项都试了一遍，也没有效果。我是Firefox浏览器，插件上显示off

- 划词模式？以及其它觉得相关的设置。[config-1544095192667.zip](https://github.com/crimx/ext-saladict/files/2652856/config-1544095192667.zip)

- 重现：导入以上设置，打开网页，鼠标滑过文字。

- 期待：在插件未激活时，可以选择网页上的文字。

- 实际：光标经过文字时，文字变为选中状态。移走光标，选中状态取消。

- （可选）额外信息： 控制台无输出。

**Comment by crimx** [comment]
你在默认模式下开启了“悬浮取词”。要么关闭，要么配合快捷键开关，右上的图标点开下面也有开关。

**Comment by maggiedot** [comment]
感谢反馈，原来是设置问题。这可能是我用过的最好的查词/翻译应用了，赞一个！

**Comment by crimx** [comment]
谢谢！
