### ISSUE TITLE
沪江词典chrome下第一次查询需要点开网页，firefox下无法查询

### ISSUE THREAD

**Issue by pepapu** [crimx/ext-saladict#259]
1. chrome下第一次查询需要点开网页

    现象：用saladict第一次无法查词，需要点开一次沪江页面就能正常查词了。

    原因：据观测，应该是沪江的反爬机制，第一次搜索的时候会跳转到https://www.hjdict.com/notfound/jp/jc/xxxx ，url中间会多个 **notfound** ,接着会生成cookies，接下来才能正常查词。

    经过反复实验，主要影响的是2条cookie ，Domain为`.hjdict.com`的 `HJ_UID` 和 `HJ_SID` ，这2条存在的情况下才能正常搜索。

    同时即使url中间带notfound，也能返回正确结果，比如https://www.hjdict.com/notfound/jp/jc/動画 ， 也能搜索到。

     `HJ_SID` 的有效期只有30分钟，修改有效期无效，每次请求都会刷新这条的有效期。

2. firefox下无法查询

    如图，效果如图1，同时点击一次沙拉内 `沪江小d` 跳转到沪江后，第二次这个位置就无法点击了（点击后如图2，毫无反应）。
    
    图1：
    ![salahujiangfirefoxbug](https://user-images.githubusercontent.com/26113175/49695354-cca7fd00-fbd4-11e8-8a9b-ffef92e4a5cd.gif)
    
    图2：
    ![salahujiangfirefoxbug2](https://user-images.githubusercontent.com/26113175/49695358-d3cf0b00-fbd4-11e8-8dea-49c739d0eea1.gif)

**Comment by crimx** [comment]
请问你有时间帮忙修复 1 吗。

**Comment by pepapu** [comment]
2 后面半段确实是这样，关掉已经打开的就行了。主要还是firefox下无法使用

**Comment by pepapu** [comment]
1也顺便做了张图。js不是很懂，复制粘贴流，不确定能不能帮，我会试着看下源码。
![salahujiangbug](https://user-images.githubusercontent.com/26113175/49695588-61602a00-fbd8-11e8-8dcc-13efc9b1fe31.gif)

**Comment by crimx** [comment]
没关系，谢谢你详细的调查，很有用，可以加快我 debug。
