### ISSUE TITLE
希望生词本能不重复添加单词

### ISSUE THREAD

**Issue by dream-jx** [crimx/ext-saladict#26]
目前如果添加了一个单词到生词本的话，如 Hello，那么下次再遇到添加到生词本的话，在生词本里就有2个 Hello 的单词，希望一个单词只要添加到生词本，下次再点击可以选择移除或者其他操作，就是不要重复出现在生词本中

**Comment by crimx** [comment]
这是因为不同的上下文，同个上下文还是只有一个的

**Comment by dream-jx** [comment]
好的，是不同上下文，但是如果是导出文本呢，导出文本的话还是会有重复的单词，能否把重复的单词去掉呢

**Comment by crimx** [comment]
这个可以交由其它软件去处理，一般带导入功能的都会自动识别

**Comment by dream-jx** [comment]
那好吧，谢谢了！

**Comment by dream-jx** [comment]
那好吧，谢谢了
