### ISSUE TITLE
建议：可以在面板内继续划词 无限下去比如esc关闭最近打开一层

### ISSUE THREAD

**Issue by wjtien** [crimx/ext-saladict#261]
- Saladict 最新

- 平台：chrome

- 类型：建议

- 期待：可以在弹出来的区域再划词。如果我把插件面板弄到最左边，那么，我在第一个面板内点击划某个单词，在第一个的旁边紧挨着，继续弹出来一个面板。如果区域不够了就覆盖最后一个位置，当按esc时，关闭最新一个，把被覆盖的显示出来。直到全部关闭。

**Comment by crimx** [comment]
谢谢你的建议，这个交互贼复杂了。Saladict 本身就支持面板内划词，见设置。搜索框左边也有历史回退键。

**Comment by wjtien** [comment]
> 谢谢你的建议，这个交互贼复杂了。Saladict 本身就支持面板内划词，见设置。搜索框左边也有历史回退键。

是呀。如果在新面板内打开的话，回退还是会重新加载。
如果在面板内划词新单词时原来的那个是隐藏起来的，当按esc关掉最新被搜索的那个单词面板，恢复上一个面板。
缓存当前打开面板之后查找的单词（回退之后再次划词不用加载了），完全退出之后清空缓存。
多个面板的话，主要还是好对比。有的词意思太多了。。。。。

**Comment by crimx** [comment]
一个页面中显示多个面板需要对当前架构做较大改动。或许你可以结合独立窗口的快捷查词面板使用。

**Comment by wjtien** [comment]
> 一个页面中显示多个面板需要对当前架构做较大改动。或许你可以结合独立窗口的快捷查词面板使用。

可以缓存单词结果最好了，建议加一个在面板内鼠标中键（滚轮按下）查词，右键返回。这样如果有返回那么是很快的。。。。。

**Comment by wjtien** [comment]
所以说建议仅仅只是建议 手动滑稽
