### ISSUE TITLE
有道翻译字符数限制问题

### ISSUE THREAD

**Issue by innerpeace715** [crimx/ext-saladict#262]
- Saladict 版本 6.22.1

- 平台：Win 10 Chrome 55.0.2883.87

- 类型：建议

- 划词模式

- 重现：采用有道词典（翻译），划词翻译整段文字

- 期待：完整翻译整段文字

- 实际：由于https://dict.youdao.com/w/搜索框字符数限制，只翻译了在字符数限制内的部分文字

- （可选）额外信息：建议增加http://fanyi.youdao.com/或替代https://dict.youdao.com/w/，以达到类似谷歌翻译整段文字的效果

**Comment by crimx** [comment]
你可以在网页上右击使用有道网页翻译

**Comment by crimx** [comment]
翻译的服务没时间再一一破解啦
