### ISSUE TITLE
鼠标悬浮取词导致输入框无法输入

### ISSUE THREAD

**Issue by AlixChiong** [crimx/ext-saladict#264]
- Saladict 版本
Saladict  v6.22.2

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）

win 10，猎豹浏览器 v6.5.115.18629.8004

- 类型：错误？建议？
错误

Saladict 开启了鼠标悬浮取词并设置为直接取词后，浏览器网页中输入框都会失去焦点导致无法输入，也无法选择输入框中内容，关闭鼠标悬浮取词并刷新网页后网页输入框才恢复正常，开启鼠标悬浮取词后可复现此问题。

**Comment by crimx** [comment]
直接查词下请结合快捷键开关使用悬浮取词。
