### ISSUE TITLE
[Feature Request] Chrome app 支持

### ISSUE THREAD

**Issue by memphis147** [crimx/ext-saladict#265]
你好，请问有没有可能支持Chrome app，这样可以拖至桌面不用打开chrome而直接使用。
目前有勉强可行的操作办法就是打开chrome以后按三次ctrl调出单独的查词界面，在关掉chrome。
谢谢！

**Comment by crimx** [comment]
Chrome APP 在除 Chrome OS 其它平台已被抛弃，就不再开发了。
