### ISSUE TITLE
词典兼容性问题

### ISSUE THREAD

**Issue by sonyxu** [crimx/ext-saladict#266]
剑桥词典兼容性问题，应该是剑桥词典网页版改版发音按钮做了更改，现在在插件内只有音标没有发音按钮。请检查升级
eg
![snipaste_2018-12-20_03-21-25](https://user-images.githubusercontent.com/25625821/50243014-ecc29200-0406-11e9-9830-98e2c8559905.png)

**Comment by crimx** [comment]
已提交发布，等待浏览器更新
