### ISSUE TITLE
更新后，在线网站pdf出现打开错误

### ISSUE THREAD

**Issue by drinmo** [crimx/ext-saladict#272]
- Saladict 版本
6.22.6

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）
Chrome 71.0.3578.98（正式版本）（64 位）

- 类型：错误？建议？
错误

- 划词模式？以及其它觉得相关的设置。
pdf模式

- 重现：提供详细的可重现问题的操作。
打开任意在线pdf文件，右键扩展插件选择“在PDF阅读器中打开”，显示只支持本地PDF。

- 期待：理想情况下扩展应该怎么做？
回到原来的版本一样，可以对在线PDF文件使用PDF阅读器功能

- 实际：客观描述扩展实际上做了什么。
扩展告知使用者必须打开本地PDF，不支持在线PDF

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。
截图：https://imgur.com/LDOXeMB

**Comment by crimx** [comment]
你能提供出现问题的网站吗。

**Comment by drinmo** [comment]
任意在线pdf，例如这个：https://samtools.github.io/hts-specs/SAMv1.pdf

**Comment by crimx** [comment]
PDF 右键逻辑现修改为：

1. 图标上的右键菜单，当当前页面链接以 PDF 结尾时加载该链接，否则打开默认界面。
2. 页面上的右键菜单，总是加载当前页面。

**Comment by drinmo** [comment]
在扩展的选项设置里，重置设定后问题解决。

**Comment by crimx** [comment]
应该是刚才浏览器更新了扩展
