### ISSUE TITLE
选定一个长文本后报错

### ISSUE THREAD

**Issue by firewiki** [crimx/ext-saladict#273]
<details><summary>反馈说明</summary>

使用相关的问题请阅读 《使用方式》 <https://github.com/crimx/crx-saladict/wiki#wiki-content> 。

常见问题：

问: 词典第一次没结果，再点一下展开箭头又可以。
答: 这是由于网络不稳定导致的。可考虑在设置更换其它词典，或者更换 DNS 服务器。
    如果某个词典反复出现这种情况也可以作反馈，我会检查一下。

问: PDF 划词字符显示不对（如 f 与 ƒ）/ PDF 划词换行的单词粘连在一起。
答: PDF 文件是不保存语义的，它只负责让文档的样式保持一致。
    请先自行复制一遍原文粘贴到纯文本编辑器上看看是不是 PDF 的问题。

问: 某个词典一直无结果，那怕是查简单的单词。
答: 先排除自身网络问题。可先点击词典标题跳转到网页。
    如果打不开可用代理试试。再不行可作反馈。
    如果可以打开的话有可能是网站更新了，请作反馈。

问: 只有某个网站不能划词，其它可以。
答: 按下面模板反馈并提供具体链接和可复现的操作。
    注意刚安装扩展可能需要刷新一遍已打开的页面以加载词典。
    因安全问题，扩展商店页面、内置的 PDF 页面以及其它扩展的页面是不能划词的。
    可用点击图标或三按 ctrl 快速查词，本扩展自带 PDF 阅读器。

请根据模板描述问题，以便作者理解、定位和解决问题。

== 提交前删除下一行以及到以上*所有*内容，并填充下面模板 ==
</details>

- Saladict 版本

6.22.7

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）

firefox

- 类型：错误？建议？
错误

- 划词模式？以及其它觉得相关的设置。
报错截图
![image](https://user-images.githubusercontent.com/31975616/50686278-abadbd00-1057-11e9-9058-87a496a1c75a.png)
我选定的文本，本来是想选定文本复制的，没想到刚选定就报错了
![image](https://user-images.githubusercontent.com/31975616/50686288-b23c3480-1057-11e9-8a93-6ec87aa18d87.png)
我的设置
![image](https://user-images.githubusercontent.com/31975616/50686317-d3048a00-1057-11e9-9da1-e00fca475728.png)
![image](https://user-images.githubusercontent.com/31975616/50686323-dc8df200-1057-11e9-946b-23ab359bff8f.png)

- 重现：提供详细的可重现问题的操作。

- 期待：理想情况下扩展应该怎么做？

- 实际：客观描述扩展实际上做了什么。

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
你好，你的 Firefox 版本是多少

**Comment by firewiki** [comment]
firefox版本 64.0

**Comment by firewiki** [comment]
75415f30dd1b568425af80063aae79f1 ep_server201901031632.tgz f75f805c5c319fealcca7ce3d16233cf

**Comment by crimx** [comment]
我认为这是浏览器的问题，也许在安装扩展过程中出错了，一些文件被污染。Saladict 即便内部报错也一般不会让网页崩溃。

**Comment by crimx** [comment]
代理无关，对于非代理管理的扩展来说代理就是透明的。

**Comment by firewiki** [comment]
lm_server201901041930.tgz 0e037c5a4565efbc8be1e20804b32623 ep_server201901041930.tgz 8f7dede4864a4568b5daf72d7ab41538

**Comment by firewiki** [comment]
1. 测试用例：只留下saladict一个扩展，测试会报错
2. 测试用例：把系统代理服务器设置成无代理，测试也会报错

**Comment by crimx** [comment]
你的用例我在 Chrome 和 Firefox 都测试了，并搭建了本地服务器，都没发现问题。

**Comment by crimx** [comment]
很可能是该网站禁止插入 iframe

**Comment by crimx** [comment]
你如果按三遍 ctrl 打开了独立窗口，然后按住 ctrl 划词，看会不会崩溃。

**Comment by crimx** [comment]
如果确定是网站问题的话，可以在 Saladict 设置中给该网站（或匹配该类网站）添加黑名单。

**Comment by firewiki** [comment]
因为文本内容有点敏感，你提供一下邮箱，我把内容发你。

**Comment by crimx** [comment]
点击我的头像就可以看到。另外这个已经可以确定不是文本的问题了。要么是浏览器的问题，要么是网站的问题，后者可能性比较大。

**Comment by firewiki** [comment]
是文本问题，我把文本贴到QQ邮箱，也会报错。

**Comment by crimx** [comment]
如果是这样的话，现在最有可能是浏览器问题，或者跟其它扩展有冲突，因为目前只有你的一台电脑出现这样的问题。

**Comment by firewiki** [comment]
文本已经发你邮箱了。
如果是跟其他扩展冲突，但我把其他扩展都禁用了啊，只留下saladict一个扩展。
崩溃的时候什么图标和查词面板都没有出现，就相当于是进入死循环的感觉，然后浏览器发现扩展耗时长，就提示错误了。

**Comment by crimx** [comment]
感谢你的例子。现在我的初步猜测是 Saladict 获取上下文化了过多时间，这也可以解释为什么你单独粘贴出来就没有问题了。由于这个情况属于比较特殊，我晚些再来修复。目前我推荐将生成这些日志文件的网站加入 Saladict 黑名单。

**Comment by firewiki** [comment]
多谢，期待您的修复。

**Comment by firewiki** [comment]
刚试了一下把网站加入黑名单，看起来不起作用，仍然会报错。
![image](https://user-images.githubusercontent.com/31975616/50750244-f1989a00-127e-11e9-84fd-8e5c333fd031.png)

**Comment by crimx** [comment]
先禁用 Saladict 吧 :sweat_smile: ，修复了这里会通知。

**Comment by crimx** [comment]
修复已发布。这是由于前文太长，匹配上下文的正则花了过多时间。

**Comment by firewiki** [comment]
这更新效率，太赞了。
