### ISSUE TITLE
偶尔查词时(比如GitHub上查词)，会自动把网页内容弹至最顶部。

### ISSUE THREAD

**Issue by aa476822485** [crimx/ext-saladict#276]
- Saladict 版本
6.22.7

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）

- 类型：错误？建议？

- 划词模式？以及其它觉得相关的设置。

- 重现：提供详细的可重现问题的操作。
Github双击查词

- 期待：理想情况下扩展应该怎么做？
保持原本网页浏览位置

- 实际：客观描述扩展实际上做了什么。
偶尔查词时(比如GitHub上查词)，会自动把网页内容弹至最顶部（网页滑动条至最上方）。

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by aa476822485** [comment]
![image](https://user-images.githubusercontent.com/9399639/50760081-b9ef1980-12a1-11e9-83c0-c327af90ea4a.png)
cha'ci查词位置。

![image](https://user-images.githubusercontent.com/9399639/50760100-c7a49f00-12a1-11e9-952d-1143e1b0c486.png)

窗口位置

点击网页的页面任意位置，窗口内容跳至顶部。
![image](https://user-images.githubusercontent.com/9399639/50760173-ff134b80-12a1-11e9-8fe5-74e9e5b96127.png)

**Comment by aa476822485** [comment]
就是，我在网页下方查词。沙拉的页面始终在网页顶部显示（我并不能看到沙拉的内容页面），点击任意位置后，网页跳转至滑动条顶部（跳转至顶部沙拉查词页面，因为点击了网页其他位置，查词页面也关闭了）。
必然重现。

**Comment by crimx** [comment]
你好，我按这个步骤测试了没有出现这样的情况，且 Saladict 也没有操作全局的滚动。可以看看是不是其它扩展的原因。

**Comment by crimx** [comment]
看到你应该是用了一些修改样式的扩展。

**Comment by aa476822485** [comment]
好的，我把其他扩展关闭再试试。麻烦了~

**Comment by aa476822485** [comment]
关闭其他插件后就没这问题了。 再次开启插件，也没有这个问题了。估计是样式扩展的插件造成了冲突。（GitHub首页没放打赏:coffee:的二维码，Wiki上找到了，请大佬一杯咖啡，麻烦了大佬的时间~）

**Comment by crimx** [comment]
解决了就好，谢谢你！

**Comment by aa476822485** [comment]
居然是一个网页黑色模式护眼插件的冲突。。。
![image](https://user-images.githubusercontent.com/9399639/50761691-ffade100-12a5-11e9-9f16-d9dbfafda8f2.png)

**Comment by crimx** [comment]
嗯，这类插件以及有的阅读模式类的插件会比较粗暴地修改原网页。
