### ISSUE TITLE
拓展导致某些网页内对话窗意外关闭

### ISSUE THREAD

**Issue by haoye999** [crimx/ext-saladict#277]
- Saladict 版本 6.22.7

- 平台：
    Windows 10/ Ubuntu 18.04 LTS 
    Chrome 71.0.3578.98

- 类型：错误

- 错误：
在打开[stackedit编辑器](https://benweet.github.io/stackedit.js)时，点击上方功能按钮导致对话框退出，停用此拓展后恢复。

**Comment by crimx** [comment]
谢谢反馈，会在下个版本修复。

**Comment by crimx** [comment]
修复已发布
