### ISSUE TITLE
java doc 无法划词翻译

### ISSUE THREAD

**Issue by lsldragon** [crimx/ext-saladict#278]
发现在 Java doc 的 界面下划词不能出现那个水果碗 比如apache common lang 的 doc :
https://commons.apache.org/proper/commons-lang/javadocs/api-release/index.html

Win10 系统
火狐和谷歌浏览器都有这种情况

**Comment by crimx** [comment]
同 #142 ，不再兼容严重过时的网页。可以用独立窗口的查词面板响应划词。
