### ISSUE TITLE
可否增加搜狗翻译对网页翻译的支持？

### ISSUE THREAD

**Issue by depthsky2016** [crimx/ext-saladict#279]
Hi~感谢你开发了这个插件，就贴合用户使用习惯和细节来看，是一款非常优秀的产品。

有一个不情之请，不知道是不是多数用户的诉求。

在对比和使用了多家网页翻译引擎之后，发现只有搜狗翻译的准确度和还原度最高，基本上能保持原义，但无奈搜狗网页翻译没有 chrome 插件版，所以不知道有没有可能开发一个基于搜狗翻译引擎的 chrome 插件版，采用彩云小译的实现方式，可以是付费使用，谢谢。

期待回复。

**Comment by crimx** [comment]
你好，彩云小译有官方维护的扩展。

**Comment by crimx** [comment]
设置中 -> 右键 -> 添加搜狗网页翻译

**Comment by depthsky2016** [comment]
收到，看到了实现方式，谢谢。但是需要打开新的页面跳转略微有些不便，如果能封装成本页面直接翻译就好了。

**Comment by crimx** [comment]
搜狗翻译应该没有这方面的实现
