### ISSUE TITLE
能否支持网页翻译

### ISSUE THREAD

**Issue by cat2mao** [crimx/ext-saladict#281]
- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）
Firefox 版本

- 类型：错误？建议？
建议

- 期待：理想情况下扩展应该怎么做？
网页翻译

- 实际：客观描述扩展实际上做了什么。
能够翻译全屏那就好了

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
请阅读完 wiki 使用说明后，如依然有疑问，按模板反馈。
