### ISSUE TITLE
免空（Onedrive、Dropbox）下載 PDF 類型檔案時沒反應

### ISSUE THREAD

**Issue by YuiTatsumi** [crimx/ext-saladict#282]
哈囉，不好意思，我又來了，最近發現使用沙拉查詞來閱讀本地 PDF 真的很方便 XD
然後，就意外在我的 **OneDrive** 下載檔案時，發現下述這個問題。

- Saladict 版本 6.22.8

- 平台：Firefox 64.0.2 (64 位元) Windows 10 1809

- 类型：免空（**OneDrive**、**Dropbox**）下載 PDF 類型檔案時沒反應。

- 划词模式？以及其它觉得相关的设置：n/a

- 重现：這個 <kbd>使用本應用程式瀏覽 PDF</kbd> 選項如果打勾的話，我在上述等免空下載檔案就沒反應；取消打勾，則就可以順利下載 PDF 檔案。

- 期待：這多少影響到免空使用體驗了，自然是期待能不去影響到免空下載東西最好囉。

- 实际：n/a

**Comment by crimx** [comment]
你可以在设置给该j链接添加 PDF 黑名单

**Comment by YuiTatsumi** [comment]
喔喔喔~ 真的耶！我設了黑名單像這樣子就可以了，謝謝作者大大

<kbd>**OneDrive**</kbd>：`*://*.1drv.com/*`

<kbd>**Dropbox**</kbd>：`*://*.dropbox.com/*`

**Comment by crimx** [comment]
不客气 :+1:

**Comment by fireattack** [comment]
**OneDrive**
