### ISSUE TITLE
[issue]gitbook文档下载冲突

### ISSUE THREAD

**Issue by wstlxx** [crimx/ext-saladict#284]
- Saladict 版本 ：6.22.8
- 平台：Firefox
- 类型：错误
- 重现：在gitbook上点击下载电子书会跳转到本插件
- 期待：期待是不会跳转
- 实际：下载地址不是普通文件名结束，插件冲突导致浏览器不能下载

-还有另一个问题，偶尔出现沙拉图标消失不了，挡住页面的情况，不确定如何能稳定触发。这个问题倒不是很要紧。

**Comment by crimx** [comment]
希望特定网站直接下载请按使用说明添加 PDF 黑名单。
