### ISSUE TITLE
现有可添加的英语词典都是学习型的词典，收词量有限，希望增加对更多权威词典网站的支持

### ISSUE THREAD

**Issue by funnybones2015** [crimx/ext-saladict#285]
</details>

- Saladict 版本：6.22.8

- 平台：Win 10最新版，Chrome 开发版 73.0.3664.3

- 类型：建议

- 划词模式：默认

- 期待：希望增加对更多词典网站的支持，比如 Oxford Dictionaries Online ( https://en.oxforddictionaries.com/)、Random House Dictionary Online (https://www.dictionary.com/)、Merriam-Webster Online Dictionaries (https://www.merriam-webster.com/)，最好能够自定义添加其他网站。

**Comment by crimx** [comment]
请问你在查什么单词遇到了困难

**Comment by crimx** [comment]
另外普通用户不懂技术，很难自定义添加

**Comment by funnybones2015** [comment]
平时翻译理解一些专业资料的时候需要用到这些母语型词典，之前有个这样的扩展支持的词典更多，可供参考：https://chrome.google.com/webstore/detail/fairydict/gpdpcfgfmgkmljmhhnedefdaadgehaah

**Comment by crimx** [comment]
ENL 其实比较推荐  Google 词典，解释会比较新，就是得翻墙，对大陆伙伴不太友好。

**Comment by crimx** [comment]
必应这几天被墙，事态发展未知。你可以选择其它国内的词典如有道。

**Comment by longlife** [comment]
> 必应这几天被墙，事态发展未知。你可以选择其它国内的词典如有道。

嗯呢，没办法，有道用起来没这么爽了
