### ISSUE TITLE
这个图标可以增加设置吗

### ISSUE THREAD

**Issue by xivi1839** [crimx/ext-saladict#286]
![default](https://user-images.githubusercontent.com/24610024/51168956-a36e4100-18e5-11e9-8b51-d9b0e27d070c.png)

可以给水果盘图标增加 滑动条设置大小吗，还有滑动设置透明度，自己可以按个人喜欢设定，
每次总是挡住文字，看着难受

**Comment by crimx** [comment]
你好，暂时没有计划添加类似的设置，图标位置一般不会覆盖当前行文字，你也可以换用其它划词模式。
