### ISSUE TITLE
好用，不过例句裁剪太长

### ISSUE THREAD

**Issue by SUSTCLEU** [crimx/ext-saladict#287]
如题，希望可以只裁剪单词前后一两句，不然复习时太长了呀。
![snipaste_2019-01-17_11-36-34](https://user-images.githubusercontent.com/46770323/51294100-6e303300-1a4c-11e9-8bdb-4e8d5edaffca.png)

**Comment by crimx** [comment]
这应该是 bug ，请按模板提供可复现的流程，将会在下个版本修复。

**Comment by SUSTCLEU** [comment]
> 这应该是 bug ，请按模板提供可复现的流程，将会在下个版本修复。
回复这么快的令人发指。。。先用段时间，好用一定请咖啡

**Comment by SUSTCLEU** [comment]
> 这应该是 bug ，请按模板提供可复现的流程，将会在下个版本修复。

回复这么快的令人发指。。。先用段时间，好用一定请咖啡

**Comment by crimx** [comment]
因为背单词已经有其它专门做得更好的应用了（如 Anki），所以 Saladict 的生词本不打算重造轮子，而是主要方便导出各种需要的格式。

**Comment by crimx** [comment]
翻译那里其实还没做完，以后会可以配置翻译引擎和模板。
