### ISSUE TITLE
生词本编辑收藏单词时无法正确反应

### ISSUE THREAD

**Issue by AUROCHSY** [crimx/ext-saladict#289]
- Saladict 版本
6.22.8

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）
windows10 64， chrome版本 71.0.3578.98（正式版本） （64 位）

- 类型：错误
在生词本中编辑单词时并不会弹出单词编辑界面，而是会在生词本中复制一个该单词，即在单词本中添加一个一模一样的单词

- 划词模式？以及其它觉得相关的设置。
单词时点红心添加进单词本的

- 重现：提供详细的可重现问题的操作。
点击右上角插件图标-》随便输入一个单词》点击红心保存》在设置中关闭点击红心时跳转编辑页面的选项》去到生词本》点击刚刚的单词右边的编辑按钮

- 期待：理想情况下扩展应该怎么做？
应该是弹出单词编辑页面

- 实际：客观描述扩展实际上做了什么。
在单词本中复制了该单词

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。
无error

**Comment by crimx** [comment]
确认是 bug ，感谢反馈。
