### ISSUE TITLE
是本人么？貌似被抄了

### ISSUE THREAD

**Issue by kexul** [crimx/ext-saladict#290]
![_ _20190122133700](https://user-images.githubusercontent.com/5920217/51514462-dca93280-1e4a-11e9-882e-224955b5ac21.png)

**Comment by crimx** [comment]
感谢你的热心提醒！这个抄也是没有办法的，我也不通过这个盈利。不过还是建议大家用开源的 Saladict 以免被植入恶意代码。

**Comment by likuku** [comment]
> 感谢你的热心提醒！这个抄也是没有办法的，我也不通过这个盈利。不过还是建议大家用开源的 Saladict 以免被植入恶意代码。

何不趁机入驻 360浏览器 扩展平台呢？

**Comment by crimx** [comment]
@likuku 不用 360 浏览器，所以好好养懒癌……

**Comment by zhpcool** [comment]
太不要脸了。气愤。
