### ISSUE TITLE
建议：希望能提供翻译快捷键

### ISSUE THREAD

**Issue by Halfknow** [crimx/ext-saladict#291]
建议：希望能提供翻译快捷键

描述：因为经常要用到有道网页翻译，而要调用只能通过右键菜单调用，特别每个网页有需要通过点击右键菜单，再鼠标悬停一会去点击子菜单中的有道网页翻译，所以调用非常繁琐。鉴于此希望能够提供快捷键的功能来添加有道网页翻译的选项，到时就可以每次只要按一下快捷键就能使用有道网页翻译。另一个方案可以是提供全局调用功能，也就是每次打开网页都会直接自动调用有道网页翻译，就有点像谷歌翻译他自己的拓展一样有自动翻译的功能。最后再次感谢作者，写了这么个好软件来福利我们广大英语学习者们！

**Comment by crimx** [comment]
你好，请阅读[使用说明](https://github.com/crimx/ext-saladict/wiki)再反馈问题。
