### ISSUE TITLE
滑鼠懸浮取詞後，點擊網頁任意空白處，面板不會消失

### ISSUE THREAD

**Issue by YuiTatsumi** [crimx/ext-saladict#296]
- Saladict 版本：6.23.1

- 平台：Firefox 65.0 (64 位元) & Win10 1809 (OS 組建 17763.292) 

- 类型：錯誤 

- 划词模式：滑鼠懸浮取詞

- 重现：滑鼠懸浮取詞後，點一下網頁任意空白處，面板仍不會消失（偶而會正常，但通常只發生在第一次懸浮取詞時）。疑似是 bug，因為有試了其他種取詞方式，點擊一下空白處，取詞面板都會消失。

- 期待：n/a

- 实际：滑鼠懸浮取詞後，滑鼠要雙擊（點兩下）空白處或是自行按面板右上角的 <kbd>X</kbd> 按鈕，才能關閉面板。

**Comment by crimx** [comment]
你好， 這應該是 bug ，謝謝你提供的信息，我會看看是什麼原因。
