### ISSUE TITLE
划词翻译的时候，网页标题会变成Saladict Panel

### ISSUE THREAD

**Issue by zzm-note** [crimx/ext-saladict#298]
* 版本 

saladict版本最新 浏览器版本chrome 71

* 描述

在任意网页使用划词翻译，网页的标题都会变成Saladict Panel

* 如图
![image](https://user-images.githubusercontent.com/25860330/52681778-0f40d980-2f78-11e9-8c12-bdcf7148d182.png)

**Comment by dcean** [comment]
同样的问题：MAC PRO   Chrome71

**Comment by crimx** [comment]
一会会发布修复
