### ISSUE TITLE
6.24.0 点击红心，不会变红，不会弹出编辑框。 

### ISSUE THREAD

**Issue by myocm** [crimx/ext-saladict#299]
点击红心，不会变红，不会弹出编辑框。 

- Saladict 版本
6.24.0

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）
macOS Mojave
Version  10.14.2

chrome  V71.0.3578.98

**Comment by crimx** [comment]
对的，昨天更新时弄反了哈哈。刚刚正在发布修复哈哈。
