### ISSUE TITLE
PDF 划词换行的单词粘连在一起

### ISSUE THREAD

**Issue by little-ron** [crimx/ext-saladict#300]
- Saladict 版本

6.24.3

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）

Windows 10 Education
Chrome Version 72.0.3626.96 (Official Build) (64-bit)

- 类型：错误？建议？

错误/建议？

- 划词模式？以及其它觉得相关的设置。

PDF 划词换行的单词粘连在一起。在PDF Viewer中换行的两个单词复制到纯文本编辑器中是连在一起的，但是原PDF本身不是连在一起的，因为使用Chrome打开和Acrobat打开再复制相同的换行单词到纯文本编辑器中两个单词是分开（换行）的。（这个锅应该是Saladict所用的PDF Viewer的，不知道可否修复）

- 重现：提供详细的可重现问题的操作。

随便一篇PDF吧，https://arxiv.org/pdf/1412.6806.pdf
从Abstract开始几乎每行的的最后一个单词在本插件中的PDF Viewer中都是和下一行的第一个单词连在一起的，而在Chrome或者Acrobat里打开都是分开的。

- 期待：理想情况下扩展应该怎么做？

期待改善此问题或换个PDF viewer？
双击一行中最后一个或第一个单词时，不与下一行第一个单词或上一行最后一个单词粘连。

**Comment by crimx** [comment]
Saladict 用的 PDF.js 应该是目前最好的开源库了，如果有更好的推荐也可以考虑。相关问题可移步该仓库。
