### ISSUE TITLE
google translate api可以使用jsdelivr的cdn

### ISSUE THREAD

**Issue by jerry011235** [crimx/ext-saladict#301]
鉴于国内连接 谷歌翻译服务 的不稳定，可以使用jsdelivr的cdn
[jsdelivr的google translate api](https://www.jsdelivr.com/?query=google%20translate)

另外能否增加一个[Translater.JS](https://wangchujiang.com/translater.js/)
cdn：https://cdn.staticfile.org/translater.js/1.0.12/translater.min.js

**Comment by crimx** [comment]
你好，谢谢你的建议！

1. jsDelivr 托管的是代码包，其项目本身还是用谷歌的 API，而这个项目不依赖这些（直接使用谷歌翻译服务）。
2. Translater.JS 看了一下不是一个翻译服务，而是一个网页 i18n 支持的插件？

**Comment by jerry011235** [comment]
不好意思，看错了，他是利用HTML**注释**的页面翻译解决方案，是事先自己人工翻译 写好的，再点击切换的😂
