### ISSUE TITLE
可以添加根据语言判断是否自动弹出翻译吗？

### ISSUE THREAD

**Issue by LoogCP** [crimx/ext-saladict#302]
- Saladict 版本

6.24.4

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）

OS：Windows10  1903  build 18334  64bit
Browser：Firefox Nightly 67.0a1  64bit

- 类型：错误？建议？
类型：建议

- 划词模式？以及其它觉得相关的设置。

00

- 重现：提供详细的可重现问题的操作。

00

- 期待：理想情况下扩展应该怎么做？

希望根据个人设置实现对不同语言选择不同的弹出翻译模式，比如我划词选中的内容是中文，不自动翻译，而是出现logo，根据需要点击logo翻译；而如果划词选中的内容是非中文内容，便根据设置自动翻译成指定的语言。

- 实际：客观描述扩展实际上做了什么。

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
这样细分操作我认为增加了不必要的复杂度了。目前查词面板和词典显示都可以设置响应语言，足以满足这个需求。

**Comment by LoogCP** [comment]
前面没看到可以选择语言

CRIMX <notifications@github.com> 于2019年2月19日周二 下午11:57写道：

**Comment by crimx** [comment]
好的，现在问题解决了吗？

**Comment by LoogCP** [comment]
已经解决了。前面主要是平时浏览一些文字很多的网页，阅读的时候喜欢用鼠标把正在读的部分给选上。
你可以关闭这个issue了。
非常感谢！

CRIMX <notifications@github.com> 于2019年2月20日周三 上午12:03写道：

**Comment by crimx** [comment]
好的！解决了就好
