### ISSUE TITLE
反馈下除了英文词典的问题！

### ISSUE THREAD

**Issue by wekey7** [crimx/ext-saladict#303]
首先谢谢大大做了一个这么好用的软件，收费我也心甘情愿，毕竟劳动不是无偿的。
当时更新Weblio日文词典的时候我特别开心，还有特别找到微信去打赏了一下。
Weblio日文词典的使用几乎是没有问题的，这里先略过。

我想说的事情是，最近更新的小语种词典“沪江小D”（因为英文词典太多了）在英文、日文的使用上都是没有问题的，但是在韩文、法文、西文的使用上特别的混乱。
韩文是直接无法搜索，但是我看到有一个小框标注了韩文的。
而法文和西文都是字母文字，所以特别容易被识别成英文，然后无法找到词语。

**Comment by wekey7** [comment]
我不知道该如何发我自己的截图 我选了西文 法文 韩文的截图 但是没办法上传
另外我自己很推荐 naver的三个词典 
https://ja.dict.naver.com/main.nhn 韩日词典
https://zh.dict.naver.com/#/main 韩中词典
https://ko.dict.naver.com/#/main 韩国语词典
希望有朝一日可以看到添加

**Comment by wekey7** [comment]
![1](https://user-images.githubusercontent.com/34415026/53066622-a7f0cf80-350b-11e9-832f-916627d20b5e.png)
![2](https://user-images.githubusercontent.com/34415026/53066623-a7f0cf80-350b-11e9-99d3-44341ae94c12.png)
![3](https://user-images.githubusercontent.com/34415026/53066624-a7f0cf80-350b-11e9-80f4-b17de6ca042f.png)
找到图片上传了 这是在实际使用上的 韩文小D 法文小D 西文小D
英文和日文是完美的

**Comment by crimx** [comment]
你好，首先感谢你的支持！

拉丁语系语言字符冲突这个是没办法避免的，我在小 D 的词典设置里提供了选项来选择优先的词典。你是经常英德法一起看的吗？推荐用其它词典看英文和中文，让小 D 专门识别小语种。

**Comment by wekey7** [comment]
> 你好，首先感谢你的支持！
> 
> 拉丁语系语言字符冲突这个是没办法避免的，我在小 D 的词典设置里提供了选项来选择优先的词典。你是经常英德法一起看的吗？推荐用其它词典看英文和中文，让小 D 专门识别小语种。

我经常使用的是英文、日文和韩文的词典 偶尔会用一下西文词典
韩文目前划词是无法识别的 西文我自己用词典查没问题的 谢谢大大回复

**Comment by wekey7** [comment]
![1](https://user-images.githubusercontent.com/34415026/53067003-3d409380-350d-11e9-9c26-079c956f0e8f.png)

**Comment by crimx** [comment]
嗯，我刚试了一下，韩文匹配估计有 bug 。

另外你提供的 naver 词典可以取几个典型的例子截图并圈出关心的部分么。让我了解你的使用方式，因为我不懂韩文哈哈。

**Comment by wekey7** [comment]
![1](https://user-images.githubusercontent.com/34415026/53067338-c60bff00-350e-11e9-94b6-5147b13d3038.png)
![2](https://user-images.githubusercontent.com/34415026/53067339-c60bff00-350e-11e9-9d78-46d7061300b2.png)
这是韩中词典的 图1是查中文汉字 图2是查韩文

![1](https://user-images.githubusercontent.com/34415026/53067353-d2905780-350e-11e9-8071-8ac06416fe65.png)
![2](https://user-images.githubusercontent.com/34415026/53067354-d2905780-350e-11e9-8084-bb3d1a58e42b.png)
这是韩日词典的 图1是查日文汉字 图2是查韩文

![1](https://user-images.githubusercontent.com/34415026/53067372-e20fa080-350e-11e9-89ad-b8562ba5dc3d.png)
这是韩国语词典的 他只能查韩语汉字（繁体字）或者是韩文

**Comment by wekey7** [comment]
> 嗯，我刚试了一下，韩文匹配估计有 bug 。
> 
> 另外你提供的 naver 词典可以取几个典型的例子截图并圈出关心的部分么。让我了解你的使用方式，因为我不懂韩文哈哈。

不知道我这么说能看懂吗 就跟大大之前做的weblio的词典很像吧 
不知道可不可以拆成三个词典或者像沪江小D一样可以设置下

韩中词典和沪江小D韩语词典有点类似 但是会自动还原韩语的动词变化 沪江小D没有
韩日词典是因为日语韩语很多语法通用 如果会其中一种语言更能看懂 而且也会自动还原韩语的动词变化 沪江小D没有
韩国语词典就是高阶使用者用的了

**Comment by crimx** [comment]
其实没太懂哈哈。你可以理解为现在要将这个页面精简到一块小面板，那么页面上有哪些部分是要保留的。另外有的词典查不同的词会有不同排版的页面，有这样的情况也要另外处理。可以参考关于 Weblio 的讨论 #156

**Comment by wekey7** [comment]
![1](https://user-images.githubusercontent.com/34415026/53068708-6153a300-3514-11e9-8be7-856ab01b7847.jpg)
图1是输入词典时候的界面。
图1①输入韩文单词的情况 
图1②所有单词都是同音字（韩语有大规模同音字的情况）都是需要的
如果点开其中一个跳转图4【！】
图1③是更多单词 虽然也是同音字但是没那么常用的
![33](https://user-images.githubusercontent.com/34415026/53068782-9a8c1300-3514-11e9-9a83-6e1d7bad7146.png)
图2是图1③点开过后的全部单词
如果点开跳转图4【！】
![22](https://user-images.githubusercontent.com/34415026/53068781-99f37c80-3514-11e9-88d4-059e6fd55a5a.png)
图3是中文汉字输入的情况 不会有那么多的同音字 但是会跳出关联的汉字词
![44](https://user-images.githubusercontent.com/34415026/53068783-9a8c1300-3514-11e9-9f4f-fda4c283dcd3.png)
图4①韩文
图4②韩文汉字（繁体字）
图4③中文意思
图4④韩文发音
图4⑤⑥⑦分别是三个单词书 可以切换看不同的解释
图4⑧例句

不知道有说清楚吗 我想晚点来做日韩的解释

**Comment by crimx** [comment]
可以可以，谢谢！辛苦了

像 图4⑤⑥⑦ 这样的切换常用么，几个单词书有什么区别？

**Comment by wekey7** [comment]
![1](https://user-images.githubusercontent.com/34415026/53091370-c0cda500-354c-11e9-8664-fcbbf538791a.png)
![2](https://user-images.githubusercontent.com/34415026/53091371-c0cda500-354c-11e9-8f1c-46fdf691de83.png)
![3](https://user-images.githubusercontent.com/34415026/53091372-c0cda500-354c-11e9-980c-491050afae30.png)
一般来说第一个词典会比较详细 第二个和第三个词典比较简洁

**Comment by wekey7** [comment]
我来啦！ 这一批是韩日词典的输入韩语相关的页面！！

图1①单词输入的地方
图1②“1.全体（所有的集合）2.只出现单词 3.只出现例句 4.只出现相关日文单词”
图1③显示或者关闭“日文假名标注” 详见图2
图1④显示所有该韩语发音单词
![1](https://user-images.githubusercontent.com/34415026/53092381-a0ebb080-354f-11e9-83cc-72a0e44b280d.jpg)
图2与图1③相关 打开或者关闭
![2](https://user-images.githubusercontent.com/34415026/53092383-a21cdd80-354f-11e9-998e-dd83ed0f4162.png)
图3进入单词界面
图3①单词
图3②单词
图3③韩文汉字（繁体字）
图3④单词意思
图3⑤所有该单词的相关发音词语 图5 图6相关【意义不同韩语单词相同】
图3⑥造句
图3⑦打开或者关闭日文假名标注 与图1③相同 图4注解
图3⑧韩文解释
图3⑨日文解释（一般看日文解释比较多）
![3](https://user-images.githubusercontent.com/34415026/53092386-a21cdd80-354f-11e9-9b41-68642a03fa8b.png)
图3⑦打开或者关闭日文假名标注 与图1③相同 图4注解
![4](https://user-images.githubusercontent.com/34415026/53092387-a21cdd80-354f-11e9-96cd-a530bef0db17.png)
图3⑤所有该单词的相关发音词语 图5 图6相关【意义不同韩语单词相同】
![5](https://user-images.githubusercontent.com/34415026/53092388-a2b57400-354f-11e9-9743-1669ad863e3d.png)
图3⑤所有该单词的相关发音词语 图5 图6相关【意义不同韩语单词相同】
![6](https://user-images.githubusercontent.com/34415026/53092389-a2b57400-354f-11e9-9007-7c275aaa3a08.png)

**Comment by wekey7** [comment]
输入日文查韩文解释
图1①单词
图1②“1.全体（所有的集合）2.只出现单词 3.只出现例句 4.只出现相关单词”
图1③打开或者关闭日文假名【该图选择了关闭模式】
图1④日文最优解释
图1⑤日文该词相关解释
![7](https://user-images.githubusercontent.com/34415026/53092905-ee1c5200-3550-11e9-8933-ee37f911f32d.png)
图2①日文发音
图2②日文汉字
图2③韩文相近单词
图2④日文单词解释
图2⑤韩文相关发音单词
图2⑥例句
图2⑦打开或者关闭日文假名【该图选择了关闭模式】
图2⑧日文解释
图2⑨韩文解释
![8](https://user-images.githubusercontent.com/34415026/53092897-e6f54400-3550-11e9-9ecf-04a9f2cbe0ab.png)

日韩词典也十分有用 不知道我有没有给大大解释清楚 
如果有我没讲清楚的地方 请一定多多提问喔！

**Comment by wekey7** [comment]
> 可以可以，谢谢！辛苦了
> 
> 像 图4⑤⑥⑦ 这样的切换常用么，几个单词书有什么区别？

麻烦大大抽空看一下日韩词典

**Comment by wekey7** [comment]
总的来说 如果按照我的使用频率
韩中词典我一般是输入韩文看看中文意思是什么
韩日词典我一般是输入韩文看看日文意思是什么
中文查韩文或者日文查韩文的情况比较少（也有）

**Comment by crimx** [comment]
谢谢！没问题了，整理得非常详细。这个功能比较多，我整理一下，实现的时候有问题再向你请教， 辛苦了。

**Comment by wekey7** [comment]
> 谢谢！没问题了，整理得非常详细。这个功能比较多，我整理一下，实现的时候有问题再向你请教， 辛苦了。

比较怕自己没说清楚 或者图片整理得太乱了 期待成果！！

**Comment by crimx** [comment]
你好，现在有个问题。一般搜索出来的第一个结果页面（图 1）可以满足大部分查词需求吗？ 单词页面我打算不内嵌到 Saladict 查词面板上，需要再点开到新标签页上查看。

**Comment by wekey7** [comment]
请问是哪个词典 中韩 还是日韩 如果 结果页面是这种完全能满足查词需求 
![2](https://user-images.githubusercontent.com/34415026/53336262-c7875e00-3938-11e9-8059-898f444a2318.jpg)
![53068708-6153a300-3514-11e9-8be7-856ab01b7847](https://user-images.githubusercontent.com/34415026/53336263-c7875e00-3938-11e9-9d89-f30ebe12c74c.jpg)

**Comment by crimx** [comment]
是的，两个词典都是，只从搜索结果的页面提取。

**Comment by wekey7** [comment]
那应该完全没问题的 但是上述两个图标都是在 中韩词典 日韩词典搜 韩文的情况 
如果是中韩词典搜中文 只有框框内的第一个词条是比较有用的 后面都是拓展的 或者网友例句
【词条点开之后会比缩略的预览多几个解释】
![1](https://user-images.githubusercontent.com/34415026/53337042-2e0d7b80-393b-11e9-9aa3-c7ef1e333711.png)
日韩词典分两种情况 
一是没有多音字比如食う就只有一条比较有用同中韩词典 
二是する有多音字的情况 可能都会有用
【词条点开之后会比缩略的预览多几个解释】
另外就是日韩词典保留了日语的变形 对于新学日语的人或许有用 可要可不要
![2](https://user-images.githubusercontent.com/34415026/53337043-2e0d7b80-393b-11e9-89cb-c4805a617899.png)
![3](https://user-images.githubusercontent.com/34415026/53337044-2e0d7b80-393b-11e9-8c1b-2cd8a9bcf59f.png)

**Comment by crimx** [comment]
嗯，如果还有这样特殊的页面请一并加进来，我添加到测试中。

**Comment by crimx** [comment]
另外可以附上这几个页面的链接么，日语我可以打得出来，韩文实在不行了。

**Comment by wekey7** [comment]
好的 
[전기]
https://zh.dict.naver.com/#/search?query=%EC%A0%84%EA%B8%B0 [中韩]
https://ja.dict.naver.com/search.nhn?range=all&q=%EC%A0%84%EA%B8%B0&sm=jpd_hty [日韩]
「食う」
https://ja.dict.naver.com/search.nhn?range=all&q=%E9%A3%9F%E3%81%86&sm=jpd_hty
「する」
https://ja.dict.naver.com/search.nhn?range=all&q=%E3%81%99%E3%82%8B&sm=jpd_hty

**Comment by wekey7** [comment]
[대하다] 表面只会有3个解释 实际点开会有6个解释 很多单词都会是这样 
我看大大做沪江小D词典插件是可以点进去的 这么解决就特别的方便
https://ja.dict.naver.com/search.nhn?query=%EB%8C%80%ED%95%98%EB%8B%A4
![1](https://user-images.githubusercontent.com/34415026/53339523-919aa780-3941-11e9-94f4-10bacc10cb64.png)
![2](https://user-images.githubusercontent.com/34415026/53339524-919aa780-3941-11e9-942b-22321ffa5a4d.png)

**Comment by wekey7** [comment]
大大 另外在【日韩词典】如果输入地名 或者汉字 会有两种语言同时存在的情况
图1 【近畿】是日韩两个都存在的地方
![1](https://user-images.githubusercontent.com/34415026/53340531-2ef6db00-3944-11e9-971e-205342262670.png)
图2 【京】在日语代表“京都 东京 首都” 在韩语代表“首尔”
![2](https://user-images.githubusercontent.com/34415026/53340475-125aa300-3944-11e9-8e9d-bd0eca475572.png)
图3【東京】在日语代表“东京” 在韩语代表古代的“庆州”
![3](https://user-images.githubusercontent.com/34415026/53340476-125aa300-3944-11e9-8416-ad6135335d7f.png)
图4【ソウル】在日语代表“外来语：soul 韩语：首尔” 在韩语也是如此
![4](https://user-images.githubusercontent.com/34415026/53340477-12f33980-3944-11e9-9908-acd5a8502ea2.png)

**Comment by wekey7** [comment]
中韩词典里面 如果遇到汉字词的情况下
1.汉字里面简体字 繁体字可以通用
2.汉字词会出现中文汉字 韩语汉字两种意思
3.甚至会出现“中文拟音”的情况 类似于“i love you”="爱老虎油”
[東京]
![1](https://user-images.githubusercontent.com/34415026/53341310-2ef7da80-3946-11e9-9023-983fbe5ba11d.png)
[江陵]
![2](https://user-images.githubusercontent.com/34415026/53341311-2ef7da80-3946-11e9-92bd-1f1c6f57a3de.png)
[江]
![3](https://user-images.githubusercontent.com/34415026/53341312-2ef7da80-3946-11e9-936b-6995a66b5ac4.png)
[고려]=韩语汉字[考慮、高麗]
https://zh.dict.naver.com/#/search?query=%EA%B3%A0%EB%A0%A4
![4](https://user-images.githubusercontent.com/34415026/53341314-2f907100-3946-11e9-9e33-1786d906971a.png)
[신라]=韩语汉字[新羅]拟音[辛辣]
https://zh.dict.naver.com/#/search?query=%EC%8B%A0%EB%9D%BC
![5](https://user-images.githubusercontent.com/34415026/53341316-2f907100-3946-11e9-89f5-58def65bf506.png)

**Comment by wekey7** [comment]
补充一下 如果同样三个汉字在日韩词典上会出现的情况
https://ja.dict.naver.com/search.nhn?range=all&q=%EC%8B%A0%EB%9D%BC&sm=jpd_hty
![1](https://user-images.githubusercontent.com/34415026/53341672-218f2000-3947-11e9-9587-af8f452d8afe.png)
https://ja.dict.naver.com/search.nhn?range=all&q=%EA%B3%A0%EB%A0%A4&sm=jpd_hty
![2](https://user-images.githubusercontent.com/34415026/53341673-218f2000-3947-11e9-977a-9d63d6a658d9.png)
https://ja.dict.naver.com/search.nhn?range=all&q=%E6%B1%9F&sm=jpd_hty
![3](https://user-images.githubusercontent.com/34415026/53341674-2227b680-3947-11e9-8e73-139f399a10e8.png)

**Comment by wekey7** [comment]
有点乱
第一波 第二波图是日韩词典
第三波图是 中韩词典
第四波图是 日韩词典

**Comment by crimx** [comment]
嗯嗯，这个意思层面的变化其实没关系的，只要排版不变即可。

**Comment by wekey7** [comment]
好的 主要是怕汉字词识别会bug

**Comment by crimx** [comment]
对了，沪江的其实不是识别的问题，而是它换了韩语页面的链接哈哈。

**Comment by wekey7** [comment]
我点开看了下 真的是诶 说是页面不在了 哈哈哈
我就是在想韩文这种圈圈文字 不应该识别有问题啊 
大大你做的词典可以点击变成浏览器页面这个功能实在是太方便了

**Comment by crimx** [comment]
@wekey7 现在已基本添加完毕了，我会在鸣谢名单上添加上你的名字，你需要留个社交媒体的帐号么？

**Comment by wekey7** [comment]
这个是我的b站账号最近在做rap歌曲的字幕 https://space.bilibili.com/2847931
这是我微博 http://weibo.com/925515171
很开心能看到大大的成果啊 预计多久会上线啊 迫不及待用最新版去看韩文资料啦！

**Comment by crimx** [comment]
已发布。不好意思最近有点忙所以晚了些。如果出现排版问题请继续反馈。
