### ISSUE TITLE
在推特划词添加单词本时，翻译板内的内容无法被复制粘贴。

### ISSUE THREAD

**Issue by Hasaki2142** [crimx/ext-saladict#304]
@crimx 
!https://github.com/Hasaki2142/hasaki2142/blob/master/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20190222012042.png

**Comment by Hasaki2142** [comment]
之前都还好好的，不知道怎么回事就不能粘贴了。

**Comment by Hasaki2142** [comment]
之前都还可以复制粘贴，安装了个变换网页颜色的插件就不能了。然后我就没用那个软件了，把沙拉卸载又重装了两次，还是不行。

**Comment by crimx** [comment]
你好，你的图挂了。

我试了一下没有问题的，重装之后有没有刷新一下 Twitter 的页面。

**Comment by Hasaki2142** [comment]
刷新了的,我已经把那款插件卸载了,现在恢复正常了,确定没有冲突吗,我感觉就是那个插件的问题.

**Comment by Hasaki2142** [comment]
我那个图的地址应该没挂啊 那我怎么给你看截图呢

**Comment by crimx** [comment]
图你是不是上传到了自己的私有仓库。直接拖到评论框即可上传（见评论框底部的文字）。

插件冲突不知道，因为，你根本没说是哪个扩展啊哈哈哈哈。

**Comment by crimx** [comment]
插件我看到了！我先试一下

**Comment by crimx** [comment]
是的，这个是该扩展造成的。

**Comment by Hasaki2142** [comment]
那我就放心了 安心地卸载了那个插件

**Comment by Hasaki2142** [comment]
有什么不冲突的网页颜色插件推荐吗

**Comment by crimx** [comment]
这个不清楚了。各种网站实现复杂不一，这类对排版大动干戈的扩展很容易就触发到什么雷区，破坏网页原有的设计。
