### ISSUE TITLE
点击图标，不自动查词。

### ISSUE THREAD

**Issue by xinxudong** [crimx/ext-saladict#305]
Saladict 6.24.4,，Windows 10系统，最新版本的Chrome浏览器。
       今天，重置设定，默认模式，复制单词，点击图标不会自动查词，之后重新安装扩展程序，还是不行，看了一下设置 “ 右上弹框 ” 没这个 “ 剪切板自动查词 ” 这个功能，之前旧版本是有的。
       没重置前，复制单词，点击图标，会自动查词，可能因为缓存着之前旧版本的设置数据吧。
       希望能修复一下，谢谢了！扩展做的不错！

**Comment by crimx** [comment]
是的，谢谢反馈。这个选项是我之前不小心隐藏了，修复的版本会等 #303 一起发布。

**Comment by xinxudong** [comment]
好的！
