### ISSUE TITLE
添加单词本时无法自动填充翻译 && 移动时会被卡住

### ISSUE THREAD

**Issue by WonderfulUnknown** [crimx/ext-saladict#307]
- Saladict 版本
6.24.4

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）
win10 Chrome72.0.3626.119（正式版本） （64 位）

- 类型：错误？建议？
错误 && 建议

- 划词模式？以及其它觉得相关的设置。
单词本

- 重现：提供详细的可重现问题的操作。
添加一个单词到单词本，将原本翻译界面拖动，会卡在屏幕下方无法拖动上来，多次尝试以后能回来，基本移到下方就会被卡住
单词本自动添加的翻译是原网页中选中该单词那整句话的翻译

- 期待：理想情况下扩展应该怎么做？
翻译界面可以任意拖动不被卡住
单词本自动添加的翻译最好可以默认选择某个翻译软件的翻译，或者全部

- 实际：客观描述扩展实际上做了什么。

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

![problem](https://user-images.githubusercontent.com/40764322/53682441-ae175500-3d30-11e9-9828-e88683de4e5b.png)

**Comment by crimx** [comment]
感谢反馈，

1. 拖动的 bug 是因为编辑框屏蔽了拖动，会在下个版本修复。
2. 翻译原因见置顶帖子。
