### ISSUE TITLE
给大大反应一下韩语词典的使用情况【排版相关】

### ISSUE THREAD

**Issue by wekey7** [crimx/ext-saladict#308]
图1：不知道能不能设置一下让用户自定义“中韩”“日韩”的顺序 好像是默认的“中韩”其次才是“日韩”
![1](https://user-images.githubusercontent.com/34415026/53685440-a61ddc00-3d55-11e9-98f7-cce36ceda898.jpg)
图2：日语在查询动词的时候【列如：走る、寝る】会特别浪费划词的页面 建议弄成横排 如果难以做到个人建议不如删去 更简洁
![2](https://user-images.githubusercontent.com/34415026/53685442-a61ddc00-3d55-11e9-9064-2389e69fb379.jpg)
图3：在使用韩日词典的情况会默认打开日语假名标注 这样在看的时候会比较松散不紧凑 建议可以让用户自定义吗？【位于韩日单词标注处"후리가나"「振り仮名」】
![3](https://user-images.githubusercontent.com/34415026/53685443-a6b67280-3d55-11e9-8f48-fd52b2cdf7da.jpg)
图4：沪江小D不管是日语还是韩语在使用上都特别的空 需要打开下面的箭头“或许是沪江本身的问题”
“韩中词典”排版特别舒服紧凑 “韩日词典”还是会有假名占太多页面的情况 希望可以用户自定义打开或者关闭假名
![4](https://user-images.githubusercontent.com/34415026/53685444-a6b67280-3d55-11e9-8330-ba05f64fb197.jpg)

**Comment by crimx** [comment]
我总结一下哈

1. 词典顺序。这个不重要的，只要有假名就会搜日语词典，三者只有汉字是重叠的，你按设置勾选即可。
1. 走る 之类的词会出现排列占据过多空间。这个没办法，因为从它的排版是不知道哪些是什么内容的。只能照着它的设计排。
1. 假名显示隐藏。还没有时间弄，就先显示着，有空再来做这个。
1. 排版紧凑问题。这个因为样式基本是从原网页拿来改，我再调调。

**Comment by crimx** [comment]
貌似找到方法处理词性变化的排版问题，我一会看看。

**Comment by crimx** [comment]
要不我把假名都隐藏了，面板较小看起来也不方便。

**Comment by wekey7** [comment]
好的 
1.词典顺序这个是不重要了
2.走る 那个是日语变形 给韩国学日语的初学者看的 我比较建议删去好了

**Comment by wekey7** [comment]
好的
1.词典顺序这个是不重要了
2.走る 那个是日语变形 给韩国学日语的初学者看的 我比较建议删去好了
3.我也和大大的想法一样 隐藏了比较清爽 去看韩日词典的 应该是日语稍微毕竟好的

**Comment by wekey7** [comment]
2.走る 给韩国学日语的初学者看的 我比较建议删去好了
图1这个是韩日词典 变形我翻译的
![1](https://user-images.githubusercontent.com/34415026/53693402-e07d8c80-3dda-11e9-9249-c7f24d3a8d5c.png)
图2 是给日语初学者看的变形的
![2](https://user-images.githubusercontent.com/34415026/53693403-e1162300-3dda-11e9-82a9-2cfcb33c909f.png)

**Comment by crimx** [comment]
哦哦，这个中文初学者是用不到的吗？另外图2提供个链接，我要加进去测试。

**Comment by wekey7** [comment]
对的 中文初学者我想是用不到的 
http://www.gavo.t.u-tokyo.ac.jp/ojad/search/index/sortprefix:accent/narabi1:kata_asc/narabi2:accent_asc/narabi3:mola_asc/yure:visible/curve:invisible/details:invisible/limit:20
图2是我找的一个日语网站 不是词典里面的 只是想说这是日语的变形

**Comment by crimx** [comment]
哦哦，不是那没关系了。

**Comment by crimx** [comment]
对了哈哈，另外我也在学日语，刚背完五十音了，你应该是相当棒的，不知道有没有资料推荐。

**Comment by wekey7** [comment]
https://ja.wiktionary.org/wiki/%E3%83%A1%E3%82%A4%E3%83%B3%E3%83%9A%E3%83%BC%E3%82%B8 
这个是维基词典特别推荐 经常可以看到中日韩越的发音
http://www.gavo.t.u-tokyo.ac.jp/ojad/search/index/sortprefix:accent/narabi1:kata_asc/narabi2:accent_asc/narabi3:mola_asc/yure:visible/curve:invisible/details:invisible/limit:20
这是日语初学者要掌握的动词变形网站 可以随时查
前期还是比较建议先按照课本学 至少学到N4 N3开始再去看别人写的东西
比较推荐的教材是《标准日本语》

**Comment by crimx** [comment]
非常感谢！

**Comment by wekey7** [comment]
如果有什么日语上的问题 大大可以来问我 我们共同学习（不过我也很差啦 哈哈）
中文的互联网有一点特别好 查日文语法几乎都找得到 搜韩文很多乱码

**Comment by crimx** [comment]
谢谢你！共勉！新版本已发布，等待浏览器更新。

**Comment by wekey7** [comment]
迫不及待的用开发者模式更新啦~ 超棒的
