### ISSUE TITLE
遇到三個問題，請教作者大大

### ISSUE THREAD

**Issue by YuiTatsumi** [crimx/ext-saladict#309]
**■ 問題 1：Firefox 在 Twitch 顯示圖案劃詞失效（Chrome 是正常的）**
- Saladict 版本 6.25.0

- 平台：Firefox 65.0.2 & Win10 1809 (OS 組建 17763.346)

- 类型：錯誤

- 划词模式：顯示圖案（會顯示沙拉圖示的那個）

- 重现：在網站 Twitch （https://www.twitch.tv/ ）用 <kbd>顯示圖案</kbd>，再點擊沙拉圖示來翻譯沒有作用。其他例如 <kbd>直接搜尋</kbd> 或 <kbd>滑鼠雙點擊</kbd> 等其他取詞模式則都正常。

**■ 問題 2：選詞語言怪怪的，無法阻止中文翻譯成英文等問題**

- 平台：Firefox 65.0.2 & Chromium 71.0.3578.98

- 类型：錯誤

- 划词模式：跟劃詞模式沒關係，主要是谷哥翻譯、百度翻譯、搜狗翻譯

- 重现：
1. 第一種情況，假設設定如下圖，應該是要若劃詞均為中文則忽略；實則不然，還是會跑出來並把中文翻譯成英文。
![5](https://user-images.githubusercontent.com/42616117/53695878-f0599880-3dfb-11e9-8b0f-fc036c92b90a.png)

2. 第二種情況，假設設定如下圖，應該是要忽略韓文劃詞；實則不然，要把最後一個選項 <kbd>其他字元</kbd> 的勾勾也取消，才能不去翻譯韓文。
![6](https://user-images.githubusercontent.com/42616117/53695886-f485b600-3dfb-11e9-9dd8-e944661463c9.png)

**■ 問題 3：希望不要出現空的取詞框**

- 平台：Firefox 65.0.2 & Chromium 71.0.3578.98

- 类型：建議

- 划词模式：n/a

- 重现：如果我僅使用一個劍橋詞典，並設定 <kbd>選詞字數</kbd> 皆為1時（希望將沙拉查詞當字典用，不想使用到翻譯功能），如第一張圖。此設定下，若選超過1個字，還是會取詞，並出現空的取詞框，如第二張圖。
![7](https://user-images.githubusercontent.com/42616117/53695897-2b5bcc00-3dfc-11e9-93e8-f1aa944fb78d.png)
![8](https://user-images.githubusercontent.com/42616117/53695929-77a70c00-3dfc-11e9-8d8f-c98c3694c91f.png)

- 期待：忽略一個以上的字數不翻譯時，照理來說劃詞選取範圍若超過一個單字，沙拉查詞應該要沒任何反應才對。

**Comment by crimx** [comment]
你好，

1. 初看了一下，沒發現是什麼原因。我會再看看。
2. 中文這個是因為日語和韓語也包含了漢字，這個設定我優化一下，取消中文時自動取消日語和韓語，需要的再自行勾回來。其它字元先不要勾選。
3. 你這裡是設定詞典的顯示（看到詞典沒有出現了嗎），查詞面板的顯示在「查詞習慣」中設定。

**Comment by YuiTatsumi** [comment]
好的，謝謝您，辛苦了。
這個 1. 我記得以前 Firefox 上是正常的，好像是最近才有的問題（不太確定，因為我 Firefox 跟 Chrome 兩邊混著用，所以我也記不是很清楚）

**Comment by crimx** [comment]
Twitch 没能搞清是什么原因，就不再花时间纠结了。新版本已发布，等待浏览器更新。
