### ISSUE TITLE
collins 词典这两天突然不能用了  一直在加载

### ISSUE THREAD

**Issue by beichengyuxia** [crimx/ext-saladict#311]

**Comment by beichengyuxia** [comment]
i got it

**Comment by crimx** [comment]
双语用的爱词霸源，不太稳定。我打算再加上官网的全英源。

**Comment by beichengyuxia** [comment]
> 双语用的爱词霸源，不太稳定。我打算再加上官网的全英源。
是我的问题  忽略了一个问题：就是词典本身不存在这个词条即无法检索。 并未发现bug,thanks for  your time.
