### ISSUE TITLE
复制单词或者输入单词，点击图标查词后，会在Google搜索里留下记录(如图)

### ISSUE THREAD

**Issue by xinxudong** [crimx/ext-saladict#312]
![2019-03-04 091159](https://user-images.githubusercontent.com/28260207/53712329-5fc59b80-3e81-11e9-881c-79998fb2c683.jpg)

我刚开始时以为我的Google账号被盗，后来发现用这个扩展查词后会在Google搜索里留下记录，不过这个不影响使用，有空可以考虑修复一下，或许之前有其他人反馈过给你吧，谢谢了！

**Comment by crimx** [comment]
好的，谢谢反馈。

**Comment by LambdaAlpha** [comment]
这个 bug 修复了吗? 我也用了几个月了, 一直都有这个问题.

**Comment by LambdaAlpha** [comment]
![image](https://user-images.githubusercontent.com/20299598/104983814-79a60280-5a48-11eb-9a15-46f2d56fca90.png)

@crimx

**Comment by crimx** [comment]
这个已经修复了，这边也没法复现这个问题。你的系统，浏览器，沙拉查词版本是多少？

**Comment by LambdaAlpha** [comment]
Google Chrome | 87.0.4280.141 (正式版本) （64 位）
系统 windows 10 2004, ubuntu 20.04 都用
沙拉查词版本 7.18.0

因为我也用挺久了, 所以应该是多个系统, 多个系统版本, 多个 chrome 版本,  多个沙拉查词版本都能复现. @crimx

**Comment by crimx** [comment]
信息看起来没问题。

要不你再重新复现一遍，然后把步骤发一下？

**Comment by LambdaAlpha** [comment]
@crimx 使用默认模式, pdf 设置里嗅探 pdf 链接选项关闭, chrome 快捷键里把 `在独立窗口中搜索剪贴板内容` 设置为 `ctrl+d`, 打开一个 pdf 文件, 选中一个单词, `ctrl_c` `ctrl+d`, 可以换几个词重复几次, 在地址栏输入任意字符进行搜索, 将搜索栏清空查看建议.
