### ISSUE TITLE
www.sharetechnote.com  无法划词翻译

### ISSUE THREAD

**Issue by sungoth** [crimx/ext-saladict#313]
<details><summary>反馈说明</summary>

</details>

- Saladict 版本 6.25.1

- 平台：windows7 64bit和 Chrome 72.0.3626.121（正式版本） （32 位）/Firefox 65.0.1 64位

- 类型：www.sharetechnote.com  无法划词翻译,用鼠标选择的时候不会出现翻译的图标。

- 划词模式？全默认设置

- 重现：www.sharetechnote.com 网站可以重现

- 期待：可以正常的划词翻译

- 实际：可能原因是网页中使用了frame?

**Comment by crimx** [comment]
你好，是的，这个网页是使用了过时的技术实现的。Saladict 没有计划支持。

**Comment by crimx** [comment]
你可以用 Saladict 快捷查词的独立窗口。
