### ISSUE TITLE
快捷查词-独立窗口 选项说明有误

### ISSUE THREAD

**Issue by fireattack** [crimx/ext-saladict#314]
- Saladict 版本

6.25.1

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）

Chrome beta 
Win7x64

- 类型：错误？建议？

选项说明错误

![image](https://user-images.githubusercontent.com/4130991/54067361-ad852f80-4204-11e9-9b98-51b87c593e37.png)

独立窗口相关的这些选项，实际是对开启独立窗口时，响应**网页划词**的控制，而不是”查词面板内部划词“的控制。

**Comment by crimx** [comment]
眼残看漏了，谢谢反馈
