### ISSUE TITLE
点红心后两个窗体起始高度位置不一样

### ISSUE THREAD

**Issue by shesuyo** [crimx/ext-saladict#315]
- Saladict 版本
6.26.0

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）
Google Chrome 
版本 75.0.3730.0（正式版本）canary （64 位）

- 类型：错误？建议？
错误

- 划词模式？以及其它觉得相关的设置。

- 重现：提供详细的可重现问题的操作。
![image](https://user-images.githubusercontent.com/10195494/54095528-c9dec300-43e2-11e9-9714-3c66c27b647c.png)

- 期待：理想情况下扩展应该怎么做？

两个框的起始高度应该在同一水平
![image](https://user-images.githubusercontent.com/10195494/54095629-3eb1fd00-43e3-11e9-9bb1-f5db826a4ad8.png)

- 实际：客观描述扩展实际上做了什么。

左边的框更高了点

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。
分辨率为 `2560*1440`
截图大小为 `2560*1329`

**Comment by crimx** [comment]
你好，你设置的面板最大高度占比是多少呢？

**Comment by crimx** [comment]
已换为居中的方式
