### ISSUE TITLE
新版弹出窗口会被Context Search挡住

### ISSUE THREAD

**Issue by dx99999** [crimx/ext-saladict#316]
新版有一个问题，弹出窗口会被Context Search（https://chrome.google.com/webstore/detail/context-search/eopohglffbpfjebajgdholffljaccfdk）的弹出窗口挡住，旧版本就不会，看能不能处理一下，谢谢

**Comment by crimx** [comment]
新版在处理拖动断掉时将面板的 z-index 降了一个值，会在下个版本修复。
