### ISSUE TITLE
Markdown Preview supported?

### ISSUE THREAD

**Issue by AlixChiong** [crimx/ext-saladict#317]
can markdown be supported like the pdf ？

**Comment by crimx** [comment]
What do you mean by "Markdown Preview"? Is there a specific service that's in you mind? Markdown result is only normal HTML which is converted from plain text.

**Comment by AlixChiong** [comment]
I want to preview a markdown file in this plugin , like viewing a pdf file in this plugin. could u add the feature to the plugin. Thanks.

**Comment by crimx** [comment]
I see. That's actually unnecessary. You can use any online Markdown service like <https://markdownlivepreview.com/> (or even Github) and Saladict should work just fine.
