### ISSUE TITLE
 Firefox Developer Edition 无法删除词典

### ISSUE THREAD

**Issue by ziselive** [crimx/ext-saladict#319]
- Saladict 版本
6.26

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）
win7 X64  Firefox Developer Edition 67.0b1 (64 位)

- 类型：错误？建议？

词典管理里面 无法删除词典，但是可以添加。

**Comment by crimx** [comment]
在稳定版中是没问题的，Developer Edition 我还没有测试。用户量太少了，这个不在 Saladict 适配范围内。

**Comment by ziselive** [comment]
好
