### ISSUE TITLE
Cent Browser上使用無效

### ISSUE THREAD

**Issue by ast000** [crimx/ext-saladict#322]
- Saladict 版本
Version
6.26.0

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）
win7 
Cent Browser 64位元

- 类型：错误？建议？
错误

- 划词模式？以及其它觉得相关的设置。
Saladict 設定 > 字典設定

- 重现：提供详细的可重现问题的操作。
已選字典部分
字典太多要刪除時
刪除鍵點擊無反應
編輯鍵點擊後有選單  但是修改選項無效
其餘部份正常

- 期待：理想情况下扩展应该怎么做？

- 实际：客观描述扩展实际上做了什么。

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
你好，确定一下。你是不是之前就安装了 Saladict 然后升级后出现的这个问题？

**Comment by ast000** [comment]
應該是 
之前用chrome就一段時間沒開cent browser
移除重裝後問題解決了 謝謝
