### ISSUE TITLE
今天发现不起作用了？

### ISSUE THREAD

**Issue by sambodhi-cn** [crimx/ext-saladict#323]
- Saladict 版本

- 平台：Windows 10 1809，Chrome 79

- 类型：错误

- 划词模式

- 重现：划定句子或者单词后，不出现结果，只剩下光秃秃的菜单栏。

**Comment by sambodhi-cn** [comment]
嗯。

**Comment by crimx** [comment]
在所有页面都不能打开么？

**Comment by sambodhi-cn** [comment]
是啊！我反复重启浏览器也不行。

**Comment by crimx** [comment]
你可以在设置里重置试试。这个问题我没法重现暂时找不出来，你是一直保持自动更新这个扩展的吗？还是偶尔翻墙了 Chrome 自动更新。

**Comment by crimx** [comment]
我还没有时间做错误收集，你也可以看看当前页面和扩展管理里 background 的 console 有没有报错。

**Comment by sambodhi-cn** [comment]
是的，我一直保持自动更新，而且我一直在墙外。上周五，我还用了呢。。我天天都用，除了双休日

**Comment by sambodhi-cn** [comment]
我重装了chrome还是不行啊

**Comment by crimx** [comment]
在沙拉查词的设置中重置

**Comment by sambodhi-cn** [comment]
重置后可以了，个别地方要自己微调，谢谢。不知道用得好好的，怎么突然就坏了？

**Comment by crimx** [comment]
我也不清楚……偶尔也会有用户出现这样的问题，但我一直没法重现。猜八九成是跟浏览器扩展同步的那个存储有关，之前因为设置数据有可能过于庞大超过 quota per item，这个版本 gzip 了一下。

**Comment by sambodhi-cn** [comment]
今天发现，百度翻译不翻译了，但也没有像上次那样搜狗翻译出现一堆乱码。

**Comment by crimx** [comment]
网络问题吧，我这边是可以的

**Comment by crimx** [comment]
之前搜狗出现乱码是因为它偶尔会更新一个写死的字符串，后来我改成自动更新这个串就没有问题了。
