### ISSUE TITLE
希望在 Saladict 设置里的右键菜单栏里增加可以开关右键菜单的 switch

### ISSUE THREAD

**Issue by coldice945** [crimx/ext-saladict#325]
- Saladict 版本

6.27.2

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）

Chrome

- 类型：错误？建议？

右键菜单栏有开关 右键菜单的按钮；

**Comment by crimx** [comment]
你把右键菜单列表清空即可
