### ISSUE TITLE
查词范围不对，选中了句子，只弹出了单个词汇的翻译

### ISSUE THREAD

**Issue by Cosecant233** [crimx/ext-saladict#326]
</details>

- Saladict 版本
6.27.3

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）
win10 Firefox
用的surface的触屏，不过应该无所谓吧

- 类型：错误？建议？
选中一句话后点悬浮标以后弹出的翻译窗口只翻译了一个单词，貌似点到搜索框再点左边的返回上一词可以出现选中的句子

- 划词模式？以及其它觉得相关的设置。
都是默认模式吧，我应该没动过

- 重现：提供详细的可重现问题的操作。
youtube评论，其他还没试过，surface用触屏选中一个词，拖动选中范围至整句，然后点悬浮图标翻译，只显示单词翻译，貌似是第一个选中的词

- 期待：理想情况下扩展应该怎么做？
应该是选中多少翻译多少啦，我记得之前是可以的啊，不过以前是用的鼠标，不知道有没有关系。

- 实际：客观描述扩展实际上做了什么。
只翻译了第一个选中的词，没有管拉动范围以后的词。

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
你好，这个 bug 目前没有合适的解决方案。

- 目前的选词是在放手的一刻获取的，而调整选词之后没有相应的事件触发。
- 虽然可以在点击图标时再获取一遍，但因为这个选词可能存在层层嵌套的 frame 中，故倒过来找比较麻烦，目前就先不做实现了。

**Comment by barrer** [comment]
@crimx 试试`selectionchange`事件
```
// 选中变化事件：当点击已经选中的文本的时候，隐藏翻译图标（此时浏览器动作是：选中的文本已经取消选中了）
    document.addEventListener('selectionchange', function (e) {
        log('selectionchange event:', e);
        log('selectionchange:' + window.getSelection().toString());
        if (!window.getSelection().toString().trim()) {
            log('hide icon:selectionchange');
            hideIcon();
        }
    });
```

见：https://github.com/barrer/tampermonkey-script

这个扩展其实非常好，就是`TypeScript`不太熟。要是能提供类似`https://github.com/DIYgod/RSSHub`这个项目类似的，以接口的形式扩充就好了。方便那些只熟悉原生js写法的人，这样可能维护多个翻译引擎压力小一些。

出于隐私考虑，希望可以增加一个功能，点击指定词典后才触发请求，因为一些文字不便于发到各个翻译引擎。

**Comment by barrer** [comment]
chrome扩展请求的时候，好像是会带上这个域名的cookie的。例如我登录了百度账号，那么我天天翻译什么东西，百度全跟账号关联了。

**Comment by crimx** [comment]
@barrer 跟本 issue 不相关的反馈请放到新的 issue。我在这里做一下答复，如果需要继续讨论请新开 issue 。

- `selectionchange` 我看漏了这个 API 哈哈，这个我试试加上。
- 点击才触发查词这个 Saladict 早已支持设置，在每个词典的设置中，请看 wiki 使用说明。
- 百度 cookie 这个会在下个版本修复。

**Comment by crimx** [comment]
沙拉查词 7 已支持。
