### ISSUE TITLE
打不开沙拉查词

### ISSUE THREAD

**Issue by Oraculars** [crimx/ext-saladict#328]
如题 点击直接是一个小的空白方格 什么也没有

**Comment by crimx** [comment]
你好，如此粗略的反馈我很难给予解答。请新开一个 issue 并按模板描述。

此外附上

- 沙拉查词普通页面的弹框，有右上点击图标的弹框，还有独立窗口的弹框，是哪个（些）打不开。
- 所有的网页如此么？如果是特定网页请提供链接。
- 新安装扩展已打开的页面请刷新一下。
