### ISSUE TITLE
无法打开沙拉查词

### ISSUE THREAD

**Issue by Oraculars** [crimx/ext-saladict#329]
</details>

- Saladict 版本

最新版本 6.27.5

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）

windows 10 1803（17134.648）百分浏览器 64位 版本 3.9.2.45（正式版本） （64 位） (Chromium 72.0.3626.121)

- 类型：错误？建议？

在所有网页中都无法正常打开沙拉查词，点击之后只是一个空白的方格

- 划词模式？以及其它觉得相关的设置。

所有模式均不能使用 但可以进入设置

- 重现：提供详细的可重现问题的操作。

点击右上方的插件图标

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

我在另一台电脑上的插件可以正常打开，但新电脑不行，网络没有问题，可以上网。

![Snipaste_2019-03-26_16-56-19](https://user-images.githubusercontent.com/43881970/54983877-a160e680-4fe8-11e9-8bb2-975df55c38ab.png)

**Comment by crimx** [comment]
这种情况有可能是这个「百分浏览器」的问题。因为用户有限，这个浏览器不在 Saladict 支持维护范围，你可以尝试以下解决方式：

- 在 Saladict 设置中尝试重置。
- 不行的话右击这个白色的地方，选择最底的 Inspect ，看看 console 标签下有没有报错。
- 还是不行的话只能重装扩展。

**Comment by Oraculars** [comment]
似乎有错误 右上角有一个error 
下面有一个 display block 怎么解决呢 之前已经重装过插件了
也重置过了 还是不行
![Snipaste_2019-03-26_17-12-19](https://user-images.githubusercontent.com/43881970/54984840-a9ba2100-4fea-11e9-84f2-49a6c2ace28e.png)

**Comment by crimx** [comment]
你点一下那个 error 或者 console

**Comment by Oraculars** [comment]
![Snipaste_2019-03-26_17-12-19](https://user-images.githubusercontent.com/43881970/54985086-2220e200-4feb-11e9-8822-2d37aaa42c84.png)
![Snipaste_2019-03-26_17-18-05](https://user-images.githubusercontent.com/43881970/54985087-22b97880-4feb-11e9-883e-1541f195c996.png)
点了 似乎没反应

**Comment by crimx** [comment]
右上角显示 1 hidden 了，点那个输入框的 x 清空过滤器来显示所有。

**Comment by Oraculars** [comment]
![Snipaste_2019-03-26_17-23-00](https://user-images.githubusercontent.com/43881970/54985466-d0c52280-4feb-11e9-8c38-222bc9b53cf9.png)

**Comment by crimx** [comment]
点那个三角形展开，将里面的内容复制过来。

**Comment by Oraculars** [comment]
Uncaught (in promise) 
第一张图片：

﻿
popup.html:1 Uncaught (in promise) 
Object
message: "IO error: .../MANIFEST-000001: Unable to create sequential file (ChromeMethodBFE: 7::NewSequentialFile::4)"
__proto__: Object


第二张图片：
Object
message: "IO error: .../MANIFEST-000001: Unable to create sequential file (ChromeMethodBFE: 7::NewSequentialFile::4)"
__proto__:
constructor: ƒ Object()
hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()
toString: ƒ toString()
valueOf: ƒ valueOf()
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
get __proto__: ƒ __proto__()
set __proto__: ƒ __proto__()


![Snipaste_2019-03-26_17-25-06](https://user-images.githubusercontent.com/43881970/54985635-20a3e980-4fec-11e9-8b5f-e0d5684e0dab.png)
![Snipaste_2019-03-26_17-25-11](https://user-images.githubusercontent.com/43881970/54985636-20a3e980-4fec-11e9-908d-efa9b33bbe18.png)

里面还有好多三角形…… Orz

**Comment by crimx** [comment]
不需要了哈哈，这个情况是浏览器的问题了。有没有最近升级了浏览器，解决这个问题需要重装浏览器。

**Comment by Oraculars** [comment]
好的我试试

**Comment by crimx** [comment]
见 #183 和 #295

**Comment by Oraculars** [comment]
搞定了 哭辽 谢谢作者细心耐心迅速及时的解答 mua 再也不更新浏览器辽

**Comment by crimx** [comment]
不客气哈哈，保持更新还是要的。
