### ISSUE TITLE
建议：关于chrome打开PDF本地文件

### ISSUE THREAD

**Issue by yakumosumi** [crimx/ext-saladict#330]
- 类型：建议

- 期待：能否在chrome打开本地pdf的时候自动进入扩展pdf阅读器模式

**Comment by crimx** [comment]
安装时不是弹出了使用方式了么，https://github.com/crimx/ext-saladict/wiki/Instructions

**Comment by yakumosumi** [comment]
直接双打开pdf文件的时候并没有自动跳转。

**Comment by yakumosumi** [comment]
> 
> 
> 安装时不是弹出了使用方式了么，https://github.com/crimx/ext-saladict/wiki/Instructions

我的意思是直接双击打开电脑里的本地PDF文件时是不会直接进入扩展阅读器的，必须要手动刷新一下才会自动打开。不知道这个能不能一步到位？ @crimx

**Comment by crimx** [comment]
浏览器开着的情况下是可以的，否则扩展还没载入无法拦截。

**Comment by DerekTso** [comment]
@crimx 浏览器中打开过PDF，能否给添加一个最近打开的记录，方便继续上次阅读PDF文件？

**Comment by crimx** [comment]
建议你改用本地的 PDF 阅读器搭配[浏览器外划词](https://saladict.crimx.com/native.html)。
