### ISSUE TITLE
#错误#无法查词，划词后不会弹出字典

### ISSUE THREAD

**Issue by BaldStrong** [crimx/ext-saladict#332]
- Saladict 版本
6.27.7

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）
win10

- 类型：错误？建议？
错误
无法查词，划词后不会弹出字典，点搜索也无效，换成上一版本就可以。
![image](https://user-images.githubusercontent.com/37842039/55283541-2dcc2a00-5398-11e9-935f-6d977893d24c.png)

**Comment by BaldStrong** [comment]
我发现这个错误是由于我导入了之前旧版本的设定文件导致的。我不导入就行。
我的浏览器是360浏览器。

**Comment by crimx** [comment]
嗯，因为原设置可能超过了一次同步的最大容量，最近版本优化了设置结构，导致旧版本导入有兼容问题。不过应该不会再进行这样的大改动了。
