### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by tyronetyrone** [crimx/ext-saladict#333]
mac firefox 点击右上角图标并查词，内容超过一屏长度之后  滑动滚动条会白屏，必现

**Comment by crimx** [comment]
请你按模板反馈提供完整信息，最好能截图（包括沙拉的图标一起截了）

**Comment by tyronetyrone** [comment]
![image](https://user-images.githubusercontent.com/13401082/55401884-9f68cb80-5584-11e9-9fe0-0859601abba2.png)
![image](https://user-images.githubusercontent.com/13401082/55401920-b60f2280-5584-11e9-832c-ed0839a23202.png)
火狐开发版

**Comment by tyronetyrone** [comment]
每次滚动滚动条都要等个几秒钟之后 才恢复

**Comment by crimx** [comment]
这应该是开发版的渲染 bug ，稳定版没有这个问题。

**Comment by mengdaxing** [comment]
I can reproduct this issue exactly.
Hope reopen it

**Comment by crimx** [comment]
I cannot reproduce, on the other hand. Are you using Firefox Developer Edition? I would rather not wasting my time fixing issues for unstable platforms. If this happens on a Firefox stable release, please fire a bug on Bugzilla instead.
