### ISSUE TITLE
看图说事

### ISSUE THREAD

**Issue by tumble1** [crimx/ext-saladict#334]
扩展和chrome，firefox都是最新版，系统是win10。
**复现步骤**
![2](https://user-images.githubusercontent.com/49236036/55475790-752c1200-5647-11e9-9241-435d772b2197.gif)

**问题**
为什么会出现下图右边的查词界面呢？
![图片](https://user-images.githubusercontent.com/49236036/55475862-a0166600-5647-11e9-98ea-c0b1a4c29d34.png)

**Comment by crimx** [comment]
这个是给你看设置改变的效果的。

**Comment by crimx** [comment]
你的窗口貌似有点小，这是在什么设备上的？

**Comment by tumble1** [comment]
好吧，我一直以为是个bug。没想到是个特性

**Comment by tumble1** [comment]
> 
> 
> 你的窗口貌似有点小，这是在什么设备上的？
为了录制文件不太大，录制的时候我把chrome窗口缩小了，设备就是笔记本电脑

**Comment by crimx** [comment]
好的。
