### ISSUE TITLE
面板大小调节建议+词典建议+PDF推荐

### ISSUE THREAD

**Issue by yiyuan101** [crimx/ext-saladict#336]
- Saladict 版本：6.27.8

- 平台：Google Chrome 73.0.3683.86（64 位）

- 类型：建议

- 期待：
面板大小可以直接用鼠标拖拽调节
添加CNKI翻译助手
另外，推荐配合另一款插件kami来使用，用kami打开PDF效果比pdf.js更好

- 实际：
面板大小只能在设置里填写来调节
没有CNKI翻译助手

**Comment by crimx** [comment]
你好

1. 改变面板大小是一个相对不那么常用的操作，拖动调节会增加不必要的实现难度。（有人愿意提交 PR 也是欢迎的）
1. 「CNKI 翻译助手」可能会添加，但因为我不太用这个，得看时间或者其他人实现。
1. 跨扩展植入在目前是不可以实现的，除非你[手动允许](https://github.com/crimx/ext-saladict/wiki/Instructions#chrome)（危险操作）。

**Comment by greatunicorn** [comment]
同样期待添加「CNKI 翻译助手」，对于学术词汇和论文翻译很有帮助
