### ISSUE TITLE
无法使用自己搭建的WebDAV服务器

### ISSUE THREAD

**Issue by huangdaren1997** [crimx/ext-saladict#339]
- Saladict 版本
6.27.8

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）
ubuntu 18.04 Chrome

- 类型：错误？建议？
错误

- 划词模式？以及其它觉得相关的设置。

- 重现：提供详细的可重现问题的操作。
添加webDAV同步
服务器地址http://47.107.57.26/webdav
用户alex
密码1997hifai
显示连接服务器失败

- 期待：理想情况下扩展应该怎么做？
希望可以使用自定义的webDAV服务器

- 实际：客观描述扩展实际上做了什么。

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
你的服务器配置有问题，404 了。
