### ISSUE TITLE
关于谷歌翻译的建议

### ISSUE THREAD

**Issue by Briy09** [crimx/ext-saladict#340]
- Saladict 版本 v6.27.8
- 平台：win10 Chrome版本 73.0.3683.75
- 类型：建议

- 期待：
1. 谷歌cn网页翻译 能否与 谷歌网页翻译 区别。即去掉其他语言，只保留中文。
```
  function googleTranslateElementInit (){
    new google.translate.TranslateElement({
      pageLanguage: 'auto'
+     includedLanguages: 'zh-CN'
    },'google_translate_element');
  }

```
`$main.src = b + '/translate_static/js/element/main_zh-CN.js';`
https://github.com/crimx/ext-saladict/blob/13b815f3d46365beedcaac34c83845d97fb24455/public/static/google-page-trans.js#L50
2. 有时候翻译框被其他div覆盖，能否给`id = 'google_translate_element`加个`z-index: 9999; top: 100px; left: 100px`
 
 虽然可以自己用stylus实现：）

3. 希望实现 点击一次 谷歌网页翻译，即马上出现 翻译条并翻译成中文，而不是选择下拉的窗口（此处有坑，慎入）。

![翻译条](https://user-images.githubusercontent.com/49552463/56023697-0b93be00-5d41-11e9-9c42-890f5f651bb1.png)
翻译条

![下拉窗口](https://user-images.githubusercontent.com/49552463/56023710-13ebf900-5d41-11e9-8707-ae395b4188c6.png)
下拉窗口

目前的情况是在某个外语网站，点击网页翻译，出现 选择下拉的窗口，选择中文，出现翻译条并翻译。然后此操作就被记录在cookie里，在**同一个外语网站**第二次点击，可以实现马上出现 翻译条并翻译。
但缺点有二：a，必须是同一网站，其他网站则不行。b，清除了cookie则无效。

想实现的情况：直接把 翻译成中文 写死在 扩展里。然后 点击一次 谷歌网页翻译，即马上出现 翻译条并翻译成中文，就和目前的“有道网页翻译一样”。

谷歌了下“auto translate googleTranslateElementInit trigger”也没有什么好办法。

4. 能否把一些静态资源放到扩展文件夹里，然后用 相对路径 引用。
```
https://translate.googleapis.com/translate_static/css/translateelement.css 
https://translate.googleapis.com/translate_static/js/element/main_zh-CN.js 
https://translate.googleapis.com/translate_static/img/te_bk.gif
```
等等。

目的：因为你懂的原因，导致有些资源 访问不了 或 加载很慢 ，导致翻译不了。虽然有人说googleapis在北京有服务器，但有时候会抽风。

最后：其实都是不怎么重要的建议，工作量有些大，还有坑，希望无聊时看看就行，不解决也没关系，毕竟现在的沙拉查词已经非常完美了，还有身体健康最重要：）

**Comment by crimx** [comment]
你好，

先回答写死中文的问题，因为这个扩展还有其它语种的用户在使用，如果是做成设置倒是可以的。

静态资源的问题，因为翻译也是在 `translate.googleapis.com`，如果加载不了的话自然就翻译不了。现在扩展体积有点大，就不再加不必要的资源了。

样式和翻译问题，有空会研究研究。

**Comment by Briy09** [comment]
你好，谢谢回复。
1. 写死中文，是说 只改变 `谷歌cn网页翻译`，这个是给同胞专用的啊。而 其它语种的用户 可以用 `谷歌网页翻译`。做成设置也行：）
2. 关于翻译框被其他div覆盖，比如 https://thenextweb.com

**Comment by KnIfER** [comment]
谷歌翻译的这个js有文档吗，怎么只翻译一部分dom啊？

**Comment by crimx** [comment]
没有文档，好像加特定类名可以跳过。
