### ISSUE TITLE
因有道翻译接口一直默认中英互译，建议使用自动检测语言接口

### ISSUE THREAD

**Issue by youkoulc** [crimx/ext-saladict#343]
- Saladict 版本：6.27.8

- 平台：WIN10 Chrome  73.0.3683.103（正式版本） （32 位）

- 类型：建议

- 期待：用有道翻译翻译其他语言能像其他翻译接口一样，不必跳转到网页做选择语言种类的操作
，建议增加http://fanyi.youdao.com/    替代 https://dict.youdao.com/w/。

- 实际：有道翻译接口一直默认中英互译，翻译其他语言还是多有不便，需跳转网页做进一步操作

- （可选）额外信息：
![image](https://user-images.githubusercontent.com/49615746/56095324-15b6e780-5f0e-11e9-9787-b59d6d9386bc.png)

**Comment by crimx** [comment]
我觉得翻译已经够多了……

**Comment by youkoulc** [comment]
> 我觉得翻译已经够多了…… 有道翻译相比其它几个没有什么特色

就我个人的体验来说，这几家机器翻译可靠性最高的就是谷歌和有道了，甚至有些长句有道翻译的准确性是强于谷歌的。
不过，我提到只是提升用户体验的一个小小建议而已，目前来说这款插件也已经完全够用，谢谢开发者的用心制作。^_^

**Comment by crimx** [comment]
谢谢你的建议！

翻译涉及到上下文，是个很个性化的东西。而对于日常的文章，现在市面上的几个翻译引擎均有瑕疵，但差距也不是特别大。「有些」强于其它的比较是没有什么意义的。

本扩展通过对比阅读来解决不可靠的问题，但我本人更倾向查词典而不是看整句翻译。且翻译引擎破解比词典难度要大，故暂时只维护现有的几个。
