### ISSUE TITLE
无法解压缩扩展程序

### ISSUE THREAD

**Issue by adolphnov** [crimx/ext-saladict#344]
**问题描述**：
使用最新版正式版chrome浏览器，在官方应用商店安装saladict时，出现无法安装的问题，chromuim浏览器同样如此。

![出现如上提示](https://i.loli.net/2019/04/15/5cb418bf721a8.png)

- console标签下的错误如下
![console信息](https://i.loli.net/2019/04/15/5cb41aad530aa.png)
---
- 平台：WIN10 64位家庭版
- Chrome版本： 73.0.3683.103（正式版本） （64 位）

**Comment by crimx** [comment]
这是谷歌商店的问题，且很可能是你网络的问题。你可以下载 ext 拖入扩展管理页面安装。

**Comment by adolphnov** [comment]
> 这是谷歌商店的问题，且很可能是你网络的问题。你可以下载 ext 拖入扩展管理页面安装。

试过了，就这个插件存在这种问题，本地拖入提示无效。
![](https://i.loli.net/2019/04/15/5cb43a222e96c.png)

**Comment by crimx** [comment]
是在 <https://github.com/crimx/ext-saladict/releases> 推荐的地方下载的吗？如果多处地方下载都出现这样的问题，不排除是防火墙或杀毒软件之类污染了下载文件。

**Comment by adolphnov** [comment]
> 是在 https://github.com/crimx/ext-saladict/releases 推荐的地方下载的吗？如果多处地方下载都出现这样的问题，不排除是防火墙或杀毒软件之类污染了下载文件。

在 [chrome-extension-downloader](https://chrome-extension-downloader.com/)上下载的。

**Comment by crimx** [comment]
应该不是本扩展的问题，这边也帮不了你什么了。

**Comment by crimx** [comment]
你可以对比一下文件校验值

```
MD5: 2397539BE6C52464959E9D836979EB75
SHA1: 8B4F6ED62B2B67F8ABF8BF935B50B558498A5A89
SHA-256: B9497C803E24F48017507C984358E28F54D8708F89A6AB36C2EF9FDE5451B230
```

**Comment by adolphnov** [comment]
一样的...

项目 | 项目值
-- | --
沙拉查词-聚合词典划词翻译_v6.27.8.crx（3.3/3.3 MiB）\| 耗时: 1.25s @ 2.62 MiB/s \| 1555319784389
CRC-32 | f91d7f8b
MD5 Hash | 2397539be6c52464959e9d836979eb75
SHA1 Hash | 8b4f6ed62b2b67f8abf8bf935b50b558498a5a89
SHA256 Hash | b9497c803e24f48017507c984358e28f54d8708f89a6ab36c2ef9fde5451b230

**Comment by crimx** [comment]
这样可以排除扩展文件的问题，就可以把问题定位到浏览器上，大致有两种情况。

1. 浏览器进行过特殊的配置导致冲突。还没有用户反馈过这样的情况。
2. 浏览器本身出现问题，可能是升级出错。有三位用户出现过类似的问题，见 Wiki 常见问题。

解决方式建议重启设备，还是不行建议重装浏览器。

**Comment by adolphnov** [comment]
已通过自行解压ext，加载已解压扩展程序解决问题。

**Comment by mlzboy** [comment]
我做的插件也遇到类似的问题，请问您最后是怎么解决的

**Comment by crimx** [comment]
是大量用户出现这个问题么？沙拉查词目前只收到这一个反馈。

**Comment by liqiao-ponyai** [comment]
我刚才也遇到了这个问题，已经搞定了，给后来者发一下解决步骤：

1. 下载crx文件
从这个链接下载
https://clients2.google.com/service/update2/crx?response=redirect&prodversion=[PRODVERSION]&acceptformat=crx2,crx3&x=id%3D[EXTENSIONID]%26uc
[PRODVERSION] 是你的chrome版本号
[EXTENSIONID] 是extention ID，从extention的链接里能找到
（详见https://stackoverflow.com/questions/7184793/how-to-download-a-crx-file-from-the-chrome-web-store-for-a-given-id）
2. 本地解压
创建一个空目录，把你刚才下载的xxxxx.crx放进去，unzip xxxxx.crx
3. 安装
打开 chrome://extensions/ ，右上角打开开发者模式，左上角点击“加载已解压的扩展程序”，选中你第2步创建的目录

齐活
ps. 出现这个问题好像是chrome解压不了crx文件，我怀疑把crx文件的默认打开方式换成unzip能解决这个问题，不过我电脑上因为一些配置问题验证不了。。。其他人遇到了这个问题也可以试试这条路
