### ISSUE TITLE
希望划词习惯加入情景模式设置中

### ISSUE THREAD

**Issue by ttttmr** [crimx/ext-saladict#346]
- Saladict 版本

6.28.1

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）

Windows 10，Vivaldi 2.4.1488.40

- 类型：错误？建议？

建议

- 划词模式？以及其它觉得相关的设置。

划词习惯和情景模式的设置

- 重现：提供详细的可重现问题的操作。

- 期待：理想情况下扩展应该怎么做？

希望划词习惯加入情景模式设置中，不同情景下可以使用不同的划词方式，比如默认模式和翻译模式下，默认情况下使用不多，也经常选中复制操作，就会选显示图标悬浮查词，而在翻译的时候使用频率较高，悬浮就很麻烦了，直接显示会比较方便

- 实际：客观描述扩展实际上做了什么。

现在所有情景共用一个划词模式了，记得在老版本（设置页UI还没改）里是分开的，希望能加回来

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
你好，建议使用快捷键切换。

**Comment by ttttmr** [comment]
好的吧，因为我用快捷键的时候容易有冲突😂

**Comment by crimx** [comment]
最新版提供的那个独立窗口侧边栏布局很适合翻译的时候使用，直接三按 ctrl/command 即可调出。

**Comment by ttttmr** [comment]
这个也冲突了😂双击Ctrl唤起Listary

**Comment by crimx** [comment]
这个留给你自行衡量了，也可以设置其它快捷键。
