### ISSUE TITLE
关于增加生词本导出选项的建议

### ISSUE THREAD

**Issue by liuxin777** [crimx/ext-saladict#347]
<details><summary>反馈说明</summary>

使用相关的问题请阅读使用方式：
https://github.com/crimx/ext-saladict/wiki#wiki-content

你的问题可能已被回答过，请阅读常见问题及答复：
https://github.com/crimx/ext-saladict/wiki/Q&A

请根据模板描述问题，以便别人理解、定位和解决问题。
请根据模板描述问题，以便别人理解、定位和解决问题。
请根据模板描述问题，以便别人理解、定位和解决问题。

== 提交前删除下一行以及到以上*所有*内容，并填充下面模板 ==
1 请问生词本导出可以把时间加上去吗，否则只能在笔记里面手动添加再通过excel截取
2 还有生词本翻译那个地方能不能多一些选项，比如导出bing词典，去掉baidu之类的

- Saladict 版本
6.28.1

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）
win10,chrome 
72.0.3626.121（正式版本） （64 位）

- 类型：错误？建议？
建议

- 划词模式？以及其它觉得相关的设置。
生词本

- 重现：提供详细的可重现问题的操作。

- 期待：理想情况下扩展应该怎么做？
在生词本导出处增加%date%方便管理

- 实际：客观描述扩展实际上做了什么。
没有%date%选项

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。
![image](https://user-images.githubusercontent.com/44891734/56457429-69fa1580-63ad-11e9-89fb-80a5e73fe1c9.png)

**Comment by liuxin777** [comment]
emmmm，好吧，也许我应该通过时间筛选再导出，然后通过excel增加时间。再与之前导出的内容合并。这样也挺方便的

**Comment by crimx** [comment]
建议导出后删除。
