### ISSUE TITLE
查词后翻页内容未能正常显示，需要等数秒才能显示

### ISSUE THREAD

**Issue by geekpany** [crimx/ext-saladict#348]
- Saladict 版本

    6.28.1

- 平台：包括操作系统和 Chrome/Firefox 版本（或者其它浏览器版本）

    macOS 10.14.4 Firefox 66.0.3

- 类型：错误？建议？

    错误

- 划词模式？以及其它觉得相关的设置。

    非划词模式

- 重现：提供详细的可重现问题的操作。

    点击浏览器上的沙拉查词按钮，在输入框中查词，鼠标翻页，内容变白，需要等数秒才会显示出文本。如下图所示：

    ![saladict_feedback](https://user-images.githubusercontent.com/34344425/56468528-725f5880-6460-11e9-8e2e-9201d4d35338.gif)

- 期待：理想情况下扩展应该怎么做？

    翻页时正常显示文本。

- 实际：客观描述扩展实际上做了什么。

    翻页时文本未正常显示，需要等数秒才能显示出来。

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
这貌似是 Mac 上 Firefox 的问题，你的是测试版还是稳定版。

**Comment by geekpany** [comment]
是最新的稳定版
Version: 	66.0.3
Build ID: 	20190409155332
Update Channel: 	release

**Comment by crimx** [comment]
这个是 Firefox 新版的 bug ，之前测试版就有了，应该做了什么渲染优化，没发现问题稳定版就发布了。现在我无法重现所以也不好修复。

**Comment by geekpany** [comment]
好的，明白了。谢谢作者的付出，辛苦了！

**Comment by zhanglinbo** [comment]
同样的问题，好像5、6秒才出来

**Comment by crimx** [comment]
我的建议是先不要升级火狐最新版。它这个版本实现了一些滚动相关的 CSS3 新规范，底层应该重写的比较多。

**Comment by crimx** [comment]
火狐已经更新了几个版本，现在还有这个问题吗？

**Comment by geekpany** [comment]
Firefox 67.0 Build ID 20190516215225
沙拉查词 6.30.0

问题依然存在

**Comment by crimx** [comment]
这个可能跟火狐的硬件加速有关，有调整过这方面的设置吗。只有这个地方出现这种情况是不是？在其它页面面板是否正常？

**Comment by crimx** [comment]
[火狐论坛](https://support.mozilla.org/zh-CN/questions/1029512)还提到可能跟主题有关，你可以排查一下，但我估计十有八九是硬件加速的问题。

> Start Firefox in Safe Mode to check if one of the extensions (Firefox/Tools > Add-ons > Extensions) or if hardware acceleration is causing the problem.
> 
> Switch to the DEFAULT theme: Firefox/Tools > Add-ons > Appearance
> Do NOT click the Reset button on the Safe Mode start window
> https://support.mozilla.org/kb/Safe+Mode
> https://support.mozilla.org/kb/Troubleshooting+extensions+and+themes

> To disable hardware acceleration in Firefox.
> 
> Tools > Options > Advanced > General > Browsing: "Use hardware acceleration when available"
> https://support.mozilla.org/kb/Troubleshooting+extensions+and+themes
> https://hacks.mozilla.org/2010/09/hardware-acceleration/

**Comment by geekpany** [comment]
破案了！关掉硬件加速，重启 Firefox，Popup Panel 查词翻页正常了。谢谢指导！

之前问题出现场景如下：

- Popup Panel 有问题
- Quick Search 翻页正常
- Inline translation 翻页正常

**Comment by crimx** [comment]
嗯，硬件加速有时会跟显卡冲突。

**Comment by crimx** [comment]
火狐已确认问题，等待火狐团队修复更新即可。

**Comment by geekpany** [comment]
太棒了！
