### ISSUE TITLE
查词面板查词记录不能选择下一个

### ISSUE THREAD

**Issue by lj123454321** [crimx/ext-saladict#349]
<!––
使用相关的问题请阅读使用方式：
https://github.com/crimx/ext-saladict/wiki#wiki-content

你的问题可能已被回答过，请阅读常见问题及答复：
https://github.com/crimx/ext-saladict/wiki/Q&A

请根据模板描述问题，以便别人理解、定位和解决问题。
请根据模板描述问题，以便别人理解、定位和解决问题。
请根据模板描述问题，以便别人理解、定位和解决问题。
-->

- Saladict 版本 6.28.1

- Windows 10 Chrome 73.0.3683.103

- 类型：错误

- 重现：划词或者点击工具快捷方式图标出现的查词面板，如果不关闭面板连续查了多个词，只能点击“上一个”，点击了上一个查看了历史记录之后，下一个的图标是灰色的，无法点击。

**Comment by crimx** [comment]
我看看怎么优化这里
