### ISSUE TITLE
建议增加面板消失时间

### ISSUE THREAD

**Issue by libukong007** [crimx/ext-saladict#350]
建议增加翻译面板自动消失时间，点完一个翻译后还要再点空白处才能消失面板。建议给一个面板自动消失时间的选项，3到8秒最好。

**Comment by libukong007** [comment]
另外，生词能不能自动保存，顺便保存这个单词的句子，然后在复习生词方面，能不给给一个测试生词的版块。像那种记单词一样的功能。

**Comment by crimx** [comment]
你好，谢谢你的反馈！

1. 自动消失面板。不考虑添加。
2. 生词和句子自动保存。查看设置。
3. 背单词功能。不考虑添加（过于复杂且已有不少优秀的软件）。请导出到专门的软件中背。
