### ISSUE TITLE
【Linux，Firefox, 6.28.1版本】CPU占用100%

### ISSUE THREAD

**Issue by wilkice** [crimx/ext-saladict#351]
- Saladict 版本
6.28.1

- 平台：操作系统版本，Chrome/Firefox 版本，是否测试版
Linux, Firefox, 非测试版

- 类型：错误？建议？
bug: 打开沙拉查词拓展后CPU占用率一直在100%， 打开其他拓展不会导致此现象。卸载沙拉查词再安装依然如此

- 划词模式？以及其它觉得相关的设置。

- 重现：提供详细的可重现问题的操作。
Linux 下 Firefox 开启沙拉查词就有此现象。

- 期待：理想情况下扩展应该怎么做？
期待：正常占用就可以了，我这里只要一开查词， 风扇就转个不停

- 实际：客观描述扩展实际上做了什么。

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

我做了以下实验：

**开启沙拉查词与其他拓展**：

![](https://i.bmp.ovh/imgs/2019/04/90e871a051d9e6ce.png)

**关闭沙拉查词但打开其他所有拓展**：

![](https://i.bmp.ovh/imgs/2019/04/43989d20407cf066.png)

**关闭其他任意一个拓展打开沙拉查词**：

![](https://i.bmp.ovh/imgs/2019/04/daa095abf3d8bd0b.png)

**Comment by crimx** [comment]
这有点奇怪，我一直用 Arch 没有出现这样的情况。

Saladict 的运算集中在解析结果和 UI 渲染上，没有划词时占用应该极低的。

这很可能是与浏览器的某些设置冲突了或者是 Firefox 的 bug ，你没有提供版本，请升级到 Firefox 最新版看看还有没有问题。

**Comment by crimx** [comment]
如果还出现的话， top 的 COMMAND 那栏可以复制完整的信息过来，我可以帮忙查查有没有人遇到类似的问题。

**Comment by wilkice** [comment]
Firefox 版本是66.0.3， Command 那里是 `WebExtensions`，我晚上再重新装下浏览器，谢谢您的回复哈 :smile: 

![](https://i.bmp.ovh/imgs/2019/04/345d4be767578a95.png)

**Comment by crimx** [comment]
没查到类似的问题，先关了，有问题可以继续反馈。

**Comment by crimx** [comment]
很可能是因为 WebDAV 配置导致的，见 #361 。修复版本正在发布。

**Comment by wilkice** [comment]
删除了坚果云 WebDAV 之后就正常了 :smile:
