### ISSUE TITLE
”面板大小“实现全局设置

### ISSUE THREAD

**Issue by Erbzur** [crimx/ext-saladict#352]
- Saladict 版本    6.28.1

- 平台：win10, Chrome 72 stable

- 类型：建议

- 面板大小

- 重现：浏览器地址栏右边点击扩展图标出现面板

- 期待：点击图标出现的面板大小和“查词面板”里的设置一致，即希望实现“面板大小”全局设置

- 实际：点击图标出现的面板大小仍为默认大小（设置里我已经调小了宽度）

**Comment by crimx** [comment]
此面板还没有时间支持，我会看看。
