### ISSUE TITLE
FireFox 66.0.3 (64 位)下，saladict插件被禁用

### ISSUE THREAD

**Issue by maggiedot** [crimx/ext-saladict#353]
- Saladict 版本
插件禁用后，版本无法确定。

- 平台：操作系统版本，浏览器名字及版本（测试版或开发者版的浏览器不在 Saladict 支持范围）
Windows 10 企业版，最新版FireFox （66.0.3 (64 位)），saladict插件被禁用。
![image](https://user-images.githubusercontent.com/6770380/57186617-13e0b280-6f15-11e9-93b3-6bfc0c668a8b.png)

![image](https://user-images.githubusercontent.com/6770380/57186646-ab460580-6f15-11e9-8e81-a5711cde78d3.png)

图中`了解详情`链接地址：[https://support.mozilla.org/1/firefox/66.0.3/WINNT/zh-CN/unsigned-addons](https://support.mozilla.org/1/firefox/66.0.3/WINNT/zh-CN/unsigned-addons)，之前使用一直正常，怀疑是浏览器后台更新了版本。

非常感谢作者的辛苦付出及维护。

**Comment by crimx** [comment]
见 https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

火狐出问题了，等它更新吧，或用里面提到的 work-arounds （不推荐）。

**Comment by maggiedot** [comment]
原来是这么回事儿……这波操作看来影响很大呢。

**Comment by crimx** [comment]
是的，有人要背大锅了哈哈。应该很快会收到更新。

**Comment by maggiedot** [comment]
嗯，坐等看戏。阿不，更新:)

**Comment by crimx** [comment]
火狐更新确认已解决。
