### ISSUE TITLE
有道网页翻译入门级以上均检测不到难词，无法使用

### ISSUE THREAD

**Issue by hyyc554** [crimx/ext-saladict#354]
- Saladict 版本
6.29.0

- 平台：操作系统版本，浏览器名字及版本（测试版或开发者版的浏览器不在 Saladict 支持范围）
win10 GoogleChrome 73.0.3683.103（正式版本）

- 类型：错误？建议？
有道网页翻译功能下，所有网页的入门和以上级别翻译，都检测不到难词。全文翻译正常

- 划词模式？以及其它觉得相关的设置。

- 重现：提供详细的可重现问题的操作。
任意一个英文网页，目前均不可支持入门级以上的翻译

- 期待：理想情况下扩展应该怎么做？
前几个版本似乎没有这个问题，期望及时修复。师妹写论文要用这个功能：）

- 实际：客观描述扩展实际上做了什么。

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。
![TIM图片20190505174759](https://user-images.githubusercontent.com/31528034/57191971-069be600-6f5e-11e9-97a1-8874ff809156.png)

**Comment by crimx** [comment]
本插件没有发现错误信息，打开[官网](http://fanyi.youdao.com/web2/)使用官方的例子可以看到是有道翻译本身的问题。

**Comment by hyyc554** [comment]
> 本插件没有发现错误信息，打开[官网](http://fanyi.youdao.com/web2/)使用官方的例子可以看到是有道翻译本身的问题。

测试了一下，还真有道翻译的问题，有道那边这个功能似乎确实不怎么稳定了。感谢回复，祝工作顺利：)

**Comment by crimx** [comment]
有道这个东西没更新好多年了，看着稳定才整合进来给兼容 https，其它问题没有精力扒源码了。生词多的话可以试试新版的侧边栏布局。

祝论文顺利，早日摆脱全文翻译。
