### ISSUE TITLE
在生词本设置导出格式时，特定操作会导致导出面板关闭。

### ISSUE THREAD

**Issue by JFSelf** [crimx/ext-saladict#355]
- Saladict 版本 

6.29.0

- 平台：win10 ，chrome浏览器   73.0.3683.103（正式版本） （64 位）

- 类型：错误

-重现：

![bug](https://user-images.githubusercontent.com/46085220/57285467-dbdc9980-70e5-11e9-8350-ee5f276ab74d.gif)

长按鼠标左键选择文本并将鼠标移到窗口外时，导出单词格式窗口会关闭。

应该是和鼠标左键单击窗口外空间关闭窗口冲突了。

**Comment by crimx** [comment]
这是期望效果。
