### ISSUE TITLE
Prompt:Download failed. Please check your connection

### ISSUE THREAD

**Issue by AELe** [crimx/ext-saladict#356]
- Saladict 版本
Download Saladictby CRIMX by firefox store
- 平台：操作系统版本，浏览器名字及版本（测试版或开发者版的浏览器不在 Saladict 支持范围）
![image](https://user-images.githubusercontent.com/16604753/57299082-4ac9ea80-7106-11e9-889e-e9fcbd8b48b8.png)

- 类型：错误？建议？

Download failed. Please check your connection

- 划词模式？以及其它觉得相关的设置。

- 重现：提供详细的可重现问题的操作。
I am download the saladict plugin from firefox store but it tell me that Download failed. Please check your connection

- 期待：理想情况下扩展应该怎么做？

How can I get the plugin "saladict"?

- 实际：客观描述扩展实际上做了什么。

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
请更新火狐到最新版
