### ISSUE TITLE
同时开白名单和黑名单，白名单在play.google.com/books看书时不work

### ISSUE THREAD

**Issue by superxiao** [crimx/ext-saladict#357]
- Saladict 版本
6.29.0

- 平台：操作系统版本，浏览器名字及版本（测试版或开发者版的浏览器不在 Saladict 支持范围）
Windows10, Chrome, 74.0.3729.131 64bit

- 类型：错误？建议？
应该是个bug

- 划词模式？以及其它觉得相关的设置。
双击选择取词

- 重现：提供详细的可重现问题的操作。
在黑名单开  https://\*/\* (黑所有)
在白名单开  https://play.google.com/* (白google play商店，包括google 在线读书器)

在https://play.google.com/store/books 随便点开一本free sample, 双击取词翻译不work. 但是在https://play.google.com/ 其他地方可以取词翻译。

- 期待：理想情况下扩展应该怎么做？
在https://play.google.com/books 读书时可以取词。

- 实际：客观描述扩展实际上做了什么。
在https://play.google.com/books 读书时不能取词翻译。但是在https://play.google.com/ 其他地方可以取词翻译。

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
> https://play.google.com/ 其他地方可以取词翻译。

这说明扩展是没问题的。图书其实是加载在 `https://books.googleusercontent.com` 域名下，但真正的问题在于 Google 在这里自行实现了一套选词机制（跟 Google Doc 一样），所以 Saladict 无法通过浏览器的接口获得选词。

这个兼容起来有点工作量，我本身也很少在这些地方划词，所以几乎是不会去实现了。有其他人提 PR 也是欢迎的。

它这个阅读器本身也提供了划词，应该可以满足大部分需求。你可以打开 Saladict 的独立查词窗口为侧边栏模式，遇到难词再做深入查询。

**Comment by superxiao** [comment]
谢谢回复。图书页面不加黑白名单的话是可以取词的，我一直再用，就是看完书了要disable应用。试了https://books.googleusercontent.com 加白名单好像也不管用。不过不是大问题，应用还是很好用的。

**Comment by superxiao** [comment]
刚试了把
https://*.googleusercontent.com/*
https://play.google.com/*
一起加白名单，好像可以了。

**Comment by crimx** [comment]
可以用这么奇怪 :joy: ，可能是你有什么配置吧，我预览的页面书本的文字都是给设了 `user-select: none;` ，即禁止了默认的选词。

可以就行。另外也可以设快捷键关闭划词，点击地址栏旁的图标打开下面也有开关。
