### ISSUE TITLE
能增加各种翻译的常用词组么?

### ISSUE THREAD

**Issue by Sandural** [crimx/ext-saladict#358]
记单词, 还是有常用词组更容易记住, 比如搜 serious, 常用词组就有: serious damage,之类的. 每个词汇软件都不一样, 但是有总比没有好撒.,... 😃

**Comment by crimx** [comment]
你好，几大英英词典都提供了 Synonyms 或 Thesaurus 。

**Comment by crimx** [comment]
另外也可以查看词典提供的例句，下个版本会有更多句库词典。
