### ISSUE TITLE
你好，设置查词面板宽度不小心设置太大，导致面板占满了屏幕，再重新在options中设置时，所有选项都被面板挡住了，没法设置，怎么恢复默认大小

### ISSUE THREAD

**Issue by siyuan-zhang** [crimx/ext-saladict#359]
- Saladict 版本

- 平台：操作系统版本，浏览器名字及版本（测试版或开发者版的浏览器不在 Saladict 支持范围）

- 类型：错误？建议？

- 划词模式？以及其它觉得相关的设置。

- 重现：提供详细的可重现问题的操作。

- 期待：理想情况下扩展应该怎么做？

- 实际：客观描述扩展实际上做了什么。

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
按住绿条面板可以拖动。
