### ISSUE TITLE
维基百科切换一次语言后，无法再次切换其他语言

### ISSUE THREAD

**Issue by loveky** [crimx/ext-saladict#360]
- Saladict 版本

6.29.0

- 平台：操作系统版本，浏览器名字及版本（测试版或开发者版的浏览器不在 Saladict 支持范围）

macOS Mojave 10.14 (18A391)
Chrome 74.0.3729.131（正式版本） （64 位）

- 类型：错误？建议？

错误

- 划词模式？以及其它觉得相关的设置。

维基百科 -> 获取全部语言列表 -> 选择一种语言 -> 再次点击获取全部语言列表

- 重现：提供详细的可重现问题的操作。

见gif

![bug](https://user-images.githubusercontent.com/1198651/57453395-e4290600-7298-11e9-90b7-303648fe7838.gif)

- 期待：理想情况下扩展应该怎么做？

可以继续选择其他语言

- 实际：客观描述扩展实际上做了什么。

下拉菜单无内容

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
我看看是什么原因
