### ISSUE TITLE
linux 平台 firefox CPU 占用100%

### ISSUE THREAD

**Issue by rachpt** [crimx/ext-saladict#361]
- Saladict 版本

**6.29.0**

- 平台：操作系统版本，浏览器名字及版本（测试版或开发者版的浏览器不在 Saladict 支持范围）

**Manjaro KDE  firefox 66.0.5 (64 位)**

- 类型：错误？建议？

**启用本插件后 cpu 持续 100%，禁用后 cpu 使用率明显回落。**

- 划词模式？以及其它觉得相关的设置。

- 重现：提供详细的可重现问题的操作。

**Manjaro Linux  firefox 正常启动。**

- 期待：理想情况下扩展应该怎么做？

**cpu 占用不应该这么高......**

- 实际：客观描述扩展实际上做了什么。

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

截图：

[![ERs72F.png](https://s2.ax1x.com/2019/05/10/ERs72F.png)](https://imgchr.com/i/ERs72F)
[![ERsT8U.png](https://s2.ax1x.com/2019/05/10/ERsT8U.png)](https://imgchr.com/i/ERsT8U)

**htop 过滤了 其他进程。**

**Comment by crimx** [comment]
之前也有一位用户反馈过这个问题，我在 manjaro 上一直没能重现。你是初次安装就这样吗？发生之前有没有对 Saladict 做了什么配置？

**Comment by rachpt** [comment]
> 之前也有一位用户反馈过这个问题，我在 manjaro 上一直没能重现。你是初次安装就这样吗？发生之前有没有对 Saladict 做了什么配置？

我从去s3.translate 插件下架开始(大概去年12月左右) 使用 Saladict (非常感谢能有如此强大的替代插件)，重截图也可以看到我使用的机器不算很差 i7 7700 (8线程) 16G ram 几乎不关机。加上我是 firefox 的忠实用户，所以我一直没有关注过 firefox 后台 cpu 占用情况。**所以以前有没有我没注意过。**
**至于配置**：我上次设置Saladict应该是界面改版前，~~竟然改变界面了~~ :scream:，大致是默认配置，我试了 关掉动画过度 等选项，貌似并没什么变化(进程cpu占用)。
最近 一两个月 因为较多时间需要较长时间运行 大强度计算任务， firefox 开始了频繁的奔溃，中途尝试过删掉就得配置文件，但是这是插件 根本离不开，装完后 也就差不多，该崩溃继续崩溃。

上面截图中可以看到 我装了  chromium 作为备用浏览器，cpu占用比正常情况的fx还第一点 :joy: ~~我都想要叛逃了~~。因为之前也比较懒，一直没管。 :smiley:


下面是我的 **笔记本**，系统环境几乎一样 manjaro linux，我很少使用，也是刚刚才注意到同样有该问题。  后面有时间我测试一下 chromium 的情况以及虚拟机里面试试。
[![EWkvwT.png](https://s2.ax1x.com/2019/05/10/EWkvwT.png)](https://imgchr.com/i/EWkvwT)
[![EWkjmV.png](https://s2.ax1x.com/2019/05/10/EWkjmV.png)](https://imgchr.com/i/EWkjmV)

**Comment by crimx** [comment]
Saladict 在 Chrome 和 Firefox 是共用一套代码的。你在另一台机器中是登录了同个帐号安装的是吗？这样很可能会同步了 Saladict 的设置，我怀疑是某个设置导致了 Firefox 在页面消息传递那里出现了死循环。 你试试重置 Saladict 的设置看还有没有高 CPU 占用。Saladict 在没有查词的时候 CPU 占用应该是极低的。

**Comment by rachpt** [comment]
> Saladict 在 Chrome 和 Firefox 是共用一套代码的。你在另一台机器中是登录了同个帐号安装的是吗？这样很可能会同步了 Saladict 的设置，我怀疑是某个设置导致了 Firefox 在页面消息传递那里出现了死循环。 你试试重置 Saladict 的设置看还有没有高 CPU 占用。Saladict 在没有查词的时候 CPU 占用应该是极低的。

是同一账号，刚刚 我重置 Saladict的设置，cpu 占用并没有明显改变，重启firefox浏览器后依旧如此。
[![EWePUK.png](https://s2.ax1x.com/2019/05/10/EWePUK.png)](https://imgchr.com/i/EWePUK)

**Comment by crimx** [comment]
这实在是令人费解。因为我这边一直无法复现，如果你有空的话麻烦最后再测试一下

1. 在一个干净的虚拟机中 Firefox 不登录帐号安装 Saladict 。扩展文件地址：<https://addons.mozilla.org/firefox/downloads/file/2201909/_-6.29.0-fx.xpi> 
2. 如果上面没出现高 CPU 的话，卸载 Saladict，登录你的帐号在火狐商店安装，看看有没有问题。<https://addons.mozilla.org/zh-CN/firefox/addon/ext-saladict>

**Comment by rachpt** [comment]
> 这实在是令人费解。因为我这边一直无法复现，如果你有空的话麻烦最后再测试一下
> 
>     1. 在一个干净的虚拟机中 Firefox 不登录帐号安装 Saladict 。扩展文件地址：https://addons.mozilla.org/firefox/downloads/file/2201909/_-6.29.0-fx.xpi
> 
>     2. 如果上面没出现高 CPU 的话，卸载 Saladict，登录你的帐号在火狐商店安装，看看有没有问题。https://addons.mozilla.org/zh-CN/firefox/addon/ext-saladict

在虚拟机中，真是这样，在登录账号前 正常，登录 同步 后 又出现了占用。

看来真是同步所致，那么如何彻底清理以前的配置信息呢。 插件的 `重置设定` 无效。

[![EfwCKs.png](https://s2.ax1x.com/2019/05/11/EfwCKs.png)](https://imgchr.com/i/EfwCKs)
[![Efwpvj.png](https://s2.ax1x.com/2019/05/11/Efwpvj.png)](https://imgchr.com/i/Efwpvj)

**Comment by crimx** [comment]
你可以在 saladict 设置中把配置导出给我吗？今晚会有一个更新，我一并修复了。

**Comment by rachpt** [comment]
> 你可以在 saladict 设置中把配置导出给我吗？今晚会有一个更新，我一并修复了。

[config-1557581073488.saladict.zip](https://github.com/crimx/ext-saladict/files/3169072/config-1557581073488.saladict.zip)

**Comment by crimx** [comment]
谢谢找出了 bug！没想到会设这么大的值，之前直接用的 `setTimeout` 每次启动倒计时，可能太大了浏览器会出问题。现在换了更准确的基于时间截的 `alarms` 扩展 API，即便在周期间关闭了浏览器，下次打开依然能接着算。

**Comment by wilkice** [comment]
终于解决了啊！我从 Ubuntu 到 Manjaro, 只要打开插件火狐占用就满了，为了接着用拓展，不得不跑到了 Chrome :cry:  刚刚删除了坚果云同步马上就好了。。。哈哈，太感谢两位大佬了 @rachpt @crimx
