### ISSUE TITLE
独立窗口与浏览器缝隙过大

### ISSUE THREAD

**Issue by chile-zhong** [crimx/ext-saladict#362]
![image](https://user-images.githubusercontent.com/8914104/57516694-c4045000-7347-11e9-8ed2-9e88d3b4b1ef.png)
如图,独立窗口与浏览器缝隙过大,能不能减小点

**Comment by crimx** [comment]
这个恐怕是你的系统问题，可以看到深色部分甚至到达了窗口的任务栏，说明这不属于网页的一部分。

你没有按模板提供完整信息，所以无法给出进一步的建议。
