### ISSUE TITLE
特定操作导致生词本无法再次打开

### ISSUE THREAD

**Issue by mengxuehu** [crimx/ext-saladict#363]
- Saladict 版本
6.29.0

- 平台：操作系统版本，浏览器名字及版本（测试版或开发者版的浏览器不在 Saladict 支持范围）
1. x86_64 Linux 4.19.36-1, Chromium Version 74.0.3729.131 (Official Build) (64-bit)
2. Windows 10 1803, Google Chrome 版本 74.0.3729.131（正式版本） （64 位）

- 类型：错误？建议？
错误

- 划词模式？以及其它觉得相关的设置。
生词本

- 重现：提供详细的可重现问题的操作。
1. 点击Chrome工具栏的saladict图标
2. 点击心形添加生词
3. 生词添加界面：单词文本框填入"a"，翻译文本框填入"a"，其他文本框不填（不包含引号，此处a可为任意文本）
4. 保存
5. [生词本无法再次打开，生词添加页面可以打开]

- 期待：理想情况下扩展应该怎么做？
即使不允许这种行为，生词本也应该可以正常打开

- 实际：客观描述扩展实际上做了什么。
生词本无法打开

- （可选）额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
这个操作导致保存了错误的数据，页面崩溃了，我看看如何修复。

**Comment by crimx** [comment]
找到问题了，下个版本在明晚发布，届时会修复这个 bug

**Comment by mengxuehu** [comment]
非常感谢
