### ISSUE TITLE
建议增加内嵌模式

### ISSUE THREAD

**Issue by Reveanime** [crimx/ext-saladict#364]
- Saladict 版本

6.30.0

- 平台：操作系统版本，浏览器名字及版本（测试版或开发者版的浏览器不在 Saladict 支持范围）

windows 10 1809，chrome 版本 74.0.3729.157（正式版本） （64 位）

- 类型：错误？建议？
建议

建议右键菜单增加类似于 [ImTranslator](https://chrome.google.com/webstore/detail/imtranslator-translator-d/noaijdpnepcgjemiklgfkcfbkokogabh) 的 Inline Translator 模式，这样方便对翻译结果留存，在阅读较长的文章时不至于看了后面忘了前面。这种模式相比较整个网页翻译而言，对网页排版影响小，可以按需要进行翻译，而且有原文对比，方便对比阅读。
![image](https://user-images.githubusercontent.com/20869550/57752754-c1757200-771c-11e9-8b42-af6936d653ef.png)
![image](https://user-images.githubusercontent.com/20869550/57752821-f2ee3d80-771c-11e9-9f0f-e77ff8c1cdcd.png)

--

**Comment by crimx** [comment]
可以两个扩展搭配使用。ImTranslator 专注翻译，而 Saladict 更专注词典查词。
