### ISSUE TITLE
关于生词本

### ISSUE THREAD

**Issue by leonxjf** [crimx/ext-saladict#365]
请问一下生词本是存储在哪儿？本地？云端？
还有能不能选择整段翻译的翻译引擎？会不会泄露个人隐私呢？
还有生词本的数据能不能导出？通过百度云导出到其他设备？

**Comment by crimx** [comment]
> 请问一下生词本是存储在哪儿？本地？云端？

生词本只保存在本地，这个之前有说明，换了设置页面后忘了补上去。

> 还有能不能选择整段翻译的翻译引擎？会不会泄露个人隐私呢？

见设置「单词管理」。“泄漏”得看你怎么定义了，要使用翻译服务不可避免会给该服务上传句子，至于该服务如何处理已不在本扩展的范围。

> 还有生词本的数据能不能导出？通过百度云导出到其他设备？

生词本右上角有个「导出」按钮。支持 WebDAV 同步，见设置「单词管理」。

设置请阅读使用说明<https://github.com/crimx/ext-saladict/wiki>。
