### ISSUE TITLE
【懒人鼠标党的福利】能否给独立窗口增加鼠标自定义呼出?

### ISSUE THREAD

**Issue by 990721830** [crimx/ext-saladict#366]
1丶
比如鼠标选中文字后....
直接按中键...
右键按住+中间...
右键按住+左键...
仔细想想之后不止是独立窗口可以更快捷....
最好给所有选择按键的地方都可以添加自定义鼠标...

2丶
还有截图ocr有计划添加了吗

**Comment by crimx** [comment]
你好，

1. 要在浏览器实现这样的交互应该得拦截所有右键菜单（如有合适实现方式欢迎提出），这可能会产生未知问题。
2. 截图 ocr 不在 Saladict 计划上。

**Comment by 990721830** [comment]
浏览器默认不就是长按右键不显示的吗?
我这边cent手势【长按右键+其他 】也是可以用的...

**Comment by 990721830** [comment]
![【Snipaste】【2019-05-25】No 041106](https://user-images.githubusercontent.com/25548230/58354163-2fe7cc00-7ea3-11e9-8e6d-c18da0b980cd.jpg)

**Comment by crimx** [comment]
Chrome 和 Firefox 均没有哦，这个应该是浏览器层面的实现？

**Comment by crimx** [comment]
或者可以给 cent 团队提建议把手势结合到扩展快捷键中，设置快捷键是可以选择手势。

**Comment by 990721830** [comment]
![【Snipaste】【2019-05-25】No 091555](https://user-images.githubusercontent.com/25548230/58362768-c4ffba80-7ecd-11e9-8e21-56e2b32bf107.jpg)
WGestures好像可以用cmd命令...
我应该怎么写啊?

**Comment by crimx** [comment]
先去设置扩展快捷键，给 saladict 设置快捷键，要选全局，然后回来这里选择触发快捷键就可以啦。

**Comment by 990721830** [comment]
可以了惹...
![【2019 05 25】【09∶37∶10】](https://user-images.githubusercontent.com/25548230/58363006-b36be200-7ed0-11e9-89ac-69b1c128923f.gif)

**Comment by crimx** [comment]
很好，不知道你的是什么系统，如果是 Windows 可以参考使用说明，有人提供了浏览器外获取选词翻译的方式。

**Comment by 990721830** [comment]
win10惹...

**Comment by 990721830** [comment]
我真的很想要ocr啊...
真的不能添加吗?
主要聚合翻译实在太好了...
其他ocr的翻译不是聚合的...
你看我配合边角触碰直接截图ocr...
如果翻译能直接换成你的就好了...
![【2019 05 25】【09∶48∶09】](https://user-images.githubusercontent.com/25548230/58363149-79034480-7ed2-11e9-8234-9ec89f583eab.gif)

**Comment by crimx** [comment]
WGestures 应该也可以实现，结合多个操作，先复制再弹出 Saladict ，同时设置 Saladict 快捷查词自动翻译粘贴板内容。

**Comment by crimx** [comment]
OCR 对于 Saladict 来说太花哨啦。

**Comment by crimx** [comment]
你如果能在 WGestures 实现浏览器外选词翻译的话，欢迎分享设置方式，我添加到使用说明上去。

**Comment by 990721830** [comment]
不过似乎一不错了可以熊猫ocr后..
从剪切板呼出...
但是只能关闭后才打开触发...

**Comment by 990721830** [comment]
> 你如果能在 WGestures 实现浏览器外选词翻译的话，欢迎分享设置方式，我添加到使用说明上去。

![【Snipaste】【2019-05-25】No 095809](https://user-images.githubusercontent.com/25548230/58363233-ae5c6200-7ed3-11e9-95e5-269a58811af2.jpg)

**Comment by crimx** [comment]
还要设置复制的操作然后用修饰键结合吧？我没有 Windows 暂时不能测试。

**Comment by crimx** [comment]
你可以设置手势关闭窗口，查完词就关掉。

**Comment by 990721830** [comment]
什么是修饰按键...
我具体操作录个图吧...

**Comment by crimx** [comment]
我看官网的说明，“修饰键：让一个手势变为多个”

**Comment by crimx** [comment]
录制可以啊！你可以把动态桌面遮一下，每帧颜色变化少了会减小大小。

**Comment by 990721830** [comment]
> 录制可以啊！你可以把动态桌面遮一下，每帧颜色变化少了会减小大小。

1丶首先给翻译软件【打开独立词典窗口】设置【全局】和一个自定义快捷键【ait+0】 

2丶添加一个【自定义手势】我用的【按住鼠标右键+单机鼠标中键】

3丶执行操作选择【执行快捷键】录入快捷键

     把之前1丶的【ait+0】录入
    
    其他【划词开关】快捷键操作步骤都一样....
![【2019 05 25】【10∶18∶42】](https://user-images.githubusercontent.com/25548230/58363445-c8e40a80-7ed6-11e9-8c30-83824e64a8f2.gif)

**Comment by crimx** [comment]
好的，谢谢，已添加到使用说明上。
