### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by leonxjf** [crimx/ext-saladict#368]
我开始喜欢上使用这个插件，同时希望作者可以考虑一下是不是能加入一下功能？
1、单词多次发音功能，跟读
好像百度查询单词，旁边都有一个播放按钮，按下以后，就会多次朗读所查询的单词，中间会有一段时间间隔给用户跟读一遍，大概重复10次，如果有这个功能的话，就可以减少按鼠标的次数了。每次跟读都要自己按鼠标其实有点麻烦。

2、单词本提供背单词的小功能
就好像一些背单词的app，都会有背单词的功能，如“江户网校”之类的，比方说apple，就会随机掏空中间的字母，从ap_le到a_ _ _e，下面有中文解析，由浅入深，或者是例句中间掏空，如I have an a_ _ _e之类的，如果有这个功能就好了，每次要打开单词本回忆单词、抄写单词其实也是挺麻烦的事情，不知道哪个单词记熟悉了那个不熟悉，如果有类似背单词的功能，将单词本所有单词随机打散，记忆+测验，新单词记忆+旧单词复习，混合着来，其实对英语学习应该蛮有帮助的。

Anyway，谢谢阁下提供了这么好的学习英语的工具。

**Comment by crimx** [comment]
谢谢你的建议

1. 这个前几天账正好与另一位日语老师用户聊了这个话题，相关的功能正在开发中，我会优先抽时间实现这个功能。
2. 背单词功能之复杂足以超过本扩展，而市面上已有较好的实现，就没有必要重复劳动了。本扩展提供了灵活的方式导出与同步。见使用说明和结合 anki 使用的例子。
