### ISSUE TITLE
特定网站划词无效(如pixiv，pornhub等

### ISSUE THREAD

**Issue by yukiflandre** [crimx/ext-saladict#373]
如下所示：
![123](https://user-images.githubusercontent.com/6152854/58655897-d1609900-834d-11e9-87c1-633731b9c447.gif)

**Comment by crimx** [comment]
咳咳，不知道为何 iframe 的 srcdoc 没有加载。你可以用独立窗口的查词面板，再设置划词模式响应页面划词。

**Comment by crimx** [comment]
发现 iframe 是正常加载了，但是没有渲染出来？检查外部 CSS 计算结果也都正常，但 iframe 内部的 viewport 高度不正确。没找到原因。

**Comment by crimx** [comment]
看到服务器都设置了 `x-frame-options: SAMEORIGIN` ，将通过 `sandbox='allow-same-origin'` 解决。

**Comment by kirkvicent** [comment]
我怀疑你在开车，但我没有证据

**Comment by crimx** [comment]
搞不好人家是司机
