### ISSUE TITLE
最新版在 Chromium 版 edge 上 崩溃

### ISSUE THREAD

**Issue by ZCShou** [crimx/ext-saladict#374]
### Saladict 版本

6.32.0

### 平台

Win 10  Microsoft Edge Chromium 版

### 类型

选词后，出现弹图标，鼠标移动到图标上，则 插件崩溃

### 重现方式

选词后，出现弹图标，鼠标移动到图标上，则 插件崩溃

**Comment by crimx** [comment]
你好，请提供发生崩溃的网站。

**Comment by ZCShou** [comment]
随便一个英文网站，选中一个英文句子，会出现 saladict 图标， 鼠标移动到 图标上就 崩溃了！

ps: 我的设置里选择了 鼠标 放到 图标上 才 弹出 词典窗口

**Comment by ZCShou** [comment]
![MarcoResult](https://user-images.githubusercontent.com/8591065/58930391-b5b22400-878d-11e9-9cc3-ea14367f466b.gif)


![2019-06-05_123054](https://user-images.githubusercontent.com/8591065/58930411-cebad500-878d-11e9-9986-6ade434ac88f.png)

**Comment by crimx** [comment]
这样的话应该是 Edge 的问题了，它对 WebExtensions 的实现不是很全。Edge 目前不在 Saladict 的维护计划中，所以这个问题应该不会得到解决。

**Comment by ZCShou** [comment]
在之前的版本时没有问题，只最新版出现该问题！貌似还和鼠标滑过速度有关系。。
那我先看看怎么使用旧版本吧！

**Comment by crimx** [comment]
你可以在 ChromeFor 下载历史版本

**Comment by crimx** [comment]
新版本才有这是个很重要的信息。这可能是与音频波形控制有关，我在下个版本提供选项关闭。

**Comment by crimx** [comment]
我再收集一些信息

- 你有开启自动发音吗？
- 如果有，尝试关闭了看会不会崩溃。如果没有崩溃则点一下发音再看看。
- 在 Saladict 设置页面也会崩溃吗？
- 崩溃时上面截图中的 Details 里的信息可以复制过来。

**Comment by ZCShou** [comment]
1. 没有开启自动发音，设置里面，我就选择了一个就是右键菜单，就是监视剪切板 后自动查词，其他全部默认
2. 设置页面没有崩溃
3. 我大体测试了一下，貌似和 Edge 更新了有关系，我没有旧的 Saladict  ，只看到了新的出现崩溃！原来 Edge 和 Saladict  都是旧版本没问题！现在不止 Saladict   更新了， Edge 也更新了！
4. 我再测试一下再反馈，以免耽误你时间！

**Comment by crimx** [comment]
不好意思我之前的一个问题可能有些歧义，这个查词面板在设置页面和点击地址栏旁图标弹出来的页面中都能正常显示是吧，如果是这样我大概知道怎么修复了。

**Comment by crimx** [comment]
还有崩溃时上面截图中的 Details 里的信息可以复制过来吗

**Comment by strange-life** [comment]
最新版 chrome dev 上也有一样的问题，查询若干次之后就会损坏
![image](https://user-images.githubusercontent.com/19758341/59318896-4e4f2380-8cfb-11e9-90cf-ce56d747b22d.png)
![image](https://user-images.githubusercontent.com/19758341/59318949-80f91c00-8cfb-11e9-85f6-6557b6aebd89.png)

**Comment by crimx** [comment]
@strange-life 测试版不在 Saladict 维护范围中。

出现这个问题的原因应该是扩展的文件被更改了，看看是不是用了[清理工具](https://techdows.com/2017/08/repair-chrome-extensions.html)什么的。如果是 Windows 平台也可以考虑是不是[恶意病毒](https://www.reddit.com/r/chrome/comments/8wafn5/this_extension_may_have_been_corrupted/)的问题。

**Comment by strange-life** [comment]
> @strange-life 测试版不在 Saladict 维护范围中。
> 
> 出现这个问题的原因应该是扩展的文件被更改了，看看是不是用了[清理工具](https://techdows.com/2017/08/repair-chrome-extensions.html)什么的。如果是 Windows 平台也可以考虑是不是[恶意病毒](https://www.reddit.com/r/chrome/comments/8wafn5/this_extension_may_have_been_corrupted/)的问题。

👌

**Comment by crimx** [comment]
@ZCShou 新版 6.33 中可以关闭音频波形控制，看看有没有解决这个问题。

**Comment by ZCShou** [comment]
> @ZCShou 新版 6.33 中可以关闭音频波形控制，看看有没有解决这个问题。

关闭音频波形控制，貌似真的可以了！用了一段时间暂时还没有出现崩溃。我再继续试试
