### ISSUE TITLE
字典顯示不完全

### ISSUE THREAD

**Issue by aisen0921** [crimx/ext-saladict#375]
火狐版本67.0
Saladict 版本 6.32.0

問題截圖

![img1](https://i.imgur.com/RyMf5dhl.png)

在某些情況下卷軸拉到底仍無法顯示最後一行
可是有時候行數更多的翻譯卻能顯示，如下圖

![img2](https://i.imgur.com/eEbRjTL.png)

已經嘗試過修改字典預設高度沒有作用
請問要修改哪一個設定?

另請問要如何設定才能讓翻譯的結果自動展開，不需要拉動卷軸即可顯示完整翻譯結果?
謝謝

**Comment by crimx** [comment]
感谢反馈，这个可能是由于新版本加入了下面的这个语音控制的高度没有算进去，下个版本会进行修正。

要完全自动展开，你把默认高度设一个大的值就可以，如`999999`。

**Comment by crimx** [comment]
另外滚动到底不能显示全的情况，我没能重现这样的情况，能提供你设备的信息吗？

**Comment by crimx** [comment]
Firefox 试试关闭硬件加速，很多问题是源于这个

To disable hardware acceleration in Firefox.

Tools > Options > Advanced > General > Browsing: "Use hardware acceleration when available"  
https://hacks.mozilla.org/2010/09/hardware-acceleration/

**Comment by aisen0921** [comment]
> 
> 
> 感谢反馈，这个可能是由于新版本加入了下面的这个语音控制的高度没有算进去，下个版本会进行修正。
> 
> 要完全自动展开，你把默认高度设一个大的值就可以，如`999999`。

請問默認高度要從哪設置?
我從字典設定裡面設定了999999沒有效果

就我所知關閉硬體加速會有某些網頁的顯示問題(https://forum.moztw.org/viewtopic.php?p=163533)
不知道你的硬體加速是關閉的嗎?

**Comment by crimx** [comment]
你分享的这个是很多年前的讨论了，Firefox 现在换了新的量子引擎，所以这些讨论没有太大意义。

一般来说，硬件加速关闭是比开启要稳定，这是因为显卡繁杂不一，主流的显卡一般会得到较好的支持。

默认高度就在每个词典的设置中，只要词典结果小于这个高度就不会显示进一步展开箭头。

**Comment by aisen0921** [comment]
> 
> 默认高度就在每个词典的设置中，只要词典结果小于这个高度就不会显示进一步展开箭头。

設置了但沒作用

**Comment by crimx** [comment]
这样我也不清楚了，没有设备信息我也是大概这么猜测。我在几台设备上都无法重现显示不全的问题。

**Comment by crimx** [comment]
![Screenshot_2019-06-04_19-29-21](https://user-images.githubusercontent.com/6882794/58875828-15152300-86ff-11e9-9362-2a1f33c2c366.png)

如图，是可以滚动到最低，剩下的一点点多余滚动在下个版本会修正。

**Comment by aisen0921** [comment]
設備訊息從哪裡看可以提供給你?

**Comment by crimx** [comment]
![sssss](https://user-images.githubusercontent.com/6882794/58876047-940a5b80-86ff-11e9-82ed-fb85767f78e0.png)

这是长的结果显示，词典默认高度我设置了 `9000` ，可以看到没有显示下箭头。

**Comment by crimx** [comment]
> 設備訊息從哪裡看可以提供給你?

主要是你的作业系统。其它的 CPU 和显卡也无妨。

**Comment by aisen0921** [comment]
我的意思是連卷軸都不要有，因為行數不多不太需要拉卷軸，拉卷軸就有點多此一舉
我的翻譯結果只有少少幾行也是要拉卷軸才能全部顯示
作業系統是win10

**Comment by crimx** [comment]
那你是指设置字典介面的最大高度吧，在「字典介面」那里设置

**Comment by aisen0921** [comment]
我的意思是連卷軸都不要有，因為行數不多不太需要拉卷軸，拉卷軸就有點多此一舉
我的翻譯結果只有少少幾行也是要拉卷軸才能全部顯示
作業系統是win10

> 
> 
> 那你是指设置字典介面的最大高度吧，在「字典介面」那里设置

那裏只能設定寬度，沒有高度

**Comment by crimx** [comment]
「字典介面最高占螢幕高度比例」
