### ISSUE TITLE
查词滚动的时候扩展界面白屏

### ISSUE THREAD

**Issue by CrackingTofu** [crimx/ext-saladict#376]
### Saladict 版本

6.32.0

### 平台

Firefox

### 类型

查词的时候正常
<img width="452" alt="WeChatd05cd6ba9b905e53294bc528b6747408" src="https://user-images.githubusercontent.com/34636158/59038297-63642680-88a5-11e9-8907-39422760dd90.png">
但是一旦滑动
就变成这样了
<img width="452" alt="WeChat44c574b359a1505f450beb2fd99ea3ec" src="https://user-images.githubusercontent.com/34636158/59038350-80005e80-88a5-11e9-85d7-958b233f1aab.png">

**Comment by crimx** [comment]
你是 MacOS 吧，关闭 Firefox 的硬件加速。

**Comment by CrackingTofu** [comment]
> 你是 MacOS 吧，关闭 Firefox 的硬件加速。

弱弱的问一句，mac的硬件加速在哪里关闭，我在首选项里面好像找不到，度娘上似乎也没看到，我就是个弱鸡QAQ

**Comment by crimx** [comment]
是在 Firefox 中关闭，Tools > Options > Advanced > General > Browsing: "Use hardware acceleration when available"

你可以把 Mac 和 OS 的版本给我发一下吗，我给火狐反馈问题。

**Comment by CrackingTofu** [comment]
> 是在 Firefox 中关闭，Tools > Options > Advanced > General > Browsing: "Use hardware acceleration when available"
> 
> 你可以把 Mac 设备和 OS 的版本给我发一下吗，我给火狐反馈问题。

mojave  10.14.5 你这个应该是Windows的吧
<img width="982" alt="图片" src="https://user-images.githubusercontent.com/34636158/59040766-f8691e80-88a9-11e9-8a85-87eca56519a9.png">
在首选项里找不到硬件加速，也搜不到高级的选项

**Comment by crimx** [comment]
嗯嗯，`首选项` 位于 `常规` 面板的 `性能` 部分，请在此取消选中 `使用推荐的性能设置` 可以看到 `自动启用硬件加速`。

**Comment by CrackingTofu** [comment]
> 嗯嗯，`首选项` 位于 `常规` 面板的 `性能` 部分，请在此取消选中 `使用推荐的性能设置` 可以看到 `自动启用硬件加速`。

真的太感谢了~~~~(>_<)~~~~

**Comment by crimx** [comment]
不客气！

**Comment by crimx** [comment]
火狐已确认问题，等待火狐团队修复更新即可。
