### ISSUE TITLE
沪江小d 无法显示出「日语」单词释义

### ISSUE THREAD

**Issue by ericahsu1115** [crimx/ext-saladict#377]
### Saladict 版本

6.32.0

### 平台

Google Chrome
版本 74.0.3729.169 (正式版本) (64 位元)

### 类型

沪江小d 无法显示出「日语」单词释义
![image](https://user-images.githubusercontent.com/51479503/59099724-90bcdd00-8956-11e9-8583-d2546aa3755d.png)

### 重现方式

搜寻任意日语单词，例如：「トレーニング」、「ストレッチ」、「勉強」、「帰る」

### 期待

更新沪江小d的日语查词连结 
https://dict.hjenglish.com/jp/jc/

**Comment by crimx** [comment]
我测试是没有问题的，请点击字典的标题跳转到原网页看能不能打开。

**Comment by crimx** [comment]
你所在的地方是不能访问 <https://www.hjdict.com> 么

**Comment by ericahsu1115** [comment]
是TouchVPN的問題！我把TouchVPN關掉就可以查詢了XD 沙拉查詞最棒了！謝謝：）

**Comment by crimx** [comment]
嗯嗯，你可以为 VPN 设置白名单
