### ISSUE TITLE
点击心型图标收藏时反应慢

### ISSUE THREAD

**Issue by zhuxiaoxi** [crimx/ext-saladict#379]
### Saladict 版本

6.32.0

### 平台

macOS 10.14.4
Chrome 74

### 类型

疑似错误

### 重现方式

划词后在弹窗里点击收藏，心型图标在1s后点亮，这个有点慢吧

### 期待

快一点

**Comment by crimx** [comment]
在设置「单词管理」中根据你的网络条件自行去掉勾选几个自动翻译上下文的词典。
