### ISSUE TITLE
独立窗口时能增加监控剪贴板吗?

### ISSUE THREAD

**Issue by chile-zhong** [crimx/ext-saladict#380]
如题

**Comment by crimx** [comment]
你可以使用第三方工具
请阅读使用说明<https://github.com/crimx/ext-saladict/wiki>。

**Comment by crimx** [comment]
响应浏览器内的划词在 Saladict 设置「快捷查词」设置。

**Comment by chile-zhong** [comment]
> 响应浏览器内的划词在 Saladict 设置「快捷查词」设置。

这个好像不是独立窗口的吧, 我的意思是独立窗口开始时, 我在其他地方, 比如文档, 复制东西, 能自动翻译

**Comment by crimx** [comment]
请阅读使用说明<https://github.com/crimx/ext-saladict/wiki>。
