### ISSUE TITLE
求大佬增加一个双击ctrl启动查词面板的选项。

### ISSUE THREAD

**Issue by wuhao747003943** [crimx/ext-saladict#382]
沙拉查询太好用了，功能强大，非常喜欢！但我有点不明白，为什么要连续按三ctrl才能启动查词面板？换成2次不更好吗？

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by wuhao747003943** [comment]
如果非要三次的话，那么请大佬增加一个双击的选项做备用，万分感谢！！！

**Comment by crimx** [comment]
你好，这个不考虑添加，你可以自行设置浏览器扩展快捷键。

**Comment by crimx** [comment]
两次 ctrl 在复制粘贴的时候很容易误触。
