### ISSUE TITLE
我希望，快捷查词的时候，在没有开启自动查词的情况下，能够显示输入联想。

### ISSUE THREAD

**Issue by peizhi** [crimx/ext-saladict#383]
### 期待

我希望，
1、快捷查词的时候，在没有开启自动查词的情况下，能够显示输入联想。
2、设置个选项，当翻译的句子或段落超过多少单词时，不启用自动朗读。
### 额外信息

非常感谢你们的工作。良心作品！

**Comment by crimx** [comment]
1. 这个可以考虑。
2. 这个就不再加设置了，太琐碎。你结合情景模式切换使用吧。

**Comment by peizhi** [comment]
谢谢！
