### ISSUE TITLE
Chrome 浏览器插件崩溃

### ISSUE THREAD

**Issue by Forforfor-3** [crimx/ext-saladict#384]
### Saladict 版本
6.33.0

### 平台
Mac 
Chrome Version 76.0.3809.21 (Official Build) dev (64-bit)

### 类型
插件在未操作浏览器的情况下自动崩溃，需重新下载 & 重新配置设置

**Comment by crimx** [comment]
开发版浏览器不在 Saladict 支持范围内。

**Comment by Forforfor-3** [comment]
> 开发版浏览器不在 Saladict 支持范围内。

好的 谢谢

**Comment by liuliangsir** [comment]
@crimx 正式版也出现崩溃的情况

![screenshot-2019-06-23-pm-5 25 26](https://user-images.githubusercontent.com/8049878/59974210-0cb45780-95dc-11e9-94c1-ede4d502c879.png)

**Comment by crimx** [comment]
@liuliangsir 你的是 beta 版本…… 目前稳定版是 75 。你可以试试在设置「词典设置」中关闭「波形控制]。

**Comment by liuliangsir** [comment]
@crimx 不好意思，我竟然把 beta 看成正式版[/捂脸]。好的，我试试，谢谢啦
