### ISSUE TITLE
搜索结果布局意见

### ISSUE THREAD

**Issue by yezheyu** [crimx/ext-saladict#385]
希望划词搜索出来的多个词典结果能是横向布局而不是纵向布局。

一是不美观，二是不同词典显示太多类似的翻译结果会显得很臃肿，拖长翻译显示的结果。

建议可以使用这样的横向布局，点击词典图标切换搜索结果即可
![5](https://user-images.githubusercontent.com/18241256/59545439-bd718580-8f50-11e9-959c-ddbd16f34195.png)

**Comment by crimx** [comment]
这种方式也有缺点，即不能一眼看到几个结果，而这个正是 Saladict 要解决的主要问题。如果你喜欢这样的布局可以看看 FairyDict 扩展。
