### ISSUE TITLE
希望右键菜单支持添加javascript:地址

### ISSUE THREAD

**Issue by zhouhuajdsh** [crimx/ext-saladict#386]
本来是建议添加彩云网页翻译的右键菜单的，但看以前好像有人提过了没用。。
不想再安装扩展，彩云给出了小书签代码非常好用，是javascript开头地址。想自己添加到右键菜单，可惜填到了URL栏不支持

**Comment by crimx** [comment]
沙拉查词已内置彩云小译

**Comment by zhouhuajdsh** [comment]
那个只是词典啊，我想要网页翻译，怎么弄出右键菜单

**Comment by crimx** [comment]
你可以试试收藏到浏览器书签使用，具体可不可行我也不太清楚，可以自行搜索教程。因安全隐患 Saladict 没有计划支持添加 javascript 链接。

**Comment by zhouhuajdsh** [comment]
好吧，凉凉，感谢回复。
