### ISSUE TITLE
能不能设置窗口坐标？

### ISSUE THREAD

**Issue by lhj5426** [crimx/ext-saladict#387]
![BaiduShurufa_2019-6-19_20-42-17](https://user-images.githubusercontent.com/30548000/59766621-2ea79480-92d3-11e9-8b3c-297781c612a5.png)
 用另外 一个 划词 扩展  
  那个扩展的作者早就不更新了但是能用
如图 在点击沙拉划词图标之后 沙拉 翻译的页面 和这个扩展会重叠在一起
那么能不能 弄个自定义的 窗口位置 。。 每次弹出的位置固定这就避免了。。。
 2个 划词窗口重叠看不到翻译的问题。。  或者记住上次打开的位置 这个在鼠标旁边 这样很闹心

现在临时的曲线解决方案 是 在 G键位上设置一个3连ctrl 虽然可以在固定位置弹出面板 
但是弊端 是 在腿搭在桌子上网需要翻译的时候 需要起身去按键盘。。。。 不能愉快的单手 鼠标浏览网页。。
![BaiduShurufa_2019-6-19_21-4-56](https://user-images.githubusercontent.com/30548000/59768028-2a30ab00-92d6-11e9-95a0-435fbc1b05ed.png)

**Comment by crimx** [comment]
你好，这个功能太私人化了我不是很感兴趣去实现。你可以试试设置快捷查词独立窗口中有个侧边栏布局，看看能不能解决不用键盘的问题？
