### ISSUE TITLE
你好 yarn start 模式可以热更新吗

### ISSUE THREAD

**Issue by lulinglm** [crimx/ext-saladict#388]
### Saladict 版本

6.33.1

### 平台
mac chrome  74.0.3729.169（正式版本） （64 位）

### 实际
你好 yarn start 模式可以热更新吗

**Comment by crimx** [comment]
理论上可以，但我删去了因为不太用得上

**Comment by crimx** [comment]
想起来了，删去是因为我还要测试一些 iframe 黑魔法，热更新不兼容。

**Comment by lulinglm** [comment]
请教一下，那我改了一行代码是不是都要重新 npm run build 一下（我看了代码好像暂时只能这样）

**Comment by lulinglm** [comment]
> 想起来了，删去是因为我还要测试一些 iframe 黑魔法，热更新不兼容。

请教一下，那我改了一行代码是不是都要重新 npm run build 一下（我看了代码好像暂时只能这样）

**Comment by crimx** [comment]
start 不用，start 是开发特定模块的时候使用的，加载了一个假的扩展环境，见 CONTRIBUTION 文档。如果要完整把玩则需要 build。`yarn devbuild --notypecheck` 会快些。

**Comment by crimx** [comment]
我现在在重构这个项目，Saladict7 应该支持热更新。
