### ISSUE TITLE
Firefox 查词时，首次点击发音会同时触发多次发声（声音重叠，有回音效果）

### ISSUE THREAD

**Issue by PYGC** [crimx/ext-saladict#391]
### Saladict 版本

6.33.0

### 平台

Windows 10 1903， Firefox 67.0.4

### 类型

错误

### 重现方式

选中单词，点击发音

### 期待

正常发音

### 实际

首次发音有回音效果，应该是触发了多次，声音重叠

### 额外信息

测试发现 Chrome 无该问题

**Comment by crimx** [comment]
好的，你可以先在「词典设置」中关闭「波形控制」
