### ISSUE TITLE
<功能建议>有道网页翻页新增快捷键响应

### ISSUE THREAD

**Issue by FishOrBear** [crimx/ext-saladict#392]
当前:
可以通过快捷键快速呼出有道的网页翻译,但是如果想切换翻译状态,例如<取消翻译>和<重新翻译>时,需要通过鼠标去点击.

期望:
通过快捷键可以直接触发<取消翻译>和<重新翻译>,来控制翻译状态.

**Comment by crimx** [comment]
支持快捷键，请阅读使用说明<https://github.com/crimx/ext-saladict/wiki>。
