### ISSUE TITLE
请问作者有没有意向开发查词一键导入anki的功能？

### ISSUE THREAD

**Issue by wuhao747003943** [crimx/ext-saladict#394]
anki的用户非常的多，但是制作学习卡片费时费力，如果沙拉查词能增加这项功能，肯定会非常的火爆!

**Comment by crimx** [comment]
支持 ANKI 导入，请阅读使用说明<https://github.com/crimx/ext-saladict/wiki>。

**Comment by summiry** [comment]
我按照https://github.com/crimx/ext-saladict/wiki 这篇说明设置的，一键导入anki，可是总是有字段确实，不知道是什么原因

**Comment by crimx** [comment]
字段确实应该是你导出的字段跟 Anki 中设置的字段数目不一致。要知道原因你要提供文本。

**Comment by yllgl** [comment]
我发现导入Anki时txt中不能使用回车符，否则导入anki时会导致字段缺失。

**Comment by yllgl** [comment]
@crimx 由于生词本自动添加了翻译的内容，翻译中有回车符，导出txt文本时回车符会导致Anki误认为这是不同单词的分隔符，导致导入时会显示字段缺失，作者可以自己试一下，希望能尽快修复这个问题。

**Comment by crimx** [comment]
[已支持](https://saladict.crimx.com/anki.html)。
