### ISSUE TITLE
在某些页面无法划词翻译

### ISSUE THREAD

**Issue by Oldmoooon** [crimx/ext-saladict#397]
### Saladict 版本
6.33.1

### 平台
Mac OS
Google Chrome / Version 75.0.3770.100 (Official Build) (64-bit)

### 类型
错误

### 详情
划词翻译在某些页面（如stackoverflow）失效。重新安装扩展可以解决问题。

> 如果这不是一个bug，请关闭这个issue。

**Comment by crimx** [comment]
你好，无法复现这个问题。这可能是其它原因，如页面没有加载完成等。

**Comment by Oldmoooon** [comment]
页面加载确实已经完成了，插件也确实在运行。
怀疑是有些页面的js脚本阻止了插件脚本的某些逻辑。

**Comment by crimx** [comment]
我在 stackoverflow 上还没有遇到过这个问题。
