### ISSUE TITLE
部分网页无法划词翻译

### ISSUE THREAD

**Issue by HeavenElegy** [crimx/ext-saladict#398]
### Saladict 版本

6.33.1

### 平台

Ubuntu 18.04.2 火狐浏览器 67.0.4 (64 位)

### 类型

悬浮按钮没有显示

### 实际

网址: http://kafka.apache.org/22/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html

**Comment by crimx** [comment]
这类网站用了非常古老的技术，不打算支持。
