### ISSUE TITLE
希望添加快捷操作

### ISSUE THREAD

**Issue by TGich** [crimx/ext-saladict#399]
### Saladict 版本

6.33.1

### 平台

win10，chrome75.0.3770.100 x64

### 类型

建议

### 期待

请添加功能：输入框内输入英文并弹出结果框之后可以支持键盘↑↓键移动到结果上，并且接回车可以直接进入结果

**Comment by crimx** [comment]
目前可以通过 tab 跳转。

**Comment by crimx** [comment]
沙拉查词 7 已支持。
