### ISSUE TITLE
希望添加thefreedictionary这个词典

### ISSUE THREAD

**Issue by yukinahimeragi** [crimx/ext-saladict#401]
如题

**Comment by crimx** [comment]
你好，最好说明一下原因。这个词典有什么优势，有什么需求是当前词典不能满足的？

**Comment by yukinahimeragi** [comment]
这个词典收词量大还能查短语 和dictionary.com类似 也有很多人用

**Comment by crimx** [comment]
如果 Saladict 现有的词典组合已经可以解决问题就没有必要再维护一个词典了。
