### ISSUE TITLE
1

### ISSUE THREAD

**Issue by sambodhi-cn** [crimx/ext-saladict#402]

**Comment by crimx** [comment]
请提供相关网页

**Comment by sambodhi-cn** [comment]
> 请提供相关网页

https://machinelearningmastery.com/how-to-develop-a-face-recognition-system-using-facenet-in-keras-and-an-svm-classifier/

**Comment by crimx** [comment]
没能重现问题，请看看是不是其它扩展的问题。

**Comment by sambodhi-cn** [comment]
> 没能重现问题，请看看是不是其它扩展的问题。

我在另一台电脑，Chrome完全同步，扩展一样，另一台电脑就没有这种现象。有问题的电脑我试过重装这个扩展，还试过重置这个扩展，都不行啊。

**Comment by crimx** [comment]
这个不清楚了，但应该不是这个扩展的问题。
