### ISSUE TITLE
【建议】：期待能从程序优化上减少插件的体积大小

### ISSUE THREAD

**Issue by veeson** [crimx/ext-saladict#405]
感谢作者，插件很实用。
不过对于一个翻译插件而言，3M多的体积是否过大了？建议在程序优化上能减少插件的体积大小，谢谢！
![image](https://user-images.githubusercontent.com/16076436/60755032-beac4480-a01c-11e9-9995-14bcef239df9.png)

**Comment by crimx** [comment]
主要是 PDF 浏览器以及词典的 CSS ，不使用时并不会对性能造成任何影响。有人愿意做精简也是欢迎的。

**Comment by breakTBB** [comment]
我觉得对于现在的计算机来说，3M并没有什么，希望目前更多的精力放在功能和使用体验上，不用在意这些。
