### ISSUE TITLE
求记录上一次的翻译内容

### ISSUE THREAD

**Issue by CHN-STUDENT** [crimx/ext-saladict#408]
### Saladict 版本

V6.33.2

### 平台

Windows 10 version 1809 
Chrome75

### 类型

建议

### 划词模式

手工输入单词

### 重现方式

打开面板，手工输入单词后，打开新页面面板将会关闭，可能仍需重新打开面板，查询上一个单词内容。

### 期待

面板是否在打开新页面后不会自动关闭？能够记录上一次的查询内容？

**Comment by crimx** [comment]
请使用独立窗口。

请阅读使用说明<https://github.com/crimx/ext-saladict/wiki>。
