### ISSUE TITLE
【小bug】沪江小d词典英文、日文、韩文都无法单词发音了。

### ISSUE THREAD

**Issue by wekey7** [crimx/ext-saladict#410]
经过测试 发现三种语言在沪江小D上都不能在线朗读/发音了。
![1](https://user-images.githubusercontent.com/34415026/61196104-f7c07500-a6fe-11e9-904d-660084dd1863.png)
![2](https://user-images.githubusercontent.com/34415026/61196105-f7c07500-a6fe-11e9-8dad-151aca9a735c.png)
![3](https://user-images.githubusercontent.com/34415026/61196106-f7c07500-a6fe-11e9-991c-f8865250472b.png)

**Comment by crimx** [comment]
我测试是没问题的，请点击词典标题打开网页看看是不是自身网络的问题。

**Comment by wekey7** [comment]
> 我测试是没问题的，请点击词典标题打开网页看看是不是自身网络的问题。

谢谢大大回复，但是我这里测试，其他英文词典都能发音，并且点开沪江小D的网页版(原网页)也能发音。
只有在拓展程序中查词点击发音没反应，不知道是否是我个人情况。

**Comment by crimx** [comment]
可以在设置「查词面板」中关闭「波形控制」试试。

**Comment by wekey7** [comment]
> 可以在设置「查词面板」中关闭「波形控制」试试。

啊！问题完美解决了，查任何语言都有朗读和发音了。
请问这是什么原理啊？好神奇。谢谢大大。

**Comment by crimx** [comment]
波形控制使用另外的方式加载音频，有时会有问题。
