### ISSUE TITLE
pdf 翻译划词翻译无法完全查询单词且复制长句没有空格

### ISSUE THREAD

**Issue by CHN-STUDENT** [crimx/ext-saladict#412]
### Saladict 版本

6.33.2

### 平台

Win10 Version 1809 Chrome 75

### 类型

单词无法查询完全：
![image](https://user-images.githubusercontent.com/21209416/61417936-7c8fd680-a92b-11e9-9a6c-447732332340.png)

![image](https://user-images.githubusercontent.com/21209416/61417945-831e4e00-a92b-11e9-881f-c19d7e17cf5f.png)

句子复制错误：
![image](https://user-images.githubusercontent.com/21209416/61417987-a3e6a380-a92b-11e9-99cf-9a2c37974a5a.png)

### 划词模式

PDF 划词打开本地文件

### 重现方式

一份英语课件（中英混杂）划词查询单词+复制出现问题

### 期待

猜测可能还是pdf.js的问题

### 额外信息

在另外一款划词翻译软件上可能会出现的同样的问题。
两个软件都对我提供了很大的帮助。

**Comment by crimx** [comment]
请阅读[常见问题及答复](https://github.com/crimx/ext-saladict/wiki/Q&A#wiki-wrapper)。
