### ISSUE TITLE
在 chrome canary 版本上经常 crash

### ISSUE THREAD

**Issue by xwartz** [crimx/ext-saladict#414]
在 chrome canary 版本中，经常出现 crash，如下图

### Saladict 版本
6.33.2

### 平台

Chrome 版本 77.0.3857.0（正式版本）canary （64 位）

### 类型

![image](https://user-images.githubusercontent.com/4149827/61575172-0cd04600-aafb-11e9-8de6-9632881c675f.png)

### 划词模式

默认选项

### 重现方式

安装 Chrome 版本 77.0.3857.0（正式版本）canary （64 位）

使用一会就 crash

### 期待

无 crash 现象

### 实际

crash

### 额外信息

无

**Comment by crimx** [comment]
请阅读[常见问题及答复](https://github.com/crimx/ext-saladict/wiki/Q&A#wiki-wrapper)。

**Comment by xwartz** [comment]
常见问题里并没有类似情况

**Comment by crimx** [comment]
沙拉查词不会对非稳定版的浏览器进行支持。

你可以尝试在设置「查词面板」中关闭「波形控制」。

**Comment by xwartz** [comment]
默认就是关闭的
