### ISSUE TITLE
翻译显示白框，重启无效

### ISSUE THREAD

**Issue by LinJ07** [crimx/ext-saladict#415]
### Saladict 版本

6.33.2

### 平台

win10 17763.615, 火狐68.0.1

### 类型

划词翻译不显示内容，重启电脑，卸载重装插件均无效

**Comment by crimx** [comment]
你好，请阅读[常见问题及答复](https://github.com/crimx/ext-saladict/wiki/Q&A#wiki-wrapper)。

**Comment by crimx** [comment]
我测试没有问题的。你是在什么地方出现白框呢。是特定网页呢，还是地址栏旁边的图标呢，还是独立窗口呢。

**Comment by LinJ07** [comment]
划词之后出现的窗口。
刚刚重启了一下好了，过一会儿突然又不行了，重启加重装之后过一会儿又好了。。

**Comment by crimx** [comment]
是在特定网页上出现呢，还是所有网页都一样。

**Comment by LinJ07** [comment]
所有网页

**Comment by LinJ07** [comment]
![图片](https://user-images.githubusercontent.com/53166576/61616385-d4676e00-ac9a-11e9-9bfc-ec99ffd5a081.png)
像这样

**Comment by crimx** [comment]
是不是其它插件拦截了

**Comment by LinJ07** [comment]
其余插件应该都是浏览器自带的，以前一直在用的动态主题也出现问题了，怀疑是浏览器的问题。

**Comment by crimx** [comment]
嗯，这个是应该不是本扩展的问题。

**Comment by LinJ07** [comment]
谢啦
