### ISSUE TITLE
上次打开的pdf标签页，再次打开浏览器就变成空白，需要重新打开pdf文件

### ISSUE THREAD

**Issue by moerfutin** [crimx/ext-saladict#417]
### Saladict 版本

6.33.2

### 平台

Windows7 X64, Chrome 75.0.3770.100（正式版本） （64 位）

### 类型

比如，我已经用沙拉打开了一个pdf，关闭了浏览器，下次我再打开浏览器，其他页面都可以继续上次的浏览状态，唯独沙拉的pdf阅读器，是空白的，必须点右上角的打开箭头才能重新打开pdf，不知何故。

### 额外信息

PDF df0f21bf442145a5fa2c661567f51388 [1.4 ilovepdf.com / Adobe Photoshop CS6 (Windows)] (PDF.js: 2.2.9)
viewer.js:1418 PDF 05590000ff7e00003d310000ff2b0000 [1.5 FreePic2Pdf_Lib - v2.19 / -] (PDF.js: 2.2.9)

**Comment by crimx** [comment]
你可以向 PDF.js 反馈。但我猜测是浏览器安全策略相关的原因，本地的文件需要用户主动打开。
