### ISSUE TITLE
【建议】添加完生词后的鼠标，能否聚焦到查词框呢？

### ISSUE THREAD

**Issue by Leezhaofeng** [crimx/ext-saladict#418]
### Saladict 版本

6.33.2

### 平台

win10 \ chrome 75.0.3770.142

### 类型

建议

### 期待

钉住查词面板的情况下，添加完生词后，鼠标能够聚焦到查词框。

### 实际

我的使用场景是，钉住查词面板，同时用电脑kindle看书，手动查词。点击完添加生词的保存按钮后，还要手动点鼠标到查词框。如果能实现鼠标自动聚焦到查词框，可以少点一下鼠标。

**Comment by Co-xuan** [comment]
同需求,需要快速定位到搜索框,重新搜索单词

**Comment by crimx** [comment]
在独立窗口下工具栏开启了「查词时面板获取焦点」划词后会重新回到搜索框。
