### ISSUE TITLE
单词本至少应该添加单子翻译功能

### ISSUE THREAD

**Issue by linxingwu** [crimx/ext-saladict#419]
一个单词本至少应该有单词本身和单词的释义两部分组成，目前是整句的各种翻译。并且对此解释为
> 如果随便放一个翻译或者全部释义都放上，那么这个行为是无意义的

实在是本末倒置。而且整句的翻译是锦上添花的角色，不应该把所有来源的翻译全部放上去。
我建议，作为一个单词本应该
* 添加所有单词释义，包括中英文。
* 例句翻译作为下拉选择，用户选择一种自认为翻译的不错的添加到单词本。

**Comment by crimx** [comment]
- 无本何来本末倒置。
- 翻译引擎设置可选。
