### ISSUE TITLE
自动查词设置项总是被关闭

### ISSUE THREAD

**Issue by AlixChiong** [crimx/ext-saladict#42]
- 平台：Windows 10 64 bit 猎豹浏览器
- 类型：错误
- 描述：插件设置中打开了自动直接搜索查词、双击搜索查词，总是用着用着莫名其妙的自动就被关闭了，每次还要重新设置一遍，不能默认就开启这些设置吗
![qq 20180201142551](https://user-images.githubusercontent.com/8144608/35664174-d52c7afa-075b-11e8-8f1b-1cf25edc8414.png)

**Comment by crimx** [comment]
这里确实有个奇怪的 bug，遇到的话重置一下设置就行，在重写新的版本所以这个不修复了。
