### ISSUE TITLE
有道翻译分级功能失效

### ISSUE THREAD

**Issue by kaijianding** [crimx/ext-saladict#420]
### Saladict 版本

6.33.2

### 平台

mac

### 类型

有道网页翻译分级功能失效了，只有全文翻译功能有效，其他三种分级全部都显示 该网页没有难词

### 重现方式

比如 https://clickhouse.yandex/docs/zh/operations/utils/clickhouse-copier/ 试过很多别的网站的网页，都是一样问题

**Comment by crimx** [comment]
deuplcated #354
