### ISSUE TITLE
在javadoc文档中不显示翻译按钮

### ISSUE THREAD

**Issue by Willing-Xyz** [crimx/ext-saladict#421]
### Saladict 版本

6.33.2

### 平台

操作系统版本：macOS 10.14.5
浏览器版本 75.0.3770.142（正式版本） （64 位）

### 类型

在各种javadoc页面，划词不显示翻译图标

### 重现方式

例如，在https://docs.spring.io/spring/docs/5.0.6.RELEASE/javadoc-api/ 页面，划词后不显示图标

**Comment by crimx** [comment]
太古老的过时技术实在不想抽时间支持。之前已有几次反馈，我重构的时候看看吧。

**Comment by crimx** [comment]
无法支持页面内显示面板，因为每个 frame 都是独立的。但你可以启用独立窗口的沙拉查词面板。
