### ISSUE TITLE
会不会考虑做成安卓/ios app? 用ionic/cordova之类的

### ISSUE THREAD

**Issue by rekhubs** [crimx/ext-saladict#423]

**Comment by crimx** [comment]
请阅读[常见问题及答复](https://github.com/crimx/ext-saladict/wiki/Q&A#%E9%97%AE%E8%83%BD%E5%90%A6%E5%9C%A8-windowsmaclinuxiosandroid-%E5%B9%B3%E5%8F%B0%E4%B8%8A%E5%AE%9E%E7%8E%B0%E5%8E%9F%E7%94%9F%E7%89%88%E6%9C%AC%E7%9A%84-saladict)
