### ISSUE TITLE
柯林斯词典的发音功能无法使用

### ISSUE THREAD

**Issue by CZXFCN** [crimx/ext-saladict#424]
### Saladict 版本

6.33.2

### 平台

Windows 10 专业版 版本号 1809 操作系统版本 17763.379 ，chrome 75.0.3770.142

### 类型

柯林斯词典的发音功能无法使用，但是进入官网查词的时候是可以使用的

### 期待

能让功能正常使用

**Comment by crimx** [comment]
双语和英英源我都测试没问题。
