### ISSUE TITLE
可能的插件冲突

### ISSUE THREAD

**Issue by HeavenElegy** [crimx/ext-saladict#425]
### 重现方式

与插件Stylus一起使用。
访问网页: https://docs.spring.io/spring-security/site/docs/5.2.0.M3/reference/htmlsingle/#core-components
Stylus添加Spring Documentation样式(默认排序目前是地一个)。源码位于https://userstyles.org/styles/167945/spring-documentation
此时对任意单词进行翻译，可以观察到弹框内字体样式变为灰色。

**Comment by crimx** [comment]
不好意思，你的表达我没看懂，请按模板反馈。

**Comment by HeavenElegy** [comment]
![Uploading Peek 2019-07-30 11-44.gif…]()
@crimx

**Comment by HeavenElegy** [comment]
![Uploading Peek 2019-07-30 11-44.gif…](图)

**Comment by HeavenElegy** [comment]
![a1](https://user-images.githubusercontent.com/19890506/62099254-12c6e380-b2c0-11e9-96a7-67c0ca1b5f09.gif)
@crimx 录了下屏。更直观些

**Comment by crimx** [comment]
不知道这个 Stylus 有没有设置可以过滤元素，或者你可以通过沙拉查词设置的「查词面板」中自定义样式覆盖。

Saladict7 将使用 Shadow DOM ，这个问题应该会解决。

**Comment by HeavenElegy** [comment]
ok, 其实这并不影响使用。期待你们发展的更好。

**Comment by crimx** [comment]
都以为是团队哈哈哈，其实只有我一个，所以 Saladict7 有可能是有生之年……

**Comment by HeavenElegy** [comment]
干，那不就更吊了吗。哈哈哈哈
