### ISSUE TITLE
关于面板查词的问题及建议

### ISSUE THREAD

**Issue by Raychanan** [crimx/ext-saladict#426]
### Saladict 版本

6.33.2

### 平台

chrome

### 类型

1.「出现位置」选择「下方」后，查词面板依然在右方显示
2.建议：让「查词习惯」下的「直接搜索」可以设置快捷键。我个人用沙拉查词只会在阅读英文新闻的时候用，因此只会在直接搜索和彻底关闭沙拉查词之间切换，但每次切换却都要点很多次。为什么不用其他模式：「显示图标」模式一直有个东西在那很烦，「按住按键」模式在连续大量查词查句条件下用起来很累...

**Comment by crimx** [comment]
> 每次切换却都要点很多次

关闭沙拉查词不是有快捷键吗？另外可以结合黑白名单使用。

> 为什么不用其他模式

没看懂这是什么意思

**Comment by crimx** [comment]
> 「出现位置」选择「下方」后，查词面板依然在右方显示

这是快捷查词的设置，不是鼠标划词的设置，见分类的名字。

**Comment by DerekTso** [comment]
@crimx 
浏览器外使用 查词面板 时，每次调用它，都会出现在一个固定的位置
希望提供一个设置，来设定它弹出时出现的位置
比如，上次移动后的位置

**Comment by crimx** [comment]
出现位置见上面提到的设置。

设定为上次关闭的位置我看不出有什么用处？你可以开新 issue 详细反馈。
