### ISSUE TITLE
保存到生词本时，添加了 “笔记”“上下文”信息，但是在“Saladict 查词记录（仅本地保存）”没有显示

### ISSUE THREAD

**Issue by conncui** [crimx/ext-saladict#428]
首先致敬作者。
这个插件在功能设计，交互实现，数据存储方面都做的超级棒。用起来很爽。

使用中遇到一个问题：

保存到生词本时，添加了 “笔记”“上下文”信息，但是在“Saladict 查词记录（仅本地保存）”没有显示。
如图：
![image](https://user-images.githubusercontent.com/6135718/62349668-00a0ab80-b533-11e9-9401-429ed0fb3e31.png)
![image](https://user-images.githubusercontent.com/6135718/62349675-04ccc900-b533-11e9-89d7-25db810b2d49.png)
Google Chrome

浏览器：Chrome 
版本 75.0.3770.142（正式版本） （64 位）
系统： macOS Mojave 10.14.3  Pro 15 2018

**Comment by crimx** [comment]
单词是保存在生词本，查词记录需要在设置中开启才会记录查词历史。
