### ISSUE TITLE
希望添加一个折叠按钮

### ISSUE THREAD

**Issue by cchenga** [crimx/ext-saladict#429]
### Saladict 版本

6.33.2

### 平台

Windows 10 Pro, chrome 75.0.xxx

### 类型

建议

### 期待

查词之后如果单词内容多可以点击" ﹀ "展开内容，希望可以在内容底部添加一个button  " ︿ " 点击之后恢复到原来的缩略视图，而不是完全折叠内容

**Comment by crimx** [comment]
你好，这个功能的场景是什么呢？为什么需要再次看回缩略状态。

**Comment by cchenga** [comment]
你好，感谢回复。具体场景是：
很多时候缩略状态下内容是释义，被折叠的内容是例句，看完例句之后想再次回看释义，如果内容很长就要用滚轮滑动很长。如果可以添加折叠button，只要一个单击就回去了。

**Comment by crimx** [comment]
这样操作也不是很方便。我的设想是再添加一个目录按钮，为词典的不同部分提供跳转。

**Comment by cchenga** [comment]
比起添加一个目录按钮，我个人觉得，显示词典名字的bar 如果完全折叠的使用场景不多的话，可以改成折叠到缩略图的状态。

**Comment by crimx** [comment]
这样当处于缩略状态时按箭头就无法判断是该展开还是收回。我还是倾向保留收回的功能。

**Comment by crimx** [comment]
7.14.0 在词典标题栏添加了多功能菜单，部分较长的词典支持了跳转。如果发现其它词典需要支持欢迎提交新 issue 反馈。
