### ISSUE TITLE
除了谷歌翻译外，其他的词典都无结果

### ISSUE THREAD

**Issue by sutoonl** [crimx/ext-saladict#430]
### Saladict 版本

6.33.2

### 平台

chrome 75.0.3770.142 (正式版本)

### 类型

错误

### 实际

划词翻译的时候，除了谷歌翻译外，其他的词典都无结果，点词典标题网页都能打开。
chrome安装了谷歌访问助手，没有开vpn或者其他代理。谷歌访问助手打开或关闭，其他词典都无结果。

**Comment by crimx** [comment]
扩展运行正常，请检查你的其它网络设置。
