### ISSUE TITLE
增加youdict支持

### ISSUE THREAD

**Issue by he-johnson** [crimx/ext-saladict#433]
可否增加这个网站的支持，觉得他的词根做得不错
https://www.youdict.com/

**Comment by crimx** [comment]
你好，功能雷同的词典不再考虑添加。

**Comment by he-johnson** [comment]
> 你好，功能雷同的词典不再考虑添加。

哪个替代词典可以解析单词包含的词根

**Comment by crimx** [comment]
etymonline ，顾名思义。

**Comment by he-johnson** [comment]
感觉这个的解释没有那个那么通俗易懂啊，那词根看不太懂含义，英文的
