### ISSUE TITLE
建议增加一个选项,只有划词只有英文时才翻译

### ISSUE THREAD

**Issue by a471640241** [crimx/ext-saladict#434]
经常复制一句包含中英文的翻译就显示出来了,其实只是为了复制

**Comment by crimx** [comment]
请阅读使用说明<https://github.com/crimx/ext-saladict/wiki>。

**Comment by a471640241** [comment]
![image](https://user-images.githubusercontent.com/11511810/62766690-a6b95c00-bac5-11e9-8c49-236426de9e16.png)
我的建议是 设置后,只有英文才翻译,而不是包含英文就翻译

**Comment by withwind819** [comment]
看了使用说明还是没发现解决方案

**Comment by crimx** [comment]
这个功能在待实现列表中。

**Comment by a471640241** [comment]
选项勾选了后,划词含有中文还是会弹出窗口翻译
我以为我使用方式不对,但是我试了一下勾选或者不勾选,只要含有英文都会被翻译
环境:  系统 Windows 10  浏览器 Chrome 77.0.3865.90  / QQ浏览器 10.5  两个都是一样的结果
![image](https://user-images.githubusercontent.com/11511810/66737740-5b457480-ee9f-11e9-860b-cfa624e04eed.png)
![image](https://user-images.githubusercontent.com/11511810/66737866-b0818600-ee9f-11e9-87fd-aa32307013bf.png)

**Comment by crimx** [comment]
哈哈，忘了怎么没写完就提交上去了。

**Comment by a471640241** [comment]
建议只有数字的时候不要弹窗,只是想复制一下,结果弹窗把右边的内容挡住了
我已经设置了只有英文的时候翻译,但是纯数字的时候也会弹窗
![image](https://user-images.githubusercontent.com/11511810/67137312-7fb99c00-f265-11e9-890a-97a668856ac6.png)
