### ISSUE TITLE
希望加入自定义主题功能或者dark theme

### ISSUE THREAD

**Issue by kevinhwang91** [crimx/ext-saladict#435]
非常喜欢这款插件，是我Linux下最主要翻译工具。

浏览器使用了[Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh)渲染成黑色，triple ctrl若设置成独立窗口，界面是没办法渲染成黑色(非独立窗口能)。
同时chrome(chromium)通过自定义Activate the extension快捷键启动也无法经过Dark Reader渲染成黑色。

以上问题造成了在黑色界面上使用不协调，建议加入自定义css或者一个标准的dark theme。

**Comment by crimx** [comment]
请查看设置。
