### ISSUE TITLE
程序无法使用  提示已损坏   

### ISSUE THREAD

**Issue by ihoey** [crimx/ext-saladict#436]
### Saladict 版本

沙拉查词-聚合词典划词翻译
6.33.3

### 平台

Mac chrome
![image](https://user-images.githubusercontent.com/14155573/62753364-eff5b580-ba9d-11e9-81bc-153474010d75.png)

### 类型

![image](https://user-images.githubusercontent.com/14155573/62753350-dfddd600-ba9d-11e9-90ab-674503e59885.png)
![image](https://user-images.githubusercontent.com/14155573/62753358-e66c4d80-ba9d-11e9-8080-65be4b5be704.png)
![image](https://user-images.githubusercontent.com/14155573/62753502-84601800-ba9e-11e9-805b-a3d57c1f4058.png)

**Comment by ihoey** [comment]
![image](https://user-images.githubusercontent.com/14155573/62753601-ecaef980-ba9e-11e9-81b4-f835dc0942e4.png)

**Comment by crimx** [comment]
安装 Saladict 后你有改过什么设置吗？导出来我测试一下。

**Comment by ihoey** [comment]
[config-1565324302974.saladict.zip](https://github.com/crimx/ext-saladict/files/3484732/config-1565324302974.saladict.zip)

这是我的设置 我感觉是使用的频繁会这样

**Comment by crimx** [comment]
跟频率没有关系，很可能是 bug chrome 最近做了什么升级。

**Comment by ihoey** [comment]
> 跟频率没有关系，很可能是 bug chrome 最近做了什么升级。

那也是极有可能  我是前两天升级的 chrome

**Comment by crimx** [comment]
你是通过 Chrome Web Store 安装 Saladict 的吗？

**Comment by ihoey** [comment]
> 你是通过 Chrome Web Store 安装 Saladict 的吗？

是的  我点击修复之后也是可以正常使用的  不过过段时间还会出现

**Comment by ihoey** [comment]
![image](https://user-images.githubusercontent.com/14155573/62754140-3567b200-baa1-11e9-95dd-f1b2866ac2fe.png)


> > 你是通过 Chrome Web Store 安装 Saladict 的吗？
> 
> 是的 我点击修复之后也是可以正常使用的 不过过段时间还会出现

**Comment by ihoey** [comment]
应该给你看这个

![image](https://user-images.githubusercontent.com/14155573/62754243-90010e00-baa1-11e9-848a-203c3f1d1f8f.png)

**Comment by crimx** [comment]
这个问题貌似在 Mac 上出现比较多，Linux 上偶尔出现（或者说用户本来就不多），Windows 还没有人反馈。估计 Mac 和 Linux 是用的同一套代码，可能某个地方出 bug 了，但我一直没能复现，只能玄学修复。

**Comment by crimx** [comment]
v6.33.4 正在发布，有问题转到 #432 反馈。

**Comment by shetz163** [comment]
我用的是 windwos,这几天更新了chrome 76 之后就开始了,

**Comment by crimx** [comment]
看来 Windows 也开始中招了
