### ISSUE TITLE
希望能出一个app用来复习之前添加的单词

### ISSUE THREAD

**Issue by wawo00** [crimx/ext-saladict#437]

**Comment by crimx** [comment]
请阅读[常见问题及答复](https://github.com/crimx/ext-saladict/wiki/Q&A#wiki-wrapper)。

**Comment by wawo00** [comment]
恩。。。您可以暴露接口我们来贡献代码

**Comment by crimx** [comment]
你们是有现成的产品了么？

**Comment by wawo00** [comment]
不是啊，只是有点时间可以工作之余做一下，沙拉我是一直在用，但是单词经常添加完了不复习很快就忘了

**Comment by crimx** [comment]
我用的 Anki 感觉很难能超越它了。这样你可以做一个独立的记单词应用，最后我可以提供接口获取沙拉查词的单词。

**Comment by crimx** [comment]
或者你也可以通过同步 WebDAV 获取单词

**Comment by wawo00** [comment]
得需要一套数据库来对应每个人的单词本吧

**Comment by crimx** [comment]
Saladict 不在服务器保存任何用户数据。你可以

- 通过谷歌扩展的接口与 Saladict 扩展交互获得用户本地的生词。
- 或者通过 WebDAV 同步到你的应用上。

**Comment by wawo00** [comment]
哇，是个好主意!谢谢您!

**Comment by crimx** [comment]
不客气
