### ISSUE TITLE
在这个网站https://ees.elsevier.com/ipm/ 无法显示翻译图标，希望修复，感谢大神。

### ISSUE THREAD

**Issue by squllwu** [crimx/ext-saladict#438]
### 类型

在这个网站https://ees.elsevier.com/ipm/
无法显示翻译图标，希望修复，感谢大神。

### 划词模式

在这个网站https://ees.elsevier.com/ipm/
无法显示翻译图标，希望修复，感谢大神。

**Comment by crimx** [comment]
又是 frameset 的网页，这种技术已经严重过时了，基本都是上古的网站。在 Saladict 重写的时候我会看看能不能兼容，如果太麻烦就只能放弃了。
