### ISSUE TITLE
8月11日更新的沙拉查词版本，在使用时频繁被停用

### ISSUE THREAD

**Issue by guyeu** [crimx/ext-saladict#439]
8月11日更新的沙拉查词版本；
在使用时频繁莫名被停用，需要在扩展页面重新启用，然而等一会儿它又被停用了。

**Comment by crimx** [comment]
请按模板提供必要的信息。

**Comment by guyeu** [comment]
版本号6.33.5的沙拉查词在所有页面出现被停用的情况，因为我已经弃用该插件，所以无法提供更进一步的信息。
我不会重新打开这个issue，如果有其他人遇到了同样的问题请自行打开。

**Comment by crimx** [comment]
如果是 6.33.5 说明 Chrome 76 的 Bug  依然存在（见 #432 ），如果不幸出现问题了目前也就只能禁用插件等待 Chrome 修复。

**Comment by Mrcooder** [comment]
> 如果是 6.33.5 说明 Chrome 76 的 Bug 依然存在（见 #432 ），如果不幸出现问题了目前也就只能禁用插件等待 Chrome 修复。

6.33.5 还是有问题，Chrome 版本 76.0.3809.100

**Comment by crimx** [comment]
请订阅 #432 等待消息
