### ISSUE TITLE
划词后 无法翻译，挂掉了，extensions中提示 repare

### ISSUE THREAD

**Issue by karp-hope** [crimx/ext-saladict#442]
### Saladict 版本

6.33.5

### 平台

mac version10.14.6 ,     chrome Version 76.0.3809.100 (Official Build) (64-bit)

### 类型

经常出现无法翻译的情况，然后在extensions中提示repare，才能使用，用不了一会后，又出现了此种情况~~~ 其他的方面做得挺好， 就是感觉 稳定性 有待提高

**Comment by crimx** [comment]
duplicate of #432
