### ISSUE TITLE
腾讯翻译君无法正常显示段落翻译结果

### ISSUE THREAD

**Issue by lifesoul** [crimx/ext-saladict#443]
### Saladict 版本

6.33.5

### 平台

Windows 10 1903，Chrome 76.0.3809.100

### 类型

在网页上通过划词方式选取一段英文后，点击沙拉图标，腾讯翻译君无法正常显示翻译结果

### 额外信息

我是在[www.learnrazorpages.com](https://www.learnrazorpages.com/razor-pages/handler-methods)上进行划词翻译操作时，发现的这个问题。

**Comment by crimx** [comment]
嗯，腾讯更新了 API

**Comment by YangFan789** [comment]
腾讯翻译在 Firefox（69.0）上是正常的。在 Chrome 下会显示 "。。。"

**Comment by YangFan789** [comment]
看起来这个问题已经解决了。

**Comment by crimx** [comment]
差不多，现在发音也得处理一下
