### ISSUE TITLE
请求添加新词典 Weblio日中中日词典

### ISSUE THREAD

**Issue by Wolfsin** [crimx/ext-saladict#444]
### Saladict 版本

6.33.5

### 平台

Win10 
Chrome 76.0.3809.100

### 类型

建议

### 额外信息

在当前版本中已经有Weblio 英和和英这个词典了，但是Weblio它是有中日日中词典的。目前对于日语的划词，基本还是靠谷歌词典和Weblio 辞書，可是Weblio 辞書对于词组的划词体验非常不好，更不用说中文词组想知道日文写法这种情况了，所以既然作者添加了Weblio 英和和英词典，我觉得加一个Weblio 中日日中词典也很有必要吧。
词典地址：https://cjjc.weblio.jp/

**Comment by crimx** [comment]
> 所以既然作者添加了Weblio 英和和英词典，我觉得加一个Weblio 中日日中词典也很有必要吧。

你好，这里的逻辑没明白。我个人觉得 Weblio 中日日中比英和和英鸡肋，我基本都是用后者，所以没什么动力再维护多一个词典。有其他人愿意维护也是欢迎的。

**Comment by Wolfsin** [comment]
> > 所以既然作者添加了Weblio 英和和英词典，我觉得加一个Weblio 中日日中词典也很有必要吧。
> 
> 你好，这里的逻辑没明白。我个人觉得 Weblio 中日日中比英和和英鸡肋，我基本都是用后者，所以没什么动力再维护多一个词典。有其他人愿意维护也是欢迎的。

我是从中文用户的角度出发的，所以中日日中 会比 英和和英 在日常使用上用的次数更多一点。而实际目前在中日日中上 除了谷歌词典以外其他词典的使用体验并不好，比如Weblio只给出了日文解释，Weblio英和只给出了英文解释。对于复合词典的插件来说，只有一个词典在这种情况下能正常使用，我个人感觉不太友好。
