### ISSUE TITLE
独立窗口：可否让它不要抢占当前浏览器焦点？

### ISSUE THREAD

**Issue by longnight** [crimx/ext-saladict#445]
### Saladict 版本

6.33.5

### 平台

win10, chrome 76

### 类型

独立窗口会抢占当前浏览器焦点，使得正在编辑文本、选中一段文字要删除或复制时，引发操作失误。

### 期待

建议：独立窗口做到不要抢占焦点，默默地在后台查词就好了：)

**Comment by crimx** [comment]
不太懂这个逻辑，为什么要默默后台划词……不需要就关掉或者设置其它的划词方式。

**Comment by longnight** [comment]
> 不太懂这个逻辑，为什么要默默后台划词……不需要就关掉或者设置其它的划词方式。

在一个含有可编辑内容、且需要saladict 查词时，我会开一个saladict的独立窗口放在当前浏览器旁边以免挡住文档内容。这样就会出现issue提到的问题。
能否做到不抢占焦点呢 ？

**Comment by crimx** [comment]
这样的情况可以考虑。

**Comment by crimx** [comment]
沙拉查词 7 已支持。可通过点击 📌 按钮切换。
