### ISSUE TITLE
添加到扇贝单词失败

### ISSUE THREAD

**Issue by xmlyqing00** [crimx/ext-saladict#447]
点击图标查看单词翻译，添加到扇贝单词本失败。已成功添加50多个单词，但现在突然失败了。

![image](https://user-images.githubusercontent.com/8945602/63661734-5dcdfc80-c781-11e9-9bea-3aaf7fd6369b.png)

### Saladict 版本
6.33.5

### 平台
Mac, Chrome

### 类型
添加单词到单词本失败

### 划词模式
网页双击划词

### 期待
已成功添加50多个单词，想添加新的失败

**Comment by crimx** [comment]
扇贝网貌似不是什么单词都行的，你可以在官网中添加看看。

**Comment by crimx** [comment]
我添加是可以的。可能是频率问题？

**Comment by xmlyqing00** [comment]
谢谢，我这里后来时好时坏，问题不大，整体上还是挺好用的！（顺手read后忘了回了不好意思
