### ISSUE TITLE
希望google翻译可以添加或提供修改到uk

### ISSUE THREAD

**Issue by jjkmaze** [crimx/ext-saladict#450]
希望google翻译可以添加或提供修改到uk。有些词，词典并没有收录，句子也无法朗读。

### Saladict 版本

6.33.5

### 平台

Win7, Chrome

### 类型

建议

### 期待

希望google翻译可以添加或提供修改到uk。有些词，词典并没有收录，句子也无法朗读。

**Comment by crimx** [comment]
"google翻译" 是指字典面板中的翻译还是指网页翻译。“有些词，词典”请提供可测试的例子谢谢。

**Comment by jjkmaze** [comment]
> "google翻译" 是指字典面板中的翻译还是指网页翻译。“有些词，词典”请提供可测试的例子谢谢。

不好意思，漏了提及。是字典面板中的翻译

**Comment by crimx** [comment]
没有问题的。你的是什么网络环境呢？为什么需要切换到 uk ？

**Comment by mogu1121** [comment]
@crimx 搜狗翻译没有东西，状态码 200 body 0

**Comment by crimx** [comment]
是的，搜狗更新了 API，我在 saladict 7 中已经修复，但最快也得中秋后上线了。

还有新问题请新开 issue ，尽量不要搭楼反馈跟主题无关的问题。
