### ISSUE TITLE
右上角查词能否设置快捷键打开？

### ISSUE THREAD

**Issue by firewiki** [crimx/ext-saladict#451]
### Saladict 版本

6.33.5
### 平台

win7 firefox 68.0.2

### 额外信息

遇到一些图片上的文字，只能通过输入单词查，每查一次都要点右上角的图标弹出查词界面。能否有个快捷键弹出？

**Comment by crimx** [comment]
请阅读使用说明<https://github.com/crimx/ext-saladict/wiki>。
