### ISSUE TITLE
这个界面不能使用插件

### ISSUE THREAD

**Issue by chile-zhong** [crimx/ext-saladict#452]
https://news.google.com/?hl=en-US&gl=US&ceid=US:en
这个界面不能使用插件,有办法吗?

**Comment by crimx** [comment]
全是链接，一般链接可以按住 <kbd>Alt</kdb> 选词，如果不行你也可以结合快捷键使用悬浮查词。

**Comment by crimx** [comment]
看了代码，谷歌在文字上面都多加了一层，所以是没法选了，除非出一个专门的插件去掉。

**Comment by chile-zhong** [comment]
> 看了代码，谷歌在文字上面都多加了一层，所以是没法选了，除非出一个专门的插件去掉。

那就对了

**Comment by crimx** [comment]
这个已超出本扩展的范围，除非是刚需不会考虑针对单一网页提供兼容。

**Comment by chile-zhong** [comment]
> 这个已超出本扩展的范围，除非是刚需不会考虑针对单一网页提供兼容。

好的
