### ISSUE TITLE
浏览器右上角菜单栏打开翻译窗口， 滚动内容后， 会清除掉已有的内容。 

### ISSUE THREAD

**Issue by W-quan** [crimx/ext-saladict#455]
### Saladict 版本
6.33.5

### 平台
macOS 10.14.6
Firefox 69.0

### 类型
显示问题

![图片](https://user-images.githubusercontent.com/9608466/64674568-b00e5d80-d4a3-11e9-9720-76cc6ab61a01.png)

**Comment by crimx** [comment]
这应该是 ff 对你的显卡支持有问题，关闭 ff 硬件加速即可。

**Comment by xiecang** [comment]
同遇到这个问题，有不关闭硬件加速的方案吗？

**Comment by xiecang** [comment]
只在 ToolBar 上有这个问题，网页内未复现。

ps: 设备与 W-quan 相同

**Comment by crimx** [comment]
沙拉查词 7 将使用不同的技术，到时看看还会不会出现吧。

**Comment by xiecang** [comment]
收到，期待，后续会反馈在这里~

**Comment by crimx** [comment]
新版如果有问题欢迎重开。

**Comment by xiecang** [comment]
7.0 还是有问题

**Comment by crimx** [comment]
火狐团队[确认]((https://bugzilla.mozilla.org/show_bug.cgi?id=1557342))了这个 bug ，但是优先级不高。

**Comment by crimx** [comment]
沙拉查词 7 可以设置为点击打开独立窗口。
