### ISSUE TITLE
某些网页插件失效

### ISSUE THREAD

**Issue by xuechangjiang** [crimx/ext-saladict#456]
例如：http://www-inst.eecs.berkeley.edu/~cs162/sp14/
我使用的是76.0.3809.132版本的Chrome,64位，Windows10 1903,插件版本：6.33.5。当我打开此网页后，选中一段文字并不会弹出图标，其他网页却可以，请问这是网页的限制还是插件的问题

**Comment by crimx** [comment]
这个网页使用了严重过时的 frameset 技术，所以沙拉查词不支持内嵌。你可以使用独立查词面板。
