### ISSUE TITLE
建议网页翻译增加彩云小译的功能

### ISSUE THREAD

**Issue by zsedcbm** [crimx/ext-saladict#46]
目前的有道网页翻译是直接将内容变成中文, 彩云小译是在每段文字后面增加翻译的内容,看起来更加方便.平时直接通过书签栏能快速翻译,但是在github上面不能正常使用.希望能够集成到插件中,能够快速使用.

**Comment by crimx** [comment]
彩云小译有[官方](https://chrome.google.com/webstore/detail/lingocloud/jmpepeebcbihafjjadogphmbgiffiajh) chrome 扩展，且保持更新。

**Comment by zsedcbm** [comment]
知道了, 自己忘记去chrome商店找了.
