### ISSUE TITLE
Bug: 剑桥词典无法发音

### ISSUE THREAD

**Issue by maomaowei5655** [crimx/ext-saladict#460]
**Saladict 版本**
6.33.6

**平台**
MacOS Mojave,版本 10.14.5
Firfox Quantum 69.0 (64 位)

**问题类型**
【剑桥词典】（点击发音图标时  或  设置为英文自动发音时）无法发音

**额外信息**
在剑桥词典的源网站中点击发音图标仍可正常发音👉[https://dictionary.cambridge.org/zhs/词典/英语-汉语-简体/](url)

**Comment by crimx** [comment]
更新到 6.33.7
