### ISSUE TITLE
分享Mac版使用技巧：通过Popclip在Mac上实现“Saladict响应浏览器外划词翻译”

### ISSUE THREAD

**Issue by maomaowei5655** [crimx/ext-saladict#463]
### Saladict 版本
6.33.7

### 平台
MacOS Mojave，版本 10.14.5
**Google Chrome**，版本 76.0.3809.132

### 类型
<在Mac上实现沙拉词典响应浏览器外划词翻译>

### 操作方法

1. 下载Popclip👉[官网](https://pilotmoon.com/popclip/)或[App Store](https://apps.apple.com/cn/app/popclip/id445189367?mt=12)（¥68.00）
2. 下载本人自制的popclip扩展：Saladict.popclipext👉[Saladict.popclipext.zip](https://github.com/crimx/ext-saladict/files/3612769/Saladict.popclipext.zip)
3. 解压上述zip压缩包，双击解压得到的文件：Saladict.popclipext
4. 下载Google Chrome并安装扩展程序：“沙拉查词”，并设置“沙拉查词”扩展程序“打开独立词典窗口”的快捷键为“Control+L”且”全局”生效👇
   ![](https://user-images.githubusercontent.com/51223743/64909221-d51cfd80-d73b-11e9-9d7c-f7d488f36461.png)
5. 将沙拉查词的“快捷查词”设置为如下状态👇
   ![](https://user-images.githubusercontent.com/51223743/64909275-a8b5b100-d73c-11e9-9cce-1d4f03192dc7.png)
6. **在打开（或后台运行）Chrome浏览器的情况下**，在Chrome浏览器以外的任意位置选中文字并点击Popclip弹窗中的沙拉查词Logo后，出现沙拉查词面板，e.g.👇
   ![图片](https://user-images.githubusercontent.com/51223743/64909399-0c8ca980-d73e-11e9-965d-a413e586c911.png)

**Comment by crimx** [comment]
非常感谢！

**Comment by LambdaExpression** [comment]
我在使用时，发现如果独立窗口已经存在，再使用PopClip，无法覆盖原独立窗口内查询的单词，使用不太方便

**环境：**
mac os 10.13.6
chrome 78.0.3904.97
沙拉查词 7.5.2
PopClip 2019.10

我临时改了一下插件

**准备**
![image](https://user-images.githubusercontent.com/17667040/68749864-e69a5d00-0639-11ea-98f0-85abe04894e8.png)

**修改内容：**
saladict.applescript 文件
```
tell application "System Events"
	key code 37 using {control down}
end tell
//添加了下面代码
tell application "System Events"
	key code 35 using {control down}
end tell
```

**修改后的插件 [Saladict.popclipext.tar.gz](https://github.com/crimx/ext-saladict/files/3840340/Saladict.popclipext.tar.gz)**

**Comment by maomaowei5655** [comment]
> 我在使用时，发现如果独立窗口已经存在，再使用PopClip，无法覆盖原独立窗口内查询的单词，使用不太方便
> 
> **环境：**
> mac os 10.13.6
> chrome 78.0.3904.97
> 沙拉查词 7.5.2
> PopClip 2019.10
> 
> 我临时改了一下插件
> 
> **准备**
> ![image](https://user-images.githubusercontent.com/17667040/68749864-e69a5d00-0639-11ea-98f0-85abe04894e8.png)
> 
> **修改内容：**
> saladict.applescript 文件
> 
> ```
> tell application "System Events"
> 	key code 37 using {control down}
> end tell
> //添加了下面代码
> tell application "System Events"
> 	key code 35 using {control down}
> end tell
> ```
> 
> **修改后的插件 [Saladict.popclipext.tar.gz](https://github.com/crimx/ext-saladict/files/3840340/Saladict.popclipext.tar.gz)**

非常感谢！解决了我使用过程中一直感到困惑的一个问题👍

**Comment by ImJoeHs** [comment]
补充一下，第 5 步，自动查词选项是必须的。
![image](https://user-images.githubusercontent.com/13445155/69963939-46ef3100-154c-11ea-9ad3-17628707ff8b.png)

其次，Ctrl_L 这样的快捷键非常容易冲突，个人的设置是：
```
	key code 43 using {shift down, control down} -- Ctrl Shift ,
	key code 47 using {shift down, control down} -- Ctrl Shift .
```

当前方案还有一个小问题是，无法将独立窗口移动到当前的 space，[相关讨论](https://stackoverflow.com/questions/14060991/how-can-i-move-a-window-to-a-target-space-with-applescript-in-os-x-10-8)，个人几番尝试无果，不知后来人有没有兴趣再研究下。
如果习惯多 space 操作，会比较麻烦。

**Comment by crimx** [comment]
@ImJoeHs 自动查词应该不需要的，  @maomaowei5655 你是不是还用着原来只调出查词面板的快捷键，现在有新的快捷键可以让沙拉查词直接查剪贴板内容。

**Comment by ImJoeHs** [comment]
@crimx 确实是，只设置 [在独立窗口中搜索剪贴板内容] 这个快捷键就可以了。

我是按上面操作 apple script 中先后触发两个快捷键，应该是第一个先被相应，因此剪贴板没有生效。

**Comment by zhylmzr** [comment]
saladict 窗口关闭后会自动聚焦到 chrome, 有什么办法不让它自动聚焦吗?

**Comment by crimx** [comment]
请[另开 issue](https://github.com/crimx/ext-saladict/issues/new/choose) 描述你遇到了什么问题。

**Comment by drcege** [comment]
有没有办法直接划词翻译？ 不用再点一下 popclip 上的按钮

**Comment by Kevin0602** [comment]
第4步上的界面没有找到啊

**Comment by lingyuecui** [comment]
全部都按照要求设置了，可是我在pdf预览中划词以后点击沙拉查词的浮动图标，沙拉查词的空白独立窗口会弹出，但并不会显示已划词和其翻译。在popclip官方下载比如谷歌翻译的扩展就可以在浏览器外正常查词，在chrome浏览器网页划词也正常。求大神帮忙>< 谢谢啦！

**Comment by BingYu-track** [comment]
我也没找到第4步的界面

**Comment by PoJunHao** [comment]
第一次使用正常，再勾选词点击图标后无法再覆盖原来的查词。需要手动复制后才可以。。。这个插件好久没更了

**Comment by ImJoeHs** [comment]
您好， 您的邮件已收到，我会尽快回复，谢谢。

**Comment by kkkkkk110** [comment]
我每次第一次划词之后可以翻译，但是第二次划词之后翻译的就是上次的文本了，请问这是为什么啊，急求解答！！！

**Comment by bobojx** [comment]
能自定义快捷键吗？

**Comment by LU90210** [comment]
是不支持m2芯片了吗

**Comment by ryan4096** [comment]
> 第4步上的界面没有找到啊

在这里chrome://extensions/shortcuts
