### ISSUE TITLE
关于查词面板查词记录的小建议

### ISSUE THREAD

**Issue by JIAN-JUN** [crimx/ext-saladict#466]
### 期待

希望查词面板上的上（下）一个查词记录这两个按键，能够变得更可视化，直观一点。例如直接把之前查的单词列出来供选择，这样可以比较快速的定位。

### 实际

现行的方案很简洁，但是如果在实际使用中，如果我在一个查词面板中又连续点击的几次面板中的其他生词，那么我想要回到一开始查询的那个词，可能就要经历几次或多次比较模糊的操作。

### 额外信息

还有希望读音重播的按键在面板上，可以快速开关。

**Comment by crimx** [comment]
这个有点麻烦所以没有时间实现，希望查看更多历史记录可以打开查词记录页面。
