### ISSUE TITLE
[UI建议]

### ISSUE THREAD

**Issue by TTTPOB** [crimx/ext-saladict#467]
### Saladict 版本

6.33.7

### 平台

Windows 10 1903 
Chrome stable 77.0.3865.75

### 类型

建议

### 期待

UI的开关按钮改小一点，特别是单击扩展图标的“启用划词”这个开关
![image](https://user-images.githubusercontent.com/19909103/65104518-3e369680-da04-11e9-8b68-0ba65c699a50.png)
我觉得跟Windows设置的可以差不多大，更小一点也好。
### 实际

![image](https://user-images.githubusercontent.com/19909103/65104456-10e9e880-da04-11e9-84a2-51c262421d51.png)
太大啦！
![image](https://user-images.githubusercontent.com/19909103/65104472-1c3d1400-da04-11e9-9720-d3e7f6fc3f74.png)
这些地方的也略大

**Comment by crimx** [comment]
你好，我不用 windows 所以不太能体会到这个「太大」。这也是无关要紧的功能故不考虑修改。
