### ISSUE TITLE
划词翻译中的谷歌翻译结果和在谷歌翻译网页上的翻译结果相差太大，翻译结果不理想。

### ISSUE THREAD

**Issue by ZXPingDev** [crimx/ext-saladict#468]
下图是我分别在划词翻译时得到的结果：
![image](https://user-images.githubusercontent.com/39424594/65130986-0bef5e00-da31-11e9-93fb-eed2e21c760d.png)

下图是我在谷歌翻译的网站上查询的翻译结果：
![image](https://user-images.githubusercontent.com/39424594/65131063-29bcc300-da31-11e9-9fed-d74755685545.png)

可以看到，直接划词翻译时，得出的翻译结果并不怎么理想，甚至有些难以理解，和谷歌翻译网站上翻译出来的结果相差太大，能否优化处理一下呢？划词中的翻译结果，用的不是谷歌官方的API吗？

**Comment by sambodhi-cn** [comment]
我也发现这个问题了，已经到Google商店提出反馈了

**Comment by shuoyuan** [comment]
+1，两者结果的确相差太大，现在划词翻译中的谷歌翻译的结果感觉都不如有道机器翻译

**Comment by crimx** [comment]
这是因为谷歌更新了参数。

**Comment by iowijf** [comment]
正准备说这个问题呢

**Comment by crimx** [comment]
请不必再反馈，更新将会随沙拉查词 7 一同发布。
