### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by Aroman-RonCyan** [crimx/ext-saladict#470]
启用快捷键能不能加个自定义快捷键的功能，qq浏览器没法设置插件的快捷键，在用quicker的时候，必须时刻开着谷歌浏览器才能打开独立窗口

**Comment by crimx** [comment]
你好，请问你阅读[使用说明](https://github.com/crimx/ext-saladict/wiki)如何设置快捷键了吗。

如果 QQ 浏览器没有提供设置或者无法打开 `chrome://extensions/shortcuts` 那么是没法设置快捷键的。

**Comment by Aroman-RonCyan** [comment]
使用说明里面只有谷歌浏览器的设置，这个我知道怎么设置，但是QQ浏览器没找到可以设置插件快捷键的地方，上面的地址在QQ浏览器打不开，如果没法添加自定义快捷键功能，那能不能把3击Ctrl改成组合键，3击有时候识别不出

**Comment by Aroman-RonCyan** [comment]
> 你好，请问你阅读[使用说明](https://github.com/crimx/ext-saladict/wiki)如何设置快捷键了吗.
> 
> 如果QQ浏览器没有提供设置或者无法打开`chrome://extensions/shortcuts`那么是没法设置全局快捷键的.

使用说明里面只有谷歌浏览器的设置，这个我知道怎么设置，但是qq浏览器没找到可以设置插件快捷键的地方，上面的地址在qq浏览器打不开，如果没法添加自定义快捷键功能，那能不能把3击ctrl改成组合键，3击有时候识别不出

**Comment by crimx** [comment]
> 3击有时候识别不出

你好，什么时候呢？可以给出例子吗？

**Comment by crimx** [comment]
QQ 浏览器是无法设置扩展全局快捷键了。三击那个是在网页上监听，所以需要打开沙拉查词能访问的页面才行。下个版本我增加了点击右上的沙拉图标可以选择打开独立窗口。

当然更好的是用 Chrome 或者 Firefox 。

**Comment by Aroman-RonCyan** [comment]
不确定的，有时候刚打开浏览器或者用一段时间可以打开，有时候又不行，但是一般重启浏览器多试几次可以打开




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CRIMX"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月21日(星期六) 上午9:53
收件人:&nbsp;"crimx/ext-saladict"<ext-saladict@noreply.github.com&gt;;
抄送:&nbsp;"Bruce"<2329957852@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [crimx/ext-saladict] 提个建议 (#470)



 
3击有时候识别不出
  
你好，什么时候呢？可以给出例子吗？

**Comment by Aroman-RonCyan** [comment]
希望再添加一个OCR识别翻译的功能，用过很多种，感觉百度的相对最准




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CRIMX"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月21日(星期六) 中午1:14
收件人:&nbsp;"crimx/ext-saladict"<ext-saladict@noreply.github.com&gt;;
抄送:&nbsp;"Bruce"<2329957852@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [crimx/ext-saladict] 提个建议 (#470)




QQ 浏览器是无法设置扩展全局快捷键了。三击那个是在网页上监听，所以需要打开沙拉查词能访问的页面才行。下个版本我增加了点击右上的沙拉图标可以选择打开独立窗口。
 
当然更好的是用 Chrome 或者 Firefox 。

**Comment by crimx** [comment]
@Aroman-RonCyan 看看 #493
