### ISSUE TITLE
干扰正常ctrl+c

### ISSUE THREAD

**Issue by zhangdaren** [crimx/ext-saladict#471]
直接一句话：  感觉取词，网易云也好，贵插件也好，都有一个通用的问题，就是会时不时干扰ctrl+c，尤其第一次ctrl+c的时候，选中的词并没有到剪贴板上，而我此时并不需要翻译。

把取词的ctrl干掉再试试先。

**Comment by crimx** [comment]
你好，请提供复现该问题的步骤。

**Comment by zhangdaren** [comment]
在放开鼠标之前按住选择的按键才显示词典面板（Meta 键为 Mac 上的「⌘ Command」键以及其它键盘的「⊞ Windows」键）。

其实就是这个功能，，选择为ctrl按住取词时出现的，

重现步骤：
当我鼠标选中文字时，立即按ctrl+c（平时按的速度就是这样快），这个时候是不能复制到文字的，因为翻译弹窗已经出来了

**Comment by crimx** [comment]
沙拉查词 7 用的不同技术，这个问题将不会存在，你可以关掉这个功能。

**Comment by zhangdaren** [comment]
好的，谢谢~
