### ISSUE TITLE
搜狗翻译不行了

### ISSUE THREAD

**Issue by mogu1121** [crimx/ext-saladict#473]

**Comment by sylzh** [comment]
今天划词还是用不了搜狗，昨天也不行，前天是可以的；搜狗的网页翻译能打开

**Comment by crimx** [comment]
搜狗更新了 token 。这个 issue 已划到 Done ，请不必再反馈，等待更新。不习惯用 Github 的朋友也可以在公众号「柠檬反应堆」订阅动态。
