### ISSUE TITLE
好像在Javadoc上不能用

### ISSUE THREAD

**Issue by sidian123** [crimx/ext-saladict#474]
其他的都用划词翻译, 唯独Javadoc上不能用, 见[javadoc8](https://docs.oracle.com/javase/8/docs/api/)

**Comment by sidian123** [comment]
发现在package描述中不能使用, 其他的还好

**Comment by crimx** [comment]
请阅读[常见问题及答复](https://github.com/crimx/ext-saladict/wiki/Q&A#wiki-wrapper)。
