### ISSUE TITLE
WebDAV 同步配置 未知错误「unknown」

### ISSUE THREAD

**Issue by dodojava** [crimx/ext-saladict#475]
### Saladict 版本

6.33.7

### 平台

MacOS+Chrome 77.0.3865.90

### 类型

错误

### 重现方式

单词管理 > WebDAV 同步 配置界面
服务器地址：https://dav.jianguoyun.com/dav/WebDAV/
坚果云有该目录，并且在WebDAV同步点保存后，可以自动创建同步目录WebDAV>Saladict
随后提示“  未知错误 「unknown」。”

看了一下源码，同步文件名应该是 notebook.json， 自己建了一个这个文件后，再保存还是不行。

### 期待

正常同步就好了。

### 额外信息

出现错误的时候，F12 没任何信息更新。
坚果云的WebDAV配置没有问题，同时用的还有其它一些App，都是OK的。

**Comment by crimx** [comment]
服务器地址不应该是 `https://dav.jianguoyun.com/dav/` 吗

**Comment by dodojava** [comment]
我自己加了一层文件夹“WebDAV”，刚才在7.0.0版本用 https://dav.jianguoyun.com/dav/ 这个服务器地址又配置了一次，同样的效果：1. 本来没有Saladict根目录，点完“保存”按钮后，自动创建了（应该能说明服务器地址，用户名，密码配置正确）2. 依然弹出“未知错误 「unknown」“。 3. 坚果云自动创建出来的Saladict根目录中没有任何文件。

**Comment by crimx** [comment]
1. 要按照坚果云给的配置复制，不能自己修改。
2. 创建目录坚果云更新了策略，所以不成功。下个版本会更新。
3. 目前如果手动创建 Saladict 目录是可以同步成功的。
