### ISSUE TITLE
焦点在查词面板上，滑动滚轮，背后的页面在滚动

### ISSUE THREAD

**Issue by birbird** [crimx/ext-saladict#476]
### Saladict 版本
7.0.0

### 平台
Windows 10, Chrome 77.0.3865.90

感觉是没修彻底，之前是如果查词面板有滚动条，会优先滚动查词面板的内容，查词面板滚到底以后，就开始滚动背后的页面，这个问题已经修好了。

但是，如果查词面板没有滚动条，滑动滚轮就会滚动背后的页面，这个问题还存在。

**Comment by crimx** [comment]
浏览器的实现不支持这样的情况，既然没有滚动条为什么还要滚动呢。要阻止的话需要监听鼠标滑轮，比较浪费性能。

**Comment by crimx** [comment]
以前的问题是因为 iframe 的限制，见 #205 。如果有合适的解决方案欢迎重开 issue 。
