### ISSUE TITLE
打开本地pdf 无法划词翻译

### ISSUE THREAD

**Issue by zhuqysf** [crimx/ext-saladict#477]
请根据模板描述问题，以便别人理解、定位和解决问题。
请根据模板描述问题，以便别人理解、定位和解决问题。
请根据模板描述问题，以便别人理解、定位和解决问题。
-->

### Saladict 版本

Saladict 7.0.0

### 平台

火狐 69.0.1

### 类型

同一个本地pdf，之前在沙拉的pdf阅读器打开能使用划词翻译,之后关掉重新打开显示“内嵌面板不支持此类页面“

**Comment by crimx** [comment]
踩坑了，Firefox 的 API 跟 Chrome 有点不一样。我兼容一下。
