### ISSUE TITLE
7.0 的彩云小译不能用了？

### ISSUE THREAD

**Issue by sambodhi-cn** [crimx/ext-saladict#478]
如题，Chrome版的7.0，彩云小译不能用

**Comment by crimx** [comment]
Chrome 彩云小译没问题。

**Comment by sambodhi-cn** [comment]
> Chrome 彩云小译没问题。

似乎跟网络有关，某些线路，彩云小译没有任何结果，换流量后就有了

**Comment by crimx** [comment]
是彩云服务器的问题，你打开网页也会有这个问题。

**Comment by sambodhi-cn** [comment]
> 是彩云服务器的问题，你打开网页也会有这个问题。

明白，谢谢！
