### ISSUE TITLE
7.0中快速查词的弹窗默认位置是左上角，且设置中显示为0

### ISSUE THREAD

**Issue by Sraw** [crimx/ext-saladict#479]
### Saladict 版本

7.0

### 平台

Linux Chrome 77

### 类型

Bug

### 重现方式

设置中关于快速查词弹窗的默认值貌似是0，而不是一个有意义的字符串

### 期待

略

### 实际

略

**Comment by crimx** [comment]
嗯嗯，这个是设置兼容问题。如果你不在意的话可以重置设置。或者等我再发个版本修复一下。
