### ISSUE TITLE
今天9.30凌晨更新的剑桥词典查有些词，内容信息变少

### ISSUE THREAD

**Issue by LouisZhouzzz** [crimx/ext-saladict#480]
### 平台

chorme77

### 类型

9.29晚上我还在用剑桥词典，查词，比如disposal，解释里面有两块。
清除；处理；抛弃
和
at sb's disposal  可供...使用

结果到9.30凌晨更新后，再查disposal，更新后的剑桥词典
只能查到      清除；处理；抛弃，后面的at sb's disposal  可供...使用   没有了

**Comment by crimx** [comment]
这个区域有的结果上是一些无意义的内容，我以为都是这样就隐藏了。下个版本补回来。
