### ISSUE TITLE
鼠标悬浮取词 不能自动选词了

### ISSUE THREAD

**Issue by fish-rain** [crimx/ext-saladict#482]
### Saladict 版本

Saladict 版本 7.0

### 平台

chrome 

### 类型

之前鼠标悬浮取词，可以选取该词，就是在这个词的背景显示灰色，代表选中。新的悬浮取词没有这个功能了，这个选词功能可以代替双击选中，很好用，希望保留。

**Comment by crimx** [comment]
这本来是个 bug 来着……

**Comment by fish-rain** [comment]
> 这本来是个 bug 来着……

是个bug？？？能加个开关，保留吗？很多有链接的地方，不能双击选中，用这个功能可以选中。选中之后未必是划词，可以配合其他插件使用。

**Comment by crimx** [comment]
链接上选词可以按住 <kbd>Alt</kbd> 。

**Comment by crimx** [comment]
这本来是个 bug 是因为这个功能会干扰页面本身的划词。悬浮查词应该是安静无干扰的。

**Comment by fish-rain** [comment]
悬浮查词的使用一般和划词是分开的，这个bug反而有聚焦选词的作用。交互上你能感知他在选词，反馈更好。
