### ISSUE TITLE
安装的应用程序会内置一些.html网页，通过Chrome打开，发现Saladict不能够使用

### ISSUE THREAD

**Issue by githubxinshou** [crimx/ext-saladict#484]
### Saladict 版本
7.0.1 最新版本，刚刚更新的，还有那个潜在危胁我也出现了

### 平台
Google Chrome 已是最新版本 
 win 10系统
版本 77.0.3865.90（正式版本） （64 位）

### 类型

安装的应用程序会内置一些.html网页，然后通过Chrome打开，发现Saladict不能够使用，并且左上角的Saladict这个图标上有off这个提示
比如我打开：file:///C:/Program%20Files%20(x86)/Oticon/Genie/Genie2/Help/en-GB/Content/B_Fitting%20flow%20and%20tools/D_Fitting/Fine-tuning.htm

我看了您写的文档，有提到说是google因为安全问题或不再支持一些落后的技术，比如您文档中出现的下面两个，想问问我出现的这个问题是不是下面类似的原因？是我哪里没设置好，还是安全问题？还是您这里没有支持？

问: 谷歌办公 Google Doc 或 Google Play 上读书不能划词。
答: 谷歌在这些地方自行实现了一套选词机制，所以 Saladict 无法通过浏览器的接口获得选词。这个兼容起来有点工作量，作者本身也很少在这些地方划词，所以几乎是不会去实现了。有其他人提 PR 也是欢迎的。目前可以打开 Saladict 的独立查词窗口为侧边栏模式输入查询。

问：在 Java 类的文档中无法显示图标，如 Java, Spring。
答：这类文档使用了一种严重过时的技术 <frameset>，在现代网页中已不多见。因其技术限制，在页面内显示面板将非常麻烦，故不做支持。但可以启用独立窗口的沙拉查词面板。

**Comment by crimx** [comment]
让扩展浏览本地文档需要在 Chrome 扩展设置中开启允许权限。

**Comment by githubxinshou** [comment]
谢谢，哇，太好了，第一次发提问，然后作者迅速回复，谢谢您。

**Comment by crimx** [comment]
不客气！
