### ISSUE TITLE
独立窗口 使用问题

### ISSUE THREAD

**Issue by xinshangshangxin** [crimx/ext-saladict#485]
### Saladict 版本

7.0.1

### 平台

MacOS  10.14 
Google Chrome
Version 77.0.3865.90 (Official Build) (64-bit)

### 期待

快捷键激活 / 打开 独立窗口时, 自动替换 剪切板搜索词

### 实际

快捷键打开独立窗口时, 自动替换 剪切板搜索词, 但是 激活时, 依然显示上一次的搜索结果

### 额外信息

![image](https://user-images.githubusercontent.com/8779091/65855072-d6cbff80-e390-11e9-996c-b99b975534e7.png)

**Comment by crimx** [comment]
你好，你是指在独立窗口打开的情况下，按下快捷键加载剪贴板？

**Comment by xinshangshangxin** [comment]
是的

因为从文档[支持快捷键操作](https://github.com/crimx/ext-saladict/wiki#%E6%94%AF%E6%8C%81%E5%BF%AB%E6%8D%B7%E9%94%AE%E6%93%8D%E4%BD%9C)上
`在 Windows 平台可以结合 Quicker 调用 Saladict。` 这个是可以更新每次搜索选择的内容
但是 `另外还可以通过 WGestures 配置鼠标手势调用 Saladict。` 如果仅仅使用 快捷键的话, 不知道能否实现

**Comment by crimx** [comment]
这个功能可以考虑。

**Comment by xinshangshangxin** [comment]
关于 
`在 Windows 平台可以结合 Quicker 调用 Saladict。 这个是可以更新每次搜索选择的内容`

有详细技术细节, 是如何实现 `更新每次搜索选择的内容` 的吗?

**Comment by crimx** [comment]
因为我不用 Windows ，这个你得请教分享配置的作者。

另外这个功能 @elliottzheng 的 [CopyTranslator](https://github.com/CopyTranslator/CopyTranslator) 也有实现，你可以看看！😉
