### ISSUE TITLE
更新后不能使用了

### ISSUE THREAD

**Issue by ghndc** [crimx/ext-saladict#486]
### Saladict 版本

7.0.1

### 平台

win7 firefox60.0.1(64位)

### 类型

自动更新后不能使用 进入sala设置页面显示空白

### 额外信息

![图片](https://user-images.githubusercontent.com/55974227/65859818-99b93a80-e39b-11e9-950f-a46fdde3755d.png)
![图片](https://user-images.githubusercontent.com/55974227/65859836-a50c6600-e39b-11e9-83d0-acc757a4404e.png)

**Comment by crimx** [comment]
你的浏览器已经严重滞后了，火狐对扩展的支持改变了很多，请更新到最新版。

**Comment by ghndc** [comment]
反馈 更新火狐后已修复

**Comment by crimx** [comment]
赞
