### ISSUE TITLE
建议和bug

### ISSUE THREAD

**Issue by Aroman-RonCyan** [crimx/ext-saladict#487]
### Saladict 版本
最新

### 平台
QQ浏览器最新

### bug
独立窗口：
1、无法双击翻译；
2、无法按shift+左键双击翻译；
3、钉住没用，钉住了，也不能处在最顶部，设置如图

### 建议
1、添加截图识别，也能在独立窗口截其它应用的图识别（在邮箱跟你提过，不知道你有没有看到）
2、打开独立窗口，自动选中编辑框全部内容
3、查词记录以独立窗口的方式显示，并可以钉住

![批注 2019-09-30 170223](https://user-images.githubusercontent.com/18456044/65864373-58795880-e3a4-11e9-93c2-f3e109e186da.png)

**Comment by crimx** [comment]
你好

1. 独立窗口不能划词这个是忘了加载划词模块。
2. 同上。
3. 钉住不是保持最顶，这个浏览器不支持实现。钉住是划词时是否切换焦点到面板上。

建议

1. 请阅读[常见问题及答复](https://github.com/crimx/ext-saladict/wiki/Q&A#wiki-wrapper)。  
2. 单行输入框是没问题的，多行因为自动适应高度引入的组件有点问题，待修复。
3. 这个你可以把浏览器标签拉出来成独立窗口。

**Comment by Sraw** [comment]
我有相同的问题，按住某按键双击无法翻译了。望尽快修复。谢谢作者。

**Comment by charlesmz** [comment]
Saladict 版本
最新

平台
Opera浏览器

问题：
划词后，显示的图标被Opera 的 浮窗 挡住了
![批注 2019-10-02 112112](https://user-images.githubusercontent.com/32212601/66015850-c8075900-e506-11e9-85e0-a5a5f9f7c3ee.png)

**Comment by crimx** [comment]
@Sraw 这个问题已经解决了，请确认用的是新版。

@charlesmz Opera 不在我支持范围内。你可以看看能不能关闭掉这个浮窗，或者鼠标远点放开，或者用其它划词方式。

**Comment by Sraw** [comment]
可以了，谢谢作者。
