### ISSUE TITLE
能否增加扇贝收藏单词的功能

### ISSUE THREAD

**Issue by waihoyu** [crimx/ext-saladict#488]
本人在使用扇贝背单词，发现了一款扇贝的插件，可以把网页的词汇增加到扇贝生词本里，是否可以在沙拉里面也增加这样的功能呢？
https://chrome.google.com/webstore/detail/%E6%89%87%E8%B4%9D%E5%8A%A9%E6%89%8B%E5%A2%9E%E5%BC%BA%E7%89%88/aibonellgbdkldghjgbnapgjblebfkbl

**Comment by crimx** [comment]
先读读使用说明。

**Comment by waihoyu** [comment]
> 先读读使用说明。

你是指扇贝单词的同步功能吗？我知道你开了扇贝生词的同步功能，但是能不能直接鼠标右键的时候就弹出扇贝添加界面呢？而不是同步。
