### ISSUE TITLE
没有选中效果与独立窗口翻译多个词

### ISSUE THREAD

**Issue by OpenWaygate** [crimx/ext-saladict#491]
### Saladict 版本

7.0.4

### 平台

win 10, chrome 77

### 类型

错误

### 划词模式

[config-1569939402296.txt](https://github.com/crimx/ext-saladict/files/3676831/config-1569939402296.txt)

### 重现方式

1. 鼠标放在单词上按住alt, 以前此单词会有被鼠标划过的选中效果(底色会变), 现在没有任何视觉反馈.

2. 独立窗口模式时, 双击浏览器单词可以查词, 但这样只能查询一个词, 用鼠标划选多个单词没有反应.

**Comment by crimx** [comment]
1. Duplicate of #482
2. 请阅读使用说明<https://github.com/crimx/ext-saladict/wiki>设置划词模式。
