### ISSUE TITLE
划词选择的时间

### ISSUE THREAD

**Issue by axrdiv** [crimx/ext-saladict#492]
### Saladict 版本

7.0.4

### 平台

Opensuse 15.1
chromium 76.0

### 划词模式

划词翻译的弹出窗口有点太快，有时没有选完就弹出了搜索结果。
此时的弹出窗口往往会遮挡页面影响继续划词。
能否增加一个选项，当鼠标松开时才开始查询。

**Comment by crimx** [comment]
你是启用指「直接搜索」模式吗，是鼠标松开时才开始查询的。

**Comment by crimx** [comment]
请你提供完整可复现的步骤。

**Comment by axrdiv** [comment]
![reappeare](https://user-images.githubusercontent.com/10485290/65982477-0290d780-e4ae-11e9-8858-5450c5ede23a.gif)

在Google搜索页面里出现的这种问题。
设置是开启「直接搜索」选项

**Comment by crimx** [comment]
这个应该是因为你大范围选到其它 frame 了，正常选词应该没问题。

为了兼容触摸调整选词，目前是监听选词区域变化，没有按下鼠标就延时后触发。跨 frame 不能识别到鼠标按键所以延时触发了。

目前解决方式可能是要增加一个触摸模式开关。

**Comment by axrdiv** [comment]
好的 谢谢你！
