### ISSUE TITLE
pdf模式，快捷键冲突

### ISSUE THREAD

**Issue by L-Simmon** [crimx/ext-saladict#495]
### Saladict 版本

7.0.4

### 平台

win10
chrome 77.0.3865.90

### 类型

pdf模式，划词后面板弹出，再在该面板上输入 ‘r' 会触发pdf的快捷旋转键，导致pdf旋转。

### 重现方式

使用default.pdf，在此页面划词操作，再输入带'r'的单词即可复现。

### 期待

未出现划词面板时，pdf快捷键如 ’r‘ （旋转）能正常使用；
出现划词面板后，屏蔽pdf快捷键以免干扰。

### 实际

未处理快捷键冲突 。

**Comment by crimx** [comment]
Duplicate of #490
