### ISSUE TITLE
最新版7.0.4经常会失效

### ISSUE THREAD

**Issue by RudeTheJack** [crimx/ext-saladict#497]
我是习惯在放开鼠标之前按住选择的按键才显示词典面板，这更新之后不知道什么原因，经常失效，求大佬救命，之前从来没遇到过这种情况

**Comment by crimx** [comment]
Duplicate of #492

等待更新

**Comment by RudeTheJack** [comment]
> Duplicate of #492
> 
> 等待更新
OK了，谢谢！！！！
