### ISSUE TITLE
今天刚更新的，剑桥词典点英音发音又重复查询

### ISSUE THREAD

**Issue by LouisZhouzzz** [crimx/ext-saladict#498]
### 平台

chrome77

### 类型

今天刚更新的版本，我剑桥词典，设置的自动发音美音，每次自动发音后，我点播放英音，结果自动再查一次才发出英音，上个版本本来已经解决了没有问题，现在又这样了。

**Comment by crimx** [comment]
本次更新并没有涉及到这个，我有空看看什么原因吧。

**Comment by crimx** [comment]
没能复现。你把设置导出上传一下。

**Comment by LouisZhouzzz** [comment]
> 没能复现。你把设置导出上传一下。


[config-1570166800603.zip](https://github.com/crimx/ext-saladict/files/3689073/config-1570166800603.zip)

**Comment by crimx** [comment]
是因为开启了面板内直接查词，点击喇叭时输入框如果有选中词的话会触发搜索。我看看怎么兼容。

**Comment by LouisZhouzzz** [comment]
有点没有明白，我看了我的设置，不知道设置哪里，我一直都是在面板里面输入查词的，上个版本是没有问题的。

**Comment by crimx** [comment]
在「查词习惯」中。

7.0 开始是基于监听选词变化而触发查词，这是为了兼容触摸，但这个方式有许多缺陷（#497 #492 ），这个版本用回了鼠标按键监听，触摸模式需要手动开启。
