### ISSUE TITLE
不能同时开启独立窗口和页面内划词吗？

### ISSUE THREAD

**Issue by Royce17** [crimx/ext-saladict#501]
### Saladict 版本

7.1.0

### 平台

Windows 10 教育版 1903
Chrome 77.0.3865.90

### 类型

不能同时开启独立窗口和页面内划词。
打开独立窗口后就不能页内划词了。

### 期待

支持上述功能

### 实际

.

**Comment by crimx** [comment]
why

**Comment by Royce17** [comment]
> why

不知道，但就是这样。不能两个一起用，至少在我的电脑上是的。

**Comment by crimx** [comment]
你好，我是指为什么要这么做？有什么使用场景吗？

**Comment by Royce17** [comment]
三个原因吧
1. 独立窗口不会始终保持在最前，点击页面后，独立窗口会被移到下一级，要看到需要查的词，就必须再手动点击独立窗口了。
2. 有的时候需要做多词或多句对比翻译。
3. 有时想用独立窗口查自己想查的东西，页面划词查自己看到的。需要保持互不干涉。

**Comment by crimx** [comment]
试试「侧边栏模式」？不响应页面划词的情况下应该能显示两个面板，可能我重构的时候出了 bug ，有时间看看。

**Comment by Royce17** [comment]
能不能有一种「侧边栏模式」+ 「普通页面划词」或者「非侧边栏独立窗口」+ 「普通页面划词」的模式。

**Comment by crimx** [comment]
我回来测试了，关闭响应页面划词之后两个面板显示没问题啊？

**Comment by Royce17** [comment]
嗯嗯，我清空缓存然后重启两次之后也可以了。谢谢。
