### ISSUE TITLE
右上弹窗查词滚动条和关闭按钮无效

### ISSUE THREAD

**Issue by cc419378878** [crimx/ext-saladict#502]
### Saladict 版本
7.1.0
### 平台
linux chrome 77.0
### 类型

1.**右上弹窗** 设置为_显示查词面板_时，使用右上弹窗查词**滚动条**和**关闭按钮**是无效的
2.**查词习惯**普通查词和钉住后划词设置为_双击搜索_，右键也会触发查词，不清楚这是不是原本的预期功能

**Comment by crimx** [comment]
你好

1. 我在 Manjaro 下测试滚动没问题。关闭按钮这里不需要，但我看看支持一下或者 disable 掉。
2. 这个是重构 bug 。
