### ISSUE TITLE
Bug Report: FIrefox版沙拉查词右上弹框下拉后无法显示内容

### ISSUE THREAD

**Issue by maomaowei5655** [crimx/ext-saladict#503]
### Saladict 版本
7.1.0

### 平台
Macos Mojave，版本 10.14.5
Firefox Quantum，69.0.2 (64 位）

### 类型
右上弹框下拉后无法显示内容👇
![Bug](https://user-images.githubusercontent.com/51223743/66319093-137a9680-e94f-11e9-92eb-8c8d0696e894.gif)

**Comment by crimx** [comment]
Duplicate of #455
