### ISSUE TITLE
造成页面卡顿问题

### ISSUE THREAD

**Issue by Richard-zhao93** [crimx/ext-saladict#504]
### Saladict 版本

7.1.1

### 平台

Window 7 
Google  77.0.3865.90

### 类型

更新之后，弹出框如果有自动聚焦效果，沙拉会导致明显的卡顿效果。

**Comment by crimx** [comment]
看不懂你的描述

**Comment by Richard-zhao93** [comment]
17625222531@163.com
 
发件人： CRIMX
发送时间： 2019-10-09 09:51
收件人： crimx/ext-saladict
抄送： Richard; Author
主题： Re: [crimx/ext-saladict] 造成页面卡顿问题 (#504)
看不懂你的描述

**Comment by crimx** [comment]
?
