### ISSUE TITLE
扩展图标不明原因出现黄底白字的off

### ISSUE THREAD

**Issue by jerry011235** [crimx/ext-saladict#505]
### Saladict 版本
版本 7.1.1，扩展设置为默认设置。

### 平台
win10和win7，chrome版本 77.0.3865.90（正式版本） （64 位）
就沙拉查词一个扩展，无其他扩展。

### 类型
扩展图标，不明原因出现黄底白字的off，如图：
![66134072-4ad50480-e62a-11e9-8db5-3c255b92b44b](https://user-images.githubusercontent.com/12509976/66462578-fd371c80-eaad-11e9-8e6c-2503564d88c9.png)

### 重现方式
打开chrome://extensions/，chrome://settings/ 等100%出现下图样式，打开百度首页和新标签页 偶然出现。另外有时打开网页瞬间 图标右下角会有“off”字样，一会儿又没有了。
隐身模式下 新标签页 100%出现。

已仔细阅读：
https://github.com/crimx/ext-saladict/wiki#wiki-content
https://github.com/crimx/ext-saladict/wiki/Q&A
可惜并没有找到 出现此图标样式的原因。
只是发现在Saladict 设置，基本选项中，启用划词翻译，关闭后，会出现 红底白字的 off 字样。

### 期待
希望在wiki中添加出现此图标的原因 以及调试和解决办法。
建议：加一个选项，显示/隐藏通知off。
对于强迫症来说，图标无任何通知，看起来很舒服；对于普通用户来说，不需要调试，只需要能正常使用。

### 额外信息
扩展设置为 右上弹框，有道网页翻译，打开百度首页，出现 黄底白字的off，左键单击 扩展图标，出现如图情况（可能要多次单击）：
![111](https://user-images.githubusercontent.com/12509976/66463624-0aeda180-eab0-11e9-8ea2-c9830adf87b5.png)

点击后的console:
```
VM100 main.js:5 Uncaught Error: Existed CDA iFrame element
    at VM98 main.js:5
    at init.createMessageChannel (VM98 main.js:5)
    at new init (VM98 main.js:5)
    at Object.b [as CDA] (VM98 main.js:5)
    at new a.TR.UI (VM98 main.js:5)
    at VM98 main.js:5
    at VM98 main.js:5
    at VM98 main.js:8
```

**Comment by crimx** [comment]
你把鼠标放上去就可以看到原因。

**Comment by jerry011235** [comment]
谢谢，显示的是 内嵌面板不支持此类页面(独立窗口页面依然可用)，可以访问此网站。

**Comment by crimx** [comment]
对的

**Comment by crimx** [comment]
隐身模式下你要允许沙拉查词才能加载内嵌面板。

**Comment by jerry011235** [comment]
怎么解决呢？目的是 让图标恢复成下图样子。
![image](https://user-images.githubusercontent.com/12509976/66464949-83edf880-eab2-11e9-972f-9711f215cd0b.png)

另外在 chrome://settings/ ，出现 黄底白字的off，多次左键单击 扩展图标，出现上述错误通知。

在隐身模式下启用 开了的，实际上 下面的几个都开了，还是出现黄底白字的off

**Comment by crimx** [comment]
我补充了[说明](https://github.com/crimx/ext-saladict/wiki/Q&A#%E9%97%AE%E4%B8%BA%E4%BB%80%E4%B9%88%E5%9C%B0%E5%9D%80%E6%A0%8F%E6%97%81%E7%9A%84%E6%B2%99%E6%8B%89%E6%9F%A5%E8%AF%8D%E5%9B%BE%E6%A0%87%E6%9C%89%E6%97%B6%E4%BC%9A%E5%87%BA%E7%8E%B0%E9%BB%84%E5%BA%95%E7%99%BD%E5%AD%97%E7%9A%84off%E6%8F%90%E7%A4%BA)。

**Comment by jerry011235** [comment]
谢谢，自动识别是能自动识别，但此问题是：自动识别出 不能加载内嵌面板的页面 后，能否**不显示**黄底白字的“off”，或者**加一个选项**，这个有计划做吗？

**Comment by crimx** [comment]
暂时没有这个计划

**Comment by jerry011235** [comment]
好的，可以关闭此 issue

**Comment by jerry011235** [comment]
自己解决了。好吧，我承认自己是强迫症 ：）
到扩展文件夹 `……\cdonnmffkdaoajfknoeeecmchibpmkmg\7.1.1_0\assets`
打开 `background.4d347848.js` 文件，
查找 `unsupported: !0 `改成 `unsupported: !1` 即可。

也可修改源代码 https://github.com/crimx/ext-saladict/blob/5ddd49af9cdd0e2ecbcd06baeb1d7bbf6c67d694/src/background/badge.ts#L22
`true`改成 `false`，然后自己[build](https://github.com/crimx/ext-saladict/blob/dev/CONTRIBUTING.md)即可。
