### ISSUE TITLE
gmail邮件中PDF文件下载不了。被插件拦截了

### ISSUE THREAD

**Issue by iqpkeq** [crimx/ext-saladict#508]
#20 # Saladict 版本

7.1.1

### 平台

win10,chrome64位 77

### 类型

开启插件后，在gmail邮件中，点附件的下载PDF，下载不了，拦截了

### 期待

点下载，应该能正常下载

### 实际

拦截了下载动作

**Comment by crimx** [comment]
第一次安装不是提供了注意事项么。
请阅读使用说明<https://github.com/crimx/ext-saladict/wiki>。
