### ISSUE TITLE
【建议】关于划词取词，会划取到查词面板

### ISSUE THREAD

**Issue by Beating-flies** [crimx/ext-saladict#510]
### Saladict 版本

7.1.0

### 平台

win10 1903 / chrome 77.0.3865.90

### 类型

建议

### 划词模式

直接搜索，鼠标悬停取词-直接取词

![saladict](https://user-images.githubusercontent.com/56392161/66565915-3b0f7000-eb96-11e9-8d77-c8ea4aed790d.PNG)

### 重现方式

按下鼠标，移动鼠标光标到查词面板。
![saladict](https://user-images.githubusercontent.com/56392161/66565953-4ebad680-eb96-11e9-9ada-27521877f156.gif)

### 期待

在我按下鼠标时，查词面板会躲避我的鼠标光标。

### 实际

尊敬的saladict作者：
您好！

我正在学习英语，发现saladict扩展。它很不错，可以帮助我浏览英语网站。

我开启了直接搜索（划词取词），和悬浮取词。在我想查一个词组时，取词面板已打开。光标会滑动到查词面板上。影响查词。

希望查词面板可以被我调节，离光标远一些。或在我按下鼠标时，查词面板会移动，和光标保持距离，这样的话，我能查询句子了。

最后，向你表示感谢。

### 额外信息

无

**Comment by crimx** [comment]
你好，首先非常感谢你清晰的描述。

我认为你的问题主要在于在「普通划词模式」下开启了「悬浮划词」。一般来说，「普通划词模式」下开启「悬浮划词」应该结合同时按下按键激活，或者结合快捷键开启关闭。不知道你直接开启的动机是什么？不会经常误触么？

**Comment by Beating-flies** [comment]
因为我的英语水平差，词汇量少，看整篇英语文章，不认识的词有很多。

哪个单词不会，就把鼠标指针放在上面查词。查一个词时，「悬浮划词」就可以了。查词组、句子时，需要用「普通划词」。见一个词按一下键盘，感觉繁琐。

在我不用词典时，会关闭取词功能的。

**Comment by crimx** [comment]
这样我建议你用独立窗口侧边栏模式

**Comment by Beating-flies** [comment]
这只是个建议，我认为，这可以使扩展更好用。

我个人使用「扩展程序-键盘快捷键-鼠标悬浮取词开关」解决问题。

**Comment by crimx** [comment]
> 这只是个建议，我认为，这可以使扩展更好用。
> 
> 我个人使用「扩展程序-键盘快捷键-鼠标悬浮取词开关」解决问题。

谢谢你的建议，但我不希望为一个边缘的情况将实现复杂化。我认为「直接划词」与「悬浮查词」这两个功能都按照各自的设计正常地运作。对于大量查词的情况也提供了侧边栏模式，普通的独立窗口也能解决这个问题，顺应沙拉查词的设计去使用会更轻松些。

**Comment by Beating-flies** [comment]
没关系。我不是程序员，不知道编程的复杂。

saladict，可以说是我目前发现最好用的划词扩展。

总之，对你的回答和作品表示感谢。

**Comment by crimx** [comment]
哈哈，你的反馈非常清晰有条理，比许多程序员好多啦。
