### ISSUE TITLE
Bug Report: FIrefox版本打开本地 pdf 显示空白

### ISSUE THREAD

**Issue by rachpt** [crimx/ext-saladict#511]
### Saladict 版本

7.1.1

### 平台

Linux Manjaro 64 bits   
Firefox Quantum 69.0.1 64 bits

### 类型

已经打开的本地pdf  右键  `沙拉查词` -->  `在pdf阅读器中打开`，显示空白页面(非default.pdf)

### 实际

在 default.pdf 中自己定位本地文件则能正常打开翻译，但是刷新页面又变成 default.pdf

也就是说 地址栏的 链接不可复用，只能手动 `open local pdf`
### 额外信息

附上 地址处链接
```
moz-extension://a7f28fea-0851-414d-8856-edecc2e165a3/assets/pdf/web/viewer.html?file=file%3A%2F%2F%2Fhome%2Frachpt%2FDesktop%2FLiteratures%2FQprop%2FPhysRevLett.121.053401.pdf
手动  open local pdf 和上面一样
```

[![u7aADe.png](https://s2.ax1x.com/2019/10/10/u7aADe.png)](https://imgchr.com/i/u7aADe)
[![u7aEHH.png](https://s2.ax1x.com/2019/10/10/u7aEHH.png)](https://imgchr.com/i/u7aEHH)

**Comment by crimx** [comment]
Firefox 不支持本地链接
