### ISSUE TITLE
更新后剑桥词典直接展开还是会重复查询

### ISSUE THREAD

**Issue by LouisZhouzzz** [crimx/ext-saladict#513]
更新后剑桥词典直接展开还是会重复查询
现在是等个一秒后点展开可能正常，也可能还是重复查询，快速直接点还是重复查询比如girl，
inform

### 平台

chrome77

**Comment by LouisZhouzzz** [comment]
这是设置
[config-1570940048575.zip](https://github.com/crimx/ext-saladict/files/3721419/config-1570940048575.zip)

**Comment by crimx** [comment]
嗯……先不按那个箭头，按箭头左右的位置。
