### ISSUE TITLE
Saladict沙拉查詞 搜狗 不支援

### ISSUE THREAD

**Issue by eye987tw** [crimx/ext-saladict#518]
Saladict沙拉查詞 搜狗 不支援
希望能支援搜狗一下

**Comment by crimx** [comment]
搜狗翻译没有问题。

**Comment by drcege** [comment]
我的也是，翻译不能用了

**Comment by crimx** [comment]
我使用没有发现问题。反馈请按照模板走一遍，并打开搜狗网页看看能不能翻译。

**Comment by drcege** [comment]
我刚刚尝试把搜狗翻译里的 “目标语言” 改为 “简体中文”，然后就可以了，再改回 “随扩展语言” ，依然可以了

以前一直是 “随扩展语言”，不知道是不是多次更新导致的缓存bug

**Comment by crimx** [comment]
应该是没有打开过搜狗网页，现在好像要验证 cookies 。

**Comment by drcege** [comment]
哦，可能是，我也尝试打开搜狗翻译网页了
