### ISSUE TITLE
建议:关于在Saladict查词框中继续划词翻译

### ISSUE THREAD

**Issue by hdchieh** [crimx/ext-saladict#52]
chrome中这个划词翻译非常好用.
有一点建议,关于在saladict弹出的查词框中继续划词翻译.
目前的情况是会跳转查询单词,希望可以弹出新的查词框,或者可以后退.

**Comment by crimx** [comment]
双击单词即可，点击查词记录图标可以查看历史记录。

**Comment by hdchieh** [comment]
我的意思是,在沙拉查词面板再次查词的话不会弹出新的查词框而是在当前查词面板显示新词.
所以觉得如果会弹出新的查词框或者有后退按钮会不会更好.(～﹃～)~zZ

**Comment by crimx** [comment]
为什么要弹出新的查词框呢？这让我想起了以前 Windows 无限弹窗 bug 还有指纸牌游戏胜利的界面 :smile: 。

能查看全部历史也就可以代替后退按钮了。

**Comment by hdchieh** [comment]
好吧...谢谢..

**Comment by crimx** [comment]
嗯嗯，这个 issue 先 close 了。如果有更具说服力的使用场景欢迎提出。
