### ISSUE TITLE
【建议】目前沙拉查词不支持本地网页

### ISSUE THREAD

**Issue by AnyinSong** [crimx/ext-saladict#520]
**请描述目前使用沙拉查词遇到什么不便**

从Chrome浏览本地网页，如下载的网页版帮助文档时，沙拉查词是off状态

**理想情况下，沙拉查词应该怎么做**

本地网页也能使用沙拉查词

**替代方案**

**额外信息**

**Comment by crimx** [comment]
https://github.com/crimx/ext-saladict/wiki/Instructions
