### ISSUE TITLE
能否支持Android设备上的firefox？

### ISSUE THREAD

**Issue by leiminghany** [crimx/ext-saladict#523]
**请描述目前使用沙拉查词遇到什么不便**

在Firefox on Android浏览器上， 插件可以成功安装，能成功设置及显示窗口，但是查询单词时卡住了查不出来。

![570572068](https://user-images.githubusercontent.com/4607445/67155576-ac90b080-f344-11e9-8f67-371bf3004ba7.jpg)

**理想情况下，沙拉查词应该怎么做**
正常显示出翻译结果

**替代方案**
无

**额外信息**
无

**Comment by crimx** [comment]
请按模板清晰描述你的问题。

**Comment by leiminghany** [comment]
上面是手机上截屏，下面这个是在平板上的截图
![Screenshot_2019-10-20-14-42-31-039_org mozilla firefox](https://user-images.githubusercontent.com/4607445/67155807-650c2380-f348-11e9-9bd6-c1b1d75eab5b.png)

**Comment by crimx** [comment]
> 在Firefox on Android浏览器上， 插件可以成功安装

你是怎么安装的，火狐商店页面已经标记了不支持 Android 。

> 查询单词时卡住了查不出来。

看了一下，火狐 debug Android 扩展比较麻烦，我没有兴趣折腾了。如果有人找到原因或者提供 PR 十分欢迎。
