### ISSUE TITLE
导出的txt文档导入anki时不正确

### ISSUE THREAD

**Issue by yllgl** [crimx/ext-saladict#524]
具体原因是导出的txt文档包括翻译，而翻译内容由于有多个引擎的结果，中间用换行符分隔，而换行符是anki中每个单词的默认分隔符，导致anki识别错误。

建议：导出的txt文档中换行符用< br >替换，这样可在anki中勾选“允许字段中使用HTML"解决。

**Comment by crimx** [comment]
更新到最新版
