### ISSUE TITLE
生词本中 来自沙拉面板中的单词，翻译为空

### ISSUE THREAD

**Issue by riverOcea** [crimx/ext-saladict#525]
**请描述目前使用沙拉查词遇到什么不便**

生词本页面，来源为来自沙拉面板中的单词，翻译为空，翻译是抓取的上下文吗
因为一句话有时候某个单词会单独划词，看单词意思然后添加到生词本，但是导出的时候发现翻译为空

**理想情况下，沙拉查词应该怎么做**

希望能把面板划词的上下文也抓取

**替代方案**

**额外信息**

另外所有的“笔记”那一栏也是空的，不知道是抓取的什么字段呢，可能是我不会设置，
另外翻译是抓取的谷歌翻译吧 更喜欢有道词典的翻译，可以设置抓取哪个翻译吗

**Comment by crimx** [comment]
> 生词本页面，来源为来自沙拉面板中的单词，翻译为空，翻译是抓取的上下文吗

是的，且不应该为空。检查网络问题。否则请提供可复现的步骤。

> 另外所有的“笔记”那一栏也是空的，不知道是抓取的什么字段呢，可能是我不会设置，

顾名思义，笔记需要自己填。

> 另外翻译是抓取的谷歌翻译吧 更喜欢有道词典的翻译，可以设置抓取哪个翻译吗

查看设置，反馈模板提醒了要阅读使用说明。

**Comment by riverOcea** [comment]
谢谢
来自沙拉面板中的单词，翻译现在有值了
