### ISSUE TITLE
自定义查词面板样式没有效果

### ISSUE THREAD

**Issue by bmxbmx3** [crimx/ext-saladict#526]
## 设备信息
 - 操作系统: win10
 - 浏览器版本: chrome77.0.3865.120
 - 沙拉查词版本: 7.3.2

## 描述问题

我在自定义查词面板样式定义了如下css代码：
```
.dictPanel-Root{
    position:relative;
    top:100px;
    right:100px;
    width: 300px;
    height: 60%;
}
```
但是面板没有什么变化，不知道什么原因

**Comment by crimx** [comment]
你可以通过 devtools 查看层级权值。

**Comment by bmxbmx3** [comment]
是弹出面板时查看devtools的变化吗？

**Comment by crimx** [comment]
就是普通的 inspect 元素即可查看。

**Comment by crimx** [comment]
如果对 CSS 不熟悉不建议捣腾，可能会导致显示异常。

**Comment by bmxbmx3** [comment]
我用开发者工具查看了对应的style，按[w3schools](https://www.w3schools.com/css/css_attribute_selectors.asp)设置css样式为：
```
div[class="dictPanel-Root saladict-panel"]{
    background-color: rgb(255, 255, 255);
    color: rgb(51, 51, 51);
    --color-brand: #5caf9e;
    --color-background: #fff;
    --color-rgb-background: 255, 255, 255;
    --color-font: #400;
    --color-divider: #ddd;
    left: 400px;
    top: 400px;
    z-index: 2147483647;
    width: 400px;
    height: 400px;
    --panel-width: 400px;
    --panel-max-height: 432px;
}
```
我试着更改了left,top等属性，为什么还是没有效果？在开发者工具里直接改效果会有改变，但是放到自定义面板样式里就不行了。我想在鼠标点击单词时面板出现的位置离鼠标远一点，因为沙拉查词的面板总是挡住了我diigo弹出的用于注释的面板，所以想自定义css样式。

**Comment by crimx** [comment]
这个不能这么改，因为坐标是程序设置的。

**Comment by crimx** [comment]
你可以换其它划词方式

**Comment by cooper1x** [comment]
@bmxbmx3 这个自定义在哪里呢，我没有找到
