### ISSUE TITLE
谷歌翻译音频无法播放

### ISSUE THREAD

**Issue by d1101** [crimx/ext-saladict#528]
## 设备信息
 - 操作系统: Window10
 - 浏览器版本: Chrome77.0.3865.120
 - 沙拉查词版本: 7.3.2

## 描述问题

无论是读原词，还是翻译结果，无论是google.cn还是.com，音频都无法播放
用其他翻译（有道词典）可以正常播放

**Comment by d1101** [comment]
## 复现步骤
- 划词翻译：获得谷歌翻译结果
- 点击谷歌翻译播放音频按钮：有按钮动画，无声音，无波形图

**Comment by xuing** [comment]
同样问题~
