### ISSUE TITLE
翻译日语的时候会翻译成英文

### ISSUE THREAD

**Issue by pspas** [crimx/ext-saladict#530]
翻译日语的时候会翻译成英文，即使将目标语言手动改为中文也会自动变回英文。

**Comment by crimx** [comment]
在词典设置中设置目标语言。

**Comment by pspas** [comment]
像是这句话会翻译成英语：今の若者は親から大事に扱われ
而其他句子像是这句话没有问题：その強さ、性質、明瞭性などはしだいに弱まります。
