### ISSUE TITLE
在CSDN的博客中,划词翻译的没办法用的

### ISSUE THREAD

**Issue by QingFengEmperor** [crimx/ext-saladict#532]
在CSDN 的其他区域都是没问题的,唯独在博客中是无法用的,划词后没有任何反应
以下:
https://blog.csdn.net/hellozpc/article/details/80878563
Chrome 版本 77.0.3865.120（正式版本） （64 位）
沙拉查词 版本7.3.2
安装途径 Chrome网上应用商店

**Comment by crimx** [comment]
这是因为 CSDN 取消了鼠标事件，这个已经修复了，等下个版本吧。
