### ISSUE TITLE
關於在Kiwi部分字典(滬江小D和騰訊翻譯)無法顯示結果的問題

### ISSUE THREAD

**Issue by Yusei-StarDust** [crimx/ext-saladict#534]
## 设备信息
 - 操作系统: Android 6.0.1
 - 浏览器版本: Kiwi Browser Quadea
 - 沙拉查词版本: 7.3.2

## 描述问题
不知道為什麼部分字典結果在Kiwi上無法顯示，如滬江小D(沒有顯示任何內容)、騰訊翻譯(顯示句號。。。。)都無法正確顯示查詢結果，我也沒有其他手機可以測試是只有我一個人這樣還是有其他人也這樣……

**Comment by crimx** [comment]
Android 不在沙拉查词支持范围。
