### ISSUE TITLE
划词小图标希望能自定义位置

### ISSUE THREAD

**Issue by ziiyoos** [crimx/ext-saladict#535]
第一次用真的是被惊艳到了，忍不住打赏了一波，就提一个小小的建议：
划词后的小图标目前是固定在鼠标右上方显示，但个人更习惯在右下方点击，暂时没找到能够设置的地方，希望作者有时间能加上吧

**Comment by crimx** [comment]
谢谢你的支持！

因为这个还会涉及到面板的位置，计算起来有点复杂我有空再理清这个逻辑。

**Comment by xuing** [comment]
还有就是，如果弹出的面板可以设置在划词的上面显示就更好了。就是不遮挡到划的词以及下面的词。我觉可以顺便考虑一下这个feature，非常感谢。不过这样面板的内容，就不能设置太多了23333。我可能还没能想清楚。

**Comment by crimx** [comment]
@xuing 请不要搭楼反馈新主题。反馈前阅读[使用说明](https://github.com/crimx/ext-saladict/wiki)。了解独立窗口以及侧边栏模式。

**Comment by xuing** [comment]
> @xuing 请不要搭楼反馈新主题。反馈前阅读[使用说明](https://github.com/crimx/ext-saladict/wiki)。了解独立窗口以及侧边栏模式。

ok
