### ISSUE TITLE
Error occurred while running `yarn install`

### ISSUE THREAD

**Issue by OrcaXS** [crimx/ext-saladict#536]
## Device info
 - OS: macOS 
 - Browser Version: N/A
 - Saladict Version: https://github.com/crimx/ext-saladict/commit/97d2af25381f147f94d477af2c9abc85119dfd1c

## Describe the bug
`yarn install` fails and reports
```
error An unexpected error occurred: "https://registry.yarnpkg.com/@opentranslate/baidu/-/baidu-1.0.4.tgz: Request failed \"404 Not Found\"".
```

## To Reproduce
1. Clone the repo and run `yarn install`.

## Expected behavior
1. `yarn install` should exit without errors.

**Comment by Spiderixius** [comment]
Hey. This issue occurs because the @opentranslate/ are not in `npm` so far only /languages and /translator is in npm.

**Comment by crimx** [comment]
Sorry we are still testing on OpenTranslate which is not production ready.

**Comment by crimx** [comment]
fixed
