### ISSUE TITLE
开启“默认用本扩展浏览 PDF”这个选项后，PDF文件划词翻译不正常

### ISSUE THREAD

**Issue by hobbitmr** [crimx/ext-saladict#543]
设备信息
操作系统: Window10
浏览器版本: Chrome77
沙拉查词版本: <!--v7.4.0
描述问题
沙拉查词开启了“默认用本扩展浏览 PDF”这个选项之后，用浏览器打开PDF文件，复制PDF上的文本内容，空白分隔符被自动过滤掉了。这个就导致了划词翻译的时候，单词都凑在一起了。

复现步骤
1.首先开启沙拉查词中“默认用本扩展浏览 PDF”这个选项
2.随便打开一个pdf文件，比如：http://ilpubs.stanford.edu:8090/422/1/1999-66.pdf

3.然后复制一段文字，用于查词。发现单词与单词之间的空白间隔符被自动过滤掉了。
4.然后我复制这段文字到文本中，也是一个样。
5.然后我关闭了“默认用本扩展浏览 PDF”这个选项，就恢复了正常。

期待的正常行为
正常逻辑应该是 划词或者复制之后，应该要能保留空白间隔符才对。

截图
开启了“默认用本扩展浏览 PDF”这个选项的表现

![异常显示](https://user-images.githubusercontent.com/18525259/67829922-cdf75680-fb13-11e9-8dda-812e2af17015.png)
![异常显示](https://user-images.githubusercontent.com/18525259/67829925-cfc11a00-fb13-11e9-9227-24f162191b6e.png)

关闭了“默认用本扩展浏览 PDF”这个选项的表现
![微信截图_20191030124435](https://user-images.githubusercontent.com/18525259/67829980-00a14f00-fb14-11e9-950a-ab8bf71e2575.png)

**Comment by crimx** [comment]
沙拉查词使用的是 [PDF.js](https://github.com/mozilla/pdf.js) 阅读器，你可以前往该项目反馈。

可以提供出问题的 pdf 文件给他们测试。

**Comment by PYGC** [comment]
这的确不是扩展的问题，你没发现你选中的内容之中就没有空格吗，我觉得是和 PDF 有关

**Comment by crimx** [comment]
这肯定书与 PDF 文件本身有关。但也不能说是 PDF 文件的问题或者是 PDF.js 的问题。因为 PDF 的设计就不是用来划词的（即不保留语义）。但如果其它 PDF 阅读器能在这个文件上做到保留语义，那说明 PDF.js 还有改进的空间。

**Comment by crimx** [comment]
现在推荐使用本地的 PDF 阅读器配合浏览器外划词。这个 issue close 了。
