### ISSUE TITLE
关于直接从 Saladict 窗口输入的文本分段问题

### ISSUE THREAD

**Issue by hqyyqh** [crimx/ext-saladict#544]
## 请描述目前使用沙拉查词遇到什么不便

从**外部**输入 Saladict 有两个位置，如下

![_20191030031353_compress](https://user-images.githubusercontent.com/38676455/67836756-64ce0e00-fb28-11e9-93f9-bb46d60b0aa5.jpg)

- 从 ① 位置输入会直接删除掉所有的换行
- 从 ② 位置输入则保留原文本的格式

**问题**：该问题的提出源于使用 Quicker 调用 Saladict，调用过程为**唤出独立窗口后，，Ctrl+V 粘贴到 ①  位置的输入框**，因此如果在通过这样的方式在浏览器外翻译一列较长的文本，就会直接变成一行而难以阅读。

**截图示例**：比如一列带有分段的文本

>精选大量词典，手工打磨排版，涵盖几乎所有领域
自动发音，可选不同词典、英美音
各个词典支持个性化调整
支持整个网页翻译，谷歌和有道分级网页翻译
右键支持更多词典页面直达

## 两种**外部方式输入**翻译效果如下：
![_20191030032228_horizontal_compress](https://user-images.githubusercontent.com/38676455/67837075-2edd5980-fb29-11e9-997d-8fff0cd89844.png)

## 但是如果直接从**浏览器内划词翻译**的效果是带有分段的
![_20191030032501_compress](https://user-images.githubusercontent.com/38676455/67837220-8380d480-fb29-11e9-8cc5-7505e4c571ee.jpg)

## 理想情况下，沙拉查词应该怎么做

核心问题是能否让 Quicker 调用 Saladict 时，输入的文本**保持带有分段的原格式**

## 替代方案或者建议

1. 增加一个**唤出独立窗口时默认展开 ② 位置**进行输入的快捷键设置
2. 可以在设置中切换 从 **① 位置中输入的文本需不需要经过去换行处理**

**Comment by crimx** [comment]
感谢反馈，这个是 bug

**Comment by crimx** [comment]
发现不是沙拉查词的 bug。

多行查词框默认展开是可以设置的。沙拉查词其实已经支持直接搜索剪贴板，已通知 Quicker 动作作者更新，你会的话也可以自行调整。

**Comment by hqyyqh** [comment]
感谢提醒，我的动作更新了，换到了【在独立窗口中搜索剪贴板内容】快捷键完美解决。

**Comment by crimx** [comment]
才发现原来也是你啊😂
