### ISSUE TITLE
Custom dictionaries

### ISSUE THREAD

**Issue by Sagitee** [crimx/ext-saladict#545]
Thank you for your really great addon.

How much feasible-possible might be a Saladict option for custom dictionaries addition by the users, with the use of some basic parameters, like some other, mainly searching addons do? (like https://addons.mozilla.org/en-GB/firefox/addon/contextsearch-web-ext/ or https://addons.mozilla.org/en-GB/firefox/addon/contextual-search/)

![191030_115120_capture_001](https://user-images.githubusercontent.com/50146787/67850240-ad79cd00-fb10-11e9-9382-80ebd676a376.jpg)

![191030_115347_capture_002](https://user-images.githubusercontent.com/50146787/67850250-b66a9e80-fb10-11e9-9883-af96c1b57e77.jpg)

**Comment by crimx** [comment]
Hi, thanks for the advice. Adding custom dictionary may seem fancy but I doubt the usefulness of this feature.

This approach often introduces iframes. With the unique design of Saladict, rendering multiple iframes at the same time would slow down performance drastically. 

Also simple embedded webpages are often not ideal, which requires extra styling. This is not something that the majority of users can do.

The goal of Saladict is to help people understand words better and faster by viewing multiple sources at the same time. If you have the ability and responsibility to maintain a dictionary source, follow the contribution guide and open a PR.
