### ISSUE TITLE
单词查询框大小建议

### ISSUE THREAD

**Issue by waynelw** [crimx/ext-saladict#547]
**请描述目前使用沙拉查词遇到什么不便**

单词查询的弹出框所占面积太大

**理想情况下，沙拉查词应该怎么做**

希望可以像普通应用边框一样，可以手动调节查询边框大小

**替代方案**

**额外信息**

**Comment by crimx** [comment]
设置里调，反馈前请阅读使用说明<https://github.com/crimx/ext-saladict/wiki>。
