### ISSUE TITLE
PDF阅读器变为英文版本

### ISSUE THREAD

**Issue by 1160300208** [crimx/ext-saladict#548]
## 设备信息
 - 操作系统:  Windows 10 OS Version 1903 (Build 18362.418)
 - 浏览器版本: Chrome 78.0.3904.70 (正式版本) （64 位） (cohort: 78_70_Win)
 - 沙拉查词版本: v7.4.0

## 描述问题

使用沙拉查词打开PDF时，PDF阅读器为英文版本

## 复现步骤

1. 打开沙拉查词的 **PDF 设置**
2. 开启 **默认用本扩展浏览 PDF** 选项
3. 打开任意一个合法的PDF文件
4. 问题出现

## 期待的正常行为

PDF阅读器为中文版本

## 截图

![image](https://user-images.githubusercontent.com/34236718/67960520-5faab500-fc35-11e9-819e-55a82175c9d4.png)
![image](https://user-images.githubusercontent.com/34236718/67960586-794bfc80-fc35-11e9-8a8f-64432678fc90.png)

## 额外信息

之前一直是好用的，显示的是中文版本，最近才发现这个问题，没研究过 [pdf.js](https://github.com/mozilla/pdf.js)，可能是调用出了问题吧

**Comment by crimx** [comment]
应该是我精简语言的时候去掉了什么文件，有空排查一下。
