### ISSUE TITLE
只剩查词面板打开时，新开浏览器窗口的窗口大小会跟查词面板一样大

### ISSUE THREAD

**Issue by RemRemRemRe** [crimx/ext-saladict#549]
## 设备信息
 - 操作系统: Window10 
 - 浏览器版本: FireFox 70.1
 - 沙拉查词版本: 7.4.0

## 描述问题

只剩查词面板打开时，新开浏览器窗口的窗口大小会跟查词面板一样大:

这让我不得不重新缩放窗口，以正确浏览网页。

## 复现步骤

1.连按三次ctrl呼出查词面板
2.关闭其它打开的标签页，直至FireFox只剩查词面板窗口
3.从任务栏图标右键→Firefox,打开窗口时，窗口大小强制跟查词面板一样大小。

## 期待的正常行为

查词面板的大小不会影响到标签页窗口的大小。

## 额外信息

顺便说一下:
沙拉查词是我用过的最牛逼的查词软件/插件
开发大大牛逼，感谢开发者！

**Comment by crimx** [comment]
这个是 Firefox 的逻辑，不受扩展控制。

你可以新建一个 Firefox 的快捷方式[通过参数指定大小](http://kb.mozillazine.org/Command_line_arguments)，如 `-width 400 -height 600` 。

**Comment by RemRemRemRe** [comment]
Firefox有没有什么选项可以改变这个逻辑？
比如：bSaveWindowSize = false;
设置下某标志位，火狐就不会自动保存最后关闭的窗口大小了。

或者我去给火狐提个issue？😂

**Comment by crimx** [comment]
理论上沙拉查词可以记录打开的窗口，然后判断相应的情况恢复大小。但这个更像是 Firefox 的 bug，可以提 issue 看他们愿意改进不。

**Comment by RemRemRemRe** [comment]
我觉得你不用记录，而是让插件的窗口，开启一个特殊的标志位，让它的大小**不记录**到**已打开窗口大小**里去。

当然前提是火狐提供了这个选项。不然麻烦很多

**Comment by crimx** [comment]
`popup` window 的大小不应该作为新打开 window 的参考。

**Comment by crimx** [comment]
没有这样的接口。

**Comment by RemRemRemRe** [comment]
> 
> 
> `popup` window 的大小不应该作为新打开 window 的参考。

对，是这个意思
