### ISSUE TITLE
能否添加一个"关闭更新通知"的选项

### ISSUE THREAD

**Issue by yonjar** [crimx/ext-saladict#552]
**请描述目前使用沙拉查词遇到什么不便**

每当扩展更新后，打开浏览器后就会出现一个包含更新信息的通知框，更新频繁是一件好事，我很感激各位开发者的辛勤劳动，但作为使用者的我其实并不太关心一个划词翻译扩展更新了哪些厉害的功能，而且这个**通知框**假如不手动去点x关闭的话**短时间内不会自动关闭**

**理想情况下，沙拉查词应该怎么做**

在设置里添加一个"关闭更新通知"的选项，在开启状态下更新后才弹出通知框

**替代方案**

或者在短时间（2~3秒）内自动关闭这个通知框

**额外信息**

**Comment by crimx** [comment]
只有增加新功能之后才会提醒。
