### ISSUE TITLE
鼠须管输入法中文状态下，点击右上角的沙拉图标，输入中文不上屏

### ISSUE THREAD

**Issue by mr-dragon** [crimx/ext-saladict#553]
## 设备信息
 - 操作系统:  Mac
 - 浏览器版本:  Chrome 77
 - 沙拉查词版本:  最新版

## 描述问题

当使用鼠须管输入法时，点击图标，输入时不上屏
换成搜狗就可以，不知道是插件问题还是输入法问题

## 复现步骤

1.  输入法切换到：鼠须管，中文输入状态
2. 点击chrome右上角的沙拉图标，输入中文

## 期待的正常行为

中文输入可正常上屏

## 截图

无法截图

**Comment by crimx** [comment]
你好，输入法属于浏览器外的问题，与本扩展无关。如果不能输入考虑是输入法的问题。
