### ISSUE TITLE
执行划词动作，出现了两个图标

### ISSUE THREAD

**Issue by konkong** [crimx/ext-saladict#554]
## 设备信息
 - 操作系统:  Window10 
 - 浏览器版本:  Chrome78
 - 沙拉查词版本: v7.5.1

## 描述问题
在高德地图左侧的查询栏里执行划词动作，出现了两个图标

## 复现步骤
同上

## 期待的正常行为
只出现一个图标一个搜索栏

## 截图
划词后：
![image](https://user-images.githubusercontent.com/11269613/68129295-42872680-ff54-11e9-904e-b20ed79c8114.png)
戳图标后：
![image](https://user-images.githubusercontent.com/11269613/68129386-6cd8e400-ff54-11e9-836f-e60c0ff50eba.png)

**Comment by crimx** [comment]
请提供该页面链接

**Comment by crimx** [comment]
<https://www.amap.com/> 没有发现问题呢。是不是恰好遇到扩展更新了。你刷新试试。

![ezgif-1-c3ce0543dd66](https://user-images.githubusercontent.com/6882794/68172183-89573980-ffb1-11e9-8cc6-70ea43710eee.gif)

**Comment by konkong** [comment]
感谢回复，开源这么棒的一个工具！
后面在地图里使用过程中又没出现了。
