### ISSUE TITLE
中文句子翻译为英文时，中文句号会被翻译成英文句号加换行键.

### ISSUE THREAD

**Issue by lyleeea** [crimx/ext-saladict#555]
## 设备信息
 - 操作系统:  Window7 
 - 浏览器版本:  Chrome78 
 - 沙拉查词版本:  v7.5.1

## 描述问题
 之前中文段落翻译为英文可以正常显示，现在中文段落翻译会将中文句号或者中文问号翻译为英文句号＋换行键，不利于复制粘贴，如下图所示.
``
<a href="https://sm.ms/image/f9XC4FosVkmITOj" target="_blank"><img src="https://i.loli.net/2019/11/05/f9XC4FosVkmITOj.png" /></a>

**Comment by crimx** [comment]
你好，这个是谷歌翻译转换的，所以不受扩展控制。

**Comment by lyleeea** [comment]
感谢作者热心帮助.
