### ISSUE TITLE
请求将此插件发布到Microsoft Edge应用商店

### ISSUE THREAD

**Issue by rumosky** [crimx/ext-saladict#556]
您好，此插件用的很舒心，功能十分强大，先感谢作者！
如题，自从Microsoft Edge Beta版发布之后，体验十分好，换成 Chromium内核就是爽。
唯独美中不足的就是此浏览器的扩展太少了，商店里正好有ublock origin，但是没有沙拉查词。
目前edge浏览器支持从chrome商店安装沙拉查词，但是您知道，这必须要科学上网。对于抛弃谷歌奔向edge的我来说就是不想折腾那个了，毕竟很多梯子不稳。
我猜想毕竟内核是一样的，从chrome移植到edge应该不是很复杂吧？
最后，再次感谢作者的奉献，感谢感谢！期待早日在Microsoft Store里见到沙拉查词！

**Comment by crimx** [comment]
你好，貌似 Edge 是可以直接运行 Chrome 扩展的。下载页面也提供了墙内的安装方式。

沙拉查词目前绝大多数用户都是用 Chrome ，所以我没有兴趣去额外维护微软商店。如果有人愿意搬运维护十分欢迎。

**Comment by rumosky** [comment]
> 你好，貌似 Edge 是可以直接运行 Chrome 扩展的。下载页面也提供了墙内的安装方式。
> 
> 沙拉查词目前绝大多数用户都是用 Chrome ，所以我没有兴趣去额外维护微软商店。如果有人愿意搬运维护十分欢迎。

好的， 谢谢。
您好，我愿意搬运维护，但是从未做过扩展开发。提交扩展程序zip包的时候，需要manifest.json文件，里面要包含图标之类的。能否发一下？
不知道微软商店发布的时候直接用谷歌的crx文件行不行，能否发点教程，我在微软开发者官网没找到。感谢！
邮箱rumosky@163.com

**Comment by rumosky** [comment]
目前，需要提供除了manifest.json之外，还有隐私政策URL，更新地址URL
扩展商店徽标300x300
小促销磁贴440x280

**Comment by crimx** [comment]
谢谢你的志愿！

我查找资料发现 Chromium 版本的 Edge 是可以直接安装 Chrome 扩展的，甚至可以直接连接 Chrome Web Store 。

![image](https://user-images.githubusercontent.com/6882794/68261977-c4726f00-007c-11ea-970e-d7c4798799de.png)

另外维护需要懂些扩展开发才行，因为如果以 Edge 扩展形式安装很可能会出现不兼容问题，我不用 Windows 所以出现问题了是没有办法修复的。你确定要入坑么？

**Comment by rumosky** [comment]
好的，谢谢，我知道维护需要懂一些开发知识。但您可能没明白我的意思。

我知道Chromium 版本的 Edge可以直接从谷歌商店安装应用，但是这还是要你能稳定访问谷歌。
使用Chromium 版本的 Edge的人大部分都是为了方便，至少微软账号什么的同步不用搭梯子。且微软自家的东西，兼容性还是很好的，就跟denfender完美兼容win10一样。

目前，Chromium 版本的 Edge有一个网页版的扩展商店，类似于谷歌的应用商店，这个商店里应用很少，我的需求就是将沙拉查词移植到这里。而不是老版edge的那个微软商店UWP版。所以，Chromium 版本Edge的应用商店扩展和谷歌应该是一样的，不需要修改什么东西就可以发布扩展。我的目的只是让Chromium 版本的 Edge使用沙拉查词，而不是老版edge。

最后，我有意愿去移植插件的到微软商店，但是这应该是暂时做不到的，毕竟是新手，还需要学习一下。最近也没实践，下学期就🆗了。已经提交了Chromium 版本Edge的沙拉查词，不知道能不能通过审核。

另，在网上，几乎找不到开发微软扩展的学习资料，很难受，若您有相关书籍视频资料等，能否发送一下，谢谢！

**Comment by crimx** [comment]
> 所以，Chromium 版本Edge的应用商店扩展和谷歌应该是一样的，不需要修改什么东西就可以发布扩展。我的目的只是让Chromium 版本的 Edge使用沙拉查词，而不是老版edge。

我说的就是 Chromium 版的 Edge 。Edge 规范不一定跟 Chrome 或者 Firefox 一致的。但你以 Edge 扩展方式提交，扩展很可能会以兼容 Edge 旧规范的方式运行，这里会有 API 上行为的不一致。

> 另，在网上，几乎找不到开发微软扩展的学习资料，很难受，若您有相关书籍视频资料等，能否发送一下，谢谢！

由于 Edge 本身技术在不断变换中，所以扩展的学习资料不一定能跟上，甚至文档也可能跟实际有出入。但文档是除源码以外最靠谱的参考资料了。<https://docs.microsoft.com/en-us/microsoft-edge/extensions>

**Comment by rumosky** [comment]
好的，我提交的是chromium版扩展，应该不用修改规范，因为在文档里看到这样写：
![QQ截图20191106110117](https://user-images.githubusercontent.com/41993388/68264723-c9d3b780-0084-11ea-87b1-92298a3157ae.png)
旧版edge也基本上没人用，期待旧版edge滚动更新到chromium版

**Comment by crimx** [comment]
很好，我以后发布的时候 chrome 版的源码包会一并挂到 [release](https://github.com/crimx/ext-saladict/releases) 上。

**Comment by rumosky** [comment]
好的，非常感谢！我在发布的时候明确注明了我不是原作者，只是搬运工，描述信息与截图等都copy自谷歌应用商店。
再次感谢！

**Comment by crimx** [comment]
如果发布成功的话我可能需要得到扩展在 Edge 上的 id 。发布成功并安装后你在扩展管理页面上看看有没有显示，或者在扩展 background 页面上跑一下 `chrome.runtime.id` 看看值是什么。

**Comment by rumosky** [comment]
好的， 如果成功的话一定会回复你

**Comment by crimx** [comment]
你是直接提供 crx 还是另外提供的？如果是 crx 就不需要，如果解压了 checksum 会不一致。

**Comment by rumosky** [comment]
直接提供的 crx，打包之后添加了一个manifest.json说明文件

**Comment by crimx** [comment]
这样啊，那应该不需要源码包了。这个 `manifest.json` 格式没找到资料，不知道是不是跟扩展的一样？

https://github.com/crimx/ext-saladict/blob/dev/src/manifest/common.manifest.json

**Comment by rumosky** [comment]
对，我找到的格式跟你这个一样。不过我提交的那个只填写了几个字段。到时候看吧，审核不通过再修改就行了。

**Comment by crimx** [comment]
这有点奇怪，提供了 crx 为什么还要提供一份重复的 manifest 。这是完整的 Chrome manifest ，解压 crx 也可以得到。

```json
{
  "version": "7.5.1",
  "content_scripts": [
    {
      "matches": [
        "<all_urls>"
      ],
      "js": [
        "assets/browser-polyfill.min.js",
        "assets/runtime.a044b40a.js",
        "assets/dictpanel.1042a748.js",
        "assets/16.2e924849.js",
        "assets/1.7eddf80c.js",
        "assets/3.5393048d.js",
        "assets/content.3d38ecc5.js"
      ]
    },
    {
      "match_about_blank": true,
      "all_frames": true,
      "matches": [
        "<all_urls>"
      ],
      "js": [
        "assets/browser-polyfill.min.js",
        "assets/runtime.a044b40a.js",
        "assets/17.1c5015e3.js",
        "assets/1.7eddf80c.js",
        "assets/selection.50944d2e.js"
      ]
    }
  ],
  "browser_action": {
    "default_popup": "popup.html",
    "default_icon": {
      "16": "assets/icon-16.png",
      "19": "assets/icon-19.png",
      "24": "assets/icon-24.png",
      "38": "assets/icon-38.png",
      "48": "assets/icon-48.png",
      "128": "assets/icon-128.png"
    }
  },
  "options_ui": {
    "page": "options.html",
    "open_in_tab": true,
    "chrome_style": false
  },
  "background": {
    "scripts": [
      "assets/browser-polyfill.min.js",
      "assets/runtime.a044b40a.js",
      "assets/15.a800633e.js",
      "assets/1.7eddf80c.js",
      "assets/3.5393048d.js",
      "assets/background.1a567c87.js"
    ],
    "persistent": true
  },
  "manifest_version": 2,
  "homepage_url": "https://saladict.crimx.com/",
  "minimum_chrome_version": "60",
  "name": "__MSG_extension_name__",
  "short_name": "__MSG_extension_short_name__",
  "description": "__MSG_extension_description__",
  "default_locale": "zh_CN",
  "icons": {
    "16": "assets/icon-16.png",
    "48": "assets/icon-48.png",
    "128": "assets/icon-128.png"
  },
  "commands": {
    "toggle-active": {
      "description": "__MSG_command_toggle_active__"
    },
    "toggle-instant": {
      "description": "__MSG_command_toggle_instant__"
    },
    "open-quick-search": {
      "description": "__MSG_command_open_quick_search__"
    },
    "open-pdf": {
      "description": "__MSG_command_open_pdf__"
    },
    "open-youdao": {
      "description": "__MSG_command_open_youdao__"
    },
    "open-google": {
      "description": "__MSG_command_open_google__"
    },
    "search-clipboard": {
      "description": "__MSG_command_search_clipboard__"
    }
  },
  "web_accessible_resources": [
    "assets/*",
    "audio-control.html",
    "quick-search.html"
  ],
  "permissions": [
    "<all_urls>",
    "alarms",
    "clipboardRead",
    "contextMenus",
    "cookies",
    "notifications",
    "storage",
    "tabs",
    "unlimitedStorage",
    "webRequest",
    "webRequestBlocking"
  ],
  "optional_permissions": [
    "clipboardWrite"
  ],
  "content_security_policy": "script-src 'self' 'unsafe-eval' https://www.google-analytics.com; object-src 'self'",
  "incognito": "split",
  "update_url": "https://clients2.google.com/service/update2/crx"
}

```

**Comment by rumosky** [comment]
对，我也没明白。可我第一次提交之后，微软提示我缺少manifest.json文件，我就重新打包了一下，第二次就上传成功。到时候再说吧，文档里面也没找到开发的规范，示例文件等。可能因为chromium版edge还没发正式版的缘故吧

**Comment by richerdking** [comment]
在Edge开发模式Load extension提示缺乏manifest.json 使用上面的代码创建manifest.json后又提示 Missing‘author“ field

**Comment by Fanx-jk** [comment]
> 对，我也没明白。可我第一次提交之后，微软提示我缺少manifest.json文件，我就重新打包了一下，第二次就上传成功。到时候再说吧，文档里面也没找到开发的规范，示例文件等。可能因为chromium版edge还没发正式版的缘故吧

请问可以抽时间更新一下吗，上一次更新还是去年11月份，正式版edge已经发布了，插件都不能正常使用了

**Comment by rumosky** [comment]
> > 对，我也没明白。可我第一次提交之后，微软提示我缺少manifest.json文件，我就重新打包了一下，第二次就上传成功。到时候再说吧，文档里面也没找到开发的规范，示例文件等。可能因为chromium版edge还没发正式版的缘故吧
> 
> 请问可以抽时间更新一下吗，上一次更新还是去年11月份，正式版edge已经发布了，插件都不能正常使用了

早就发布了新版，edge审核太慢。到现在到没有通过，正在修改中

**Comment by rumosky** [comment]
@crimx我发送到 straybugs@gmail.com这个邮箱的邮件被退信了。能给个邮箱地址吗？有了最新的动态

**Comment by crimx** [comment]
@rumosky 你可以再发一遍吗？我对外目前只会用这个邮箱。

**Comment by rumosky** [comment]
> @rumosky 你可以再发一遍吗？我对外目前只会用这个邮箱。

![Screenshot_20200118_131610_com netease mail](https://user-images.githubusercontent.com/41993388/72659077-017aac00-39b2-11ea-8c31-685a1be37651.jpg)
还是退信。不知道是怎么了

**Comment by crimx** [comment]
<https://support.google.com/mail/answer/6590?p=BlockedMessage>

> ## Types you can't include as attachments
> To protect your account, Gmail doesn't allow you to attach certain types of files. Gmail often updates the types of files not allowed to keep up with harmful software that is constantly changing. Some examples include: 

> .ade, .adp, .apk, .appx, .appxbundle, .bat, .cab, .chm, .cmd, .com, .cpl, .dll, .dmg, .exe, .hta, .ins, .isp, .iso, .jar, .js, .jse, .lib, .lnk, .mde, .msc, .msi, .msix, .msixbundle, .msp, .mst, .nsh, .pif, .ps1, .scr, .sct, .shb, .sys, .vb, .vbe, .vbs, .vxd, .wsc, .wsf, .wsh

把有问题的附件去掉。

**Comment by rumosky** [comment]
edge浏览器chromium版插件已更新，目前最新版7.6.2，由于微软审核较慢，会落后于Chrome商店。

**Comment by rockeyshao** [comment]
请问有没有办法在edge自带的pdf浏览器中实现沙拉查词的使用呢，批注功能感觉还是很必要的

**Comment by crimx** [comment]
- [初次使用说明](https://saladict.crimx.com/notice.html)
- [浏览器外划词](https://saladict.crimx.com/native.html)
