### ISSUE TITLE
可以增加pdf阅读时，颜色标记和颜色标记后的备注功能吗，类似用edge打开pdf的那种

### ISSUE THREAD

**Issue by fkjkkll** [crimx/ext-saladict#557]
**请描述目前使用沙拉查词遇到什么不便**

**理想情况下，沙拉查词应该怎么做**

**替代方案**

**额外信息**

**Comment by crimx** [comment]
请阅读[常见问题及答复](https://github.com/crimx/ext-saladict/wiki/Q&A#wiki-wrapper)。
