### ISSUE TITLE
translator依赖无法下载

### ISSUE THREAD

**Issue by snow2flying** [crimx/ext-saladict#558]
您好，编译的时候运行 npm i 出现以下的问题，麻烦解决一下：
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@opentranslate%2fbaidu - Not found
npm ERR! 404 
npm ERR! 404  '@opentranslate/baidu@^1.0.4' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'ext-saladict'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by crimx** [comment]
部分功能正好在重构中。

**Comment by snow2flying** [comment]
好的，非常期待

**Comment by snow2flying** [comment]
error An unexpected error occurred: "https://registry.yarnpkg.com/@opentranslate/baidu/-/baidu-1.0.4.tgz: Request failed \"404 Not Found\"".
目前还是这个问题，请问可以尽快修复一下吗？或者可以指教一下如何解决这个错误吗？

**Comment by snow2flying** [comment]
error Couldn't find package "storybook__addon-knobs@*" required by "@types/storybook__addon-knobs@^5.0.2" on the "npm" registry.
目前还新增了这个，期待可以及时维护一下这个project

**Comment by crimx** [comment]
感谢反馈，已更新。

**Comment by snow2flying** [comment]
well done! I appreciate it.
