### ISSUE TITLE
一个“沙拉查词”点击红心不能同步到“扇贝单词”的情况

### ISSUE THREAD

**Issue by LucasZhan** [crimx/ext-saladict#559]
首先很感谢开发组提供如此方便且实用的查词插件。再道歉我之前没看到github是开发者倡导反馈issue的渠道，之前发了反馈邮件却又在这里发一遍。

是这样的，最近我查词之后点击“红心❤”不能像以前一样同步到我的“扇贝单词”了（提示同步失败）。

系统是OSX 10.15.1。
插件用的是firefox插件最新版本7.5.1
firefox的版本是70.0.1

同样的设置，在chrome可以，firefox却不行（之前可以）。

如果您知道解决方法的话能告知我吗？Thanks♪(･ω･)ﾉ

**Comment by crimx** [comment]
我测试没问题的。你是不是在 Firefox 上退出了扇贝网帐号？

**Comment by LucasZhan** [comment]
我也怀疑是这样。但我在沙拉划词的设置里找不到退出/重新登录扇贝账号的按钮/入口。
您能告知哪里能找到吗？
谢谢



詹旭
XuZhan







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CRIMX"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月9日(星期六) 下午2:53
收件人:&nbsp;"crimx/ext-saladict"<ext-saladict@noreply.github.com&gt;;
抄送:&nbsp;"詹旭"<1012999614@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [crimx/ext-saladict] 一个“沙拉查词”点击红心不能同步到“扇贝单词”的情况 (#559)




我测试没问题的。你是不是在 Firefox 上退出了扇贝网帐号？

**Comment by crimx** [comment]
是在官网上登录

**Comment by LucasZhan** [comment]
搞定了。谢谢~


詹旭
XuZhan


机械电子工程专业
Mechatronic Engineering


华南理工大学机械与汽车工程学院

South China University of technology Mechanical and Automotive Engineering


Tel:+86-132-4767-4627
 

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CRIMX"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月9日(星期六) 下午3:12
收件人:&nbsp;"crimx/ext-saladict"<ext-saladict@noreply.github.com&gt;;
抄送:&nbsp;"詹旭"<1012999614@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [crimx/ext-saladict] 一个“沙拉查词”点击红心不能同步到“扇贝单词”的情况 (#559)




是在官网上登录
