### ISSUE TITLE
kiwi 浏览器中绑定扇贝→验证失败。

### ISSUE THREAD

**Issue by cheung-dp** [crimx/ext-saladict#560]
kiwi 是目前唯一能装这款插件的手机浏览器。但是无法绑定扇贝，向右滑动滑块验证时总是失败。另外手机浏览器中单词本不能导出。我认为这是学英语的终极杀器。非常感谢您的开发这样一款神器。

**Comment by crimx** [comment]
你登录扇贝网了么？另外本扩展目前没有提供移动设备的支持，如果你要在手机上使用的话会有很多坑。
