### ISSUE TITLE
添加WebDAV同步账号时，弹窗提示：未知错误 「unknown」。

### ISSUE THREAD

**Issue by Qingchundefeng** [crimx/ext-saladict#562]
服务器的DAV已经搭建好，测试正常。
WebDAV同步功能中，填写完账号信息，点击保存时，提示：未知错误 「unknown」。
感谢您开发出如此实用的插件。

**Comment by crimx** [comment]
服务器是自建的话是用什么框架。没有例子我无法测试。

**Comment by Qingchundefeng** [comment]
用的框架是caddy和其自带的http.webdav插件。

**Comment by crimx** [comment]
可以提供测试帐号吗

**Comment by Qingchundefeng** [comment]
可以的，怎么发你，邮箱还是...？

**Comment by crimx** [comment]
可以，见我的 profile

**Comment by crimx** [comment]
发现 bug 了，你先在服务器链接后面补上 `/` 即可。

**Comment by Qingchundefeng** [comment]
嗯，可以了，非常感谢！
