### ISSUE TITLE
防止生词本被删

### ISSUE THREAD

**Issue by doyanger** [crimx/ext-saladict#563]
防止生词本被删
我用了一阵子saladict，保存了一些生词，某次运行ccleaner，结果发现生词本被删掉了。
有机会可将生词本保存到其他地方的吗？防止被一些清理软件误删？
非常感谢你们的工作，saladict真的非常好用！

**Comment by crimx** [comment]
生词本可以同步。请阅读[使用说明](https://saladict.crimx.com/manual.html)。
