### ISSUE TITLE
NEW edge can't show the window of salad.

### ISSUE THREAD

**Issue by Bear808** [crimx/ext-saladict#565]
此浏览器基于 Chromium 开源项目及其他 开源软件。

Microsoft Edge

## 设备信息
 - 操作系统: 
 - 浏览器版本: 
 - 沙拉查词版本:

**Comment by crimx** [comment]
Edge 浏览器不在 Saladict 的维护范围。但据 #556 Edge 是应该可用的，你要更具体描述你的问题。

**Comment by Bear808** [comment]
> Edge 浏览器不在 Saladict 的维护范围。但据 #556 Edge 是应该可用的，你要更具体描述你的问题。
重新安装后解决了问题。
