### ISSUE TITLE
本地页面，划取英文单词无法弹查词弹窗

### ISSUE THREAD

**Issue by twocold0451** [crimx/ext-saladict#566]
## 设备信息
 - 操作系统: Window10
 - 浏览器版本: Chrome76
 - 沙拉查词版本: v7.5.2

## 描述问题
打开本地页面，划取英文单词无法弹查词弹窗

## 复现步骤
1. 打开本地HTML文件
2. 划取英文单词
3. 不出现查词窗口
4. 观察浏览器右上角扩展图表是灰色的

## 期待的正常行为
1.正确出现查词窗口

**Comment by crimx** [comment]
[⚠️（重要）初次使用注意事项！！！](https://saladict.crimx.com/notice.html)
