### ISSUE TITLE
谷歌网页翻译在linux的firefox所有网页下不可用

### ISSUE THREAD

**Issue by wangbaolong36gmail** [crimx/ext-saladict#567]
## 设备信息
 - 操作系统: linux(kali) 
 - 浏览器版本:  70.0.1 (64-bit) 
 - 沙拉查词版本:7.5.2 

## 描述问题

谷歌网页翻译大部分情况下无法使用(所有网页) :broken_heart:
应该也不是科学上网的问题,浏览器是可以正常fanqiang的
记得刚安装的时候特意测试了一下谷歌网页翻译,是可使用的,后来再次需要使用的时候发现无效,不论什么页面,大部分情况下右键点击谷歌网页翻译都没有响应, 浏览器控制台也没有报错信息, 有道翻译一直可以正常使用,但翻译质量有点差  :strawberry: :strawberry:希望作者可以抽时间检查一下是什么问题,辛苦啦~~~~
 :rose: :rose: :rose:

## 期待的正常行为

将网页内容正常替换为目标语言

**Comment by crimx** [comment]
许多网页会对跨域有限制。有道之所以没问题是因为我逆向了请求通过扩展转接。谷歌我没有时间弄了，你用 Chrome 的话直接用内置的翻译就行。

**Comment by wangbaolong36gmail** [comment]
个人喜欢ff，就是因为chrome翻译好用才一直留着做备用，哭哭
谢谢回复～
