### ISSUE TITLE
Dark theme please.

### ISSUE THREAD

**Issue by Pwn-X** [crimx/ext-saladict#570]
**Is your feature request related to a problem? Please describe.**

I use the dark theme almost 24h. So every time I use the saladict, I feel uncomfortable. The panel is too bright.

**Describe the solution you'd like**

So please add the dark theme!

**Describe alternatives you've considered**

**Additional context**

I like the saladict and use it everyday.
Thanks.
:-)

**Comment by crimx** [comment]
Dark theme is under panel settings.

**Comment by Pwn-X** [comment]
> Dark theme is under panel settings.

Oh, I'm wondering if my eyes are functioning properly.
Thanks.
