### ISSUE TITLE
建议 在pdf阅读界面添加 输出pdf原始URI地址 的功能

### ISSUE THREAD

**Issue by WangYves** [crimx/ext-saladict#571]
**请描述目前使用沙拉查词遇到什么不便**

每次在Firefox里打开pdf,地址栏里就显示一堆扩展信息.
想复制原始下载地址的时候,就要手动更改URI地址,
删掉前面一大段扩展用的信息,%2F改成/,%3A改成:,再手动复制.
网上大多数的pdf用途是手册文档,目录都挺深的,要改好久.

**理想情况下，沙拉查词应该怎么做**

啪! 右键-沙拉查词-地址栏显示pdf原始URI地址,,方便浏览上层目录或者修改文件序号查看下个文件.
或者
啪! 右键-沙拉查词-复制pdf原始URI地址到剪贴板,,直接分享给其他人.

简单高效,帅气靓丽.

**可能有用的信息**

给个相对简单的链接,体会下这种感觉.
https://www.st.com/resource/en/user_manual/usermanual_gnu_assembler.pdf
我一直认为阅读rfc是从根源获取信息的好办法.
https://tools.ietf.org/pdf/rfc3986.pdf

**Comment by crimx** [comment]
点击地址栏旁的图标，面板左下方有二维码图案，放上去可以看到原始链接。

右键菜单以后有缘再添加。

**Comment by WangYves** [comment]
啊哈哈哈,原来在这,我平常都不把沙拉查词放在工具栏里边.
试了一下,只有鼠标悬停的时候才能显示并操作地址.
