### ISSUE TITLE
源映射错误：Error: NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by David-LS** [crimx/ext-saladict#572]
## 设备信息
 - 操作系统: windows10
 - 浏览器版本: Firefox 70.0.1 x64
 - 沙拉查词版本: 7.5.2

## 描述问题
源映射错误：Error: NetworkError when attempting to fetch resource.
源 URL：moz-extension://d392a7d3-af5b-421d-ab5a-15827c3828b0/assets/browser-polyfill.min.js
源映射 URL：browser-polyfill.min.js.map
源映射map文件丢失

## 截图

![图片](https://user-images.githubusercontent.com/37445928/69553696-8ca37b00-0fdb-11ea-9710-125ed5d87d4e.png)

**Comment by crimx** [comment]
map 文件用于调试，不影响运行。
