### ISSUE TITLE
独立窗口模式下，menuBar-SearchBox 与 menuBar-DragArea 宽度自适应优化建议

### ISSUE THREAD

**Issue by Tidlo** [crimx/ext-saladict#573]
**请描述目前使用沙拉查词遇到什么不便**

在使用独立窗口模式时，如果将独立查词面板的宽度调到比较小的范围内，查词输入框 menuBar-SearchBox 的宽度就会变得非常小，而此时  menuBar-DragArea 仍然有较大空间。

独立窗口模式下已经有系统自带的 Window Bar 用作拖拽的 handle，不需要一块空白的空间作为鼠标拖拽的 handle，所以个人认为这部分空间在独立窗口模式下意义不大。

**理想情况下，沙拉查词应该怎么做**

在独立窗口模式下，应该优先确保查词输入框在外围元素宽度减少时有足够的宽度，也就是先减小 menuBar-DragArea 的宽度，再减小 menuBar-SearchBox 的宽度。

**替代方案**

**额外信息**

**Comment by crimx** [comment]
谢谢你的建议。这个是应该在独立窗口下去除。
