### ISSUE TITLE
该扩展会导致 Gmail 网页版无法下载 PDF 附件

### ISSUE THREAD

**Issue by resuly** [crimx/ext-saladict#576]
#332  设备信息
 - 操作系统: Windows 10
 - 浏览器版本: Chrome78
 - 沙拉查词版本: 如 v7.5.2

## 描述问题
Gmail 邮件中的 PDF 无法下载，关闭插件后恢复正常

## 截图
![image](https://user-images.githubusercontent.com/3870826/70008528-adb13080-15c6-11ea-8c79-c45c4d3fca0b.png)

**Comment by crimx** [comment]
https://saladict.crimx.com 读注意事项和使用说明。将不需要的网页加入 PDF 黑名单。

**Comment by resuly** [comment]
![image](https://user-images.githubusercontent.com/3870826/70022873-d0087580-15e9-11ea-8972-2fe5d5e85e57.png)
是我设置的有问题吗？添加黑名单后还是报一样的错，点击下载无反应：
![image](https://user-images.githubusercontent.com/3870826/70022951-12ca4d80-15ea-11ea-9941-221659571335.png)
![image](https://user-images.githubusercontent.com/3870826/70022997-32617600-15ea-11ea-8448-be61fd96831f.png)
但关闭插件后一切正常。

**Comment by crimx** [comment]
测试了一下，是 `*://*.googleusercontent.com/*`
