### ISSUE TITLE
添加微软翻译

### ISSUE THREAD

**Issue by dakehero** [crimx/ext-saladict#577]
**请描述目前使用沙拉查词遇到什么不便**

整句翻译没有准确路极高的微软翻译

**理想情况下，沙拉查词应该怎么做**

能够弹出微软翻译和谷歌翻译等对照查看

**替代方案**

**额外信息**

**Comment by crimx** [comment]
你好，目前没有绝对完美的翻译平台，沙拉查词已支持众多机器翻译，应对绝大部分场景已绰绰有余。精力有限不再考虑维护雷同服务。
