### ISSUE TITLE
建议：查词面板定位到鼠标剪头下面

### ISSUE THREAD

**Issue by RenDaRen** [crimx/ext-saladict#580]
遇到的问题：阅读是从左往右的习惯，但是查询前一个单词的时候，查词面板默认是在当前单词右面，如果我想要查找右面的单词，还得点击空白处或者关闭按钮关闭查词面板，才能继续操作。

建议：将查词面板默认定位到鼠标剪头下面，这样右面的单词可以直接选中查询（页面底部的单词还是按照现在的定位方式处理即可。）

**Comment by crimx** [comment]
你在「查词习惯」设置沙拉图标出现的位置即可。

**Comment by RenDaRen** [comment]
> 你在「查词习惯」设置沙拉图标出现的位置即可。

😭原来这么简单，我还多此一举，在自定义查词面板样式加了个
`.dictPanel-Root {
margin-top:50px;
}`
感谢作者开发了这么好用的翻译插件！！！

**Comment by crimx** [comment]
不客气！
