### ISSUE TITLE
查询单词自动加入生词本，并同步到扇贝。

### ISSUE THREAD

**Issue by Co-xuan** [crimx/ext-saladict#581]
无论是在独立窗口还是页面，查询的单词自动加入生词本，自动或每天手动同步到扇贝，这样可以手机用扇贝复习了。谢谢你。支持！

**Comment by crimx** [comment]
> 查询的单词自动加入生词本

生词本放的是经过筛选的单词，查词记录用来放粗糙的数据。自动加入生词本噪音太多，只会适得其反。

> 自动或每天手动同步到扇贝

生词本支持扇贝同步。
