### ISSUE TITLE
劃詞翻譯，加個設置吧

### ISSUE THREAD

**Issue by zzzgit** [crimx/ext-saladict#583]
<img width="333" alt="Screen Shot 2019-12-09 at 17 37 10" src="https://user-images.githubusercontent.com/1060733/70424583-954f8300-1aaa-11ea-8789-897312261a51.png">

目前，只要開啟了這個選項，劃詞翻譯就生效。
可否加個設置：**劃詞的同時，需要按住CTRL鍵**

**Comment by crimx** [comment]
请阅读[使用说明](https://saladict.crimx.com/manual.html)。
