### ISSUE TITLE
在Edge Beta版本浏览器中无法弹出窗口

### ISSUE THREAD

**Issue by Seumi** [crimx/ext-saladict#585]
#170  设备信息
 - 操作系统:  Win10 1903
 - 浏览器版本: Microsoft Edge 版本 80.0.345.0 (官方内部版本) dev (64 位)
 - 沙拉查词版本: 7.5.2

## 描述问题

点击浏览器右上角的图标，会显示一个非常小的方框，无法显示内容。
在页面划词后会显示沙拉碗，但是点击后没有弹出窗口

## 复现步骤

点击图标
划词后点击沙拉碗

## 截图

![image](https://user-images.githubusercontent.com/3949730/70496389-5f61db80-1b4a-11ea-9407-09faa137c459.png)

## 额外信息

在同一台机器的Chrome浏览器与360极速浏览器上均无此问题，可正常使用

**Comment by Seumi** [comment]
在点击的一瞬间能看到部分窗口，然后就变成截图那样了

**Comment by crimx** [comment]
你好，Edge 不在 Saladict 支持范围，只能看有没有其他志愿者维护了。

**Comment by Seumi** [comment]
Understand，thanks for your brilliant work
