### ISSUE TITLE
希望增加自动翻译网页功能

### ISSUE THREAD

**Issue by tulip33** [crimx/ext-saladict#586]
**请描述目前使用沙拉查词遇到什么不便**

S3 translator扩展有个自动翻译网页功能，还能记住哪些站点需要自动翻译，只要打开那个网站的网页就会自动使用谷歌翻译页面。但是S3今天被火狐官方彻底禁止无法使用。
看到莎拉也有谷歌网页翻译，但是无法自动翻译页面，每次都要点击图标。
希望莎拉能添加自动翻译功能，谢谢！

**理想情况下，沙拉查词应该怎么做**

**替代方案**

**额外信息**

**Comment by crimx** [comment]
你好，沙拉查词的定位更多是在查词方面，网页翻译功能主要是作为辅助功能。因为我个人不太需要，所以目前没有计划继续实现这方面的功能。

**Comment by jenniferchiang** [comment]
用彩云小译可以实现双语对照翻译，翻译的效果还不错，个别单词不会可以再结合着saladictia查，非常棒~
