### ISSUE TITLE
希望可以添加独立窗口置顶功能

### ISSUE THREAD

**Issue by honghuhu** [crimx/ext-saladict#588]
**请描述目前使用沙拉查词遇到什么不便**

- 问题 - 在钉住窗口时点击其它应用, 沙拉独立窗口会被覆盖掉
- 希望 - 当我钉住他时, 他能保证**永远保持在界面最前方**

**Comment by crimx** [comment]
浏览器 API 不支持。我昨天正好在[更新说明](https://mp.weixin.qq.com/s/5BZaV0wsfBSFkRic9aNk1Q)里提到了。你只能看系统有没有提供相关的按钮或安装其它系统插件。
