### ISSUE TITLE
更新7.5.3后Chrome快捷键无响应

### ISSUE THREAD

**Issue by gmm4** [crimx/ext-saladict#589]
## 设备信息
 - 操作系统: Window10
 - 浏览器版本: Chrome79.0.3945.79（正式版本64位）（今日最新）
 - 沙拉查词版本: 7.5.3

## 描述问题
自动更新后，快捷键（全局和Chrome内）失效。
尝试切换多个未占用的快捷键，也无响应。

## 复现步骤
在Chrome内和全局输入设定的快捷键

## 期待的正常行为
求修复

## 额外信息
快捷键失效的情况下，Quicker调用也因此一并失效了...

**Comment by crimx** [comment]
我在 Linux 上测试没问题，你看看是不是快捷键冲突了。重启浏览器试试。并试试 `Alt + L`。

**Comment by gmm4** [comment]
> 我在 Linux 上测试没问题，你看看是不是快捷键冲突了。重启浏览器试试。并试试 `Alt + L`。

下午试了下，重启Chrome和计算机，修改快捷键组合仍然不行；其他扩展程序的全局正常响应；昨天还能正常调用。
等等看有没有其他人有和我一样的问题好了。

**Comment by liang404001** [comment]
版本一致，有相同的问题

**Comment by crimx** [comment]
好，我晚上再看看

**Comment by liang404001** [comment]
补充一下，只有”打开独立词典窗口”和”在独立窗口中搜索剪贴板内容”这两个设置快捷键没反应（不论是全局还是chrome内），其他的有相应，说明不是快捷键冲突。

**Comment by crimx** [comment]
嗯，应该是窗口控制方面的判断逻辑有问题。
