### ISSUE TITLE
在独立窗口中进行查词后添加到生词本，功能不正常

### ISSUE THREAD

**Issue by huanglusong** [crimx/ext-saladict#590]
## 设备信息
 - 操作系统: win 10
 - 浏览器版本:   Chrome 78
 - 沙拉查词版本:  v7.5.4

## 描述问题

使用沙拉查词插件的独立窗口进行生词查询，将生词添加到生词本中，此功能表现不正常！

## 期待的正常行为

生词本中及时的记录单词，并希望记录单词的方式能与划词的方式类似

## 截图

![image.png](https://i.loli.net/2019/12/12/xQH5agnbINC6XAh.png)

**Comment by crimx** [comment]
请详细说明你指的「正常」是什么？

**Comment by huanglusong** [comment]
### 我所期望的正常流程
1、点击图标弹出面板
2、进行生词查询
3、将此生词进行爱心
4、右击爱心进入生词本
5、生词本中出现这个生词

##### 目前的结果
生词本中并没有及时记录我的生词，出现的时机十分诡异

##### 截图
![image.png](https://i.loli.net/2019/12/12/xQH5agnbINC6XAh.png)

**Comment by huanglusong** [comment]
sorry，尝试了几次，有时添加到生词本的时机确实很慢，有时很快。不知道是网络原因还是软件原因。同时希望能在爱心的同时弹出编辑面板，然而这个只在划词时是可用的

**Comment by crimx** [comment]
> 出现的时机十分诡异

在设置「单词管理」中关闭一些上下文翻译引擎试试。

**Comment by huanglusong** [comment]
谢谢，你的想法和我一样。同时希望能够考虑这个  **独立窗口能在爱心的同时弹出编辑面板**这个令人兴奋的功能！
