### ISSUE TITLE
生词无法上传进扇贝单词

### ISSUE THREAD

**Issue by TwoAndOne** [crimx/ext-saladict#591]
## 设备信息
 - 操作系统: 
 - 浏览器版本: 
 - 沙拉查词版本: 

## 描述问题

点击生词本同步,上传现有所有单词时
chrome出现弹窗说无法上传

![image](https://user-images.githubusercontent.com/44161851/70723277-9810d900-1d33-11ea-8cc2-e75fefc3f38a.png)

**Comment by crimx** [comment]
扇贝网上没有「uninterruptible」这个单词。

**Comment by TwoAndOne** [comment]
谢谢你回复的这么快!
我还有一个疑问:
如果出现了扇贝网没有的单词,就会出现无法上传的弹窗.
那么其余扇贝网有的单词是否已经成功上传呢?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CRIMX"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月12日(星期四) 晚上11:07
收件人:&nbsp;"crimx/ext-saladict"<ext-saladict@noreply.github.com&gt;;
抄送:&nbsp;"2414655851"<2414655851@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [crimx/ext-saladict] 生词无法上传进扇贝单词 (#591)




扇贝网上没有「uninterruptible」这个单词。

**Comment by crimx** [comment]
会上传的。你打开扇贝生词本看看不就知道了。
