### ISSUE TITLE
设置chrome快捷键“在 Saladict 中浏览此 PDF”无法正常打开文件

### ISSUE THREAD

**Issue by NoelZong** [crimx/ext-saladict#594]
## 设备信息
 - 操作系统:  win10
 - 浏览器版本: chrome78
 - 沙拉查词版本: v7.5.4

## 描述问题

使用chrome扩展程序快捷键“在 Saladict 中浏览此 PDF”后无法使用该快捷键打开pdf

## 复现步骤

在chrome设置扩展程序快捷键页面“chrome://extensions/shortcuts”，为沙拉查词设置好“在 Saladict 中浏览此 PDF”的快捷键后，打开一个使用内置pdf浏览器阅读的pdf文件，在此页面使用刚刚设置好的快捷键后无法正常打开该pdf文件。可以正常进入到沙拉查词的内置pdf界面，但是无法显示pdf的内容，显示为空白。

## 期待的正常行为

可以使用chrome扩展程序快捷键正常在沙拉查词中打开pdf

**Comment by crimx** [comment]
> 打开一个使用内置pdf浏览器阅读的pdf文件

是本地的码？本地要在扩展管理页面开启允许。链接的测试 <http://www.africau.edu/images/default/sample.pdf> 没问题。

**Comment by NoelZong** [comment]
ok了，感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CRIMX"<notifications@github.com&gt;; 
发送时间: 2019年12月14日(星期六) 晚上6:51
收件人: "crimx/ext-saladict"<ext-saladict@noreply.github.com&gt;; 
抄送: "罐头卡"<eruk@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [crimx/ext-saladict] 设置chrome快捷键“在 Saladict 中浏览此 PDF”无法正常打开文件 (#594)



 
打开一个使用内置pdf浏览器阅读的pdf文件
  
是本地的码？本地要在扩展管理页面开启允许。链接的测试 http://www.africau.edu/images/default/sample.pdf 没问题。
