### ISSUE TITLE
沙拉单词导入Anki时添加音频(Sound字段)支持

### ISSUE THREAD

**Issue by AdamWang1102** [crimx/ext-saladict#595]
**请描述目前使用沙拉查词遇到什么不便**

目前沙拉单词导入Anki时没有音频相关的字段，如果想导入anki音频的话，就只能手动复制音频的链接，之后下载到本地再使用沙拉单词里面的其中一个字段（比如SourceURL）临时作为**Sound**字段比较麻烦，不知道能不能添加一个audio字段，或者通过其他的方式在导入anki时是带有音频信息的。

**理想情况下，沙拉查词应该怎么做**

[ODH](https://github.com/ninja33/ODH)
[Online Dictionary Helper](https://chrome.google.com/webstore/detail/online-dictionary-helper/lppjdajkacanlmpbbcdkccjkdbpllajb) 
这个扩展是通过Anki connect的方式来实现扫词一键导入到anki的，或许类似的可以在沙拉单词里面每个词典的角落添加一个一键添加到Anki的button？这样相当于直接用anki来实现生词本的功能了。

**Comment by crimx** [comment]
> 不知道能不能添加一个audio字段，或者通过其他的方式在导入anki时是带有音频信息的

这个跟沙拉查词为什么不自动填写释义是一个原因，发音根据词义、区域以及平台词库很难准确定位到单一的结果。这样的功能做出来只会是错漏百出，不实用也浪费了开发的时间。

如果你是要用 Anki 来记单词的，还是建议挑选合适的结果右键复制链接。你可以放在「笔记」区域，导入时作为发音字段即可。Anki 的记忆应该是从添加单词的时候开始，但很多人忽略了这个步骤。

如果仅仅是收藏单词，目前可以同步到扇贝词库，会有简单的通用释义和发音。

Anki connect 进度请订阅 #394 。

**Comment by AdamWang1102** [comment]
了解，感谢回复。
