### ISSUE TITLE
Google Dictionnary 显示不全，部分内容左边被遮挡

### ISSUE THREAD

**Issue by asche910** [crimx/ext-saladict#596]
## 设备信息
 - 操作系统:  Windows10
 - 浏览器版本: Version 78.0.3904.108 (Official Build) (64-bit)
 - 沙拉查词版本: 7.5.4

## 描述问题

详情看下面图片，就是某些单词的谷歌词典解释中，内容显示太左边导致不全。上面开始显示完全，往下就慢慢不全了。 比如单词 elevated

## 复现步骤

谷歌词典，例如单词 elevated

## 截图

![TIM截图20191217192520.png](https://i.loli.net/2019/12/17/5JZKMdqYsFjnoHz.png)

**Comment by crimx** [comment]
![image](https://user-images.githubusercontent.com/6882794/71308092-ef4d3280-2432-11ea-839e-e7f66c9f8513.png)

我这边显示正常。点击 “Google Dictionary” 标题你打开的谷歌搜索页面是怎么样的？

**Comment by asche910** [comment]
具体解释的缩进没了
同样这个单词，好像只有google dictionary的是这样的

![TIM截图20191224095641.png](https://i.loli.net/2019/12/24/KByHas1OqEhPRGf.png)

**Comment by crimx** [comment]
> 点击 “Google Dictionary” 标题你打开的谷歌搜索页面是怎么样的？

👆

**Comment by asche910** [comment]
![TIM截图20191224210422.png](https://i.loli.net/2019/12/24/vVAJUaBf1k9ZTtF.png)

**Comment by crimx** [comment]
这个链接呢 <https://www.google.com/search?q=define+elevated&safe=off&newwindow=1>

**Comment by crimx** [comment]
我怀疑是谷歌在搞灰度测试。

**Comment by asche910** [comment]
也是正常的

![TIM截图20191225103256.png](https://i.loli.net/2019/12/25/KLecuWPUQ1iHa5D.png)

**Comment by crimx** [comment]
你的 Google 页面最下方显示是什么国家呢？

**Comment by asche910** [comment]
Singapore

**Comment by crimx** [comment]
![image](https://user-images.githubusercontent.com/6882794/71430224-85b87700-2705-11ea-93f3-66a4e49fefbd.png)

是不一样。不过没关系了，我已经找到其它方式实现。
