### ISSUE TITLE
在edge beat上无法运行

### ISSUE THREAD

**Issue by shijinlong12** [crimx/ext-saladict#598]
## 设备信息
 - 操作系统: Window10
 - 浏览器版本:  Microsoft Edge | 79.0.309.54 (官方内部版本) beta (64 位)
 - 沙拉查词版本: 7.5.1

## 描述问题
从 Edge beta 扩展商店下到沙拉查词, 安装完以后图标就是灰的, 一直不能用

## 截图
![微信图片_20191218175454](https://user-images.githubusercontent.com/40626840/71076536-dc332c00-21c0-11ea-94a0-3332f65af55f.png)

**Comment by zzzgit** [comment]
edge沒有必要兼容吧，直接用Chrome

**Comment by crimx** [comment]
Duplicate of #585
