### ISSUE TITLE
選中一段文字，然後翻譯成英文

### ISSUE THREAD

**Issue by zzzgit** [crimx/ext-saladict#599]
選中一段文字，然後翻譯成英文。
這個需求，最好的配置和操作方式是？

**Comment by hqyyqh** [comment]
是指浏览器外划词？如果是的话，最简单应该是：
1. 只需要给插件的【在独立窗口中搜索剪贴板内容】选项设置一个**全局快捷键**
2. 然后选中文字→Ctrl+C 复制→**快捷键**呼出独立窗口
