### ISSUE TITLE
百度翻译等字典查词无结果

### ISSUE THREAD

**Issue by azikabans** [crimx/ext-saladict#600]
反馈前请确保已阅读
反馈前请确保已阅读
反馈前请确保已阅读

- 使用说明： https://saladict.crimx.com/manual.html
- 常见问题以及答复： https://saladict.crimx.com/q&a.html

请根据模板描述问题，以便别人理解、定位和解决问题。
请根据模板描述问题，以便别人理解、定位和解决问题。
请根据模板描述问题，以便别人理解、定位和解决问题。

## 设备信息
 - 操作系统: 如 Window10 
 - 浏览器版本: 如 Google Chrome 78.0.3904.97
 - 沙拉查词版本: v7.5.4

## 描述问题

划词时，只有彩云小译，谷歌翻译（不是谷歌词典），柯林斯高阶这三个可以使用，使用其他的字典进行查词会一直无结果，我已经检查过网络，并且也开启了代理。

## 复现步骤

如何重复触发不正确的行为，如：

1. 打开任意一个网站......
2. 用鼠标选中一个单词......
3. 静待一会，会发现百度翻译，必应翻译等，其他翻译自带一直处于查询中......
4. 问题出现

## 期待的正常行为
正常情况下，全部字典都会显示翻译结果。

## 截图

![QQ截图20191221152834](https://user-images.githubusercontent.com/59109502/71304885-6a98ef00-2407-11ea-9292-6530075f50f4.png)

## 额外信息
2019/12/12-2019/12/14这段期间可以正常使用，并且可以正常使用百度翻译和必应翻译，2019/12/21就无法使用了

**Comment by azikabans** [comment]
截图好像没成功上传，我重新上传一次
![QQ截图20191221152834](https://user-images.githubusercontent.com/59109502/71304896-8d2b0800-2407-11ea-925c-424568037e45.png)

**Comment by azikabans** [comment]
算了，我重装了一遍，就可以正常使用了

**Comment by crimx** [comment]
![image](https://user-images.githubusercontent.com/6882794/71305460-94eeaa80-240f-11ea-9594-24797bc906a2.png)

测试没有问题的。

**Comment by crimx** [comment]
> 我已经检查过网络，并且也开启了代理。

如何检查的？你可以点击词典标题打开网页查看。

**Comment by azikabans** [comment]
如果这样设置的话，百度翻译就无法使用了。

CRIMX <notifications@github.com> 于2019年12月21日周六 下午4:35写道：

**Comment by crimx** [comment]
> 如果这样设置的话，百度翻译就无法使用了。

???

**Comment by azikabans** [comment]
刚刚图片好像没有成功发送

CRIMX <notifications@github.com> 于2019年12月21日周六 下午5:44写道：

**Comment by azikabans** [comment]
这样设置就无法使用百度翻译


CAn Ghost <kt260625694@gmail.com> 于2019年12月21日周六 下午9:56写道：

**Comment by azikabans** [comment]
如果我把可读取和更改网页数据的选项改为在某某网站上，就无法使用百度翻译
但是可以正常使用柯林斯高阶

CAn Ghost <kt260625694@gmail.com> 于2019年12月21日周六 下午9:57写道：

**Comment by azikabans** [comment]
CAn Ghost <kt260625694@gmail.com> 于2019年12月21日周六 下午9:58写道：

**Comment by azikabans** [comment]
CAn Ghost <kt260625694@gmail.com> 于2019年12月21日周六 下午9:58写道：

**Comment by crimx** [comment]
> 如果我把可读取和更改网页数据的选项改为在某某网站上，就无法使用百度翻译

请不要更改此设置，沙拉查词需要访问对应的词典服务器才能获取结果。

> 但是可以正常使用柯林斯高阶

这个可能是浏览器缓存的结果。

沙拉查词不会产生额外的流量，源代码开源，经历广大用户的检验，请放心使用。

**Comment by Cloudprogram** [comment]
例如comments就无法查询到牛津词典，只有commnent牛津词典才可以查询

**Comment by crimx** [comment]
@Cloudprogram  请不要搭楼反馈无关问题，你可以点开词典标题看官网结果，牛津高阶确实没有提供
<https://www.oxfordlearnersdictionaries.com/definition/english/comments>

**Comment by Cloudprogram** [comment]
> @Cloudprogram 请不要搭楼反馈无关问题，你可以点开词典标题看官网结果，牛津高阶确实没有提供
> https://www.oxfordlearnersdictionaries.com/definition/english/comments

我知道，我去官网看过了，就是牛津高阶确实有点low了，其他家的都提供了

**Comment by crimx** [comment]
牛津确实是主流几家中最抠门的嘻嘻

**Comment by Cloudprogram** [comment]
> 牛津确实是主流几家中最抠门的嘻嘻

刷新三观了，牛津词典不应该是最权威的么？剑桥词典也一样，搞得刚开始查询不到以为是bug，知道真相的我无力吐槽

**Comment by crimx** [comment]
牛津词典质量当然是可以的，但是很贵，开放的都是阉割的。

老牌词典权威但是不够灵活，网络词典灵活但是质量不稳定得甄别，没有完美的词典，这是沙拉查词存在的原因。

利用网络词典可以很容易找到原词，再结合沙拉查词的查词面板中继续查词既可。
