### ISSUE TITLE
add to notebook 弹框在点击取消按钮之后会再弹出一次

### ISSUE THREAD

**Issue by hu7may** [crimx/ext-saladict#601]
## 设备信息
 - 操作系统: 
 - 浏览器版本: 
 - 沙拉查词版本:

**Comment by hu7may** [comment]
add to notebook 弹框在点击取消按钮之后会再弹出一次。
当使用将单词添加到单词本的功能时，在“add to notebook 弹框”中点击save时功能正常，但如果是点击cancel，则在当前弹框小时之后会再弹出一次，需要再一次手动点击取消。

**Comment by crimx** [comment]
你好按你的描述我无法复现这个情况。你能提供详细的步骤么。

**Comment by crimx** [comment]
请编辑一楼并完整填写模板。
