### ISSUE TITLE
弹窗移动无法取消

### ISSUE THREAD

**Issue by ACtimeMask** [crimx/ext-saladict#602]
鼠标左键长按移动弹窗，松开应该为停止移动，但是在实际使用中无法中断，鼠标松开后，依然处于移动模式，只能将其拖动到上边界才可以脱离。在设置中，作为例子的弹窗，移动是正常的。

**Comment by crimx** [comment]
你好，因为信息不完全所以无法处理你的问题。请新开 issue 完整填写模板。
