### ISSUE TITLE
希望增加到PANTHERBAR  extensions

### ISSUE THREAD

**Issue by zhxiyao** [crimx/ext-saladict#605]
RT，Windows 下的 PopClip， 貌似这个软件还比较新鲜，上面能用的插件还比较少，但的确和mac下的POPCLIP神似，希望SaladDict可以通过PantherBar呼出，Quicher需要点击中键且出来的菜单也蛮大的，体验还是不如PopClip。
https://www.microsoft.com/zh-cn/p/pantherbar/9npz2tvkjvt7?rtc=1&activetab=pivot:overviewtab
https://pantherbar-app.com/

**Comment by crimx** [comment]
原理都是一样的（剪贴板 + Saladict 全局快捷键），你可以自行配置。

**Comment by hqyyqh** [comment]
这个也是可以的，使用[文档](http://pantherbar-app.com/create-extension)中的 `keyCombo` 选项或者在 `PowerShell` 脚本中调用快捷键就可以。有两个问题：

1. 弹窗貌似没有弹到最前面
2. PowerShell 脚本中还没有添加文本分段处理的部分，有兴趣可以再完善下

> 快捷键设置项【在独立窗口中搜索剪贴板内容】为 Alt+L，全局。
>[Saladict.zip](https://github.com/crimx/ext-saladict/files/4005179/Saladict.zip)，后缀`.zip` 改为 `.pbar`

![1123](https://user-images.githubusercontent.com/38676455/71515739-ec918800-28df-11ea-933a-2948bdea04a7.gif)

**Comment by zhxiyao** [comment]
Awesome！

**Comment by hqyyqh** [comment]
哈哈，我发现这个类似于 popclip 的软件用来做Saladict 的划词翻译还挺顺溜的。有内味了😂😂

**Comment by hqyyqh** [comment]
> Awesome！

我今晚把 Quicker 动作文本处理部分都搬了过来，PDF 中识别分段效果很好。除了没法截图翻译，作为桌面划词完全没问题！

**Comment by zhxiyao** [comment]
快捷鍵定義爲 ^(cc) 可用於goldendict 或者歐陸詞典

**Comment by leonsong09** [comment]
> 这个也是可以的，使用[文档](http://pantherbar-app.com/create-extension)中的 `keyCombo` 选项或者在 `PowerShell` 脚本中调用快捷键就可以。
> 
> > Pantherbar 大部分场合可用，在少数网页跟软件内不可用（例如 Acrobat）
> 
> ## 效果展示
> ### 划词操作
> ![PantherbarSaladict](https://user-images.githubusercontent.com/38676455/71808606-2f561b80-30a9-11ea-89ca-1ceb128d751f.gif)
> 
> ### 分段识别
> ![Segment](https://user-images.githubusercontent.com/38676455/71808629-3e3cce00-30a9-11ea-8941-fb8914396403.jpg)
> 
> ## PantherBar 沙拉查词扩展下载
> 快捷键设置项【在独立窗口中搜索剪贴板内容】为 Alt+L，全局（沙拉查词快捷键具体设置参考 #493 ）。下载文件后缀`.zip` 改为 `.pbar`，双击安装。
> 
> **自定义快捷键：** 如需自定义调用快捷键，下载压缩包后修改 `.ps1` 文件内的 `$ShortCut` 变量，重新压缩修改后缀即可。
> ![custom shortcuts](https://user-images.githubusercontent.com/38676455/71591644-0fce6880-2b68-11ea-8e74-df6955fc337e.jpg)
> 
> > [SaladictTranslate v1.8.zip](https://github.com/crimx/ext-saladict/files/4022902/SaladictTranslate.v1.8.zip)
> > fix: 删除空行
> > add: 标题判断
> 
> ### 历史版本
> > [SaladictTranslate v1.6.zip](https://github.com/crimx/ext-saladict/files/4010405/SaladictTranslate.v1.6.zip)
> > fix: 误判行末空白字符为分段
> 
> > [SaladictTranslate v1.4.zip](https://github.com/crimx/ext-saladict/files/4007678/SaladictTranslate.v1.4.zip)
> > 
> > 1. 解决 Powershell 输出到剪贴板的编码问题
> > 2. 完善识别分段功能，基本能够还原 PDF 的分段格式
> > 3. 替换 LaTeX 生成 PDF 中 `ﬂ ﬃ ﬁ ﬀ` 字符
> >    **（插件基本完美可用了）**
> >    ![Snipaste_2019-12-28_22-21-53_compress](https://user-images.githubusercontent.com/38676455/71545435-f097d580-29c5-11ea-92e4-2280511ec776.jpg)
> 
> > [SaladictTranslate v1.2.zip](https://github.com/crimx/ext-saladict/files/4006901/SaladictTranslate.v1.2.zip)
> > 增加标点识别分段
> 
> > [SaladictTranslate.zip v1.1](https://github.com/crimx/ext-saladict/files/4006673/SaladictTranslate.zip)
> > 增加是否删除分段选项
> > ![text](https://user-images.githubusercontent.com/38676455/71520382-ce835200-28f6-11ea-995e-f5e909c68f08.jpg)
> 
> > [SaladictTranslate.zip v1.0](https://github.com/crimx/ext-saladict/files/4005179/Saladict.zip)
> > 快捷键调用复制以及呼出沙拉查词窗口。

能问下您用的是什么pdf阅读器吗

**Comment by hqyyqh** [comment]
[PDF-XChange Editor](https://www.tracker-software.com/product/pdf-xchange-editor)

**Comment by leonsong09** [comment]
> RT，Windows 下的 PopClip， 貌似这个软件还比较新鲜，上面能用的插件还比较少，但的确和mac下的POPCLIP神似，希望SaladDict可以通过PantherBar呼出，Quicher需要点击中键且出来的菜单也蛮大的，体验还是不如PopClip。
> https://www.microsoft.com/zh-cn/p/pantherbar/9npz2tvkjvt7?rtc=1&activetab=pivot:overviewtab
> https://pantherbar-app.com/

我下载之后无法安装这个扩展，您安装成功了吗

**Comment by Sibyl233** [comment]
请问在其它pdf阅读器里可以使用么？比如在福昕阅读器里划词后正常出现pantherbar，但无法使用沙拉查词

**Comment by hqyyqh** [comment]
> 请问在其它 pdf 阅读器里可以使用么？比如在福昕阅读器里划词后正常出现 pantherbar，但无法使用沙拉查词

检查下是否按照说明配置了沙拉查词的全集快捷键为 Alt+L。

注：
pantherbar限制比较多，我目前没有使用了，扩展也有很长一段时间没有维护，无法确保正常使用。
Windows系统的沙拉查词我更推荐使用 Quicker #493
