### ISSUE TITLE
快捷键无响应

### ISSUE THREAD

**Issue by liang404001** [crimx/ext-saladict#606]
saladict版本从7.5.2自动更新到7.5.4之后，原本的Alt+快捷键无响应，导致无法使用quicker调用saladict，chrome版本79.0.3945.88，开始以为是chrome版本问题，换用78，76等版本后还是存在这个问题，后来重新下载7.5.2版本的saladict后任意chrome版本又都可以调用。但由于chrome插件静默升级的机制，会导致7.5.2自动升级到7.5.4，所以无法解决问题。不知道是不是我的个例。

**Comment by crimx** [comment]
是什么功能的快捷键无响应呢，提供了模板为什么不填写……
