### ISSUE TITLE
全局快捷键无响应

### ISSUE THREAD

**Issue by liang404001** [crimx/ext-saladict#607]
## 设备信息
 - 操作系统: 如 Window10
 - 浏览器版本: Chrome79.0.3945.88
 - 沙拉查词版本: 7.5.4

## 描述问题
为“独立窗口中搜索剪贴板内容”设置全局快捷键Alt+L，启用快捷键无响应。

## 复现步骤
1. 为“独立窗口中搜索剪贴板内容”设置全局快捷键Alt+L
2. 按下设置的快捷键Alt+L无响应。（什么事都没有发生）

## 期待的正常行为
按下快捷键后出现独立窗口

## 额外信息
1.  反复确认绝对没有快捷键冲突
2. 换用不同版本的chrome浏览器（包括78、76等均无效）
3.  将saladict从7.5.4降低到7.5.2之后快捷键可用，而且对任意测试版本chrome都能调用快捷键
4. 设置快捷键的目的是想用quicker调用saladict，快捷键失效导致quicker调用失效

**Comment by liang404001** [comment]
补充：降级成7.5.2版本之后可以解决，但因为chrome会自动升级插件，没有停止更新的选项，所以导致问题没有解决。（看到其他人没有反应这个问题，不知道是不是我的个例，重装chrome浏览器无效）

**Comment by crimx** [comment]
我按步骤设置可以正常调出窗口。

1. 测试快捷键的时候剪贴板确定有内容吗。
2. 换一个快捷键试试。
3. 尝试重启电脑。

**Comment by liang404001** [comment]
1.确定剪切板有内容
2.换快捷键的方法已经试过了，没有作用
3.重启过电脑无效
4.目前的解决办法就是将7.5.4降级到7.5.2，快捷键就可用了
5.如果是普遍现象常理来说其他人应该早就反应这个问题了，这几天没看到反馈，可能是我的个例，但不知道7.5.2为何有效

**Comment by crimx** [comment]
因为 7.5.3 重写了独立窗口逻辑。

有另外一个快捷键是打开或高亮独立窗口，你试试那个有无反应。

**Comment by liang404001** [comment]
为“打开独立词典窗口”设置快捷键一样是没有反应的，对其他快捷键也进行了测试，除了“打开独立词典窗口”和“独立窗口中搜索剪贴板内容”均有效。

**Comment by crimx** [comment]
有可能是某些设置导致了创建失败。

在这个 github 页面上先刷新一遍，然后按三遍 ctrl 能调出查词面板吗？

如果可以的话，让其失焦，再按「打开独立词典窗口」的快捷键可以让其重新聚焦到前台不？

如果不行的话请留个邮箱，我发个测试版给你试试。

**Comment by liang404001** [comment]
按三遍 ctrl 测试了并不能调出查词面板。（邮箱：liang404001@163.com）

**Comment by crimx** [comment]
[chrome.zip](https://github.com/crimx/ext-saladict/files/4005096/chrome.zip)

直接上传这里了，你下载用开发者模式加载试试。

**Comment by liang404001** [comment]
![image](https://user-images.githubusercontent.com/43444320/71514899-9fabb280-28db-11ea-8f8f-030cf534cff1.png)

**Comment by liang404001** [comment]
能接收到快捷键，还是没有弹出独立窗口

**Comment by crimx** [comment]
创建失败了，不清楚什么原因。你点击扩展管理的 background.html 看看有没有异常？

**Comment by liang404001** [comment]
![image](https://user-images.githubusercontent.com/43444320/71515201-15fce480-28dd-11ea-94de-4afbbd599a88.png)
是这个吗

**Comment by crimx** [comment]
哦哦，是坐标小数问题？但是为什么只有你的系统出问题？

**Comment by liang404001** [comment]
这个我也不太清楚。。。电脑买了不到1年

**Comment by crimx** [comment]
[chrome.zip](https://github.com/crimx/ext-saladict/files/4005156/chrome.zip)

约了整数，你看看这个可以了没有。

**Comment by crimx** [comment]
有可能是屏幕分辨率的关系，你的系统对屏幕缩放出现了半个像素的计算，所以导致了创建出现问题。

**Comment by crimx** [comment]
之前的版本有做取整，这个版本没有加上所以导致这个 bug。

**Comment by liang404001** [comment]
确实可以了，感谢。只是现在导入的是文件夹，每次都会弹出“请停用以开发者模式运行的扩展程序”。不知道下一个版本什么时候会上chrome的应用商店？

**Comment by crimx** [comment]
明年前会有最后一次更新。
