### ISSUE TITLE
对‘独立窗口查词功能’的一些建议

### ISSUE THREAD

**Issue by huanglusong** [crimx/ext-saladict#608]
**我所使用的操作系统、浏览器和沙拉查词版本**
1、操作系统win10
2、浏览器chrome
3、沙拉查词版本76.0
**请描述目前使用沙拉查词遇到什么不便**

您好，我经常使用沙拉查词这个软件，但是有2个痛点希望开发者可以改进
1、当我的沙拉查词独立窗口在后台运行时，在浏览器中的划词功能就失效了
2、在独立窗口进行生词记录到记事本后，即点击红心后会触发浏览器打开生词本网页，即使之前已经打开还是会重复打开多个，这样子的使用体验很糟糕

**用图片复现我所提到的问题吧**
1、第一个问题复现
![第二个问题](https://i.loli.net/2019/12/30/uVfgopXzTPC4q8k.gif)
![第一个问题](https://raw.githubusercontent.com/huanglusong/imageReposity/master/小书匠/1577683756394.gif)
2、第二个问题复现
**理想情况下，沙拉查词应该怎么做**

1、第一个问题：独立窗口在后台运行时，浏览器中可以正常地进行划词操作
2、第二个问题：在独立窗口中添加生词弹出生词本，希望不会重复弹出生词本窗口，有一个就够了

**Comment by crimx** [comment]
1. 见[使用说明](https://saladict.crimx.com/manual.html#triple-ctrl)，在设置「快捷查词」下打开「响应页面划词」。
2. 这里面如何互相通讯我还没时间整理，目前你先添加完就把生词本关掉。
