### ISSUE TITLE
建议把英文的collins也加入

### ISSUE THREAD

**Issue by wisecrick** [crimx/ext-saladict#610]
## 词典名称以及链接

https://www.collinsdictionary.com/

## 沙拉查词的已有的词典为什么不能满足？

喜欢先看纯英文的词典

**Comment by crimx** [comment]
> 喜欢先看纯英文的词典

这不足以说明问题。沙拉查词已有的英英词典为什么不能满足？

**Comment by crimx** [comment]
柯林斯在设置可关闭双语。

**Comment by wisecrick** [comment]
沙拉有双解的collins，想先看看能否自己理解纯英文的，不能再看中文的翻译

没有发现如何关闭

**Comment by crimx** [comment]
目前只能二选一，这个快速切换功能太小众暂时不会考虑添加。如果对英文水平有限的话可以柯林斯双语结合麦克米伦，或者英英柯林斯结合其它中英词典。
