### ISSUE TITLE
建议加入Free Dictionary

### ISSUE THREAD

**Issue by wisecrick** [crimx/ext-saladict#611]
## 词典名称以及链接

https://www.thefreedictionary.com/

## 沙拉查词的已有的词典为什么不能满足？

这个就包括了多本词典
美国传统等等

**Comment by crimx** [comment]
> 这个就包括了多本词典  
> 美国传统双解等等

你好，这个理由不是很能说明为什么沙拉查词的已有的词典不能满足。

**Comment by wisecrick** [comment]
这个网站提供的是给母语人士用的词典，已有的基本是给非母语人士用的学习词典

**Comment by crimx** [comment]
> 这个网站提供的是给母语人士用的词典，已有的基本是给非母语人士用的学习词典

这个理由也是非常勉强呢。沙拉查词已有的柯林斯（英英）和麦克米伦也都是面向母语人士的专业词典。另外还有 urban dictionary 和 etymoline。

**Comment by crimx** [comment]
你遇到了什么单词无法找到合适的释义么。

**Comment by wisecrick** [comment]
就和merriam-webster与merriam-webster advanced learner 是一样的区别
还有oxford english与oxford advanced learner's一样的区别

英专最后都要求查前者

**Comment by crimx** [comment]
> 英专最后都要求查前者

你好，沙拉查词的目的是用于获取单词在特定上下文中的含义，不会围绕英专的教学大纲去实现功能。

你推荐的几个词典各有千秋，但互相重叠的部分也是巨大的。如果没有明显的目前组合无法解决的优势暂时不考虑添加进来。

**Comment by wisecrick** [comment]
你已经有了merriam-webster learner，为什么不加merriam-webster呢？
已经有的基本都是学习词典

**Comment by crimx** [comment]
> 你已经有了merriam-webster learner，为什么不加merriam-webster呢？

因为前者因历史原因已存在沙拉查词中，而每新增一个词典都需要投入时间成本，目前是我在义务维护，接下来沙拉查词只会新增有明确意义的功能。

> 已经有的基本都是学习词典

前面提到的词典覆盖常见母语场景是毫无问题的。如果是英专学生需要专门研究英语语言的话这个受众面太小，沙拉查词不会特别针对实现功能。

**Comment by liinyun** [comment]
> > 这个网站提供的是给母语人士用的词典，已有的基本是给非母语人士用的学习词典
> 
> 这个理由也是非常勉强呢。沙拉查词已有的柯林斯（英英）和麦克米伦也都是面向母语人士的专业词典。另外还有 urban dictionary, google dictionary 和 etymoline。

你的etymoline 可以展开吗，我的好像不行，只能点击后跳转到他们的网页看
