### ISSUE TITLE
自带PDF阅读器打开本地pdf文件出现跨域问题

### ISSUE THREAD

**Issue by WangYuLue** [crimx/ext-saladict#612]
## 设备信息
 - 操作系统: mac 10.14.6
 - 浏览器版本: chrome79
 - 沙拉查词版本: 7.6

## 描述问题
自带PDF阅读器打开本地pdf文件出现跨域问题

## 复现步骤
1、将本地pdf文件拖进浏览器
2、右击又上角的灰色沙拉查词图标
3、选择 '在PDF阅读器中打开'
4、弹出一个新窗口，但是新窗口没有出现pdf文件，并且报如下错误：

## 期待的正常行为

预期可以打开PDF文件，并且可以使用沙拉查词

## 截图

![屏幕快照 2019-12-31 下午1 23 16](https://user-images.githubusercontent.com/19245919/71611078-48565c80-2bd1-11ea-9d8e-5c9a3bd45287.png)

**Comment by crimx** [comment]
按[初次使用说明](https://saladict.crimx.com/notice.html)开启了允许访问本地链接了吗？

**Comment by WangYuLue** [comment]
已解决，谢谢🙏
