### ISSUE TITLE
结合Anki导入，但是不能正确导入翻译字段信息，详见下方截图

### ISSUE THREAD

**Issue by tiankonghenlan20113046** [crimx/ext-saladict#616]
## 设备信息
- 操作系统: [Window10] 
-浏览器版本：[Chrome 版本 79.0.3945.88（正式版本） （64 位)]
- Saladict版本：[7.6.0]

## 描述问题

你好，通过Anki，不能将上下文翻译的内容成功映射到卡片的反面，只有[::google::]的字样

## 复现步骤

1. 按照[操作说明](https://saladict.crimx.com/anki.html#note-type)把生词本导入到桌面
2. 通过Anki客户端进行设置
3. 通过Anki进行导入
4. 在导入页面，发现映射不正确，但是差找不到解决原因
## 期待的正常行为

在卡片的反面，有上下文的翻译。

## 截图

1. 按照操作说明，导出生词本
![image](https://user-images.githubusercontent.com/10166585/71759532-4c43f080-2ee9-11ea-976b-fd5aec78f0d2.png)
2. 导出的生词本如图所示
![image](https://user-images.githubusercontent.com/10166585/71759538-6d0c4600-2ee9-11ea-9c52-48db84490c3f.png)
3. 按照操作进行字段设置
![image](https://user-images.githubusercontent.com/10166585/71759551-bb214980-2ee9-11ea-92b5-1035624973e0.png)
![image](https://user-images.githubusercontent.com/10166585/71759557-c70d0b80-2ee9-11ea-9976-a1eb6b8d72c4.png)
4. 导入生词本
![image](https://user-images.githubusercontent.com/10166585/71759563-f4f25000-2ee9-11ea-8789-4b1592eef233.png)

![image](https://user-images.githubusercontent.com/10166585/71759569-0b001080-2eea-11ea-9963-d0ab7952772b.png)
![image](https://user-images.githubusercontent.com/10166585/71759587-426ebd00-2eea-11ea-906b-6a6918167de5.png)
wei未导入生词本中的英文
5.反面卡片的显示
![image](https://user-images.githubusercontent.com/10166585/71760291-49033180-2ef6-11ea-9d99-a3fd0350a8a1.png)

## 额外信息

严格按照导出的格式导入的，不晓得是哪里出了问题。

**Comment by crimx** [comment]
谢谢你的反馈，这个教程我更新一下。这是因为后来自动翻译加入了换行的原因，Anki 是以行为单位录取的，所以如果要导出到 Anki 需要把保留换行选 <br> 或者 <p>，然后 Anki 中导入的面板勾选 Allow HTML in fields.

**Comment by tiankonghenlan20113046** [comment]
> 谢谢你的反馈，这个教程我更新一下。这是因为后来自动翻译加入了换行的原因，Anki 是以行为单位录取的，所以如果要导出到 Anki 需要把保留换行选 `<br>` 或者 `<p>`，然后 Anki 中导入的面板勾选 `Allow HTML in fields`。

谢谢采纳。按照你的方法去做，已经搞好了。

**Comment by ankifyh** [comment]
hi！ 你邮件发错人了吧！



---原始邮件---
发件人: "DC_Woog"<notifications@github.com&gt;
发送时间: 2020年1月4日(周六) 晚上6:11
收件人: "crimx/ext-saladict"<ext-saladict@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [crimx/ext-saladict] 结合Anki导入，但是不能正确导入翻译字段信息，详见下方截图 (#616)


 
谢谢你的反馈，这个教程我更新一下。这是因为后来自动翻译加入了换行的原因，Anki 是以行为单位录取的，所以如果要导出到 Anki 需要把保留换行选 <br&gt; 或者 <p&gt;，然后 Anki 中导入的面板勾选 Allow HTML in fields。
  
谢谢采纳。按照你的方法去做，已经搞好了。

**Comment by crimx** [comment]
@ankifyh 你在 watch 这个仓库所以会收到 Github 邮件提醒……点击仓库 Github 顶端的 <kbd>Unwatch</kbd> 取消。
