### ISSUE TITLE
关于沙拉查词的token的问题

### ISSUE THREAD

**Issue by cindylababy** [crimx/ext-saladict#617]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 请描述目前使用沙拉查词遇到什么不便

我就是想问下作者在使用各个平台的在线翻译 API 的时候是使用自己的账号的 token 吗？
使用的人多了之后平台会不会向您收费啊？
有没有考虑提供用户填写自己 token 的方式？

**Comment by crimx** [comment]
你好，目前无需担心这个问题。如果你是自行编译沙拉查词按 README 的说明设置 token 就可以。
