### ISSUE TITLE
打开独立窗口后划词搜索功能失效

### ISSUE THREAD

**Issue by steven-em** [crimx/ext-saladict#618]
## 设备信息
- 操作系统: [Windows7, Debian 8] 
- 浏览器版本: [Chrome79] 
- 沙拉查词版本: [v7.6.0] 

## 描述问题

打开独立窗口（连续按3次ctrl）后再关闭，划词搜索功能就无效了，必须重启浏览器才能恢复。
Firefox浏览器无此问题。

**Comment by crimx** [comment]
非常抱歉，在修复前请暂时在快捷查词设置中关闭响应页面划词。

**Comment by crimx** [comment]
已修复
