### ISSUE TITLE
直接打开独立窗口查询

### ISSUE THREAD

**Issue by steven-em** [crimx/ext-saladict#619]
## 设备信息
- 操作系统: [Debian8] 
- 浏览器版本: [chrome79] 
- 沙拉查词版本: [7.6.1] 

## 请描述目前使用沙拉查词遇到什么不便

我想用shell命令直接打开词典独立窗口，并查询clipboard内容，而不必先打开chrome浏览器，
不知道有无方法实现？

**Comment by crimx** [comment]
Chrome 可以设置保持后台运行，然后开机启动 Chrome 即可。

全局快捷键不需要 shell，未来考虑实现原生的通讯（浏览器扩展支持通过 stdin 和 stdout 通讯），但这个计划比较遥远了。
