### ISSUE TITLE
彩云小译调不出来

### ISSUE THREAD

**Issue by SAKURA96** [crimx/ext-saladict#625]
## 设备信息
- 操作系统: [] windows10-64bit  ，系统语言English-UK
- 浏览器版本: [] Version 79.0.3945.117 (Official Build) (64-bit)
- 沙拉查词版本: [] 2020/1/13安装的

## 描述问题

勾选了notebook--Context Translate Engines--LingoCloud,在使用的时候没看到这个翻译

## 期待的正常行为

能有彩云小译的翻译结果

## 截图

![image](https://user-images.githubusercontent.com/38367662/72335352-d23a1580-36f9-11ea-933a-86dcebaae518.png)

**Comment by crimx** [comment]
你这是在设置生词编辑器自动翻译的词典，看左边的导航。

**Comment by crimx** [comment]
选项下方也有灰色的文字对这个选项进行说明。

**Comment by sambodhi-cn** [comment]
彩云小译和搜狗都不出翻译结果了。

**Comment by sambodhi-cn** [comment]
彩云小姨刚刚好了，但搜狗一直不显示。

**Comment by crimx** [comment]
请不要搭楼反馈不相关问题，先按[常见问题及答复]https://saladict.crimx.com/q&a.html#%E9%97%AE-%E6%9F%90%E4%B8%AA%E8%AF%8D%E5%85%B8%E4%B8%80%E7%9B%B4%E6%97%A0%E7%BB%93%E6%9E%9C%EF%BC%8C%E9%82%A3%E6%80%95%E6%98%AF%E6%9F%A5%E7%AE%80%E5%8D%95%E7%9A%84%E5%8D%95%E8%AF%8D%E3%80%82)自行排除网络问题。

**Comment by yummic** [comment]
截图左边设置的是加入生词本时，上下文翻译使用的翻译选项；
截图右边显示的翻译结果是在“词典设置/Dictionaries" 设置的自动翻译选用的词典；

这两个没有关联。

显示彩云的功能在这里，如下示例图：
![caiyun](https://user-images.githubusercontent.com/3368182/72580001-ac895800-3915-11ea-9fdd-0e48533de276.png)
