### ISSUE TITLE
查词面板搜索框无法输入空格

### ISSUE THREAD

**Issue by 103rd** [crimx/ext-saladict#627]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [ 79.0.3945.117（正式版本） （64 位）] 
- 沙拉查词版本: [Saladict v7.6.1] 

## 描述问题

在某些网页，查词面板搜索框无法输入空格

## 复现步骤

在使用《gre考满分》网站做练习题时，发现在练习过程中，使用沙拉查词，在非独立窗口模式时，无法在查词面板搜索栏输入空格，其他字符都可以输入，也可以使用delete，唯独空格输入没反应

[网站链接：http://gre.kmf.com/practise/exercise/1028/157916661354284644/cfcd0r/0/0/0/0/0](http://gre.kmf.com/practise/exercise/1028/157916661354284644/cfcd0r/0/0/0/0/0)
ps：其他网页上都可以正常运行

感谢作者，很好的插件，刷题利器
## 截图

![image](https://user-images.githubusercontent.com/56637192/72515348-b3b75400-388a-11ea-9eb0-8ce3567705a8.png)

## 额外信息

试过重装浏览器，清除缓存，重装插件，排查过插件冲突，也换了两台电脑试，都没有用

**Comment by crimx** [comment]
似乎是这个网页劫持了按键？暂时没能发现是什么原因。你可以用独立窗口，可以结合侧边栏模式使用。

**Comment by 103rd** [comment]
谢谢！

很奇怪，这个网站的练习题库会出这种问题，但是模考题库就没问题。

只是用独立窗口写note添加生词本比较麻烦，要跳转一下网页，效率稍微低一点。不过已经很满意了！

再次感谢！

**Comment by crimx** [comment]
生词编缉面板未来也会做成独立窗口。因为不清楚问题来源这个网页就不做特殊兼容了。
