### ISSUE TITLE
无法添加单词到生词本

### ISSUE THREAD

**Issue by gcl916** [crimx/ext-saladict#628]
使用chrome时候，无法添加单词到单词本。扇贝已登录。
如图
![image](https://user-images.githubusercontent.com/59955021/72523840-f2381900-3860-11ea-905f-3c9cefcfb743.png)

## 设备信息
- 操作系统: [] Win10
- 浏览器版本: [] Google Chrome 版本 79.0.3945.117（正式版本） （64 位）
- 沙拉查词版本: [] 版本  7.6.1

**Comment by crimx** [comment]
需要扇贝生词库里面有的单词才能添加
