### ISSUE TITLE
新版edge上，扩展不工作

### ISSUE THREAD

**Issue by xiongtao0201** [crimx/ext-saladict#629]
## 设备信息
- 操作系统: [] 
window10
- 浏览器版本: [] 
基于chromium的edge  版本 79.0.309.65 (官方内部版本) (64 位)
- 沙拉查词版本: [] 
7.5.1

## 描述问题

就是不能用，我是在edge的商店下载的，不是在chrome商店下载的

## 截图

![image](https://user-images.githubusercontent.com/25071472/72583694-2a536080-3922-11ea-823f-2b7323c85cad.png)

**Comment by crimx** [comment]
见 #556

**Comment by rumosky** [comment]
edge商店已更新，请重新安装即可使用。目前最新版是7.6.2
由于微软审核较慢，可能会落后Chrome商店若干个版本
