### ISSUE TITLE
When this plugin was turned on, PDF cannot be loaded

### ISSUE THREAD

**Issue by MrMorning** [crimx/ext-saladict#630]
## Device info
 - OS: Ubuntu 19.10
 - Browser Version Firefox 72.0.1
 - Saladict Version 7

## Describe the bug
When the plugin is turned on, it seems that the pdf reader of firefox doesn't work anymore. When you click on a pdf file, it just opens a regular pdf framework but doesn't load the exact pdf file. I've tried reinstall the plugin but it doesn't work.

## To Reproduce
1. Click on any online pdf file, [such as](http://vision.stanford.edu/teaching/cs131_fall1920/slides/02_filters.pdf)

## Screenshots
![1ZyZH1.md.png](https://s2.ax1x.com/2020/01/24/1ZyZH1.md.png)

## Additional context
I think it may be related to the version of the browser.
祝作者新年快乐❤

**Comment by crimx** [comment]
The url you provided ends with `.pdf` but does not point to a pdf file directly. That is why you cannot load it on the fly (even with the browser built-in PDF viewer).

**Comment by MrMorning** [comment]
> The url you provided ends with `.pdf` but does not point to a pdf file directly. That is why you cannot load it on the fly (even with the browser built-in PDF viewer).

Then is there any method to load such urls via saladict?

**Comment by crimx** [comment]
I'll take the night to fix that.
