### ISSUE TITLE
是否考虑做一个网站出来

### ISSUE THREAD

**Issue by johannhuang** [crimx/ext-saladict#631]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 额外信息

也就是希望把目前的插件模式变成一个类似于Google的搜索引擎搜索框查词。

感觉大部分代码是可以通用的，网站的优势是，可以集成到Goldendict、欧陆词典等软件中使用。

更多信息 https://www.pdawiki.com/forum/thread-38310-1-1.html

**Comment by crimx** [comment]
你好，谢谢建议！不会做网站。

1. 没有计划义务提供服务器。
2. 版权问题。

**Comment by johannhuang** [comment]
其实做Chrome插件和做网站差不多一样吧。也可以使用GitHub Pages作为服务器。反正都是纯前端的东西，GitHub Pages完全可以胜任的。

**Comment by crimx** [comment]
无服务器不能跨域的。

**Comment by johannhuang** [comment]
前端跨域确实是个问题，但是Chrome Extension允许了突破，是否也考虑做一个Chrome App的版本呢？（虽然有传言Chrome计划砍掉Chrome App功能）
其实我这里的核心建议就是，改变查词模式，使能够专注的在一个页面上，通过键入关键词进行词典查询。类似于搜索引擎，只不过搜索出来的内容就是现在沙拉查词的内容。

**Comment by crimx** [comment]
Chrome App 请阅读[常见问题及答复](https://saladict.crimx.com/q&a.html)。

> 其实我这里的核心建议就是，改变查词模式，使能够专注的在一个页面上，通过键入关键词进行词典查询。类似于搜索引擎，只不过搜索出来的内容就是现在沙拉查词的内容。

查词面板可以钉住，或者独立窗口的侧边栏模式也能并排显示。

**Comment by KnIfER** [comment]
做成供个人使用的内网服务站点如何？
相当于运行在浏览器中的软件。
PC版概念图：
![20200801_213054_SchivoNo 0_GifNo 0](https://user-images.githubusercontent.com/11593903/89102808-1941eb00-d43f-11ea-8a66-778cf268b1d0.gif)
图中我在一个javafx_webview+nanohttpd环境中稍做测试，不算成功，释义都没有加载出来，只有词典标题……


如果真能做成这样，甚至可以把沙拉词典搬进安卓浏览器。

想象一个自带沙拉聚合词典的移动端浏览器！

还可以搭配即点即译模式，试想下图弹窗里，内容是沙拉词典聚合的内容，甚至可以随时放大、固定弹窗，变成普通的标签页……

**Comment by KnIfER** [comment]
![SVID_20200801_214330_1_SchivoNo 0_SchivoNo 0_GifNo 0](https://user-images.githubusercontent.com/11593903/89102980-c9642380-d440-11ea-9d08-49d09f3a5929.gif)

**Comment by crimx** [comment]
沙拉查词支持触摸模式，用支持扩展的移动端浏览器（如火狐）也可以运行。但是对于手机屏目前没有时间做体验优化。

**Comment by KnIfER** [comment]
跨域问题好像无解了……

安卓浏览器支持扩展似乎都是自带内核的。

我打算直接上iframe，然后用onload事件修改页面……

下面这个提示框没有跨域问题把？

![salad-autocomplete](https://github.com/KnIfER/tuChuang/blob/master/salad-autocomplete.jpg?raw=true)

**Comment by KnIfER** [comment]
怎么弄成普通网页呢，编译后的backgroud.js里面是个奇怪的数组，引用了也不执行。v5.3版本的可以通过引入backgroud.js使监听生效：
![Screenshot (627)](https://user-images.githubusercontent.com/11593903/89117974-b0a54d80-d4d4-11ea-85d6-4885db760399.jpg)

新的版本怎么改呢？

**Comment by KnIfER** [comment]
现修改 v6.33.2，这也是最后一个在release中附crx的。

https://github.com/crimx/ext-saladict/releases?after=v7.0.4

我的目的是最终在安卓套壳浏览器中使用。至于那些支持插件的，都是自带内核的，原生无法实现。

关于跨域，浏览器对iframe的限制更加严格，父窗口无法修改别人的网页。所以还是决定搬沙拉查词。这样，chrome上可以调试；安卓那边也可以拦截资源，然后手动添加`headers.put("Access-Control-Allow-Origin", "*");`允许跨域。

先直接修改编译后的代码，成功后再改源代码，因为，编译太慢了。。。

现在是内容和提示都能显示了。

**Comment by crimx** [comment]
安卓我不太清楚。为什么一定要原生内核？

沙拉查词的[下载页面](https://saladict.crimx.com/download.html)提供了最新的 crx 供下载。

另外手机上用欧路词典也是挺不错的。

**Comment by KnIfER** [comment]
总算搬完了：
![](https://upload-images.jianshu.io/upload_images/2253897-29472d32aedabf1f.jpg)
设置页也可以用，不过比较麻烦，字体挤一块儿了。

**Comment by KnIfER** [comment]
初步实现saladict和mdx服务的联合！

在getALlDicts之前，先向服务端请求一个**json**，里面放mdx**词典的定义**，比如牛津词典：`OED2:
{"OED2":{"host":"http://127.0.0.1:8080/OED2/%s.json", "title":"牛津英语词典(来自mdx伺服)"}}`。直接用文件名当作词典ID。

getALlDicts之时，动态地将mdx词典装载到返回结果中。(为了不存储请求来的**词典定义**，将之以` Object.defineProperty`隐式挂到dict对象。)
```
var ret = {
    baidu: baidu(),
    ……
}
var dict=mdx() as any
ret ['OED2'] = dict

  Object.defineProperty(dict, "TEST", { enumerable: false, writable:true })
  exta1.TEST = {
    host : json.host,
    title : json.title,
  }

```

然后是渲染，我让服务端直接返回查询结果的html，然后react组件中这样：
```
<div dangerouslySetInnerHTML={ {__html:result.html}}/>
```

暂无css，打算放在**词典定义**中处理。

![Screenshot (636)](https://user-images.githubusercontent.com/11593903/90161123-44282980-ddc5-11ea-809a-f42c3a1ecc76.jpg)
