### ISSUE TITLE
"保留换行"换成"将换行替换为<br>"时,文本会发生变化

### ISSUE THREAD

**Issue by playdougher** [crimx/ext-saladict#632]
## 设备信息
- 操作系统: [win10] 
- 浏览器版本: [Chromium 78.0.3904.108] 
- 沙拉查词版本: [v] 

## 描述问题

在将单词导出时,选择"保留换行"和"将换行替换为<br>",一些文本会发生变化,导致在导入anki时格式显示出现问题.

## 复现步骤
选择"保留换行": 
![1](https://user-images.githubusercontent.com/26463515/73588643-88796980-4506-11ea-9cb2-9a32642a77eb.png)
选择"将换行替换为`<br>`": 
![2](https://user-images.githubusercontent.com/26463515/73588659-ae067300-4506-11ea-9516-27165c391708.png)

## 期待的正常行为

希望`<b><u>`不会变成其他字符

**Comment by crimx** [comment]
在导入 Anki 时开启 [Allow HTML in fields](https://saladict.crimx.com/anki.html#%E5%AF%BC%E5%85%A5%E5%8D%95%E8%AF%8D) 了吗。

**Comment by playdougher** [comment]
开启了,从文本到anki没问题.

**Comment by crimx** [comment]
所以你的问题解决了吗？

如果没有解决很可能是这个上下文本身是这样的？沙拉查词生词本导出不会做这样的处理。

**Comment by crimx** [comment]
如果你能提供单词的来源页面我可以测试一下。

**Comment by playdougher** [comment]
有开启. 问题在于导出的时候若想选择"换行替换为`<br>`",翻译的文本里就不能有`<b><u>`这些,因为一选择"换行替换为`<br>`",`<b><u>`就变成了`&lt;b&gt;&lt;u&gt;`. 
在导入anki后,`&lt;b&gt;&lt;u&gt;`显示为`<b><u>`,而软件替换的`<br>`能正常转化成换行.
![1](https://user-images.githubusercontent.com/26463515/73589431-57526680-4511-11ea-9a26-e76460e453c4.png)
![2](https://user-images.githubusercontent.com/26463515/73589432-591c2a00-4511-11ea-831b-44aa2ea998ca.png)

**Comment by playdougher** [comment]
> 所以你的问题解决了吗？
> 
> 如果没有解决很可能是这个上下文本身是这样的？沙拉查词生词本导出不会做这样的处理。

没有解决,那个<b><u>是我自己加的,因为我想把单词翻译在句子中加粗加斜线,这样在anki里会比较容易看出单词解释.然后就出现了这问题.

**Comment by crimx** [comment]
啊，想起来了，这个转义是为了避免内容错误被解析为 HTML。我忘了提供一个开关。

**Comment by playdougher** [comment]
哇, 我竟然找到个bug, 坐等修复.

**Comment by crimx** [comment]
已修复
