### ISSUE TITLE
WebDAV应用密码以明文的方式包含在导出的配置文件中会不会不太安全？

### ISSUE THREAD

**Issue by wenlzhang** [crimx/ext-saladict#633]
## 设备信息
- 操作系统: Windows 10 
- 浏览器版本: Chrome 79 
- 沙拉查词版本: v7.7.6 

## 请描述目前使用沙拉查词遇到什么不便

设置WebDAV并导出配置文件后，发现WebDAV应用密码以明文的方式包含在其中。个人对WebDAV没有深入的了解，感觉这样是不是会不太安全？

## 理想情况下，沙拉查词应该怎么做

配置文件中对WebDAV应用密码进行加密处理，或者不将与WebDAV相关的信息包含在导出的配置文件中。

**Comment by crimx** [comment]
沙拉查词是开源的，任何自动化处理有心人很容易就可以逆向。

WebDAV 的设置不会随浏览器同步，即便你安装了恶意扩展也无法访问沙拉查词存的数据。

如果是为了转移设置到另外浏览器，导入之后就可以删除掉；如果需要存储备份，可以对导出的文件自行压缩加密处理。
