### ISSUE TITLE
请求黑夜模式(dark mode)

### ISSUE THREAD

**Issue by zivshek** [crimx/ext-saladict#634]
## 设备信息
- 操作系统: [Windows 10] 
- 浏览器版本: [Chrome79] 
- 沙拉查词版本: [不知道怎么看，应该是最新版，自动升级的] 

## 请描述目前使用沙拉查词遇到什么不便

我一直用着[Dark Reader](https://github.com/darkreader/darkreader)插件，所有的网页都会以黑夜模式显示，看的很舒服不刺眼，但沙拉查词仍然是以亮白显示，与网页形成鲜明对比。

## 理想情况下，沙拉查词应该怎么做

增加一个黑夜模式。

## 替代方案

[Dark Mode in CSS](https://css-tricks.com/dark-modes-with-css/)

**Comment by crimx** [comment]
读使用说明
