### ISSUE TITLE
空格转义错误导致查不到词组

### ISSUE THREAD

**Issue by zen010101** [crimx/ext-saladict#635]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Edge chrome版本 版本 79.0.309.71 (官方内部版本) (64 位)] 
- 沙拉查词版本: [Latest] 

## 描述问题

"out of the question" 用Collins词典查词的时候，对空格的转义存在问题导致查不到单词。对比下面两个URL，第一个是Collins官网自己生成的URL，第二个是沙拉生成的。

https://www.collinsdictionary.com/dictionary/english/out-of-the-question
https://www.collinsdictionary.com/dictionary/english/out%20of%20the%20question

## 复现步骤

1

## 期待的正常行为

1

## 截图

1

## 额外信息

1

**Comment by crimx** [comment]
谢谢反馈！
