### ISSUE TITLE
能不能增加点击单词后就弹出释义窗口呢？

### ISSUE THREAD

**Issue by redstoneleo** [crimx/ext-saladict#637]
我在安卓版的kiwi浏览器上面安装了这个插件，发现能用，只是需要长按选中单词之后才会有释义窗口，能不能增加点击单词后就弹出释义窗口呢？这样子会更便捷一点。
我搜了下本项目的源码，发现源代码是以ts为后缀的文件，这让懂一点js的我不知道该去哪里增加这个功能，阁下如果不想实现这个功能的话，希望指点我实现这个功能，谢谢！

**Comment by crimx** [comment]
你可以设置在相关查词模式中开启双击。
请阅读[使用说明](https://saladict.crimx.com/manual.html)。

**Comment by redstoneleo** [comment]
单击不是比双击更便捷吗？

**Comment by crimx** [comment]
才看到是说安卓上……选词因为之前一并监听了触摸事件所以能用。

沙拉查词的悬浮取词功能实现了获取特定坐标周围的词语，所以理论上实现点按也是可以的，但是会有点工作量。还需要处理多个查词模式，以及查词面板响应，添加相关设置界面。

因为我很少在移动设备上使用所以目前没有计划实现。如果你有兴趣的话可以看 
- `src/selection` 这里处理划词
- `src/content/redux/modules/reducer/new-selection.handler` 处理查词面板响应
- `src/options/components/options/` 下的
  - `SearchModes` 三个查词模式
  - `QuickSearch` 独立窗口有自己的查词模式

**Comment by redstoneleo** [comment]
比较复杂，我目前干不了。谢谢！
