### ISSUE TITLE
日语网页（雅虎日本）划词翻译问题：除了谷歌翻译为【日→中 】之外，其他翻译均为【中→英】

### ISSUE THREAD

**Issue by zhr3051** [crimx/ext-saladict#638]
![image](https://user-images.githubusercontent.com/52150513/73827434-80893480-483a-11ea-81d1-2269a607994c.png)

![image](https://user-images.githubusercontent.com/52150513/73827591-cc3bde00-483a-11ea-9166-ded14b60cb22.png)

**Comment by zhr3051** [comment]
不知道类似于这种自己可以选择X→Y的功能 怎么设置...
![image](https://user-images.githubusercontent.com/52150513/73828837-f098ba00-483c-11ea-8526-88e5b6fec420.png)

**Comment by crimx** [comment]
沙拉查词的语言识别目前是基于字符匹配，一些机器翻译如谷歌会使用自带识别服务。你可以在对应的词典设置中设置汉字的识别方式。

**Comment by ShadowLyin** [comment]
我也有同样的问题，已尝试设定彩云小译与腾讯翻译君的词典设置内的目标语言为中文，但是翻译时仍然显示英文，每次翻译必须手动在划词翻译界面手动更改来源语言和目标语言才行（截图如下），另外经测试只有划词部分只包含假名时识别语言才正确。
操作系统：Windows 10 1909
浏览器版本：firefox 73.0.1
沙拉查词版本：7.8.0
具体操作：翻译 https://ci-en.dlsite.com/creator/391/article/210640 中的

> ASMR音源配布+無料で聞ける音声+本日の配信情報を確認
>フォローすると詳しく見られます

![图片](https://user-images.githubusercontent.com/20549332/75094832-aa2bb500-55c9-11ea-918b-299a1e8ab93f.png)

![图片](https://user-images.githubusercontent.com/20549332/75094970-fcb9a100-55ca-11ea-9938-155d97629e96.png)
