### ISSUE TITLE
请问是否有计划提供Safari浏览器支持的插件？

### ISSUE THREAD

**Issue by lizy0100** [crimx/ext-saladict#639]
## 设备信息
- 操作系统: [macOS Catalina 10.15] 
- 浏览器版本: [Safari] 
- 沙拉查词版本: [-] 

## 请描述目前使用沙拉查词遇到什么不便

请问是否有计划提供Safari浏览器支持的插件？

**Comment by crimx** [comment]
你好，目前无计划。
