### ISSUE TITLE
可以設置字典的地區和語言，或不影響網頁原來的設定

### ISSUE THREAD

**Issue by 2ndBillGates** [crimx/ext-saladict#640]
## 设备信息
- 操作系统: Window10
- 浏览器版本: Microsoft Edge Version 79.0.309.71 (Official build) (64-bit)
- 沙拉查词版本: v7.7.6

## 请描述目前使用沙拉查词遇到什么不便

為了享用更多的功能，我會把Bing的地區設置為UK/US。
但Saladict在使用如Bing字典時，會自動導向Bing(CN)，間接導致Bing預設地區為CN(簡體中文)。

## 理想情况下，沙拉查词应该怎么做

我希望作者能讓我們使用者設置字典的預設地區和語言[如繁體中文(澳門/香港/台灣)；英文(英國/美國)]
這樣，不但能解決地區錯誤問題，更能讓使用者選擇喜好的方言，例如英式英文和美式英文。

## 替代方案

如果上述的功能太麻煩的話，有沒有方法能解決Bing自動更改地區設置的問題?

## 额外信息

感謝你制作了如此好用的程式，在日常生活中真的幫助了我很多。
我祝福你們打Code時得心應手，新年快樂。

**Comment by crimx** [comment]
你好，感谢反馈。我不太清楚你说的问题，可以附上图片说明一下吗？

**Comment by 2ndBillGates** [comment]
> 你好，感谢反馈。~我不太清楚你说的问题，可以附上图片说明一下吗？~ 已成功复现这个问题。

我剛測試了一下，原來只是bing的問題，包括
1) 地區自動更改機制
2) Bing詞典

2) 是因為Bing詞典只有Bing CN版才會這樣
辛苦作者了

**Comment by crimx** [comment]
这是因为 bing 词典返回结果时覆盖了 bing 域名下的 cookies ，我试试不带 cookies 看能不能用 bing 词典。

**Comment by 2ndBillGates** [comment]
> 这是因为 bing 词典返回结果时覆盖了 bing 域名下的 cookies ，我试试不带 cookies 看能不能用 bing 词典。

麻煩你了

**Comment by crimx** [comment]
发现无法更换，但是你可以将 bing 的搜索链接换为 `https://www.bing.com/search?mkt=en-UK&setLang=en`

**Comment by vsnst** [comment]
> 发现无法更换，但是你可以将 bing 的搜索链接换为 `https://www.bing.com/search?mkt=en-UK&setLang=en`

感謝
