### ISSUE TITLE
我的沙拉查词出现的一些问题

### ISSUE THREAD

**Issue by hebuhrer** [crimx/ext-saladict#642]
![9B820C04BAD8091929A2DE58653AFABD](https://user-images.githubusercontent.com/60803353/74078197-32567a00-4a62-11ea-8b5d-db290d2c5769.jpg)

我随便打开一个网页不能翻译，换系统之前可以的，用的谷歌浏览器，不知道怎么设置
![sendpix1](https://user-images.githubusercontent.com/60803353/74078226-911bf380-4a62-11ea-95fe-4a4ba627a493.jpg)
每次开启谷歌浏览器都打开一个这样的空白网页

**Comment by crimx** [comment]
你好.

1. 这个提示已经说明了。沙拉查词重心不在网页翻译，所以有些网页可能不能支持。网页翻译推荐使用彩云小译或者谷歌翻译扩展。

2. 空白网页这个应该不是沙拉查词的问题。
