### ISSUE TITLE
Module not found: Error: Can't resolve './response' 

### ISSUE THREAD

**Issue by Mrshulan** [crimx/ext-saladict#644]
npm pdf后
npm run start

ERROR in ./test/specs/components/dictionaries/wikipedia/requests.mock.ts
Module not found: Error: Can't resolve './response' 

请问我是缺了什么步骤嘛

**Comment by crimx** [comment]
新版本换了处理方式，所以最后还需要 `yarn fixtures` ，一会在 README 补上。另外请用 yarn 避免包不匹配。

**Comment by crimx** [comment]
发现之前已经补上了，见 `CONTRIBUTING.md`。

**Comment by Mrshulan** [comment]
感谢~ yarn start之后成功运行 
但是在我点击saladbowl之后 想 显示翻译结果 报错误
Unmatch url: https://cn.bing.com/dict/clientsearch?mkt=zh-CN&setLang=zh&form=BDVEHC&ClientVer=BDDTV3.5.1.4320&q=ihil%20ipsum%20itaque%20pr Object

bing Error: NETWORK_ERROR

是我获取数据姿势错误吗？ 我在.env只配置了百度

**Comment by crimx** [comment]
start 环境中是没有 stub xhr request 的，如果想调整翻译结果样式请用 `yarn storybook`。

**Comment by Mrshulan** [comment]
也就是说storybook的样式调正可以直接联动 start环境下的结果?
另外想额外的问一下 在插件的background这一层是没有 跨域的限制，所以在build之后是可以成功获取到数据，你看我这样理解是正确的吗

**Comment by crimx** [comment]
> 也就是说storybook的样式调正可以直接联动 start环境下的结果?

start 环境主要用于调试其它页面，查词面板作为植入页面的复杂组件且涉及跨域请求所以主要在 storybook 中开发。

> 另外想额外的问一下 在插件的background这一层是没有 跨域的限制，所以在build之后是可以成功获取到数据，你看我这样理解是正确的吗

是的。

**Comment by crimx** [comment]
嗨，谢谢你的赞赏！有更多相关问题欢迎在这里继续讨论。点击我的头像也可以看到我的邮件地址。
