### ISSUE TITLE
机器翻译的“词典设置”中能否可增加一个选项可以设置是否展开原文

### ISSUE THREAD

**Issue by moxuanyuan** [crimx/ext-saladict#645]
如果原文过长，沙拉默认是会折叠原文的。这样不方便对照参考。如果可以在“词典设置”中增加一个选项可以设置是否展开原文就更好了

**Comment by Beating-flies** [comment]
我赞同他的建议。使用谷歌翻译的语音功能时，为了多听原文，我需要先展开才能点击发声按钮。我希望直接点到原文的发声按钮。

**Comment by crimx** [comment]
7.14.0 以添加多功能菜单以及提供三种设置原文显示方式。
