### ISSUE TITLE
独立窗口快捷查词全局快捷键有时不起作用

### ISSUE THREAD

**Issue by moxuanyuan** [crimx/ext-saladict#646]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Chrome81] 
- 沙拉查词版本: [7.7.6] 

## 描述问题
已经在chrome中为“在独立窗口中搜索剪贴板内容”设置了全局快捷键，但全局快捷键有时不起作用。
当不起作用时，在网页上操作一次划词查词后，全局快捷键就能起作用。

**Comment by crimx** [comment]
你好，首先谢谢反馈。

目前无法复现这个失效情况，如果可以提供更稳定的重现方法我可以试试。

可以更换快捷键排查一下有没有冲突。
