### ISSUE TITLE
想要柯林斯词典

### ISSUE THREAD

**Issue by Yeluoqianqiu** [crimx/ext-saladict#65]
- 类型：建议
- 期待：1.想要生词本同步，不然容易丢失啊
             2.可以添加柯林斯吗，感觉还是柯林斯比较好用？

**Comment by crimx** [comment]
1. 生词本不同步是因为 Chrome 同步数据容量有限制
2. 中文柯林斯可能有版权问题不好公开

**Comment by crimx** [comment]
另一方面看，这样也可以避免添加到生词本就“记住”的错觉哈哈，建议定制导出到背单词的应用中学起来。

**Comment by Yeluoqianqiu** [comment]
百度不是有柯林斯吗？直接调用百度翻译的柯林斯可以吗？

**Comment by crimx** [comment]
其实我已经实现了，用的是词霸的结果，作为彩蛋一直没有公开，下个大版本看看怎样。

**Comment by crimx** [comment]
[新版](https://github.com/crimx/ext-saladict/wiki/Saladict6)已添加，如有问题欢迎开新 issue 反馈。
