### ISSUE TITLE
查词时，词典中的 牛津高阶 词典无法打开

### ISSUE THREAD

**Issue by Frustrated9363** [crimx/ext-saladict#651]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: []

**Comment by NyaaGitty** [comment]
相同问题，悬浮窗中的牛津高阶没有显示翻译信息。
单击牛津高阶后跳转的页面可以正常显示单词。

**Comment by crimx** [comment]
牛津高阶网页完全更新了，考虑到学习型词典比较多，不再维护改为基于 Dictionary.com 和牛津的 Lexico 词典。
