### ISSUE TITLE
在某些页面弹出层进行查词时，无法对选中的查词内容进行编辑

### ISSUE THREAD

**Issue by liby** [crimx/ext-saladict#652]
## 设备信息
- 操作系统: [MacOS 10.15.2] 
- 浏览器版本: [Chrome Version 80.0.3987.106 (Official Build) (64-bit)] 
- 沙拉查词版本: [v7.8.0] 

## 描述问题

某些网页有一些会弹出一些 Modal，在这些弹出层中选中单词/句子进行查词时，在沙拉查词窗口 -> 编辑框 -> 无法进行编辑

## 复现步骤

1. 打开 [BootStrap](https://getbootstrap.com/docs/4.0/components/modal/#live-demo)
2. 点击 Launch demo modal
3. 在打开的弹窗中，选中任意单词/句子进行查词
4. 尝试在沙拉查词窗口进行编辑，问题出现

## 期待的正常行为

- 在选中单词/句子查词后，在沙拉查词窗口可以正常编辑
- 比如在 [Ant Design](https://ant.design/components/modal/) 中的弹出层就可以正常查词并编辑，不知道它与 BootStrap 的弹出层实现区别在哪，导致了沙拉查词在查词后无法进行编辑

## 截图

![截图](https://user-images.githubusercontent.com/38807139/74701519-f1205000-5241-11ea-81c4-2e95074d354d.jpg)

## 额外信息

暂无

**Comment by crimx** [comment]
这似乎是因为焦点被强行取消了。既然网页强行取消焦点，那么不抢占是正确的行为。如果非要在这样的 modal 上查词可以使用独立窗口。

**Comment by crimx** [comment]
见这里 

https://github.com/twbs/bootstrap/blob/557e9cfb3cb82ce59cc09fe8bfc6ad463d51f91f/js/src/modal.js#L297

如果要拦截 document 事件可能会导致其它 bug。

**Comment by liby** [comment]
@crimx 谢谢你，我看了一下确实是这样，既然如此那我就先关闭了
