### ISSUE TITLE
百度翻译无法翻译句子

### ISSUE THREAD

**Issue by Ulysses233** [crimx/ext-saladict#653]
## 设备信息
- 操作系统: [Windows10] 
- 浏览器版本: [Edge80.0.361.54] 
- 沙拉查词版本: [v7.8.0] 

## 描述问题

英译中，翻译模式下，百度翻译不显示句子的翻译内容(俩个词及以上)，部分单词也无法显示翻译内容。

## 复现步骤

划一句任意英文，开启划词翻译的情况下，其他源显示正常而百度翻译无内容。在扩展悬浮框中输入的是句子百度一样不能翻译(俩个词及以上)。

## 期待的正常行为

正常出现翻译内容。

**Comment by crimx** [comment]
我测试是没有问题的（Chrome 上）。你可以点击百度翻译的标题打开网页看看有没有结果。

![image](https://user-images.githubusercontent.com/6882794/74727005-69efce00-527b-11ea-9302-e5dbbfc80924.png)

**Comment by Ulysses233** [comment]
刚试了下, 的确句子翻译显示正常了, 可能是我这的网络问题?
但有一个特例: The agent also perceives a reward signal from the environment, a number that tells it how good or bad the current world state is. The goal of the agent is to maximize its cumulative reward, called return.
这个句子无法显示翻译内容, 丢进去百度翻译的网址上有一定几率没有翻译结果, 可能是百度翻译的bug?
