### ISSUE TITLE
新版EDGE浏览器无法使用 浏览器外召唤沙拉查词

### ISSUE THREAD

**Issue by SKEETCHAN** [crimx/ext-saladict#654]
## 设备信息
- 操作系统：Window10
- 浏览器版本：Microsoft Edge 80.0.361.56 (官方内部版本) (64 位)
- 沙拉查词版本：v7.8.0

## 描述问题

浏览器后台已开启，三下CTRL没有效果

## 截图
 [[如图已开启相关功能]](https://s2.ax1x.com/2020/02/20/3ZNAC6.png)

**Comment by crimx** [comment]
三按 ctrl 是浏览器内的功能，浏览器外请阅读[使用说明](https://saladict.crimx.com/native.html)。
