### ISSUE TITLE
导出的单词本中标点符号是中式的

### ISSUE THREAD

**Issue by playdougher** [crimx/ext-saladict#655]
## Device info
 - OS: Window10
 - Browser Version [Chrome]
 - Saladict Version [ v7.0.0]

## Describe the bug

导出的单词本中标点符号是中式的,导致在anki中查看会显得很宽

## To Reproduce

1. 进入沙拉单词本
2. 找一个例句带有`'`的句子,点击编辑
3. 会发现`'`是中式的

## Screenshots

![Snipaste_2020-02-20_13-22-03](https://user-images.githubusercontent.com/26463515/74903870-38931180-53e5-11ea-8cfe-9adf57245ce4.png)
![Snipaste_2020-02-20_13-34-02](https://user-images.githubusercontent.com/26463515/74904023-b22aff80-53e5-11ea-8e8a-f5c4c496d604.png)

**Comment by crimx** [comment]
你好，这应该是你划词的上下文是用这个符号，与导出无关。

**Comment by playdougher** [comment]
> 你好，这应该是你划词的上下文是用这个符号，与导出无关。

不是的，原文是英文的（Medium网站），例句变成中文符号了
![2](https://user-images.githubusercontent.com/26463515/74906523-3bddcb80-53ec-11ea-8e53-8e8b2d3e9da5.png)
![1](https://user-images.githubusercontent.com/26463515/74906525-3e402580-53ec-11ea-8990-fcef428834d8.png)

**Comment by crimx** [comment]
原文就是这个符号，不同字体以及样式而已。

**Comment by crimx** [comment]
你可以手动复制粘贴过来检查。

**Comment by playdougher** [comment]
还真是，全是英文的网站复制出来就变中文的了，难受。

**Comment by crimx** [comment]
原文 https://medium.com/@briaeliza/13-things-you-need-to-be-willing-to-lose-if-you-really-want-to-change-your-life-for-the-better-c2e0595bda84

- 符号  `’` 为 [Right Single Quotation Mark](https://www.codetable.net/decimal/8217)
- 英文 `'` 为 [Apostrophe](https://www.codetable.net/decimal/39)

你可以编辑 Anki CSS 样式更换字体。
