### ISSUE TITLE
悬浮窗不显示释义

### ISSUE THREAD

**Issue by EgbertLi** [crimx/ext-saladict#656]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Chrome79] 
- 沙拉查词版本: [7.6.2] 

## 描述问题

悬浮窗词典无法下拉展开，无法显示释义

## 复现步骤

1.打开一英文网站
2.选取任意一句
3.点击沙拉图标
4.悬浮窗内的所有词典都不会下拉展开，无法显示释义，但单击词典可以成功跳转网页
5.只有翻译模式下的彩云小译下拉展开，显示释义

## 期待的正常行为

悬浮窗内的词典自动下拉展开，显示释义

**Comment by crimx** [comment]
你好，这个复现步骤范围太广，无法准确复现你的问题。

鉴于沙拉查词的用户数量，如果大量用户出现这种情况必然会有大量反馈。所以先考虑是网络或配置问题。你可以

- 先打开 `chrome://extensions/` 点击上方的 `Update` 手动触发更新。
