### ISSUE TITLE
有道翻译一段话只翻译一小句

### ISSUE THREAD

**Issue by Kasonreal** [crimx/ext-saladict#660]
## Device info
 - OS: [Window10] 
 - Browser Version [Chrome 80.0.3987.116]  
 - Saladict Version [v7.8]  

## Describe the bug
有道翻译一段话只翻译一小句

## Screenshots

![image](https://user-images.githubusercontent.com/43562668/75086898-5c389200-5574-11ea-8ba7-a95362d980d9.png)

**Comment by crimx** [comment]
你好，需要更多信息

1. 点击有道翻译的展开全文查看是否完整。
2. 点击有道翻译的标题在官网上翻译看是否完整。

**Comment by Kasonreal** [comment]
> 你好，需要更多信息
> 
> 1. 点击有道翻译的展开全文查看是否完整。
> 2. 点击有道翻译的标题在官网上翻译看是否完整。
> 3. 请把文本贴过来以供复现测试。

你好！
1.展开全文的英文是完整的，翻译的中文不全
2.这里点击官网点不开，其他的比如谷歌翻译、腾讯翻译都能点开官网
3.在这里任何大段落都翻译不全，下面给出贴图的文本
In recent years, deep neural networks have yielded immensesuccess on speech recognition, computer vision and naturallanguage processing. However, the exploration of deep neu-ral networks on recommender systems has received relativelyless scrutiny. In this work, we strive to develop techniquesbased on neural networks to tackle the key problem in rec-ommendation — collaborative filtering — on the basis ofimplicit feedback.

![image](https://user-images.githubusercontent.com/43562668/75088986-07564500-558f-11ea-9390-6039ab750e15.png)

**Comment by caofengl** [comment]
同样遇到此问题，有道翻译结果只有一句话。

**Comment by suoluomen233** [comment]
操作系统: [Window10]
浏览器版本: [chrome  75.0.3770.142]
沙拉查词版本: [7.8.0]
同样的问题 ，有道翻译在官网上翻译正常，但是沙拉就不行显示一小段，而且不准确

**Comment by crimx** [comment]
有道翻译由另一位朋友维护，本楼先锁了，请耐心等待。
