### ISSUE TITLE
新版EDGE浏览器【沉浸式阅读器】模式下沙拉无法工作

### ISSUE THREAD

**Issue by kerryliu98** [crimx/ext-saladict#661]
## 设备信息
- 操作系统: Win 10 
- 浏览器版本: Microsoft Edge 
- 沙拉查词版本: [] 

## 请描述目前使用沙拉查词遇到什么不便

![image](https://user-images.githubusercontent.com/50589621/75087910-10401a00-5581-11ea-9c23-e6e8d20061d7.png)

**Comment by crimx** [comment]
请使用[浏览器外划词](https://saladict.crimx.com/native.html)。
