### ISSUE TITLE
插件右键中的谷歌网页翻译质量与原生的或者google翻译插件的翻译质量不一样，质量差很多。

### ISSUE THREAD

**Issue by aviton** [crimx/ext-saladict#662]
## 设备信息
- 操作系统: [windows10] 
- 浏览器版本: [edge80] 
- 沙拉查词版本: [7.8.0] 

## 请描述目前使用沙拉查词遇到什么不便

非常好用的插件，感谢开发者。不过有个小问题，就是需要整个网页翻译（因为使用edge，所以无法使用chrome自带的网页翻译功能，但是edge的网页翻译功能没有chrome自带的好），所以我在右键中添加了谷歌网页翻译，但是发现与我安装google翻译官方插件（或者使用chrome自带翻译功能）里面的翻译此页面的翻译质量完全不一样，差太多了，不知道是不是这里右键添加的谷歌网页翻译地址有问题？

## 理想情况下，沙拉查词应该怎么做

希望插件里面的谷歌网页翻译与google翻译或chrome中的翻译质量一样。

## 额外信息

翻译同一网页https://www.bbc.com/news/world-asia-51596665的结果对比：
沙拉查词插件的谷歌网页翻译结果截图：
![image](https://user-images.githubusercontent.com/61352203/75093243-f6232d80-55ba-11ea-8f84-a8dc0466a302.png)
使用google官方翻译插件进行网页翻译结果截图：
![image](https://user-images.githubusercontent.com/61352203/75093262-118e3880-55bb-11ea-8d0b-d77ba69d6072.png)

**Comment by crimx** [comment]
你好，目前网页翻译处于维护状态，没有计划更新功能，请用其它官方扩展如彩云小译和谷歌翻译。
