### ISSUE TITLE
单词管理是否可以增加默默单词的同步功能呢？

### ISSUE THREAD

**Issue by Jethrozxy** [crimx/ext-saladict#663]
单词管理是否可以增加默默单词的同步功能呢？谢谢作者

**Comment by crimx** [comment]
默默背单词貌似没有提供这样的接口？

**Comment by vsnst** [comment]
如果生字本可以加入識辨詞性 Verb noun adj. 就非常捧了

**Comment by crimx** [comment]
@vsnst 这需要通过自然语言处理（NLP）引擎分析上下文，目前还不能在扩展中实现。另外与主题无关的讨论请另开 issue 不要搭楼反馈。
