### ISSUE TITLE
由大编辑框获取焦点改为搜索框获取焦点

### ISSUE THREAD

**Issue by zhangnan15** [crimx/ext-saladict#664]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Chrome78] 
- 沙拉查词版本: [v7.6.2] 

## 请描述目前使用沙拉查词遇到什么不便

唤出查词面板后，输入单词/句子后按回车无法直接进行搜索（只会回车到下一行），不够便捷。

## 理想情况下，沙拉查词应该怎么做

可否将原本“大编辑框获取焦点”改为“搜索框获取焦点”，这样就可以按回车进行搜索了。然后保留大编辑框以及它的同步显示功能，如果用户有需要的话（编辑修改长句子的需要），自会去用鼠标把焦点移向大编辑框。
我觉得日常使用中，需要用到大编辑框来修改长句子的概率应该相对小一点。可否直接把获取焦点改至搜索框呢？或者在Saladict 设置中的“查词面板”选项卡里添加一个“按回车搜素”的选项？然后我们可以自由选择进入查词页面时——①焦点在搜索框，单词/短句子可以直接回车进行搜索；②焦点在大编辑框，可以直接修改长句子

**Comment by crimx** [comment]
1. 多行编辑框可以在设置中调整。
2. 多行编辑框 ctrl+enter 搜索。
