### ISSUE TITLE
日语划词翻译，除了谷歌翻译为【日→中 】之外，其他翻译均为【中→英】

### ISSUE THREAD

**Issue by ShadowLyin** [crimx/ext-saladict#665]
## 设备信息
- 操作系统: [Windows 10 1909] 
- 浏览器版本: [firefox 73.0.1] 
- 沙拉查词版本: [7.8.0] 

## 描述问题

日语划词翻译，除了谷歌翻译为【日→中 】之外，其他翻译均为【中→英】，已尝试设定彩云小译与腾讯翻译君的词典设置内的目标语言为中文，但是翻译时仍然显示英文，每次翻译必须手动在划词翻译界面手动更改来源语言和目标语言才行。有在 https://github.com/crimx/ext-saladict/issues/638 中反映了这个问题，但是您没有回复所就新开了个 issue。

## 复现步骤

翻译 https://ci-en.dlsite.com/creator/391/article/210640 中的

> ASMR音源配布+無料で聞ける音声+本日の配信情報を確認
> フォローすると詳しく見られます

截图如下

另外又尝试了翻译 Twitter 中的日语，如 https://twitter.com/Bell_Nekonogi/status/1233793166953705472 ，发现其可以正常的日翻中。
## 截图

![图片](https://user-images.githubusercontent.com/20549332/75611747-3739b580-5b58-11ea-8c07-1b7532216660.png)
![图片](https://user-images.githubusercontent.com/20549332/75611754-40c31d80-5b58-11ea-98cb-19ba8c7de431.png)

**Comment by crimx** [comment]
语言判断的逻辑有些 bug ，需要些时间理清一下
