### ISSUE TITLE
快捷查词可自定义快捷键

### ISSUE THREAD

**Issue by JRolly** [crimx/ext-saladict#667]
## 设备信息
- 操作系统: [Windows10] 
- 浏览器版本: [Microsoft Edge 81.0.416.20 ] 
- 沙拉查词版本: [7.8.0] 

## 请描述目前使用沙拉查词遇到什么不便

快捷查词快捷键默认只能使用连按三次Ctrl键， 此默认设置与其他软件（Listry默认连按两次弹出）的默认快捷键有冲突， 已然习惯了这个默认快捷键来使用其他软件了。

## 理想情况下，沙拉查词应该怎么做

希望可以增加自定义快捷键的功能。

**Comment by crimx** [comment]
请阅读[使用说明](https://saladict.crimx.com/manual.html)。
