### ISSUE TITLE
腾讯文档无法使用划词翻译功能

### ISSUE THREAD

**Issue by onoha** [crimx/ext-saladict#668]
在腾讯文档中无法使用划词翻译功能，面板没有弹出。其他网站正常

**Comment by crimx** [comment]
文档类应用为了实现多人编辑一般会自定义实现划词机制，故无法通过浏览器接口获得选词。目前没有计划特意兼容腾讯文档。可以配置浏览器外划词 https://saladict.crimx.com/native.html
