### ISSUE TITLE
【建议】希望可以提供更多快速切换查询模式的方法

### ISSUE THREAD

**Issue by lxchx** [crimx/ext-saladict#669]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Chrome74] 
- 沙拉查词版本: [v7.7.6] 

## 请描述目前使用沙拉查词遇到什么不便

在查词/句时不能很快地切换查询模式

## 理想情况下，沙拉查词应该怎么做

可以提供更多切换模式的方法

## 替代方案

1. 加入左右/上下切换模式的按键，会比汉堡键更顺手
2. 鼠标悬停在汉堡键时滚动滚轮可以快速切换模式

**Comment by crimx** [comment]
情景模式的交互是接下来优化的一个点，你的建议很不错，谢谢。

**Comment by catterdx** [comment]
@crimx 这个汉堡键不太好用，切换模式功能和设置功能在一起的，经常不小心点击了右键，弹出了设置页面！
顺便还有个问题，关于不同模式智能判断，比如根据划词数量的多少来判断决定模式的选择
再有就是不同模式里内置的词典或接口排列顺序可以自定义

**Comment by crimx** [comment]
> 切换模式功能和设置功能在一起的

确实如此。目前还没有想到更好的方式。

> 顺便还有个问题，关于不同模式智能判断，比如根据划词数量的多少来判断决定模式的选择

词典可以根据划词数来显示，没必要再情景模式上再实现一遍。

> 再有就是不同模式里内置的词典或接口排列顺序可以自定义

本来就是如此。不同模式下词典的配置都是独立的。如不知道如何进入设置请阅读[使用说明](https://saladict.crimx.com/manual.html#qrcode)。

**Comment by catterdx** [comment]
@crimx 关于不同模式的独立配置我之前**没有搞清楚原理**，重新看了说明，**解决了**。
关于划词数量的问题，我再**补充**一下，
我指的是在查询单词是默认模式的单词查询样式是我想要的，
但是选择多词的时，样式只能是有道词典和谷歌翻译，不能自定义，
所以翻译模式里的多词翻译是我想要的，
**或者说的得简单些，我想要默认模式的单词查询，和翻译模式的句子段落查询为一个新的模式**
当然，**快速切换**也可以**部分**的解决这个问题。

**Comment by crimx** [comment]
你新建一个模式不能解决么

**Comment by catterdx** [comment]
解决了，在默认模式设好了，没有新增模式，我把想要作为主要翻译器的词典单词语数量设为最低6，并向上移动顺序，就可以通过判断划词数实现单词和语句的智能样式了！
