### ISSUE TITLE
希望可以添加一个功能，在每次打开新网页的时候自动弹出一个单词，这样可以更加高效背单词

### ISSUE THREAD

**Issue by 1572365765** [crimx/ext-saladict#670]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: []

**Comment by crimx** [comment]
你好，谢谢你的建议。沙拉查词主要针对「查词」设计，目前没有计划研究与实现背单词方面的功能。请导出到相关应用中记忆。
