### ISSUE TITLE
选中文本后，从右键菜单中启动词典面板

### ISSUE THREAD

**Issue by zhangyucha0** [crimx/ext-saladict#671]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Chrome77] 
- 沙拉查词版本: [v7.8.0] 

## 请描述目前使用沙拉查词遇到什么不便

隔壁“划词翻译”的选中文本后从右键启动的方式，个人认为非常简洁好用。
跪求作者能考虑把这个小功能加上。

## 理想情况下，沙拉查词应该怎么做

希望增加一种新的划词方式：
改动：右键菜单中，新增 `翻译“xxx”` 选项（因为选项前缀有saladict的图标，可以判断是使用saladict翻译，极简至上！）
流程：选中文本 -> 右键点击该选项 -> 弹出显示词典面板

**Comment by crimx** [comment]
沙拉查词支持的，查看设置。

**Comment by zhangyucha0** [comment]
> 沙拉查词支持的，查看设置。

我眼瞎了，谢谢！
