### ISSUE TITLE
沙拉查词+popclip无法实现浏览器外划词翻译

### ISSUE THREAD

**Issue by nikolajohn** [crimx/ext-saladict#672]
## Device info
 - OS: MacOS 10.14.6
 - Browser Version : 80.0.3987.132（正式版本）
 - Saladict Version : 7.8.0

## Describe the bug
我按照如下链接进行操作，但是不起作用：
https://github.com/crimx/ext-saladict/issues/463

## To Reproduce
1.我购买了popclip，并且下载了根据如下链接下载了popclip的插件并解压后双击进行安装
https://github.com/crimx/ext-saladict/files/3915430/Saladict.popclipext.zip
2.对于沙拉，我进一步地设置，设置步骤见screenshot
3.最后，当我尝试用Mac自带的“预览”应用打开PDF后，并尝试用沙拉进行翻译时，我失败了，当我选中一段文字并点击popclip的黑色沙拉图标，我的电脑发出“嘟”的一声，然而沙拉并没有任何显示，效果见screenshot

## Expected behavior
我喜欢沙拉，并且花钱买了popclip，我希望能实现浏览器外使用沙拉

## Screenshots
![image](https://user-images.githubusercontent.com/19464494/76145687-c69a1800-60c6-11ea-97be-81dc57ae0e5f.png)
![image](https://user-images.githubusercontent.com/19464494/76145700-d0238000-60c6-11ea-8390-33714cd4e667.png)
![image](https://user-images.githubusercontent.com/19464494/76145724-0a8d1d00-60c7-11ea-9394-9be93ad70146.png)
![image](https://user-images.githubusercontent.com/19464494/76145723-ff39f180-60c6-11ea-965f-1edec4be287b.png)
![image](https://user-images.githubusercontent.com/19464494/76145769-b3d41300-60c7-11ea-84e5-b586fd7e2db9.png)

**Comment by crimx** [comment]
你好，你有尝试重启试试吗。

排查过程：

- 如果你复制一段文字再按下设置的快捷键（`^P`）没有反应那么可能是浏览器的全局快捷键没有生效。如果重启后依然没有生效那么有可能是与其它快捷键冲突了，可以更换快捷键尝试。
- 如果按快捷键生效而 popclip 没有反应那么有可能是 popclip 配置的问题。可以到原 issue 请教一下原作者。

**Comment by nikolajohn** [comment]
> 你好，你有尝试重启试试吗。
> 
> 排查过程：
> 
> * 如果你复制一段文字再按下设置的快捷键（`^P`）没有反应那么可能是浏览器的全局快捷键没有生效。如果重启后依然没有生效那么有可能是与其它快捷键冲突了，可以更换快捷键尝试。
> * 如果按快捷键生效而 popclip 没有反应那么有可能是 popclip 配置的问题。可以到原 issue 请教一下原作者。

感谢您的回复，我试了一下，按下control + P好像也没有用，或许是浏览器的全局快捷键没有生效，我尝试重启并切换打其他快捷键，然而依然无法生效...

**Comment by crimx** [comment]
如果是这样那么就比较玄学了。因为每个人的系统环境复杂我也不太清楚哪里配置导致了 chrome 快捷键设置失效。

- 你可以尝试更换「全局」为 chrome 内，然后复制一段文字，在 chrome 中按下快捷键看有无反应。如果有那么很有可能是全局快捷键冲突了。也可能是系统的其它配置导致 chrome 全局快捷键失效。
- 也可以尝试对其它命令设置全局快捷键，如「激活该扩展程序」，如果按下快捷键后会出现一个弹框，那么有可能是沙拉查词本身的问题；如果没有那么基本可以确定是 chrome 的全局快捷键问题。

**Comment by nikolajohn** [comment]
I am impressed by your logical rigour. Thank you for your reply.

**Comment by nikolajohn** [comment]
> 如果是这样那么就比较玄学了。因为每个人的系统环境复杂我也不太清楚哪里配置导致了 chrome 快捷键设置失效。
> 
> * 你可以尝试更换「全局」为 chrome 内，然后复制一段文字，在 chrome 中按下快捷键看有无反应。如果有那么很有可能是全局快捷键冲突了。也可能是系统的其它配置导致 chrome 全局快捷键失效。
> * 也可以尝试对其它命令设置全局快捷键，如「激活该扩展程序」，如果按下快捷键后会出现一个弹框，那么有可能是沙拉查词本身的问题；如果没有那么基本可以确定是 chrome 的全局快捷键问题。

I am impressed by your logical rigour. Thank you for your reply.

**Comment by AntoineGao** [comment]
请问楼主解决这个问题了吗，我也遇到了同样的问题，看pdf时点一下沙拉查词按钮只发出嘟一声没有任何反应

**Comment by mrmissed** [comment]
我也遇到了和楼主一样的问题。浏览器外选中文字之后点击popclip里的沙拉查词按钮只会发出嘟的一声；直接按在独立窗口搜索剪贴板内容的快捷键，独立窗口有响应，但查询的并不是我所选择的文字内容。但是如果选择文字之后，先点选popclip里面的“拷贝”，再按独立窗口快捷键，就可以正确查询了。不知道是什么原因，虽然这样可以查询，但还是有点麻烦，希望作者大大来解答一下。另外浏览器外的独立页面不能像浏览器内一样固定在页面最上方，有点麻烦，不知道作者大大可否改进一下。辛苦～

**Comment by ab00b** [comment]
> 请问楼主解决这个问题了吗，我也遇到了同样的问题，看pdf时点一下沙拉查词按钮只发出嘟一声没有任何反应



> 我也遇到了和楼主一样的问题。浏览器外选中文字之后点击popclip里的沙拉查词按钮只会发出嘟的一声；直接按在独立窗口搜索剪贴板内容的快捷键，独立窗口有响应，但查询的并不是我所选择的文字内容。但是如果选择文字之后，先点选popclip里面的“拷贝”，再按独立窗口快捷键，就可以正确查询了。不知道是什么原因，虽然这样可以查询，但还是有点麻烦，希望作者大大来解答一下。另外浏览器外的独立页面不能像浏览器内一样固定在页面最上方，有点麻烦，不知道作者大大可否改进一下。辛苦～

我查看了原作者的popclip扩展解包（右键-查看包内容即可看到），里面的popclip扩展配置如下
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Actions</key>
	<array>
		<dict>
			<key>AppleScript File</key>
			<string>saladict.applescript</string>
			<key>Before</key>
			<string>copy</string>
			<key>Image File</key>
			<string>saladict.png</string>
			<key>Long Running</key>
			<false/>
			<key>Requirements</key>
			<array>
				<string>copy</string>
			</array>
			<key>Title</key>
			<string>Search In Saladict</string>
		</dict>
	</array>
	<key>Extension Description</key>
	<string>Look up the selected text in Saladict, an add-on for Firefox and Chrome.</string>
	<key>Extension Identifier</key>
	<string>com.myownextension.saladict</string>
	<key>Extension Name</key>
	<string>Saladict</string>

</dict>
</plist>

```

大概能看出popclip必须已经添加了"copy"功能，扩展会先调用这个功能复制选中的单词，然后运行apple script脚本为
（为了避免快捷键冲突我这里已经把快捷键改成了command+contol+，）
```
tell application "System Events"
	key code 43 using {command down, control down}
end tell
```
即单纯的按下设置好的沙拉查词快捷键

我这边一切正常，希望你们可以检查一下自己的设置

**Comment by lingyuecui** [comment]
我遇到跟楼主一样的问题，请问解决了吗？我的popclip已经开启了拷贝功能但还是不能用呀...

**Comment by BingYu-track** [comment]
没用呀，还是用不了

**Comment by BingYu-track** [comment]
![image](https://user-images.githubusercontent.com/33021175/127775521-75063cb9-ba4e-4730-b9e5-470a89c79094.png)
我找到了第4步的界面了！

**Comment by BingYu-track** [comment]
这个设置好就OK了，亲测没问题！

**Comment by xiaolaoc** [comment]
问下如果在chrome中把"在独立窗口中搜索剪切板内容"的快捷键(默认control-p)修改成其他的，popclip的插件如何同步修改快捷键从而生效呢？

**Comment by Apache-US** [comment]
> Events

你好大佬,能请教一下帮个忙吗? 我想要改成左边的 shift+command+c , 对应的key code 是什么?

感谢!

**Comment by ab00b** [comment]
在Google搜索“apple script key code”就有一张表，修改脚本后打包并且重命名后缀就能安装了
2022年12月28日 +0800 PM2:16 apachecn ***@***.***>，写道：
