### ISSUE TITLE
百度翻译，谷歌翻译，有道翻译选中中文无法翻译成英文

### ISSUE THREAD

**Issue by hqyyqh** [crimx/ext-saladict#674]
## 设备信息
- 操作系统: win10 1909
- 浏览器版本: Chrome80
- 沙拉查词版本: v7.9.0

## 描述问题

目前发现**百度翻译、谷歌翻译、有道翻译**，选中中文翻译结果仍为中文
![Snipaste_2020-03-09_23-59-37_compress](https://user-images.githubusercontent.com/38676455/76233001-78ba1700-6262-11ea-898e-c6d8a1d9e75e.jpg)

**Comment by crimx** [comment]
这里的问题是如果检测源语言与目标语言相同要不要修改目标语言。最后还是选择尊重目标语言设置比较不容易起冲突，这也是各个机器翻译的逻辑。

在词典设置中调整常用目标语言，在词典结果中临时改变目标语言。

如果有更好的判断逻辑欢迎分享。

**Comment by crimx** [comment]
添加了「第二目标语言」来解决这个问题。
