### ISSUE TITLE
建议增加双击弹窗隐藏翻译的功能

### ISSUE THREAD

**Issue by nb5p** [crimx/ext-saladict#675]
请描述目前使用沙拉查词遇到什么不便

平时双击单词一般是想使用词典去查询单词，而非翻译这个单词。

## 理想情况下，沙拉查词应该怎么做

增加一个开关，开启后
双击单词只显示配置的词典的查询结果，不获取翻译

**Comment by crimx** [comment]
这其实是要实现不同划词模式触发不同情景模式，这个实现难度比较大，而且会让配置变得更加繁杂。

其实你可以将翻译的最小字数设为 2 或以上，双击查词时就不会出现。

**Comment by nb5p** [comment]
抱歉，我没找到这个选项。能提示下，在哪个页面吗，谢谢

**Comment by crimx** [comment]
在各个的词典设置中。请阅读[使用说明](https://saladict.crimx.com/manual.html)。

**Comment by nb5p** [comment]
谢谢
