### ISSUE TITLE
建议：加入生词本后单词高亮的功能

### ISSUE THREAD

**Issue by mxyq** [crimx/ext-saladict#676]
## 设备信息
- 操作系统: Windows 10
- 浏览器版本: Chrome 80
- 沙拉查词版本: 7.9.1

## 请描述目前使用沙拉查词遇到什么不便？
建议在沙拉查词里面加入类似于单词发现者那种查词高亮的功能：在某一个文章或页面中将此词高亮，在另外一个页面中也会默认高亮。我感觉这样可以对经常遇到的单词加深印象。

## 理想情况下，沙拉查词应该怎么做
您可以在后台设置加入：加入生词本后是否高亮选项，用户查询后，加入生词本就会高亮。

## 替代方案
无

## 额外信息
无

**Comment by crimx** [comment]
你好，沙拉查词目前还是专注于查词体验，学习单词相关的特性优先级较低。你可以尝试结合其它扩展如单词发现者使用，如果这些应用支持导入或同步的话。

**Comment by mxyq** [comment]
目前就只有单词发现者有类似的功能，但是在我的chrome单词发现者插件不能正常使用：加入生词本，刷新页面后不会高亮。
另外在使用高亮的时候，并不会仅仅使用单词高亮，也可以进行语法，短语，例句等高亮。

**Comment by crimx** [comment]
沙拉查词还积压着不少功能
