### ISSUE TITLE
Saladict 设置云同步功能

### ISSUE THREAD

**Issue by mrdulin** [crimx/ext-saladict#680]
## 设备信息
- 操作系统: [macOS] 
- 浏览器版本: [Chromium 版本 81.0.4009.0（开发者内部版本） （64 位）] 
- 沙拉查词版本: [7.9.1] 

## 请描述目前使用沙拉查词遇到什么不便

Saladict 设置支持云同步，本地导入导出，对于多个平台，多个浏览器，略不方便

## 理想情况下，沙拉查词应该怎么做

考虑使用Github Gist或者Repo作为Saladict 配置存储，只需要设置一次access token,授予相应的权限即可。

## 替代方案

目前流程是：配置手动导出，上传坚果云，在其他地点的其他机器上，下载配置，手动导入

**Comment by crimx** [comment]
沙拉查词的设置选择浏览器内置同步的原因：

1. 开箱即用，是使用门槛最低的使用方式，只要是同个帐号跨平台也可以同步。
2. 一般来说设置不会频繁改变，导入导出到另外浏览器也是可以接受的，不同浏览器间需要频繁同步的用户数量我预计不会很多。
3. 沙拉查词许多用户是技术小白，使用 Github 服务同步的方法不太合适。
4. 沙拉查词的设置目前是深度基于浏览器存储 API 实现的，引入第三方库或自行实现同步我估计会比较麻烦，且自己没有这个需求，所以搁置了，但欢迎提交 PR。

**Comment by hcycc** [comment]
我看了生词本仅仅支持本地导出，还是希望可以有一个  “通道”  来同步生词本  对于学习英语的来说吧。

**Comment by Echodawn** [comment]
非常希望能支持同步到欧路词典 谢谢!

**Comment by crimx** [comment]
@hcycc 生词本[支持 WebDAV 和扇贝同步](https://saladict.crimx.com/manual.html#search-history)。
