### ISSUE TITLE
作者你好，沙拉查词在UC浏览器上没法安装。希望作者可以让这个插件兼容UC。

### ISSUE THREAD

**Issue by Time-A-1** [crimx/ext-saladict#681]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: []

**Comment by crimx** [comment]
UC 官网已找不到 PC 浏览器，很可能已经被淘汰了。沙拉查词是在 Chrome 商店编译签名的，内核滞后的浏览器不再兼容。
