### ISSUE TITLE
滑词时取一个句子，句子包含换行，导致翻译变成对几个单词的翻译。建议对词语进行预处理，去除换行符

### ISSUE THREAD

**Issue by miderxi** [crimx/ext-saladict#682]
## 设备信息
- 操作系统: [] deepin
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 请描述目前使用沙拉查词遇到什么不便

查询一句英语时，英语包含换行，导致变成对部分单词的翻译，

## 理想情况下，沙拉查词应该怎么做

建议增加对取词预处理，去除换行符

**Comment by crimx** [comment]
你好，换行是特意保留下来的。毕竟不按规则开发的网站还是少数，故不会去除掉以保留完整语义。

**Comment by miderxi** [comment]
> 你好，换行是特意保留下来的。毕竟不按规则开发的网站还是少数，故不会去除掉以保留完整语义。

能不能增加一个选项让我们调控，因为如果是取一个句子，特别是文库或网页使用时，会非常方便，有道翻译翻译句子时，他就会去掉换行符号

**Comment by crimx** [comment]
因为目前设置已经开始变得复杂了，沙拉查词对加入新选项会比较克制。

一个句子中单词出现换行很可能是网页使用了块元素来包裹高亮词（你没有提供网页我只能大致猜测），这种情况反语义的情况应该是极少的（一般是反过来滥用）。

**Comment by miderxi** [comment]
我使用的是百度文库，百度文库有些文档会有这种问题，有些文档不会。而百度文库有pdf，doc等多种格式文档

**Comment by crimx** [comment]
嗯，这个问题一般出现在解析 PDF 上。没想到沙拉查词也能支持百度文库。

机器翻译目前有选项支持在内置 PDF 阅读器中过滤换行，我可以把这个选项改为通用，这样也能兼容其它在线 PDF 阅读器。

**Comment by miderxi** [comment]
嗯嗯，我也觉得这样很合理

**Comment by crimx** [comment]
已发布
