### ISSUE TITLE
提示设置更新失败

### ISSUE THREAD

**Issue by StulenX** [crimx/ext-saladict#683]
## 设备信息
- 操作系统: [MacOS Catalina 10.15.3] 
- 浏览器版本: [v.80.0.3987.132] 
- 沙拉查词版本: [7.9.1] 

## 描述问题

任何一个设置（如开启划词）在更改之后均无法保存，上方弹窗推送“红色叉+设置更新失败”

## 复现步骤

设置——基本选项——启用查词翻译（开/官）
出现弹窗：设置更新失败

## 期待的正常行为

应该显示更新成功.....

**Comment by crimx** [comment]
在此之前有改变什么设置么？

先导出设置备份一下，然后重置试试。

**Comment by StulenX** [comment]
导入设定也是失败的///

**Comment by crimx** [comment]
那可能是浏览器存储出了问题。是不是刚升级浏览器？可尝试重启。

**Comment by StulenX** [comment]
重启和重进均无法解决问题

**Comment by crimx** [comment]
那不清楚了，我无法重现这个问题。

**Comment by crimx** [comment]
那不清楚了，我无法重现这个问题。
