### ISSUE TITLE
腾讯翻译君，点击小喇叭，没有发出单词语音

### ISSUE THREAD

**Issue by yancheng199287** [crimx/ext-saladict#685]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 期待的正常行为

期待可以正常发音

**Comment by crimx** [comment]
很遗憾这个目前无解。腾讯限制了请求来源，有一定几率中招，沙拉查词的发音系统不能兼容。
