### ISSUE TITLE
查词结果希望加入一键复制功能

### ISSUE THREAD

**Issue by yancheng199287** [crimx/ext-saladict#686]
查询得出的结果，希望在后面加入按钮，一键复制。

现在每次手动去选中，又会去查询，而且复制很不方便。

因为查词，是需要得到结果的，粘贴到其他地方。

谢谢！！

**Comment by crimx** [comment]
你好，如果是复制选中内容，沙拉查词的查词面板不会抢占焦点，划词后直接复制没有问题；如果是复制查词结果，可以考虑安装其它一键复制类扩展，沙拉查词目前没有计划提供类似功能。
