### ISSUE TITLE
取消翻译时，会出现快速跳转到页面顶部再返回，及有概率白屏

### ISSUE THREAD

**Issue by BlackHole1** [crimx/ext-saladict#688]
## 设备信息
- 操作系统: [macOS Catalina 10.15.3] 
- 浏览器版本: [Firefox Developer Edition 75.0b3] 
- 沙拉查词版本: [v7.9.2] 

## 描述问题

当划词翻译后，点击页面，将会关闭翻译的窗口。
但是关闭翻译窗口时，页面将会快速跳转到页面顶部，然后在回到原始位置

并且快速点击页面中的任意一处时，将会有概率白屏。

## 复现步骤

复现视频: https://i.imgur.com/9bD0diF.mp4

## 期待的正常行为

不应该白屏及跳转到顶部在返回

## 截图

https://i.imgur.com/9bD0diF.mp4

## 额外信息

已经禁用了其他插件，避免其他插件脚本的影响

**Comment by crimx** [comment]
你好，这看起来更像是火狐开发者版的问题，可能是硬件加速的问题。可以换稳定版试试。

**Comment by BlackHole1** [comment]
好的，我这里测试下其他版本

**Comment by BlackHole1** [comment]
经过测试发现Firefox独有的问题
1. 关闭硬件加速，问题依旧
2. 使用 Chrome 正常
3. 使用稳定版 Firefox 问题依旧

**Comment by crimx** [comment]
有没有可能是同步了什么配置导致问题？使用稳定版时有没有登录了 Firefox 帐号？如果登录了可以清理掉退出，不登录安装沙拉查词试试。

**Comment by BlackHole1** [comment]
为了确保测试的正确性，我是重新下载国际版的firefox稳定版本，并且没有在稳定版本中登录 firefox账号。
我的测试流程是：
1. 从 https://www.mozilla.org/zh-CN/firefox/new/ 下载最新版本的firefox 稳定版本
2. 安装后，直接在插件商店安装 沙拉翻译
3. 打开 https://github.com/llitfkitfk/go-best-practice 进行测试

**Comment by BlackHole1** [comment]
我这边先 clone 下项目，根据 tag 切换下版本，看下是哪个版本引起的问题。我记得之前是没有这个问题的

**Comment by BlackHole1** [comment]
7.8.0是没有问题的，此问题从v7.9.0开始出现

**Comment by crimx** [comment]
v7.9.0 只是词典的修改，没有改变面板的代码。从视频看，图标本身的隐藏也会造成错乱。但是图标相关的代码已经很长时间没有动过。

目前能想到的两种可能，一是火狐渲染问题，白屏现象在以前也在 macOS 上出现过，已被火狐团队确认是硬件加速 bug；二是 v7.9.0 给依赖做过升级，有可能是某个依赖导致这个问题。

我现在还不能在那个页面复现这个问题，给排查增加了难度。

**Comment by BlackHole1** [comment]
我这里通过git bisect已经找到问题代码了，问题commit: https://github.com/crimx/ext-saladict/commit/10cea8146dad74a18b53c981b01ca71ff8034854

至于为什么这段代码会导致这种问题，我先吃个午饭，再去排查下。

**Comment by BlackHole1** [comment]
没有排查出来，初步猜测是css相关问题导致的，根据 `all: 'initial'` 去排查，没有在网上找到相关的bug。css这种不正交性实在是太难debug了。

目前估计是和 `react-transition-group` 库有关，不清楚 `Shadow DOM` + `all: 'initial'` + 'CSSTransition' 到底会触发什么样的化学反应。我的css能力太差，目前只能到这一步。

目前我的临时解决方案，下载此插件，并手动注释源码中的 `$root.style.setProperty('all', 'initial')` 来解决

**Comment by crimx** [comment]
感谢！都忘了这个 commit 。我晚上弄个兼容的试一下。

这应该是火狐的 bug，我再弄个最小复现给火狐反馈一下。

**Comment by BlackHole1** [comment]
好的，如果可以的话，麻烦后面反馈给火狐时，贴下火狐相关讨论的链接，我对这个也比较感兴趣，想看下火狐那边将会怎么去讨论及修复
