### ISSUE TITLE
请问我自己怎么加一个词典呢？

### ISSUE THREAD

**Issue by cctvbnm1111** [crimx/ext-saladict#689]
我想弄个波斯文字典，本地，自己用，请问如何做呀，实现网页上划词翻译，就
很简单，就一个key 对应一个中文解释就行了，请告知下，谢谢啦

**Comment by crimx** [comment]
你好，目前不支持本地词典。如何添加词典见[CONTRIBUTING.md](https://github.com/crimx/ext-saladict/blob/dev/CONTRIBUTING.md)。

**Comment by cctvbnm1111** [comment]
你好，那我自己架设一个服务端可以么，我不太会这个词典开发，就是觉得这个不错，想加一个自己定义的

**Comment by crimx** [comment]
理论上可以的，你的服务器开放么？

**Comment by cctvbnm1111** [comment]
可以啊，肯定嘛！！

**Comment by cctvbnm1111** [comment]
> 理论上可以的，你的服务器开放么？

你好，我怎么做呢，是不是不需要改啥，就弄个服务端词典就可以了呢，非常感谢呀

**Comment by crimx** [comment]
服务器返回 json 前端组装就行。可以结合 [CONTRIBUTING.md](https://github.com/crimx/ext-saladict/blob/dev/CONTRIBUTING.md) 参考 [国语词典](https://github.com/crimx/ext-saladict/tree/dev/src/components/dictionaries/guoyu)。

**Comment by cctvbnm1111** [comment]
请问，如何增加一个语言弹出识别框呢， 中文、法文、德文能弹出，但是我这个是གློ་ཚད་ནད་ཡམས་དང་འབྲེ，语言：Bo，字体是Microsoft Himalaya，需要加个这种识别，谢谢啦  @crimx

**Comment by crimx** [comment]
这是个问题了。这个功能在设计的时候没有考虑到其它更多的语言。你先本地修改 `src/_helpers/lang-check.ts` 的 `checkSupportedLangs` 强制返回 `true` 作测试（注意不要 commit 这个修改）。这个词典 merge 之后我再补上波斯语识别。

**Comment by cctvbnm1111** [comment]
嗯嗯，可以的，感谢
