### ISSUE TITLE
生词本导入扇贝失败

### ISSUE THREAD

**Issue by Gunhoho1** [crimx/ext-saladict#692]
您好
感谢能开发出如此优秀的插件
我的问题是，生词导入扇贝后，提示同步失败。
我的扇贝账号处于成功登陆状态。
我使用的浏览器是：chrome 80.0.3987.132
系统是：macOS 10.14.6
看日志，好像大家都成功解决了类似问题，希望能看到后帮我解惑，谢谢！

**Comment by crimx** [comment]
> 我的问题是，生词导入扇贝后，提示同步失败。  

同步失败的准确信息是什么呢？如无法复制你可以截取图片。

**Comment by Gunhoho1** [comment]
我又仔细看了一下
原来是我自己对扇贝的ui不熟悉导致没找到生词本，现在已经没有也对，非常感谢您。




| |
Gun
美术指导
|
|
蓝色光标数字营销机构
邮箱：18500428264@163.com
|

签名由 网易邮箱大师 定制

在2020年03月17日 22:17，CRIMX 写道：

我的问题是，生词导入扇贝后，提示同步失败。

同步失败的准确信息是什么呢？如无法复制你可以截取图片。

**Comment by Gunhoho1** [comment]
抱歉，之前的反馈问题我已经找到答案。
是我自己对扇贝的UI不熟悉，没有找到生词本位置。
很感谢你的回应，这里再次感谢制作如此优秀的工具帮助我们学习。
