### ISSUE TITLE
没有登录么

### ISSUE THREAD

**Issue by hcycc** [crimx/ext-saladict#693]

**Comment by hcycc** [comment]
我看里面有个添加单词的选项，不过没有登录，不就不能记录我们添加的单词历史了么，如果我们需要整理历史的单词，我们是不是就需要一个账户来同步记录单词

**Comment by crimx** [comment]
你好，没看明白你的描述。

沙拉查词不需要登录来记录单词历史记录，所有记录均保存在本地。

同步单词目前支持同步到扇贝以及 webdav 同步。

请阅读[使用说明](https://saladict.crimx.com/manual.html)。
