### ISSUE TITLE
添加生词时点击【选择翻译结果】无反应

### ISSUE THREAD

**Issue by SKEETCHAN** [crimx/ext-saladict#694]
## 设备信息
- 操作系统: Windows 10
- 浏览器版本: Microsoft Edge 80.0.361.66 (官方内部版本) (64 位)
- 沙拉查词版本: 7.9.2

## 描述问题
添加生词时点击【选择翻译结果】无反应，但是进入单独进入生词本界面点击【编辑】时就会弹出各翻译翻译结果。

## 截图
[截图](https://s1.ax1x.com/2020/03/18/80AWIH.png)

**Comment by crimx** [comment]
Bug: 独立窗口下无法打开【选择翻译结果】
