### ISSUE TITLE
希望支持使用DeepL翻译页面的功能

### ISSUE THREAD

**Issue by luojunyuan** [crimx/ext-saladict#696]
## 请描述目前使用沙拉查词遇到什么不便

[DeepL](https://www.deepl.com/translator) 是一款基于ai 神经网络翻译的产品。很希望能在saladict这样一款优秀的翻译软件上使用到它，来替代chrome或edge的自带网页翻译功能

## Example
![image](https://user-images.githubusercontent.com/28323948/77219495-5cc34900-6b71-11ea-9b13-0b4a3ac8b31d.png)

**Comment by crimx** [comment]
你好，沙拉查词重心将放在查词体验，无计划进一步支持网页翻译，见[注意事项](https://saladict.crimx.com/notice.html#%E9%A2%84%E8%AE%BE)。

**Comment by luojunyuan** [comment]
好的
