### ISSUE TITLE
能否集成类似 单词发现者 这类功能

### ISSUE THREAD

**Issue by xinshangshangxin** [crimx/ext-saladict#697]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 请描述目前使用沙拉查词遇到什么不便

给网页默认标注某些单词, 比如 [Words Discoverer](https://chrome.google.com/webstore/detail/words-discoverer-expand-y/noncaeikjgpbdeoocblijjgegnobogib) ([github 地址](https://github.com/mechatroner/aided_reading))
作用: 假设设置了 认识常用10% 的单词,超过这类的单词会标注显示, 并且通过查词显示含义

## 理想情况下，沙拉查词应该怎么做

集成 或者 是否有接口提供集成

## 替代方案

目前手动在沙拉中查询

**Comment by crimx** [comment]
> 并且通过查词显示含义

请展开一下这个会是什么样的效果。

沙拉查词配合 Words Discoverer 使用不能满足么？

**Comment by xinshangshangxin** [comment]
![image](https://user-images.githubusercontent.com/8779091/77252834-7cea2980-6c91-11ea-8dbb-f3dc528f4da3.png)

默认鼠标悬浮支持 下拉框显示
显示配置:
![image](https://user-images.githubusercontent.com/8779091/77252855-a440f680-6c91-11ea-8f05-e6bbe14f2738.png)

是否支持类似 查询条件, 以及加入 saladict 的生词本配置?

**Comment by crimx** [comment]
沙拉查词支持悬浮查词，词典顺序组合也可以灵活调整。

Words Discoverer 如它的名字，初衷是帮助用户发现单词。但人与人差异实在太大，其目前的实现是通过百分比笼统地高亮，不太符合沙拉查词“准确”的宗旨。如果只对生词本单词高亮，那么用户已经了解过这个单词，用处不大。

这个功能值得实现的前提是能结合机器学习通过用户查词历史或其它资料推测出可能的生词，否则沙拉查词会尽可能避免修改用户的网页，这里面坑太多。
