### ISSUE TITLE
要翻译的原文丢失了后半段

### ISSUE THREAD

**Issue by molkes** [crimx/ext-saladict#699]
## 设备信息

- 操作系统: [Window7]
- 浏览器版本:  [Cent Browser 4.1.7.182 (Chromium 78.0.3904.108)]
- 沙拉查词版本: [v7.9.3]

## 描述问题

右键菜单的谷歌翻译，跳转后原文丢失了后半段。

## 复现步骤

1. 打开[Comparing Streaming/Instant record vs Conventional Video Recording Methods - Nimbus Note](https://nimbusweb.me/s/share/3267935/99q972riouoi0b4fs19s)。
1. 选中文字“Comparing Streaming/Instant record vs Conventional Video Recording Methods”，选择右键菜单的【沙拉查词】-【谷歌翻译】。
1. 自动跳转到谷歌翻译后，原文变成了“Comparing Streaming”，少了后半段。

## 期待的正常行为

要翻译的原文不变。

**Comment by crimx** [comment]
这是因为 `/` 没有转义导致，感谢反馈。
