### ISSUE TITLE
Linux X11多屏下 快速查词 弹出位置不正确

### ISSUE THREAD

**Issue by kevinhwang91** [crimx/ext-saladict#701]
## 设备信息沙拉
- 操作系统: [ArchLinux Gnome X11] 
- 浏览器版本: [Chromium Version 80.0.3987.149 (Official Build) Arch Linux (64-bit)] 
- 沙拉查词版本: [7.9.3] 

## 描述问题

单屏是没问题的，多屏触发快速查词的时候位置不正确。以下是我屏幕的Layout：
![image](https://user-images.githubusercontent.com/17562139/77324375-99e63180-6d51-11ea-8457-8aff37c749e6.png)

## 复现步骤

1. 设置快速查词弹出位置：右上
2. 三击ctrl
3. 在显示器2上中部弹出窗口如下图：
![image](https://user-images.githubusercontent.com/17562139/77324689-18db6a00-6d52-11ea-8d8d-4087269db465.png)

## 期待的正常行为

窗口在右上角弹出

**Comment by crimx** [comment]
在显示器 2 中打开浏览器 console 看看 `window.screen` 返回什么值？

**Comment by kevinhwang91** [comment]
window.screen
Screen {availWidth: 1920, availHeight: 1080, width: 1920, height: 1080, colorDepth: 24, …}availWidth: 1920availHeight: 1080width: 1920height: 1080colorDepth: 24pixelDepth: 24availLeft: 1080availTop: 269orientation: ScreenOrientationangle: 0type: "landscape-primary"onchange: null__proto__: ScreenOrientation__proto__: ScreenavailWidth: (...)availHeight: (...)width: (...)height: (...)colorDepth: (...)pixelDepth: (...)availLeft: (...)availTop: (...)orientation: (...)constructor: ƒ Screen()Symbol(Symbol.toStringTag): "Screen"get availWidth: ƒ availWidth()get availHeight: ƒ availHeight()get width: ƒ width()get height: ƒ height()get colorDepth: ƒ colorDepth()get pixelDepth: ƒ pixelDepth()get availLeft: ƒ availLeft()get availTop: ƒ availTop()get orientation: ƒ orientation()__proto__: Object



我的分辨率是4k，切换了1080p相对位置还是同样的问题。

**Comment by kevinhwang91** [comment]
![image](https://user-images.githubusercontent.com/17562139/77327272-f6e3e680-6d55-11ea-9d9e-947c864f3c89.png)

**Comment by crimx** [comment]
已经定位到问题，感谢反馈

**Comment by crimx** [comment]
你可以试试效果如何。解压 [chrome.zip](https://github.com/crimx/ext-saladict/files/4370304/chrome.zip) ，在扩展管理中心关掉沙拉查词，开启开发者模式加载。

**Comment by kevinhwang91** [comment]
酷！我这边没问题了，你合并代码就可以关闭这个issue。
