### ISSUE TITLE
希望增加查词页面的打印或导出pdf功能

### ISSUE THREAD

**Issue by wudunxu** [crimx/ext-saladict#702]
希望增加查词页面的打印或导出pdf、html功能，方便英语学习存档。

**Comment by crimx** [comment]
在沙拉查词 6 的时候有保存查词结果为图片的功能，但更多是为了满足分享的需求，重写 7 时为了减少体积去掉了。

存档需求直接导出生词本即可。

**Comment by crimx** [comment]
在沙拉查词 6 的时候有保存查词结果为图片的功能，但更多是为了满足分享的需求，重写 7 时为了减少体积去掉了。

存档需求直接导出生词本即可。

**Comment by crimx** [comment]
在沙拉查词 6 的时候有保存查词结果为图片的功能，但更多是为了满足分享的需求，重写 7 时为了减少体积去掉了。

存档需求直接导出生词本即可。
