### ISSUE TITLE
扩展在body下生成的div节点样式可能会被干扰

### ISSUE THREAD

**Issue by guyigenius** [crimx/ext-saladict#703]
## 设备信息
- 操作系统: [macOS Catalina Version 10.15.3] 
- 浏览器版本: [Firefox Developer Edition 75.0b5 (64-bit)] 
- 沙拉查词版本: [7.9.3] 

## 描述问题

选中文字以后，扩展会在body下生成\<div id="saladict-saladbowl-root" class="saladict-div saladict-external"\>\</div\>节点，如果网站页面给body下的div设置了样式的话，扩展生成的div节点也会有一样的样式，可能会导致页面整体的布局和样式产生变化。
类似的，鼠标移动到沙拉查词的Icon上时由于生成了\<div id="saladict-saladbowl-root" class="saladict-div saladict-panel"\>\</div\>节点，因此也会出现同样的问题。

## 复现步骤

1. 打开<https://example.com/>；
2. 选中“Example Domain”，可以观察到页面多出了一个白底的方框；
3. 在选中状态下鼠标移动到沙拉查词的Icon上，可以观察到页面又多出了一个白底的方框。

## 期待的正常行为

即使网站页面给body下的div设置了样式，扩展在body下生成的div节点也不应该有样式，以确保页面整体的布局和样式不会产生变化。
建议扩展生成的节点都先添加{all: unset;}样式，然后再添加所需的样式。

## 截图

<img width="960" alt="image" src="https://user-images.githubusercontent.com/7352378/77423555-67e4d600-6e0a-11ea-94d0-6fad29c25ec0.png">

**Comment by crimx** [comment]
macOS 火狐上 all 属性会导致插入时白屏 #688 。

这个一般不影响使用。我再隐藏一下。
