### ISSUE TITLE
强烈建议添加pdf高亮显示功能，这样就更完美了！

### ISSUE THREAD

**Issue by ifreeman6** [crimx/ext-saladict#706]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 请描述目前使用沙拉查词遇到什么不便

       首先，必须强调的是沙拉单词是一款非常非常优秀的插件。但是，我在阅读英文pdf文献的时候，必须同时借助其他软件才能对pdf进行高亮显示，比如 weava插件，显得特别累赘，要是沙拉单词同时支持pdf高亮显示，我觉的这真的是一款极其完美的产品。非常感谢开发者们，希望可以考虑添加pdf高亮显示功能，拜托了。

**Comment by crimx** [comment]
请阅读[常见问题及答复](https://saladict.crimx.com/q&a.html#%E9%97%AE%EF%BC%9A%E5%8F%AF%E4%B8%8D%E5%8F%AF%E4%BB%A5%E5%A2%9E%E5%8A%A0-pdf-%E9%98%85%E8%AF%BB%E5%99%A8%E5%8A%9F%E8%83%BD%EF%BC%8C%E5%A6%82%E5%81%9A%E7%AC%94%E8%AE%B0%E3%80%81%E5%88%92%E7%BA%BF%E6%A0%87%E8%AE%B0%E3%80%81%E5%A4%9C%E9%97%B4%E6%A8%A1%E5%BC%8F%E7%AD%89%E3%80%82)。

**Comment by onepiecejx** [comment]
+1,强烈建议添加pdf高亮显示功能。
