### ISSUE TITLE
自定义查词面板独立窗口的弹窗位置

### ISSUE THREAD

**Issue by DerekTso** [crimx/ext-saladict#707]
### 使用中遇到的麻烦

如图，查词面板弹出来的位置在屏幕的正中央往上一点，刚好挡住了一块地方。
移动它的位置后，再次弹出来时，又恢复到默认的固定的位置。

![image](https://user-images.githubusercontent.com/10363328/77824209-f1164880-713b-11ea-8af7-cd8e5b79c6c7.png)

---

![image](https://user-images.githubusercontent.com/10363328/77824012-43566a00-713a-11ea-8c2f-b76bb25bbc23.png)

---

### 新功能建议

希望能够设置查词面板的弹窗位置，以便更好地更自由地使用它。
最好能够让它自动记录住上次移动过后的位置，下次弹窗时，刚好出现在预定的位置上。

**Comment by crimx** [comment]
你可以在设置中调整出现位置。

连续阅读文章的时候不必关掉查词窗口。

**Comment by DerekTso** [comment]
出现的位置只能调整左边/右边，如果显示器宽一点的话，阅读起来不太方便，每次都要扭一下脖子。

没有关掉查词窗口，只是它弹出来的位置在正中央，刚好是阅读的最佳位置，但是挡住了文字显示的位置。

其实，需求是自定义弹窗的位置，只需要稍微移动一下就好，下次弹窗的位置是上次移动后的位置。

// 另外，独立窗口好像不能钉住/总显示在最前。

**Comment by crimx** [comment]
> 没有关掉查词窗口，

我是指第一次出来之后拖到合适位置，不必关闭。连续查词查词面板不会移动位置。

> 其实，需求是自定义弹窗的位置，只需要稍微移动一下就好，下次弹窗的位置是上次移动后的位置

因为每次最佳位置都不一定在一个地方，所以实现这个功能性价比有限。改变一下使用方式即可。

> // 另外，独立窗口好像不能钉住/总显示在最前。

这个需要操作系统支持。如果操作系统不支持可以安装增强类插件。

**Comment by DerekTso** [comment]
嗯嗯，我理解错了。确实不会移动位置了。
谢谢~

**Comment by crimx** [comment]
你也可以安装一键排版类的窗口排版插件。这些插件一般支持更个性化的设置。

**Comment by meteorsh** [comment]
现在可以设置记住上次窗口位置和大小了
地址：chrome-extension://cdonnmffkdaoajfknoeeecmchibpmkmg/options.html?menuselected=QuickSearch

![image](https://user-images.githubusercontent.com/46078304/91936958-7d4c1d80-ed23-11ea-8666-37e87d9b405d.png)
