### ISSUE TITLE
nordic的网站页面Firefox插件不能翻译

### ISSUE THREAD

**Issue by zhuweihua163** [crimx/ext-saladict#708]
## 设备信息
- 操作系统: [win10 64bit] 
- 浏览器版本: [Firefox 75 64bit] 
- 沙拉查词版本: [7.9.3] 

## 描述问题

用firefox浏览器打开nordic的网站，查词插件不能正常工作。例如下面网址：
https://infocenter.nordicsemi.com/topic/com.nordic.infocenter.sdk5.v15.3.0/lib_background_dfu.html

## 复现步骤

没有特定操作步骤，打开网页就可以看到这个现象。

## 期待的正常行为

希望能够正常翻译。

**Comment by crimx** [comment]
图标不是变灰了么，说明不支持此类网页。

现在很少网页用这种过时技术，不会再做支持。你可以用[浏览器外划词](https://saladict.crimx.com/native.html)的方式。
