### ISSUE TITLE
在独立窗口中搜索剪贴板内容 全局快捷键失效

### ISSUE THREAD

**Issue by yxlong17** [crimx/ext-saladict#709]
设置了在独立窗口中搜索剪贴板内容的全局快捷键，但是依然无法打开独立窗口翻译赋值内容。
之后，测试用同样的快捷键设置了打开独立窗口，可以成功打开独立窗口，确认不是热键被占用。
希望可以早点解决，不然无法用quicker进行浏览器外划词翻译。

**Comment by crimx** [comment]
你好，无法重现你的问题。

上次更新也有一段时间了，目前还没有其他用户反馈这个问题，所以可能不是沙拉查词的问题。

你把反馈模板都删了，无法进一步分析。

**Comment by hqyyqh** [comment]
设置好快捷键后如果不能使用，可以**重启浏览器**，然后再试试看能不能调用。
发现不少需要重启浏览器快捷键才能生效的情况。
