### ISSUE TITLE
能否调整查词页面字体的大小 

### ISSUE THREAD

**Issue by hutuxiong** [crimx/ext-saladict#710]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 请描述目前使用沙拉查词遇到什么不便

查词的页面字体太小了且不能跟随网页大小调整，有点费眼睛

**Comment by crimx** [comment]
请阅读[使用说明](https://saladict.crimx.com/manual.html)。
