### ISSUE TITLE
macOS Firefox工具栏沙拉查词向下滚动查看翻译结果显示空白

### ISSUE THREAD

**Issue by guyigenius** [crimx/ext-saladict#712]
## 设备信息
- 操作系统: [macOS Catalina Version 10.15.4] 
- 浏览器版本: [Firefox Developer Edition 75.0b11 (64-bit)] 
- 沙拉查词版本: [7.9.3] 

## 描述问题

使用工具栏的沙拉查词输入待翻译文本按下查询按钮以后，可以正常显示结果，此时如果向下滚动查看更多词典的翻译结果，则每个词典的翻译结果均显示空白。

## 复现步骤

参考描述问题一节，可以直接复现。

## 期待的正常行为

向下滚动应该正确呈现更多词典的翻译结果，而不是空白。

## 截图

![Saladict Bug](https://user-images.githubusercontent.com/7352378/78038733-c75d5b80-739f-11ea-8fa8-b5f8a0a5d310.gif)

## 额外信息

经过初步的排查这个问题应该只有在macOS下的Firefox可以复现。考虑到之前macOS下的Firefox总是有各种奇怪的显示问题也不足为怪了。
完全新建的Profile，只安装了Saladict，避免了其他干扰因素。

**Comment by crimx** [comment]
Duplicate of #455

**Comment by guyigenius** [comment]
感谢，确实这个问题已经存在很久了，但是我之前翻了翻Issues并没有注意到有人已经提过了，通过标题判断是否重复太难了！
看了一下这个问题的优先级是P3，按照Firefox开发团队的尿性可能最近一年内都不会修复这个Bug，目前来看只能采用将Saladict右上弹框设置为打开快捷查词独立窗口这个曲线救国的方法了。

**Comment by crimx** [comment]
> 但是我之前翻了翻Issues并没有注意到有人已经提过了

没关系。

> 通过标题判断是否重复太难了！

你可以试试搜索框。

> 看了一下这个问题的优先级是P3，按照Firefox开发团队的尿性可能最近一年内都不会修复这个Bug，目前来看只能采用将Saladict右上弹框设置为打开快捷查词独立窗口这个曲线救国的方法了。

确实如此。上流问题沙拉查词也做不了什么，只能等待火狐更新，先关闭本 issue 。

**Comment by guyigenius** [comment]
最近我发现在Firefox Nightly 81.0a1 (2020-07-30) (64-bit)上这个问题已经修复了，但是我看了一下[Bug 1557342](https://bugzilla.mozilla.org/show_bug.cgi?id=1557342)并没有任何更新，Nightly的更新说明上似乎也没有关于这方面的内容。，同时在Firefox Developer Edition 80.0b1 (64-bit)上这个问题依然可以稳定复现。

**Comment by crimx** [comment]
可能是修复其它问题的时候同时也解决了这个问题吧。感谢更新情况。

**Comment by guyigenius** [comment]
@crimx 最近Firefox Developer Edition从[80.0b8](https://download-installer.cdn.mozilla.net/pub/devedition/releases/80.0b8/mac/en-US/Firefox%2080.0b8.dmg)升级到[81.0b1](https://download-installer.cdn.mozilla.net/pub/devedition/releases/81.0b1/mac/en-US/Firefox%2081.0b1.dmg)以后，这个问题就已经修复了！
虽然不知道具体是因为其他哪个问题的解决同时顺便解决了这个渲染白屏的问题，但是感觉可以更新一下[Bug 1557342](https://bugzilla.mozilla.org/show_bug.cgi?id=1557342)的状态？

**Comment by crimx** [comment]
能用就行，等稳定版出来再反馈吧。

**Comment by guyigenius** [comment]
@crimx 时隔四个月后的反馈：2020.12.15 Firefox Release正式版从[83.0](https://download-installer.cdn.mozilla.net/pub/firefox/releases/83.0/mac/en-US/Firefox%2083.0.dmg)升级到[84.0](https://download-installer.cdn.mozilla.net/pub/firefox/releases/84.0/mac/en-US/Firefox%2084.0.dmg)以后，这个问题终于修复了！也是莫名其妙Release正式版隔了这么久才同步修复了这个问题。
我觉得现在可以更新[Bug 1557342](https://bugzilla.mozilla.org/show_bug.cgi?id=1557342)的状态了？

**Comment by crimx** [comment]
喜大普奔😂
