### ISSUE TITLE
YouTube字幕取词

### ISSUE THREAD

**Issue by james-xiao** [crimx/ext-saladict#713]
## 设备信息
- 操作系统: []  win10
- 浏览器版本: [] Chrome 80.0.3987.149
- 沙拉查词版本: [] v7.9.3

## 请描述目前使用沙拉查词遇到什么不便

打开YouTube全屏时无法查取字幕上的单词

## 理想情况下，沙拉查词应该怎么做

可对全屏下youtube字幕直接取词

**Comment by crimx** [comment]
这个无法在网页中支持，可以使用[浏览器外划词](https://saladict.crimx.com/native.html)。

**Comment by james-xiao** [comment]
谢谢
