### ISSUE TITLE
希望增加一键复制翻译结果功能

### ISSUE THREAD

**Issue by BoltLi** [crimx/ext-saladict#715]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Chrome80] 
- 沙拉查词版本: [v7.9.3] 

## 请描述目前使用沙拉查词遇到什么不便

每次需要复制翻译结果都需要手动选中，较为繁琐

## 理想情况下，沙拉查词应该怎么做

希望在新版本中在每个翻译器的适当位置添加一键复制翻译结果的功能。

**Comment by crimx** [comment]
你好，请展开说明一下这个功能的作用。复制什么内容。为什么需要复制。

**Comment by BoltLi** [comment]
# 感谢回复！
![image](https://user-images.githubusercontent.com/42888380/78202861-fe2e9100-74c7-11ea-8b57-0f8278de79be.png)
# 功能及复制内容   
如上图，我使用它对句子进行了翻译，但是得到的结果需要手动选中才可以进行复制，而不是**直接一键复制**该翻译器的翻译结果，例如，在这个图片中，我可能会复制有道机器翻译的结果：
       这四个组件中的每一个都为一个对象添加了颜色。一个物体的最终颜色是所有成分的总和。在求和之后，如果任何红色、绿色或蓝色值高于1.0，则将其设置为1.0。
# 为什么需要复制
至于为什么需要复制，自然是需要翻译的结果，特别是对要翻译整理外语文献资料的时候。

**Comment by Jiyr0119** [comment]
哈哈哈 我也是想过来提这个issues的 
![image](https://user-images.githubusercontent.com/28727613/78741581-45b39200-798c-11ea-8db2-4b186bbe0564.png)
比如说这种地方可以加一键复制  也可以给作者加个打赏功能什么的，这样总比别人打开设置才能看到随机大赏更容易创收吧 哈哈哈

**Comment by crimx** [comment]
> 比如说这种地方可以加一键复制

这里的空间是计划进一步缩减的哈哈，我是打算把操作移到标题栏上。

> 也可以给作者加个打赏功能什么的，这样总比别人打开设置才能看到随机大赏更容易创收吧

以分散用户注意力的方式创收不太符合沙拉查词的初衷，但还是谢谢你的建议，我会保持开放的心态继续吸收更多灵感。

**Comment by Jiyr0119** [comment]
@crimx 感谢你的付出和开源，加油

**Comment by crimx** [comment]
已添加。
