### ISSUE TITLE
改进长篇段落翻译体验

### ISSUE THREAD

**Issue by orz12** [crimx/ext-saladict#716]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Chrome 83.0.4098.0] 
- 沙拉查词版本: [v7.9.3] 

## 请描述目前使用沙拉查词遇到什么不便

在pdf中选中整段（包含若干句话）后翻译：
1、由于数个引擎只支持单词或单句翻译（如有道），表现为翻译不全或没有返回结果，建议对这些条目进行隐藏（而非折叠成一行）。
2、在每一个正常的翻译结果后，都附带【▷原文】和【更改语言】两项，当需要对比多项翻译结果时，呈现出较多的冗余。建议将两者全部隐藏、迁移至引擎名称右侧（同一行）或统一至标题栏等处进行折叠展示，而非在每一个引擎后都进行展示，并独占一行。
3、内容较多时，界面无法方便地拖动调节大小，如果实现起来有困难，能否增加一个全屏显示或半屏显示（用于分为双栏的文献中）的快捷按钮？
4、内容较多时，翻译结果将被默认折叠一部分，能否增加一项设置，直接展示完整翻译结果？

**Comment by crimx** [comment]
你好，谢谢你的建议。

> 由于数个引擎只支持单词或单句翻译（如有道）

有道见 #660 。会在下个版本修复。

> 建议对这些条目进行隐藏（而非折叠成一行）。

在设置中可以对每个词典进行调整响应划词语言、长度。原本默认会进行相应的隐藏，但许多用户以为是 bug ，所以交给用户自行设置。不知道如何打开设置请阅读[使用说明](https://saladict.crimx.com/manual.html)。

> 在每一个正常的翻译结果后，都附带【▷原文】和【更改语言】两项，当需要对比多项翻译结果时，呈现出较多的冗余。建议将两者全部隐藏、迁移至引擎名称右侧（同一行）或统一至标题栏等处进行折叠展示，而非在每一个引擎后都进行展示，并独占一行。

标题栏选项还在 Todos 中，参考 [Project](https://github.com/crimx/ext-saladict/projects/3) 查看进度。

> 内容较多时，界面无法方便地拖动调节大小，如果实现起来有困难，能否增加一个全屏显示或半屏显示（用于分为双栏的文献中）的快捷按钮？

独立窗口查词面板正是为了解决这个问题。不知道如何打开请阅读[使用说明](https://saladict.crimx.com/manual.html)。

> 内容较多时，翻译结果将被默认折叠一部分，能否增加一项设置，直接展示完整翻译结果？

每个词典可设置默认高度，设为 `999999` 即可。不知道如何打开设置请阅读[使用说明](https://saladict.crimx.com/manual.html)。

**Comment by orz12** [comment]
非常感谢开发者的回复！

> 由于数个引擎只支持单词或单句翻译，表现为翻译不全或没有返回结果，建议对这些条目进行隐藏（而非折叠成一行）。

![image](https://user-images.githubusercontent.com/17450420/78328586-1ed31580-75b2-11ea-8134-21cf95eda002.png)

如图所示，扇贝词典没有查询结果，但仍然占用了一行，且该词典没有“失败时显示备选”设置项；而如果只是将划词长度最大值减至1，就会过滤掉许多能查到的短语。

> 原本默认会进行相应的隐藏，但许多用户以为是 bug ，所以交给用户自行设置。

如果您提到的“自行设置”是指“失败时显示备选”，在本机环境中，“麦克米伦”和“韦氏学习词典”在查询常规的单词时没有返回结果（点标题可正常访问网页且有结果，或许是页面改版），且关闭此项设置也不会隐藏；另外，如果查询词典中不存在的单词（如本例中的hrom），同样也不会隐藏（图中的必应词典也关闭了该项设置）；那么这个设置是如何生效的呢？
![image](https://user-images.githubusercontent.com/17450420/78327835-550f9580-75b0-11ea-97cb-0240199d456f.png)
Chrome 稳定版 80.0.3987.149 也可以复现此问题

> 在每一个正常的翻译结果后，都附带【▷原文】和【更改语言】两项

我目前采取的措施为 自定义CSS
`.MachineTrans-LangSwitchWrap {
 display: none;
}
details {
 display: none;
}`
该项可以解决此问题

> 独立窗口查词面板正是为了解决这个问题

这个确实是我的疏忽，不过也希望能在查询内容有多行的时候（或其他条件）于标题栏等处额外显示一个按钮，“将结果用独立窗口查词面板打开”，可引导用户使用此功能，真的非常棒。

> 每个词典可设置默认高度，设为 999999 即可。

该项测试良好，就是有点深而且需要单独设置。如果能在“查词面板”中仿照【自动展开多行搜索框】，在其后加入一项【自动展开所有词典的查询结果】（列入情景模式），或许能提升一定的易用性。

另外，我也将此扩展推荐给同学使用，用于阅读文献确实非常便捷。感谢开发者您的工作！

**Comment by crimx** [comment]
> 如图所示，扇贝词典没有查询结果，但仍然占用了一行，且该词典没有“失败时显示备选”设置项

抱歉我之前看错了。这个沙拉查词目前不支持。因为没有结果也有可能是网络问题，再点击展开可重复查询。一行占不了多少空间，为此增加一个选项没什么必要。

> 另外，我也将此扩展推荐给同学使用，用于阅读文献确实非常便捷。感谢开发者您的工作！

谢谢你的推荐。
