### ISSUE TITLE
扇贝同步一直提醒同步错误，太扰人了

### ISSUE THREAD

**Issue by debbbbie** [crimx/ext-saladict#717]
## 描述问题
扇贝同步一直提醒同步错误，太扰人了

## 复现步骤
1. 收藏一个扇贝没有的单词，比如 arity  debounce 等
2. 点扇贝同步

## 期待的正常行为
不能同步提示一次就行了，不应该一直提示！

## 截图
![image](https://user-images.githubusercontent.com/233115/78217472-c38c1f00-74ee-11ea-92c2-0b157a5d0881.png)

**Comment by crimx** [comment]
你是一直点击同步？开启了之后以后新增生词会自动同步，不用手动点击。

**Comment by debbbbie** [comment]
@crimx 他自己搁一段时间提醒一次。我在设置中心点同步也提示

![image](https://user-images.githubusercontent.com/233115/78223362-503bda80-74f9-11ea-93ab-303a2a0306d7.png)

**Comment by crimx** [comment]
> 他自己搁一段时间提醒一次。

无法复现这个情况。扇贝不会自动全量同步。

> 我在设置中心点同步也提示

第一次开启同步时点全部同步就行，以后不需要反复按。

**Comment by crimx** [comment]
另外你没有提供沙拉查词版本信息。最近版本的提醒中如果词库里没有的话不是这个提醒，这个提示是已经查到了单词 id 但无法添加到生词本。考虑是网络或者登录问题？因为扇贝接口是由 @lwdgit 实现的我也不太清楚。但扇贝不会自动全量同步这个是我实现的这个可以确定。

**Comment by debbbbie** [comment]
@crimx 尴尬不，还提示，我啥都没做。

版本的话应该是最新版，是7.9.3_0 （PS：查看版本也挺难的，设置界面上找不到，我从chrome extensions 文件夹找到的）



![image](https://user-images.githubusercontent.com/233115/78231268-1d97df00-7505-11ea-8ec7-d299631cda0c.png)

**Comment by crimx** [comment]
>  尴尬不

没什么好尴尬的，我又不欠谁什么。

> 还提示，我啥都没做。

我看提醒是每隔 30 分钟发一遍，你有没有同时开启了 WebDAV 同步并设置了 30 分钟间隔？

**Comment by debbbbie** [comment]
@crimx 有设置webdav同步，好诡异，看来webdav影响扇贝了？

![image](https://user-images.githubusercontent.com/233115/78239458-4bceec00-7510-11ea-9cf9-abb7e0f6d283.png)

**Comment by crimx** [comment]
应该是 WebDAV 服务器每次都返回了新的 etag 或者没有返回 304 导致生词本需要重新导入，从而触发了扇贝的添加。

**Comment by debbbbie** [comment]
👍

**Comment by crimx** [comment]
我测试了坚果云会正常返回 304 ，不知道是什么原因。不管怎样，在拦截生词写入数据库时判断了一下是否来自同步服务。应该不会再互相影响。
