### ISSUE TITLE
建议推出网页版比如H5或手机APP

### ISSUE THREAD

**Issue by memphis147** [crimx/ext-saladict#722]
## 设备信息
- 操作系统: [] Window10，iOS13.3
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 请描述目前使用沙拉查词遇到什么不便

希望手机上也能使用沙拉查词

## 理想情况下，沙拉查词应该怎么做

推出免费或收费APP

## 替代方案

手机移动网页版查词或WebAPP

**Comment by crimx** [comment]
请阅读[常见问题及答复](https://saladict.crimx.com/q&a.html)。
