### ISSUE TITLE
总是丢失面板焦点，独立窗口大小位置保存不住

### ISSUE THREAD

**Issue by fabaoin** [crimx/ext-saladict#723]
## 设备信息
- 操作系统: []  WIN7
- 浏览器版本: []   78
- 沙拉查词版本: []   找不到在哪看版本号

## 描述问题

1，总是丢失面板焦点，三点CTRL出来面板后，再搜索别的词，面板总是置于浏览器后方，需要每次再点击面板才行。但是在之前一直是默认聚焦面板焦点的。
2，独立窗口在屏幕右边，上下完全满屏，设置成小的窗口飘浮，下次打开还是通天能地满屏幕。

**Comment by fabaoin** [comment]
我试着把插件卸载，重装，装完好了2天，然后又出现这个问题。

**Comment by crimx** [comment]
> 三点CTRL出来面板后，再搜索别的词，面板总是置于浏览器后方，需要每次再点击面板才行

”搜索别的词“比较含糊。如果是点击了其它页面，面板自然会失去焦点。如果触发了查词，面板默认情况下会重新获得焦点。这个行为可以在面板上的按钮调整。

如果是开启了”查词时面板获取焦点“的情况下触发了查词而面板没有获得焦点，目前没有办法复现这样的行为。

> 独立窗口在屏幕右边，上下完全满屏，设置成小的窗口飘浮，下次打开还是通天能地满屏幕。

”上下满屏“还是”小的窗口“以设置页面设置的为准。查词面板不会记住上次关闭前的大小和位置，这个未来可能会加入设置。
