### ISSUE TITLE
SearchBox 里能换成支持自动换行的输入标签吗

### ISSUE THREAD

**Issue by flipp3d** [crimx/ext-saladict#724]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 请描述目前使用沙拉查词遇到什么不便

翻译长文本时，界面搜索框不美观

## 理想情况下，沙拉查词应该怎么做

当我输入长文本时，搜索框可以自动换行(textarea )，菜单栏可以自适应高度

**Comment by crimx** [comment]
有没有看到菜单栏下方有个长长的按键。可以在设置中调整多行编辑框的行为。你也可以切换到翻译模式会默认展开。

请阅读[使用说明](https://saladict.crimx.com/manual.html)。
