### ISSUE TITLE
音频播放按钮挪移

### ISSUE THREAD

**Issue by guleng** [crimx/ext-saladict#725]
![image](https://user-images.githubusercontent.com/40238640/79070367-f234a180-7d07-11ea-9298-42f81b72d511.png)

很希望能把播放音频的按钮挪动到前面，放在英音，美音后面就感觉很别扭，用起来不是很顺手
谢谢你们付出的一切。

**Comment by crimx** [comment]
你好，谢谢你的建议。你能提供一些例子说明有哪些词典是这么设置的吗？我相信放在后边更符合大部分人使用方式。

**Comment by guleng** [comment]
![image](https://user-images.githubusercontent.com/40238640/79070601-87846580-7d09-11ea-8eae-35d67788b3c0.png)

或者我们可以试一下带有星星的把这个放在英美音后，最后面展示，

**Comment by crimx** [comment]
沙拉查词支持自定义 CSS ，你可以尝试自行调整喜欢的显示方式。
