### ISSUE TITLE
取词功能  在隐私窗口里面 不能生效,已经开启了扩展  在无痕模式下启用

### ISSUE THREAD

**Issue by marcos-sun0218** [crimx/ext-saladict#727]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: []

**Comment by marcos-sun0218** [comment]
在无痕模式下启用

**Comment by marcos-sun0218** [comment]
准确来 说,是 百分浏览器的  小号标签页  不能用

**Comment by crimx** [comment]
> 准确来 说,是 百分浏览器的 小号标签页 不能用

请按模板提供完整复现方法。“百分浏览器”不在官方支持的浏览器中，如果只是该浏览器特有的问题因个人精力有限将不会得到修复。可以看看有没有其他开发者愿意维护。
