### ISSUE TITLE
面板和历史记录

### ISSUE THREAD

**Issue by binglvs** [crimx/ext-saladict#728]
（1）历史记录页面感觉还得改进，收藏单词时有点繁琐，历史查词节目感觉不舒服。
（2）独立面板有个固定功能就好了，让他一直显示在所有页面最上面，而不是分屏的感觉。
其他都很nice超级优秀。

**Comment by crimx** [comment]
你好，

> 历史记录页面感觉还得改进，收藏单词时有点繁琐，历史查词节目感觉不舒服。

请按模板反馈，展开说明一下你想要达到什么，以及这个“不舒服”的操作过程。

> 独立面板有个固定功能就好了

这个需要系统桌面管理器支持。如果不支持可考虑安装该桌面的增强类插件或更换桌面管理器。

> 其他都很nice超级优秀。

谢谢你的评价！
