### ISSUE TITLE
按鍵添加option

### ISSUE THREAD

**Issue by zzzgit** [crimx/ext-saladict#729]
## 设备信息
- 操作系统: [macOS] 
- 浏览器版本: [最新] 
- 沙拉查词版本: [最新] 

## 请描述目前使用沙拉查词遇到什么不便

<img width="323" alt="Screen Shot 2020-04-14 at 16 47 40" src="https://user-images.githubusercontent.com/1060733/79205360-668a5480-7e70-11ea-9891-c19ef2530d07.png">

此處只有Shift Ctrl Command三個按鍵，沒MacBook Pro中的Option。

## 理想情况下，沙拉查词应该怎么做
添加一個選項，MacBook中的option按鍵

**Comment by crimx** [comment]
你是指这个 Option（alt）？

![image](https://user-images.githubusercontent.com/6882794/79234238-918a9d80-7e9c-11ea-87ea-d93cddb85cc9.png)

**Comment by crimx** [comment]
想不起来为什么没有添加了……有空再看看吧

**Comment by zzzgit** [comment]
好的👌🏻

**Comment by tjx666** [comment]
实测 mac 上 option 按键无效

**Comment by tjx666** [comment]
@crimx
