### ISSUE TITLE
生词本翻页不是很方便

### ISSUE THREAD

**Issue by deaconcu** [crimx/ext-saladict#730]
## 设备信息
- 操作系统: [MacOS] 
- 浏览器版本: [最新] 
- 沙拉查词版本: [最新] 

## 请描述目前使用沙拉查词遇到什么不便

生词本翻页不是很方便，页码导航只在最下方，每次只能跳最多5页
如果一共有两百页，我想去100页，我需要每次下拉到最下方，点击后5页，然后再下拉到最下方，再点击后5页，重复这个操作20次，才能到100页，比较麻烦

## 理想情况下，沙拉查词应该怎么做

页面顶部放一个页码导航，并提供输入页码直接跳转

**Comment by crimx** [comment]
我会把每个页面的单词数提到 400，但注意生词本的设计是作为一个本地的中间工具，不是一个可靠的存储数据库，清理系统时是有可能被删掉的。100 页就得有 10000 个单词，请尽量导出到相应的软件中。

**Comment by deaconcu** [comment]
谢谢作者，提供了一个很棒的工具。

这个生词本有阅读时的上下文，也有一些自己记忆理解时写的注释。这些东西在回看的时候是很有用的，导入别的地方就会丢失，所以我最多也只会导出到文本，而不会去别的软件。

所以我觉得生词本是对一个有用户粘性的产品功能，值得更好的开发一下。

**Comment by crimx** [comment]
fair point
