### ISSUE TITLE
新一待AI翻译DeepL，听说碾压谷歌、百度、有道！

### ISSUE THREAD

**Issue by pealpool** [crimx/ext-saladict#731]
新一待AI翻译DeepL，听说碾压谷歌百度有道！

![image](https://user-images.githubusercontent.com/16716146/79288866-78183e80-7efa-11ea-9772-93ecd517af2f.png)

下面是介绍文章：
https://www.iplaysoft.com/deepl.html

**Comment by crimx** [comment]
Duplicate of #705
