### ISSUE TITLE
搜狗翻译经常失效

### ISSUE THREAD

**Issue by rxnwin** [crimx/ext-saladict#733]
貌似是调用网页版过多，网页版输入验证码后恢复。希望能调用搜狗输入法的翻译工具模块，不会出现验证码。默认位置："C:\Program Files (x86)\SogouInput\Components\SogouComMgr.exe" -openapp exinputBundle.translateCom

**Comment by sylzh** [comment]
在网页版输入验证码也只能使用一小会 马上又会崩溃 向搜狗客服反映客服建议我卸载插件【无语

**Comment by crimx** [comment]
你……去找搜狗客服了😂……小学生？

在最新版中你可以申请自己的搜狗帐号使用，打开扩展设置（不知道怎么打开见[这里](https://saladict.crimx.com/manual.html)），左边菜单找到「词典帐号」。

**Comment by xp12904** [comment]
<使用了自己申请的pid和key，搜狗翻译仍然是只是刚开始的少数几次能用，在网页版输入验证码后恢复，恢复后用几下又不行了>

**Comment by xp12904** [comment]
> 你……去找搜狗客服了😂……
> 
> 在最新版中你可以申请自己的搜狗帐号使用，打开扩展设置（不知道怎么打开见[这里](https://saladict.crimx.com/manual.html)），左边菜单找到「词典帐号」。

使用了自己申请的pid和key，搜狗翻译仍然是只是刚开始的少数几次能用，在网页版输入验证码后恢复，恢复后用几下又不行了

**Comment by crimx** [comment]
> 使用了自己申请的pid和key，搜狗翻译仍然是只是刚开始的少数几次能用，在网页版输入验证码后恢复，恢复后用几下又不行了

这可能得感谢楼上的朋友，只能建议你不用搜狗或者隔一段时间不用了。我也不清楚他们背后什么操作。
