### ISSUE TITLE
划段翻译有些小问题

### ISSUE THREAD

**Issue by qq627296160** [crimx/ext-saladict#734]
在邮箱中划整段翻译的过程中，如果一个句子没有在一行，划句翻译的过程会自动加一个回车，导致句子翻译的过程中不连续，出现很多难以理解的地方。
能否参考**天若幽心**在**quicker**中的**段落排版**应用，进行自己排版之后然后再进行翻译？
![image](https://user-images.githubusercontent.com/47805895/79445272-f960f580-800e-11ea-8e4c-dc46d307ae4e.png)

**Comment by crimx** [comment]
你可以在机器翻译的词典中分别设置是否保留换行。如果经常换着用可以新建一个模式，里面的机器翻译全部不保留换行。

**Comment by crimx** [comment]
如果不知道如何打开设置请参考[使用说明](https://saladict.crimx.com/manual.html)。

**Comment by qq627296160** [comment]
谢谢回复，问题已经解决，插件真的很强大，感谢作者的辛劳付出，已经再次打赏

**Comment by crimx** [comment]
谢谢支持！
