### ISSUE TITLE
增加一个类似彩云小译的双语对照网页翻译怎么样😂

### ISSUE THREAD

**Issue by danini1976** [crimx/ext-saladict#737]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Microsoft Edge 81] 
- 沙拉查词版本: [v7.9.3] 

## 请描述目前使用沙拉查词遇到什么不便

网页双语对照翻译，英文句子下面有对应的中文。
效果类似下图
![image](https://user-images.githubusercontent.com/41039420/79549819-0e4e8f00-80ca-11ea-8fe9-9c4991130457.png)
感觉可以只对网页正文进行翻译，不需要像他这个一样连菜单都翻译了。

**Comment by crimx** [comment]
请阅读[注意事项](https://saladict.crimx.com/notice.html)。

**Comment by danini1976** [comment]
好的，那那么请删除这个issue

**Comment by hxse** [comment]
> 请阅读[注意事项](https://saladict.crimx.com/notice.html)。

???啥意思
