### ISSUE TITLE
划词直接显示翻译的功能完善建议

### ISSUE THREAD

**Issue by kid-oh** [crimx/ext-saladict#738]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Chrome81] 
- 沙拉查词版本: [v7.9.3] 

## 请描述目前使用沙拉查词遇到什么不便

划词直接显示翻译的功能还不完善

## 理想情况下，沙拉查词应该怎么做

我希望可以增加一个指定域名开启直接划词翻译，不然的话不需要划词翻译的网站需要在拓展插件的一个个去手动关闭，效率很低

**Comment by crimx** [comment]
打开设置，看右边的目录。如不知道如何打开设置请阅读[使用说明](https://saladict.crimx.com/manual.html)。
