### ISSUE TITLE
https://www.english-corpora.org/coca/ 这个网站不能使用，可能扩展无权访问该界面

### ISSUE THREAD

**Issue by freemedom** [crimx/ext-saladict#740]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: []

**Comment by crimx** [comment]
这类文档使用了一种严重过时的技术 `<frameset>`，在现代网页中已不多见。因其技术限制，在页面内显示面板将非常麻烦，故不做支持。但可以启用独立窗口的沙拉查词面板。

**Comment by freemedom** [comment]
> 这类文档使用了一种严重过时的技术 `<frameset>`，在现代网页中已不多见。因其技术限制，在页面内显示面板将非常麻烦，故不做支持。但可以启用独立窗口的沙拉查词面板。

感谢解释
