### ISSUE TITLE
关于英文字体突然变化

### ISSUE THREAD

**Issue by PlutoFeng** [crimx/ext-saladict#741]
我想知道为什么英文字体忽然变了，看起来很不舒服，重设Chrome浏览器也没用，但是Firefox查词面板的字体正常

**Comment by crimx** [comment]
这你可问倒我了。沙拉查词没有字体变化的功能，猜测可能是做了什么其它的系统设置。

**Comment by crimx** [comment]
只有沙拉查词这样吗？你可以先导出沙拉查词的设置，然后重置设置排查一下。

**Comment by PlutoFeng** [comment]
设置我都是使用默认的。

**Comment by PlutoFeng** [comment]
我用了另一个chrome内核的浏览器试了一下, 也是这种情况, firefox就正常。打扰你了，字体变化其实影响不大，谢谢。
