### ISSUE TITLE
chrome无法更改为全局快捷键

### ISSUE THREAD

**Issue by ltjackll** [crimx/ext-saladict#743]
## 设备信息
- 操作系统: [win10] 
- 浏览器版本: [chrome78] 
- 沙拉查词版本: [v7.9.3] 

## 描述问题

具体时间我忘了,之前还用的好好的,今天想查一下单词发现无法呼出窗口了,然后发现chrome不允许更改了.我本来用的360浏览器的,一开始以为是360的骚操作,后来进chrome里面试了一下发现也这样了...

## 截图

[![JKN59A.png](https://s1.ax1x.com/2020/04/19/JKN59A.png)](https://imgchr.com/i/JKN59A)
无法更改为全局,下拉框是灰色的无法选择

**Comment by crimx** [comment]
这个应该不是扩展的问题。你可以自行排查一下

1. 只有这个不能选全局吗？如果其它选项可以考虑是快捷键冲突。
2. 老方法重启设备。

除此以外我也不清楚是什么问题了。你可以从最近的系统修改或者安装软件下手。

**Comment by ltjackll** [comment]
感谢回复,正常的排错手段都试过了,如果这个只是特例的话,看来就不是浏览器的问题了?但是我在另一台电脑上也出现了同样的问题,那台电脑平时不怎么参与工作的,现在尝试重装一下浏览器看行不行

**Comment by ltjackll** [comment]
在回复您之后我重装了一下浏览器(360极速),发现依然是无法选择全局,是不是chrome新版本对安全做了限制?

**Comment by crimx** [comment]
你好，

> 正常的排错手段都试过了

有需要的话可以说明一下你的排查过程，「正常」一词过于泛。

> 如果这个只是特例的话,看来就不是浏览器的问题了?

问题在浏览器的可能性不是很大。

> 但是我在另一台电脑上也出现了同样的问题

考虑是快捷键冲突。「 <kbd>Alt</kbd> + 数字」在 Chrome 中是用于切换网页标签的快捷键。

你需要排查三个问题

1. 为出现问题的命令重新设置**不同**的快捷键。
   如此可以排查是否由快捷键冲突引起的问题。
2. 为沙拉查词其它命令设置快捷键。
   如此可以排查是否只有该命令不能设置快捷键。
3. 为其它扩展的命令设置**不同**快捷键。
   如此可以排查是否浏览器无法设置快捷键。

考虑使用一组不容易出现问题的快捷键测试，如 <kbd>Alt</kbd> + <kbd>L</kbd> 或 <kbd>Alt</kbd> + <kbd>K</kbd>。

**Comment by GH01** [comment]
激活键（各扩展的首个按键）向来就是不能全局的吧。
激活扩展按钮 本就是浏览器内的事。

----------
倒是其他键，若已设为全局，改动时不注意姿势会出现问题：

先在命令A添加按键，并设为全局，
此时此键可用，
再到命令B，按下此键，
结果：
键是被夺了过来，但此键在本轮会话期间再不可用，除非重启浏览器。

正确姿势似乎是：
先在命令A关掉全局，然后再改。

你们用Chrome，试试是否如此？

这大概是Chrome自身的问题。

----------
P.S.
激活键 在Chrome自身好像也有问题：
假如某扩展自带默认激活键，
虽然貌似可以删除，但删除后，重新打开该设置你再看……

**Comment by crimx** [comment]
> 激活键（各扩展的首个按键）向来就是不能全局的吧。
> 激活扩展按钮 本就是浏览器内的事。

对的，你不说我都没注意到。这个快捷键是用来打开地址栏旁边的图标，不支持全局使用。
