### ISSUE TITLE
台异体字词典，古汉语学习利器，求大神添加。网址：https://dict.variants.moe.edu.tw/variants/rbt/home.do。

### ISSUE THREAD

**Issue by davider2016** [crimx/ext-saladict#744]

**Comment by davider2016** [comment]
汉典词量大，但古汉语解释不够精细。异体字词典可以弥补这方面的缺憾。

**Comment by crimx** [comment]
> 汉典词量大，但古汉语解释不够精细。异体字词典可以弥补这方面的缺憾。

你好，古汉语研究是相对冷门的领域，你贴出的链接中有九个查询入口。请点击一楼的编辑重新填写模板举例阐述这个词典的用法。
