### ISSUE TITLE
能否适配手机浏览器（yandex或kiwibrowser）的Chrome插件?

### ISSUE THREAD

**Issue by MrZLY** [crimx/ext-saladict#746]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 请描述目前使用沙拉查词遇到什么不便

使用kiwi或yandex等支持Chrome插件的手机浏览器不能划词或点击来翻译

## 理想情况下，沙拉查词应该怎么做

双击/点击/长按 单词就可以给出翻译（比如火狐的轻灵划译的策略）

## 替代方案

chromium内核手机浏览器没有替代方案。

（换火狐可能有轻灵划译的替代，但个人不打算再用火狐，查阅以前问题开放火狐插件安卓版似乎很麻烦，不知chromium内核的浏览器会不会简单一些）

**Comment by crimx** [comment]
设置开启触摸模式。
