### ISSUE TITLE
翻译界面拖动锁定

### ISSUE THREAD

**Issue by Lord-Fec** [crimx/ext-saladict#747]
在网页中取词翻译之后，若是拖动页面，则会产生鼠标箭头一直处于拖动的状态，无法释放。

**Comment by crimx** [comment]
> 若是拖动页面

什么是“拖动页面”？

请按模板填写，提供具体复现步骤。

**Comment by Lord-Fec** [comment]
![image](https://user-images.githubusercontent.com/47498451/79871804-83e29400-8417-11ea-888f-bc44dad7ca76.png)
这是出现bug的截图，我在各网站上都试了一下，发现只有在csdn的网页上出现了问题，复现步骤的话，就是打开任意一个csdn网站，如：https://blog.csdn.net/Jason160918/article/details/78295423，我是按住ctrl键然后取词翻译的，接着，我打算拖动翻译界面的位置，就是鼠标左键按住沙拉查词的界面，发现即使鼠标左键释放了，但是沙拉查词的小界面还是会跟着鼠标的移动而移动，如上面附图所示，此时鼠标是处于释放状态的。

**Comment by crimx** [comment]
这个可能是 CSDN 做了什么骚操作，我有空看一下。
