### ISSUE TITLE
彩云小译很多时候无法翻译

### ISSUE THREAD

**Issue by Chuxiuhonglx** [crimx/ext-saladict#748]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [81.0.4044.113（正式版本） （64 位）] 
- 沙拉查词版本: [v7.9.3] 

## 描述问题

2020.4.12下午用着用着彩云小译就翻译不出来了。重启了几次，有些时候可以，大多时候不行。对于一段话，一开始不行，于是先去翻译下其它东西，然后再来翻译同一段话，就可以翻译了。很奇怪。

## 复现步骤

1.使用全局快捷键翻译（在chrome里面试过也不行）word文档里有一段话，如“If the GMD regime had been a fully developed modern state, it might have been able to withstand this loss of legitimacy. But as it were, the regime attempted to lay claim to the prerequisites of a modern state without having developed the ideological or administrative framework for giving in return even the most essential services that modern elites need. It should not be surprising, then, that even among its former supporters the GMD state at the end of its existence came to be viewed as a brigand, next to which virtually any alternative focus of power would be preferable. What the GMD attempted to do—facing the worst possible circumstances—was to extend the role of the state. The attempts were met by common resistance, both in the cities and in the countryside. ”彩云小译不动。
2，随便去翻译一个东西 如“countries”（不管翻译成功与否），再翻译这句话，彩云小译就可以翻译了。

## 期待的正常行为

正常情况彩云小译可以直接翻译。

**Comment by crimx** [comment]
也许是敏感词汇过多……抽风了。下个版本沙拉查词支持用户使用自行申请的 key，可能稳定些。

**Comment by Chuxiuhonglx** [comment]
谢谢
