### ISSUE TITLE
有道网页翻译总是“没有难词”，只能全文翻译

### ISSUE THREAD

**Issue by myfjdthink** [crimx/ext-saladict#749]
## 设备信息
- 操作系统: [macOS 10.14.5 ] 
- 浏览器版本: [Chrome 80.0.3987.163（正式版本） （64 位）] 
- 沙拉查词版本: [7.9.3] 

## 描述问题

有道网页翻译总是“没有难词”，无论选择什么翻译级别都是这样，只能全文翻译。

在多个网站上使用有道网页翻译，都是这样子

[网站1](https://www.openshift.com/blog/adding-authentication-to-your-kubernetes-web-applications-with-keycloak)

[网站2](https://github.com/keycloak/keycloak-quickstarts)

## 复现步骤

1. 打开 [网站1](https://www.openshift.com/blog/adding-authentication-to-your-kubernetes-web-applications-with-keycloak)，
2. 点击右键--沙拉查词--有道网页翻译
3. 网页顶部出现有道翻译选项，但是总是显示“恭喜你，该网页上没有难词”

在任何英文网站上都能重现此问题，说明和网页内容无关

## 期待的正常行为

应该能找出难词，实现部分翻译

## 截图

![image](https://user-images.githubusercontent.com/2044143/79953742-ef2b7500-84ae-11ea-8960-6fca576475e7.png)

**Comment by crimx** [comment]
你好，谢谢反馈。这是有道的问题，无法解决。

**Comment by crimx** [comment]
另外见[注意事项](https://saladict.crimx.com/notice.html)，网页翻译请使用官方扩展。
