### ISSUE TITLE
鼠标滚轮滚动到网页边界才能作用到插件的浮动页面上

### ISSUE THREAD

**Issue by a448582655** [crimx/ext-saladict#750]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Chrome81] 
- 沙拉查词版本: [7.9.3] 

## 请描述目前使用沙拉查词遇到什么不便

鼠标滚轮滚动到网页边界才能作用到插件的浮动页面上，而不是获取鼠标的焦点从而单独作用于后面的网页或者沙拉查词的浮动窗口，这样只能通过下拉滚动条来单独滚动沙拉词条

## 理想情况下，沙拉查词应该怎么做

能够获取鼠标焦点，滚动沙拉查词的页面，而不是优先滚动原网页

## 额外信息

gif效果
[https://gifyu.com/image/l8rC](gif效果)

**Comment by crimx** [comment]
沙拉查词已经阻止了滚动传播，你的操作系统和浏览器都没有问题，考虑是其它插件修改了样式。

**Comment by a448582655** [comment]
> 沙拉查词已经阻止了滚动传播，你的操作系统和浏览器都没有问题，考虑是其它插件修改了样式。

确实，我排查了一下，与CrxMouse冲突了，修改了CrxMouse的配置项，把鼠标滚轮去掉就可以了，感谢
