### ISSUE TITLE
CNKI 翻译助手设置中，「显示双语例句」和「显示英文例句」开关无效

### ISSUE THREAD

**Issue by xxy935** [crimx/ext-saladict#752]
## 设备信息
- 操作系统: [Windows 10] 
- 浏览器版本: [Chrome 81.0.4044.122] 
- 沙拉查词版本: [7.10.1] 

## 描述问题

CNKI 翻译助手的「双语例句」和「英文例句」一定会显示，即使在设置中关闭了「显示双语例句」和「显示英文例句」。

**Comment by crimx** [comment]
感谢反馈
