### ISSUE TITLE
设置界面切换到黑暗模式后，重新进入设置界面时，会有白到黑的变化过程

### ISSUE THREAD

**Issue by hqyyqh** [crimx/ext-saladict#753]
## 设备信息
- 操作系统: [win10 1909] 
- 浏览器版本: [Chrome 81] 
- 沙拉查词版本: [7.10.1] 

## 请描述目前使用沙拉查词遇到什么不便

复现过程：
1. 设置界面切换到黑暗模式
2. 刷新设置界面或者从查词界面进入到设置界面会由白到黑变化。这个变化过程看起来有点眼花。

![ ](https://user-images.githubusercontent.com/38676455/80268878-adccdc80-86dd-11ea-99e3-c1d51cbc9b0a.gif)

## 理想情况下，沙拉查词应该怎么做

刷新或者重新进入设置界面时，直接显示黑暗界面，而不是白到黑的变化。

**Comment by crimx** [comment]
因为要读取设置，这个我目前没有什么好办法解决。

**Comment by crimx** [comment]
用了中间的灰色过渡一下貌似还可以。

**Comment by hqyyqh** [comment]
刚更新了v7.10.2，新加的灰色过渡舒服了很多，不过又有个一个新的问题。
1. 浏览器窗口最大化时，沙拉查词扩展设置页面拉到最底部，左下角和右下角就会出现灰色的小色块🤣。
2. 黑暗模式下也会出现这个小色块。显示器分辨率是 1902*1080。
![Snipaste_2020-04-26_18-02-32_compress](https://user-images.githubusercontent.com/38676455/80304495-cd046080-87e8-11ea-88ff-080ba094cadb.png)

**Comment by crimx** [comment]
shit 这个不是黑块，是背景的灰色，我看看怎么遮上。
