### ISSUE TITLE
PDF阅读器崩了！！！！！！

### ISSUE THREAD

**Issue by morjoey** [crimx/ext-saladict#755]
PDF.js v2.5.123 (build: cd287875)
信息：The browser/environment lacks native support for critical functionality used by the PDF.js library (e.g. `ReadableStream` and/or `Promise.allSettled`); please use an ES5-compatible build instead.

急死我了，我书签里很多pdf都是存在沙拉里的，有什么办法能解决这个问题或者让我把之前存储的pdf找出来的吗？

**Comment by crimx** [comment]
没事，只要链接在都会没问题的。你先冷静下载按模板反馈，给的信息太少了。

盲猜是浏览器版本过低，新版 PDF 阅读器去掉了很多兼容旧有浏览器的代码以减少体积和加快速度。

**Comment by northernCold** [comment]
我也出来这个问题，更新chrome浏览器后就可以正常使用了。

**Comment by Zeko-Ran** [comment]
我也突然出现了这个问题，不知道如何解决，谷歌浏览器版本已最新

**Comment by crimx** [comment]
看来有的朋友不能更新浏览器，我看看把兼容包打回去。

**Comment by Zeko-Ran** [comment]
> 看来有的朋友不能更新浏览器，我看看把兼容包打回去。

好棒啊今天就好使了^_^
