### ISSUE TITLE
悬浮取词被意外激活

### ISSUE THREAD

**Issue by Erimus-Koo** [crimx/ext-saladict#756]
## 设备信息
- 操作系统: [WIN10] 
- 浏览器版本: [Chrome81] 
- 沙拉查词版本: [最新版 - 不知道哪裏看版本] 

## 请描述目前使用沙拉查词遇到什么不便

- 开启悬浮取词，需要按住 `Ctrl`，延时 500ms。
- 在Chrome存在两个标签页，A和B。
- 当前页B激活，A在边上。
- 用快捷键 `Ctrl+w` 关闭B页时，如果鼠标刚好停留在A页上的某个单词处，有一定概率激活悬浮取词。
- 应该是在B页面使用 `Ctrl+w` 快捷键时，`Ctrl` 的按住时间已经纳入500ms计时，导致A页面激活时，延时秒数已经满足，且此时鼠标刚好在某个词上，悬浮取词被激活。
- 我实际使用时是用罗技的自定义鼠标键，应该录入 `Ctrl+w` 只是一瞬（未达到500ms），不知道为什么也会激发这个情况，而且很频繁。用键盘也可以复现。

## 理想情况下，沙拉查词应该怎么做

- 期待行为是，在页面被激活时，重新机算悬浮取词所需的延时。

**Comment by crimx** [comment]
嗯，应该在释放按键后重新计数。
