### ISSUE TITLE
划词时误激活悬浮取词

### ISSUE THREAD

**Issue by Erimus-Koo** [crimx/ext-saladict#758]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 请描述目前使用沙拉查词遇到什么不便

- 划词快捷键 和 悬浮取词快捷键 都是 `Ctrl`，悬浮取词延时 500ms。
- 在按住 `Ctrl` 划词之后，如果鼠标停留在最后一次单词上，并且释放鼠标。
- 先会激活划词翻译的弹窗，然后立刻变成悬浮取词最后一个词的弹窗。等于导致了划词翻译的失败。
- 原因猜测：
  按住 `Ctrl` 划词时，悬浮取词开始计时。释放鼠标时，先激活了划词翻译，后激活了悬浮取词。

## 理想情况下，沙拉查词应该怎么做

- 如果划词的弹窗激活，把悬浮取词的计时清零。或者设一小段间隔时间来阻止其它事件。

**Comment by crimx** [comment]
新版在按键放开后会取消悬浮取词。

**Comment by Erimus-Koo** [comment]
> 新版在按键放开后会取消悬浮取词。

请问新版什么时候出？版本号是多少？
目前7.11.2，问题依旧。

**Comment by crimx** [comment]
7.11.2 已经实现了这个功能。

但是如果继续按住 ctrl 不放依然会激活两次划词。这是因为每个划词功能的实现都是独立的，如果要互相影响就要将功能进行耦合，增加了逻辑复杂性和实现难度。这个代价我考虑了一下觉得不太值得，最好换用不同按键避免冲突。

**Comment by crimx** [comment]
在鼠标放开前按下 ctrl 然后放开，悬浮取词就会取消，同时激活 ctrl 划词。
