### ISSUE TITLE
Vivaldi獨立視窗的問題

### ISSUE THREAD

**Issue by Yusei-StarDust** [crimx/ext-saladict#759]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Vivaldi 81.0.4044.123] 
- 沙拉查词版本: [7.10.2] 

## 描述问题

不是出現獨立視窗，而是直接開新視窗了……這也導致獨立視窗的視窗大小無法任意調整

## 复现步骤

打開獨立視窗

## 期待的正常行为

正常的獨立視窗

## 截图

![image](https://user-images.githubusercontent.com/26076608/80307503-0eead200-87fc-11ea-8b14-b695381b194d.png)

不正常的獨立視窗顯示如附圖

## 额外信息

雖然Vivaldi是Chromium內核，但也一直有兼容性的問題，所以我猜這大概率也是Vivaldi自身的bug，不過還是厚顏無恥地來這裡發問了，畢竟也不是專業的，天知道到底是什麼原因導致的，至少希望可以得知相關技術術語的英文詞彙，也好去官方forum回報Orz

**Comment by crimx** [comment]
谢谢你的反馈。可以看一下是什么变化导致的，是最近出现问题还是一直是这样？是升级了浏览器还是扩展？这些都可以帮助排查问题。

相关的词汇是 `chrome.windows.create` 中的 `type: 'popup'` 浏览器没能以此打开 popup 窗口。

链接：
- <https://developer.chrome.com/extensions/windows#method-create>
- <https://developer.chrome.com/extensions/windows#type-CreateType>

**Comment by Yusei-StarDust** [comment]
> 谢谢你的反馈。可以看一下是什么变化导致的，是最近出现问题还是一直是这样？是升级了浏览器还是扩展？这些都可以帮助排查问题。
> 
> 相关的词汇是 `chrome.windows.create` 中的 `type: 'popup'` 浏览器没能以此打开 popup 窗口。
> 
> 链接：
> 
> * https://developer.chrome.com/extensions/windows#method-create
> * https://developer.chrome.com/extensions/windows#type-CreateType

謝謝您的耐心回覆，坦白說這是老問題了，之前Vivaldi還在2.X版本的時候，其實獨立視窗就不太成功，網址列(含extensions button)那一欄無法消除，個人猜測因為這個Bug的附帶影響所以獨立視窗才沒辦法自由調整大小，受Chrome的最小視窗限制，現在Vivaldi升級到3.0，問題就更嚴重了，已經不是獨立視窗，而是開新視窗了啊Orz連分頁列、書籤列都出現了

順帶一說，無痕模式下Vivaldi獨立視窗也無法響應網頁劃詞(有在設定/extensions中啟用允許在無痕模式中執行)，不過這是另外一個問題就是了……

**Comment by crimx** [comment]
这个只能由 Vivaldi 团队来修复了。

**Comment by Yusei-StarDust** [comment]
> 这个只能由 Vivaldi 团队来修复了。

了解，非常謝謝您耐心的回答

**Comment by GH01** [comment]
独立窗口 按设计是否应该跟 Gmail (页底的) Activity Details 弹出的简化窗口一样？
Vivaldi 对 Gmail Activity Details 用的是 简化窗口。
