### ISSUE TITLE
pdf浏览问题

### ISSUE THREAD

**Issue by Chancex10** [crimx/ext-saladict#760]
最近几天开始在谷歌里用打开的pdf会集体突然消失，两台设备win10和mac均有此现象，不知道怎么回事。

**Comment by crimx** [comment]
> 用打开的pdf会集体突然消失

请你理顺一下语文，然后按模板反馈。

**Comment by Chancex10** [comment]
**设备信息**
操作系统: [win10，macos10.15]
浏览器版本: [chrome81.0.4044.122]
沙拉查词版本: [v7.10.3]
**描述问题**
同时打开的几个pdf浏览器会同时在某一时间消失，并且在历史记录查找不到浏览记录
<img width="755" alt="Screenshot 2020-04-26 at 20 28 05" src="https://user-images.githubusercontent.com/50698421/80317551-7f91ee80-87fc-11ea-952f-b42576acdf9b.png">
如上图所示，以上三个pdf浏览器会自动关闭，剩下普通网页，变成下图。
<img width="655" alt="Screenshot 2020-04-26 at 20 29 54" src="https://user-images.githubusercontent.com/50698421/80317614-c41d8a00-87fc-11ea-83df-e1203552c27b.png">

**Comment by crimx** [comment]
这么奇怪的现象？我暂时无法复现这个现象，“某一时间”是多长，不太好把握。

> 同时在某一时间消失

可能是扩展崩溃，可以在扩展管理页面查看有无崩溃提醒。

> 并且在历史记录查找不到浏览记录

这个就更奇怪了。历史记录在页面打开那一刻就记上了，即便扩展崩溃也应该不会受影响。

考虑是浏览器安装出现问题，或某个有修改历史记录权限的扩展。

可以重启试试。
