### ISSUE TITLE
PDF阅读器无法打开本地pdf文件，错误提示缺少PDF.js

### ISSUE THREAD

**Issue by Zeko-Ran** [crimx/ext-saladict#761]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Chrome 72.0.3626.121]，公司固定版本无法更新 
- 沙拉查词版本: [] 

## 描述问题

pdf阅读器突然无法打开本地pdf文件，默认default也出现同样错误提示：
An error occurred while loading the PDF.  Less Information Close
PDF.js v2.5.123 (build: cd287875)
Message: The browser/environment lacks native support for critical functionality used by the PDF.js library (e.g. `ReadableStream` and/or `Promise.allSettled`); please use an ES5-compatible build instead.

## 复现步骤

1. 右键沙拉查词
2. 点击“在PDF阅读器中打开”
3. （右上角打开本地任意PDF文件）——不打开也会报错，选择本地文件也无法打开一样报错
4. 问题出现

## 截图

![image](https://user-images.githubusercontent.com/25809089/80330449-c1ac4600-8877-11ea-9398-4cf9c5269f1a.png)

## 额外信息

因为浏览器是公司固定版本，无法自主更新，但是之前沙拉查词中的pdf是可以使用的，这个问题是突然出现的。出现问题后，我在插件中心里又下载了使用PDF.js的pdf viewer，这个插件是可以在谷歌浏览器中打开本地pdf的，但是无法使用沙拉查词划词翻译。

**Comment by Zeko-Ran** [comment]
沙拉查词版本：7.10.3
不知道为什么没粘上去

**Comment by crimx** [comment]
duplicate of #755
