### ISSUE TITLE
网页中的选块不该因打开页内浮窗而消失

### ISSUE THREAD

**Issue by GH01** [crimx/ext-saladict#764]
## 设备信息
- 沙拉查词版本: [7.10.4]

## 请描述目前使用沙拉查词遇到什么不便
页内浮窗打开时，其搜索栏中的文本呈选中状态。
不知这有多大意义，
但这导致网页中的选块消失，影响用户的后续操作。

## 理想情况下，沙拉查词应该怎么做
保持网页中的选块。
（或者为此增一选项）

**Comment by crimx** [comment]
???

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6882794/80440172-c1c14a00-893a-11ea-8fa9-985f13b93d6a.gif)

**Comment by GH01** [comment]
## 补充：
在 off 状态时，
用 Ctrl*3 就会发生。

P.S.
照此，用快捷键可能也会发生。
但我无法测试：
Toggle instant capture 就是翻译选块的快捷键吧？
但我这里无效。
（别的快捷键正常，相同的键赋给别的命令也正常。）
你也试一下，如果你那里正常，那我再找原因。

**Comment by crimx** [comment]
> 在 off 状态时，用 Ctrl*3 就会发生。

这个是 Quick Search Panel，目的就是用来快速输入查词，你不需要这个。应该通过 Search Modes 设置不同的划词方式来激活页面内查词面板。

Instant capture 是鼠标悬浮取词，见 Search Modes 设置说明。

**Comment by GH01** [comment]
怎样设置出：
off + 快捷键 = 页内浮窗
能否教我一下？

我知道【off + 快捷键】可以出 按钮弹窗 或 独立窗口，
但能不能出 页内浮窗 呢？

目前的【off + Ctrl*3】其实就是我想要的方式之一，但我宁愿用快捷键。

**Comment by crimx** [comment]
你最好说明一下你这么做是要达到什么目的？我实在没看懂。

快捷查词的设计是用来输入查词，如果你仅仅需要划词，普通的划词模式快捷键就已经可以满足。在「划词习惯」中设置。

**Comment by GH01** [comment]
比如我只想在必要时用快捷键查询选块（不要自动查询），
并且是用 页内浮窗。

（别的同类扩展可以做到这样。）

**Comment by crimx** [comment]
沙拉查词的功能不会因为同类扩展有就得实现，而是以合适为前提。

快捷查词可以与独立窗口的焦点获取功能一起做一个小优化，以判断获取焦点的时机。
