### ISSUE TITLE
界面设计优化建议

### ISSUE THREAD

**Issue by sky5454** [crimx/ext-saladict#768]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 请描述目前使用沙拉查词遇到什么不便

1. 非圆角的视觉不太好，改成小圆角圆润一点，感官体验上会好很多
2. 各词典的`更改语言`没有统一，界面冗余度大。
![image](https://user-images.githubusercontent.com/12370628/80439949-3e9ff400-893a-11ea-8d91-effbd3f36d68.png)
3. 定位到自己想看的词典需要用鼠标滑轮，在长文本里，人眼定位的操作效率很低

## 替代方案

1. 采用四角圆角设计
2. 使用右键菜单模式（即为沙拉查词结果界面增加右键菜单）
3. 加个左侧细边栏，里面放各词典图标（点击图标就定位并自动展开）

**Comment by crimx** [comment]
你好

1. 你可以自定义 CSS 自行调整喜欢的样式。
2. Duplicate of #715
3. 沙拉查词顾名思义是更注重查词体验。长文翻译不适合使用沙拉查词。

> 加个左侧细边栏，里面放各词典图标

快速跳转词典功能可以考虑，但应该不会在左侧增加一栏，这样会比较难看。目前通过不同情景模式切换可以一定程度上减少冗余词典量。
