### ISSUE TITLE
独立窗口快捷键 导致 设置中的“预览查词面板”被触发？

### ISSUE THREAD

**Issue by GH01** [crimx/ext-saladict#769]
## 设备信息
- 操作系统: Win 7
- 浏览器版本: Vivaldi 3.0.1874.27 (内核 Chrome 81.0.4044.123)
- 沙拉查词版本: 7.10.4

## 描述问题
独立窗口快捷键 导致 设置中的“预览查词面板”被触发

## 复现步骤
1. 打开设置，
2. 无论在哪个标签按下 Open or highlight standalone dict panel 快捷键，
结果：设置标签中的“预览查词面板”被触发。

## 期待的正常行为
设置标签中的“预览查词面板”不应该被触发。

## 额外信息
如果不能重现，我再尝试补充。

**Comment by crimx** [comment]
可以复现，谢谢反馈。
