### ISSUE TITLE
按钮上的off经常消失

### ISSUE THREAD

**Issue by GH01** [crimx/ext-saladict#770]
## 设备信息
- 操作系统: Win 7
- 浏览器版本: Vivaldi 3.0.1874.27 (内核 Chrome 81.0.4044.123)
- 沙拉查词版本: 7.10.4

## 描述问题
按钮上的off经常消失。
比如：
▲打开独立窗口后
▲关掉一个标签后
▲网页载入期间
▲停用+启用扩展后

虽不影响使用，但变化会无谓地引人注目。

## 期待的正常行为
off应该静态恒稳显示。

**Comment by GH01** [comment]
P.S.
一碗沙拉这么漂亮，off底板若能透明，可能更好看。

**Comment by crimx** [comment]
浏览器不支持透明显示。你如果常关闭的话可以不关闭总开关，而是直接取消勾选所有划词模式。

**Comment by GH01** [comment]
![image](https://user-images.githubusercontent.com/19272301/80637304-5b9b0b00-8a91-11ea-9125-a15c245d7c2d.png)

**Comment by crimx** [comment]
看到黑色的圈圈了么……🤯

**Comment by crimx** [comment]
目前在所有浏览器上都是没有办法去掉。

**Comment by GH01** [comment]
我倒觉得有边界挺好，玻璃感

**Comment by crimx** [comment]
打算全部弄成灰色-彩色变换好了，免得打扰用户注意力。

**Comment by GH01** [comment]
但本题最初所说bug仍在，只不过在7.11.0成了颜色变化。

**Comment by GH01** [comment]
> 但本题最初所说bug仍在，只不过在7.11.0成了颜色变化。

请确认一下这个问题是否不再处理，谢谢。

**Comment by crimx** [comment]
不确定，还没有空看这个问题。
