### ISSUE TITLE
划词时面板上的翻译很难复制

### ISSUE THREAD

**Issue by Kimice1230** [crimx/ext-saladict#771]
edge浏览器。
复制时很多时候会复制粘贴成单词，翻译很难复制下来，但偶尔也可以复制。

**Comment by crimx** [comment]
你好，

> 复制时很多时候会复制粘贴成单词，翻译很难复制下来，但偶尔也可以复制。

没看懂。请按模板提供完整信息，包括复现的步骤。

**Comment by Kimice1230** [comment]
# 感谢回复！

## 设备信息

- 操作系统: [Window10]
- 浏览器版本: [Edge 81.0.416.68 (官方内部版本) (64 位)]
- 沙拉查词版本: [v7.10.4]

## 请描述目前使用沙拉查词遇到什么不便

- 复制翻译面板上的内容时无法知道自己是否成功复制。

- 右键没有复制功能框，但是ctrl+c时也无法复制，粘贴下来的并不是翻译而是之前剪切板上的内容。

## 理想情况下，沙拉查词应该怎么做

- 希望在面板右键有复制的功能框。

## 替代方案
- 选中需要复制的文字时浮现复制按钮。
## 额外信息

- 复制成功与否的条件不太明确，有时候可以复制成功。

- 之前以为是和别的软件快捷键冲突，但是后来发现即使关了也没有反应。

**Comment by crimx** [comment]
谢谢你的补充，查词面板只是普通网页界面，所有浏览器功能都应该可以正常使用。按你上面的描述无法确定是什么问题。沙拉查词目前没有专门支持 Edge，如果你有 Chrome 的话可以试试在 Chrome 上是否能正常复制，以排除是 Edge 的问题。

> 包括复现的步骤

你填写的是「功能建议」模板，请改为反馈 bug 提供复现问题的具体步骤。

**Comment by crimx** [comment]
> 右键没有复制功能框

这是 Chrome 里的样子

![image](https://user-images.githubusercontent.com/6882794/80859155-03caf280-8c91-11ea-8605-27746b70a178.png)

**Comment by Kimice1230** [comment]
## 目前清楚是什么问题了

- 我之所以复制不了，是因为我把那个网站当作站点安装了。![image](https://github.com/Kimice1230/pics/blob/master/image-20200502170131119.png)
  - 其他功能都和网页差不多，所以没有注意到orz

- Edge和Chrome都可以复制。

  ![image](https://github.com/Kimice1230/pics/blob/master/image-20200502170418069.png)

## 复现步骤

- 打开被当作应用安装的网站，选中需要翻译的单词。
- 用沙拉进行查词。
- 选中翻译后的文本。
- 右键没有反应，Ctrl+c时灵时不灵。

感谢您的耐心回复！因为我是第一次在github上反馈所以不太清楚模板！真的很喜欢沙拉划词！加油( •̀ ω •́ )✧






> > 右键没有复制功能框
> 
> 这是 Chrome 里的样子
> 
> ![image](https://user-images.githubusercontent.com/6882794/80859155-03caf280-8c91-11ea-8605-27746b70a178.png)

**Comment by crimx** [comment]
没关系，Github 评论贴图可以在评论框底下的长栏点击上传，或者直接拖进来都可以的。

**Comment by crimx** [comment]
> 打开被当作应用安装的网站，选中需要翻译的单词。

也是没有问题的。可以的话请提供出现问题的页面。

PS 沙拉查词[官网](https://saladict.crimx.com)也是可以以应用方式打开。

**Comment by Kimice1230** [comment]
> > 打开被当作应用安装的网站，选中需要翻译的单词。
> 
> 也是没有问题的。可以的话请提供出现问题的页面。
> 
> PS 沙拉查词[官网](https://saladict.crimx.com)也是可以以应用方式打开。

谢谢！这是一个叫做notion的网站！ [https://www.notion.so/](url)
![image](https://user-images.githubusercontent.com/63463437/80897325-e39b4200-8d29-11ea-871c-c7eacad16f2e.png)
我试了一下，安装后的网页和原网页都和普通网页一样可以复制文本，但是两者都不能复制沙拉面板上的内容。
![image](https://user-images.githubusercontent.com/63463437/80897387-8f449200-8d2a-11ea-852f-e36f2ffa4fe0.png)

**Comment by crimx** [comment]
嗯，这样的场景相对小众，Edge 可能还没来得及优化。

**Comment by crimx** [comment]
可以向 Edge 团队反馈，这个不是扩展层面的问题，沙拉查词也做不了什么。

**Comment by Kimice1230** [comment]
> 可以向 Edge 团队反馈，这个不是扩展层面的问题，沙拉查词也做不了什么。

谢谢！刚刚chrome突然也有相同的状况出现，但是清了缓存之后又好了，edge真是无力回天……谢谢您的帮助！😊
