### ISSUE TITLE
能不能提供点击沙拉图标关闭查词面板的功能？

### ISSUE THREAD

**Issue by frankyuan** [crimx/ext-saladict#772]
## 设备信息
- 操作系统: [Windows 10] 
- 浏览器版本: [Chrome 81] 
- 沙拉查词版本: [] 

## 当显示查词面板时，点击沙拉图标能不能隐藏查词面板。

在看到单词的翻译后，关闭查词面板有点不方便，因为点击关闭按钮距离比较远，点击页面关闭的话需要挪下鼠标再点击。而大部分情况下沙拉图标就在鼠标附近。

## 理想情况下，沙拉查词应该怎么做

选择要查的词，点击沙拉图标，显示查词面板。再次点击沙拉图标，隐藏查词面板（最好连沙拉图标一并隐藏）。

## 额外信息

插件很好用，翻译的很快，十分感谢。也可能是我刚开始用没找到相应功能，如果已经有设置/操作能方便的关闭查词面板请告知，谢谢

**Comment by crimx** [comment]
> 而大部分情况下沙拉图标就在鼠标附近

你好，我不是很明白。按这个逻辑现在图标消失的后这个位置底下就是页面，点击一下不是同样也可以隐藏？为什么需要点击图标？

另外按 <kbd>Esc</kbd> 也可以隐藏。

**Comment by frankyuan** [comment]
谢谢了，用Esc挺方便的。有的页面是链接，点击一下就跳转到别的页面了。

**Comment by jiangnanqw12** [comment]
> > 而大部分情况下沙拉图标就在鼠标附近
> 
> 你好，我不是很明白。按这个逻辑现在图标消失的后这个位置底下就是页面，点击一下不是同样也可以隐藏？为什么需要点击图标？
> 
> 另外按 Esc 也可以隐藏。

求问，我为啥摁ESC，无法隐藏了呀

**Comment by jiangnanqw12** [comment]
> 谢谢了，用Esc挺方便的。有的页面是链接，点击一下就跳转到别的页面了。

求问，我为啥摁ESC，无法隐藏了呀
