### ISSUE TITLE
多种模式下（默认、学术、翻译模式等）谷歌翻译均无法使用

### ISSUE THREAD

**Issue by yisenz** [crimx/ext-saladict#773]
## 设备信息
- 操作系统: [] 1909
- 浏览器版本: [] chrome 81.0
- 沙拉查词版本: [] v7.10.4

## 描述问题

使用默认、学术等模式进行翻译时，其他翻译接口均正常使用，如有道等，但是谷歌翻译一直显示...并且无法正确使用！

**Comment by crimx** [comment]
![image](https://user-images.githubusercontent.com/6882794/80779162-5b883180-8b9d-11ea-82a6-ded31bd45171.png)

请检查你的网络状态。

**Comment by yisenz** [comment]
感谢回复，如图所示，尝试了挂V2与不挂V2，均无法使用，其他几个均是正常的





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CRIMX"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月1日(星期五) 中午11:18
收件人:&nbsp;"crimx/ext-saladict"<ext-saladict@noreply.github.com&gt;;
抄送:&nbsp;"SQ~Y"<781540927@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [crimx/ext-saladict] 多种模式下（默认、学术、翻译模式等）谷歌翻译均无法使用 (#773)





 

 
请检查你的网络状态。

**Comment by yisenz** [comment]
![QQ图片20200501111936](https://user-images.githubusercontent.com/64624954/80779407-216b5f80-8b9e-11ea-83be-e13d2e827573.png)

**Comment by yisenz** [comment]
尝试了打开google翻译的网页，也是不可以的。。。挂了V2，结果仍然是能打开google搜索但打不开google翻译。或许是我网络的问题？我再次尝试一下，非常感谢！

**Comment by yisenz** [comment]
继续更新  google translate .cn网址无论挂V2还是不挂V2均打不开，translate.com挂了V2正常打开，所以请问是否与.cn网址有关系呢

**Comment by crimx** [comment]
你可以在词典设置中调整是否访问 cn

**Comment by Len-Jon** [comment]
找不到哪里可以设置 调整是否访问.cn

**Comment by crimx** [comment]
设置-词典管理-词典列表中谷歌翻译右侧的小铅笔图标。
