### ISSUE TITLE
浏览器外划词保存生词本后无法保存上下文

### ISSUE THREAD

**Issue by DRLH07** [crimx/ext-saladict#774]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Chrome 81.0.4044.129（正式版本）] 
- 沙拉查词版本: [v7.9.3] 

## 描述问题

福昕高级PDF编辑器以及XODO 等PDF阅读器打开PDF 可以通过Quicker调用 Saladict 实现全局查词 但将单词保存到生词本的时候无法保存上下文，但在Chrome浏览器中查词 保存生词本的时候可以保存上下文

## 复现步骤

1.用外部PDF阅读器打开PDF
2.选中单词 通过Quicker调用Saladict进行查词（此步骤无问题）
3.保存生词本时仅保存选中的单词本身 未保存上下文

## 期待的正常行为

希望能够浏览器之外 PDF阅读器调用Saladict查词 保存生词本的时候可以保存PDF的上下文 谢谢！！！

**Comment by crimx** [comment]
浏览器外的划词不受扩展控制，请阅读[说明](https://saladict.crimx.com/native.html)了解浏览器外划词原理。目前应该没有这样的辅助工具。

**Comment by DRLH07** [comment]
感谢回复！

CRIMX <notifications@github.com> 于2020年5月1日周五 下午4:26写道：
