### ISSUE TITLE
chrome无法更改为全局快捷键

### ISSUE THREAD

**Issue by TaiwenYou** [crimx/ext-saladict#775]
后面的选项是灰色的，突然就这样了，我试了下Edge也无法修改。
![image](https://user-images.githubusercontent.com/22187367/80865568-f3307180-8cbc-11ea-8e60-10ed4f8ae0b6.png)

**Comment by TaiwenYou** [comment]
salad：7.11
chrome:版本 81.0.4044.129（正式版本） （64 位）
win10 64位

**Comment by TaiwenYou** [comment]
之前是chrome 76，出现问题后我升级到81了结果还是老样子。已打开chrome后台。

**Comment by crimx** [comment]
见 #743 。第一个是 Chrome 给每个扩展自动生成的快捷键，取这个名字确实很费解，改不了没办法。

不过为什么要对这个设置全局快捷键？下面沙拉查词提供的快捷键应该可以满足。

**Comment by TaiwenYou** [comment]
> 见 #743 。第一个是 Chrome 给每个扩展自动生成的快捷键，取这个名字确实很费解，改不了没办法。
> 
> 不过为什么要对这个设置全局快捷键？下面沙拉查词提供的快捷键应该可以满足。

昨天没看明白，今天弄懂了。Chrome自己的问题，我们设置快捷键应该是在快捷查词，而不是激活程序（虽然设置激活程序也能唤出沙拉），但是我猜你的意思应该是按照如下设置：
![image](https://user-images.githubusercontent.com/22187367/80897982-d0d83b80-8d30-11ea-9ba0-6e0e904275b5.png)

**Comment by crimx** [comment]
这个可以，还有一个是让沙拉查词直接搜剪贴板。

**Comment by TaiwenYou** [comment]
我试了下，这样设置没法唤出查词界面，换了好几个快捷键，无论是在chrome，还是其他程序中都无法唤出

**Comment by crimx** [comment]
是不是在其它快捷键上设置过，Chrome 貌似需要重启系统才会释放全局快捷键，比较玄学。

**Comment by TaiwenYou** [comment]
我试试，我刚刚设置在 沙拉中打开pdf能够实现全局唤起，就打开词典貌似不太行

**Comment by TaiwenYou** [comment]
Great! It's working. Thank you very much!

**Comment by Jason-purse** [comment]
![image](https://user-images.githubusercontent.com/57804598/123084067-4df1d300-d453-11eb-9e58-54ed1e84f080.png)
chrome 无法进行全局设置

**Comment by crimx** [comment]
先设置快捷键，才能设置全局。
