### ISSUE TITLE
沙拉查词小鸡词典无法查询 emoji

### ISSUE THREAD

**Issue by hqyyqh** [crimx/ext-saladict#776]
## 设备信息
- 操作系统: [Windows10 1909] 
- 浏览器版本: [Chrome81] 
- 沙拉查词版本: [v7.11.0] 

## 描述问题

测试了新增的小鸡词典，发现无法查到emoji（例如😂）的显示结果。

## 复现步骤

1. 在小鸡词典网页版可以正常显示 emoji的搜索结果，
例如 https://jikipedia.com/search?phrase=😂 
或者 https://jikipedia.com/search?phrase=🌶️④💉💧🐮🍺

2. 在沙拉查词内查询则无法显示
![ ](https://user-images.githubusercontent.com/38676455/80907830-9d0b0f00-8d4c-11ea-81f2-6f07e7310a8a.gif)

---
一开始我以为是沙拉查词所有词典都不支持emoji，直到测试到维基词典 可以正常查询，例如 https://en.wikipedia.org/wiki/😂 
![ ](https://user-images.githubusercontent.com/38676455/80907786-456ca380-8d4c-11ea-87e1-dd96fc51525e.png)

## 期待的正常行为

理想的情况就是能够正常查到 emoji 了。

> 算是~~无聊间~~无意间发现的一个小问题，并不影响任何使用。

**Comment by crimx** [comment]
你要在词典设置中允许「其它字符」。
