### ISSUE TITLE
希望查词面板上提供查询链接实现跳转

### ISSUE THREAD

**Issue by sean2feng** [crimx/ext-saladict#777]
## 设备信息
- 操作系统: Windows 10
- 浏览器版本: Microsoft Edge 81.0.416.64 (x64)
- 沙拉查词版本: 7.10.4

## 请描述目前使用沙拉查词遇到什么不便

在之前的更新日志里面看到因为牛津学习字典（OALD）失效，而被Lexico替代，但两者还是不一样。OALD是基于Oxford 3000编写的，释意和例句都通常会简单一些，更适合多数英语学习者。

## 理想情况下，沙拉查词应该怎么做

如果牛津学习字典（OALD）这一项维护起来比较耗时耗力，是否可以只提供网页查询链接（而不提供内容），以便于用户点击之后，实现跳转？（类似于chrome商店里的一个名为word discoverer的功能）

**Comment by crimx** [comment]
你可以添加右键菜单，[使用说明](https://saladict.crimx.com/manual.html)。（这个菜单还可以设置为点击地址栏旁图标时触发，见「右上弹框」）

未来有个计划是给划词弹出来的沙拉图标增加二级图标，但这个很遥远了。

**Comment by sean2feng** [comment]
> 你可以添加右键菜单，[使用说明](https://saladict.crimx.com/manual.html)。（这个菜单还可以设置为点击地址栏旁图标时触发，见「右上弹框」）
> 
> 未来有个计划是给划词弹出来的沙拉图标增加二级图标，但这个很遥远了。

谢谢。我有使用通过右键菜单，不过我目前的操作是：双击或者划词——右击——在菜单中找到选择沙拉查词——左击直达的链接。如果能够添加到查词面板中，就只需要两步：双击或者划词——左击直达链接。:) 我等会再仔细看看有没有更快速的方法。

我用word discoverer有几年了。今天第一次接触使用到沙拉查词，很兴奋。我跟我一个程序员朋友说，假如我会编程的话，沙拉查词就是那种我想要做的东西。:D

真得非常感谢。

**Comment by crimx** [comment]
> 如果能够添加到查词面板中，就只需要两步：双击或者划词——左击直达链接。

添加到查词面板中肯定是不行的，这是两种不同的信息，放在一起会打乱用户的预期。

未来二级图标除了可以选择打开链接还可以快速选择不同情境模式。

> 我用word discoverer有几年了。今天第一次接触使用到沙拉查词，很兴奋。我跟我一个程序员朋友说，假如我会编程的话，沙拉查词就是那种我想要做的东西。:D

😆😆
