### ISSUE TITLE
firefox扩展的v7.11.0查词面板无法输出所有字典的查询结果

### ISSUE THREAD

**Issue by Cincinnatuscitizen4** [crimx/ext-saladict#778]
## 设备信息
- 操作系统: Window10 
- 浏览器版本: Firefox 75.0(64-bit) 
- 沙拉查词版本: 7.11.0 

## 描述问题

正常使用的过程中，突然无法接收到所有工具源的翻译结果（不管是划词翻译or直接在面板上搜索查询；不管是pdf文件or平常的网络页面；不管时中文的or英文的）

## 复现步骤

1.在pdf阅读器中打开.pdf文件（问题出现之前一直在使用的文件）
2.双击选中enthusiasm 
3.鼠标移动到出现的sala图标
4.问题出现，查词面板上的各种字典停留在5个红点，不再有结果出现（正常使用的过程中突然出现的问题）

## 期待的正常行为

跟往常一样，查词面板上的各个字典正常反馈结果，有些字典可能有延迟

## 截图

![image](https://user-images.githubusercontent.com/64823449/81035491-c2735680-8ecd-11ea-9088-ad0d3dbb29a3.png)

## 额外信息

1.出问题后，发现扩展的版本似乎刚刚更新了
2.remove扩展，重新安装后，问题依旧
3.全部词典都没有结果。但是在面板搜索下拉，有实时结果出来。比如键入of，下拉出现of/offer/office等等实时结果

**Comment by crimx** [comment]
感谢反馈

**Comment by 108678868** [comment]
我也这样，退回7.9.3版就好了

**Comment by crimx** [comment]
更新已经准核了，也可以在扩展管理页面的齿轮按钮里手动点击更新。

**Comment by Cincinnatuscitizen4** [comment]
可以使用了，有劳了，谢谢。黑暗模式很酷！加油！
