### ISSUE TITLE
After update, the dict doesn't work on firefox

### ISSUE THREAD

**Issue by Unknown-Chinese-User** [crimx/ext-saladict#779]
## 设备信息
- 操作系统: [macOS10.15.4] 
- 浏览器版本: [firefox75.0] 
- 沙拉查词版本: [v7.10.4] 

## 描述问题
在更新了沙拉查词后，Firefox的沙拉查词就用不了了，我在chrome上的查词就可以正常用

## 复现步骤
我在[维基](https://en.jinzhao.wiki/wiki/Action-adventure_game)随便一个页面划了生词(我在这个界面总是等了很久都没用)
<img width="604" alt="Snipaste_2020-05-05_14-19-21" src="https://user-images.githubusercontent.com/56683174/81039540-ec337a00-8edb-11ea-8793-8b5f4ab4fa92.png">
下图是我在Chrome的效果，可以正常用（等的时间不长）
<img width="552" alt="Snipaste_2020-05-05_14-25-40" src="https://user-images.githubusercontent.com/56683174/81039704-58ae7900-8edc-11ea-9d1c-11794bc7a8a0.png">

**Comment by crimx** [comment]
Duplicate of #778

**Comment by Unknown-Chinese-User** [comment]
ok，thank you
