### ISSUE TITLE
Firefox上的V7.11.1，遗失了原先的2个功能

### ISSUE THREAD

**Issue by Cincinnatuscitizen4** [crimx/ext-saladict#780]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Firefox75] 
- 沙拉查词版本: [7.11.1] 

## 描述问题

1.查词并收藏到生词本后，查词面板略变暗，并且无法交互（无法下拉、复制、播放等）。
2.生词本的条目‘编辑’‘保存’后，浏览器Tag没有自动刷新，依然呈现旧的页面。

## 复现步骤

1.1划词查询enthusiasm
1.2点击查词面板右上角‘爱心’收藏
1.3左侧依然是查词面板，右侧生成新的生词本窗口
1.4问题出现：左侧的查词面板变成了非激活状态，无法进行任何操作。

2.1点击右侧生词本窗口的右下角‘保存’按钮
2.2问题出现：已打开的firefox生词本Tag，没有像以往自动刷新。
2.3右击扩展打开‘生词本’，点击‘编辑’，修改内容后点击‘保存’
2.4问题出现：生词本Tag没有像以往自动刷新。

## 期待的正常行为

1.点击‘爱心’激活生词本后，左侧的查词面板依然可以使用
2.生词本改动保存后，已打开的生词本Tag自动刷新，显示最新的结果

## 截图

![image](https://user-images.githubusercontent.com/64823449/81051932-2eb58080-8ef5-11ea-874c-0f608764318f.png)

**Comment by crimx** [comment]
谢谢反馈
