### ISSUE TITLE
开启鼠标悬浮取词后无法复制长段文字

### ISSUE THREAD

**Issue by shiyindebcd** [crimx/ext-saladict#781]
开启鼠标悬浮取词，并开启直接取词，会出现无法复制大段文字的现象，有时候鼠标点一下输入框，没反应，输入光标会自动消失，有时候得点好几下才行，输入一段文字时，无法把光标点到文字中间插入，只能在最后按顺序输入
希望开发人员能看看

**Comment by crimx** [comment]
你好，在这个设置的底下已有文字说明不建议这么使用，请注意查看。

**Comment by shiyindebcd** [comment]
> 你好，在这个设置的底下已有文字说明不建议这么使用，请注意查看。

可是这个功能非常非常好用啊
对于我这种英文不好的人来说就是神器
要是能解决这个问题就完美了
