### ISSUE TITLE
建议从顶部的词典开始查起

### ISSUE THREAD

**Issue by edwinyzh** [crimx/ext-saladict#782]
首先谢谢开发这个好用的扩展。
用了几天，发现似乎翻译内容的显示是从底部到上部进行的。比如现在默认顶部是Bing字典，有时候网络慢，比如通过shadowsocks上网，我发现bing字典的翻译内容最后才显示。

这似乎不太科学，顶部字典应该优先显示内容，对吧。

希望扩展越做越好！

**Comment by sean2feng** [comment]
（不确定我有没有理解对）查词面板中的字典和翻译器的顺序是可以自定义调整的。

**Comment by crimx** [comment]
你好，

> 用了几天，发现似乎翻译内容的显示是从底部到上部进行的。

不是的。所有词典是由上往下发送请求，只有毫秒级偏差，可以理解为同时发送。

> 比如现在默认顶部是Bing字典，有时候网络慢，比如通过shadowsocks上网，我发现bing字典的翻译内容最后才显示。
> 
> 这似乎不太科学，顶部字典应该优先显示内容，对吧。

这没有不科学的，如果你的设备连接到必应较慢，那么返回结果自然比其它词典要慢。如果其它词典等必应返回再查询那么只会等更久。必应服务器没有被墙，可以检查 PAC 或代理工具让其直通。

> 希望扩展越做越好！

谢谢！❤️

> （不确定我有没有理解对）查词面板中的字典和翻译器的顺序是可以自定义调整的。

是的。请阅读[使用说明](https://saladict.crimx.com/manual.html)。

**Comment by edwinyzh** [comment]
感谢说明！那应该是因为不同的网络速度等原因，不同的翻译服务器返回结果的速度不一样了。
