### ISSUE TITLE
一行英文单词未完换行出现 - 

### ISSUE THREAD

**Issue by Bollie15** [crimx/ext-saladict#783]
## 设备信息
- 操作系统: [Window10]
- 浏览器版本: Chrome ?? 不知道版本 
- 沙拉查词版本: [目前最新版] 

## 请描述目前使用沙拉查词遇到什么不便
很简单，如下图，单词长度在换行的时候出现 `-` 这种情况提取文字翻以前可以检测换行吗？
![XYO)477OHB{JOQMDGS1C5A9](https://user-images.githubusercontent.com/56813612/81183819-34d55b00-8fe2-11ea-8bfd-c7bdd4c975ab.png)

可能有时候它恰好单词就是这样的，那可能又有问题！所以很纠结。

## 理想情况下，沙拉查词应该怎么做
理想建议换行的 `-` 直接删除，单词首尾连接在一起，如果真有那种刚好单词 `-` ，那没法了。

**Comment by crimx** [comment]
这个一般不影响翻译效果。

**Comment by Bollie15** [comment]
> 这个一般不影响翻译效果。

好的，感谢开发者大人

**Comment by Bollie15** [comment]
> 这个一般不影响翻译效果。

对了，开发者大人，您这个可以脱离 Chrome 使用吗？比如在没打开 Chrome 浏览器，能像那个有道词典全局点此翻译吗？（即不需要打开浏览器，我似乎没看到这方面的 tips，其他都需要安装其他的软件）

**Comment by crimx** [comment]
见[浏览器外划词](https://saladict.crimx.com/native.html)。
