### ISSUE TITLE
新版本独立页面会默认【查词时默认不获取焦点】，影响查词效率。

### ISSUE THREAD

**Issue by SKEETCHAN** [crimx/ext-saladict#784]
## 设备信息
- 操作系统: win10
- 浏览器版本:edge 版本 81.0.416.68 (官方内部版本) (64 位)
- 沙拉查词版本:7.11.2

## 描述问题
沙拉查词更新后，使用快捷键alt+l，全局唤出面板；会默认【查词时默认不获取焦点】，及时手动切换至获取焦点，独立页面被关闭后，再次唤起仍然会是不获取焦点。

## 导致问题
使用Quicker悬浮窗查询后，页面会在其他窗口下刷新内容，内部是弹出置顶。每次都需要额外选定

独立窗口查看新词，十分影响效率。

## 截图
![批注 2020-05-07 204938](https://user-images.githubusercontent.com/40740405/81296341-50089f00-90a4-11ea-8cff-c1471dd64fa0.png)

**Comment by crimx** [comment]
在「快捷查词」设置。

**Comment by crimx** [comment]
可以重现这个 bug

**Comment by crimx** [comment]
下个版本会修复，感谢反馈
