### ISSUE TITLE
希望添加日译中功能

### ISSUE THREAD

**Issue by Iiji** [crimx/ext-saladict#786]
## 设备信息
- 操作系统: [Win10] 
- 浏览器版本: [Chrome81.0.4044.129] 
- 沙拉查词版本: [7.11.2] 

## 请描述目前使用沙拉查词遇到什么不便

RT,发现没有日译中功能，设置里也没有找到如何设置

## 理想情况下，沙拉查词应该怎么做

希望添加一项设置，修改默认翻译到的语言

**Comment by crimx** [comment]
见[使用说明](https://saladict.crimx.com/manual.html)。

在设置-词典设置-调整各个词典设置。
