### ISSUE TITLE
不小心把错误的单词添加为自建词

### ISSUE THREAD

**Issue by catyou515** [crimx/ext-saladict#787]
## 设备信息
- 操作系统: Window10
- 浏览器版本: Chrome 81.0.4044.129
- 沙拉查词版本: Chrome插件

#不小心把错误的单词添加为自建词# 

不知道按了啥 把一个错误的词添加为自己的词还是啥的 然后就不会提醒错误 比如allo这个词我刚不知道点了啥 本来会提醒我这个词错误的 现在不会了 想知道去哪取消这个操作

## 理想情况下，沙拉查词应该怎么做

有一个专门区域放自己添加的词 可以后续添加 删除 修改

## 额外信息

就是正常allo这个单词下面会有红线提示错误嘛 现在不会了 想让他继续显示错误

**Comment by crimx** [comment]
> allo这个单词下面会有红线提示错误

你说的应该是 Chrome 浏览器自带的拼写检查功能，与扩展没有关系。

**Comment by catyou515** [comment]
> > allo这个单词下面会有红线提示错误
> 
> 你说的应该是 Chrome 浏览器自带的拼写检查功能，与扩展没有关系。

你这么一说我才想起chrome还有别的插件。。谢谢了
