### ISSUE TITLE
“/”问题

### ISSUE THREAD

**Issue by Mrliu8023** [crimx/ext-saladict#788]
## 设备信息
- 操作系统: [mac os] 
- 浏览器版本: [chrome81] 
- 沙拉查词版本: [7.11.1] 

## 描述问题

划线查询时碰到"/"有时会只查询"/"后面的内容。

## 截图

![](https://user-images.githubusercontent.com/24569795/81366925-681d0480-911e-11ea-911b-5737a53e4953.png)

**Comment by crimx** [comment]
> 划线查询时碰到"/"有时会只查询"/"后面的内容。

截图与反馈的信息不一致。图片中显示的是备选结果，因为这是一句话，有道词典只能查词。

机器翻译才支持句子。

![image](https://user-images.githubusercontent.com/6882794/81367287-5e47d100-911f-11ea-9c44-ccc5756993db.png)

**Comment by crimx** [comment]
你可以使用「有道翻译」。另外机器翻译可以与词典混合使用，可以对词典设置划词长度避免对单词翻译。

**Comment by Mrliu8023** [comment]
好的，收到，谢谢！

**Comment by Mrliu8023** [comment]
为什么我查询的时候只有有道这一个额。。
