### ISSUE TITLE
隐身模式下没有“在PDF阅读器中打开“的选项

### ISSUE THREAD

**Issue by wj199564** [crimx/ext-saladict#789]
![TIM图片20200508110253](https://user-images.githubusercontent.com/45971169/81390348-8b928000-911b-11ea-8cfb-bdc7dbe87168.png)
拓展程序管理里面  所有权限都打开了。

**Comment by crimx** [comment]
请把模板填写完整。

可以尝试重启浏览器或系统。同时检查正常模式里有无菜单以排除问题。
