### ISSUE TITLE
在js预览内查词，出现词典内容render error

### ISSUE THREAD

**Issue by lvjs** [crimx/ext-saladict#790]
在https://raw.githubusercontent.com/lodash/lodash/4.17.15-npm/core.js
里进行查词，无法渲染出词释义内容

## 设备信息
- 操作系统: [Window10]
- 浏览器版本:  [Chrome77]
- 沙拉查词版本: [7.11.2]

## 描述问题
如题

## 复现步骤
1. 打开https://raw.githubusercontent.com/lodash/lodash/4.17.15-npm/core.js
2. 选词查词，问题出现
![image](https://user-images.githubusercontent.com/9304685/81469741-4eacb300-9219-11ea-8151-d844dd966c23.png)

## 期待的正常行为
在如下页面进行查词，词释义可以正常渲染
https://code.jquery.com/jquery-3.5.1.js
![image](https://user-images.githubusercontent.com/9304685/81470127-992f2f00-921b-11ea-87fd-f19ecf645620.png)

## 额外信息

![image](https://user-images.githubusercontent.com/9304685/81470403-33dc3d80-921d-11ea-8a20-0875aa2860a0.png)
感觉是Content-Security-Policy限制导致的

**Comment by crimx** [comment]
感谢反馈，每个词典都是动态加载，看来收到了页面 CSP 限制，我看看有什么解决方式，如果不行的话只能回滚到原来的统一加载了。
