### ISSUE TITLE
建议增加最大规模的权威在线免费俚语词典 Green Dictionary of Slang （https://greensdictofslang.com）

### ISSUE THREAD

**Issue by funnybones2015** [crimx/ext-saladict#793]
## 词典名称以及链接
词典名称：Green Dictionary of Slang
网站链接：https://greensdictofslang.com

## 沙拉查词的已有的词典为什么不能满足？

Green Dictionary of Slang 是目前权威版权词典里面规模最大的一本俚语词典，而且现在其官网https://greensdictofslang.com 已经变成完全免费，以前其中的例句是收费的。该词典的俚语收词范围很大，而且包括各种英文国家的丰富例句，十分值得收录。由于是版权词典，比 Urban dictionary 这种自由开放的词典更加严谨权威。

## 单词举例

非常多俚语的用法只能在该词典查到。

## 截图

![ED0JQm8M5f](https://user-images.githubusercontent.com/15063728/81476186-099d7680-9243-11ea-8cbf-54f96927f7f5.png)
比如前几天在网上看到一个句子，用到了dumb，在那个句子里是表示强调的意思。而这个意思在其他很多词典里都找不到这个解释。只能在green dictionary of slang 里查到。

**Comment by crimx** [comment]
你好，这个词典确实很不错，但是也确实与现有的 Urban Dictionary 功能雷同。俚语来自民间，权威性相对不那么重要，Urban Dictionary 丰富的 UGC 能解决绝大多数问题。

> 比如前几天在网上看到一个句子，用到了dumb，在那个句子里是表示强调的意思。而这个意思在其他很多词典里都找不到这个解释。只能在green dictionary of slang 里查到。

这个在 Urban Dictionary 上也能查到的。

考虑到维护压力，功能雷同的词典沙拉查词暂不考虑添加。很感觉你抽出时间提建议。

**Comment by funnybones2015** [comment]
> 你好，这个词典确实很不错，但是也确实与现有的 Urban Dictionary 功能雷同。俚语来自民间，权威性相对不那么重要，Urban Dictionary 丰富的 UGC 能解决绝大多数问题。如果是成熟的俚语，其它几个英英词典一般都已经收录。
> 
> > 比如前几天在网上看到一个句子，用到了dumb，在那个句子里是表示强调的意思。而这个意思在其他很多词典里都找不到这个解释。只能在green dictionary of slang 里查到。
> 
> 这个在 Urban Dictionary 上也能查到的。
> 
> 考虑到维护压力，功能雷同的词典沙拉查词暂不考虑添加。很感谢你抽出时间提建议。

就我自己多年英语查词、学习和翻译经验来说，我觉得词典就需要权威点的，urban dictionary查找词义太过费时，很多垃圾信息，其实很影响体验。您多查一些词就明白了，很多都是网友杜撰，废话连篇，甚至很多错误。而且重要的是在读一些文学小说用到的俚语，比如二战时期的电影里面用到的俚语等等，这些历史性的俚语只有green dictionary of slang这本词典才能兼顾到。

**Comment by crimx** [comment]
> 就我自己多年英语查词、学习和翻译经验来说，我觉得词典就需要权威点的

你的观点没有问题，但前面我也说明了，维护一个词典涉及到更多因素。沙拉查词在布局时考虑的是如何用更少的词典涵盖更多角度，权威的词典沙拉查词不少，Urban Dictionary 作为一个权威的对立面，可以很好地形成互补。

> urban dictionary查找词义太过费时，很多垃圾信息，其实很影响体验。

每个东西都有侧重点，Urban Dictionary 的亮点是对新潮俚语的解释，这本身就很难或者来不及成为权威。对于成熟的俚语其它词典一般都已经收录。

> 您多查一些词就明白了，很多都是网友杜撰，废话连篇，甚至很多错误。

有错误我也是同意的。但这个很少会影响到查词结果，首先 Urban Dictionary 有投票机制，这个已经过滤掉大部分劣质的解释。剩下偶尔会出现抖机灵，一般不影响观感。我自己日常生活大部分时间是使用英语，所以 Urban Dictionary 是我重度使用的词典之一，目前还是很满意的。

> 而且重要的是在读一些文学小说、电影里用到的俚语，比如二战时期的电影里面用到的俚语等等，这些历史性的俚语只有green dictionary of slang这本词典才能兼顾到。

比如？我目前还没有看到确切的例子。

**Comment by funnybones2015** [comment]
> > 就我自己多年英语查词、学习和翻译经验来说，我觉得词典就需要权威点的
> 
> 你的观点没有问题，但前面我也说明了，维护一个词典涉及到更多因素。沙拉查词在布局时考虑的是如何用更少的词典涵盖更多角度，权威的词典沙拉查词不少，Urban Dictionary 作为一个权威的对立面，可以很好地形成互补。
> 
> > urban dictionary查找词义太过费时，很多垃圾信息，其实很影响体验。
> 
> 每个东西都有侧重点，Urban Dictionary 的亮点是对新潮俚语的解释，这本身就很难或者来不及成为权威。对于成熟的俚语其它词典一般都已经收录。
> 
> > 您多查一些词就明白了，很多都是网友杜撰，废话连篇，甚至很多错误。
> 
> 有错误我也是同意的。但这个很少会影响到查词结果，首先 Urban Dictionary 有投票机制，这个已经过滤掉大部分劣质的解释。剩下偶尔会出现抖机灵，一般不影响观感。我自己日常生活大部分时间是使用英语，所以 Urban Dictionary 是我重度使用的词典之一，目前还是很满意的。
> 
> > 而且重要的是在读一些文学小说、电影里用到的俚语，比如二战时期的电影里面用到的俚语等等，这些历史性的俚语只有green dictionary of slang这本词典才能兼顾到。
> 
> 比如？我目前还没有看到确切的例子。

以前遇到过，一时没想起来。那就拿上面这个dumb做举例吧，urban dictionary还是普通的stupid 等词义，而没有greenn dictionary中 dull 和 unattractive 这两个解释。这个dumb作为stupid的解释已经不是俚语，而是日常普通义项，green dictionary没收也正常。但那两个解释却是其他词典难查到的。

再比如随便想到 bomb 这个词，Urban Dictionary 上的解释总共有7个，其中有些还是重复的，第 2 个Bomb的解释，居然把“不能在飞机上说的话”还作为一条解释，更多是幽默闲侃性质，而非解释。再看看 green dictionary 上，仅作为名词的解释就有14个，其中还有很多子义项，加起来二三十条。这些还按年代和地区配有大量丰富的例句作为佐证。

**Comment by crimx** [comment]
> 那就拿上面这个dumb做举例吧，urban dictionary还是普通的stupid 等词义，而没有greenn dictionary中 dull 和 unattractive 这两个解释。这个dumb作为stupid的解释已经不是俚语，而是日常普通义项，green dictionary没收也正常。但那两个解释却是其他词典难查到的。

这个不是么？要看具体上下文。

![image](https://user-images.githubusercontent.com/6882794/81491295-73f3fc80-92bf-11ea-8cb9-81d269c6ad1b.png)

> 比如随便想到 bomb 这个词，Urban Dictionary 上的解释总共有7个，其中有些还是重复的，第 2 个Bomb的解释，居然把“不能在飞机上说的话”还作为一条解释，更多是幽默闲侃性质，而非解释。再看看 green dictionary 上，仅作为名词的解释就有14个，其中还有很多子义项，加起来总共有二三十条之多。这些还按年代和地区配有大量丰富的例句作为佐证（点击年份右侧的图标即可展开例句）。

查词的目的是解决问题，在具体上下文中找到需要的解释即可，不应该以数目对比。前面说过 Urban Dictionary 是作为互补来丰富角度，沙拉查词的设计是融合各个词典的优点来抹平各自的弱项。换句话说，在什么上下文中你认为 bomb 没有得到正确的解释？

**Comment by funnybones2015** [comment]
> > 那就拿上面这个dumb做举例吧，urban dictionary还是普通的stupid 等词义，而没有greenn dictionary中 dull 和 unattractive 这两个解释。这个dumb作为stupid的解释已经不是俚语，而是日常普通义项，green dictionary没收也正常。但那两个解释却是其他词典难查到的。
> 
> 这个不是么？要看具体上下文。
> 
> ![image](https://user-images.githubusercontent.com/6882794/81491295-73f3fc80-92bf-11ea-8cb9-81d269c6ad1b.png)
> 
我是说green dictionary中dumb的这两个解释在urban上没有：

![image](https://user-images.githubusercontent.com/15063728/81491390-c41f8e80-92c0-11ea-83f8-6920a281c39e.png)

**Comment by funnybones2015** [comment]
> > 那就拿上面这个dumb做举例吧，urban dictionary还是普通的stupid 等词义，而没有greenn dictionary中 dull 和 unattractive 这两个解释。这个dumb作为stupid的解释已经不是俚语，而是日常普通义项，green dictionary没收也正常。但那两个解释却是其他词典难查到的。
> 
> 这个不是么？要看具体上下文。
> 
> ![image](https://user-images.githubusercontent.com/6882794/81491295-73f3fc80-92bf-11ea-8cb9-81d269c6ad1b.png)
> 
> > 比如随便想到 bomb 这个词，Urban Dictionary 上的解释总共有7个，其中有些还是重复的，第 2 个Bomb的解释，居然把“不能在飞机上说的话”还作为一条解释，更多是幽默闲侃性质，而非解释。再看看 green dictionary 上，仅作为名词的解释就有14个，其中还有很多子义项，加起来总共有二三十条之多。这些还按年代和地区配有大量丰富的例句作为佐证（点击年份右侧的图标即可展开例句）。
> 
> 查词的目的是解决问题，在具体上下文中找到需要的解释即可，不应该以数目对比。前面说过 Urban Dictionary 是作为互补来丰富角度，沙拉查词的设计是融合各个词典的优点来抹平各自的弱项。换句话说，在什么上下文中你认为 bomb 没有得到正确的解释？

高质量的义项数量至少能很大程度上反映查得率问题，既然您不想拿数量来比较，那我也没办法，下次遇到具体上下文了，我贴图给您。Urban 的开放视角是不错，但是过于开放鱼龙混杂，缺乏条理性，还不如English Wiktionary 这种开放而不失条理性的自由词典。既然现有的俚语缺乏一种权威词典来压阵，何不拿urban和green作为互补，权威视角和自由视角的互补。我相信没有一本词典是完全不重复又互补的把？比如内置的那个柯林斯高阶词典，论词汇词义丰富性和词典功能现在远不及Oxford Advanced Dictionary和朗文等词典，他的唯一原创性可能是最早采用句子解说释义，但缺点是对于解释有些词汇而言太过罗嗦。但现在各大学习型词典已经把句子释义和一般释义风格两者结合了，其优势已不明显，其他词典几乎可以完全替代之。

**Comment by crimx** [comment]
> 还不如English Wiktionary 这种开放而不失条理性的自由词典

Wiktionary 已在计划中，见 #345 。

> 我相信没有一本词典是完全不重复又互补的把？比如内置的那个柯林斯高阶词典，论词汇词义丰富性和词典功能现在远不及Oxford Advanced Dictionary和朗文等词典，他的唯一原创性可能是最早采用句子解说释义，但缺点是对于解释有些词汇而言太过罗嗦。而且现在各大学习型词典已经把句子释义和一般释义风格两者结合了，其优势已不明显，其他词典几乎可以完全替代之。

我再总结一下，我前面表达的是完美理想状态与现实可行性的问题。我认同了你对 Green 权威性的描述，我也不否认它在部分领域比 Urban 要优秀，但它与现有的 Urban 在大部分功能上是雷同的。任何一个产品都会有其历史包袱，特别是个人项目。你也许注意到沙拉查词已经有部分功能重复的词典，这也是我现在要克制避免的问题。我必须考虑在我时间有限的情况下如何维持项目发展，无止境追求完美很容易失去控制。对于俚语我指出了在权威性上做折中是可以接受的，Green 加进来更多是锦上添花的作用，大部分情况下缺失了不会导致无法解决的问题。

我建议你可以把这个词典添加到沙拉查词的右键菜单，在沙拉查词查不到的情况下跳转到 Green 网页查看结果。

**Comment by funnybones2015** [comment]
> > 还不如English Wiktionary 这种开放而不失条理性的自由词典
> 
> Wiktionary 已在计划中，见 #345 。
> 
> > 我相信没有一本词典是完全不重复又互补的把？比如内置的那个柯林斯高阶词典，论词汇词义丰富性和词典功能现在远不及Oxford Advanced Dictionary和朗文等词典，他的唯一原创性可能是最早采用句子解说释义，但缺点是对于解释有些词汇而言太过罗嗦。而且现在各大学习型词典已经把句子释义和一般释义风格两者结合了，其优势已不明显，其他词典几乎可以完全替代之。
> 
> 我再总结一下，我前面表达的是完美理想状态与现实可行性的问题。我认同了你对 Green 权威性的描述，我也不否认它在部分领域比 Urban 要优秀，但它与现有的 Urban 在大部分功能上是雷同的。任何一个产品都会有其历史包袱，特别是个人项目。你也许注意到沙拉查词已经有部分功能重复的词典，这也是我现在要克制避免的问题。我必须考虑在我时间有限的情况下如何维持项目发展，无止境追求完美很容易失去控制。对于俚语我指出了在权威性上做折中是可以接受的，Green 加进来更多是锦上添花的作用，大部分情况下缺失了不会导致无法解决的问题。
> 
> 我建议你可以把这个词典添加到沙拉查词的右键菜单，在沙拉查词查不到的情况下跳转到 Green 网页查看结果。

ok，谢谢回复，我试下添加到右键菜单吧。词典维护不易，感谢持续维护！！

**Comment by crimx** [comment]
感谢理解。

**Comment by funnybones2015** [comment]
再次请求添加该词典，这本的解释和例句都是比较权威全面的！！
