### ISSUE TITLE
pdf模式翻译可能会挡到原文

### ISSUE THREAD

**Issue by Zmcmc123** [crimx/ext-saladict#794]
## 设备信息
- 操作系统: [macOS 10.15.4] 
- 浏览器版本: [Chrome 84.0.4136.7（正式版本）dev （64 位）] 
- 沙拉查词版本: [7.11.2] 

## 请描述目前使用沙拉查词遇到什么不便

如果阅读的pdf不是分栏的，只有将pdf缩小，才能将翻译窗口固定在pdf旁边，不影响pdf的阅读。如果pdf是分栏的，需要把翻译窗口固定在另一栏，阅读完另一栏之后，又要重新调整翻译窗口的位置，感觉有一些不方便。其实pdf是分栏的还好，挪个位置也不是很费力，但是对不分栏的pdf很不友好，希望可以改进。

## 理想情况下，沙拉查词应该怎么做

希望可以调整翻译窗口的大小，或者pdf可以不居中，可以调节pdf偏左或偏右。

**Comment by hqyyqh** [comment]
## 第一种 导航栏占位
![ ](https://user-images.githubusercontent.com/38676455/81494919-035cd800-92df-11ea-9066-0435738a1c12.gif)

## 第二种 独立窗口
![ ](https://user-images.githubusercontent.com/38676455/81494927-12dc2100-92df-11ea-9d93-3e8ef15e1e18.gif)

**Comment by Zmcmc123** [comment]
> ## 第一种 导航栏占位
> ![ ](https://user-images.githubusercontent.com/38676455/81494919-035cd800-92df-11ea-9066-0435738a1c12.gif)
> 
> ## 第二种 独立窗口
> ![ ](https://user-images.githubusercontent.com/38676455/81494927-12dc2100-92df-11ea-9d93-3e8ef15e1e18.gif)

第二种独立窗口是怎么弄的，动图没有看清。

**Comment by hqyyqh** [comment]
设置快捷键打开独立面板，可以针对独立面板设置直接划词搜索，
![image](https://user-images.githubusercontent.com/38676455/81495406-bed33b80-92e2-11ea-9354-b815f8b1b746.png)

**Comment by crimx** [comment]
导航栏占位 这个真没想到，思路新奇。Orz

**Comment by Zmcmc123** [comment]
> 设置快捷键打开独立面板，可以针对独立面板设置直接划词搜索，
> ![image](https://user-images.githubusercontent.com/38676455/81495406-bed33b80-92e2-11ea-9354-b815f8b1b746.png)

谢谢，这样看文献就方便多了。
