### ISSUE TITLE
麦克米伦Macmillan词典是不是失效了？

### ISSUE THREAD

**Issue by funnybones2015** [crimx/ext-saladict#795]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 描述问题

查询任何单词，麦克米伦词典都不显示结果，强行展开也不行。一开始以为是网络不畅导致加载太慢，但试了好多次都不行。打开麦克米伦官网是没问题的。

**Comment by crimx** [comment]
是的，已经在修复中。
