### ISSUE TITLE
建议pdf阅读器中增加阅读模式，或者叫便签模式

### ISSUE THREAD

**Issue by xsrolau-liu** [crimx/ext-saladict#797]
## 设备信息
- 操作系统: [Window10]
- 浏览器版本: [QQ浏览器10.5.3 Beta (4083)Chromium70.0.3538.25 \ IE11.7 78.1 8362.0] 
- 沙拉查词版本: [7.10.4]

## 请描述目前使用沙拉查词遇到什么不便

在使用pdf工具的时候
![image](https://user-images.githubusercontent.com/64292434/81679078-92efbb80-9484-11ea-9397-f4808c51dcbc.png)
这样使用的时候视野受到了很大限制，希望能够增加读取模式（或者叫便签模式）
## 理想情况下，沙拉查词应该怎么做

增加一个模式，启动一个独立窗口只显示pdf和pdf相关功能
- 一个可以缩小的全屏模式
- 或者说一个隐藏了标签栏书签栏等部分的正常窗口

## 额外信息
类似这样：
![image](https://user-images.githubusercontent.com/64292434/81678626-4e642000-9484-11ea-9d34-9a4963dff247.png)

![image](https://user-images.githubusercontent.com/64292434/81678893-75baed00-9484-11ea-87ea-d16ca5ff8e20.png)

**Comment by crimx** [comment]
https://saladict.crimx.com/manual.html#triple-ctrl

**Comment by xsrolau-liu** [comment]
> https://saladict.crimx.com/manual.html#triple-ctrl

thanks very much
独立窗口查词很方便，是否可以给pdf阅读器也增加一个独立窗口

**Comment by crimx** [comment]
哦，明白你意思了，可以。
