### ISSUE TITLE
段落翻译中除了机器翻译其他都不可用

### ISSUE THREAD

**Issue by zyf265600** [crimx/ext-saladict#798]
段落翻译中除了机器翻译其他都不可用
![批注 2020-05-12 214846](https://user-images.githubusercontent.com/59152151/81762358-72326080-949a-11ea-9d2e-e6e896d9e843.jpg)

**Comment by crimx** [comment]
请阅读[使用说明](https://saladict.crimx.com/manual.html)了解情境模式以及如何打开各个词典设置。

**Comment by zyf265600** [comment]
之前使用一直没问题，突然就这样了，设置里字典也都选定了。

CRIMX <notifications@github.com>于2020年5月12日 周二21:51写道：

**Comment by crimx** [comment]
请问你有在网上导入过其他人的设置么？

请提供截图，设置中的词典列表，以及没有按预期显示的词典的具体设置。
