### ISSUE TITLE
one bug

### ISSUE THREAD

**Issue by zyf265600** [crimx/ext-saladict#799]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 描述问题

词典默认模式下，原本划句整句翻译或整段翻译有谷歌有道等词典，现在只有机器翻译一个框，设置已更改，已重启，均未解决问题。
![批注 2020-05-12 214846](https://user-images.githubusercontent.com/59152151/81763566-89268200-949d-11ea-9fc4-68d708b7283f.jpg)

**Comment by crimx** [comment]
请提供设置中词典列表的截图，检查有无谷歌翻译。

以及提供谷歌翻译或有道翻译词典的设置截图。

把图片拖到评论框即可自动上传。。

**Comment by crimx** [comment]
同时编辑一楼，把系统，浏览器，和沙拉查词信息补上。

**Comment by zyf265600** [comment]
![image](https://user-images.githubusercontent.com/59152151/81764010-8ed09780-949e-11ea-8c39-d53e69c9b800.png)
操作系统: [windows 10 home]
浏览器版本: [Google Chrome 已是最新版本 版本 81.0.4044.138（正式版本） （64 位）]
沙拉查词版本: [Version 7.11.2]
谷歌翻译或有道翻译词典的设置在哪里找？
不好意思 麻烦您了

**Comment by crimx** [comment]
没事，点击一下词典名字旁边的铅笔图标。

另外你现在是翻译模式，里面根本没有有道词典，但一楼提供的查词结果却是在默认模式？

为了避免误解建议你点击设置右下角的圆圈按钮实时预览设置效果。

**Comment by crimx** [comment]
如果不理解情境模式建议阅读[使用说明](https://saladict.crimx.com/manual.html)。

**Comment by zyf265600** [comment]
您好 可能是因为刚刚更新了chrome浏览器 设置变化了，我重新设置了字典，问题已解决。

感谢您的这一款软件，我在国外留学已一年有余，您的这款软件对我帮助良多，现在也正在学习Java，将来想成为一名computer engineer，像您一样设计出优秀的软件。再次感谢，祝好。

**Comment by crimx** [comment]
解决了就好，加油⛽
