### ISSUE TITLE
推荐一个国内沙拉查词镜像，兼容所有Chromium内核浏览器

### ISSUE THREAD

**Issue by frankroad** [crimx/ext-saladict#800]
[https://pictureknow.com/extension?id=a2b1e68968824af48d70f90471f4bcca](https://pictureknow.com/extension?id=a2b1e68968824af48d70f90471f4bcca)

**Comment by crimx** [comment]
感谢推荐，与[谷歌商店打包](https://72k.us/dir788/24782725-37758132-dc15d5)的对比 checksums 确认一致，已添加到 [releases](https://github.com/crimx/ext-saladict/releases) 中。
