### ISSUE TITLE
PDF字体异常

### ISSUE THREAD

**Issue by Xavier01** [crimx/ext-saladict#801]
Firefox中在线/本地的PDF文件在沙拉查词中打开之后，文件字体会显示异常，经排除不是浏览器的问题，是插件的问题。

**Comment by crimx** [comment]
你好，“字体异常”是如何异常。请完整填写模板，如能提供截图更佳。

**Comment by Xavier01** [comment]
在线或者本地的PDF文件只要选择用沙拉查词的“Open in PDF Viewer” 打开，整个英文文献的字体就会和正常时候显示不一样，看起来特别难受。不选择在插件中浏览就没有任何问题。具体差异如下：

![在线加载的正常字体](https://user-images.githubusercontent.com/43513092/82136140-0145cc80-983d-11ea-8c4f-5e3f94476747.png)
![用沙拉词典打开的PDF显示的字体](https://user-images.githubusercontent.com/43513092/82136144-07d44400-983d-11ea-9729-1d2464386989.png)

**Comment by crimx** [comment]
嗯，你可以尝试用 PDF.js 的 [viewer](https://github.com/mozilla/pdf.js#online-demo) 打开看看，如出现同样问题请到 [PDF.js issues](https://github.com/mozilla/pdf.js/issues) 反馈，建议同时提供 PDF 文件供该团队测试。
