### ISSUE TITLE
技巧分享：沙拉划词配合youtube字幕划词

### ISSUE THREAD

**Issue by iamwwc** [crimx/ext-saladict#802]
#### 问题：

Youtube生成的字幕默认情况下不能选择，且每次点击字幕时，字幕会突然向上滚动

![you](https://user-images.githubusercontent.com/24750337/82004880-80e56700-9696-11ea-9a2b-7fca6830b2b6.gif)
### 解决
为了配合沙拉划词，我写了一个油猴脚本，将youtube字幕改为可选择，并且直接固定死字幕，点击时字幕不会突然向上滑动，避免了双击字幕时字幕滑动之后全屏了播放器

https://greasyfork.org/en/scripts/402598-youtube-entancer-of-mine/code

现在我将划词面板固定到右角，碰到字幕单词直接点击一下，面板就会自动翻译，十分方便

![image](https://user-images.githubusercontent.com/24750337/82004593-e127d900-9695-11ea-88a2-4d0c13996adc.png)

感谢插件作者提供的生产力工具，同时感谢大家分享的各种技巧，以及对我这个程序员英语的帮助，这是我的一丁点贡献，感谢😁

**如果脚本有问题，直接在这个Issues下@我，greasyfork我很少用**

**Comment by crimx** [comment]
这看起来很赞👍感谢分享！

**Comment by james-xiao** [comment]
非常感谢！

**Comment by iamwwc** [comment]
@james-xiao 是你在https://greasyfork.org/提的反馈吗，我修复了，你可以再试试

**Comment by emily22333** [comment]
感谢分享

**Comment by middzwb** [comment]
感谢！
