### ISSUE TITLE
麦克米伦词典里的语言标签和解释挨在一起了，缺空格

### ISSUE THREAD

**Issue by funnybones2015** [crimx/ext-saladict#803]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 描述问题

如图，语言标签和解释挨在一起，缺空格。
![image](https://user-images.githubusercontent.com/15063728/82070031-c2adf600-9706-11ea-8eec-21d61a916411.png)

## 截图

![image](https://user-images.githubusercontent.com/15063728/82070050-c6da1380-9706-11ea-9d3e-ac85de86f355.png)

**Comment by crimx** [comment]
nice catch
