### ISSUE TITLE
跳到translate.google.cn根本沒法登陸Google賬號

### ISSUE THREAD

**Issue by zzzgit** [crimx/ext-saladict#806]
![image](https://user-images.githubusercontent.com/1060733/82130497-6d551000-97fe-11ea-8ec4-71e08ae416e8.png)

如圖，這樣會跳到translate.google.**cn**，這個域名下，沒法使用**保存到star**這個功能，因為沒法登陸Google賬號。應該使用translate.google.**com**才對。

**Comment by crimx** [comment]
设置-词典管理-谷歌翻译-编辑-.com优先。

**Comment by zzzgit** [comment]
okay

**Comment by crimx** [comment]
啊！才看到截图是指菜单。你在 Context Menus 设置中编辑谷歌翻译链接即可。

**Comment by zzzgit** [comment]
不是右鍵菜單哦，是點擊插件按鈕之後的行為

[image: image.png]

**Comment by crimx** [comment]
见设置下的说明，复用了同样的项目。

**Comment by zzzgit** [comment]
> 见设置下的说明，复用了同样的项目。

![image](https://user-images.githubusercontent.com/1060733/82464325-860c4100-9af0-11ea-8346-61d92065c283.png)


是的，現在問題解決了。
