### ISSUE TITLE
增加正则表达式查词方式

### ISSUE THREAD

**Issue by hhr114** [crimx/ext-saladict#807]
## 设备信息
- 操作系统: [Window1] 
- 浏览器版本: [Edge81.0.416.72 ] 
- 沙拉查词版本: [v7.12.0] 

## 理想情况下，沙拉查词应该怎么做

建议增加用正则表达式查词的方案，比如查询第一个字母和最后一个字母是 s 的所有单词

**Comment by crimx** [comment]
有支持正则表达式查询的词典么

**Comment by hhr114** [comment]
> 有支持正则表达式查询的词典么

有好些不出名的小词典支持类正则查询，比如这个 https://www.nestattacked.com/2017/08/15/regdict/ ，也有对应源码，不知道实现起来如何

**Comment by crimx** [comment]
我看了一下项目的词库词汇量有限，而且需要维护服务器目前没有计划提供。

**Comment by hhr114** [comment]
> 我看了一下项目的词库词汇量有限，而且需要维护服务器目前没有计划提供。

好的，谢谢
