### ISSUE TITLE
长文翻译功能在新版本无法实现了

### ISSUE THREAD

**Issue by Lyon-Zhou** [crimx/ext-saladict#808]
之前的版本可以复制一大段文字进行翻译的，目前的版本不行了

**Comment by crimx** [comment]
![image](https://user-images.githubusercontent.com/6882794/82195046-58759b00-992a-11ea-8ae5-e574a0d8f499.png)

请完整填写反馈模板以便他人理解、定位问题。

**Comment by Bollie15** [comment]
我的也不行，现在长文翻译模式只有一个机器翻译，并且很多时候会出现这个有道翻译没有结果，然后我的情况是更新Chrome到最新版本后出现的情况。

Chrome:Version 81.0.4044.138 (Official Build) (64-bit)
沙拉查词:最新版
windows10

词典设置如下：
![image](https://user-images.githubusercontent.com/56813612/82729882-fbb12080-9d2d-11ea-9a03-2e91fd000ad5.png)
这是在使用长文翻译模式的结果：
![image](https://user-images.githubusercontent.com/56813612/82729894-1b484900-9d2e-11ea-8261-5f5282bb3244.png)
这是使用单个单词翻译结果：
![image](https://user-images.githubusercontent.com/56813612/82729900-2ef3af80-9d2e-11ea-97e7-cb043725696e.png)
因此问题就是 长文翻译 无法获取多个翻译结果，如 Google翻译等，一个翻译对比性不太好，希望开发者了解下这个情况，谢谢

**Comment by crimx** [comment]
@Bollie15 有没有在新谷歌账号上安装或者重置过设置？目前对于新用户默认模式下的机器翻译默认都没有添加，需要用户自行在设置中添加，从而提醒用户注册相应账号。老用户的设置会保留的，你的词典列表没截全没看到，没有的话自行添加设置一下。

**Comment by Bollie15** [comment]
> @Bollie15 有没有在新谷歌账号上安装或者重置过设置？目前对于新用户默认模式下的机器翻译默认都没有添加，需要用户自行在设置中添加，从而提醒用户注册相应账号。老用户的设置会保留的，你的词典列表没截全没看到，没有的话自行添加设置一下。

ok，你说对了，感谢，确实需要重新添加设置，感谢。现在可以了

![image](https://user-images.githubusercontent.com/56813612/82730280-11741500-9d31-11ea-9cff-4daf81c077ec.png)
