### ISSUE TITLE
本地PDF加载到火狐浏览器中不能出现在网页中的弹窗翻译

### ISSUE THREAD

**Issue by sxwater** [crimx/ext-saladict#810]
本地PDF加载到火狐浏览器中不能出现在网页中的弹窗翻译，只能选择文本右键选择“沙拉翻译”→“谷歌翻译”→跳转到另一个网页“谷歌翻译”出现翻译结果，这样子太麻烦了，估计不是沙拉插件的正常操作，顾寻求帮助解决此问题。

**Comment by crimx** [comment]
火狐的问题，目前除了换 Chrome 没有办法解决。

**Comment by sxwater** [comment]
> 火狐的问题，目前除了换 Chrome 没有办法解决。

只能换浏览器么？

**Comment by crimx** [comment]
你也可以右键地址栏旁的沙拉图标打开PDF阅读器，然后通过阅读器里的打开按钮加载本地 PDF。

**Comment by sxwater** [comment]
> 你也可以右键地址栏旁的沙拉图标打开PDF阅读器，然后通过阅读器里的打开按钮加载本地 PDF。

好的，谢谢🤝

**Comment by crimx** [comment]
你也可以收藏阅读器的地址（删掉后面的参数），可以直接打开。
