### ISSUE TITLE
建议增加_独立窗口是否记忆上次关闭时的大小_选项

### ISSUE THREAD

**Issue by Nelson0491** [crimx/ext-saladict#812]
## 设备信息
- 操作系统: [Window10 1909 18363.836] 
- 浏览器版本: [Chrome 81.0.4044.138] 
- 沙拉查词版本: [v7.12.1] 

## 请描述目前使用沙拉查词遇到什么不便

我在 issues 中看到类似的问题，似乎和我相反……我不是很懂他/她想表达什么。

下面是我的建议：
关闭最大化的独立窗口后，下一次打开就显示的是“接近于最大化”的窗口

![image](https://user-images.githubusercontent.com/59787059/82219288-a3ee7000-994f-11ea-86b4-9655dc9e3a5e.png)

## 理想情况下，沙拉查词应该怎么做

但大多数时候我想打开独立窗口时显示一个类似于侧边栏的窗口，（**不是类侧边栏**），如图：

![image](https://user-images.githubusercontent.com/59787059/82220527-56730280-9951-11ea-87b9-2587bfeab89b.png)

## 替代方案

建议增加“独立窗口是否记忆上次关闭时的大小”选项

## 额外信息

这是相关配置截图：

![image](https://user-images.githubusercontent.com/59787059/82220625-75719480-9951-11ea-8d7b-120bfd89b14c.png)

![image](https://user-images.githubusercontent.com/59787059/82220777-a94cba00-9951-11ea-95c7-7339698569e8.png)

**Comment by crimx** [comment]
感谢反馈，你的建议非常不错！
