### ISSUE TITLE
新版edge无法安装，显示“download was not a valid extension or user script”

### ISSUE THREAD

**Issue by cch95813** [crimx/ext-saladict#813]
## 设备信息
- 操作系统: [] Window10
- 浏览器版本: [] edge
- 沙拉查词版本: [] v7.12.0

## 描述问题

新版edge无法安装，显示“download was not a valid extension or user script”

**Comment by crimx** [comment]
我咨询了 Edge 维护者 @rumosky 反馈是可以正常安装的，请检查你的网络在下载过程中是否中断了。可以尝试重启以及清空缓存。

**Comment by cch95813** [comment]
非常感谢！应该是edge的问题！辛苦了，沙拉非常好用，已经离不开了。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CRIMX <notifications@github.com&gt;
发送时间: 2020年5月19日 18:04
收件人: crimx/ext-saladict <ext-saladict@noreply.github.com&gt;
抄送: cch95813 <932101868@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[crimx/ext-saladict] 新版edge无法安装，显示“download was not a valid extension or user script” (#813)





 
我咨询了 Edge 维护者 @rumosky 反馈是可以正常安装的，请检查你的网络在下载过程中是否中断了。可以尝试重启以及清空缓存。
