### ISSUE TITLE
我不大会用Quicker与沙拉查词的结合以进行浏览器外翻译

### ISSUE THREAD

**Issue by zxy1555847** [crimx/ext-saladict#814]
## 设备信息
- 操作系统: Window10
- 浏览器版本: Microsoft Edge 是最新版本。
                      版本 81.0.416.77 (官方内部版本) (64 位)
- 沙拉查词版本: v7.12.0（在扩展管理页面查看）

## 描述问题

我意图将QUicker与沙拉结合进行浏览器外的翻译，跟着介绍页上B站的教程走的。快捷键是可以呼出沙拉的，但是不能呼出QUicker的设置，也不能复制即翻译。用起来很麻烦，只能先复制后在快捷键翻译。而且，我的QUicker的沙拉的“文本截图翻译”动作也不能启用

## 期待的正常行为

我希望在浏览器外，开着浏览器也可以，实现就像在浏览器中的，划词然后点击沙拉图标就可以出现翻译结果的效果。我隐隐觉得，是我Quicker哪里出错了，但我解决不了

**Comment by hqyyqh** [comment]
> 不能呼出 QUicker 的设置

按下 Ctrl，同时点击动作，就可以直接进入动作设置

> 我的 QUicker 的沙拉的 “文本截图翻译” 动作也不能启用

无法启用具体是？选中文本可以正常翻译吗；截图可以正常识别并且翻译吗？
