### ISSUE TITLE
能否设置成划词/选词后按快捷键（ALT/CTRL）触发查词

### ISSUE THREAD

**Issue by das046** [crimx/ext-saladict#815]
## 设备信息
- 操作系统: [Windows7] 
- 浏览器版本: [Chrome81] 
- 沙拉查词版本: [7.12.1] 

## 请描述目前使用沙拉查词遇到什么不便

请问可以可以把沙拉查词设置成选词后按键触发，现在在选词后会出现沙拉查词的图标，然后点击图标触发查词。这个大部分情况下很方便，不过有时候选词是为了复制，或者有时候图标会遮挡附近的文字。现在设置里面可以改成选词后松开鼠标前按键触发，但这个机制不适用与双击选词，会有一些不便。

## 理想情况下，沙拉查词应该怎么做

期待能够增加一种查词习惯，也就是选词（双击或者划词）之后不出现图标，但可以按键（CTRL，SHIFT，ALT，META）触发查词。
谢谢！

**Comment by crimx** [comment]
> 现在设置里面可以改成选词后松开鼠标前按键触发，但这个机制不适用与双击选词

为什么说不适用呢。请提供详细复现步骤。

> 期待能够增加一种查词习惯，也就是选词（双击或者划词）之后不出现图标，但可以按键（CTRL，SHIFT，ALT，META）触发查词。

见「快捷键」与「快捷查词」。[使用说明](https://saladict.crimx.com/manual.html)。

**Comment by das046** [comment]
感谢回复。
我之前叙述的问题，选词后在松开鼠标前按键触发是可以的，我又尝试了，双击也可以。我只是觉得这个触发机制不习惯的时候用起来有点别扭。因为大部分时候双击一个单词不会按住不放。所以想问一下，如果不是很复杂的话能不能添加我描述的那种触发机制。或者如果已经有这个功能，要怎么启用。我在使用说明里面并没有找到。
再说清楚一点，就是使用快捷键查选中的单词或者句子，可以在选中之后按键，而不需要选中后鼠标键不松开同时按键。

Anyway, not a big deal. 如果麻烦就不用了。

谢谢

**Comment by das046** [comment]
Thanks for replying. 

我重新尝试了一下，明白“按住 Ctrl/⌘”查词模式的用法了。是可以先按住按键在选词的，我之前理解成了要在选词后松开鼠标前按键才行，搞错了。

谢谢！

**Comment by crimx** [comment]
是的，只要鼠标放开前相应按键是按下的即可。
