### ISSUE TITLE
沙拉独立查词窗口弹出优化请求

### ISSUE THREAD

**Issue by aaronthewierdo** [crimx/ext-saladict#816]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Edge81.0.416.77] 
- 沙拉查词版本: [v7.1.2] 

## 请描述目前使用沙拉查词遇到什么不便

自从前一次升级后，每次用全局按键呼出沙拉独立查词窗口时，独立查词窗口和浏览器并列显示而不重叠显示，会挤压正在浏览页面，非常影响体验

## 理想情况下，沙拉查词应该怎么做

希望可以像以前用全局按键呼出沙拉独立查词窗口时，独立窗口会单独弹出，悬浮在浏览器上方

**Comment by crimx** [comment]
你把 设置-快捷查词-侧边栏模式 关一下。
