### ISSUE TITLE
词典显示以及交互方面的问题

### ISSUE THREAD

**Issue by xiajunwen1007** [crimx/ext-saladict#818]
## 设备信息
- 操作系统: [windows10] 
- 浏览器版本: [edge最新版 chromium81] 
- 沙拉查词版本: [v7.12.0] 

## 描述问题

科林斯高阶词典上方的选择按钮无法滚动，有时候突然不知道点到哪里就开始滚动了，有一些按钮点了之后不会有内容出现希望取消这些按钮，或者添加相应内容。lexico词典有时候会有两个元素叠加在一起的情况。

## 复现步骤

科林斯词典问题复现：
1.搜索单词way
2.滚动到科林斯词典所在位置
3.因为way这一词条上方可点击按钮很多，有些按钮会在显示范围以外，正常的逻辑为点击某个左滑或者右滑按钮来滚动显示内容，目前没有发现作者提供的交互逻辑
4.点击video pronunciation，idioms，collocation均无内容显示，在词典官网发现这些位置均是有内容的，其中idioms，collocation建议添加，video pronunciation建议删除按钮

lexico词典问题复现：
1.搜索单词hello
2.滚动到lexico词典所在位置
3.可以看到发音按钮那一部分和translate hello into spanish重合了，建议删去translate hello into spanish那一行的内容

## 期待的正常行为

科林斯词典：
添加左右滑动按钮，删去video pronunciation按钮，增加idioms和collocation部分内容

lexico词典：
删去translate ... into spanish一行内容

## 截图

科林斯词典：
![image](https://user-images.githubusercontent.com/49160447/82522785-0ec0c680-9b5d-11ea-993d-0c81abeefc87.png)
![image](https://user-images.githubusercontent.com/49160447/82522829-2a2bd180-9b5d-11ea-884d-be79eaf3b5dd.png)
![image](https://user-images.githubusercontent.com/49160447/82522843-357efd00-9b5d-11ea-94b4-0b4ee16f85c8.png)

lexico：
![image](https://user-images.githubusercontent.com/49160447/82522737-ecc74400-9b5c-11ea-8eb4-e1bbde0ee285.png)

## 额外信息

上述问题在很多单词上都会遇到，科林斯词典和lexico词典均是非常好用的词典，非常感谢作者把他们集成到了沙拉查词中，并对他们进行了美化，暗黑模式的适配。

**Comment by crimx** [comment]
感谢反馈。

1. 柯林斯词典的问题使用为没有为触摸屏进行支持，鼠标滚动可以正常查看。我考虑把它换成 select 不那么占用空间。沪江也可以同时优化一下。
2. 这个应该是 Lexico 最近加上去的，会在下个版本隐藏掉。

**Comment by xiajunwen1007** [comment]
非常感谢大大的回复，我使用的是触控板，暂时还没有使用过鼠标

**Comment by crimx** [comment]
触控版也是一样的，正常页面滚动操作即可。

**Comment by xiajunwen1007** [comment]
那可能是我设备的问题，我这里用触控板滚动有时候会滑动，有时候不会
