### ISSUE TITLE
桌面版沙拉查词-选中文本后弹出的图标和鼠标的距离大，不能紧随鼠标

### ISSUE THREAD

**Issue by Samuel579** [crimx/ext-saladict#819]
## 设备信息
- 操作系统: [Windows] 
- 沙拉查词版本: [v1.0.0] 

## 描述问题
-沙拉查词桌面版，选中文字后显示的图标总是和鼠标有一定的距离，调整设置里的数值后没有变化。

## 期待的正常行为

不知道是不是高分屏适配的原因，还是软件的bug，软件很喜欢，希望作者能够解决一下，不胜感激！！！

## 截图
![image](https://user-images.githubusercontent.com/60598976/82670793-63089b00-9c70-11ea-9a74-28b6b95226fd.png)

**Comment by crimx** [comment]
你好，沙拉查词没有桌面版，你是从什么地方下载的？

**Comment by xiajunwen1007** [comment]
https://github.com/zenghongtu/saladict-desktop 应该是这个，不过我没用过，之前无意间看到的

**Comment by crimx** [comment]
你好，这个项目为第三方修改，与沙拉查词无关。本仓库为沙拉查词唯一官方维护的仓库，官网为 https://saladict.crimx.com 。

**Comment by Samuel579** [comment]
> 本仓库为沙拉查词唯一官方维护的仓库，官网为https://saladict.crimx.com。你好，这个项目为第三方修改，与沙拉查词无关。
好的，谢谢作者，沙拉查词真的很好用，支持原作者！！

**Comment by crimx** [comment]
由于版权原因沙拉查词只会实现为浏览器辅助插件，你可以配合其他工具进行[浏览器外划词](https://saladict.crimx.com/native.html)。
