### ISSUE TITLE
在新版的Edge浏览器里只有机器翻译可以用

### ISSUE THREAD

**Issue by limingming1234** [crimx/ext-saladict#820]
## 设备信息
- 操作系统: Window10
- 浏览器版本: Microsoft Edge  83.0.478.37 (官方内部版本) (64 位)
- 沙拉查词版本: 7.12.1

## 描述问题
在新版的Edge浏览器里只有机器翻译可以用

**Comment by crimx** [comment]
很可能与 #818 重复。

**Comment by crimx** [comment]
打错了，是 #808

**Comment by limingming1234** [comment]
多谢！重新设置选择一下词典就好了。
