### ISSUE TITLE
Can't work well in Edge

### ISSUE THREAD

**Issue by wwwyeeting** [crimx/ext-saladict#823]
Dear CRIMX:

    Recently, I used Saladict in Edge, but it worked not well. I found the translation method only showed Youdao without Google or others. As a comparison， it showed the translation result by Google in Chrome,.

    I used Saladict in this website: https://docs.wxpython.org/wx.1moduleindex.html.

    My windows version is: Windows 10 Professional Edition 1909(64-Bit).

    Edge version is: 83.0.478.37(64-Bit).

Thanks.

**Comment by crimx** [comment]
Hi. Machine translators are no longer added by default. Please add it yourself in settings or login browser account to preserve settings.
