### ISSUE TITLE
有道词典部分单词柯林斯双解展示不全

### ISSUE THREAD

**Issue by NicholasRich** [crimx/ext-saladict#825]
例如make这个单词
![image](https://user-images.githubusercontent.com/35550787/83047892-9c2f7980-a07b-11ea-9329-b82bc00f35b5.png)

实际上只是查出了官方字典中第一个标签的展开内容，如下图所示，希望剩余标签的展开内容也能一并查出

![image](https://user-images.githubusercontent.com/35550787/83047822-802bd800-a07b-11ea-92e5-25a3bf0e1e3a.png)

![image](https://user-images.githubusercontent.com/35550787/83048576-62ab3e00-a07c-11ea-92bd-88424e2f9680.png)

**Comment by crimx** [comment]
感谢反馈。
