### ISSUE TITLE
建议增加牛津英英词典

### ISSUE THREAD

**Issue by Eastwood6** [crimx/ext-saladict#826]
## 词典名称以及链接
[《牛津英英词典》](https://www.oxfordlearnersdictionaries.com/)

## 沙拉查词的已有的词典为什么不能满足？

用了几乎所有词典，居然没有牛津版英英翻译
虽然和longMan类似都是英英，但:
1.翻译内容没有oxford言简意赅,清晰准确
2.我不知道为什么longman verb意思总在老后面,中间隔一大堆例子

## 截图

![image](https://user-images.githubusercontent.com/47491770/83104375-295de700-a0eb-11ea-845c-e9a5f1db1dd6.png)

**Comment by crimx** [comment]
Lexico 使用的是牛津词典。Macmillan 也不错。

**Comment by Eastwood6** [comment]
> Lexico 使用的是牛津词典
图片是牛津词典brush verb意思,和[这个词典](https://www.oxfordlearnersdictionaries.com/definition/american_english/brush_2)内容完全匹配
![image](https://user-images.githubusercontent.com/47491770/83107093-3204ec00-a0f0-11ea-9a26-34b165af6125.png)
但lexico内容不一致，Macmillan 80%一致

**Comment by crimx** [comment]
能得到正确的解释就行，与纸质一致这个要素不在添加词典考虑范围。

牛津学习词典之前是支持的，后来因页面改版就换成了 Lexico，学习型词典不再考虑添加，可在现有的词典里选择。
