### ISSUE TITLE
单词红心取消失败｜生词查询记录一直为空

### ISSUE THREAD

**Issue by JSDSG** [crimx/ext-saladict#829]
## 设备信息
- 操作系统: [MacOS] 
- 浏览器版本: [Chrome83.0.4103.61] 
- 沙拉查词版本: [v7.12.1] 

## 问题
1. 单词红心取消失败
2. 单词查询记录一直为空（已解决thx！）

## 复现步骤

针对单词红心取消失败的问题：
1.配合Alfred
2.单词同步到扇贝
3.真的是任意页面，任意单词（没调用Alfred时也会出现同样问题）
## 截图

![image](https://user-images.githubusercontent.com/66070604/83327628-d5e8c600-a2af-11ea-9d11-d54f9d6cd248.png)

**Comment by crimx** [comment]
单词保存在「生词本」，你打开的是「查词记录」。

开启查词记录可以在设置中开启。

**Comment by crimx** [comment]
看来沙拉查词应该在未开启查词记录的时候隐藏这个选项。
