### ISSUE TITLE
词典设置内选择【添加】 会提示Entry Not Found

### ISSUE THREAD

**Issue by PRStarDust** [crimx/ext-saladict#830]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 截图

![image](https://user-images.githubusercontent.com/36158676/83342303-72e34780-a320-11ea-92f7-ce5b6ae1d078.png)

**Comment by crimx** [comment]
请重新编辑把缺少的信息补上。

**Comment by anrgct** [comment]
这个是移植版升级的问题，把utools——插件中心——账号与数据——沙拉查词——清空，就可以啦
