### ISSUE TITLE
沙拉查词在浏览器外按快捷键无法调出

### ISSUE THREAD

**Issue by loglmlm** [crimx/ext-saladict#831]
昨天按照教程一步一步设置好以后，并且使用成功。但是关机之后，今早重新启动电脑，打开浏览器，发现按快捷键之后无法在桌面上调出沙拉查词。后来换了一台电脑，同样按照教程设置以后，运行良好，但是关机重启以后，打开浏览器，按住快捷键，在桌面上无法调出沙拉查词。请问这是什么原因？

**Comment by crimx** [comment]
请重现编辑补充完整信息。

**Comment by crimx** [comment]
#832
