### ISSUE TITLE
edge浏览器之外按下快捷键无法调出沙拉查词

### ISSUE THREAD

**Issue by loglmlm** [crimx/ext-saladict#832]
## 设备信息
- 操作系统: [window10] 
- 浏览器版本: [Edge83.0.478.37] 
- 沙拉查词版本: [v7.12.1] 

## 描述问题

浏览器之外按下快捷键无法调出沙拉查词

## 复现步骤

1.昨天按照教程一步步设置成功，并且运行正常，但是关机以后，今早重新打开浏览器后，在桌面按住快捷键无法调出沙拉查词，
2.重新设置快捷键后可以运行，但是关机重启以后无法运行，需要将浏览器以及Quicker动作中的快捷键重新设置才能正常使用。

## 期待的正常行为

希望关机重启以后可以用之前的快捷键打开，而不是每次重启以后都需要重新设置快捷键才能使用。

**Comment by crimx** [comment]
Edge 由 @rumosky 维护，等他看看是什么问题。

对于“快捷键失效”你可以进一步排查：

1. 是否浏览器的问题。
   1. 打开浏览器快捷键管理，设置过的快捷键是否还在？
   2. 直接按下快捷键是否有反应？
   3. 更换其它快捷键能否解决这个问题。
2. 是否 Quicker 的 问题。
   按描述看可能性不大。但如果依然无法解决可以找到[教程](https://saladict.crimx.com/native.html)的帖子请教分享的作者。

**Comment by hqyyqh** [comment]
## 可能的解决办法
先复制一段文字，再按下快捷键。

## 原因
测试发现，【在独立窗口中搜索剪贴板内容】快捷键需要在**剪贴板中有文字**内容才可以正常呼出。
系统重启，剪贴板被清空，复制一段文字后，再触发快捷键就可以了。

**Comment by rumosky** [comment]
> ## 设备信息
> * 操作系统: [window10]
> * 浏览器版本: [Edge83.0.478.37]
> * 沙拉查词版本: [v7.12.1]
> 
> ## 描述问题
> 浏览器之外按下快捷键无法调出沙拉查词
> 
> ## 复现步骤
> 1.昨天按照教程一步步设置成功，并且运行正常，但是关机以后，今早重新打开浏览器后，在桌面按住快捷键无法调出沙拉查词，
> 2.重新设置快捷键后可以运行，但是关机重启以后无法运行，需要将浏览器以及Quicker动作中的快捷键重新设置才能正常使用。
> 
> ## 期待的正常行为
> 希望关机重启以后可以用之前的快捷键打开，而不是每次重启以后都需要重新设置快捷键才能使用。
> 
> ## 截图
> ## 额外信息

我刚刚测试过了，不是edge版插件的问题，原因就是你剪切板是空的，全局呼出独立窗口是剪切板要有内容才可以实现的。 @hqyyqh 感谢你的回复，解决办法就是这样的。

**Comment by crimx** [comment]
嗯，感谢回复。「在独立窗口中搜索剪贴板内容」与「打开独立词典窗口」这两个不同快捷键的作用貌似很多人分不清……需不需要增加点说明。

**Comment by crimx** [comment]
还是说无论如何都打开查词窗口。

**Comment by rumosky** [comment]
> 嗯，感谢回复。「在独立窗口中搜索剪贴板内容」与「打开独立词典窗口」这两个不同快捷键的作用貌似很多人分不清……需不需要增加点说明。

我觉得应该增加点说明，大部分人理解的全局快捷键应该是「打开独立词典窗口」，而且，一般人肯定在全局使用时候的需求就是「打开独立词典窗口」，然后自己在词典窗口里面输入内容进行查词翻译。

**Comment by hqyyqh** [comment]
> 还是说无论如何都打开查词窗口。

赞同，这样的话不会有快捷键设置出问题的错觉🤣

**Comment by rumosky** [comment]
> 还是说无论如何都打开查词窗口。

对，就是这个意思
