### ISSUE TITLE
无法自动添加到Anki

### ISSUE THREAD

**Issue by leeggco** [crimx/ext-saladict#833]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Chrome83] 
- 沙拉查词版本: [v7.13.0] 

## 描述问题

Anki 连接成功，能自动创建牌组，但是无法添加单词到Anki。

## 截图

![image](https://user-images.githubusercontent.com/1283227/83489477-06637680-a4e1-11ea-92ab-01cac7a32782.png)

**Comment by crimx** [comment]
提供一下单词

**Comment by leeggco** [comment]
> 提供一下单词

任意单词，都能成功

**Comment by crimx** [comment]
目前无法重现这个问题，只能等其他人看看有无反馈。

另外“任意单词”是如何测试的。

**Comment by leeggco** [comment]
> 目前无法重现这个问题，只能等其他人看看有无反馈。
> 
> 另外“任意单词”是如何测试的。

抱歉，说法有点不严谨，不过的确没能正常使用。
![1](https://user-images.githubusercontent.com/1283227/83491002-9aced880-a4e3-11ea-8ed9-44a1d1f0c0de.gif)

**Comment by crimx** [comment]
这有点奇怪了，我原来猜测是有部分单词的笔记解析有问题导致失败，但是按你图片演示的过程，自动生成的单词不应该有问题。如果是 Anki Connect 连接的问题，那么设置中检查成功又无法解释。

我按图片的方式同样无法复现这个问题。

**Comment by crimx** [comment]
你有试过老方式解决么，重启系统。

**Comment by crimx** [comment]
同时确认 Anki 中对应的 Saladict 牌组和 Saladict Word 笔记类型已存在。方便的话截图看看，笔记类型在 Notes 👉 Manage Note Types。

**Comment by leeggco** [comment]
我没有尝试过老方法，这个自动的期待很久了 ：D

如图：Saladict 牌组和 Saladict Word 笔记类型已存在

![image](https://user-images.githubusercontent.com/1283227/83492539-01ed8c80-a4e6-11ea-8c92-8c57d695ab24.png)

**Comment by crimx** [comment]
不能私自修改字段名字，可以阅读[教程](https://saladict.crimx.com/anki.html)。

**Comment by crimx** [comment]
如果想自定义卡片请不要更改这些名字，而是直接添加新的卡片类型。

**Comment by leeggco** [comment]
> 如果想自定义卡片请不要更改这些名字，而是直接添加新的卡片类型。

我并没有修改字段名字，可能是因为Anki国际化导致的。

我把字段改回来就行了！感谢！

**Comment by crimx** [comment]
啊！所以是自动生成就是这样的？如果是这样这会是一个兼容问题。

**Comment by leeggco** [comment]
> 啊！所以是自动生成就是这样的？如果是这样这会是一个兼容问题。

是自动生成就这样了，我没有修改过。

**Comment by crimx** [comment]
这有点坑……估计很多人会中招……我看看怎么解决

**Comment by crimx** [comment]
Note types 的 Cards 里的字段名也会被翻译吗？

**Comment by leeggco** [comment]
> Note types 的 Cards 里的字段名也会被翻译吗？

是指卡片类型里的模板吗？ 这里面字段的没有被翻译。
![image](https://user-images.githubusercontent.com/1283227/83495311-1895e280-a4ea-11ea-8b19-227ac7569bb1.png)

**Comment by zhiw2019** [comment]
同无法添加单词。本人环境：linux ,anki 2.1.26,google chrome 83.0.4103.61.

**Comment by crimx** [comment]
见上面方案，把字段改回英文。

**Comment by crimx** [comment]
给 Anki Connect 提了 [PR](https://github.com/FooSoft/anki-connect/pull/178)，看能不能合并吧。

**Comment by crimx** [comment]
v.7.13.1 已兼容多语言 Anki。

**Comment by Rye1st** [comment]
出现此问题+1，如果是自动生成一定会出现这个问题吧。必须重新将字段修改为英文。

**Comment by crimx** [comment]
@Rye1st 请提供版本，是 v.7.13.1 吗

**Comment by crimx** [comment]
> 如果是自动生成一定会出现这个问题吧

如果 Anki 是英文版的不会。这是由于 Anki Connect 这个插件在添加字段是自动翻译了名字，导致字段名出现变化。另外我昨天提交的 [PR](https://github.com/FooSoft/anki-connect/pull/178) 作者已经合并了，新的 Anki Connect 发布后就没有这个问题。

与此同时沙拉查词 v.7.13.1 也兼容了这种情况，现在即便字段被翻译了也能准确识别，同时用户也可以随意更改字段名，沙拉查词是以字段顺序来匹配。

**Comment by crimx** [comment]
Anki Connect 作者已更新。
