### ISSUE TITLE
mac系统更新至catalina后悬浮窗口消失

### ISSUE THREAD

**Issue by qqqqqqqq-c** [crimx/ext-saladict#834]
## 设备信息
- 操作系统: []  MAC OS Catalina 
- 浏览器版本: [] Google Chrome 版本 83.0.4103.61（正式版本
- 沙拉查词版本: []  7.13.1 

## 请描述目前使用沙拉查词遇到什么不便

开始安装沙拉查词时mac处于majova系统，“pdf reader”内使用快捷键查词，出现悬浮窗口
如图：

 
[Uploading WX20200603-225847.pdf…]()

更新系统至Catelina后，pdf内查词会跳出全屏独立窗口，即使在设置中关闭独立窗口也没有改变。

即使在chrome中使用快捷键查词，依然会跳转到全屏独立窗口

## 理想情况下，沙拉查词应该怎么做

期待还可以出现悬浮窗口 

## 替代方案

只能使用独立窗口与pdf 分屏

## 额外信息

[Uploading WX20200603-225847.pdf…]()
图片上传PNG和PDF模式都显示不支持文件类型，通过邮箱发送惹

**Comment by crimx** [comment]
你好，首先你的图片没上传完成，请点击一楼右上角三个点重新编辑。

> pdf内使用快捷键查词，出现悬浮窗口

这里的"pdf内"是指什么？是沙拉查词自带的 PDF 阅读器还是其它。“快捷键”是指什么按键组合？

> pdf内查词会跳出全屏独立窗口，即使在设置中关闭独立窗口也没有改变

请提供具体的复现步骤。

> 且独立窗口右上角也没有钉子选项，只有“查词时面板不获取焦点”

独立窗口是无法保持最前的，除非系统窗口管理器支持或者支持类似的插件。

**Comment by qqqqqqqq-c** [comment]
可以直接回复附件吗，网页上总是 上传不了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CRIMX"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月3日(星期三) 晚上10:50
收件人:&nbsp;"crimx/ext-saladict"<ext-saladict@noreply.github.com&gt;;
抄送:&nbsp;"Stubborn 🌸"<394711573@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [crimx/ext-saladict] mac系统更新至catalina后悬浮窗口消失 (#834)





 
你好，首先你的图片没上传完成，请点击一楼右上角三个点重新编辑。
  
pdf内使用快捷键查词，出现悬浮窗口
  
这里的"pdf内"是指什么？是沙拉查词自带的 PDF 阅读器还是其它。“快捷键”是指什么按键组合？
  
pdf内查词会跳出全屏独立窗口，即使在设置中关闭独立窗口也没有改变
  
请提供具体的复现步骤。
  
且独立窗口右上角也没有钉子选项，只有“查词时面板不获取焦点”
  
独立窗口是无法保持最前的，除非系统窗口管理器支持或者支持类似的插件。

**Comment by crimx** [comment]
https://hao.su/pic.html

**Comment by qqqqqqqq-c** [comment]
> https://hao.su/pic.html

上传了

**Comment by qqqqqqqq-c** [comment]
> https://hao.su/pic.html
快捷键是cmd+shift+d  关联了Alfred

**Comment by crimx** [comment]
上传了请把右键图片复制链接粘贴过来。


从你提供的快捷键信息打开独立窗口是正常现象，这正是这些教程的目的。打开浏览器内浮窗**只能在浏览器内使用**，且不需要设置这些快捷键。

**Comment by qqqqqqqq-c** [comment]
> 发布了请把快捷图片复制链接粘贴过来。
> 
> 从您提供的快捷键信息打开独立窗口是正常现象，这正是这些教程的目的。打开浏览器内浮窗**只能在浏览器内部使用**，并且不需要设置这些快捷键。

我又在 设置中点击了打开独立窗口。。悬浮窗口就回来了，不好意思打扰了
