### ISSUE TITLE
建议在Macmillan 词典加入美式发音

### ISSUE THREAD

**Issue by LEGENDMOUSE** [crimx/ext-saladict#837]
现在在macmillan词典查词，点发音，只是英式发音，建议在macmillan词典中加入美式发音。
      我注意到macmillan词典官网最底下有英国，美国国旗，点哪一个就就将显示为相应国家版本的发音的词典，所以词典本身是支持美式发音的。
反馈前请确保已阅读
反馈前请确保已阅读
反馈前请确保已阅读

- 使用说明： https://saladict.crimx.com/manual.html
- 常见问题以及答复： https://saladict.crimx.com/q&a.html
- 请先在 issues 页面搜索你的问题，很可能已被解决。

请*完整*填写模板描述问题，以便别人理解、定位和解决问题。
请*完整*填写模板描述问题，以便别人理解、定位和解决问题。
请*完整*填写模板描述问题，以便别人理解、定位和解决问题。
请*完整*填写模板描述问题，以便别人理解、定位和解决问题。
请*完整*填写模板描述问题，以便别人理解、定位和解决问题。
请*完整*填写模板描述问题，以便别人理解、定位和解决问题。
请*完整*填写模板描述问题，以便别人理解、定位和解决问题。
请*完整*填写模板描述问题，以便别人理解、定位和解决问题。
请*完整*填写模板描述问题，以便别人理解、定位和解决问题。
请*完整*填写模板描述问题，以便别人理解、定位和解决问题。
-->

## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: []

**Comment by crimx** [comment]
在Macmillan词典[设置](https://saladict.crimx.com/manual.html)中选择美式词典。

**Comment by LEGENDMOUSE** [comment]
> 在Macmillan词典[设置](https://saladict.crimx.com/manual.html)中选择美式词典。
我选了，还是英式发音

**Comment by crimx** [comment]
bug 已确认，感谢反馈。
