### ISSUE TITLE
在独立窗口中搜索剪贴板内容 功能的窗口位置

### ISSUE THREAD

**Issue by linsui** [crimx/ext-saladict#838]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Firefox 76] 
- 沙拉查词版本: [7.13.2] 

## 描述问题

通过快捷键在独立窗口中搜索剪贴板内容时，窗口会出现在左上角，大部分在屏幕之外。

## 复现步骤

通过快捷键在独立窗口中搜索剪贴板内容。按下快捷键后窗口会出现在左上角。快捷查词->独立窗口设置似乎是有关的。关闭记住位置与大小时会出现上述行为，无论何时按下快捷键，窗口都会出现在左上角且大部分在屏幕外。启用记住位置与大小时，窗口会在关闭之前记住位置大小，关闭独立窗口后，会出现在左上角，但全部在屏幕内。

## 期待的正常行为

关闭记住位置与大小时，独立窗口出现在屏幕内，启用记住位置与大小时，窗口记住位置大小。

## 截图

关闭记住位置与大小
![sshot-004](https://user-images.githubusercontent.com/36977733/83849838-8e26cc00-a6ff-11ea-8c42-102933ccec51.png)

启用记住位置与大小
![sshot-003](https://user-images.githubusercontent.com/36977733/83849859-95e67080-a6ff-11ea-9535-7c2ee6e8d02f.png)

**Comment by crimx** [comment]
Duplicate of #822

**Comment by linsui** [comment]
我看到那个 issue 了，不过似乎行为不太一样就重开了一个。谢谢

**Comment by crimx** [comment]
同是因为浏览器标题栏高度偏差导致，为了兼容这个问题沙拉查词会尝试计算偏差，但目前实现方式有缺陷，部分环境下会得出错误结果。
