### ISSUE TITLE
google 词典有时仅显示部分内容

### ISSUE THREAD

**Issue by LEGENDMOUSE** [crimx/ext-saladict#840]
google 词典问题：如果查的单词在网页版的谷歌词典中需要点向下箭头展开更多内容，词典中仅显示部分内容，例如你可以试试查单词shoal

## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: []

**Comment by crimx** [comment]
Duplicate of #842

你已经反馈过了。
