### ISSUE TITLE
google词典有的单词查不了

### ISSUE THREAD

**Issue by LEGENDMOUSE** [crimx/ext-saladict#841]
google词典有的单词查不了，你查score试试，我点击google词典图标，返回的是define:score没出来词典

## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: []

**Comment by crimx** [comment]
是的，打开 Google 网页显示没有就是代表没有。Google 词典严格上说不算完整的词典，它只是 Google 搜索的一个控件。
