### ISSUE TITLE
关于内层翻译

### ISSUE THREAD

**Issue by str1ngthen** [crimx/ext-saladict#843]
## 设备信息
- 操作系统: [WINDOWS10] 
- 浏览器版本: [CHROME83] 
- 沙拉查词版本: [最新版] 

## 请描述目前使用沙拉查词遇到什么不便
当你使用沙拉查词查询一段文字或翻译一段中文时，翻译出来的单词不可查询（及翻译后的单词不可再翻译，只能从翻译后的语句中推断其意思）

## 理想情况下，沙拉查词应该怎么做
希望可以翻译一段中文后显示的英文句子中的单个词语同样可以翻译

## 替代方案
就像google翻译一样，上面是翻译好的句子，用鼠标划出句子中的某个单词，此单词的意思可在下方显示

## 额外信息
这个插件非常好用！希望可以出windows桌面版或mac版

**Comment by crimx** [comment]
可设置面板内划词模式，请阅读[使用说明](https://saladict.crimx.com/manual.html)了解查词模式。

**Comment by crimx** [comment]
> 希望可以出windows桌面版或mac版

请阅读[常见问题及答复](https://saladict.crimx.com/q&a.html)以及[浏览器外划词](https://saladict.crimx.com/native.html)。
