### ISSUE TITLE
建议独立查词窗口enter键一键查询

### ISSUE THREAD

**Issue by gao-zhijie** [crimx/ext-saladict#845]
设备信息
- 操作系统: Window10
- 浏览器版本: 最新版edge
- 沙拉查词版本:最新版

## 请描述目前使用沙拉查词遇到什么不便
在独立查词窗口不能enter一键查询，需要挪动鼠标点击搜索按钮

## 理想情况下，沙拉查词应该怎么做
独立面板输入单词后enter一键查询而不是换行

thanks

**Comment by crimx** [comment]
你是指多行编辑框？按 ctrl enter
