### ISSUE TITLE
使用quicker截图无法识别日文

### ISSUE THREAD

**Issue by zsy829** [crimx/ext-saladict#846]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Edge] 
- 沙拉查词版本: [v7.13.0] 

## 请描述目前使用沙拉查词遇到什么不便

使用quicker截图无法识别日文,翻译栏显示为中文（日语模式同样无效）

## 理想情况下，沙拉查词应该怎么做

截图识别后，翻译栏为日文

## 替代方案

quicker自带的“截图OCR”可以识别日语

**Comment by crimx** [comment]
你好，请提供至少一个具体的复现步骤。这里应该与 Quicker 无关，提供出现问题的日文即可。

**Comment by hqyyqh** [comment]
目前动作的确是不能直接识别日文，[百度文字识别](https://cloud.baidu.com/doc/OCR/s/zk3h7xz52)识别语言类型默认为**CHN_ENG 中英文混合**

后面我加个识别语言类型的手动切换选项，或者试下直接识别语言类型🤣🤣。

**Comment by hqyyqh** [comment]
Quicker 动作已更新，新增OCR自动检测识别类型，同时提供手动切换选项。

可在**高级设置**中调整
![ ](https://user-images.githubusercontent.com/38676455/84488656-1a725980-acd3-11ea-9fb5-4889a4fbd134.png)
