### ISSUE TITLE
建議增加滑鼠滾輪支持

### ISSUE THREAD

**Issue by ryanpatiency** [crimx/ext-saladict#847]
## 请描述目前使用沙拉查词的情形

想要查看其他例句只能用滑鼠點展開箭頭

## 理想情况下，沙拉查词应该怎么做

當游標移到顯示框中，使用滑鼠滾輪應該可以滑動內容

**Comment by crimx** [comment]
> 想要查看其他例句只能用滑鼠點展開箭頭

你好，「其他例句」是指什么？

> 當游標移到顯示框中，使用滑鼠滾輪應該可以滑動內容

「顯示框中」是指什么？「滑動內容」是指什么内容？

**Comment by ryanpatiency** [comment]
謝謝你。其他例句是指其他內容，查詢生字時出現的其他資訊。顯示框是查詢生字時出現的字典所在的方框，滑動內容是只滑動這方框的內文

**Comment by crimx** [comment]
在[设置](https://saladict.crimx.com/manual.html)中可以设置每个字典的次序和高度，这应该能解决大部分问题。

如果滑鼠会滚动字典内文的话将很难滚动到下面的字典。

**Comment by ryanpatiency** [comment]
原來如此，將字典高度設為 999999 後解決了這個問題，謝謝你

**Comment by crimx** [comment]
Agree to disagree. 「直觉」因人而异。在我看来字典列表比较大，放进「字典介面」中无论是放在上方还是下方都不合适，单独列出来更容易被找到。

很高兴你的问题解决了。
