### ISSUE TITLE
chrome ctrl快速開啟多個不同分頁 意外啟動獨立窗口快捷查詞

### ISSUE THREAD

**Issue by horsepowerhsu** [crimx/ext-saladict#848]
## 设备信息
- 操作系统:  Window10]
- 浏览器版本:  Chrome 版本 83.0.4103.61 (正式版本) (64 位元)
- 沙拉查词版本: 7.13.2

## 描述问题
- 啟用迅速查字 連續按三次ctrl 彈出字典視窗介面功能
- 在**短時間**使用ctrl開啟**不同**分頁時，會意外啟動
- 測試時間約一秒內
- 一定要不同分頁

## 期待的正常行为

因為常用ctrl開啟分頁功能，時常會開啟大量不同分頁，
希望開啟分頁也不會意外觸發視窗，謝謝

**Comment by crimx** [comment]
> 在短時間使用ctrl開啟不同分頁時，會意外啟動

你好，请提供具体的能重现问题的操作步骤。

**Comment by horsepowerhsu** [comment]
實在不知道怎麼描述 因為是很普通的動作 提供影片給您
https://www.youtube.com/watch?v=RGADcwVxrcM&feature=youtu.be

**Comment by crimx** [comment]
在这个过程中你是一直按住 ctrl 还是每次都会放开然后又按下。

如果是一直按住应该没有这个问题。如果是迅速放开又按下必然会触发的，但这么做的人应该会比较少。

**Comment by crimx** [comment]
你可以选择关闭 ctrl 这个功能，改换[其它快捷键](https://saladict.crimx.com/manual.html#shortcuts)。

**Comment by horsepowerhsu** [comment]
> 在这个过程中你是一直按住 ctrl 还是每次都会放开然后又按下。
> 
> 如果是一直按住应该没有这个问题。如果是迅速放开又按下必然会触发的，但这么做的人应该会比较少。
是一直按住

> 你可以选择关闭 ctrl 这个功能，改换[其它快捷键](https://saladict.crimx.com/manual.html#shortcuts)。

好的 我找到快捷鍵設定選項了 謝謝你

**Comment by crimx** [comment]
一直按住 ctrl 我没有办法重现这个问题，这个的情况沙拉查词也有专门处理的。有可能是你的作业系统安装了其它键盘或者滑鼠类辅助软体？之前有一个用户是这种情况。

**Comment by crimx** [comment]
解决了就好。

**Comment by horsepowerhsu** [comment]
> 一直按住 ctrl 我没有办法重现这个问题，这个的情况沙拉查词也有专门处理的。有可能是你的作业系统安装了其它键盘或者滑鼠类辅助软体？之前有一个用户是这种情况。

我選擇改成其他快捷鍵 謝謝~

不過再提供您一下 
剛剛測試了三台不同電腦 (皆為win10, chrome) 
滿足下面三個條件
三台電腦都確實會意外觸發
- 按住ctrl
- **短時間**內點擊(約**一秒內**)
- 一定要**三個以上不同的網址**

**Comment by crimx** [comment]
还是没有办法重现这个问题，在不同网站上都没有问题。如果可以的话把出现问题的网址也提供一下，说明按下哪几个链接。

**Comment by horsepowerhsu** [comment]
> 还是没有办法重现这个问题，在不同网站上都没有问题。如果可以的话把出现问题的网址也提供一下，说明按下哪几个链接。

![1591699867612](https://user-images.githubusercontent.com/57571514/84140464-4055ef00-aa84-11ea-868d-73828fcb3bce.jpg)
- 開啟快捷鍵功能
- 全程都只有按ctrl
我錄了兩段 不同網址和時間差上的不同 給您參考 
因為其他電腦情況相同 但不方便錄就不錄其他電腦了XD
https://www.youtube.com/watch?v=Nz4YOLXf3ww
https://www.youtube.com/watch?v=Vco83G0FCIk

**Comment by crimx** [comment]
我在 YouTube 上以同样的方式尝试了，依然无法重现。既然这个问题有 workaround 就先搁置吧。如果有其他朋友遇到再看看。
