### ISSUE TITLE
浏览器非全屏时，翻译窗口可能部分会显示在屏幕外

### ISSUE THREAD

**Issue by ouchaoo** [crimx/ext-saladict#85]

**Comment by crimx** [comment]
抱歉无法重现，需要更详细的描述。如屏幕分辨率、是否 Retina、浏览什么网页、在什么地方划词、在屏幕的哪个方位溢出。

**Comment by ouchaoo** [comment]
分辨率1080，非Retina，浏览的是Django的官方文档，具体情况如下图。

![gu9hx3 oi2 n47w158 rf8](https://user-images.githubusercontent.com/35865299/37187998-f4984836-2387-11e8-972c-0918d8006435.png)

![kdhppg v 5l70et b5b](https://user-images.githubusercontent.com/35865299/37187997-f469bf3e-2387-11e8-81a4-32893de5fe2a.png)

**Comment by crimx** [comment]
这可能是因为浏览器视口太小了，我看看怎么优化小窗口体验。与此同时你可以按住绿条拖过来。

**Comment by ouchaoo** [comment]
嗯嗯，辛苦了

**Comment by crimx** [comment]
[新版](https://github.com/crimx/ext-saladict/wiki/Saladict6)已修复，如有问题欢迎开新 issue 反馈。
