### ISSUE TITLE
mac上的firefox往下滚动白屏

### ISSUE THREAD

**Issue by lititty** [crimx/ext-saladict#853]
## 设备信息
- 操作系统: [Mac OS 10.15.5] 
- 浏览器版本: [firefox] 
- 沙拉查词版本: [7.13.2] 

## 描述问题

搜索出来结果后，向下滑动白屏

## 截图

没往下滑的时候  
![图片](https://user-images.githubusercontent.com/13444652/84474792-0c660e00-acbe-11ea-83a4-c5060c12f46a.png)  

往下
![图片](https://user-images.githubusercontent.com/13444652/84474719-e93b5e80-acbd-11ea-80c9-9abce7b31c41.png)

**Comment by crimx** [comment]
Duplicate of #712

**Comment by crimx** [comment]
Duplicate of #455
