### ISSUE TITLE
建议在全局查词后，增加可以关闭查词窗口的快捷键设置功能，以方便查词结束后，迅速关闭窗口，开展其他工作。谢谢！

### ISSUE THREAD

**Issue by MaiWei** [crimx/ext-saladict#854]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: []

**Comment by crimx** [comment]
请完整填写模板描述问题。

如果是指独立窗口查词面板那么所有系统窗口管理器快捷键都适用，如果是指页面内查词面板按<kbd>Esc</kdb>关闭。

**Comment by MaiWei** [comment]
非常感谢解答！平时没有使用系统关闭窗口的快捷键习惯，还不知道这个，有点尴尬，刚刚试了是可以的。再次感谢作者的解答！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CRIMX"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月14日(星期天) 晚上11:30
收件人:&nbsp;"crimx/ext-saladict"<ext-saladict@noreply.github.com&gt;;
抄送:&nbsp;"Ｏｎｌｙｙｏｕ"<1483258885@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [crimx/ext-saladict] 建议在全局查词后，增加可以关闭查词窗口的快捷键设置功能，以方便查词结束后，迅速关闭窗口，开展其他工作。谢谢！ (#854)





 
请完整填写模板描述问题。
 
如果是指独立窗口查词面板那么所有系统窗口管理器快捷键都适用，如果是指页面内查词面板按Esc关闭。

**Comment by crimx** [comment]
不客气，解决了就好！
