### ISSUE TITLE
有道翻译只有半截

### ISSUE THREAD

**Issue by sunyone** [crimx/ext-saladict#855]
从前天开始，有道翻译只能显示半截，如下：

有道翻译：
您可以定义文件和表单字段的t

原文：You can define files and form fields at the same time using File and Form

**Comment by crimx** [comment]
沙拉更新需要时间，你可以申请自己的有道账户 key 会更稳定些。

**Comment by okhach** [comment]
我也有这个问题，同时，我的搜狗翻译无法显示翻译结果，申请了个人 key 后任然如此。

**Comment by crimx** [comment]
> 申请了个人 key 后任然如此

主语是指哪个？

搜狗 API 对浏览器不太友好，你可能需要打开一下 http://fanyi.sogou.com/

**Comment by okhach** [comment]
我申请了有道翻译的 key ，只显示半截的问题解决了。
搜狗翻译还是有问题，无法显示翻译结果。

**Comment by crimx** [comment]
你有访问 http://fanyi.sogou.com/ 了吗？应该让你输入图片验证码。

**Comment by okhach** [comment]
访问了，已经正常了，原来是这样

**Comment by okhach** [comment]
谢谢
