### ISSUE TITLE
能不能增加固定翻译的功能

### ISSUE THREAD

**Issue by duwei54** [crimx/ext-saladict#856]
我搜索了一下,好像没有固定翻译词典的功能
有时候翻译,某些专用名词不希望翻译成中文.或者希望翻译成固定的中文词语.
能不能添加一个固定翻译列表的功能.列表内的单词或短语,翻译成固定的词语,或者说不翻译直接显示英文

**Comment by crimx** [comment]
不太清楚有什么用处？请问什么类似的词典应用中提供了此类功能。

**Comment by duwei54** [comment]
> 不太清楚有什么用处？请问什么类似的词典应用中提供了此类功能。

我查了一下 还真没有  不过对于一些全文翻译我决定还是有使用场景.比如计算机的一些词汇其实是不需要翻译或者翻译成固定的文本.  比如`spring`很多词典翻译成`春天`.可能java开发的同学会希望保留.
当然,仅仅是个例子.翻译成春天也能看得懂.

**Comment by crimx** [comment]
没错，这种替换式的方式可能更适用于全文翻译。沙拉查词目前[无计划](https://saladict.crimx.com/notice.html#%E9%A2%84%E8%AE%BE)往这个方向推进。

沙拉查词的理念是帮助用户准确理解一个单词在特定上下文中的意思，以“词”为核心进行设计。遵循这个理念使用的用户理想情况下是词汇量会不停增加，使用频率会慢慢降低。

**Comment by duwei54** [comment]
好嘛  那我关了:joy:

**Comment by crimx** [comment]
嗯嗯，有其它问题可以另开 issue。

**Comment by duwei54** [comment]
好呢  感谢回复
