### ISSUE TITLE
Webdav显示同步失败

### ISSUE THREAD

**Issue by NiuXZi** [crimx/ext-saladict#857]
用的是Mincraft Edge,
在添加webdav时，时可以同步的，显示是否上传，而且也没有报错。
但是在添加单词时会显示连接服务器失败。

**Comment by crimx** [comment]
我刚在 Chrome 上测试了一遍添加单词同步到坚果云是没有问题的。没有 Edge 测试但结果应该也会一样。你的 WebDAV 是否为自搭建？

**Comment by NiuXZi** [comment]
是的，是cloudreve里的

**Comment by crimx** [comment]
自建有无测试过 WebDAV 是否搭建成功？

**Comment by crimx** [comment]
你可以自行发送请求排查。

```bash
curl -d 'test data' -X PUT -H "Authorization: Basic $(echo -n 用户名:密钥 | base64)" https://服务器地址/Saladict/test.json 
```

然后检查服务器上是否有 `Saladict/test.json ` 文件，里面内容为 `test data`。

**Comment by NiuXZi** [comment]
搭建成功了，里面有这个文件。
我的意思是，只能手动的同步。而在添加单词后的自动同步，一直显示失败。

**Comment by crimx** [comment]
我无法复现这个问题。既然设置可以保存成功有可能是暂时的网络连接问题？

**Comment by NiuXZi** [comment]
问题是，自动上传就没成功过，是因为服务器是国外服务器的原因吗

**Comment by crimx** [comment]
不清楚你的环境，可以用上面的命令改变几次文件内容上传测试一下。

**Comment by NiuXZi** [comment]
试了一下，可以接收

**Comment by crimx** [comment]
那么问题有可能出现在下载而不是上传上。

```
curl -X GET -H "Authorization: Basic $(echo -n 用户名:密钥 | base64)" https://服务器地址/Saladict/test.json
```

可以成功下载么？

**Comment by NiuXZi** [comment]
![image](https://user-images.githubusercontent.com/61132813/84772123-144ee680-b00d-11ea-8f32-940cd112b68c.png)
显示这个

**Comment by NiuXZi** [comment]
`<a href="https://ls5-my.sharepoint.com/personal/z003_leimu_ml/_layouts/15/download.aspx?UniqueId=68f5ea41-4648-4faf-aefe-c1f569252188&amp;Translate=false&amp;tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvbHM1LW15LnNoYXJlcG9pbnQuY29tQDIzMjA1NjlkLWE4YmMtNDU4OS05YjgyLTk5ODVkODkwNTAzMSIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE1OTIzMDg2OTAiLCJleHAiOiIxNTkyMzEyMjkwIiwiZW5kcG9pbnR1cmwiOiI3aDhoM3ZRWEpWbGR0ekdNbVJRNExFNW1taloxRlBjY2xML2hyRDcwZ0U4PSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTQwIiwiaXNsb29wYmFjayI6IlRydWUiLCJjaWQiOiJOREUzTkRBNU4ySXRZVGhtTnkwMFpEQTNMVGd6T0dRdFpUQXdNalJsT1dZNU16ZGoiLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiTjJZM1l6VXdNemN0WkRFMk1DMDBNak5pTFdJMlpEZ3ROalk0WlRJME9UQTBZV1UyIiwiYXBwX2Rpc3BsYXluYW1lIjoiY2xvdWRyZXZlX3MiLCJnaXZlbl9uYW1lIjoi77-977-9IiwiZmFtaWx5X25hbWUiOiLvv73vv70iLCJzaWduaW5fc3RhdGUiOiJbXCJrbXNpXCJdIiwiYXBwaWQiOiJiZDA5Y2FhNC0zYmE4LTRjMGYtOTNkYy1mYTUxODNjZjgzNDciLCJ0aWQiOiIyMzIwNTY5ZC1hOGJjLTQ1ODktOWI4Mi05OTg1ZDg5MDUwMzEiLCJ1cG4iOiJ6MDAzQGxlaW11Lm1sIiwicHVpZCI6IjEwMDMyMDAwOUJBRDM2MjYiLCJjYWNoZWtleSI6IjBoLmZ8bWVtYmVyc2hpcHwxMDAzMjAwMDliYWQzNjI2QGxpdmUuY29tIiwic2NwIjoiYWxsZmlsZXMud3JpdGUiLCJ0dCI6IjIiLCJ1c2VQZXJzaXN0ZW50Q29va2llIjpudWxsfQ.T05ldVJMRUNXaitvNDUvZSsybkU5cVduNDZra1RPUHorMEZtSkVadlRaOD0&amp;ApiVersion=2.0">Moved Permanently</a>.`
返回了这个，应该是下载成功了吧

**Comment by crimx** [comment]
301 了，加上 `-L` 

```
curl -L -X GET -H "Authorization: Basic $(echo -n 用户名:密钥 | base64)" https://服务器地址/Saladict/test.json
```

**Comment by NiuXZi** [comment]
`{"error":{"code":"itemNotFound","message":"Item not found"}}`
出错了

**Comment by crimx** [comment]
成功的话显示的是文件的内容。

**Comment by crimx** [comment]
所以 WebDAV 服务器配置有问题了。

**Comment by NiuXZi** [comment]
好吧，我再去检查检查
