### ISSUE TITLE
能不能 在插件里 显示出插件的版本号？我好知道自己用的是不是最新版？

### ISSUE THREAD

**Issue by stfenjobs** [crimx/ext-saladict#858]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Chrome最新] 
- 沙拉查词版本: [不知道怎么看自己的版本号] 

## 请描述目前使用沙拉查词遇到什么不便

我不知道 怎么快速确认自己的插件是最新版本

## 理想情况下，沙拉查词应该怎么做

我希望在浏览器里，进入插件选项页面，可以在底部看到我用的这个翻译插件当前的版本号

**Comment by crimx** [comment]
```
- 沙拉查词版本: [] <!-- 如 [v7.0.0] （在扩展管理页面查看） -->
```

发现还是有不少朋友不知道扩展管理页面？我试试在设置页面标上版本号。
