### ISSUE TITLE
pdf阅读器中鼠标划词灵敏度太高，稍不注意就会选择到过多的句子

### ISSUE THREAD

**Issue by Zeko-Ran** [crimx/ext-saladict#859]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 请描述目前使用沙拉查词遇到什么不便

在沙拉查词的pdf阅读器中，划词或划句子灵敏度太高，稍不注意（一般是划到标点部分稍微偏移一下就会多划很多）就会划词到所选及下方整页的内容，在阅读大量文章时，总是会在这里耽误时间，通常我们只需要划所选部分。（网页中不会出现此现象）

## 理想情况下，沙拉查词应该怎么做

用户鼠标划的范围多少，就选择多少。

**Comment by crimx** [comment]
这是 PDF 的问题，PDF 的设计本来就不是用来这么用的，所以根据制作软件的不同里面的文字语义缺失也会不同。

如有其它 PDF 阅读器相关问题建议到 [PDF.js](https://github.com/mozilla/pdf.js) 反馈。
