### ISSUE TITLE
与扩展管理器的冲突（？）

### ISSUE THREAD

**Issue by H-Tung** [crimx/ext-saladict#861]
## 设备信息
- 操作系统: [Window10]
- 浏览器版本: [Edge 83.0.478.50 (官方内部版本) (64 位)] 
- 沙拉查词版本: [7.13.2] 
- 扩展管理器版本[9.3.5]
## 描述问题

使用扩展管理器锁定扩展后（在浏览器扩展管理界面会显示关闭），解锁后（扩展正常开启），但是划词无反应
## 复现步骤
1. 使用扩展管理器锁定沙拉查词
2. 一段时间后（也许是重启Edge？总之应该不是立刻），使用扩展管理器解锁沙拉查词
3. [某哲学书电子化网站](https://ctext.org/zhs)中划取页顶**中国哲学书电子化计划**
4. 沙拉图标未跳出
## 期待的正常行为

期待使用扩展管理器解锁后划词功能正常使用
## 额外信息

[Microsoft Edge 扩展管理器](https://microsoftedge.microsoft.com/addons/detail/%E6%89%A9%E5%B1%95%E7%AE%A1%E7%90%86%E5%99%A8%EF%BC%88extension-manager%EF%BC%89/bhahgfgngfghgjhnpplmemebhenieijb)
扩展管理器与沙拉查词扩展均由微软Edge官方商店获取
其实是任意网站任意单词啦
无关：期待加入更多古汉语方面的辞典，虽然单字靠着汉典、国语辞典、两岸词典够用了，但是有的时候出现的专有词汇什么的还是有点头疼~

**Comment by crimx** [comment]
不太清楚这类「扩展管理器」的工作原理。沙拉查词自带开关以及常用功能快捷键，无须通过外部控制的。

**Comment by crimx** [comment]
古汉语根据我有限的了解汉典是目前最全的了，有其它做得好的在线词典欢迎推荐。

**Comment by H-Tung** [comment]
啊我主要是因为扩展装的多所以希望通过管理器统一控制来着。。。不同扩展的快捷键有点多
古汉语应该是我想得太简单了，仔细想想通过划词查典故果然还是蛮复杂的，倒不如直接右键百度
还是很感谢大佬，让我看文献和轻小说轻松了许多~
