### ISSUE TITLE
自动朗读翻译结果时出错

### ISSUE THREAD

**Issue by TullyMonster** [crimx/ext-saladict#862]
## 设备信息
- 操作系统: Windows 10 OS Version 2004 (Build 19041.329)
- 浏览器版本: 83.0.4103.106 (正式版本) （64 位） (cohort: Stable) 
- 沙拉查词版本: 7.13.2 

## 描述问题

在设置了**选中语句自动查词**并**自动朗读彩云小译的翻译结果**后，朗读的是**百度翻译**的结果
> 另外，其他的语音朗读引擎似乎不一一匹配

## 复现步骤

1. 打开 Chrome 浏览器；
2. 选中英文句子后出现_沙拉查词 Logo_；
3. 移动光标至 Logo 开始自动朗读翻译结果；
4. 问题出现；

## 期待的正常行为
自动朗读正确的内容

## 额外信息

配置信息👉[下载](https://wwa.lanzous.com/ieThpdtx2sf)

**Comment by crimx** [comment]
使用百度翻译是因为部分服务没有提供相应接口（或者另计费），直接去掉会引起更多不适，可以翻翻之前讨论的一些 issues。
