### ISSUE TITLE
从地址栏旁 Saladict 图打开快捷查词独立窗口出现白块

### ISSUE THREAD

**Issue by owen9936** [crimx/ext-saladict#863]
## 设备信息
- 操作系统: [Windows10] 
- 浏览器版本: [360极速浏览器版本12.0.1386.0，内核版本Chrome78.0.3904.108] 
- 沙拉查词版本: [v7.13.3] 

## 描述问题

从"右上弹框"项目中设置"点击地址栏旁 Saladict 图标"操作为"打开快捷查词独立窗口"，当点击 Saladict 图标后在弹出的快捷查词独立窗口的右上角出现一个白色长条，此时，如果执行动作1：点击浏览器其他空白处，快捷查词独立窗口关闭，白色长条也消失。如果执行动作2：单击查词独立窗口右上角关闭快捷查词独立窗口后白色长条依然存在。
PS. 目测白色长条的宽度和位置与查词面板（从"右上弹框"项目中设置"点击地址栏旁 Saladict 图标"操作为"显示查词面板"，然后单击Saladict 图标弹出）顶部任务栏的宽度和位置相当。

## 复现步骤

复现步骤同上

## 期待的正常行为

正常行为应该不出现那个白色长条

## 截图

![WeChat Screenshot_20200620222246](https://user-images.githubusercontent.com/67196414/85204646-7af33d80-b348-11ea-8071-555326ef09c8.png)

## 额外信息

系统显示缩放比例为125%

**Comment by owen9936** [comment]
![WeChat Screenshot_20200620222246](https://user-images.githubusercontent.com/67196414/85204681-abd37280-b348-11ea-8d54-83596b577f23.png)

**Comment by owen9936** [comment]
系统显示缩放比例为125%

**Comment by crimx** [comment]
这个应该 360 魔改的问题，在 Chrome 中是正常的，我看看有无兼容办法。

**Comment by owen9936** [comment]
好的，没想到这么快就收到回复了，非常感谢！

**Comment by crimx** [comment]
很遗憾无法确认 360 做了什么，无法兼容这个显示。
