### ISSUE TITLE
7.13.3 版本输入完词典账号之后，切换下选项卡再换回来，词典账号就消失了

### ISSUE THREAD

**Issue by sle1008** [crimx/ext-saladict#865]
这个情况是为了隐私保护特意设置的，还是确实是个 bug 啊？

**Comment by crimx** [comment]
你好，请完整填写反馈模板，提供具体的环境信息以及问题的具体复现步骤。

**Comment by sle1008** [comment]
![image](https://user-images.githubusercontent.com/39543446/85281966-7603ca80-b4bd-11ea-834e-9342f338390c.png)
上面是我填写好各个ＡＰＩ并保存之后。

然后接下来左侧的选项卡任意切换一下，再切换回词典账号选项卡，就没了，变成了没填写之前的样子。如下图
![image](https://user-images.githubusercontent.com/39543446/85282390-3b4e6200-b4be-11ea-9ca2-bf99365e379c.png)

我在我 deepin 系统和 mac 系统的谷歌浏览器的插件上，都能复现这个情况，每次都一样。难道只有我这样？谷歌浏览器版本都是最新的84版。这样说够详细了吧。

**Comment by sle1008** [comment]
咦，为什么看不到图。你们是怎么添加图的？

**Comment by crimx** [comment]
问题已成功确认，感谢反馈。

**Comment by sle1008** [comment]
> 问题已成功确认，感谢反馈。

刚刚发现，这应该只是个显示 bug，我已经输入的各大平台的 API 都正常工作了。已经计入我自己账号的统计字数里面了

**Comment by crimx** [comment]
是的，这个版本升级了些依赖没做好兼容。
