### ISSUE TITLE
新edge浏览器里总是被禁用且无法正常使用

### ISSUE THREAD

**Issue by Maintenon** [crimx/ext-saladict#868]
## 设备信息
- 操作系统: Window10
- 浏览器版本: edge 83.0.478.54
- 沙拉查词版本: v7.13.4

## 描述问题

打开浏览器，沙拉查词是默认关闭状态，即使是重新安装一次，自动跳转的扩展选项页面也打不开。
在edge自己的商店和chrome商店都重装过，但都是一样的结果，电脑也重启过，还是打开浏览器默认沙拉查词插件是关闭状态，手动打开之后，查完一次，只要页面有刷新或者任何变动，就会立刻被自动关闭

在浏览器的扩展管理中全部开启权限，但稍不留神就又被关闭了

选择“扩展选项”的时候，完全无法打开，界面如下
![I3D8RW5AFJ 4NYCYVFWT9AH](https://user-images.githubusercontent.com/65640992/85398075-3c979180-b587-11ea-8fa8-ed11fe8f1d8f.png)

另外手动打开之后，划词也不会显示翻译，点击图标，默认出现的是我最后一次复制的文本

## 复现步骤

1. 鼠标选中一段文字，没有显示查词图标

![QQ图片20200623193638](https://user-images.githubusercontent.com/65640992/85399123-e0ce0800-b588-11ea-90ba-41d33c247d76.png)

2. 在选中状态下，点击扩展图标，显示的是我最后一次复制的文本，
![QQ图片20200623193835](https://user-images.githubusercontent.com/65640992/85399341-3c989100-b589-11ea-8a6a-7fa863e162ae.png)

3. 并且没有自动翻译出来，要点击查询才会有
![image](https://user-images.githubusercontent.com/65640992/85399622-afa20780-b589-11ea-8de1-ecc196633c43.png)

## 期待的正常行为

希望能恢复正常使用，我前段时间是可以的，后来不知道怎么回事就每次都自动关闭了

## 其他信息
不知道是不是我的浏览器被开启了什么，其他查词插件也都惨遭毒手，谷歌翻译的插件也是每用一次都要重新手动开启才能用

**Comment by crimx** [comment]
> 不知道是不是我的浏览器被开启了什么，其他查词插件也都惨遭毒手

既然其它扩展也出现这样的情况，这很可能是你开启了什么安全之类的设置吧，限制了扩展的网络权限。

因为我不用 Edge 所以不太清楚。看看有没有其TA小伙伴知道什么原因。

**Comment by crimx** [comment]
![IMG_20200623_201356](https://user-images.githubusercontent.com/6882794/85402506-63a59180-b58e-11ea-8c0e-0253b6db8b28.png)

rumosky 朋友给的建议：你可以右键扩展图标，看看是不是可访问站点是不是被限制为点击时了。

如果依然不能解决建议重置或重装 Edge，记得备份好数据。

**Comment by Maintenon** [comment]
> 。

不是的，我有检查过，确认打开了在所有站点上
<img width="604" alt="Snipaste_2020-06-23_20-20-16" src="https://user-images.githubusercontent.com/65640992/85402862-ffcf9880-b58e-11ea-929d-bf06f5235a1f.png">

**Comment by crimx** [comment]
如果不是这个情况请检查沙拉查词的设置，「右上弹框」有没有设置为打开时自动搜索？「划词模式」有没有设置为图标模式？

**Comment by Maintenon** [comment]
> 如果不是这个情况请检查沙拉查词的设置，「右上弹框」有没有设置为打开时自动搜索？「划词模式」有没有设置为图标模式？

主要是我连设置都打不开....打开就是一片空白，就是第一个图那样子

**Comment by crimx** [comment]
这么奇怪？如果你在这个页面按下 F12 ，在弹出的开发者面板中的 console 标签下能看到有红色错误信息么？

**Comment by Maintenon** [comment]
> 检查沙拉查词的设置

刷新或者努力想打开扩展设置界面的话就会出现这个
<img width="432" alt="Snipaste_2020-06-23_20-31-47" src="https://user-images.githubusercontent.com/65640992/85403861-a700ff80-b590-11ea-857c-603d7980d17f.png">

错误是这个
![ELBBNOSNAGOT5{6~4E717PH](https://user-images.githubusercontent.com/65640992/85403940-c4ce6480-b590-11ea-8559-62ec6da4c918.png)

**Comment by crimx** [comment]
有没有安装了代理扩展，这看起来像是代理配置不正确，把内部扩展地址当作普通地址发送请求了。

**Comment by Maintenon** [comment]
> 有没有安装了代理扩展，这看起来像是代理配置不正确，把内部扩展地址当作普通地址发送请求了。

啊是的有安装了二管家，我关闭试一试，但是我在chrome上也是一样的配置但是没有问题

**Comment by Maintenon** [comment]
我关闭扩展管理之后，扩展不会被自动关闭了，设置好之后，但是划词后仍然不能显示查词图标，点击扩展栏里的图标，查词面板里是空白的，必须还是要手动复制或者输入要翻译的内容点击查询才能显示

**Comment by crimx** [comment]
"设置好之后"是指“「右上弹框」设置为打开时自动搜索，「划词模式」有没有设置为图标模式”？

这个应该不是沙拉查词的问题了。把沙拉查词从扩展管理类的扩展中移出来，然后重启浏览器。

**Comment by Maintenon** [comment]
解决了，非常感谢！
