### ISSUE TITLE
希望增加欧陆词典的单词同步

### ISSUE THREAD

**Issue by leavky** [crimx/ext-saladict#869]
欧陆词典也提供了生词本同步的API，希望可以增加欧陆词典单词同步的选项。
API文档在这里：https://my.eudic.net/OpenAPI/doc_api_study

![image](https://user-images.githubusercontent.com/46547390/85497148-0b16d880-b610-11ea-824f-288d905da82f.png)

**Comment by CraKeyBoy** [comment]
辛苦了

**Comment by Kampfa** [comment]
感谢，十分期待这个功能。

**Comment by gyq171** [comment]
期待这个功能

**Comment by zzzzzjy-cuber** [comment]
非常感谢你，期待欧路词典能够纳入sala的大家庭

**Comment by crimx** [comment]
感谢 @yipanhuasheng 添加，等待 v2.20.0 上架。
