### ISSUE TITLE
开发渐进式Web应用（PWA应用）

### ISSUE THREAD

**Issue by zhangyucha0** [crimx/ext-saladict#870]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Chrome83] 
- 沙拉查词版本: [v7.13.4] 

## 请描述目前使用沙拉查词遇到什么不便
当前「不打开浏览器直接召唤沙拉查词」的[官方解决方案](https://saladict.crimx.com/native.html#%E4%B8%8D%E6%89%93%E5%BC%80%E6%B5%8F%E8%A7%88%E5%99%A8%E7%9B%B4%E6%8E%A5%E5%8F%AC%E5%94%A4%E6%B2%99%E6%8B%89%E6%9F%A5%E8%AF%8D)是打开选项：`关闭“Google Chrome 浏览器”后继续运行后台应用程序`
担心会有占用内存，以及各种奇怪的应用自启，占用资源等问题。

## 理想情况下，沙拉查词应该怎么做
考虑到Chrome APP已经被弃用。是否能开发PWA应用？还可以借助PWA的特性实现离线查词~

## 替代方案
无

## 额外信息
无

**Comment by crimx** [comment]
> 担心会有占用内存，以及各种奇怪的应用自启，占用资源等问题。

还没有遇到过类似问题，虽然我基本上浏览器都是处于打开状态😆。

> 考虑到Chrome APP已经被弃用。是否能开发PWA应用？

PWA 依然是要浏览器才能运行，而且本质还是网页应用，用不了扩展 API。

> 还可以借助PWA的特性实现离线查词~

只能缓存沙拉查词本身的数据，查词结果版权归第三方服务器所有，沙拉查词不会进行存储，所以还是要网络才能查词。
