### ISSUE TITLE
生词本没有词典结果

### ISSUE THREAD

**Issue by upcxksorce** [crimx/ext-saladict#871]
## 设备信息
- 操作系统: [Window7] 
- 浏览器版本: [Microsoft Edge | 80.0.361.111 (官方内部版本) (64 位)] 
- 沙拉查词版本: [v7.13.3] 

## 请描述目前使用沙拉查词遇到什么不便

在查词面板点击 爱心 加入生词本时，可以加入的翻译结果没有必应词典的。但是！但是！但是!，必应词典的释义是比较详细的，各方面均衡，请求请求请求
![image](https://user-images.githubusercontent.com/34813726/85521411-cbafb280-b636-11ea-88e3-b1c0170fa323.png)
添加。

![image](https://user-images.githubusercontent.com/34813726/85521110-5fcd4a00-b636-11ea-9bf8-9953a93e0ea7.png)

**Comment by crimx** [comment]
[添加生词可不可以加入单词翻译（而不是翻译整句上下文）](https://saladict.crimx.com/q&a.html#%E9%97%AE%EF%BC%9A%E6%B7%BB%E5%8A%A0%E7%94%9F%E8%AF%8D%E5%8F%AF%E4%B8%8D%E5%8F%AF%E4%BB%A5%E5%8A%A0%E5%85%A5%E5%8D%95%E8%AF%8D%E7%BF%BB%E8%AF%91%EF%BC%88%E8%80%8C%E4%B8%8D%E6%98%AF%E7%BF%BB%E8%AF%91%E6%95%B4%E5%8F%A5%E4%B8%8A%E4%B8%8B%E6%96%87%EF%BC%89%E3%80%82)

**Comment by upcxksorce** [comment]
好吧，谢谢了
&nbsp;


肖康 (x_k)&nbsp;&nbsp;
中国 山东 青岛 | 学生
广电传媒 | 暂时没有




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CRIMX"<notifications@github.com&gt;; 
发送时间: 2020年6月24日(星期三) 下午5:09
收件人: "crimx/ext-saladict"<ext-saladict@noreply.github.com&gt;; 
抄送: "快乐的qq邮箱"<1261953083@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [crimx/ext-saladict] 生词本没有词典结果 (#871)





 
添加生词可不可以加入单词翻译（而不是翻译整句上下文）
