### ISSUE TITLE
划词字符与搜索框粘贴的字符错位

### ISSUE THREAD

**Issue by FFF23333** [crimx/ext-saladict#872]
## 设备信息
- 操作系统:   Window10
- 浏览器版本:   Edge  83.0.478.54
- 沙拉查词版本:   v7.13.3

## 描述问题

鼠标划词和自动粘贴到搜索框的词会相差1-2个字母

## 截图

![image](https://user-images.githubusercontent.com/67356949/85501524-21289700-b618-11ea-9c46-b76f0c4d10b8.png)

**Comment by crimx** [comment]
<https://saladict.crimx.com/notice.html#%E5%B1%80%E9%99%90%E6%80%A7>
