### ISSUE TITLE
把它好好吃掉

### ISSUE THREAD

**Issue by kliop00023** [crimx/ext-saladict#876]
就不用啥define：打在狗狗的搜索里就说自己是词典了。。。
肉肉：https://chrome.google.com/webstore/detail/google-dictionary-by-goog/mgijmajocgfcbeboacabfgobmjgjcoja

**Comment by kliop00023** [comment]
谷狗那个是跟翻译不同滴，而搜索里是Definitions from Oxford Languages（http://english.oxforddictionaries.com/define）

**Comment by hqyyqh** [comment]
反馈不是有模板吗？这样子看不懂你想表达什么啊。
