### ISSUE TITLE
没有满足条件的词典时，是不是不应该显示查词图标？

### ISSUE THREAD

**Issue by starryspace** [crimx/ext-saladict#878]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Chromium 80.0.3987.163] 
- 沙拉查词版本: [v7.13.4] 

## 描述问题

没有满足条件的词典时，是不是不应该显示查词图标？

## 复现步骤

1. 修改词典设置
在词典设置中，删除其他词典、只保留一个，编辑保留下来的唯一一个词典的设置，取消选中”划词语言“中的“中文”，其他设置如“划词字数”的值无所谓，保存。

2. 在页面上测试划词翻译
在任意中文页面，鼠标选中几个汉字，这时会沙拉图标会浮现。

## 期待的正常行为

第2步操作中沙拉图标不应该浮现。

**Comment by crimx** [comment]
你设置的是不是词典的显示语言？划词语言在「查词习惯」中设置。这两者针对不一样的使用场景。

**Comment by starryspace** [comment]
> 你设置的是不是词典的显示语言？划词语言在「查词习惯」中设置。这两者针对不一样的使用场景。

对，我是在“词典设置“中设置的。现在我在”查词习惯“中的”划词语言“取消选中”中文”，问题解决了。
谢谢解答！
