### ISSUE TITLE
中文混合了编程语句的输入翻译不正确

### ISSUE THREAD

**Issue by mrdulin** [crimx/ext-saladict#879]
## 设备信息
- 操作系统: [macOS] 
- 浏览器版本: [chromium 版本 81.0.4009.0（开发者内部版本） （64 位）] 
- 沙拉查词版本: [v7.13.4] 

## 描述问题

中英翻译，词典为彩云小译，输入“如果bcrypt.hash导致问题”，翻译结果为：

Something something bcrypt.hash something something something something something

有道词典则不予以翻译，其他词典可能也会有此问题，不确定是词典服务本身的问题还是沙拉查词的问题

## 复现步骤

1. 点击词典扩展图标
2. 输入“如果bcrypt.hash导致问题”
3. 问题出现

## 期待的正常行为

翻译中文，英文bcrypt.hash原样显示

## 截图

![image](https://user-images.githubusercontent.com/17866683/86361641-bc6bdd00-bca6-11ea-83a6-4d944d950a73.png)

**Comment by crimx** [comment]
可以在相应词典设置中调整优先目标语言。

**Comment by mrdulin** [comment]
@crimx 查词习惯-划词语言只保留了“英文”，彩云小译-划词语言也只保留了“英文”，同样的问题

**Comment by crimx** [comment]
是在相应词典的设置中设置优先「目标语言」。划词语言设置的是什么条件下显示词典。

**Comment by crimx** [comment]
你这句话同时包含了英文和中文，默认情况下优先语言随浏览器，所以翻译成中文。改为英文即可。

**Comment by mrdulin** [comment]
![image](https://user-images.githubusercontent.com/17866683/86381431-e978b980-bcbf-11ea-9595-6720d59df042.png)

**Comment by mrdulin** [comment]
设置如下：

![image](https://user-images.githubusercontent.com/17866683/86381781-217ffc80-bcc0-11ea-8386-4e880b659a20.png)

**Comment by mrdulin** [comment]
设置目标语言算正常了
![image](https://user-images.githubusercontent.com/17866683/86382648-6efc6980-bcc0-11ea-8f84-7e68a4655ebe.png)
