### ISSUE TITLE
翻译介面视窗当机

### ISSUE THREAD

**Issue by stockyman** [crimx/ext-saladict#88]
一个好的反馈格式
===============

- 平台：包括操作系统和 Chrome 版本
Windows 10
Chrome 版本: Google Chrome 瀏覽器 v66.0.3359.26 

- 类型：错误？建议？ 

當要查一個單字時，翻譯視窗會定格黏貼在網頁上，視窗無法移動，scrollbar 無法上下移動查看額外字典的翻譯內容，請修正!! 謝謝!!

- 重现：提供详细地操作来重现状况。

- 期待：理想情况下扩展应该怎么做？

- 实际：客观描述扩展实际上做了什么。

- 额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
嗨，无法重现你的问题。这是在所有网页上都这样么？还是在特定的网页上？

另外，不知有没有兴趣帮忙修正一下繁体的措辞 :smile:  。https://github.com/crimx/ext-saladict/blob/dev/src/_locales/messages.json

**Comment by stockyman** [comment]
已經恢復正常!!
可能我剛重灌瀏覽器的原因，造成系統反應不過來。所以翻意軟體才會當機！
謝謝你的回覆!!

對了！ 有個建議， 雖然這建議對你來講工程有點浩大！ 
不過，依你的軟體寫作功力應該不成問題!

你可以把你這套中英字典軟體， 可以在設計有繁簡字體切換功能嗎??
這對我們這些使用繁體中文字的華人族群有相當大的幫助！

謝謝!!

**Comment by crimx** [comment]
这个其实是因为词典的结果是简体的，如果直接转换的成中文的话目前没有特别完美的方案，而且可能会影响速度。如果你有什么繁体的词典推荐我可以去看看。

**Comment by stockyman** [comment]
"zh_CN": "沙拉查词-网页划词翻译",
      "zh_TW": "沙拉查詞-網頁單字滑鼠劃字和句子翻譯",
-------------------------------------------------------------------------------------------------------------------
"zh_CN": "全能网页划词翻译，开放源码、功能丰富、超多词典、清爽快速、支持个性化设置",
      "zh_TW": "全能網頁單字劃字和句子翻譯，開放源碼、功能豐富、超多字典可查讀、清爽快速、支持個人化設定",
-------------------------------------------------------------------------------------------------------------------
 "zh_CN": "觉得好用的话欢迎支持一下我买杯咖啡哦~",
      "zh_TW": "覺得好用的話，歡迎支持我一下。買杯咖啡送給我哦！謝謝！~",
      "en": "觉得好用的话欢迎支持一下我买杯咖啡哦~"
-----------------------------------------------------------------------------------------------------------------
 "zh_CN": "联系作者",
      "zh_TW": "聯絡作者",
      "en": "联系作者"
--------------------------------------------------------------------------------------------------------------
  "zh_CN": "反馈问题",
      "zh_TW": "軟體使用疑問和建言",
      "en": "反馈问题"
---------------------------------------------------------------------------------------------------------------
  "zh_CN": "保存",
      "zh_TW": "蓄存",
      "en": "保存"
----------------------------------------------------------------------------------------------------------------
 "zh_CN": "设置已更新",
      "zh_TW": "設定已更新",
      "en": "设置已更新"
------------------------------------------------------------------------------------------------------------------
 "zh_CN": "重置设定",
      "zh_TW": "重設設定",
      "en": "重置设定"
-----------------------------------------------------------------------------------------------------------------
 "zh_CN": "所有设定将还原到默认值，确定？",
      "zh_TW": "所有設定將還原到還原點，確定？",
      "en": "所有设定将还原到默认值，确定？"
--------------------------------------------------------------------------------------------------------------
 "description": "设置页面标题",
    "message": {
      "zh_CN": "Saladict 设置",
      "zh_TW": "Saladict 設定",
      "en": "Saladict 设置"
    }
------------------------------------------------------------------------------------------------------------
 "zh_CN": "默认用本扩展浏览 PDF",
      "zh_TW": "確認用本延伸視窗介面擴展瀏覽 PDF功能",
      "en": "默认用本扩展浏览 PDF"
--------------------------------------------------------------------------------------------------------------
 "zh_CN": "关闭后划词翻译功能将关闭，快捷查词功能依然可用。开启默认 PDF 浏览所有 PDF 链接将自动跳转到本扩展打开（包括本地）。",
      "zh_TW": "關閉後，滑鼠劃字和句子翻譯功能將關閉，迅速查單字和句子的功能依然可以用。開啟確認鍵後， PDF 瀏覽功能可以運作使用。所有 PDF 鏈接，將自動跳轉到本延伸擴展視窗介面，打開後，可以查看（包括本地）。",
      "en": "关闭后划词翻译功能将关闭，快捷查词功能依然可用。开启默认 PDF 浏览所有 PDF 链接将自动跳转到本扩展打开（包括本地）。"
------------------------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "单词列表",
      "zh_TW": "單字和例句列表",
      "en": "单词列表"
    }
---------------------------------------------------------------------------------------------------------------
  "zh_CN": "记录查词历史",
      "zh_TW": "記錄查字歷史",
      "en": "记录查词历史"
------------------------------------------------------------------------------------------------------------------
"zh_CN": "添加生词时播放声音",
      "zh_TW": "添加單字和例句時，播放聲音",
      "en": "添加生词时播放声音"
-------------------------------------------------------------------------------------------------------------
 "message": {
      "zh_CN": "关闭记录查词历史后先前的记录依然保留，可在查词历史页面手动清空。",
      "zh_TW": "關閉查字歷史記錄後，先前的記錄依然保存，可以在查字歷史視窗介面裡手動清空。",
      "en": "关闭记录查词历史后先前的记录依然保留，可在查词历史页面手动清空。"
-------------------------------------------------------------------------------------------------------------
"zh_CN": "查词模式",
      "zh_TW": "查字模式",
      "en": "查词模式"
------------------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "显示图标",
      "zh_TW": "顯示圖案",
      "en": "显示图标"
-------------------------------------------------------------------------------------------------------------
"opt_mode_direct": {
    "description": "option",
    "message": {
      "zh_CN": "直接搜索",
      "zh_TW": "直接搜尋",
      "en": "直接搜索"
-------------------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "双击搜索",
      "zh_TW": "滑鼠雙點擊搜尋",
      "en": "双击搜索"
--------------------------------------------------------------------------------------------------------------
 "message": {
      "zh_CN": "双击间隔",
      "zh_TW": "滑鼠雙點擊間隔",
      "en": "双击间隔"
-------------------------------------------------------------------------------------------------------------
"zh_CN": "当用鼠标在网页上选择了一段文本，<strong>“显示图标”</strong>会先在鼠标附近显示一个图标，鼠标移上去后才显示词典面板；<strong>“直接搜索”</strong>则不显示图标，直接显示词典面板；<strong>“双击搜索”</strong>双击选择文本之后直接显示词典面板；<strong>“按住 Ctrl”</strong>在选择文本时需同时按住<kbd>Ctrl</kbd>或者<kbd>Command ⌘</kbd>键才显示词典面板。",
      "zh_TW": "當使用滑鼠，在網頁上選擇一段句子或單字，<strong>「顯示圖案」</strong>會先在滑鼠附近顯示一個圖案，滑鼠移動到圖案，會顯示出字典的視窗介面；<strong>「直接搜尋」</strong>則不會顯示圖案，直接顯示字典視窗介面；<strong>「滑鼠雙點擊搜尋」</strong>滑鼠雙點擊所選擇的句子或單字後，會直接顯示在字典視窗介面裡；<strong>「按住 Ctrl」</strong>在選擇句子或單字時，需同時按住<kbd>Ctrl</kbd>或者<kbd>Command ⌘</kbd>鍵，才能顯示在字典視窗介面裡。",
      "en": "当用鼠标在网页上选择了一段文本，<strong>“显示图标”</strong>会先在鼠标附近显示一个图标，鼠标移上去后才显示词典面板；<strong>“直接搜索”</strong>则不显示图标，直接显示词典面板；<strong>“双击搜索”</strong>双击选择文本之后直接显示词典面板；<strong>“按住 Ctrl”</strong>在选择文本时需同时按住<kbd>Ctrl</kbd>或者<kbd>Command ⌘</kbd>键才显示词典面板。"
    }
------------------------------------------------------------------------------------------------------------------
 "message": {
      "zh_CN": "钉住查词",
      "zh_TW": "釘住查字",
      "en": "钉住查词"
---------------------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "当面板被钉住时的查词模式。",
      "zh_TW": "當視窗被釘住時的查字模式。",
      "en": "当面板被钉住时的查词模式。"
-------------------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "预先加载",
      "zh_TW": "預先下載",
      "en": "预先加载"
------------------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "页面划词",
      "zh_TW": "滑鼠頁面劃字和句子",
      "en": "页面划词"
---------------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "自动查词",
      "zh_TW": "自動查字",
      "en": "自动查词"
----------------------------------------------------------------------------------------------------
 "opt_triple_ctrl_title": {
    "description": "option title",
    "message": {
      "zh_CN": "快捷查词",
      "zh_TW": "迅速查字",
      "en": "快捷查词"
------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "连续按三次<kbd>Ctrl</kbd>或者<kbd>Command ⌘</kbd>键将弹出词典界面。选择预先加载内容会显示在输入框里。启动自动查词将在面板出现之后自动开始查词。",
      "zh_TW": "連續按滑鼠三次<kbd>Ctrl</kbd>或者<kbd>Command ⌘</kbd>鍵，將會彈出字典視窗介面。選擇預先下載的內容，會顯示在輸入框裡。啟動自動查字功能，字典視窗介面會出現，此時，會自動開始查尋單字。",
      "en": "连续按三次<kbd>Ctrl</kbd>或者<kbd>Command ⌘</kbd>键将弹出词典界面。选择预先加载内容会显示在输入框里。启动自动查词将在面板出现之后自动开始查词。"
    }
----------------------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "点击右上方地址栏旁图标弹出的窗口。选择预先加载内容会显示在输入框里。启动自动查词将在面板出现之后自动开始查词。",
      "zh_TW": "滑鼠點擊右上方的地址欄，旁邊的圖案會自動彈出視窗介面。選擇預先下載的內容，會顯示在輸入框裡。啟動自動查字功能，在視窗介面出現後，自動開啟查字功能。",
      "en": "点击右上方地址栏旁图标弹出的窗口。选择预先加载内容会显示在输入框里。启动自动查词将在面板出现之后自动开始查词。"
    }
-------------------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "中文查词",
      "zh_TW": "中文查字",
      "en": "中文查词"
-------------------------------------------------------------------------------------------------------------
 "message": {
      "zh_CN": "英文查词",
      "zh_TW": "英文查字",
      "en": "英文查词"
-------------------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "当选中的文字包含相应的语言时才进行查找。",
      "zh_TW": "當選中的文字包含相對應的語言時，才進行查尋。",
      "en": "当选中的文字包含相应的语言时才进行查找。"
--------------------------------------------------------------------------------------------------------------
 "message": {
      "zh_CN": "美音",
      "zh_TW": "美語發音",
      "en": "美音"
---------------------------------------------------------------------------------------------------------
 "message": {
      "zh_CN": "英音",
      "zh_TW": "英語發音",
      "en": "英音"
------------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "下拉列表的项目为支持自动发音的词典，开启功能还必须启用词典，见下方“词典配置”。“默认展开”与相应的语言显示须要勾选。",
      "zh_TW": "下拉列表的選項項目為支持自動發音的字典。開啟功能，還必須啟動字典。見下方「字典配置設定」。「確認展開」與相對應的語言顯示，須要勾選。",
      "en": "下拉列表的项目为支持自动发音的词典，开启功能还必须启用词典，见下方“词典配置”。“默认展开”与相应的语言显示须要勾选。"
---------------------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "词典设置",
      "zh_TW": "字典設定",
      "en": "词典设置"
--------------------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "配置各个词典，建议按个人需求裁减到最少。拖动词典标题可以进行排序。",
      "zh_TW": "設定配置各個字典，建議按造個人所需，來增減需求。使用滑鼠拖動字典標題，可以進行排列組合。",
      "en": "配置各个词典，建议按个人需求裁减到最少。拖动词典标题可以进行排序。"
-----------------------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "添加词典",
      "zh_TW": "添加單字和句子",
      "en": "添加词典"
--------------------------------------------------------------------------------------------------------
  "description": "词典的默认高度",
    "message": {
      "zh_CN": "默认高度",
      "zh_TW": "確認高度",
      "en": "默认高度"
-----------------------------------------------------------------------------------------------------
 "description": "词典是否默认展开",
    "message": {
      "zh_CN": "默认展开",
      "zh_TW": "確認展開",
      "en": "默认展开"
--------------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "选择单词之后可以通过右键查找或者搜索。拖动标题可以进行排序。",
      "zh_TW": "選擇單字和句子後，可以按滑鼠右鍵查尋或者搜尋。使用滑鼠拖動標題，可以進行排列組合。",
      "en": "选择单词之后可以通过右键查找或者搜索。拖动标题可以进行排序。"
-------------------------------------------------------------------------------------------------------------------
 "message": {
      "zh_CN": "谷歌搜索",
      "zh_TW": "谷歌搜尋",
      "en": "谷歌搜索"
------------------------------------------------------------------------------------------------------
 "message": {
      "zh_CN": "百度搜索",
      "zh_TW": "百度搜尋",
      "en": "百度搜索"
----------------------------------------------------------------------------------------------------
 "message": {
      "zh_CN": "必应搜索",
      "zh_TW": "必應搜尋",
      "en": "必应搜索"
----------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "培根词源",
      "zh_TW": "培根字根",
      "en": "培根词源"
----------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "韦氏词典",
      "zh_TW": "韋氏字典",
      "en": "韦氏词典"
-----------------------------------------------------------------------------------------------------
 "message": {
      "zh_CN": "牛津词典",
      "zh_TW": "牛津字典",
      "en": "牛津词典"
-------------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "剑桥词典",
      "zh_TW": "劍橋字典",
      "en": "剑桥词典"
--------------------------------------------------------------------------------------------------------
 "message": {
      "zh_CN": "有道词典",
      "zh_TW": "有道字典",
      "en": "有道词典"
-----------------------------------------------------------------------------------------------------
  "message": {
      "zh_CN": "海词词典",
      "zh_TW": "海詞字典",
      "en": "海词词典"
--------------------------------------------------------------------------------------------------------
  "message": {
      "zh_CN": "两岸词典",
      "zh_TW": "兩岸字典",
      "en": "两岸词典"
---------------------------------------------------------------------------------------------------------
 "message": {
      "zh_CN": "国语辞典",
      "zh_TW": "國語字典",
      "en": "国语辞典"
-------------------------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "必应词典",
      "zh_TW": "必應字典",
      "en": "必应词典"
-----------------------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "生词本",
      "zh_TW": "生字本",
      "en": "生词本"
-----------------------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "只显示英文记录",
      "zh_TW": "只顯示英文單字記錄",
      "en": "只显示英文记录"
-------------------------------------------------------------------------------------------------------------------
  "message": {
      "zh_CN": "保存为文件",
      "zh_TW": "存取為文件",
      "en": "保存为文件"
----------------------------------------------------------------------------------------------------------------
 "message": {
      "zh_CN": "导出文本",
      "zh_TW": "輸出文本",
      "en": "导出文本"
----------------------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "保存成功！",
      "zh_TW": "存取成功！",
      "en": "保存成功！"
----------------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "保存成功！",
      "zh_TW": "存取成功！",
      "en": "保存成功！"
-----------------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "保存成功！",
      "zh_TW": "存取成功！",
      "en": "保存成功！"
-----------------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "编写生成模板，描述每条记录生成的样子：",
      "zh_TW": "編寫產生的模板，描述每條記錄產生的樣子：",
      "en": "编写生成模板，描述每条记录生成的样子："
    }
---------------------------------------------------------------------------------------------------------------
 "message": {
      "zh_CN": "替换符",
      "zh_TW": "替換符號",
      "en": "替换符"
---------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "保存到生词本",
      "zh_TW": "保存到單字本",
      "en": "保存到生词本"
-----------------------------------------------------------------------------------------------------
 "message": {
      "zh_CN": "查词历史记录",
      "zh_TW": "查單字歷史記錄",
      "en": "查词历史记录"
-------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "无历史记录，查词后再查看",
      "zh_TW": "無歷史記錄，查字後，再查看",
      "en": "无历史记录，查词后再查看"
--------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "清空查词历史",
      "zh_TW": "清空查字歷史記錄",
      "en": "清空查词历史"
-----------------------------------------------------------------------------------------
"message": {
      "zh_CN": "所有查词历史记录将被清除，确定？",
      "zh_TW": "所有查字歷史記錄將被清除，確認？",
      "en": "所有查词历史记录将被清除，确定？"
-----------------------------------------------------------------------------
"message": {
      "zh_CN": "生词本",
      "zh_TW": "單字本",
      "en": "生词本"
------------------------------------------------------------------------------
 "message": {
      "zh_CN": "共 %s 条记录，生词本数据不同步，注意导出",
      "zh_TW": "共 %s 條記錄，單字本數據不同步，注意取出",
      "en": "共 %s 条记录，生词本数据不同步，注意导出"
-----------------------------------------------------------------------------------------
"message": {
      "zh_CN": "无生词记录，添加后再查看",
      "zh_TW": "無單字記錄，添加後再查看",
      "en": "无生词记录，添加后再查看"
---------------------------------------------------------------------------------
"message": {
      "zh_CN": "清空生词本",
      "zh_TW": "清空單字本",
      "en": "清空生词本"
-----------------------------------------------------------------------------------
"message": {
      "zh_CN": "生词本所有记录将被清除，确定？",
      "zh_TW": "單字本所有記錄將被清除，確認？",
      "en": "生词本所有记录将被清除，确定？"
----------------------------------------------------------------------------------
 "message": {
      "zh_CN": "单词",
      "zh_TW": "單字",
      "en": "单词"
-----------------------------------------------------------------------------------------
 "message": {
      "zh_CN": "来源图标",
      "zh_TW": "來源圖示",
      "en": "来源图标"
---------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "有道网页翻译2.0 加载无响应，\n可能扩展无权访问该页面，\n如加载成功请忽略本消息。",
      "zh_TW": "有道網頁翻譯2.0 下載後無反應，\n可能新視窗網頁無權訪問該網站，\n如果下載成功後，請忽略本訊息。",
      "en": "有道网页翻译2.0 加载无响应，\n可能扩展无权访问该页面，\n如加载成功请忽略本消息。"
-------------------------------------------------------------------------------------------------------------------
"message": {
      "zh_CN": "来自沙拉查词面板",
      "zh_TW": "來自沙拉查詞網頁(也可講，網站 )",
      "en": "来自沙拉查词面板"
--------------------------------------------------------------------------------------------------------------
 "message": {
      "zh_CN": "来自沙拉查词旧记录",
      "zh_TW": "來自沙拉查單字舊記錄",
      "en": "来自沙拉查词旧记录"

**Comment by stockyman** [comment]
以上的繁體程式碼 話句是
在台灣和香港比較生活化的講法。
跟中國大陸人使用的講法，有些差距和不太一樣！

請參考!!

謝謝!!

**Comment by crimx** [comment]
非常感谢！ :heart:

**Comment by crimx** [comment]
我会在下个版本的时候添加致谢的！不知道你希望用什么名称？用普通网名（如 stockyman）或者提供社交网络的联系方式都可以的

**Comment by crimx** [comment]
[新版](https://github.com/crimx/ext-saladict/wiki/Saladict6)已发布，感谢提供翻译！如有问题欢迎开新 issue 反馈。
