### ISSUE TITLE
在查词记录页面时，希望可以添加当前单词到生词本，而不是最后查词

### ISSUE THREAD

**Issue by GX1D** [crimx/ext-saladict#881]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Chrome83.0.4103.116] 
- 沙拉查词版本: [7.13.4] 

## 请描述目前使用沙拉查词遇到什么不便

在查词面板中，当连续查了几个词后，返回之前的查词记录，点击心形图标添加的生词是最后所查的词，而不是当前页面的词，这可能不太符合一般的使用意愿。
举例：
1.在一个页面上，我依次查询了“ If ”、“this ”、“doesn’t” 3个单词。
2.在“doesn’t”的页面，我通过点击“<”按钮，回到了“If”的页面。
3.此时我想添加“If”到生词本，所以点击心形图标，但是在保存编辑页面，显示的词却是“doesn’t” 。
4.在点击保存后，实际保存的词也是“doesn’t”。

## 理想情况下，沙拉查词应该怎么做

在上述举例步骤中，步骤3理想中应该是点击心形图标后，保存单词为“If”。此时搜索框和页面都是“If”的内容，保存单词为“If”更加符合直觉。

## 额外信息

非常感谢开发者开发出那么好的查词插件，对我日常帮助非常大，开发者辛苦了。

**Comment by crimx** [comment]
谢谢反馈，这是 bug

**Comment by GX1D** [comment]
作者回复效率好高啊😂因为我不懂程序，考虑之后没敢轻易报告为BUG
