### ISSUE TITLE
非常建议作者基于Electron制作windows版的桌面应用程序.exe。那样就perfect了！

### ISSUE THREAD

**Issue by RaySunWHUT** [crimx/ext-saladict#882]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: []

**Comment by crimx** [comment]
[常见问题与答复](https://saladict.crimx.com/q&a.html#%E9%97%AE%EF%BC%9A%E8%83%BD%E5%90%A6%E5%9C%A8-windows-mac-linux-ios-android-%E5%B9%B3%E5%8F%B0%E4%B8%8A%E5%AE%9E%E7%8E%B0%E5%8E%9F%E7%94%9F%E7%89%88%E6%9C%AC%E7%9A%84-saladict%E3%80%82)。
