### ISSUE TITLE
点击文本搜索框自动全选文字

### ISSUE THREAD

**Issue by Miranda201909** [crimx/ext-saladict#884]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 请描述目前使用沙拉查词遇到什么不便

独立窗口查词 - 点击文本搜索框 - 不能自动全选以前查过的文本。
因此只能：ctr+A全选之前查过的文本 - 粘贴新文本 - enter

[](url)

## 理想情况下，沙拉查词应该怎么做

点击文本搜索框 - 自动全选以前查过的文本 - 粘贴新文本 - enter

## 额外信息

> 会自动全选的。请点击一楼右上角三点按钮重新填写模板，提供问题具体复现步骤。能附上截图更好。

![image](https://user-images.githubusercontent.com/54886815/86552128-a9dcf680-bf79-11ea-8ff1-fbdc4f577627.png)
是不是独立查词窗口不能自动全选呢...

**Comment by crimx** [comment]
会自动全选的。请按右上角三点按钮重新按模板填写，提供问题具体复现步骤。能附上截图更好。

**Comment by Miranda201909** [comment]
虽然发现拷贝新文本后，转到沙拉查词界面，按F5即可自动显示新文本的译文，但是无法退回去查看之前文本的译文了。

**Comment by crimx** [comment]
是指独立窗口的查词面板？工具栏的历史记录只存在当前页面，刷新会丢失掉，在设置中开启记录查词历史可持久化保存到浏览器中，在查词历史页面可查看。

独立窗口可以响应浏览器页面划词，见[使用说明](https://saladict.crimx.com/manual.html)。如指浏览器外划词见[原理](https://saladict.crimx.com/native.html)。

**Comment by Miranda201909** [comment]
好的，感谢这么及时的回复。
插件很赞！！！

**Comment by crimx** [comment]
感谢更新了反馈。

点击即全选会造成无法通过鼠标调整光标位置，独立窗口打开以及查词后查词框都会自动获取焦点，直接粘贴即可。当然更快捷的方式是使用快捷键或者配合工具，见楼上说明。

**Comment by crimx** [comment]
~会造成无法通过鼠标调整光标位置~ 发现可以实现，会加入计划，感谢反馈。

**Comment by Miranda201909** [comment]
祝越办越好，拥有更多用户：D
