### ISSUE TITLE
搜狗的pid和key填了没用?就是翻译没有内容.偶尔有.

### ISSUE THREAD

**Issue by roguex686** [crimx/ext-saladict#885]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [360极速] 
- 沙拉查词版本: [7.13.4] 

## 描述问题

搜狗的pid和key填了没用?就是翻译没有内容.偶尔有.看了后台都没使用记录
用自己写的脚本去测试是可以使用的

**Comment by crimx** [comment]
打开 http://fanyi.sogou.com 看是不是被识别为机器人了。

**Comment by roguex686** [comment]
> 打开 http://fanyi.sogou.com 看是不是被识别为机器人了。

打开这个正常页面的.我用官方的文档改写自己的key也是能用的.感觉好像就是在沙拉里面设置了没启到效果.还是使用原来的公用的

**Comment by roguex686** [comment]
> 打开 http://fanyi.sogou.com 看是不是被识别为机器人了。

原来就是搜狗经常无法翻译出内容才去自己弄key.现在没有变化

**Comment by crimx** [comment]
这应该是 bug，感谢反馈

**Comment by roguex686** [comment]
> 这应该是 bug，感谢反馈

不好意思.我刚才下载了edge测试了一下.好像是360极速浏览器的bug.edge里正常.后台正常扣费,
同一时段360里没反应
