### ISSUE TITLE
想要一英一中加音标纯粹精简的生词本，没有哪个nativespeaker需要结合上下文，懂？非常感谢。

### ISSUE THREAD

**Issue by weehumph** [crimx/ext-saladict#886]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: []

**Comment by crimx** [comment]
> 想要一英一中加音标纯粹精简的生词本，没有哪个nativespeaker需要结合上下文，懂？非常感谢。

简单的同类型应用多的是，为何要来 4s 店抱怨买不到自行车？
