### ISSUE TITLE
同步扇贝生词本使用的 API 已废弃，需要调整

### ISSUE THREAD

**Issue by elonzh** [crimx/ext-saladict#889]
## 设备信息
- 操作系统: [Ubuntu 20.04 LTS] 
- 浏览器版本: [版本 83.0.4103.116（正式版本） （64 位）] 
- 沙拉查词版本: [7.13.4] 

## 描述问题

目前拓展使用的 API：

- http://www.shanbay.com/api/v1/bdc/search/ 
- http://www.shanbay.com/api/v1/bdc/learning/

需要替换成：

- GET https://apiv3.shanbay.com/abc/words/senses?vocabulary_content=<word>(查词)
- GET https://apiv3.shanbay.com/wordscollection/words_check?vocab_ids=<vocab_id>(检查生词本)
- POST https://apiv3.shanbay.com/wordscollection/words `{vocab_id: "<vocab_id>", business_id: 6}` (添加生词)

**Comment by crimx** [comment]
感谢反馈🙏

**Comment by elonzh** [comment]
效率真高，给你点赞
