### ISSUE TITLE
希望可以支持谷歌国内翻译

### ISSUE THREAD

**Issue by zishuangzhu** [crimx/ext-saladict#89]
使用相关的问题请确保先看了 Wiki 《划词翻译食用方式》 <https://github.com/crimx/crx-saladict/wiki> 。

不能划词的网站请提供具体链接。刚安装扩展后已经打开的页面需要刷新一遍以加载词典。

如果是查词结果不正确或无结果，请先点击结果左上的词典图标跳转到词典网页，查看是否为自身网络问题。

因安全问题，chrome 商店页面、自带的 PDF 页面以及其它扩展的页面是不能划词的。可用点击图标或三按 ctrl 快速查词，本扩展自带 PDF 阅读器。

一个好的反馈格式
===============

- 平台：包括操作系统和 Chrome 版本

- 类型：错误？建议？

- 重现：提供详细地操作来重现状况。

- 期待：理想情况下扩展应该怎么做？

- 实际：客观描述扩展实际上做了什么。

- 额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
右键支持，词典面板没有找到接口，所以不支持。
