### ISSUE TITLE
浏览器不是可以直接打开pdf吗，为什么一定要用阅读器才能翻译？

### ISSUE THREAD

**Issue by asgsdbrseg** [crimx/ext-saladict#890]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [星愿浏览器7.0.1000.2003] 
- 沙拉查词版本: [7.13.4] 

## 请描述目前使用沙拉查词遇到什么不便

在阅读器选一段，闪啊闪的，就自动选一整页了

## 理想情况下，沙拉查词应该怎么做

pdf文件选择用浏览器打开，选中后沙拉查词直接翻译

## 额外信息

浏览器打开的pdf不能直接使用沙拉查词，必须要用阅读器才行，但这个阅读器用着不行，老是自己选一页，希望沙拉查词能直接在浏览器查看pdf的界面调用。
如果不行，就优化一下阅读器吧，选中的时候精确一点。

**Comment by crimx** [comment]
https://saladict.crimx.com/notice.html#%E9%A2%84%E8%AE%BE
