### ISSUE TITLE
BUG: 实际的翻译引擎与选取的翻译引擎不一样

### ISSUE THREAD

**Issue by funsiyuan** [crimx/ext-saladict#891]
## 设备信息
- 操作系统: [windows 10] 
- 浏览器版本: [opera，chrome 83.0.4103.116 都有问题] 
![TIM截图20200708222834](https://user-images.githubusercontent.com/47549414/86924513-8af18680-c16a-11ea-89fa-d531bea6ef51.jpg)
- 沙拉查词版本: [7.13.4] 

## 描述问题

在翻译引擎出选取了谷歌和腾讯翻译
![TIM截图20200708222735](https://user-images.githubusercontent.com/47549414/86924616-a78dbe80-c16a-11ea-8524-2effcae49812.jpg)

实际出现的引擎还是默认的两个
![TIM截图20200708222755](https://user-images.githubusercontent.com/47549414/86924663-bc6a5200-c16a-11ea-8d95-f6ea0ef080bd.jpg)

## 期待的正常行为

在翻译引擎出选取了谷歌和腾讯翻译，
实际出现谷歌和腾讯翻译

**Comment by crimx** [comment]
见这个选项下方的说明。词典设置在「词典管理」标签下。
