### ISSUE TITLE
新版edge在开启“关闭后保持后台运行”后，使用quicker调用沙拉查词无反应

### ISSUE THREAD

**Issue by madokami1** [crimx/ext-saladict#892]
## 设备信息
- 操作系统: [win10] 
- 浏览器版本: [edge最新版] 
- 沙拉查词版本: [v7.13.4] 

## 描述问题

新版edge在开启“关闭后保持后台运行”后，使用quicker调用沙拉查词无反应

## 复现步骤

打开edge，使用quicker调用沙拉查词正常使用，确保“关闭后保持后台运行”打开后，关闭edge，再次调用无反应

## 期待的正常行为

“关闭后保持后台运行”打开后，关闭edge，可以正常用quicker使用沙拉查词

**Comment by hqyyqh** [comment]
> 新版 edge 在开启 “关闭后保持后台运行” 后，使用 quicker 调用沙拉查词无反应

任务栏是否有显示浏览器图标？装个[后台运行](https://chrome.google.com/webstore/detail/background-process/alobgnedpnalbocldljnakbbaemakhih)扩展看看。

**Comment by 20171587wangyubin** [comment]
> > 新版 edge 在开启 “关闭后保持后台运行” 后，使用 quicker 调用沙拉查词无反应
> 
> 任务栏是否有显示浏览器图标？装个[后台运行](https://chrome.google.com/webstore/detail/background-process/alobgnedpnalbocldljnakbbaemakhih)扩展看看。

无浏览器图标。安装后有了，可以正常调用。感谢

**Comment by crimx** [comment]
感谢反馈！沙拉查词下个版本更新后不需要再安装后台运行了。

**Comment by madokami1** [comment]
> 感谢反馈！沙拉查词下个版本更新后不需要再安装后台运行了。

好的。请问沙拉查词是自动更新吗？还是使用时弹出更新提示

**Comment by crimx** [comment]
在商店安装的都会自动更新。

**Comment by madokami1** [comment]
> 在商店安装的都会自动更新。

现在更新了。关闭后台运行后quicker直接提示没有可以用沙拉查词的浏览器

**Comment by hqyyqh** [comment]
> > 在商店安装的都会自动更新。
> 
> 现在更新了。关闭后台运行后 quicker 直接提示没有可以用沙拉查词的浏览器

版本 v7.14.0 测试沙拉查词常驻后台正常，可以检查你的浏览器有没有运行。

![image](https://user-images.githubusercontent.com/38676455/87219543-ba80d880-c38e-11ea-99fb-d3222c5829f9.png)

![image](https://user-images.githubusercontent.com/38676455/87219512-7392e300-c38e-11ea-8343-f7aeed435e49.png)

**Comment by madokami1** [comment]
> > > 在商店安装的都会自动更新。
> > 
> > 
> > 现在更新了。关闭后台运行后 quicker 直接提示没有可以用沙拉查词的浏览器
> 
> 版本 v7.14.0 测试沙拉查词常驻后台正常，可以检查你的浏览器有没有运行。
> 
> ![image](https://user-images.githubusercontent.com/38676455/87219543-ba80d880-c38e-11ea-99fb-d3222c5829f9.png)
> 
> ![image](https://user-images.githubusercontent.com/38676455/87219512-7392e300-c38e-11ea-8343-f7aeed435e49.png)

我这是7.13.4，没有更新。开启那个选项后edge依然不会后台运行。借助之前的插件可以

**Comment by hqyyqh** [comment]
> 我这是 7.13.4，没有更新。开启那个选项后 edge 依然不会后台运行。借助之前的插件可以

那等更新就行。chrome 商店已经更新了，Edge 商店由 @rumosky 维护，更新可能会迟一点。

**Comment by crimx** [comment]
Edge 审核一般需要几天时间，所以会晚些。

**Comment by rumosky** [comment]
edge商店都是和Chrome同步更新的，只是edge人工审核比较慢，所以会晚Chrome几天，请耐心等待一下。

**Comment by madokami1** [comment]
> > 我这是 7.13.4，没有更新。开启那个选项后 edge 依然不会后台运行。借助之前的插件可以
> 
> 那等更新就行。chrome 商店已经更新了，Edge 商店由 @rumosky 维护，更新可能会迟一点。

试着下载了chorme的7.14.5版本，关闭edge后edge还是不会在后台运行。那个后台运行的选项已经打开了

**Comment by crimx** [comment]
有没有在沙拉查词设置开启「后台保持运行」，7.14.5 将这个设为可选了，因为不是所有人需要这个功能。
