### ISSUE TITLE
关于源码中 google 翻译

### ISSUE THREAD

**Issue by demoshang** [crimx/ext-saladict#893]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 描述问题

看源码 使用的是 `@opentranslate/google`, 但是需要使用 `GOOGLE_TOKEN`, 但是好像没有实现
而本地尝试build 使用的话  google 翻译为空, 需要设置什么吗? 谢谢~

**Comment by crimx** [comment]
不清楚，我有空测试一下什么情况

**Comment by crimx** [comment]
之前本地环境有点乱现在整理重新同步一遍，pull 一下应该可以。
