### ISSUE TITLE
请求增加添加生词本面板中【关闭自动填写翻译功能】选项

### ISSUE THREAD

**Issue by SKEETCHAN** [crimx/ext-saladict#894]
## 设备信息
- 操作系统Window10
- 浏览器版本: edge 版本 83.0.478.58
- 沙拉查词版本: 7.13.4

## 请描述目前使用沙拉查词遇到什么不便
谷歌百度等翻译引擎的的答案并不是最贴切的翻译，这里的翻译还是需要手动填写；以前都是自己手动填写的，但是突然一两个月，查询生词后点击添加生词本，生词本会直接把这个词的含义加到里面，每次我都要全选删除掉，再自行添加翻译，十分不便

## 理想情况下，沙拉查词应该怎么做
增加手动关闭功能

## 截图

![image](https://user-images.githubusercontent.com/40740405/87063860-79c77900-c241-11ea-89ee-88a957fed882.png)

**Comment by crimx** [comment]
[使用说明](https://saladict.crimx.com/manual.html)。设置👉单词管理👉取消勾选上下文翻译引擎。

**Comment by SKEETCHAN** [comment]
取消上下文翻译引擎，也仍然会自动翻译。
具体情况，已附视频 ， [点此查看](https://www.lycheebar.tk/#/s/PoCO/video?name=2020-07-11%2001-58-08.mkv)

**Comment by crimx** [comment]
> 取消上下文翻译引擎，也仍然会自动翻译。

不会的。

> 具体情况，已附视频 ， 点此查看

视频挂了。
