### ISSUE TITLE
划词图标遮挡网页内容的问题

### ISSUE THREAD

**Issue by 4zzy** [crimx/ext-saladict#896]
主要出现在两个地方:
1. 输入框内划词后删除准备输入新内容时图标不会自动消失, 造成对后续输入内容的遮挡;
2. 划词后上下滚动网页图标不会随网页滚动或者消失, 而是留在屏幕原位置, 对后续浏览内容造成遮挡.

这两个问题虽然都有间接的解决方法, 但每次遇到还是很不自在.

**Comment by crimx** [comment]
1. 设置👉查词习惯👉不在输入框划词。[使用说明](https://saladict.crimx.com/manual.html)。
2. Esc 或点击面板外部区域。
