### ISSUE TITLE
文本过长时，部分翻译无法正常调用

### ISSUE THREAD

**Issue by madokami1** [crimx/ext-saladict#897]
## 设备信息
- 操作系统: [win10] 
- 浏览器版本: [edge最新] 
- 沙拉查词版本: [7.13.4] 

## 描述问题

目前测试了百度翻译、彩云小译、腾讯翻译、谷歌翻译。
翻墙，文章过长时。腾讯翻译瞬间完成部分文本，谷歌显示空白，剩下两个翻译一会后无显示。
不翻墙，文章过长时。腾讯翻译瞬间完成部分文本，谷歌显示空白，彩云小译瞬间完成所有文本，百度翻译
翻译一会后无显示。

## 期待的正常行为

可能的话希望修复翻墙时彩云小译无法翻译的问题。其他问题可能是接口有字数限制，但彩云小译不翻墙可以翻墙反而不行我是真的迷惑。因为我上的网站需要翻墙......

**Comment by crimx** [comment]
你好，沙拉查词的设计主要围绕「查词」，过长文本目前不在计划上，建议换用其它网页翻译应用。

> 翻墙时彩云小译无法翻译的问题

目前主流的梯子都支持绕过国内ip，可以去看看你的梯子的使用说明。
