### ISSUE TITLE
一定要在后台运行吗？

### ISSUE THREAD

**Issue by MerrickZ** [crimx/ext-saladict#899]
![image](https://user-images.githubusercontent.com/1021332/87235952-1726d680-c415-11ea-98b0-c745e6fe54f9.png)
能禁掉这个功能吗？我觉得查词的应用没有必要常驻后台。

**Comment by crimx** [comment]
#892 不需要取消勾选就行。

**Comment by crimx** [comment]
7.14.4 已添加设置管理后台运行权限。
