### ISSUE TITLE
PDF模式下，某些PDF文件无法识别空格，导致无法翻译

### ISSUE THREAD

**Issue by voouvo** [crimx/ext-saladict#90]
- 平台：
操作系统：Windows 7 with SP1 64bit
浏览器：Chrome 59.0.3071.115（正式版本） （64 位）

- 类型：错误

- 重现：
虽然某些本地PDF文件用此扩展自带的PDF阅读器能正常划词翻译，但是有一些PDF文件用此扩展自带的PDF阅读器无法识别单词之间的空格，导致无法翻译。如果切换成Chrome的PDF阅读器，原本无法识别空格的文件，在划词右键“沙拉查词-网页划词翻译→谷歌翻译”，在弹出的谷歌翻译页面中，单词之间能正常地用空格断开，能正常翻译。
能正常翻译和不能翻译的PDF文档已上传到百度云盘：
链接: https://pan.baidu.com/s/1n0yPscuDCUblbWF4c8Aeqg 密码: 6eu2

**Comment by voouvo** [comment]
我用迂回的方法算是解决了。把无法正常选词的PDF文档转换成html格式，用浏览器打开。优点是可以全屏翻译，缺点是排版变了，全部页面变成一页，不知道怎么标记标签

**Comment by crimx** [comment]
[新版](https://github.com/crimx/ext-saladict/wiki/Saladict6)已更新 pdf.js，如有问题欢迎开新 issue 反馈。
