### ISSUE TITLE
建议去掉高危权限【修改您复制和粘贴的数据】

### ISSUE THREAD

**Issue by stfenjobs** [crimx/ext-saladict#900]
## 设备信息
- 操作系统: [] mac
- 浏览器版本: [] chrome
- 沙拉查词版本: [] 最新版

## 请描述目前使用沙拉查词遇到什么不便

新版请求高危权限 【修改您复制和粘贴的数据】

## 理想情况下，沙拉查词应该怎么做

建议去掉高危权限【修改您复制和粘贴的数据】

## 替代方案a!-- (可选)如果你已经有了能用的替代方案，或者对沙拉查词具体如何实现有建议 -->
无

## 额外信息

![image](https://user-images.githubusercontent.com/6580897/87242508-eae47780-c45f-11ea-8184-d7ea5f59c1df.png)

**Comment by librix** [comment]
这个权限被用来做什么？

**Comment by crimx** [comment]
读取是一直都有的，现在是多了写入，因为目前的设计不能用户交互来申请这个权限，所以写死了。没考虑到更新会弹出这个提示比较影响体验，看来需要另外设置页面让用户自行开启。

读取是打开独立窗口时获取查词，写入是新版支持直接复制机器翻译原文和译文。

**Comment by crimx** [comment]
7.14.4 已添加设置管理剪贴板权限。

**Comment by xiecang** [comment]
请问为什么新版本需要写入剪切板的权限？

**Comment by crimx** [comment]
读楼上

**Comment by newpost** [comment]
也就是说读取权限选项就算是disabled,也可以读取剪贴板吗？ @crimx

**Comment by crimx** [comment]
> 也就是说读取权限选项就算是disabled,也可以读取剪贴板吗？ @crimx

当然是不行的……不然加这个选项做什么😂

**Comment by crimx** [comment]
也许有其它手段可以绕过权限获取剪贴板信息，但沙拉查词[只用扩展官方提供的 API](https://github.com/crimx/ext-saladict/blob/dev/src/background/clipboard-manager.ts)，不会暗戳戳读取。
