### ISSUE TITLE
现有的《国语辞典》中有多余的英文翻译

### ISSUE THREAD

**Issue by gabkm** [crimx/ext-saladict#902]
## 设备信息
- 操作系统: [Windows 10] 
- 浏览器版本: [Chrome 83] 
- 沙拉查词版本: [v7.14.5] 

## 请描述目前使用沙拉查词遇到什么不便

《国语辞典》中有英文注解，但是在“[教育部重编国语辞典修订本](http://dict.revised.moe.edu.tw/cbdic/)”网站上并没有英文的解释；经验证，其为来自“[汉典](https://www.zdic.net/)”的的英文注释。

“汉典”中也有来自《国语辞典》的注解，所以没有必要让两个辞典具有很高的相似度（因为《国语辞典》专注中文，所以也没有额外的必要有英文的解释和翻译）。

## 理想情况下，沙拉查词应该怎么做

希望可以删除并非来自《国语辞典》的英文内容。

**Comment by crimx** [comment]
感谢反馈
