### ISSUE TITLE
对于某些网页翻译对话框不自动弹出，比如这个：https://www.techug.com/post/dark-history-of-unix-linux-and-windows.html

### ISSUE THREAD

**Issue by hongyi-zhao** [crimx/ext-saladict#904]
对于某些网页，对于某些网页翻译对话框不自动弹出，比如这个：https://www.techug.com/post/dark-history-of-unix-linux-and-windows.html

该问题对于Firefox、chrome插件同时存在。

**Comment by crimx** [comment]
感谢反馈，是因为被网页强制隐藏了，下个版本之前可以用独立窗口快捷查词响应。
