### ISSUE TITLE
当读取剪贴板失败时，打开插件设置页的行为导致查词面板隐藏

### ISSUE THREAD

**Issue by iamgqb** [crimx/ext-saladict#905]
## 设备信息
- 操作系统: Window10
- 浏览器版本: 83.0.4103.116
- 沙拉查词版本: 7.14.5

## 请描述目前使用沙拉查词遇到什么不便
新版本加入权限管理后，如果进行如下设置：
1、在右上弹框中设置显示词板并预载剪贴板 或者 
2、在权限管理中关闭剪贴板
![image](https://user-images.githubusercontent.com/2213424/87452509-e07ad700-c633-11ea-9b17-116ee1fa293d.png)
![image](https://user-images.githubusercontent.com/2213424/87452564-ee305c80-c633-11ea-8f02-11d317c9464b.png)

如此设置后，点击插件icon，由于插件内写死了当没有获取到剪贴板权限时，自动跳转插件权限管理设置页
[clipboard-manager](https://github.com/crimx/ext-saladict/blob/dev/src/background/clipboard-manager.ts#L24)。导致正常的查词弹框无法显示。
（或者说因为页面跳转导致查词弹框隐藏）

## 替代方案

建议
- 可以静默处理没有授权剪贴板时的行为，直接返回空串
- 在关闭剪贴板授权时清理其他涉及剪贴板的设置为无

**Comment by crimx** [comment]
感谢反馈。你建议的方式我当然有想过，就是事儿太多的用户我已经不太想再浪费时间处理了。

涉及剪贴板权限的设置默认关闭的，弹过一次应该知道是什么回事，让他们自行去调整吧！

**Comment by crimx** [comment]
感谢反馈。静默处理会导致用户以为功能失效了，所以必须弹出来。

剪贴板相关的设置默认是关闭的，可以在用户保存修改时做出相应的引导。
