### ISSUE TITLE
希望增加【自动翻译】

### ISSUE THREAD

**Issue by Alphabet1226** [crimx/ext-saladict#906]
#170  
## 请描述目前使用沙拉查词遇到什么不便

不支持自动翻译生词。

## 理想情况下，沙拉查词应该怎么做

阅读时，当生词表中的单词再次出现时，将翻译显示在生词的右边 。

## 替代方案

可以参考ios上的“蒙哥阅读器”和“小A阅读”。

**Comment by crimx** [comment]
感谢反馈。与 #895 类似，这是一个大坑，需要较多时间设计，目前没有计划去碰用户的页面。
