### ISSUE TITLE
希望更改Anki模板和增加柯林斯词典新功能

### ISSUE THREAD

**Issue by eryisan** [crimx/ext-saladict#909]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 额外信息

第一次提issue,有什么不对的地方请指正,或删除,谢谢!
非常感谢作者开发!已打赏!

以下是结合个人经验,给出的更改Anki模板建议和增加新功能想法.
如可采纳最好,不采纳也是正常.
目前沙拉查词Anki模板是:
1__填空题(上下原文)
2__中文翻译
3__笔记
4__提示

沙拉查词anki文档中视频:我们10多年的外语教学的方法几乎全错了
视频理念是:
1_看单词的英语解释
2_多看例句体会意思
3_选择常用简单句
4_看句子想场景

目前模板最大弊端是:
1_看中文意思,用中文理解英文
2_模板填空题下直接显示中文翻译,用中文去"有意识地思考"记住英文单词.don't think,feel.

个人建议更改模板样式和增加柯林斯词典新功能:
1__单词 音标 发音(自动发音)
2__上下原文(,单词发音完例句自动发音. 点击显示中文翻译)
3__柯林斯词典英英释义(英语解释英语,点击显示中文意思)  这里作为卡片背面,按显示答案按钮后显示

这个过程就会变为:
看单词_看例句_看单词英文释义_不懂点击显示中文释义_例句不懂点击显示中文翻译
结合Anki不断重复读看,后期基本已经不用点击显示中文释义就能体会到例句意思.就能想到场景.
这里输入的过程就达到了.至于输出打出字写和改单词造句说句子就不是Anki能做的事了.

优势:
单词,例句,解释全英文.用英语理解英语.
不再用中文去有意识思考记住单词.

参考:
chorme插件 在线词典助手anki模板

实用价值:
学英语方法和思维的改变.
学编程英文单词效果好,受众效果好.

程序员学编程英语的过程变为:
1__看单词
2__看上下原文例句(学英语的过程,还把编程文档的原文例句重复巩固,扎实程序员的英语和编程基础)

附注:
不知道这样讲合不合适 会不会冒犯到作者,先说声抱歉.
这个功能我愿意打赏¥400-800开发!
第一次提issue,如果此issue不合规和给作者带来困扰,请删除此issue,我并致歉!谢谢.

**Comment by crimx** [comment]
你好，谢谢你用心的反馈以及支持！

> 目前模板最大弊端是:
> 1_看中文意思,用中文理解英文
> 2_模板填空题下直接显示中文翻译,用中文去"有意识地思考"记住英文单词.don't think,feel.

中文翻译是用来作为辅助提示的，沙拉查词的设计是 _输入_：英语上下文，_输出_：英文单词。

> 个人建议更改模板样式和增加柯林斯词典新功能:
> 1__单词 音标 发音(自动发音)
> 2__上下原文(,单词发音完例句自动发音. 点击显示中文翻译)
> 3__柯林斯词典英英释义(英语解释英语,点击显示中文意思) 这里作为卡片背面,按显示答案按钮后显示

目前沙拉查词的建议是用户可以在「翻译」或者「笔记」中**手动**输入/复制单词在当前上下文中**唯一**的解释。如果直接贴上「柯林斯词典英英释义」那么_输出_中将充斥大量冗余信息，不符合 Anki 建议的 SuperMemo 中的[最小信息](https://www.supermemo.com/en/articles/20rules#minimum%20information%20principle)原则。当然这个流程还有许多可以优化的地方，如有合适的建议我是非常愿意探讨的。

**Comment by eryisan** [comment]
谢谢作者，受教了。
