### ISSUE TITLE
本插件的pdf.js各种paper的PDF路径无法正常识别

### ISSUE THREAD

**Issue by zhangchenkai** [crimx/ext-saladict#91]
- 平台：mac 10.13.3 chrome 65.0
- 类型：很多论文的链接无法正确解析使用内置的pdf.js打开，会使用默认pdf浏览器打开
- 重现：
例如 IEEE 某期刊一篇[文章](http://ieeexplore.ieee.org/document/7113786/)，点击页面Download PDF
- 问题：
之前用到的另一款插件“划词翻译”集成的pdf.js和官方插件[PDF Viewer](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm/related)都可以用正常使用pdf.js打开；
并且在链接页面，使用邮件pdf打开，仍然不行，并且会报错
- 期待：
希望能够尽快改进一下

**Comment by crimx** [comment]
这是因为有的网站下载时链接隐藏了 pdf 后缀，要嗅探的话每一次网页请求都需要拦截。我原来是洁癖取消的，具体如何实现待我实验对比之后再做决定，或许会加个开关，或许默认实现。

**Comment by crimx** [comment]
[新版](https://github.com/crimx/ext-saladict/wiki/Saladict6)已修复，如有问题欢迎开新 issue 反馈。
