### ISSUE TITLE
How can I use ext-saladict as a stand-alone tool besides as a plug-in for browsers.

### ISSUE THREAD

**Issue by hongyi-zhao** [crimx/ext-saladict#910]
Hi,

On Ubuntu 20.04, I want to let ext-saladict grab the words and translate them from the normally opened documents, say, pdf, doc(x) ( with wps Linux version), etc., instead from within browser. Any hints for this job?

Regards,
HY

**Comment by crimx** [comment]
See [manual](https://saladict.crimx.com/en/native.html). I personally use global shortcuts all the time which is quite enough for me. If you know how to automate this process on Linux please let me know.

**Comment by hongyi-zhao** [comment]
Thanks a lot this instruction. It seems this method need to run the browser as daemon at background. That means that ext-saladict in itself is designed to work with browser. So, based on this mode, I'm afraid that there is no automate methods on Linux which can do the job with less resource consumption.

**Comment by crimx** [comment]
Saladict is developed with web stack. Depending on browser should cost less comparing to electron, unless you don't use browser at all.

**Comment by hongyi-zhao** [comment]
Thanks for your comments again. Basically, it seems that the solution for this problem is running chrome as the daemon for out-of-browser mode and at the meanwhile using other browsers, if necessary, say, Firefox, for doing the job during web-surfing.

**Comment by crimx** [comment]
If you use Firefox then unfortunately currently only Firefox does not support extension global shortcuts. For other browser it is not necessary to run as a daemon unless you turn on background mode.

**Comment by hongyi-zhao** [comment]
> For other browser it is not necessary to run as a daemon unless you turn on background mode.

Does this mean, if I don't turn on background mode, I must use ext-saladict with the global shortkey when the browser has been opened?

**Comment by crimx** [comment]
Yes.

**Comment by hongyi-zhao** [comment]
So, the problem is when you run the browser as daemon firstly and subsequently, you may be want to open the browser for some online job. In this case, the daemon and the later opened browser progress will be two different instances or not?

**Comment by crimx** [comment]
I am not sure. I would guess they are the same. I don't see any significant changes on memory.
