### ISSUE TITLE
Socks5 proxy support of ext-saladict.

### ISSUE THREAD

**Issue by hongyi-zhao** [crimx/ext-saladict#911]
Hi,

I see the socks5 proxy settings template [here](https://github.com/crimx/ext-saladict/blob/40abbbc884f6ac3fba44e9423e9d4887048e91e0/.env.example#L27), but I can't find any corresponding settings on the options panel of ext-saladict.

OTOH, for my case, I use [SwitchOmega](https://github.com/FelisCatus/SwitchyOmega) to set the socks5 proxy for Firefox and it seems that ext-saladict will automatically use the socks5 proxy via SwitchyOmega.

Any hints for the socks5 proxy setting method supported by ext-saladict currently?

Regards,
HY

**Comment by crimx** [comment]
The dotenv `.env` file is for building saladict from source(See README.md). Proxy in browser can only be controlled by one extension, SwitchOmega in your case. All the traffics will go through this extension, even from other extensions.

**Comment by hongyi-zhao** [comment]
> The dotenv `.env` file is for building saladict from source(See README.md).

Do you mean the socks5 proxy there is just for pulling stuff relative to or used by ext-saladict during the compiling process?

**Comment by crimx** [comment]
Yes.

**Comment by hongyi-zhao** [comment]
If so, why not using the socks5 proxy set for yarn?

**Comment by crimx** [comment]
AFAIK yarn proxy is for connecting package registries. Proxy setting in the dotenv is also for downloading testing assets. See CONTRIBUTING.md.

**Comment by hongyi-zhao** [comment]
Thanks a lot, got it.
