### ISSUE TITLE
快捷键不好使，经常按下后不会正确响应。

### ISSUE THREAD

**Issue by xxyyy159** [crimx/ext-saladict#913]
## 设备信息
- 操作系统: [win8.1] 
- 浏览器版本: [chrome84] 
- 沙拉查词版本: [v7.1] 

## 描述问题

我设置了ctrl+0作为加入生词本的快捷键，经常99%的情况下无法使用，表现为：按下后无任何反应。只有更换快捷键后才能生效，但是又会出现选中的和加入的单词不一致的问题，截图在下面。

## 截图

![捕获](https://user-images.githubusercontent.com/43295237/87850296-93438180-c921-11ea-9f2f-193593434ccc.PNG)

**Comment by xxyyy159** [comment]
重新下载chrome和重新安装saladict都无法解决这个问题

**Comment by crimx** [comment]
ctrl+数字 是浏览器自带的切换标签快捷键，应该是这个原因不能用来设置其它快捷键。

添加单词不对是因为目前的逻辑是添加查词面板上的查词而不是最新的划词。这个我看一下能不能优化。

**Comment by xxyyy159** [comment]
因为我是利用鼠标宏调用goldendict的快捷键查词的，而saladict用来记录单词所在的例句，所以我会希望选中单词后直接能通过加入生词本快捷键来完成。

还有两个小建议：

1：能否优化下代码，把查词时候多选的标点符号自动去除

2：在导出生词本处，可否增加导出为excel文件，让单词，例句，翻译按照 行 展开，不然txt的文件，对处理数据不太方便。

**Comment by xxyyy159** [comment]
我找到了个解决方法，就是打开自动搜索，然后把查词面板的高度设置为0，那样按下快捷键可以保存生词本，同时单词被选中后不会出现saladict的界面。

**Comment by crimx** [comment]
> 能否优化下代码，把查词时候多选的标点符号自动去除

不同人想的“多余”可能都不一样，为了简单起见沙拉查词倾向不处理。

> 在导出生词本处，可否增加导出为excel文件，让单词，例句，翻译按照 行 展开，不然txt的文件，对处理数据不太方便。

你可以按 csv 格式导出，Excel 也是可以读的。

> 我找到了个解决方法，就是打开自动搜索，然后把查词面板的高度设置为0，那样按下快捷键可以保存生词本，同时单词被选中后不会出现saladict的界面。

沙拉查词会改成直接保存最新的划词。

**Comment by xxyyy159** [comment]
能否告知下csv格式如何导出？我翻阅了使用手册，都没有提到。目前只能txt导出。
还有这个预览的框框怎么是深色的，看不清。
![捕获](https://user-images.githubusercontent.com/43295237/87852147-0e149880-c932-11ea-93cb-0acba5c4c150.PNG)

**Comment by crimx** [comment]
CSV 也是一种纯文本格式。简单说就是按 `,` 分割，你可以搜索一下格式。如模板改为 `%text%,%context%`。

> 还有这个预览的框框怎么是深色的，看不清。

有没有安装了什么美化插件？否则请提供出现问题的页面以供排查。

**Comment by crimx** [comment]
另外我注意到你填写的沙拉查词版本为 `v7.1` 目前最新版为 `v7.14.5`。

**Comment by xxyyy159** [comment]
多谢！
