### ISSUE TITLE
When enabled this plug-in, the pdf file opened in browser will have a very stranage URL.

### ISSUE THREAD

**Issue by hongyi-zhao** [crimx/ext-saladict#914]
Hi,

I noted that, with ext-saladict installed for the browser, the pdf file opened online will have a very stranage URL. Say, something like the folloiwng: `moz-extension://b892d156-6061-4a1e-9300-36b4e92a4fb5/assets/pdf/web/viewer.html?file=https%3A%2F%2Fgvallverdu.gitbooks.io%2Ftp-etat-solide%2Fcontent%2FNi%2FSetyawan2010.pdf
`

Any hints for this problem?

Regards,
HY

**Comment by crimx** [comment]
Saladict comes with its own PDF.js viewer.

1. You may turn off Saladict PDF url sniffing and open PDFs with other viewer. But then you will lose the ability to search text on PDF with Saladict. And in Firefox there is no other way to achieve that.
2. Saladict offers a context menus option for copying the original url.

**Comment by hongyi-zhao** [comment]
Thanks a lot for your valuable comments.
