### ISSUE TITLE
柯林斯高阶词典不再显示中文了

### ISSUE THREAD

**Issue by Angingun** [crimx/ext-saladict#915]
## 设备信息
- 操作系统: [Windows10] 
- 浏览器版本: [chromium edge 84] 
- 沙拉查词版本: [7.14.5] 

## 请描述目前使用沙拉查词遇到什么不便

很久以前柯林斯高阶词典是中英双解的，但是最近似乎没有中文了。目前沙拉查词里似乎没有传统意义上权威的中英双语词典了

## 理想情况下，沙拉查词应该怎么做

添加上中文释义，或者增添上其他的中英双解词典。比如朗文双解，21世纪英汉词典

**Comment by crimx** [comment]
谢谢反馈，词典服务器换了新版，沙拉查词下版会跟进。
