### ISSUE TITLE
opera最新版一点保存选项就显示---权限“background”申请失败。

### ISSUE THREAD

**Issue by yigexuezha** [crimx/ext-saladict#916]
## 设备信息
- 操作系统: win10
- 浏览器版本: 69.0.3686.77 
- 沙拉查词版本: 7.14.5

## 描述问题

opera最新版一点保存选项就显示---权限“background”申请失败。 
用三月版本保存没问题，但关了自动更新还是给更到最新版，又不能用了

## 期待的正常行为

保存选项

**Comment by crimx** [comment]
打开设置，有取消勾选保持在后台运行吗？

**Comment by yigexuezha** [comment]
> 打开设置，有取消勾选保持在后台运行吗？

保持在后台运行 是关着的。
当前无法更改任何设置，点保存就弹权限失败

**Comment by crimx** [comment]
看来 Opera 对这个权限进行了魔改。会把它去掉。

**Comment by funsiyuan** [comment]
same issues here
