### ISSUE TITLE
All spaces among the words are left out when extract text from this online pdf file: http://inside.mines.edu/~zhiwu/research/slides/B03_kpt.pdf

### ISSUE THREAD

**Issue by hongyi-zhao** [crimx/ext-saladict#918]
Hi,

The environment is Ubuntu 20.04 + Firefox + the latest version of ext-saladict. When I open this [file](http://inside.mines.edu/~zhiwu/research/slides/B03_kpt.pdf) in firefox and use ext-saladict to extract the text from it for translation, I find that all of the spaces are omitted in the grabbed text by ext-saladict, say, `Lineartetrahedronmethod` whose original form in the pdf file is `Linear tetrahedron method`.

Any hints for this problem?

Regards,
HY

**Comment by crimx** [comment]
Please read the [Read It Before Use](https://saladict.crimx.com/en/notice.html#limitations) before using Saladict.

**Comment by hongyi-zhao** [comment]
> Please read the [Read It Before Use](https://saladict.crimx.com/en/notice.html#limitations) before using Saladict.

Thanks for directing me there. But is it possible to overcome these limitations?

**Comment by crimx** [comment]
> But is it possible to overcome these limitations in the future?

It's up to PDF.js. I think it's not likely to be fixed since PDF does not care semantics by design.
