### ISSUE TITLE
WebDAV 单词同步问题

### ISSUE THREAD

**Issue by WangShuoran** [crimx/ext-saladict#919]
在我使用WebDAV配合坚果云使用的时候就会报出
![image](https://user-images.githubusercontent.com/43474491/87925312-adf93000-cab2-11ea-9d75-d372edc76689.png)
这样的问题，我没有什么头绪，而且找不出什么相关的设置，在我的坚果云上也有沙拉查词的文件夹(我是按照帮助一步一步的设置的)
但我愿意提供任何信息来解决我的问题，我爱沙拉

**Comment by crimx** [comment]
坚果云上有文件夹的话那应该是可以的。你设置的坚果云链接是怎样的。点击「验证服务器」会出现什么结果。

**Comment by WangShuoran** [comment]
![image](https://user-images.githubusercontent.com/43474491/88184036-d0cb4600-cc64-11ea-83d1-d9679a5fa91a.png)
![image](https://user-images.githubusercontent.com/43474491/88184140-eccee780-cc64-11ea-918f-b72c1349a0ab.png)
看起来没有任何问题，有没有可能是代理的问题？

**Comment by crimx** [comment]
那应该没有问题的，你保存一个单词试试。

**Comment by WangShuoran** [comment]
还是一样的错误

**Comment by crimx** [comment]
我测试了一遍是没有问题，如果你觉得可能是代理的问题可以关闭代理测试一下。

**Comment by WangShuoran** [comment]
很高兴，关闭代理后是可以上传数据成功，但是我在想只需要把上传的域名改为直连就不会出错，所以不知道沙拉如何传给坚果云的数据

**Comment by crimx** [comment]
就是这个域名

**Comment by WangShuoran** [comment]
你是指那个？是坚果云的域名吗？还是？

**Comment by crimx** [comment]
是的，你填的那个
