### ISSUE TITLE
打开翻译窗 搜索单词 将结果双击选中复制 会一直搜索

### ISSUE THREAD

**Issue by middddd** [crimx/ext-saladict#92]
使用相关的问题请确保先看了 Wiki 《划词翻译食用方式》 <https://github.com/crimx/crx-saladict/wiki> 。

不能划词的网站请提供具体链接。刚安装扩展后已经打开的页面需要刷新一遍以加载词典。

如果是查词结果不正确或无结果，请先点击结果左上的词典图标跳转到词典网页，查看是否为自身网络问题。

因安全问题，chrome 商店页面、自带的 PDF 页面以及其它扩展的页面是不能划词的。可用点击图标或三按 ctrl 快速查词，本扩展自带 PDF 阅读器。

一个好的反馈格式
===============

- 平台：包括操作系统和 Chrome 版本

- 类型：错误？建议？

- 重现：提供详细地操作来重现状况。

- 期待：理想情况下扩展应该怎么做？

- 实际：客观描述扩展实际上做了什么。

- 额外信息：提供额外信息以便定位问题，如在出现错误的页面按 F12 ，截图 console 标签下的错误信息。

**Comment by crimx** [comment]
这不是 bug ，如果需要复制的话可以滑动选择，或者选上面搜索框的文字。

**Comment by zoffyzhang** [comment]
我的习惯也是在翻译窗口双击结果然后复制，滑动选择的效率有点低了，希望可以改进

**Comment by crimx** [comment]
嗯，这个功能在 6 中不实现了，也省事 :smile:

**Comment by crimx** [comment]
[新版](https://github.com/crimx/ext-saladict/wiki/Saladict6)已发布，如有问题欢迎开新 issue 反馈。
