### ISSUE TITLE
点击沙拉查词，直接跳转到了扩展程序设置页面

### ISSUE THREAD

**Issue by AlanCutFlim** [crimx/ext-saladict#920]
## 设备信息
- 操作系统: [macos catelina 10.15.4 ] 
- 浏览器版本: [Chrome87] 
- 沙拉查词版本: [7.14.5] 

## 描述问题

点击扩展程序栏沙拉查词按钮，没有停留在查词弹窗，而是直接跳转到扩展程序设置界面

## 复现步骤

在右上角扩展程序栏点击沙拉查词

## 期待的正常行为

查词弹窗正常显示，不会跳转到扩展程序设置页面

## 截图

![U5PRTH.gif](https://s1.ax1x.com/2020/07/20/U5PRTH.gif)

**Comment by crimx** [comment]
你开启了右上弹框自动加载剪贴板，但是没有给权限。

**Comment by AlanCutFlim** [comment]
感谢，已解决
