### ISSUE TITLE
建议使用google.cn而不是google.com的api

### ISSUE THREAD

**Issue by ifyr** [crimx/ext-saladict#921]
## 设备信息
- 操作系统: [Windows10] 
- 浏览器版本: [Edge84] 
- 沙拉查词版本: [7.14.5] 

## 请描述目前使用沙拉查词遇到什么不便

谷歌查词需翻墙，谷歌相关功能墙内都不可用

## 理想情况下，沙拉查词应该怎么做

建议改成google.cn，相关api都在墙内可用的。

## 替代方案

使用translate.google.cn

## 额外信息

所有 https://developer.android.com/ 开头的地址，
直接改成 https://developer.android.google.cn/ 墙内即可访问。

**Comment by crimx** [comment]
你是指右键菜单吗，在设置里选 cn 的即可。
