### ISSUE TITLE
翻译发音语速可以设置？

### ISSUE THREAD

**Issue by angelpray** [crimx/ext-saladict#923]
## 设备信息
- 操作系统: [win10] 
- 浏览器版本: [76.0.] 
- 沙拉查词版本: [v7.14.5] 

## 请描述目前使用沙拉查词遇到什么不便

我想设置英文翻译模式下，因为当前划词翻译的发音速度有点快了，导致现在听听英文句子朗读都成问题了。完全听不懂啊，亲😪😪😪。

## 理想情况下，沙拉查词应该怎么做

希望能调整设置发音速度，这对想学英文，听英文的用户会很友好。👏👏

## 替代方案

无

## 额外信息

无

**Comment by crimx** [comment]
[使用说明](https://saladict.crimx.com/manual.html#audio)
