### ISSUE TITLE
记得以前的版本中，面板内查词是能单独悬浮出一个查词窗口的

### ISSUE THREAD

**Issue by li0817** [crimx/ext-saladict#924]
## 设备信息
- 操作系统: [Windows 10 OS Version 1909 (Build 18363.959)] 
- 浏览器版本: [Chrome/81.0.4044.142] 
- 沙拉查词版本: [v7.14.5] 

## 请描述目前使用沙拉查词遇到什么不便
不知道是不是BUG，还是已经去掉了这个功能，难受挺久了，忍不住了就来问问
我清楚记得，以前的版本中，如果在查词面板中查词，会出现一个新的面板，相当于新打开了一个标签页，而不是在原标签页打开

我查词不是看个意思就完了，还得看例句看用法，该需求应用环境大概是这样的：
假设，查生词A，看例句，发现例句中有生词，查例句中的生词2，发现其下例句中又有生词，查生词3，以此类推……可是生词A的例句还没看完呢，有时候得按好几回后退键，还会出现生词A下有例句1、例句2、例句3，三句都想查生词的情况，结果根据例句1一路往后查，查到后面，就算后退回来，也忘了最初的生词A下面看到的例句2例句3是哪个了，又要重新翻找……所以希望能出现个新的面板而不覆盖之前的查词结果

目前是会覆盖掉原来的查词结果，仅一个查词面板
![77e1a8b6-a76e-4943-bf45-aa3710275359](https://user-images.githubusercontent.com/27659768/88197260-ca44ca80-cc74-11ea-8fb1-84b81a36ebed.gif)
我翻遍了设置查看了文档也搜了issue，无果_(:з」∠)_

## 理想情况下，沙拉查词应该怎么做
在面板内部查词时，希望能新悬浮出一个额外查词的面板，同时存在复数面板

**Comment by crimx** [comment]
> 我清楚记得，以前的版本中，如果在查词面板中查词，会出现一个新的面板，相当于新打开了一个标签页

你应该清楚地记错了哈哈。

> 在面板内部查词时，希望能新悬浮出一个额外查词的面板，同时存在复数面板

多个查词面板管理会导致十分复杂的逻辑问题。有空我会看看能不能实现在返回的时候保留完整浏览位置。

**Comment by li0817** [comment]
> > 我清楚记得，以前的版本中，如果在查词面板中查词，会出现一个新的面板，相当于新打开了一个标签页
> 
> 你应该清楚地记错了哈哈。
> 
> > 在面板内部查词时，希望能新悬浮出一个额外查词的面板，同时存在复数面板
> 
> 多个查词面板管理会导致十分复杂的逻辑问题。有空我会看看能不能实现在返回的时候保留完整浏览位置。

不是吧……记错了吗。。那可能是以前的浏览器版本BUG……？我印象中确实有复数面板存在过_(:з」∠)_
