### ISSUE TITLE
在查词习惯中关闭普通查词选项中的直接搜索和双击搜索，打开alt键搜索，但是仍然不起作用

### ISSUE THREAD

**Issue by bio-er** [crimx/ext-saladict#926]
## 设备信息
- 操作系统: [win10 1909] 
- 浏览器版本: [new edge 84.0] 
- 沙拉查词版本: [7.14.5] 

## 描述问题

【补充：有时会正常，但偶尔会出现不正常现象】
不正常现象为：在查词习惯中关闭普通查词选项中的直接搜索和双击搜索，打开alt键搜索，但是设置保存后，在页面划词或双击后仍然自动弹出翻译面板。

## 复现步骤

1. 打开http://language.chinadaily.com.cn/a/202007/24/WS5f1a2e86a31083481725bc10.html
2. 选择第一段
3.问题出现：选择段落后，立马自动弹出翻译窗口，而根据预期设置效果，应该是按住alt键后选择第一段，才出现翻译面板。

## 期待的正常行为

应该是在按住alt键后选择第一段，才出现翻译面板，而不是双击选择或划词后立马出现翻译面板。

## 截图

http://mmbiz.qpic.cn/mmbiz_jpg/luzibN2KHyo9x5jxZ4TibGJIL2ozHjAJqKa5yB5hYjLtRXHu04k3sWQRuBZ7VIIrSIdoO2xwPz3ib2m3CnPicR3L2g/0

## 额外信息

【非必要】能否在独立窗口中支持双击ctrl打开翻译面板？
即：浏览器最小化（而不是退出）打开word文档后，双击CTRL键即可打开面板。【目前可用"在独立窗口中搜索剪贴板内容"这个快捷键实现，不知道能否和在浏览器里一样用双击CTRL键实现？】
目前设置如图：http://mmbiz.qpic.cn/mmbiz_jpg/luzibN2KHyo9x5jxZ4TibGJIL2ozHjAJqK7jUPSanqjHoicwWicKibAYAY0LJpiboqfJOricpiaJnwPsBcibdEicqpcDqRuQ/0

**Comment by crimx** [comment]
你好，无法复现这个问题。

**Comment by crimx** [comment]
- 请补充完整系统环境信息。
- 普通查词的设置可以截图一下。
- 这个问题是出现在特殊网页还是所有页面都如此。

**Comment by bio-er** [comment]
> * 请补充完整系统环境信息。
> * 普通查词的设置可以截图一下。
> * 这个问题是出现在特殊网页还是所有页面都如此。

已补充

**Comment by crimx** [comment]
按步骤走了一遍依然没有复现这个问题。你是否额外设置了其它插件触发了快捷键？

> 能否在独立窗口中支持双击ctrl打开翻译面板？

你可以看看 Quicker 等工具让 双击 ctrl 触发沙拉查词的全局快捷键。

**Comment by bio-er** [comment]
> 按步骤走了一遍依然没有复现这个问题。你是否额外设置了其它插件触发了快捷键？
> 
> > 能否在独立窗口中支持双击ctrl打开翻译面板？
> 
> 你可以看看 Quicker 等工具让 双击 ctrl 触发沙拉查词的全局快捷键。

刚才使用时注意到了。如果已经打开了独立窗口，那么在浏览器中不管是怎么设置的，只要在浏览器里双击或者划词选择，就会自动弹出翻译面板，而如果关闭独立窗口页面，情况就会正常，划词后就不会自动弹出翻译面板。

**Comment by crimx** [comment]
那个是在「快捷查词」，「独立窗口」中设置。
