### ISSUE TITLE
剪贴板内无内容时通过三次ctrl键呼出的面板没有获取焦点

### ISSUE THREAD

**Issue by Sraw** [crimx/ext-saladict#927]
如标题，当剪贴板内没有内容时，三次ctrl键呼出的面板没有自动获取焦点。

已经在设置中开启了“出现时获取焦点”。

OS: Linux Mint 20
Chrome: 84.0.4147.89
Extension: 7.14.5

**Comment by crimx** [comment]
你好，无法复现这个问题。快捷查词设置可以截图一下。

**Comment by Sraw** [comment]
FYI

![image](https://user-images.githubusercontent.com/15711730/88352313-2e679d00-cd0e-11ea-850f-66326a9ec9c4.png)
