### ISSUE TITLE
chrome 中放大或缩小页面时会跳出弹窗 

### ISSUE THREAD

**Issue by ariesfans** [crimx/ext-saladict#928]
因为常使用笔记本触摸板这个弹窗误弹出频率还挺高，希望页面放大缩小时能别跳出沙拉弹窗

**Comment by crimx** [comment]
请按模板填写，提供复现问题的步骤。

**Comment by ariesfans** [comment]
就从笔记本触控板 双指开合 操作（放大或缩小页面）就会弹窗了 &nbsp;我用的是win10&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CRIMX <notifications@github.com&gt;
发送时间: 2020年7月24日 08:17
收件人: crimx/ext-saladict <ext-saladict@noreply.github.com&gt;
抄送: howsopen <402963902@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[crimx/ext-saladict] chrome 中放大或缩小页面时会跳出弹窗  (#928)





 
请按模板填写，提供复现问题的步骤。

**Comment by crimx** [comment]
这应该是这个触控板操作触发了某种按键组合。你的划词模式设置是如何的？如说不清楚可以提供「查词习惯」的截图。

**Comment by ariesfans** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "crimx/ext-saladict"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月24日(星期五) 中午1:30
收件人:&nbsp;"crimx/ext-saladict"<ext-saladict@noreply.github.com&gt;;
抄送:&nbsp;"白羽"<402963902@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [crimx/ext-saladict] chrome 中放大或缩小页面时会跳出弹窗  (#928)





 
这应该是这个触控板操作触发了某种按键组合。你的划词模式设置是如何的？如说不清楚可以提供「查词习惯」的截图。

**Comment by ariesfans** [comment]
图片已发您邮箱 ，弹窗后样式如图，且手动关闭沙拉弹窗后 , 浏览器窗口也由全屏变成弹窗后的尺寸

**Comment by crimx** [comment]
没有收到邮件。把图片拖到这里也可以上传。

**Comment by ariesfans** [comment]
![a39ec85a977ee8b2554377e1e240e3cd](https://user-images.githubusercontent.com/25166561/88638584-43697500-d0ee-11ea-889d-aca19b043dfa.png)
![4298e921bc12a96d4661e4172f7ecc72](https://user-images.githubusercontent.com/25166561/88638605-49f7ec80-d0ee-11ea-949c-8becc1f319c1.png)

**Comment by crimx** [comment]
这里看不出什么问题。不清楚你的触控版配置，你可以尝试关闭「快捷查词」「启用 Ctrl 快捷键」，以及[全局快捷键](https://saladict.crimx.com/manual.html#shortcuts)。

**Comment by ariesfans** [comment]
这个是bug  我正常划词弹出的是悬浮在页面之上的小窗口；而这个触控板缩放弹出的是满屏高度的窗口，且z-index与页面是同等级的，相当影响体验呢

**Comment by crimx** [comment]
> 而这个触控板缩放弹出的是满屏高度的窗口

这是因为触发了独立窗口的快捷查词面板。而能够触发这个面板只能是「启用 Ctrl 快捷键」或者通过「[快捷键](https://saladict.crimx.com/manual.html#shortcuts)」。你可以自行排除测试是哪个被触发了。

**Comment by ariesfans** [comment]
是我的设置问题 ，关闭了 启用ctrl快捷键和独立窗口后 都正常了  多谢！
