### ISSUE TITLE
快捷查词窗口没有拦截快捷键

### ISSUE THREAD

**Issue by Sraw** [crimx/ext-saladict#929]
## 设备信息
OS: Linux Mint 20
Chrome: 84.0.4147.89
Extension: 7.14.5

## 描述问题

譬如在Github页面查词，由于Github捕获快捷键s(search)，因此查词就无法输入这个字母，要么到别的窗口去查，要么就只能复制过来。
再譬如outlook页面会捕获n快捷键。

## 复现步骤

理论上来讲如下：
1. 打开github页面（需要含有左上角的Search or jump to...）
2. 三次ctrl呼出查词界面
3. 尝试输入字母s
4. 焦点会弹到左上角的搜索框中

## 期待的正常行为

呼出的界面能拦截网页快捷键，放一些系统级快捷键过去，譬如esc作为退出。否则在这些特殊页面上，查词功能实际上就是无法使用。

## 额外信息

Edit: 这个问题似乎有些难复现，我再研究一下。
Edit2: 在Github页面中较难复现，但在outlook页面中非常容易复现。无论怎么查词，只要按下n就会变成new email。

**Comment by crimx** [comment]
这个跟 #927 是不是同个问题？

**Comment by Sraw** [comment]
你好，似乎不是同一个问题。至少在outlook的页面中，即使已经获取了焦点，按下n还是会跳转到new email页面并且焦点也跳转了。
Github页面下偶尔也会有同样的情况发生，不过不能稳定复现。
使用中文输入法似乎不会触发这个问题（显然的，按键被输入法捕获了）。

**Comment by crimx** [comment]
outlook 似乎在根元素强制了按键监听，要兼容可能需要对它的页面提供特殊支持，因为我不用 outlook 所以可能要等其他人来捣腾了。

这个影响一般不大，你也可以按三下 ctrl 打开独立窗口查词面板。

**Comment by Sraw** [comment]
好的，太麻烦就算了，另外其他页面上偶尔也会出现这个问题，不知道是不是和某些加载顺序有关系。如果碰巧能找到复现的方法再来反馈。
