### ISSUE TITLE
希望悬浮框可以根据内容多少而自适应大小（高度）

### ISSUE THREAD

**Issue by zishuangzhu** [crimx/ext-saladict#93]
- 当翻译后的内容比较少时，设置的默认框有很大了

- 当翻译后的内容有很多，那么就要鼠标点击 **向下** 的标识，然后才能鼠标滚珠下滑，感觉不太方便。

所以希望悬浮框可以根据翻译后的内容多少自适应大小（高度）

**Comment by crimx** [comment]
？本身就是自适应的，设置里可以调整每个词典的默认高度，不喜欢展开可以把数值调大些

**Comment by crimx** [comment]
emmm 这个可能是只有一个词典时的问题，我再看看

**Comment by zishuangzhu** [comment]
![image](https://user-images.githubusercontent.com/26537432/38660831-48751e18-3e61-11e8-9251-7cc8842a9bd5.png)

当有两个词典时，也不是自适应的。
比如上图，谷歌翻译时 内容很少，所以占用很少空间；必应词典翻译后内容很多，但高度依旧是事先设定的固定高度，并没有自适应。而且下面还有空白

**Comment by hentaicreep** [comment]
![image](https://user-images.githubusercontent.com/1901634/39347953-b522c994-4a27-11e8-8735-2925b71a48da.png)
我的也不能自适应内容大小，环境是win10 chrome66，还有个意见就是翻译出来的字体大小能不能改成可配置的，默认的太小了，看着眼睛累

**Comment by crimx** [comment]
@hentaicreep 已经实现了，等下个大版本

**Comment by crimx** [comment]
[新版](https://github.com/crimx/ext-saladict/wiki/Saladict6)已修复，如有问题欢迎开新 issue 反馈。
