### ISSUE TITLE
WebDAV同步单词到坚果云时无法同步到某个文件夹内

### ISSUE THREAD

**Issue by wenlzhang** [crimx/ext-saladict#930]
利用坚果云WebDAV同步单词时，当前似乎需要将单词同步到坚果云根目录下的Saladict文件夹内？这样设置时，点击”验证服务器“和”保存“时都可以正常进行。

但是，当想把单词保存到坚果云的另外一个文件夹内，比如`Data/Saladict`中时却无法设置成功。具体来说，点击”验证服务器“时，单词本可以上传到坚果云的对应文件夹中，坚果云也会提示同步成功。但是，点击”保存“设置时，却无法成功，而提示”服务器上缺少Saladict目录“。自己尝试创建了`Data/Saladict`文件夹，但仍然无法保存设置。

**Comment by crimx** [comment]
你好，目前不支持自定义目录，未来有时间可能会实现。

**Comment by laerhu** [comment]
之前放在坚果云1级目录下可用，今天改到2级目录时出现了上述问题，而且不能复原了 : ( 。好奇是撤回了这个功能吗？
![image](https://user-images.githubusercontent.com/26965450/105020553-63b53380-5a82-11eb-9e71-45f98509522e.png)

**Comment by crimx** [comment]
目前还是不支持自定义目录。你先备份好文件，再尝试放回原来的目录试试。
