### ISSUE TITLE
同步到扇贝报错

### ISSUE THREAD

**Issue by lm0xfffe** [crimx/ext-saladict#932]
## 设备信息
- 操作系统:  [Window10]
- 浏览器版本: [Microsoft Edge  84.0.522.40]
- 沙拉查词版本: [v7.14.5]

## 描述问题
扇贝同步所有生词本单词的时候, 发送请求消息时,如果遇到一个在扇贝里面找不到的单词:
GET https://apiv3.shanbay.com/abc/words/senses?vocabulary_content=reassembly
会返回404, 响应内容{"msg":"Word not found","errors":{}}. 程序代码判断有误,导致异常.程序终止.

## 期待的正常行为
如果遇到某一个单词同步错误,给出提示,然后直接跳过并进行下一个单词的同步. 保证所有正确的单词能够同步完成.

## 截图
![11.png](https://i.loli.net/2020/07/27/PJcGKZzjEH7WdSf.png)
![22.png](https://i.loli.net/2020/07/27/nktqlpYzQ62WMmN.png)
![44.png](https://i.loli.net/2020/07/27/vkUz6DA1tR5sGCL.png)

## 额外信息

if(error !== 'word')  ==> if(error !== 'Error word')  ???

**Comment by crimx** [comment]
感谢反馈。这应该是新的 API 没有适配好。
