### ISSUE TITLE
刮词包含斜杠问题

### ISSUE THREAD

**Issue by Bincker1973** [crimx/ext-saladict#935]
## 设备信息
- 操作系统: [18.04.1-Ubuntu] 
- 浏览器版本: [FireFox 78.0.2 (64 位)] 
- 沙拉查词版本: [v7.14.5] 

## 描述问题

刮词同时包含空格和斜杠且斜杠后只有一个词时，有道翻译只会查出斜杠后面的词，必应等词典直接查不出
如：various repositories/resources
但如果斜杠后包含了空格则必应没有问题，有道错乱
如：various repositories/resources and

## 复现步骤

直接刮词：various repositories/resources

## 期待的正常行为

翻译出全文

**Comment by crimx** [comment]
感谢反馈

**Comment by crimx** [comment]
`various repositories/resources` 不存在这样的单词，故[有道](https://dict.youdao.com/w/various%20repositories%2Fresources)和[必应](https://cn.bing.com/dict/search?q=various%20repositories%2Fresources)没有结果是符合预期的。句子请看机器翻译。

**Comment by Bincker1973** [comment]
可是如果你程序只支持刮词好说，但你程序本身就支持整句翻译的啊。既然支持了整句翻译，然而又出现这种特例是不是有些说不过去？

**Comment by crimx** [comment]
沙拉查词提供的是第三方词典的结果，其中有道词典与必应词典不支持句子翻译，你可以打开前面提供的链接自行查词查看有无结果。既然上游不支持，沙拉查词从何处变出结果？

另外它们的名字叫「词典」，不支持句子翻译也是符合预期。每个词典各有千秋，所以沙拉查词才会提供多个来源供对比。

**Comment by Bincker1973** [comment]
好吧，既然是API的问题那我无话可说， 我原本以为是调用API时的编码问题。
