### ISSUE TITLE
搜狗翻译在cent浏览器中反应迟缓甚至无法工作

### ISSUE THREAD

**Issue by rxnwin** [crimx/ext-saladict#936]
cent浏览器是基于Chromium的一款浏览器，但使用沙拉很正常但搜狗翻译却十分缓慢，（已经用了自己的密钥）也不知道是谁的问题。希望作者能指点一下。顺便问下是否有开发独立版本的计划。谢谢

**Comment by crimx** [comment]
> 使用沙拉很正常但搜狗翻译却十分缓慢，（已经用了自己的密钥）也不知道是谁的问题

很可能是被搜狗识别为机器人了，我也搞不清楚它们的规则。你可以打开 http://fanyi.sogou.com/ 看看有没有要输入验证码。

> 顺便问下是否有开发独立版本的计划

请阅读[常见问题及答复](https://saladict.crimx.com/q&a.html)。
