### ISSUE TITLE
支持划词的时候隐藏图标，通过右键打开翻译

### ISSUE THREAD

**Issue by tjx666** [crimx/ext-saladict#938]
## 请描述目前使用沙拉查词遇到什么不便

我是一个有点洁癖的极简主义者，看文章的时候回没事就划划词，但是我并不想看到沙拉查词的图标。

## 理想情况下，沙拉查词应该怎么做

提供一个设置：`划词时不显示图标`，可以通过快捷键打开对当前选中的词的翻译，右键菜单支持翻译当前选中的词。

**Comment by crimx** [comment]
有点洁癖的极简主义者你好，反馈前先看看沙拉查词的设置会更加简洁。沙拉查词也有[使用说明](https://saladict.crimx.com/manual.html)。

简单来说(pun intended)，在沙拉查词设置中，查词习惯中关闭划词图标，右键菜单中添加沙拉查词面板。

**Comment by crimx** [comment]
补充：快捷键见使用说明。

**Comment by tjx666** [comment]
感谢回复，可以考虑加到常见问题中，因为我翻了常见问题里面没有这个
