### ISSUE TITLE
cambridge词典无法正确显示图片

### ISSUE THREAD

**Issue by PipsqueakH** [crimx/ext-saladict#939]
## 设备信息
- 操作系统: [macos 10.13] 
- 浏览器版本: [chrome84] 
- 沙拉查词版本: [v7.14.5] 

## cambridge词典无法正确显示图片

cambridge某些词条中是有图片的，无法显示。

## 复现步骤

例如lion一词在实际的cambridge词典中是有一张狮子图片的

![cambridge-lion](https://user-images.githubusercontent.com/13641935/89034442-87b57900-d36b-11ea-9a1f-93de2ab391f6.png)

但是沙拉查词就无法显示该图片。

![沙拉查词-lion](https://user-images.githubusercontent.com/13641935/89034462-93a13b00-d36b-11ea-9a84-cefbd8540a3b.png)

可以看到图片下方的文字Benedetta Barbanti/EyeEm/GettyImages是显示的，但是图片信息没有显示。

**Comment by crimx** [comment]
感谢反馈
