### ISSUE TITLE
期待：快速关闭界面

### ISSUE THREAD

**Issue by jjkmaze** [crimx/ext-saladict#94]
CCC可以快速开启界面，一直保留界面可能会遮住某些内容，但是关闭需要移动到界面，希望作者可以添加快速关闭界面的功能

**Comment by crimx** [comment]
嗯，用 esc 键关闭如何。

**Comment by alexya** [comment]
@jjkmaze 咋快速开启界面？我咋不知道还有这功能？是按“CCC”么？

**Comment by crimx** [comment]
@alexya 按三次 ctrl，所有功能在 wiki 有说明

**Comment by crimx** [comment]
[新版](https://github.com/crimx/ext-saladict/wiki/Saladict6)已添加，如有问题欢迎开新 issue 反馈。
