### ISSUE TITLE
cambridge词组无法正常显示

### ISSUE THREAD

**Issue by PipsqueakH** [crimx/ext-saladict#940]
## 设备信息
- 操作系统: [macos 10.13] 
- 浏览器版本: [chrome84] 
- 沙拉查词版本: [v7.14.5] 

## 描述问题
cambridge词典在查询词组的时候有时无法正确显示词组含义，即使词典本身包含了这个词组。
该现象在词典内跳转的时候经常出现。

## 复现步骤

1. 查询单词lion

2. 点击词条信息idioms中的the lion's den.
![Screenshot_20200731_202058](https://user-images.githubusercontent.com/13641935/89035874-3eb2f400-d36e-11ea-9c7e-9a3c352289de.png)

3.无法显示the lion's den的词条信息，但是cambridge词典本身是可以显示的。
![Screenshot_20200731_204337](https://user-images.githubusercontent.com/13641935/89036043-8fc2e800-d36e-11ea-9c9c-18485fe453a4.png)

## 原因
沙拉查词的cambridge词典引擎中使用的查词url是
`https://dictionary.cambridge.org/search/english/direct/?q=${text}`。
而cambridge词典中使用的查词url是
`https://dictionary.cambridge.org/dictionary/english/lion-s-den`

**Comment by crimx** [comment]
这两个 url 效果是一样的，只是这里没有做好兼容，感谢反馈。
