### ISSUE TITLE
"右上弹框"工作异常

### ISSUE THREAD

**Issue by Neutrino0532** [crimx/ext-saladict#942]
## 设备信息
- 操作系统: [] windows10
- 浏览器版本: [] Vivaldi 3.1.1929.48 (Chrome/83.0.4103.122)
- 沙拉查词版本: [] 7.14.5

## 描述问题

点击地址栏旁边的拓展图标时, 同时弹出查词面板和设置页面, 尽管右上弹框选项中, 设置点击地址栏图标的行为应该为"弹出查词面板"

## 复现步骤

设置"右上弹框"中点击地址栏旁图标的行为为显示查词面板, 保存后点击图标, 打开查词面板的同时, 也打开了设置页面
设置为"打开快捷查词独立窗口"后, 新窗口为设置页面, 而原窗口查词面板出出现白条(见截图)

## 期待的正常行为

只显示查词面板, 不弹出设置页面(就像以前一样)
独立窗口正常运行

## 截图

![image](https://user-images.githubusercontent.com/35738016/89132147-8ab79180-d544-11ea-9be5-8affeca395d1.png)

## 额外信息

换电脑后重新安装浏览器和沙拉查词, 出现问题

**Comment by crimx** [comment]
关掉右上弹框预加载剪贴板，或者给权限。
