### ISSUE TITLE
cambridge词典无法发音

### ISSUE THREAD

**Issue by PipsqueakH** [crimx/ext-saladict#943]
## 设备信息
- 操作系统: [mac0s10.13] 
- 浏览器版本: [chrome84] 
- 沙拉查词版本: [v7.14.5] 

## cambridge词典无法发音

个别单词的个别选项的播放图标显示Your browser doesn't support HTML5 audio

## 复现步骤

例如单词coup

## 截图

![屏幕快照 2020-08-04 下午4 45 19](https://user-images.githubusercontent.com/13641935/89274859-14b24800-d674-11ea-8017-e9916493ead3.jpg)

**Comment by crimx** [comment]
感谢反馈
