### ISSUE TITLE
建议添加DEEPL翻译

### ISSUE THREAD

**Issue by CCCCCCCCCC333** [crimx/ext-saladict#945]
## 词典名称以及链接

https://www.deepl.com/translator

## 沙拉查词的已有的词典为什么不能满足？

事实上，我注意到deepl的翻译十分强大，在各方面都超越了谷歌和百度，强烈建议加入
案例一
高考作文原文：现代社会以海德格尔的一句“一切实践传统都已经瓦解完了”为嚆矢。滥觞于家庭与社会传统的期望正失去它们的借鉴意义。但面对看似无垠的未来天空，我想循卡尔维诺“树上的男爵”的生活好过过早地振翮。

深度学习中译英：Modern society has taken as its guiding principle Heidegger's phrase that "all practical traditions have broken down". Expectations, perpetuated by family and social traditions, are losing their relevance. But in the face of the seemingly endless sky of the future, I think it is better to live the life of Calvino's "baron on a tree" than to prematurely turn the wheels.

深度学习英译中：现代社会把海德格尔的一句话作为指导原则，即 "所有实际的传统都已崩溃"。由家庭和社会传统延续下来的期望，正在失去意义。但面对未来看似无边无际的天空，我想，过着卡尔维诺 "树上男爵 "的生活，总比过早地转动车轮要好。

谷歌：现代社会一直以海德格尔的话说“所有实际的传统都被破坏”作为其指导原则。 由家庭和社会传统所延续的期望正在失去其意义。 但是面对未来看似漫长的天空，我认为过早地转动轮子比过卡尔维诺的“树上的男爵”生活更好。

百度：现代社会以海德格尔的一句话“一切实践的传统都被打破”作为其指导原则。由家庭和社会传统所延续的期望正在失去其现实意义。但面对看似无边无际的未来，我认为与其过早地转动车轮，不如过上卡尔维诺的“树上男爵”的生活。

案例2
原文：
Whether you call it Vote by Mail or Absentee Voting, in Florida the election system is Safe and Secure, Tried and True. Florida’s Voting system has been cleaned up (we defeated Democrats attempts at change), so in Florida I encourage all to request a Ballot & Vote by Mail! #MAGA

DEEPL翻译：无论你叫它 "邮寄投票 "还是 "缺席投票"，在佛罗里达州的选举制度都是安全和可靠的，是经得起考验的。佛罗里达州的投票系统已经被清理干净（我们击败了民主党的改革企图），所以在佛罗里达州，我鼓励所有的人申请选票和邮寄投票。#MAGA

谷歌：无论您称其为“邮寄投票”还是“缺席投票”，在佛罗里达州，选举制度都是“安全有保障”，“尝试过”和“真实”。 佛罗里达州的投票系统已经清理（我们击败了民主党人的变更尝试），因此在佛罗里达州，我鼓励所有人要求通过邮寄方式进行选票和投票！ #MAGA

百度：不管是在佛罗里达州的安全投票系统中，你都可以通过邮件安全地投票。佛罗里达州的投票系统已经清理干净了（我们击败了民主党人的改革尝试），所以在佛罗里达州，我鼓励所有人要求投票和邮寄投票！#玛加

**Comment by crimx** [comment]
Duplicate of #705
