### ISSUE TITLE
划词的弹出图标，周围后黑框。重装插件之后一样出现

### ISSUE THREAD

**Issue by Box-Cube** [crimx/ext-saladict#947]
## 设备信息
- 操作系统: [win10 1909 ]  
- 浏览器版本: [Chrome  84.0.4147.105]   
- 沙拉查词版本: [7.14.5]   

## 描述问题

没升级查词版本之前，是正常的。自动升级之后，划词的弹出图标，周围后黑框。重装插件之后一样出现

## 复现步骤

任意一个划词，都会弹出图标带黑框

## 期待的正常行为

正常情况下，图标不会存在黑框

## 截图

![image](https://user-images.githubusercontent.com/64300761/89516237-c1bec900-d80a-11ea-9139-5de16d22219f.png)

**Comment by crimx** [comment]
> 没升级查词版本之前

之前版本是什么，或者上一次更新是什么时候。

所有网页如此还是特殊网页上出现。

如果在浏览器设置中关闭硬件加速是否依然出现黑框？

**Comment by Box-Cube** [comment]
> > 没升级查词版本之前
> 
> 之前版本是什么，或者上一次更新是什么时候。
> 
> 所有网页如此还是特殊网页上出现。
> 
> 如果在浏览器设置中关闭硬件加速是否依然出现黑框？
一直都是插件自动更新，没有关注过上一个版本是什么。
按理，7.14.5之前一个正式版是什么版本，我的电脑插件就是什么版本。
--------
所有网页都会出现这种情况，关闭硬件加速也还是黑框。

**Comment by crimx** [comment]
> 一直都是插件自动更新，没有关注过上一个版本是什么。

那你说“没升级查词版本之前，是正常的”因为看到沙拉查词已更新的提醒之后马上出现异常还是说仅仅是觉得是扩展更新了？因为 7.14.5 在近一个月前就发布了。

> 所有网页都会出现这种情况，关闭硬件加速也还是黑框。

这样排除了显卡问题。有无安装可以改变页面样式的扩展？如把页面变黑暗模式类的扩展。

**Comment by Box-Cube** [comment]
> > 一直都是插件自动更新，没有关注过上一个版本是什么。
> 
> 那你说“没升级查词版本之前，是正常的”因为看到沙拉查词已更新的提醒之后马上出现异常还是说仅仅是觉得是扩展更新了？因为 7.14.5 在近一个月前就发布了。
> 
------
就是前段时间，浏览器提示了查词插件自动更新成功，然后这段时间就一直有黑框，只不过最近受不了黑框了才来提issues。
------
> > 所有网页都会出现这种情况，关闭硬件加速也还是黑框。
> 
> 这样排除了显卡问题。有无安装可以改变页面样式的扩展？如把页面变黑暗模式类的扩展。
-----
感谢提示，确实是因为一款暗黑插件（Super Dark Mode 4.0.9.2）原因导致，关闭插件后就好了。
不过，这个插件一直是装有的，之前不会和沙拉查词冲突导致黑框。发现最近两者都有自动升级，没有具体关注过是谁升级之后才出现的现象。

**Comment by crimx** [comment]
好的，找到原因就好办。我看看是如何冲突的。
