### ISSUE TITLE
Add Traditional Chinese Support for English Interface

### ISSUE THREAD

**Issue by kysterics** [crimx/ext-saladict#948]
Currently, when the app language is set to English, Saladict by default displays Chinese translations in Simplified Chinese and Simplified Chinese only.

It would be nice to have an option for Traditional Chinese translations while within the English Interface.

**Comment by crimx** [comment]
Why not set the extension language to Traditional Chinese instead.

**Comment by kysterics** [comment]
> Why not set the extension language to Traditional Chinese instead.

It's a matter of customizability, but one could certainly put it as personal preference.

By setting the app language to Traditional Chinese, the whole interface becomes Chinese and this may appear as undesirable to some users. For instance, as a user who mainly looks up words for their English definitions and example sentences, dictionary titles in Chinese is not optimally consistent with English contents. It would not be an issue if this could be fixed using css, but unfortunately I could not find a way to target a specific dictionary title.

![image](https://user-images.githubusercontent.com/63026996/89537266-aa440800-d82b-11ea-87e3-b4f73ee5a6e0.png)

**Comment by crimx** [comment]
> but one could certainly put it as personal preference

It is personal preference.

> this may appear as undesirable to some users

Are you a native English speaker who is learning Chinese?

> It would not be an issue if this could be fixed using css

Unfortunately it is not something as simple as few lines of CSS.

In the upcoming release of Saladict the Cambridge dictionary will support selecting the Traditional Chinese version of it.
