### ISSUE TITLE
不能翻译本地文件

### ISSUE THREAD

**Issue by suiyueranzly** [crimx/ext-saladict#95]
打开本地html文件时，不能进行划词翻译。

**Comment by crimx** [comment]
按照指示勾选了么 https://github.com/crimx/ext-saladict/wiki/Instructions

**Comment by suiyueranzly** [comment]
刚开始勾选了这个，不过不清楚为什么没起作用，现在可以了，可以是没有刷新的原因，谢谢。

**Comment by Aster-snow** [comment]
勾选了但是还是不能打开，昨天打开了一次，今天怎么都打不开了，地址栏不是沙拉查词 开头的而是文件地址

**Comment by crimx** [comment]
- 手动在沙拉查词中打开 PDF 链接： https://saladict.crimx.com/manual.html#pdf
- 如需默认使用沙拉查词浏览 PDF ，在沙拉查词设置「PDF 设置」中开启自动嗅探。

**Comment by Aster-snow** [comment]
谢谢，我之前是可以直接双击打开就可以使用的，但是换了电脑之后，我刚才双击打开之后又选择了在pdf阅读器中打开方可使用，谢谢你的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "crimx/ext-saladict"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月19日(星期六) 下午3:59
收件人:&nbsp;"crimx/ext-saladict"<ext-saladict@noreply.github.com&gt;;
抄送:&nbsp;"我吃了你的巧克力"<3133166408@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [crimx/ext-saladict] 不能翻译本地文件 (#95)





  
手动在沙拉查词中打开 PDF 链接： https://saladict.crimx.com/manual.html#pdf
 
如需默认使用沙拉查词浏览 PDF ，在沙拉查词设置「PDF 设置」中开启自动嗅探。

**Comment by crimx** [comment]
因为后来的版本已经取消默认在沙拉查词中打开 PDF，见 https://saladict.crimx.com/notice.html#%E9%A2%84%E8%AE%BE 。

**Comment by Aster-snow** [comment]
好的，谢谢你们的付出






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "crimx/ext-saladict"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月19日(星期六) 下午4:04
收件人:&nbsp;"crimx/ext-saladict"<ext-saladict@noreply.github.com&gt;;
抄送:&nbsp;"我吃了你的巧克力"<3133166408@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [crimx/ext-saladict] 不能翻译本地文件 (#95)





 
因为后来的版本已经取消默认在沙拉查词中打开 PDF，见 https://saladict.crimx.com/notice.html#%E9%A2%84%E8%AE%BE 。
