### ISSUE TITLE
更改设置后保存错误

### ISSUE THREAD

**Issue by Tomgoodboy** [crimx/ext-saladict#954]
保存时出现“权限background申请失败”

**Comment by Tomgoodboy** [comment]
![E8M3WV@%WM37PRXC4F2Y3P](https://user-images.githubusercontent.com/45429250/89918483-15912f80-dbc8-11ea-8254-a4932c726738.png)

**Comment by crimx** [comment]
Duplicate of #916

**Comment by crimx** [comment]
等 7.15.1 过审

**Comment by Tomgoodboy** [comment]
> 等 7.15.1 过审

十分感谢
