### ISSUE TITLE
全局快捷键无效

### ISSUE THREAD

**Issue by Bonita918** [crimx/ext-saladict#955]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 描述问题

想设置浏览器外划词，设置全局快捷键后发现无法触发（浏览器内外都无法触发）

## 复现步骤

1.设置插件后台运行
2.没有找到设置浏览器保持后台运行的位置
3.独立窗口中搜索剪切板内容快捷键设置全局 cmd+shift+L
4.划词并复制，按下快捷键，无法触发（浏览器内外都试过）

**Comment by crimx** [comment]
> 没有找到设置浏览器保持后台运行的位置

可以参考 https://saladict.crimx.com/native.html ，但这个不影响浏览器内部使用，所以继续看是什么问题。

你没有填写设备信息，从快捷键猜测系统应该是 macOS？浏览器是什么？

可尝试为沙拉查词的其它功能（或其它扩展）设置全局快捷键（如 cmd+shift+K）以进一步排查问题。

**Comment by Bonita918** [comment]
您好！感谢回复～

我的设备是2020的macbook pro
浏览器是谷歌浏览器
快捷键尝试过其他字母组合（也尝试过设置其他操作的快捷键）均无法触发

发自我的 iPhone

**Comment by crimx** [comment]
这样可以排除是扩展的问题了。你可以尝试设置为 ctrl + cmd + L 测试一下。可以的话提供一下快捷键设置界面的截图。

**Comment by Bonita918** [comment]
成功了！设置为ctrl+cmd+l后可以触发，感谢您的指导～😊

**Comment by Bonita918** [comment]
很抱歉，我刚刚想尝试换字母，结果设置之后又无法触发了，改回L之后也没有反应

**Comment by crimx** [comment]
可能是部分快捷键浏览器不支持全局，你可以重启一下试试。

**Comment by Bonita918** [comment]
谢谢，已经设置成功。但浏览器外查词触发快捷键后，会跳转回谷歌浏览器内部出现查词窗口，请问是什么原因呢？

**Comment by crimx** [comment]
> 浏览器外查词触发快捷键后

什么快捷键？

> 会跳转回谷歌浏览器内部出现查词窗口

内部出现查词窗口是指什么？在普通网页中的小查词窗口吗？还是独立窗口？

**Comment by Bonita918** [comment]
在外部查词的时候会跳出当前的窗口。比如说在skim里面查词，查词的窗口会跳转回谷歌浏览器，是独立的窗口

**Comment by crimx** [comment]
这符合预期，沙拉查词运行在浏览器，即便是其它本地的词典应用也是一样，不能植入到其它应用中。
