### ISSUE TITLE
无法保存设置

### ISSUE THREAD

**Issue by thermal-power** [crimx/ext-saladict#956]
## 设备信息
- 操作系统: [Windows 10 2004] 
- 浏览器版本: [Firefox 79.0] 
- 沙拉查词版本: [v7.15.1] 

## 描述问题

保存设置时右上角弹出提示框：
设置保存失败
QuotaExceededError: storage.sync API call exceeded its quota limitations.

**Comment by crimx** [comment]
是偶尔出现还是每次都会出现？火狐 79 对存储同步做了[较大修改](https://blog.mozilla.org/addons/2020/07/09/changes-to-storage-sync-in-firefox-79/)，尚未稳定。

**Comment by thermal-power** [comment]
每次都会，而且现在还发现不能切换情景模式了，同样提示
Error: QuotaExceededError: storage.sync API call exceeded its quota limitations.

**Comment by crimx** [comment]
火狐这个问题已经有人反馈了，从这个错误本身很难判断是频率还是容量超了。你可以先导出沙拉查词设置备份，然后重置沙拉查词设置试试。

**Comment by thermal-power** [comment]
无法重置，点击确定无反应

**Comment by crimx** [comment]
我在 79 上测试了一遍，保存设置没有发现问题。

你可以试试打开 `about:debugging#/runtime/this-firefox` ，然后 `inspect` 沙拉查词，在弹出的 console 下输入 `await browser.storage.sync.clear()`

**Comment by thermal-power** [comment]
666，有效果，现在功能都正常了

**Comment by vejei** [comment]
2021 了，在 Mac 下的 Firefox 里面依然有这个问题

**Comment by luneknight** [comment]
2022用坚果云同步还是会出现这个问题，用@crimx的办法解决了，万分感谢

**Comment by jizf1984** [comment]
**不懂代码，但是@crimx 的方法完美解决我的问题，谢谢！**

**Comment by QLozin** [comment]
2023
一种可能的原因是在使用的网站上拒绝了网站存储cookie权限，在Firefox(CN)里取消例外即可
如为了使用Newbing曾经拒绝cn.bing.com的cookie存储权限
放开权限后使用代码即可恢复
