### ISSUE TITLE
生词本导入功能

### ISSUE THREAD

**Issue by gabkm** [crimx/ext-saladict#958]
## 设备信息
- 操作系统: [Windows 10] 
- 浏览器版本: [Chrome 84] 
- 沙拉查词版本: [v7.14.5] 

## 请描述目前使用沙拉查词遇到什么不便

现有的生词本功能只能导出，无法导入。
如果有的用户将Saladict作为一个长期的学习工具，并存在转换浏览器/设备/备份的问题，在生词的聚合上会显得比较困难，希望能增加本地导入单词的功能。

![no_import_button](https://user-images.githubusercontent.com/60839668/90373092-fd2b8400-e0a3-11ea-83fd-9a2880a30fe1.png)

## 理想情况下，沙拉查词应该怎么做

1. 在导出/导入配置(Import/Export Configs)的时候，允许连同单词本一齐导出、导入。
2. 在单词本页面，新增“导入”的按钮。
3. （额外）在查词面板中，有一个“爱心”样式按钮（左键保存单词到生词本，右键打开生词本）和一个“书签”样式按钮（打开生词本）。“书签”样式按钮就在“爱心”样式按钮右侧，功能却重复，似乎没有实际作用，建议删除以保持界面的整洁。
![useless_button](https://user-images.githubusercontent.com/60839668/90372873-ab82f980-e0a3-11ea-8048-ca0dea1f10e6.png)

## 替代方案

方案1：如果担心导入格式的问题，可以采用比较严格的格式让用户分别导入单词和释义。以Quizlet为例，用户导入单词必须满足以下规则：以Tab区分单词与释义，以Enter区分单词。
![quizlet_import](https://user-images.githubusercontent.com/60839668/90372508-154ed380-e0a3-11ea-8ef7-d401659aa555.jpg)
方案2：只让用户导入单词，不可导入释义。以换行区分单词。

**Comment by crimx** [comment]
感谢你的反馈。

> 如果有的用户将Saladict作为一个长期的学习工具，并存在转换浏览器/设备/备份的问题，在生词的聚合上会显得比较困难，希望能增加本地导入单词的功能。

沙拉查词的生词本不提供导入的目的是因为浏览器本地存储目前依然存在不可靠性，数据可能会被某些系统清理软件误删。所以生词本被设计为连接其它学习工具的桥梁，帮助用户将单词同步到其它学习软件中。

对于浏览器备份的问题，可以设置生词本的 WebDAV 同步。这个方式其实也可以变相用作生词导入。

> “书签”样式按钮就在“爱心”样式按钮右侧，功能却重复，似乎没有实际作用，建议删除以保持界面的整洁。

在实际操作中发现对计算机不是很熟悉的用户容易找不到生词本入口，故保留了生词本图标。当启用查词记录后，这个图标会变成历史记录入口。考虑到一个小图标占的位置有限，就不再额外提供设置隐藏了。

**Comment by gabkm** [comment]
全都明白了。感谢你 : )
