### ISSUE TITLE
Anki制卡失败

### ISSUE THREAD

**Issue by Soon1y** [crimx/ext-saladict#959]
## 设备信息
- 操作系统: [Windows10] 
- 浏览器版本: [Chrome84] 
- 沙拉查词版本: [7.15.1] 

## 描述问题

Anki制卡失败

## 复现步骤

1. 准备工作完成（Anki connect已开启，Anki在后台运行）
2. 打开网址：https://cet4.koolearn.com/20170821/815989.html 选择单词bitterest，沙拉查词弹窗出现后，点击♥，出现制卡界面，点击保存
3. 右下角出现弹窗，保存单词到Anki失败。
4. Anki里显示正在编辑

## 期待的正常行为

制卡正常

## 截图

[Anki connect已开启](http://ww1.sinaimg.cn/large/005GHzkggy1ghty8446uxj30op0m1q3z.jpg)
[显示失败](http://ww1.sinaimg.cn/large/005GHzkggy1ghty83zxpvj30ch03awem.jpg)
[Anki里显示正在编辑](http://ww1.sinaimg.cn/large/005GHzkggy1ghty844spsj30ag055jr9.jpg)

## 额外信息

无

**Comment by crimx** [comment]
有没有修改了 Anki 中沙拉查词的字段？目前不支持自定义字段名 https://saladict.crimx.com/anki.html

**Comment by Soon1y** [comment]
没有呀，用的都是默认的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CRIMX"<notifications@github.com&gt;; 
发送时间: 2020年8月17日(星期一) 晚上6:47
收件人: "crimx/ext-saladict"<ext-saladict@noreply.github.com&gt;; 
抄送: "494299583"<494299583@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [crimx/ext-saladict] Anki制卡失败 (#959)





 
有没有修改了 Anki 中沙拉查词的字段？目前不支持自定义字段名 https://saladict.crimx.com/anki.html

**Comment by crimx** [comment]
哦哦，那不清楚是什么原因。你可以点击“现在恢复”，然后重新保存一遍看看。

**Comment by Soon1y** [comment]
重新试了一下，已经可以使用啦


 
---原始邮件---
发件人: "CRIMX"<notifications@github.com&gt;
发送时间: 2020年8月17日 19:00:41
收件人: "crimx/ext-saladict"<ext-saladict@noreply.github.com&gt;;
抄送: "Soon1y"<494299583@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [crimx/ext-saladict] Anki制卡失败 (#959)




 
哦哦，那不清楚是什么原因。你可以点击“现在恢复”，然后重新保存一遍看看。

**Comment by crimx** [comment]
嗯嗯，应该是 AnkiConnect 与 Anki 通信中断了。
