### ISSUE TITLE
2点建议

### ISSUE THREAD

**Issue by CNHLM** [crimx/ext-saladict#96]
- 平台：Win10  QQ浏览器

- 类型：建议

- 期待：①建议每次点击插件的时候，输入框能自动聚焦，并全选里面的内容，方便打开能直接删除里面
                 的内容；
             ②希望能开发一个简洁的桌面版，有很多翻译软件要么太杂，占用多，要么接口太旧，翻译不准
                 确

**Comment by crimx** [comment]
嗨，谢谢建议！

1. 插件打开时输入框是自动聚焦并自动全选里面内容的
2. 一个人桌面版开发恐怕有心无力了

查看你的扩展是不是最新版的 https://github.com/crimx/ext-saladict/releases

**Comment by CNHLM** [comment]
是 5.31.7版的，每次点插件，都要双击输入框全选。桌面的话，如果会做，有空就做，好东西也不怕多等几年
