### ISSUE TITLE
剑桥字典失去作用

### ISSUE THREAD

**Issue by zzan1** [crimx/ext-saladict#960]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 描述问题

剑桥字典搜索不出结果

## 额外信息

猜测是  剑桥字典的 API 发生了变化吧？

**Comment by crimx** [comment]
Duplicate of #943

**Comment by crimx** [comment]
等 Chrome 商店过审
