### ISSUE TITLE
建议划线的单词少于二个的时候，不显示谷歌、彩云、腾讯翻译君等翻译结果。

### ISSUE THREAD

**Issue by CraKeyBoy** [crimx/ext-saladict#962]
**Is your feature request related to a problem? Please describe.**

一般的词组词典就都可以查询到了，当然，单词的个数可以自定义就更好了，其实我希望是一个的时候不显示其他机器翻译结果。
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by crimx** [comment]
打开各个词典的设置调整字数。

如不清楚如何打开设置见[使用说明](https://saladict.crimx.com/manual.html)。

**Comment by CraKeyBoy** [comment]
好的，感谢
