### ISSUE TITLE
新增右键查词，不是跳转网页的那种

### ISSUE THREAD

**Issue by 496477618** [crimx/ext-saladict#964]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Chrome83] 
- 沙拉查词版本: [v7.15.1] 

## 请描述目前使用沙拉查词遇到什么不便

我不想破坏之前的体验，我想要达到的效果是浏览器携带了翻译器之后对之前的使用不影响，但是每次选词右上角有图标确实影响体验，而我确实去设置中找解决方案，有快捷键的方案等等，但都达不到我想要的效果

## 理想情况下，沙拉查词应该怎么做

我希望有个右键查词的功能，不是跳转网页的那种哦。就是选中某个单词或句子，然后右键查词，就可以出现那个查看翻译的小弹框。

**Comment by 496477618** [comment]
目前个人使用 ALT 快捷键翻译

**Comment by crimx** [comment]
在「设置」「右键菜单」「添加」，选择「沙拉查词」或者「沙拉查词独立窗口」。

**Comment by 496477618** [comment]
已解决，Thanks
