### ISSUE TITLE
浏览器内快捷键打开翻译页面，浏览器会同时打开后台页面。

### ISSUE THREAD

**Issue by LYJ420** [crimx/ext-saladict#965]
## 设备信息
- 操作系统: [win10] 
- 浏览器版本: [chrom84] 
- 沙拉查词版本: [v7.15.1] 

## 描述问题

浏览器用快捷键打开翻译的小页面，但是浏览器同时会弹出来后台，很烦。

## 期待的正常行为

不要同时打开后台页面。

**Comment by crimx** [comment]
什么是「后台页面」？是指设置页面？是不是权限缺失？注意页面内弹出的警告提示。

**Comment by LYJ420** [comment]
> 什么是“后台页面”？是指设置页面？是不是权限缺失？注意页面内部弹出的警告提示。

chrome-extension://cdonnmffkdaoajfknoeeecmchibpmkmg/options.html?menuselected=Permissions&missing_permission=clipboardRead

打开独立查词页面的同时会弹出这个网址，感觉没有必要。没看到有什么警告提示呀？

**Comment by crimx** [comment]
页面中上部会弹出提醒，提示缺失的权限。比如你这里没有给剪贴板读权限，要么关闭快捷查词面板自动加载剪贴板功能，要么提供权限。

**Comment by crimx** [comment]
![image](https://user-images.githubusercontent.com/6882794/91929114-47516e00-ed10-11ea-87c9-ff7b7338384a.png)

**Comment by LYJ420** [comment]
非常感谢回复。  另外页面报错为：共有权限「重新定义」。请赋予权限或关闭相关功能。   这个是什么意思？

**Comment by crimx** [comment]
可以截图么

**Comment by LYJ420** [comment]
> 可以截图么

在您刚才提示要修改权限后，我开启了【权限管理】页面的两个权限开关后问题消失了，想截图发现【权限管理】页面现在两个开关是：读取和写入剪贴板。但是刚才不是这两个开关，我也忘了是哪两个词了。。。

**Comment by crimx** [comment]
😂

**Comment by crimx** [comment]
没事就行，可能记错页面了吧😂。

**Comment by LYJ420** [comment]
> 没事就行，可能记错页面了吧😂。

啊。。不知道。。。再次感谢回复~
