### ISSUE TITLE
一个建议，在界面中添加“上一个单词”的功能

### ISSUE THREAD

**Issue by alexya** [crimx/ext-saladict#97]
- 平台：
Win10 & macosx 10.11.3
Chrome Version 65.0.3325.181 (Official Build) (64-bit)

- 类型：建议

- 期待：
今天突然发现saladict有个功能，查找某个不认识单词时，打开了界面，在英文对照翻译里，又出现不认识的单词，“双击”一下那个单词，saladict就会跳转，翻译这个新的不认识的单词。（很棒）

但是，看完后，我没办法回到上面那个我原先查看的单词翻译内容去了。

希望新版本里，界面上有个功能，返回上一个查看的单词，或者后一个查看单词，好像浏览器“后退”和“前进”那样的。

（不知道我没有描述清楚）

**Comment by crimx** [comment]
嗯，暂时可以用着历史记录查找

**Comment by crimx** [comment]
[新版](https://github.com/crimx/ext-saladict/wiki/Saladict6)已添加，如有问题欢迎开新 issue 反馈。

**Comment by alexya** [comment]
@crimx 大兄弟，新版本6.0里面，这个“上一个单词”功能添加进去了。但是，在saladict显示的英文对照翻译里，“双击”某不认识的英文单词，saladict再次跳转的功能没有了呢.....
