### ISSUE TITLE
设置保存失败QuotaExceededError: storage.sync API call exceeded its quota limitations.

### ISSUE THREAD

**Issue by EvineDeng** [crimx/ext-saladict#970]
## 设备信息
- 操作系统: [windows 10 2004] 
- 浏览器版本: [Firefox 原版（非中国版） 79.0 (64 位) ] 
- 沙拉查词版本: [v7.15.1] 

## 描述问题

在沙拉查词的查词设置页面中，设置任何内容均无法保存，修改任何东西后右上角均弹出以下内容：
`设置保存失败QuotaExceededError: storage.sync API call exceeded its quota limitations.`

## 复现步骤

在查词设置中，设置任何内容均可复现，已经持续很长内容，似乎没有其他人反馈过。

## 期待的正常行为

正常保存。

## 截图

![](https://i.bmp.ovh/imgs/2020/08/2a20547ece379361.png)

**Comment by EvineDeng** [comment]
> Duplicate of #956

好的，没搜索到，不好意思。

**Comment by crimx** [comment]
没事，如果成功解决的话把这个 close 掉就行。
