### ISSUE TITLE
anki connect 无法同步单词

### ISSUE THREAD

**Issue by riverOcea** [crimx/ext-saladict#971]
你好，我在设置中点击【检查Anki connect】按钮，会提示“成功检查 Anki connect” 随后马上提示“network error”。我不清楚是哪里出了问题，沙拉查词中anki connect设置里面我只变更成了“开启”其他未变动。我自己有用ssr代理，所以不清楚会不会影响到

**Comment by Lottea** [comment]
> 你可以关闭代理之后测试一遍。

你好，我和riverOcea一样的问题，关掉代理之后依然无法向Anki同步单词

**Comment by crimx** [comment]
能提供一下截图么？这个“network error”。

**Comment by Lottea** [comment]
有时是“network error"，有时是”添加单词到Anki“失败 。
![image](https://user-images.githubusercontent.com/70458863/91650232-83d25f00-eaaf-11ea-9494-f5f356c00d37.png)
![image](https://user-images.githubusercontent.com/70458863/91650240-9c427980-eaaf-11ea-8366-25ae8772c294.png)

**Comment by crimx** [comment]
这个错误是由 AnkiConnect 传过来的，如果是 Windows 貌似 AnkiConnect 需要允许防火墙，见[说明](https://saladict.crimx.com/anki.html#anki-connect-%E8%87%AA%E5%8A%A8%E5%88%B6%E5%8D%A1)。

**Comment by riverOcea** [comment]
不好意思刚看见回复。我刚才确认了。在沙拉查词设置中保存anki connect 虽然会提示network error，但是添加单词时词库是可以成功同步的。单开anki，[工具]菜单-选择[管理笔记类型]可以查看每个类型笔记的数量，这时候在网页划词添加到生词本，再打开anki查看数据是增加1的。实际上是没问题，只是无法体现到今天要背的单词中。另外我尝试的时候没有关闭代理也是可以的。
