### ISSUE TITLE
你好 能介绍一下浏览器外划词吗？ 按照文档操作不了。

### ISSUE THREAD

**Issue by lifesomething** [crimx/ext-saladict#973]
第一个问题  浏览器外划词，不太理解。是指在浏览器外，例如打开记事本，里面有英文单词，在记事本里划词，会直接出现解释翻译吗？还是会跳转到chrome浏览器里进行翻译呢？ 

第二个问题：浏览器外划词需不需要配合全局快捷键呢？

第三个问题：win10  企业版的 chrome 不能设置全局快捷键。激活该扩展程序 后面 只有一个 “在chrome中”的灰色选项。 不能选择。  难道是因为win10版本问题吗？ 快捷键设置了 CTRL+L，在外面没有反应。在浏览器内有反应。
复现步骤：
1 沙拉查词设置中开启「后台保持运行」。
2 在 Chrome 设置中搜索 background 或者 后台，
 Continue running background apps when Google Chrome is closed
启动即可。可以看到选项。 已经操作。
3 没有将 Chrome 加入开机启动。直接关闭浏览器进行测试的。

**Comment by crimx** [comment]
见[说明](https://saladict.crimx.com/native.html)。

**Comment by crimx** [comment]
目前是利用剪贴板进行中转，通过设置 Chrome 扩展全局快捷键触发沙拉查词读取剪贴板进行查词，打开的是沙拉查词独立窗口查词面板。配合其它插件可以在划词后自动触发这个流程，原理还是一样。

不需要对「激活该扩展程序」设置快捷键。

**Comment by lifesomething** [comment]
忘记了操作 “前往扩展管理中心为沙拉查词「在独立窗口中搜索剪贴板内容」设置全局快捷键。”这个步骤。 现在可以用快捷键查词了。    这就是浏览器外划词吗？
      请问 浏览器外划词指得是通过剪贴板做中转配合全局快捷键吗？

**Comment by lifesomething** [comment]
忘记了操作 “前往扩展管理中心为沙拉查词「在独立窗口中搜索剪贴板内容」设置全局快捷键。”这个步骤。 现在可以用快捷键查词了。
