### ISSUE TITLE
Chrome下请不要自动打开Saladict更新页面

### ISSUE THREAD

**Issue by c02y** [crimx/ext-saladict#975]
## 设备信息
- 操作系统: [Windows10] 
- 浏览器版本: [Chrome85以及近期多个版本] 
- 沙拉查词版本: [v7.15.1以及近期多个版本] 

## 请描述目前使用沙拉查词遇到什么不便

在Chrome上面使用Saladict的时候经常出现Saladict自动更新并自动打开更新页面标签并跳转到那个标签的情况，然后由于我打开的标签较多，关掉Saladict更新页面标签之后之前正在浏览的标签很难找。

## 理想情况下，沙拉查词应该怎么做

请不要自动打开Saladict更新页面标签，请完全禁止或者弹出小窗口说已更新我们选择打开或者关闭更新信息页面，或者在设置页面给个选项。

貌似Firefox从来没这个问题，Chrome却时不时出现，严重打乱当前的工作。

**Comment by crimx** [comment]
不清楚你说的自动打开更新页面是什么？能否提供截图？或者在历史记录里找到这个页面？

**Comment by c02y** [comment]
额，这个信息没有保存，那下次再次出现的时候我再来补充相关信息

**Comment by crimx** [comment]
嗯，那先 close 了，你可以随时 reopen 这个 issue。

除去初次安装的情况，沙拉查词应该不会在使用过程中自动打开其它页面。

沙拉查词目前是月更，有功能改增删时会通过浏览器通知提示。
