### ISSUE TITLE
生字本 新增手動填寫 生字詞性和解釋的欄位

### ISSUE THREAD

**Issue by vsnst** [crimx/ext-saladict#976]
## 设备信息
- 操作系统: []  Windows 10 
- 浏览器版本: [] Microsoft Edge Version 84.0.522.63 (Official build) (64-bit)
- 沙拉查词版本: []  7.15.1

## 请描述目前使用沙拉查词遇到什么不便

現在SalaDict的生字本，只能在筆記中輸入詞性和其他東西
## 理想情况下，沙拉查词应该怎么做

輸出生字本的時候，會有很多雜亂的東西堆在筆記欄位那裡

## 替代方案

我希望有更多的自訂欄位，我可以自己選擇輸入它的詞性/生字的中英Definition，減少依賴筆記的欄位

## 额外信息

謝謝

**Comment by crimx** [comment]
> 會有很多雜亂的東西堆在筆記欄位那裡

“东西”具体是指什么？

> 可以自己選擇輸入它的詞性/生字的中英Definition

因适配这个功能工作量比较大目前还没有办法实现:grimacing:。

**Comment by vsnst** [comment]
> > 會有很多雜亂的東西堆在筆記欄位那裡
> 
> “东西”具体是指什么？
> 
> > 可以自己選擇輸入它的詞性/生字的中英Definition
> 
> 因适配这个功能工作量比较大目前还没有办法实现😬。

原來這樣，沒關係，現在生字本的功能已經幫助了我許多
我可以先把詞性那些填進現在有的欄位(來源標題, 連結)

東西的意思是，我現在都把 單詞詞性、KK音標、definition、例句一堆有的沒的都塞進了筆記的欄位了😂
![Annotation 2020-08-27 132730-small](https://user-images.githubusercontent.com/36701269/91388261-86dc0e00-e869-11ea-8e12-c476fd6463a7.png)
我幻想手動輸入，然後在輸出文字那邊多幾個「代表內容」的話，應該沒那麼複雜
![Untitled](https://user-images.githubusercontent.com/36701269/91388699-7b3d1700-e86a-11ea-8f77-000682ab0643.png)

**Comment by crimx** [comment]
哦哦，明白你的意思了。我刚才以为是要直接从各个词典中提取出选项供选择。

不清楚你这么做的原因。为什么不希望导出完整的笔记？导出来的用途是做什么？

**Comment by vsnst** [comment]
> 哦哦，明白你的意思了。我刚才以为是要直接从各个词典中提取出选项供选择。
> 
> 不清楚你这么做的原因。为什么不希望导出完整的笔记？导出来的用途是做什么？

原來是我表達不清楚，不好意思

我想導進Excel/其他表格類的軟件，方便查看🤗

**Comment by crimx** [comment]
栏位目前很难修改，因为数据库以及其它与沙拉查词连接的工具需要重新兼容。

但是或许可以通过其它方式兼容。你现在导出文本的格式是什么呢？是否可以通过特定格式写笔记来兼容。

**Comment by vsnst** [comment]
> 栏位目前很难修改，因为数据库以及其它与沙拉查词连接的工具需要重新兼容。
> 
> 但是或许可以通过其它方式兼容。你现在导出文本的格式是什么呢？是否可以通过特定格式写笔记来兼容。

我暫時都是使用saladict生字本原來的輸出功能，txt檔

或者我會，分開%text% 先抓單詞，全部Copy進Excel/OneNote裡面
然後逐個「代表的內容」選出來
![Annotation 2020-08-27 135941](https://user-images.githubusercontent.com/36701269/91395784-96f5ec80-e86d-11ea-8ade-ddc08c80959e.png)

**Comment by crimx** [comment]
你可以了解一下 [CSV](https://zh.wikipedia.org/wiki/%E9%80%97%E5%8F%B7%E5%88%86%E9%9A%94%E5%80%BC) 格式。这样可以直接一次性从 Excel 中导入。

通过「笔记」中以固定数目的逗号分割你想要的栏位，可以在 Excel 自动生成额外栏位。

**Comment by vsnst** [comment]
> 你可以了解一下 [CSV](https://zh.wikipedia.org/wiki/%E9%80%97%E5%8F%B7%E5%88%86%E9%9A%94%E5%80%BC) 格式。这样可以直接一次性从 Excel 中导入。
> 
> 通过「笔记」中以固定数目的逗号分割你想要的栏位，可以在 Excel 自动生成额外栏位。

好，我去了解一下，感謝你👍

**Comment by crimx** [comment]
比如模板

```
%text%,%note%
```

笔记以一个逗号隔开 `verb［ T ］,UK/rɪˈzem.bəl/ US/rɪˈzem.bəl/` 则生成 4 个栏位。

**Comment by vsnst** [comment]
> 比如模板
> 
> ```
> %text%,%note%
> ```
> 
> 笔记以一个逗号隔开 `verb［ T ］,UK/rɪˈzem.bəl/ US/rɪˈzem.bəl/` 则生成 4 个栏位。

我剛試了一試，好像真的很方便，甚至比分開一個一個欄位(Saladict中) 好用
感謝你

那我覺得不需要一開始提出的那個複雜功能好了
可以直接在 「單字管理」設定頁面那邊加一項，自動加入筆記模板的功能，一個輸入框框讓用戶自行輸入
像現在測試用的這個模板
**"Type", "Definition", "Second Meaning", "KK", "Synonyms", "Antonym", "Example"
"詞性", "定義", "其他解釋", "KK音標", "同義詞", "反義詞", "例句"**

![image](https://user-images.githubusercontent.com/36701269/91404713-4c2ba300-e874-11ea-808e-ea537910ca37.png)

這樣弄起來應該沒那麼複雜了

**Comment by crimx** [comment]
这样一个个填入使用上还是比较复杂。我个人还是倾向简洁记录，以后有时间再回过来看看如何设计这个功能。

**Comment by vsnst** [comment]
> 这样一个个填入使用上还是比较复杂。我个人还是倾向简洁记录，以后有时间再回过来看看如何设计这个功能。

請問中文字，CSV輸出會有亂碼有解嗎？

輸出前
![Annotation 2020-08-27 154511-small](https://user-images.githubusercontent.com/36701269/91412525-7bdea900-e87c-11ea-897e-185d66bd90cb.png)
輸出後
![Annotation 2020-08-27 154435-small](https://user-images.githubusercontent.com/36701269/91412536-7e410300-e87c-11ea-87de-e1c031b782dc.png)

**Comment by vsnst** [comment]
亂碼的方面我知道要怎麼解決了，就是不要直接在檔案總管打開
要先打開Excel，再用裡面的開啟功能，它就會自動對應UTB8的格式

**Comment by vsnst** [comment]
另外，最好的方法還是Copy&Paste，格子才會對好
模板如下：

%text%	"Type"	"UKKK"	"USKK"	"Definition"	"Translate"	"Synonyms"	"Antonym"	"Example"
%text%	"Type
Type"	"UKKK"	"USKK"	"Defintion"	"Translate"	"Synonyms"		"Example
ExampleTranslate；
Example
ExampleTranslate
"

**Comment by crimx** [comment]
如果为了避免分割符冲突你也可以用自定义符号如反引号 `` ` `` （<kbd>1</kbd>左边的符号）分割，`` %text%`%trans%`%note% ``，导入时选择分割符即可。
