### ISSUE TITLE
必应的双语解释与悬浮图标

### ISSUE THREAD

**Issue by vsume** [crimx/ext-saladict#98]
1.必应词典中对英语单词的英语解释很有帮助，希望能增加；
2.划译时的悬浮图标有点大会遮挡文字，如能减小点，并将图标与悬浮窗的透明度增加些，体验效果应该很棒

**Comment by crimx** [comment]
嗨，谢谢建议。

1. 对词典的增加我是尽可能不重复功能，英语解释推荐用麦克米伦，还有稍后公开的柯林斯。
2. 图标已经避开了当前句子，下版本会增加规则设置对特定页面关闭图标。

**Comment by crimx** [comment]
新版[已发布](https://github.com/crimx/ext-saladict/wiki/Saladict6)，关闭遗留问题页，如有问题欢迎开新 issue 反馈。
