### ISSUE TITLE
可否导出csv或excel格式的生词本，以及改变生词本本地保存目录。

### ISSUE THREAD

**Issue by minshifu** [crimx/ext-saladict#980]
## 设备信息
- 操作系统: []  Win7
- 浏览器版本: []  Firefox 68
- 沙拉查词版本: []  7.15.1

## 请描述目前使用沙拉查词遇到什么不便

（1）目前生词本导出格式比较单一，只能文本格式。
（2）目前生词本无法选择具体保存路径。

## 理想情况下，沙拉查词应该怎么做

（1）可否将生词本导出为excel或csv格式，这样将更加方便查看和整理。
（2）能否让用户自行选择生词本的具体本地保存目录呢？多谢！

**Comment by crimx** [comment]
1. CSV 也是纯文本，导出模板用逗号分值即可。
2. 单词本存在浏览器的数据库中，应该是不能自定义区域。因为安全原因，浏览器不会允许扩展直接访问用户本地文件。你可以尝试用 WebDAV 同步生词本到本地目录中。

**Comment by minshifu** [comment]
非常感谢解答。另外，很多时候所需要的翻译目标语言并非汉语，可否实现对翻译目标语言的自由选择呢？感谢哈！

**Comment by crimx** [comment]
机器翻译中可设置目标语言。如不知道如何打开设置见[使用说明](https://saladict.crimx.com/manual.html)。

**Comment by minshifu** [comment]
好的，另外可否实现多生词本功能？因为在添加生词时候很希望可以按照不同行业，具体工作学习需求等而划分为不同种类。可否允许使用者自定义生成多个生词本，按照不同生词本进行生词的添加和导出，那样会方便很多。目前都在一个生词本里，必须事后再花时间进行具体的归类整理，希望可以免去相应麻烦。再次感谢！

**Comment by crimx** [comment]
这个功能有点复杂，目前还没有时间设计与实现。未来看看能不能加入标签系统。

**Comment by minshifu** [comment]
> 
> 
> 这个功能有点复杂，目前还没有时间设计与实现。未来看看能不能加入标签系统。

你好，我本来想通过同时使用现有的扩展比如“Clippings” 或“InFormEnter+” 来实现类似的添加标签功能，这两个扩展是预先输入经常需要填写的文本，然后通过右键菜单插入。但是有一个问题，就是咱们的扩展不允许插入文本，可否解除相应限制？

**Comment by crimx** [comment]
> 通过同时使用现有的扩展比如“Clippings” 或“InFormEnter+” 来实现类似的添加标签功能

如果能够配合使用的确是非常棒的想法。

> 咱们的扩展不允许插入文本，可否解除相应限制

这具体是什么意思？

**Comment by minshifu** [comment]
> 
> 
>     1. CSV 也是纯文本，导出模板用逗号分值即可。
> 
>     2. 单词本存在浏览器的数据库中，应该是不能自定义区域。因为安全原因，浏览器不会允许扩展直接访问用户本地文件。你可以尝试用 WebDAV 同步生词本到本地目录中。

![图片](https://user-images.githubusercontent.com/5119952/94886296-48a7bf00-04a5-11eb-90e7-4e0eba32f2f5.png)

你好，如上图我主要是想要导出的文本里不同列的内容：Word，Translation，Note等，在xslx或CSV文件里也是按照原来的格式自动分成不同的列，即保持原来的表格样式，请问现在有办法实现么？好像只加逗号并不能实现，比如我现在的导出格式是    %text%,  %trans%, %note%   如果复制按照上面格式所导出的文本到xslx或CSV格式文件里，原来的表格格式就都被破坏了。

**Comment by minshifu** [comment]
> 
> 
> > 通过同时使用现有的扩展比如“Clippings” 或“InFormEnter_+_” 来实现类似的添加标签功能
> 
> 如果能够配合使用的确是非常棒的想法。
> 
> > 咱们的扩展不允许插入文本，可否解除相应限制
> 
> 这具体是什么意思？

用图可能会表达的更清楚。
![图片](https://user-images.githubusercontent.com/5119952/94886819-172ff300-04a7-11eb-8dbb-140743d22588.png)
![图片](https://user-images.githubusercontent.com/5119952/94886823-1eef9780-04a7-11eb-88d0-d6ed5575dcc8.png)

比如 Clippings是一个常用文本预设扩展，通过它可以快捷输入需要反复输入的文本，如图所示。

我也想在咱们的扩展里使用此类扩展，如下图所示，但是所有框里都无法实现文本插入，如果可以实现就可以部分代替tag功能。

![图片](https://user-images.githubusercontent.com/5119952/94886884-58c09e00-04a7-11eb-8338-64d7a5d8b282.png)

**Comment by crimx** [comment]
哦哦，我看看是什么原因。

**Comment by crimx** [comment]
> > 
> > 
> >     1. CSV 也是纯文本，导出模板用逗号分值即可。
> > 
> >     2. 单词本存在浏览器的数据库中，应该是不能自定义区域。因为安全原因，浏览器不会允许扩展直接访问用户本地文件。你可以尝试用 WebDAV 同步生词本到本地目录中。
> 
> ![图片](https://user-images.githubusercontent.com/5119952/94886296-48a7bf00-04a5-11eb-90e7-4e0eba32f2f5.png)
> 
> 你好，如上图我主要是想要导出的文本里不同列的内容：Word，Translation，Note等，在xslx或CSV文件里也是按照原来的格式自动分成不同的列，即保持原来的表格样式，请问现在有办法实现么？好像只加逗号并不能实现，比如我现在的导出格式是    %text%,  %trans%, %note%   如果复制按照上面格式所导出的文本到xslx或CSV格式文件里，原来的表格格式就都被破坏了。
> 

原来有多少个域就保持相应的逗号数目分割，没有内容的区域留空。

**Comment by minshifu** [comment]
> 
> 
> > > ```
> > > 1. CSV 也是纯文本，导出模板用逗号分值即可。
> > > 
> > > 2. 单词本存在浏览器的数据库中，应该是不能自定义区域。因为安全原因，浏览器不会允许扩展直接访问用户本地文件。你可以尝试用 WebDAV 同步生词本到本地目录中。
> > > ```
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/5119952/94886296-48a7bf00-04a5-11eb-90e7-4e0eba32f2f5.png)
> > 你好，如上图我主要是想要导出的文本里不同列的内容：Word，Translation，Note等，在xslx或CSV文件里也是按照原来的格式自动分成不同的列，即保持原来的表格样式，请问现在有办法实现么？好像只加逗号并不能实现，比如我现在的导出格式是    %text%,  %trans%, %note%   如果复制按照上面格式所导出的文本到xslx或CSV格式文件里，原来的表格格式就都被破坏了。
> 
> 原来有多少个域就保持相应的逗号数目分割，没有内容的区域留空。

但是如果原先保存的内容就含有很多逗号，那样的话就会多出很多列

**Comment by crimx** [comment]
这种情况你可以尝试 `"%text%","%trans%","%note%"`，如果文本中同样存在双引号你也可以用自定义符号如反引号 `` ` `` （<kbd>1</kbd>左边的符号）分割，`%text%`%trans%`%note%`，导入时选择分割符即可。

**Comment by minshifu** [comment]
> 
> 
> 这种情况你可以尝试 `"%text%","%trans%","%note%"`，如果文本中同样存在双引号你也可以用自定义符号如反引号 `` ` `` （1左边的符号）分割，`` %text%`%trans%`%note% ``，导入时选择分割符即可。

好的，感谢。不知道那个无法插入文本的问题是否有解决方法了呢？

**Comment by crimx** [comment]
> 不知道那个无法插入文本的问题是否有解决方法了呢？

不清楚那个插件用了什么方式插入文本，如果是通过剪贴板应该没有兼容性问题，如果是通过获取文本框元素直接修改值的方式可能是因为不能跨扩展修改元素？具体问题不清楚，你可以向那个插件反馈一下。
