### ISSUE TITLE
有Panel width，但是没有Panel height

### ISSUE THREAD

**Issue by kevin-jing** [crimx/ext-saladict#983]
如题，找不到Panel height，怎么调节窗口高度呢？

**Comment by crimx** [comment]
高度是根据词典数目动态调整，可限制最高的宽度。在宽度设置上一个便是。

**Comment by kevin-jing** [comment]
![image](https://user-images.githubusercontent.com/29517189/91921438-21bb6900-ecfe-11ea-9250-da31f15d3e08.png)
从截图看，显示不完全，需要下拉。如果能增加高度，会方便很多。

**Comment by kevin-jing** [comment]
从上面的截图看，显示不完全，需要下拉。如果能增加高度，会方便很多。

**Comment by crimx** [comment]
浏览器对这个页面的高度有限制，考虑兼容性这个高度是固定的。

**Comment by crimx** [comment]
我开放一个设置给这个高度吧。

**Comment by kevin-jing** [comment]
谢谢！
