### ISSUE TITLE
划词有很多语言不能识别

### ISSUE THREAD

**Issue by mrdobejelly** [crimx/ext-saladict#984]
## 设备信息
- 操作系统: [win10] 
- 浏览器版本: [chrome80] 
- 沙拉查词版本: [7.15.1] 

## 描述问题

页面**划词**取词有很多语言识别不出来，不能取词。比如俄语，阿拉伯语，波斯语，泰语等等。但如果上述语言一句话中间夹杂一些可以识别的语言，却又可以完整地选中整句话。

## 复现步骤

打开上面描述的语言的网站就知道了。
简单的方法，谷歌翻译。在右边的翻译结果框是可以划词的，有什么语言划词取不了一目了然。
举个例子：แนวทาง "Look East"，单独选中前面的泰文应该是触发不了取词器的，加上后面的英语就可以了。

## 期待的正常行为

所有主流语言都能正常划词取词

**Comment by crimx** [comment]
小小语种目前不支持单独识别。如果需存请在设置「查词习惯」「划词语言」中勾选「其它字符」。
