### ISSUE TITLE
更新之后，翻译模式，划词只有Google能显示翻译内容，其他全挂了？？

### ISSUE THREAD

**Issue by wu8320175** [crimx/ext-saladict#989]
win10，edge，沙拉7.16
之前还好好的，昨天更新之后划词就这样了？

![image](https://user-images.githubusercontent.com/24267883/92296006-942c8300-ef62-11ea-975d-06ad7ce6be57.png)

**Comment by crimx** [comment]
感谢反馈

**Comment by PiPiYu** [comment]
我还以为就我一个人挂了，整了一上午

**Comment by anklcaptain** [comment]
一样的问题，还以为我哪里设置出问题了

**Comment by crimx** [comment]
由于环境配置出错导致打包程序出问题，修复已提交，等待审核发布。

**Comment by Eijux** [comment]
有道词典、谷歌翻译能用，其他都不好使

**Comment by JingchengLi** [comment]
同样问题，期待尽快修复。

**Comment by crimx** [comment]
修复昨天已经发布了，等待商店过审后自动更新即可，相同问题不必再反馈。

**Comment by crimx** [comment]
7.16.1 已成功发布。
