### ISSUE TITLE
划词时遇到斜杠 "/" 符号, 就会失效

### ISSUE THREAD

**Issue by hxse** [crimx/ext-saladict#990]
## 设备信息
- 操作系统: [Window10] 
- 浏览器版本: [Chrome 版本 85.0.4183.83（正式版本） （64 位）]
- 沙拉查词版本: [7.16.0]

## 描述问题

划词时遇到斜杠 "/" 符号, 就会失效

## 复现步骤

1. To do this, either add to an existing test in auto_tests tests or create a new one.
2. To do this, either add to an existing test in auto_tests/tests or create a new one.
比如上面两句, 第一句就可以正常划词, 第二句就会失败, 因为第二句里面有个 "/"

## 截图

![image](https://user-images.githubusercontent.com/22582226/92304064-4852fb80-efad-11ea-8467-06840c99d2c7.png)

**Comment by crimx** [comment]
能提供具体的词典对比么。我测试沙拉查词是可以正确查词的，有没有翻译结果由各个词典服务决定。

另外 16.0 目前存在打包错误导致部分机器翻译词典无结果。16.1 已经提交审核。

**Comment by hxse** [comment]
> 能提供具体的词典对比么。我测试沙拉查词是可以正确查词的，有没有翻译结果由各个词典服务决定。
> 
> 另外 16.0 目前存在打包错误导致部分机器翻译词典无结果。16.1 已经提交审核。

已补充截图

**Comment by crimx** [comment]
> 已补充截图

划词已经发送给有道词典，有没有结果由有道词典服务决定。

谷歌翻译应该是正常翻译的，检查划词语言或词典语言识别设置。

![image](https://user-images.githubusercontent.com/6882794/92304172-260dad80-efae-11ea-8476-93dccc604e1e.png)

有道翻译以及其它机器翻译等修复。

**Comment by hxse** [comment]
> > 已补充截图
> 
> 划词已经发送给有道词典，有没有结果由有道词典服务决定。
> 
> 谷歌翻译应该是正常翻译的，检查划词语言或词典语言识别设置。
> 
> ![image](https://user-images.githubusercontent.com/6882794/92304172-260dad80-efae-11ea-8476-93dccc604e1e.png)
> 
> 有道翻译以及其它机器翻译等修复。

![image](https://user-images.githubusercontent.com/22582226/92304205-6cfba300-efae-11ea-96d7-5f32e32749b6.png)
为什么我这里的全都无效了

**Comment by crimx** [comment]
说了机器翻译等待 16.1 修复发布。

**Comment by hxse** [comment]
哦哦, 好的
