### ISSUE TITLE
保存到生词本只显示 Google 翻译的结果，其它翻译源结果不显示！！！

### ISSUE THREAD

**Issue by WengYadong** [crimx/ext-saladict#993]
macOS Catalina 10.15.6
Google Chrome Version 85.0.4183.83 (Official Build) (64-bit)

保存到生词本时，只显示Google翻译的结果，其它翻译源结果不显示。【昨天(2020/09/05) 一切都正常，今天莫名奇妙就不显示其它翻译源的结果了，卸载重新安装，问题依旧存在】

<img width="729" alt="Screen Shot 2020-09-06 at 11 05 49 AM" src="https://user-images.githubusercontent.com/20606477/92317257-6a8e5d00-f031-11ea-9cde-82b1939db24b.png">
<img width="710" alt="Screen Shot 2020-09-06 at 11 05 59 AM" src="https://user-images.githubusercontent.com/20606477/92317260-6e21e400-f031-11ea-851c-3af50d053b7e.png">
<img width="1438" alt="Screen Shot 2020-09-06 at 11 07 38 AM" src="https://user-images.githubusercontent.com/20606477/92317263-711cd480-f031-11ea-8cf1-fb1b950607c0.png">

**Comment by crimx** [comment]
Duplicate of #989
