### ISSUE TITLE
被更新：”检查更新“按钮取消无效

### ISSUE THREAD

**Issue by Eijux** [crimx/ext-saladict#994]
## 设备信息
- 操作系统: [windows10] 
- 浏览器版本: [chrome85.0.4183.83] 
- 沙拉查词版本: [v7.15.1] 

## 描述问题

想要使用的版本为v7.15.1，但是被更新到了v7.16.0，在已经进行”隐私设置->检查更新“设置为取消并保存的情况下，进行了自动更新。
今天在使用.crx安装v7.15.1、被更新到v7.16.0直接重复，三次……

## 截图

更新前：
![沙拉查词](https://user-images.githubusercontent.com/34087861/92331042-25f0d900-f0a6-11ea-902f-09a2aac95995.png)
被更新：
![沙拉查词被更新](https://user-images.githubusercontent.com/34087861/92331048-3903a900-f0a6-11ea-91ca-265d3bc267e9.png)

**Comment by crimx** [comment]
扩展更新由浏览器控制，应该是无法自定义的（除了火狐）。

沙拉查词的检查更新只是为了方便部分无商店的浏览器，以便在新版时提示。
