### ISSUE TITLE
网页内无法翻译英文句子

### ISSUE THREAD

**Issue by ZenanH** [crimx/ext-saladict#995]
## 设备信息
- 操作系统: [Windows 10]
- 浏览器版本: [Chrome 85.0.4183.83] 
- 沙拉查词版本: [v7.16.0]

## 描述问题
浏览器网页和pdf文件均无法翻译整个句子或段落，但以前可以。

## 复现步骤

网页：
![网页](https://user-images.githubusercontent.com/19581645/92340182-f1a00b80-f0eb-11ea-9f6e-e4d7dee6b1fc.png)

pdf文件：
![image](https://user-images.githubusercontent.com/19581645/92340222-16947e80-f0ec-11ea-84b8-912e911c01c9.png)

## 期待的正常行为
我以前用的时候都是可以选定段落翻译的，最近不确定是什么原因导致的

**Comment by crimx** [comment]
Duplicate of #989

**Comment by crimx** [comment]
7.16.1 已成功发布。
