### ISSUE TITLE
版本更新问题

### ISSUE THREAD

**Issue by yisenz** [crimx/ext-saladict#996]
## 设备信息
- 操作系统: [] 
- 浏览器版本: [] 
- 沙拉查词版本: [] 

## 额外信息

你好，由于16.0出现BUG,谷歌商城存在上架延迟问题，因此想尝试手动下载Crx进行更新，但是目前除了火狐商城更新至16.1版本，其他下载方式，如网盘 Crx4网站等等均是16.0 15.1版本，请问可以更新一下这些获取方式的文件版本吗？谢谢！
感谢开发者的贡献！

**Comment by crimx** [comment]
Duplicate of #989

**Comment by crimx** [comment]
发布流程见[官网说明](https://saladict.crimx.com/download.html#%E6%9B%B4%E6%96%B0%E5%8F%91%E5%B8%83%E6%97%B6%E9%97%B4)

**Comment by yisenz** [comment]
你好，非常感谢您的回复。已看完官网说明。因为目前16.0版本出现无法使用的BUG，所以想及时从网盘下载新版本进行使用，但是网盘目前版本为旧版本15.1，请问网盘的版本更新只能在谷歌商城上架新版本之后是吗？
再一次感谢您的回复，等会会对本项目进行捐助，以此表达谢意！

**Comment by yisenz** [comment]
> 发布流程见[官网说明](https://saladict.crimx.com/download.html#%E6%9B%B4%E6%96%B0%E5%8F%91%E5%B8%83%E6%97%B6%E9%97%B4)

你好，非常感谢您的回复。已看完官网说明。因为目前16.0版本出现无法使用的BUG，所以想及时从网盘下载新版本进行使用，但是网盘目前版本为旧版本15.1，请问网盘的版本更新只能在谷歌商城上架新版本之后是吗？
再一次感谢您的回复，等会会对本项目进行捐助，以此表达谢意！

**Comment by crimx** [comment]
是的，很遗憾目前沙拉查词扩展 crx 文件由 Chrome 商店打包签名，Chrome 商店发布后才能提供下载。

**Comment by crimx** [comment]
需要使用机器翻译可以在设置「词典帐号」中用自己的帐号应急。

**Comment by crimx** [comment]
谢谢你的支持！♥️

**Comment by crimx** [comment]
7.16.1 已发布。
