### ISSUE TITLE
pdf阅读器增加注释功能

### ISSUE THREAD

**Issue by yyl1514** [crimx/ext-saladict#998]
希望沙拉查词自带的pdf阅读器可以增加注释功能！
比如添加 注解 打字 下划线 
这样做笔记会方便许多

**Comment by yyl1514** [comment]
因为个人偏爱在自带的阅读器上看pdf

**Comment by crimx** [comment]
https://saladict.crimx.com/q&a.html#%E9%97%AE%EF%BC%9A%E5%8F%AF%E4%B8%8D%E5%8F%AF%E4%BB%A5%E5%A2%9E%E5%8A%A0-pdf-%E9%98%85%E8%AF%BB%E5%99%A8%E5%8A%9F%E8%83%BD%EF%BC%8C%E5%A6%82%E5%81%9A%E7%AC%94%E8%AE%B0%E3%80%81%E5%88%92%E7%BA%BF%E6%A0%87%E8%AE%B0%E3%80%81%E5%A4%9C%E9%97%B4%E6%A8%A1%E5%BC%8F%E7%AD%89%E3%80%82
